### ISSUE TITLE
Deploy to root should be selected by default to keep a consistent user experience with IntelliJ

### ISSUE THREAD

**Issue by Matthew-Dong** [Microsoft/azure-tools-for-java#1001]
When users deploy a project to Web App, the "deploy to root" should be selected by default. 

![image](https://user-images.githubusercontent.com/7653539/30106440-04024f82-932e-11e7-9be7-bd75d7e928ee.png)

**Comment by jdneo** [comment]
@Matthew-Dong We have fixed this issue in the new build.

**Comment by jdneo** [comment]
Hi @bsaby , please help verify this issue, thanks!

**Comment by bsaby** [comment]
Test passed.
Build: dev426
