### ISSUE TITLE
Publish As... commands should not be disabled when not logged it

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#101]
This forces the user to figure out why these commands are disabled, which is very unobvious. Also, the login entry point is not very discoverable. So we should enable the "Publish as..." commands on the context menu, and when they are invoked, then prompt for the login as needed.

**Comment by martinsawicki** [comment]
these should be enabled regardless of sign in state, and just ask for sign in if not signed in

**Comment by vladimir-shcherbakov** [comment]
duplicate: Sign In command should be available from the Azure context menu #102

**Comment by bsaby** [comment]
Test passed in artifacts/azure-toolkit-for-intellij.234.zip
