### ISSUE TITLE
"The request content was invalid and could not be deserialized" when using Run on Web App (Linux)

### ISSUE THREAD

**Issue by jdneo** [Microsoft/azure-tools-for-java#1014]
**Repro step:**
1. Create a web app on linux on Azure Portal
![image](https://user-images.githubusercontent.com/6193897/30266026-9e315de2-9710-11e7-9ce0-9b25d6a3e882.png)

2. In IntelliJ, Using **Run on Web App (Linux)** for the created web app (Linux)
![image](https://user-images.githubusercontent.com/6193897/30266267-5dfd642c-9711-11e7-93ca-fa567dc42ddc.png)

3. Click Run

**Expect:**
The web app (Linux) will be updated

**Result:** 
An error is throwed.

**Error Message:**
The request content was invalid and could not be deserialized: 'Error reading string. Unexpected token: StartObject. Path 'tags.hidden-related:/subscriptions/<subscription-id>/resourcegroups/test-app-api/providers/Microsoft', line 1, position 152.'.

@bsaby 
Please help double check if this issue do exist in our current released plugin, thanks.

**Comment by bsaby** [comment]
Also repro in our current released plugin for Eclispe and IntelliJ

**Eclipse:**
![image](https://user-images.githubusercontent.com/22470312/30306226-9f183d54-97a9-11e7-9409-aec0e2b323da.png)

**IntelliJ:**
![image](https://user-images.githubusercontent.com/22470312/30306304-f9a96bda-97a9-11e7-9994-5ee05caf4ef6.png)

**Comment by jdneo** [comment]
@bsaby Fixed, please help verify this in the new build, thanks.

**Comment by bsaby** [comment]
Test passed.
Build: dev383
