### ISSUE TITLE
[Eclispe][Mac]Redis Cache-> Eclipse will hang up when creating an existing redis

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1028]
1. Input an existing redis name
2. Click OK

Expect:
The Alert dialog box pops up
![image](https://user-images.githubusercontent.com/22470312/30412618-54216336-994b-11e7-8c2c-5910edc8c122.png)
Result:
The create dialog box will stop responding
![image](https://user-images.githubusercontent.com/22470312/30412578-09605ec4-994b-11e7-8853-16f191c34fb0.png)

**Comment by jdneo** [comment]
@bsaby Fixed, please help verify, thanks.

**Comment by songkaiape** [comment]
Fixed.

**Comment by bsaby** [comment]
Build used: dev440
