### ISSUE TITLE
[IntelliJ] Open ACR Explorer-> UI issue 

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1035]
![image](https://user-images.githubusercontent.com/22470312/30583063-70c38eb8-9d58-11e7-9e2a-22120cb32da4.png)

To expand those content:
Admin User Enabled state requires less than 3 seconds
Disabled state requires about 2 to 10 seconds

**Comment by jdneo** [comment]
@bsaby fixed, please help verify, thanks

**Comment by bsaby** [comment]
Test passed.
Build: dev400
