### ISSUE TITLE
NPE when creating key vault for docker host

### ISSUE THREAD

**Issue by jianghaolu** [Microsoft/azure-tools-for-java#104]
<img width="1280" alt="screen shot 2017-02-17 at 11 48 03 am" src="https://cloud.githubusercontent.com/assets/2320445/23080783/ffedbb86-f506-11e6-96da-87ec08850771.png">

**Comment by milismsft** [comment]
No repro...

**Comment by bsaby** [comment]
Not repro, using azure-toolkit-for-intellij.2017.211.04-04-2017.zip.
