### ISSUE TITLE
[Eclipse]ACR Explorer -> The repository next button can not turn to the next page

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1042]
![image](https://user-images.githubusercontent.com/22470312/30678501-3a4898ba-9ec5-11e7-97ff-0bc324d8c2e8.png)

**Comment by jdneo** [comment]
@bsaby Fixed, please help verify it, thanks.

**Comment by bsaby** [comment]
Test passed.
Build used: PR 884
