### ISSUE TITLE
[Eclipse] ACR explorer -> Should have a scrollbar when the repository's current window can't show all repos.

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1043]
It would be better to have a scrollbar if we want to see all list when the repository cureent page can't show all repos.

Result:
![image](https://user-images.githubusercontent.com/22470312/30680169-ba7c5ea8-9ed0-11e7-92e4-3519e2308a81.png)

Expext:
![image](https://user-images.githubusercontent.com/22470312/30680134-88d50198-9ed0-11e7-894b-b3a9ec856d9b.png)

**Comment by jdneo** [comment]
@bsaby Fixed, please help verify, thanks.

**Comment by bsaby** [comment]
Test passed.
Build: dev400
