### ISSUE TITLE
Wrong font in Create Authentication File dialog

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#105]
it looks like Times New Roman is used in some places. The standard UI font should be used consistently everywhere.

**Comment by bsaby** [comment]
Test used latest build:  artifacts/azure-toolkit-for-intellij.225.zip.
The red circle font is not  standard UI font
![image](https://cloud.githubusercontent.com/assets/22470312/23442479/99613a8a-fe63-11e6-8a88-32563b2aa624.png)

**Comment by bsaby** [comment]
Test passed in  artifacts/azure-toolkit-for-intellij.229.zip and issue closed.
