### ISSUE TITLE
Cannot turn off admin on ACR

### ISSUE THREAD

**Issue by adashen** [Microsoft/azure-tools-for-java#1057]
1. Azure explorer -> choose xc32kbabypz6uacr ACR -> show acr explorer
2. Turn off admin
3. got error 

![image](https://user-images.githubusercontent.com/1872137/30791870-5fa0ef42-a1e8-11e7-8bbe-028809c13ca1.png)

**Comment by jdneo** [comment]
@bsaby fixed, please help verify, thanks.

**Comment by bsaby** [comment]
Test passed.
Build: dev420
