### ISSUE TITLE
[ACR explorer] page status wrong, when error happens.

### ISSUE THREAD

**Issue by adashen** [Microsoft/azure-tools-for-java#1059]
1. Turn on /off acr admin
2. error happens.
3. The property status is wrong.
    In eclipse: the progress bar still show and both admin enable/disable button are disabled
    In intelliJ: both enable/disable buttons are disabled

**Comment by adashen** [comment]
Please verified in the latest build for both intelliJ and eclipse

**Comment by bsaby** [comment]
Test passed.
Build: dev408
