### ISSUE TITLE
azureSettings file in WebApps shouldn't be created by default

### ISSUE THREAD

**Issue by kamaljit** [microsoft/azure-tools-for-java#106]
when i create a new WebApp in IntelliJ (after installing the Azure plugin), i notice that azureSettings.xml file is created by default under the .idea folder. i haven't selected anything to do with Azure so far, so why does this get created?

i notice that it does get updated with my subscription id, tenant id, etc after i select to publish to Azure, which is fine. But why are we creating this if i haven't selected to use Azure yet.

**Comment by martinsawicki** [comment]
lower pri, as no harm appears to be done - but this is old legacy that should be eventually cleaned up

**Comment by andxu** [comment]
very trivial

**Comment by andxu** [comment]
The feature will be "deprecate old settings file: azureSettings.xml"
