### ISSUE TITLE
[push to acr] didn't show validation error when image and tag has only the host prefix value

### ISSUE THREAD

**Issue by adashen** [Microsoft/azure-tools-for-java#1060]
1. push image from project or explorer
2. Select acr from acr list. The image tag name field is filled with the host prefix
3. Run
4. Got error: repository and tag is not in good format.

**Comment by jdneo** [comment]
@bsaby fixed, please help verify, thanks.

**Comment by bsaby** [comment]
Test passed.
Build: dev417
