### ISSUE TITLE
[Eclispe]-> No Web.config file for jar type webapp 

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1062]
Open a spring boot project: https://github.com/spring-guides/gs-spring-boot/tree/master/complete 
Right click project and choose Publish as Azure Web App 
New a Web App
After published, the deployed page can not show in web site

**Comment by adashen** [comment]
Please verify on dev build >= 404

**Comment by bsaby** [comment]
Test passed.
Build: dev408
