### ISSUE TITLE
IntelliJ: New debug as configuration, the item is hard to find

### ISSUE THREAD

**Issue by djlan** [Microsoft/azure-tools-for-java#1066]
From: Maxim Lukiyanov 
Sent: September 23, 2017 6:08 PM
To: DJ Lan <djlan@microsoft.com>; Jenny Jiang <jejiang@microsoft.com>; Wei Zhang <zhwe@microsoft.com>; Long Tian <ltian@microsoft.com>
Subject: RE: IntelliJ plugin problem
 
Thanks DJ, I found the problem – it’s just scrolling – I need to scroll down the window. On Mac it’s very non-obvious.
 
Maxim
 

![a](https://user-images.githubusercontent.com/26966861/30823438-005db13e-a1e1-11e7-9357-1b70ea7318de.png)

**Comment by wezhang** [comment]
Fixed by #1123

**Comment by ruoxinCheng** [comment]
Verified it.
