### ISSUE TITLE
[Eclipse] Web App -> Web App can't auto refresh after deployed

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1070]
Right click a project and choose Publish as Azure Web App
New a Web App and publish
After deployed, the Web App node in Azure explorer can not auto refresh

**Comment by bsaby** [comment]
Also repro in v3.0.9 maketplace version

**Comment by jdneo** [comment]
@bsaby fixed, please help verify, thanks.

**Comment by bsaby** [comment]
Test passed.
Build; dev417
