### ISSUE TITLE
The account being accessed does not support http

### ISSUE THREAD

**Issue by terminatur** [microsoft/azure-tools-for-java#1073]
We have configured our storage accounts to require HTTPS (enabled "Secure Transfer Required"), and now when I attempt to submit a Spark job to HDInsights, using the IntelliJ plugin, I receive the following error:

> Exception in thread "main" org.apache.hadoop.fs.azure.AzureException: com.microsoft.azure.storage.StorageException: The account being accessed does not support http. at org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.retrieveMetadata(AzureNativeFileSystemStore.java:2027) at org.apache.hadoop.fs.azure.NativeAzureFileSystem.getAncestor(NativeAzureFileSystem.java:2406) at org.apache.hadoop.fs.azure.NativeAzureFileSystem.mkdirs(NativeAzureFileSystem.java:2433) at org.apache.hadoop.fs.azure.NativeAzureFileSystem.mkdirs(NativeAzureFileSystem.java:2419) at org.apache.hadoop.fs.FileSystem.mkdirs(FileSystem.java:1924) at org.apache.hadoop.fs.FileSystem.mkdirs(FileSystem.java:617) at org.apache.spark.deploy.yarn.Client.prepareLocalResources(Client.scala:441) at org.apache.spark.deploy.yarn.Client.createContainerLaunchContext(Client.scala:895) at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:171) at org.apache.spark.deploy.yarn.Client.run(Client.scala:1231) at org.apache.spark.deploy.yarn.Client$.main(Client.scala:1290) at org.apache.spark.deploy.yarn.Client.main(Client.scala) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:745) at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187) at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212) at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126) at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala) Caused by: com.microsoft.azure.storage.StorageException: The account being accessed does not support http. at com.microsoft.azure.storage.StorageException.translateFromHttpStatus(StorageException.java:175) at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:94) at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:305) at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:175) at com.microsoft.azure.storage.blob.CloudBlobContainer.downloadAttributes(CloudBlobContainer.java:519) at org.apache.hadoop.fs.azure.StorageInterfaceImpl$CloudBlobContainerWrapperImpl.downloadAttributes(StorageInterfaceImpl.java:237) at org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.checkContainer(AzureNativeFileSystemStore.java:1199) at org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.retrieveMetadata(AzureNativeFileSystemStore.java:1949) ... 20 more

Can be this be configured somewhere, or do we have to disable "Secure Transfer Required"?

**Comment by terminatur** [comment]
We have done some testing, and this is because the IntelliJ plugin, only uploads jars to the storage account using wasb (which uses http) instead of wasbs (which uses https)

**Comment by Nyoiks** [comment]
@terminatur Thanks a lot. You saved me a lot of research time.

**Comment by AnilPavanK** [comment]
Thanks @terminatur..

**Comment by t-rufang** [comment]
Feel free to reopen if you still encounter this issue.
