### ISSUE TITLE
[IntelliJ] Wrong icon for Docker run configuration

### ISSUE THREAD

**Issue by lenala** [Microsoft/azure-tools-for-java#1074]
Steps to repro:
1.Open web application
2.Select Azure->Add Docker support
3.Select Azure->Docker run
Run configuration that gets added has wrong icon, expected to see docker icon same as for 'Docker run' menu item
![image](https://user-images.githubusercontent.com/6208231/30938257-534540d4-a38e-11e7-8ccb-4b918d4afff6.png)
 Same for Edit configurations -> Add new configuration:
![image](https://user-images.githubusercontent.com/6208231/30938439-de7c04ee-a38e-11e7-8dfd-299b2127a452.png)

**Comment by bsaby** [comment]
Build: Dev414
1. icons for project explorer:
![image](https://user-images.githubusercontent.com/22470312/30954068-55ceaf56-a461-11e7-8cf6-bc3b0a96298c.png)

2. Icons for Run/Debug configuration
![image](https://user-images.githubusercontent.com/22470312/30954114-8bde336e-a461-11e7-9417-8e85be0fc5ab.png)

@adashen  Should the **Azure Docker Support** and  **Add Docker Support** use the same icon?

**Comment by adashen** [comment]
@bsaby The icon of Azure Docker Support will be tuned later. For this issue, the fix should be complete

**Comment by bsaby** [comment]
Close this issue because it has been fixed.
