### ISSUE TITLE
create vm from azure explorer pops up an window which only shows portion of settings and doesn't let continue

### ISSUE THREAD

**Issue by arroyc** [Microsoft/azure-tools-for-java#108]
![image](https://cloud.githubusercontent.com/assets/16231002/23080962/abdad4ec-f507-11e6-870c-5e28905dc650.png)

resolution 2560X1440, windows 64 enterprise

**Comment by lenala** [comment]
Wizard was made resizable, should be able to continue.

**Comment by bsaby** [comment]
Sorry, I can not verify this issue because my test machine doesn't support 2560X1440 resolution.

**Comment by martinsawicki** [comment]
@lenala will close

**Comment by lenala** [comment]
JScrollPane was added, so all fields accessible. Duplicate to #322, closing.
