### ISSUE TITLE
Image and tag field is not right

### ISSUE THREAD

**Issue by jdneo** [Microsoft/azure-tools-for-java#1081]
If the user restart the IntelliJ and open push image panel (or web app for linux), the imge and tag field will contain server url.

<img width="618" alt="screen shot 2017-09-28 at 9 10 07 pm" src="https://user-images.githubusercontent.com/6193897/30968305-7f331392-a424-11e7-9035-1624c13ff56a.png">

**Comment by jdneo** [comment]
@bsaby fixed, please help verify, thanks.

**Comment by bsaby** [comment]
Test passed.
BUild: Dev418
