### ISSUE TITLE
'Publish' toolbar dropdown does not contain 'Docker run' and 'Publish to Web App on Linux'

### ISSUE THREAD

**Issue by lenala** [Microsoft/azure-tools-for-java#1084]
In Eclipse when right clicking on web project with docker configuration, there are 3 options to publish, but when clicking on 'Publish' dropdown in toolbar, only one option is available, 'Docker run' and 'Publish to Web App on Linux' are missing.
![image](https://user-images.githubusercontent.com/6208231/31004549-b9aaafdc-a4a9-11e7-95b9-72511409da1b.png)
![image](https://user-images.githubusercontent.com/6208231/31004654-1b9f8e06-a4aa-11e7-8362-15de45ad7920.png)

**Comment by adashen** [comment]
@bsaby, can verify whether this is still an issue in our dev build?

**Comment by jdneo** [comment]
@bsaby when click Publish dropdown, is there any project which is selected?

**Comment by bsaby** [comment]
Try again using build:dev417
**No 'Docker run' and 'Publish to Web App on Linux' options.**
1. When you select the web project, click 'Publish' dropdown in toolbar
![image](https://user-images.githubusercontent.com/22470312/31042935-768ff4ae-a5e5-11e7-8273-fd02d9494573.png)
2. When you select the Spring boot project(.jar), click 'Publish' dropdown in toolbar
![image](https://user-images.githubusercontent.com/22470312/31042940-a67928c0-a5e5-11e7-8958-d840d852860b.png)

**Comment by adashen** [comment]
@bsaby Please verify the fix. Note, the publish to web app on linux has been renamed to publish to web app for containers to align with the name on azure portal

**Comment by bsaby** [comment]
Test passed.
Build: dev435
.jar project
![image](https://user-images.githubusercontent.com/22470312/31530287-007cff96-b012-11e7-951e-bc60939f8812.png)
.war project
![image](https://user-images.githubusercontent.com/22470312/31530371-9630d4ae-b012-11e7-8de5-5282184725b5.png)
