### ISSUE TITLE
Buttons text truncated on Mac when showing container registry details

### ISSUE THREAD

**Issue by lenala** [Microsoft/azure-tools-for-java#1085]
Right click on container registry in Azure Explorer and select 'Show details'. Text for 'Enable' and 'Disable' buttons in truncated. 
![image](https://user-images.githubusercontent.com/6208231/31004752-9984cf02-a4aa-11e7-9f02-f3ce314bb6ac.png)

**Comment by jdneo** [comment]
Hi, @lenala . Could you please provide some more information about this issue, such as your Mac OS version, plugin version and eclipse version.

**Comment by lenala** [comment]
MacOS:
HighSierra 10.13 (same result was with El Captain)

Eclipse:
Version: Oxygen.1 Release (4.7.1)
Build id: 20170914-1200

Plugin version:
3.0.9.201709140615

**Comment by jdneo** [comment]
@bsaby fixed, please help verify in the new build, thanks.

**Comment by bsaby** [comment]
Test passed in latest build.
![image](https://user-images.githubusercontent.com/22470312/31324231-41c6236a-ace3-11e7-8f66-470dc26c25af.png)

**Comment by jdneo** [comment]
Hi @lenala , this issue can be reproduced in plugin v3.0.9. And has been already fixed.  But it hasn't been released yet. You can check it out in our daily build in [CI server](https://vscjavaci.cloudapp.net/job/AzureToolsManager_develop_daily/) if you want.
