### ISSUE TITLE
[Eclipse]Web App-> no content be deployed when can't detect an active project

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1088]
Repro steps:

1. Select a project
2. Don't publish directly, click other areas in Eclipse, e.g. Azure explorer
3. Then click Publish dropdown toolbar and choose Publish as Azure Web App
4. Now, a dialog will pop up
![image](https://user-images.githubusercontent.com/22470312/31043011-ff8df372-a5e6-11e7-9eda-6c0e582356aa.png)
5. Click OK in above dialog
**RESULT:**
The Deploy Web App window pops up
Choose an existing app service or new an app service, after clicking Deploy, nothing will happen in Azure Activity Log dialog, nor will the content be deployed to the Web app
**EXPECT:** 
The Deploy Web App window should not pop up.

**Comment by adashen** [comment]
@bsaby fixed from code logic. Please also try to reproduce it. The fixed behavior should be: error dialog shows up, and the deploy dialog will not show then.

**Comment by bsaby** [comment]
Test passed in Build: dev428

1. Error dialog shows up
2. Click OK
3. The deploy dialog will not show
