### ISSUE TITLE
Azure web apps dialog page not showing

### ISSUE THREAD

**Issue by doristchen** [microsoft/azure-tools-for-java#1091]
When I use Azure plugin for Eclipse, I use the option Web App for Linux, I get passed the container registry dialog window, and next window is empty.  This is on windows Surface book (windows 10).  I use Eclipse Oxygen version.

![eclipse_azure_noresult](https://user-images.githubusercontent.com/7990403/31203186-ccf42f76-a91a-11e7-9d03-c1dac2380122.PNG)

**Comment by Eskibear** [comment]
Another user also reported this issue. But we are not able to reproduce it. A few questions:
1. Can you reproduce this issue stably? If so, please kindly share the steps.  
2. When the issue occurs, try resizing the window in this page, see if the content shows. 

@doristchen

**Comment by Flanker32** [comment]
Close as we can't reproduce this issue, feel free to open it once you could reproduce it in the latest version
