### ISSUE TITLE
Can't get Azure Manager 

### ISSUE THREAD

**Issue by Matthew-Dong** [Microsoft/azure-tools-for-java#1094]
IntelliJ users have this issue when they run projects with Run Configuration after the login info expires.

**Comment by jdneo** [comment]
@bsaby fixed, please help verify, thanks.
--------------------------------

**Bug repro steps:**
Run any run configuration (e.g. Run on Web App) that need sign in.

**Expected:**
An error message tells user that he need sign in first

**Current:**
An error message shows as: Cannot get Azure Manager. (which is meaningless for users)

**Comment by bsaby** [comment]
Test passed.
Build: daily174
![image](https://user-images.githubusercontent.com/22470312/31422425-07a6fe5e-ae80-11e7-8007-fe612e1cb9c9.png)
