### ISSUE TITLE
Create App Service dialog: Missing internal margins within frame

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#110]
There needs to be extra space on both the left and the right, since the frame box embedded in this dialog.
![createwebapp](https://cloud.githubusercontent.com/assets/881767/23081007/dad52c20-f507-11e6-8c0b-eb105465e0ab.png)

**Comment by bsaby** [comment]
Test Passed in artifacts/azure-toolkit-for-intellij.197.zip
