### ISSUE TITLE
[IntelliJ]Push image from Azure Explorer-> Combo box should select the ACR as default

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1102]
Right click an ACR node in Azure Explorer to push image, eg: monaacr1
**Result:**
![image](https://user-images.githubusercontent.com/22470312/31422647-d29007d6-ae81-11e7-9c14-87003b0a7282.png)
**Expect:**
![image](https://user-images.githubusercontent.com/22470312/31422675-f364a476-ae81-11e7-8c15-9955c2e1b053.png)

**Comment by adashen** [comment]
@bsaby this is as designed currently, we didn't store the subscription, instead, the user credentials have been stored. So user still can run the push acr

**Comment by bsaby** [comment]
Close this issue because by design.
