### ISSUE TITLE
[IntelliJ] Pull image -> The prompt message should display the right image name

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1103]
![image](https://user-images.githubusercontent.com/22470312/31423148-67f7100a-ae85-11e7-8364-7327d6617adc.png)
Result:

![image](https://user-images.githubusercontent.com/22470312/31423136-4e977b40-ae85-11e7-86bd-15b0dcfdbeb4.png)

**Comment by jdneo** [comment]
@bsaby fixed, please help verify this issue, thanks.

**Comment by bsaby** [comment]
Test passed.
Build: dev435
