### ISSUE TITLE
[Eclispe] publish to Web App for Containers.. option still exists when there is no Dockerfile

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1115]
Repro when the plugin just installed or first click project to publish 
Repro steps:

1. Install plugin
2. Sign in Azure
3. Click a project without a  dockerfile
4. Click toolbar

Result:
Publish to Web App for Containers... option occurs
![image](https://user-images.githubusercontent.com/22470312/31530495-784e0a00-b013-11e7-987a-35e78f887060.png)

**Comment by bsaby** [comment]
In this case, An error dialog will pops up when publishing to web app for containers 

![image](https://user-images.githubusercontent.com/22470312/31533424-bb3d1d4a-b024-11e7-9972-c3e598e32a62.png)

**Comment by adashen** [comment]
It seems an eclipse issue. It didn't trigger the project tester when first time loaded. However, we are planning to enable the publish to web app containers in next sprint and let user choose the docker file. So this issue should be fixed later. So open now and track in next sprint.

**Comment by Eskibear** [comment]
@bsaby please help to verify it in the new workflow.

**Comment by bsaby** [comment]
Test passed using build: Dev464
The Web App for Containers entry always exists.
