### ISSUE TITLE
[Eclipse]Update the plugin without updating the web App on Linux name to web app for containers

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1117]
1. First Install a build number < dev432 (the previous build number we used is dev428)
2. Uninstall old build or update new  build directly, new build number>= dev432

The name of web app on linux does not become to web app for containers

![image](https://user-images.githubusercontent.com/22470312/31531461-d8826f5a-b019-11e7-94d5-4e89899cfcfd.png)

**Comment by adashen** [comment]
fixed, please verified on latest developer build (440 or later).

**Comment by bsaby** [comment]
Test passed. 
Build: dev440
The name will be updated after updating the plugin.
