### ISSUE TITLE
[Eclipse]Push image-> Should save last configuration

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1119]
Reopen push image dialog, the last configuration will not be saved

**Comment by jdneo** [comment]
We won't save the configuration locally in Eclipse at current stage. Because currently the flow in Eclipse is different with that in IntelliJ. And since we added the ACR selector, this should not be a big problem.

**Comment by bsaby** [comment]
Bu design and close issue.
