### ISSUE TITLE
[Eclipse] Cannot install scala IDE from marketplace

### ISSUE THREAD

**Issue by ruoxinCheng** [microsoft/azure-tools-for-java#1128]
uses Eclipse IDE for Java Developers
Version: Neon.3 Release (4.6.3)
1. do not install Scala IDE. 
2.  Open eclipse reminder you to install it from marketplace.
Actual: come out bellow error.

![image](https://user-images.githubusercontent.com/20041888/31603458-d7002bb0-b292-11e7-9c19-798ab665f247.png)

**Comment by djlan** [comment]
This is due to new version of Scala IDE released.

**Comment by t-rufang** [comment]
This bug is already fixed in #1139
