### ISSUE TITLE
create new resource group while creating new storage account in azure explorer doesn't show full text

### ISSUE THREAD

**Issue by arroyc** [microsoft/azure-tools-for-java#113]
![image](https://cloud.githubusercontent.com/assets/16231002/23081069/248c21a2-f508-11e6-95d0-c8d12d372513.png)

**Comment by martinsawicki** [comment]
need to postpone this  cosmetic issue (rarely encountered -- requires special machine with high res)

**Comment by Flanker32** [comment]
Has been fixed in the latest release
