### ISSUE TITLE
[MoonCake]Web App-> Give Wrong URL When opening in browser

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1134]
Right click a Web App in Azure explorer and choose Open In Browser
Expect:
![image](https://user-images.githubusercontent.com/22470312/31698522-82b6550c-b3f0-11e7-81c3-9376c0b452bb.png)
Result(Give the global url not azure china):
![image](https://user-images.githubusercontent.com/22470312/31698524-85867c76-b3f0-11e7-9d91-89452224e5b1.png)

Repro in v3.0.9
Not repro v3.0.7

**Comment by adashen** [comment]
Since the node does not have webapp instance. So the it hard coded the url. The fix should pass the url to the explorer node as one property. Consider we will cut bit in the afternoon. And the impact is relatively low. Will fix in next release.

**Comment by jdneo** [comment]
@bsaby Fixed, please help verify it in the new build, thanks.

**Comment by bsaby** [comment]
Test passed.
Build used: dev459
