### ISSUE TITLE
[Eclipse]Web App for Container-> UI issue of background color 

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1135]
Open Web App for container dialog, find that **Resource group** background color is different from other areas
![image](https://user-images.githubusercontent.com/22470312/31699125-c336c67c-b3f3-11e7-8eee-17eb1092d868.png)

**Comment by adashen** [comment]
The UI for web app container flow will change in next release. Hold this bug and update it when the new UI checked in.

**Comment by adashen** [comment]
@bsaby please verify it on the dev build. Since the workflow has been updated

**Comment by bsaby** [comment]
Test passed.
Build:dev449
![image](https://user-images.githubusercontent.com/22470312/31808779-3765b094-b5a7-11e7-92a5-b1264b32ef72.png)
