### ISSUE TITLE
After deploying WebApp to root, we take user to wrong URL

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#114]
After deploying a Web App as root, when the plugin shows the success dialog and asks the user to navigate to the page, it takes them to the wrong URL ---  the one based on the webApp name, not teh root. The plugin should remember that it’s getting deployed to the root and take the use there in that situation

**Comment by bsaby** [comment]
Test passed in artifacts/azure-toolkit-for-intellij.197.zip.
