### ISSUE TITLE
[IntelliJ] The error dialog size is too long

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#1144]
![image](https://user-images.githubusercontent.com/22470312/31807527-428893b6-b5a1-11e7-8d91-911c44a27ffa.png)

**Comment by andxu** [comment]
This dialog is ugly, need to fix it.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738794

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
