### ISSUE TITLE
The latest IntelliJ plugin doesn't support Azure China Cloud

### ISSUE THREAD

**Issue by kingliantop** [Microsoft/azure-tools-for-java#1146]
I installed the latest version(v3.0.10-2017.2) to my IntelliJ(build 172.4343.14), using the authentication file sign to the Azure China CLoud, it showed the below errors:

java.io.IOException: com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS50001: The application named https://management.core.windows.net/ was not found in the tenant named 8aa2cf70-b8bf-487b-9d32-7166b16c72d7. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: 109e1fc1-538b-414e-904f-d25606b21300\r\nCorrelation ID: b434916e-319a-417e-84ba-e143fd0884d7\r\nTimestamp: 2017-10-22 10:04:56Z","error":"invalid_resource"}

I checked the URLs in the authentication file, they are correct:
authURL=https://login.chinacloudapi.cn/
baseURL=https://management.chinacloudapi.cn/
graphURL=https://graph.chinacloudapi.cn/
managementURI=https://management.core.chinacloudapi.cn/

It should be the bugs in the plugin code, could you please advise? Thanks!

**Comment by adashen** [comment]
@kingliantop this is a known issue in plugin for intellij. The fix will be released in the next version (3.0.11). Currently, there is a workaround please follow the steps
1.	Create or change the auth file to json format. For creating the json format auth file please refer to https://docs.microsoft.com/en-us/python/azure/python-sdk-azure-authenticate?view=azure-python
“ az ad sp create-for-rbac --sdk-auth > mycredentials.json ”
2.	Make sure the following KV pair is added to the json file : "activeDirectoryResourceId" : "https://management.core.chinacloudapi.cn/"
3.	And then login in IDE with the new create json auth file.

**Comment by Eskibear** [comment]
reference: #1109

**Comment by kingliantop** [comment]
@adashen Thanks a lot Wei!
After run the command "az ad sp create-for-rbac --sdk-auth > mycredentials.json ”, we must manually add the item:
"activeDirectoryResourceId" : "https://management.core.chinacloudapi.cn/"

then it works!~
