### ISSUE TITLE
We should expose Azure Explorer entry point on Azure context menu

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#115]
for better discoverability, otherwise it's hard to find, but it's quite useful

So, at the bottom, after a separator line, right above the "Sign In..." suggested in issue https://github.com/Microsoft/azure-tools-for-java/issues/102

**Comment by bsaby** [comment]
Test passed, using artifacts/azure-toolkit-for-intellij.2017.333.04-18-2017.zip.
![image](https://cloud.githubusercontent.com/assets/22470312/25161324/dec03292-24ed-11e7-90d0-17fb013f80fa.png)
![image](https://cloud.githubusercontent.com/assets/22470312/25161396/4810a45c-24ee-11e7-90a1-ec3c8c63bf6d.png)
