### ISSUE TITLE
[Mooncake]-> publish as Docker Container: published link give wrong URL

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1159]
Published link give wrong URL
Repro steps:

1. Right click a project and click Publish as Docker Container
2. New a docker host ,e.g. monadockerwar1 (you can use the default configuration)
3. After published, click **Published**in Azure Activity Log Dialog, and the web site can't reach

picture1:
![image](https://user-images.githubusercontent.com/22470312/31928942-88d6cb2a-b8cc-11e7-9f44-52992e548cb7.png)
picture2:
![image](https://user-images.githubusercontent.com/22470312/31929173-801127fa-b8cd-11e7-8748-6a80c7f73271.png)

4.  Refresh this docker host node:monadockerwar1 and right click the container: monadockerwar1-8573 and choose Browse, the content can normal display:
picture3:
![image](https://user-images.githubusercontent.com/22470312/31929112-346c2ab6-b8cd-11e7-86dc-0e94570b1e88.png)
picture4:
![image](https://user-images.githubusercontent.com/22470312/31929214-ae668ffa-b8cd-11e7-8ebe-27602ea02f82.png)

**Comment by adashen** [comment]
@bsaby please verify the fix on the latest build

**Comment by bsaby** [comment]
Test passed using build: dev464
