### ISSUE TITLE
[Mooncake]Unknown HostException for Publish a .jar file to Dcoker Contaier

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1163]
I have published a .jar to Docker Container, and sometimes it occurs error in Azure Activity Log dialog.

![image](https://user-images.githubusercontent.com/22470312/31935774-3af07620-b8e2-11e7-86f8-5cfeb5433713.png)

**Comment by adashen** [comment]
@bsaby please verify the fix at latest dev build

**Comment by bsaby** [comment]
Test passed using build: dev464
