### ISSUE TITLE
[Eclipse]Docker Run-> Configuration can't be saved

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#1166]
First open Docker Run dialog and input some value shown as below
![image](https://user-images.githubusercontent.com/22470312/31978606-be56126c-b974-11e7-97b5-1d32b948d66f.png)
After Docker run, reopen this dialog, the configuraton shown as below
![image](https://user-images.githubusercontent.com/22470312/31978626-d1d37488-b974-11e7-9235-4124ad23cb01.png)

**Comment by Eskibear** [comment]
Yes we don't save it now. it's by design for the moment. It should be included in future plan.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738788

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
