### ISSUE TITLE
[Eclipse]Docker Run-> Docker file should have default value if add docker support

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1167]
1.  Add docker support for project
2. Right click project and choose Docker Run, the Docker File fixed should have value just like Docekr Run in IntelliJ
Result:
![image](https://user-images.githubusercontent.com/22470312/31978838-fd7c061c-b975-11e7-8213-967f4f69cb03.png)
Expect(In IntelliJ):
![image](https://user-images.githubusercontent.com/22470312/31978956-b1b8e898-b976-11e7-92ee-712844349596.png)

**Comment by Eskibear** [comment]
@bsaby , fixed in #1175, please verify it.

**Comment by bsaby** [comment]
Test passed.
Build used: Dev469
