### ISSUE TITLE
list HDInsight clusters error in MoonCake environment

### ISSUE THREAD

**Issue by voidfunction** [Microsoft/azure-tools-for-java#1173]
Cannot list HDInsight clusters in Azure China environment.

**Comment by voidfunction** [comment]
Root cause: `https://main.hdinsight.ext.azure.com/api/Clusters/GetAll?subscriptionIds=%s` didn't work for Mooncake. We need standard HDInsight REST API to replace it.

**Comment by adashen** [comment]
We have refactored the auth flow. You may use AzureManager azureManager = AuthMethodManager.getInstance().getAzureManager();
Environment env = Environment.GLOBAL;
If (azureManager != null) {
       Env = azureManager.getEnvironment();
}
to get the environment and decide which endpoint to use

**Comment by voidfunction** [comment]
@adashen Thanks for your tips. It's not the auth problem. It's HDInsight SDK issue. Actually, we can get the access token from `AzureManager`, but HDInsight REST API has some problem in Mooncake.
