### ISSUE TITLE
New Deployment of Docker Container window gets in undetermined state 

### ISSUE THREAD

**Issue by hovsepm** [Microsoft/azure-tools-for-java#118]
I think I clicked on Custom docker file radio button and then back to Predefined Docker image and now Next/Finish buttons are disabled. 

![image](https://cloud.githubusercontent.com/assets/7052173/23081172/7be214ca-f508-11e6-83be-bde3981e8cbd.png)

**Comment by hovsepm** [comment]
After going on previous page and clicking next Finish became available and working.

**Comment by milismsft** [comment]
fixed.

**Comment by bsaby** [comment]
Test passed in azure-toolkit-for-intellij.211.zip and issue closed
