### ISSUE TITLE
IntelliJ plugin doesn't support HDInsight China region

### ISSUE THREAD

**Issue by kingliantop** [microsoft/azure-tools-for-java#1189]
Hi guys,

I configured IntelliJ plugin to connect to Azure China, I can see the web apps and storage, while I can't see or refresh my HDInsight which is a Spark cluster. Any ideas? Thank!

**Comment by kingliantop** [comment]
![hdinsight-intellij](https://user-images.githubusercontent.com/66908/32141970-5f71e882-bcc8-11e7-95e6-5f05c7b536b4.PNG)

The snaposhot is attached.

**Comment by jingyanjingyan** [comment]
Set the environment with 
```
{
"EnvironmentName": "CHINA"
}
```

Then sign-in, expand HDInsight node to view cluster, submit, remote debug should work, with the most recent release build.

Thank you for your feedback, please re-open if the issue still happens to you.
