### ISSUE TITLE
Create Docker Host dialog: trapped in the password field

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#119]
Create a Docker Host: in the “New login credentials” radio button, my selection is automatically in the password textbox, but when I simply want to switch to the username and replace the pre-created one with a different one, it doesn’t let me leave the empty pwd box until I have a satisfactory password in it. Expectation: I should be abel to get out of the password textbox at any time, regardless of its content

**Comment by milismsft** [comment]
fixed.

**Comment by bsaby** [comment]
Test passed in azure-toolkit-for-intellij.211.zip and issue closed
