### ISSUE TITLE
[IntelliJ]web App for containers-> Lose default dockerfile path when Dockerfile exists

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1190]
![image](https://user-images.githubusercontent.com/22470312/32152034-609f5872-bd5c-11e7-945e-0ade4cae79e1.png)

**Comment by Eskibear** [comment]
fixed in #1191 , please verify the latest develop build. @bsaby

**Comment by bsaby** [comment]
Test passed.
Build used: dev481
