### ISSUE TITLE
[IntelliJ]Web App properties-> delete button doesn't work

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1192]
1. Right click a Web App and choose Show Properties
2. Choose a setting in App Settings and delete
3. Then Click Save
4. Waiting a balloon notification to prompt
5. Close the properties explorer and reopen it
RESULT:
The deleted one still exist

**Comment by jdneo** [comment]
@bsaby Fixed, please help verify, thanks.

**Comment by bsaby** [comment]
Test passed.
Build used: dev483
