### ISSUE TITLE
[IntelliJ]Web App properties: The displayed text is not appropriate

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1193]
Right click a Web App and choose Show Properties
When all settings are loaded, App Settings content should display "Loading ..." instead of "Nothing to show".
![image](https://user-images.githubusercontent.com/22470312/32154836-64faa748-bd6e-11e7-8e12-60c4b4bfffcf.png)

**Comment by jdneo** [comment]
@bsaby Fixed, please help verify, thanks.

**Comment by bsaby** [comment]
Test passed.
Build used: dev488
