### ISSUE TITLE
[IntelliJ] Web App properties -> UI issue on Mac

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1195]
![image](https://user-images.githubusercontent.com/22470312/32162289-69a15f1a-bd93-11e7-9fce-77adb7d3fa3c.png)
Same issue for ACR explorer

**Comment by jdneo** [comment]
@bsaby Fixed, pleases help verify, thanks.

**Comment by bsaby** [comment]
Test passed.
Build used: dev492
