### ISSUE TITLE
Improvement: build.xml changes in azure-toolkit-for-intellij

### ISSUE THREAD

**Issue by mpujari** [Microsoft/azure-tools-for-java#12]
fileset with id **idea.libraries**  at [build.xml:61](https://github.com/Microsoft/azure-tools-for-java/blob/31164b6bbbcd7529786d04b2f93d25bda733f91f/PluginsAndFeatures/azure-toolkit-for-intellij/build.xml#L61) can be improved, instead of adding all the jars from idea lib one by one and that too with versions, can be changed to have below pattern. The issue is, when there is a change in say minor version of any jar file then it won't compile.

```
<path id="idea.libraries">
  <fileset dir="${idea.home}">
    <include name="**/*.jar" />
  </fileset>
</path>
```

**Comment by lenala** [comment]
This change cannot be done as sometimes build fails with "Path too long" error when using a pattern.

**Comment by mpujari** [comment]
@lenala will get back to you on this...
