### ISSUE TITLE
Even after signing out Azure explorer shows the resources

### ISSUE THREAD

**Issue by anudeepsharma** [Microsoft/azure-tools-for-java#120]
Although after refreshing list is getting empty for resources. But when I logged out list still shows resources.

I am trying to stop websites, and it changes the Icon to stopped even after I am signed out.
Also able to delete blobs and contains in storage account.

Clicking on Storage account shows login dialog for split seconds first time after signing out.

**Comment by lenala** [comment]
This is fixed, please verify.

**Comment by songkaiape** [comment]
Not repro. Verified this issue  in azure-toolkit-for-intellij.14.zip
