### ISSUE TITLE
[IntelliJ] These options are confused from context menu

### ISSUE THREAD

**Issue by ruoxinCheng** [Microsoft/azure-tools-for-java#1211]
Right-click from script editor and from project explorer.
![image](https://user-images.githubusercontent.com/20041888/32308133-34e02922-bfbf-11e7-83c4-61d1ffb93c51.png)

**Comment by wezhang** [comment]
I'll try to remove them.

**Comment by wezhang** [comment]
Run context feature added

**Comment by ruoxinCheng** [comment]
It work on 2017.2 , but not work on 2017.1.

**Comment by ruoxinCheng** [comment]
and SBT also not support context menu.

**Comment by wezhang** [comment]
Due to 2017.1 Scala plugin limitation, Local Run Context only works in at `File`, `Object`, `main` function of scala file. No problems in java file.

**Comment by ruoxinCheng** [comment]
Verified it.
