### ISSUE TITLE
[Eclispe] Azure icon has not been updated in Eclipse menu bar

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1227]
![image](https://user-images.githubusercontent.com/22470312/32423760-65af9534-c2e3-11e7-8601-92387a3ee7d3.png)

**Comment by bsaby** [comment]
And the azure icon in project explorer.
![image](https://user-images.githubusercontent.com/22470312/32424961-9ebfc9b4-c2ea-11e7-9fe0-693781862c5c.png)

**Comment by Eskibear** [comment]
fixed in https://github.com/Microsoft/azure-tools-for-java-resources/pull/19
please verify develop build 501.

**Comment by bsaby** [comment]
Test passed. 
Build used: Daily 201
![image](https://user-images.githubusercontent.com/22470312/32474697-bc7868da-c3a8-11e7-983a-10233d93924a.png)
![image](https://user-images.githubusercontent.com/22470312/32474739-ff916edc-c3a8-11e7-8f35-ee8c6ab19115.png)
