### ISSUE TITLE
[IntelliJ] Help message for SSH password expired

### ISSUE THREAD

**Issue by ruoxinCheng** [Microsoft/azure-tools-for-java#1229]
unable to open debugger port(localhost:11686):java.io.IOException "handshake faile- connection prematurally closed"

**Comment by wezhang** [comment]
Can works well on Mooncake cluster.

![image](https://user-images.githubusercontent.com/7385667/33113144-d5b6b618-cf91-11e7-9c9f-1d05f74482af.png)

![image](https://user-images.githubusercontent.com/7385667/33113165-e8b7e336-cf91-11e7-967c-6274c1ec5c33.png)

**Comment by wezhang** [comment]
The issue might be the SSH password expired.

**Comment by ruoxinCheng** [comment]
Would you a suggestion of  checking the SSH login.

**Comment by wezhang** [comment]
dup #556

**Comment by jingyanjingyan** [comment]
warning message display at the advanced dialog.
