### ISSUE TITLE
[Eclipse]Web app for containers: no default value when creating a new web app for container

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1231]
![image](https://user-images.githubusercontent.com/22470312/32430928-4f0b0f2e-c30c-11e7-940c-e2c032da8371.png)

**Comment by Eskibear** [comment]
fixed in #1234

**Comment by bsaby** [comment]
Test passed.
Build used: Daily201
![image](https://user-images.githubusercontent.com/22470312/32475280-eb5cee66-c3ab-11e7-855d-13bb9d5dc784.png)
