### ISSUE TITLE
[IntelliJ and Eclipse]Mooncake Sign in with Interactive not work on Mac

### ISSUE THREAD

**Issue by tankungx** [Microsoft/azure-tools-for-java#1232]
steps:
1.	Create a new file “AadProvider.json” under the folder: <userhome>\AzureToolsForIntelliJ
2.	Add the following content into the file:
{
"EnvironmentName": "CHINA"
}
3.	Restart IntelliJ.
4. Try to sign in.

Results
![image](https://user-images.githubusercontent.com/30617450/32430842-fd3810a2-c30b-11e7-8383-f6530bda324a.png)

![image](https://user-images.githubusercontent.com/30617450/32430865-154da648-c30c-11e7-93f7-895df624cbdd.png)

**Comment by voidfunction** [comment]
@wezhang Could you help take a look? Thank you.

**Comment by voidfunction** [comment]
@adashen Could you help take a look?

**Comment by Eskibear** [comment]
I'm ok with the latest develop build No.503.

My `AadProvider.json` path and content.
```
[sechs@Yans-MacBook-Pro:~/AzureToolsForIntelliJ]
$> cat AadProvider.json 
{
  "EnvironmentName":"CHINA"
}
```

Look at Chinese characters on the bottom-right, indicating it's mooncake login page:
![image](https://user-images.githubusercontent.com/2351748/32473717-94e095e2-c32e-11e7-81b2-7ee0332714c1.png)

**Comment by tankungx** [comment]
work well now.

**Comment by yucwan** [comment]
documented here: https://github.com/microsoft/azure-tools-for-java/wiki/FAQ#1-how-to-login-to-national-clouds
