### ISSUE TITLE
[Eclipse]It would be better if the link can be clicked in the Console.

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1233]
Web app for Containers:
![image](https://user-images.githubusercontent.com/22470312/32431135-23e53f6c-c30d-11e7-95cb-e0be9d980cef.png)
Docker Run:
![image](https://user-images.githubusercontent.com/22470312/32431160-42e8854a-c30d-11e7-9b18-7dccc9b32a76.png)

**Comment by Eskibear** [comment]
would be added in #1236

**Comment by Eskibear** [comment]
merged. please help to verify.

**Comment by bsaby** [comment]
Test passed using build: dev504
1.
![image](https://user-images.githubusercontent.com/22470312/32482702-d0e46b9a-c3d3-11e7-944d-753e77bd2ca9.png)
2.
![image](https://user-images.githubusercontent.com/22470312/32482695-c8d4209e-c3d3-11e7-8f1f-da4157acb914.png)
3.
![image](https://user-images.githubusercontent.com/22470312/32482709-dc7d459e-c3d3-11e7-892a-abeb7fcf33e4.png)
