### ISSUE TITLE
The error message should be more specific

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#1235]
IntelliJ: Web app and Web app for containers
Eclipse: Web app for Containers

Create a resource group with an existing name when creating a new app service, error message shown as below:
![image](https://user-images.githubusercontent.com/22470312/32432810-dbb18a28-c313-11e7-84d3-139362293032.png)

![image](https://user-images.githubusercontent.com/22470312/32432801-d4e3050a-c313-11e7-9aa3-125d26c23fb2.png)

**Comment by ZhengJun003** [comment]
Can reproduce this issue in azure toolkits for IntelliJ 3.37.0 and azure toolkits for Eclipse 3.23.0

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738803

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
