### ISSUE TITLE
[Suggestion]  Azure Explorer - Make use of virtual machine CreateAsync resource streaming

### ISSUE THREAD

**Issue by anuchandy** [microsoft/azure-tools-for-java#124]
We call VirtualMachine.Create which internally creates related resources. If we use VirtualMachine.CreateAsync then we get notification as each resource gets created, if this info can be
propagated to intelliJ progress bar then it would be cool.

Similar issue for Docker Host: https://github.com/Microsoft/azure-tools-for-java/issues/90

**Comment by martinsawicki** [comment]
interesting but not for 3.0

**Comment by andxu** [comment]
Already implemented in 3.59.0
