### ISSUE TITLE
[IntelliJ] The context menu only work on classname or beyond script

### ISSUE THREAD

**Issue by ruoxinCheng** [Microsoft/azure-tools-for-java#1240]
![image](https://user-images.githubusercontent.com/20041888/32484899-60bc3632-c3dc-11e7-8b5b-7e23e8831b2c.png)
![image](https://user-images.githubusercontent.com/20041888/32484928-7ab35750-c3dc-11e7-9e68-3f115d740eba.png)

**Comment by wezhang** [comment]
Only repro on Scala file job.

**Comment by wezhang** [comment]
The Local Run Configuration sorted as the 2nd one.

**Comment by ruoxinCheng** [comment]
Verified it.
