### ISSUE TITLE
[IntelliJ][RemoteDebug] Click the 'Rerun remote debug' button failed

### ISSUE THREAD

**Issue by ruoxinCheng** [Microsoft/azure-tools-for-java#1241]
Error : Spark batch Job remote debug failed, got exception: com.jcraft.jsch.JSchException: Auth fail

**Comment by ruoxinCheng** [comment]
![image](https://user-images.githubusercontent.com/20041888/32485000-c2e2892e-c3dc-11e7-9c68-f08ff7df364b.png)

**Comment by wezhang** [comment]
Have you checked the ssh authentication?

**Comment by ruoxinCheng** [comment]
Yes, I'm sure. Because remote debug is work, but click the rerun button failed.

**Comment by Adrian-Sanz-Alstom** [comment]
I'm getting the same error. Any fix?

**Comment by wezhang** [comment]
Verified `Rerun` action in both `Driver` and `Executor` debug tabs, the issue is fixed by #1542
