### ISSUE TITLE
[Eclipse] Subscriptions list is not displayed correctly in Application insights dialog

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#1243]
This issue is reproduced when login Azure in Application Insights dialog and isn't a regression issue, also reproduce in v3.0.10.
1. Right click web project and choose configure Application Insights
2. Click Instrumentation keys
3. In Application Insights dialog, click Login icon to login Azure
4. Choose one/several subscription you need 
5. After login, click New to create an application insight
**Result:**
The subscriptions list shows all subscriptions
![image](https://user-images.githubusercontent.com/22470312/32533527-2a98afda-c48c-11e7-94fa-b24fa03be696.png)
**Expect:**
Only display the subscriptions which user selected in step 4

**Comment by ZhengJun003** [comment]
Can reproduce this issue in azure toolkits for eclipse 3.23.0

![image](https://user-images.githubusercontent.com/41051257/84612513-6ef41f80-aef3-11ea-96cc-101f477f1604.png)

**Comment by andxu** [comment]
It is by-design since we want to configure AIs among different subs.
