### ISSUE TITLE
[IntelliJ]Error occurs when docker run project

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1247]
Error occurs when opening Docker run dialog via project explorer.
Also repro in Web app for Containers and Push image dialog

**Error Log:**
![image](https://user-images.githubusercontent.com/22470312/32712217-54186b84-c87e-11e7-941b-80b0520306da.png)

**Comment by adashen** [comment]
@bsaby , please verify on the latest build

**Comment by bsaby** [comment]
Test pased.
Build used: dev509
