### ISSUE TITLE
[IntelliJ][Web project]Lose default dockerfile path when Dockerfile exists 

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1248]
Can't auto fill  default dockerfile path for docker run/run web app for containers/push image when Dockerfile exists.  
![image](https://user-images.githubusercontent.com/22470312/32717071-518ba344-c893-11e7-9450-aaa3cf54c9e0.png)

**Comment by adashen** [comment]
Not mac specific, but the intellij webservice app specific

**Comment by adashen** [comment]
Please verify on the latest build

**Comment by bsaby** [comment]
Test passed.
Build used: dev509
