### ISSUE TITLE
[IntelliJ][Web project]Can't load container registries

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1249]
First, you should make sure that the local idea does not have push image configurations.
Then right click project and choose push image, the container registry status is always loading.

![image](https://user-images.githubusercontent.com/22470312/32717123-7a1afb34-c893-11e7-9956-ed78c364d2a6.png)

**Comment by adashen** [comment]
Not mac specific, but intelliJ Web Service project specific

**Comment by adashen** [comment]
@bsaby please verify on the latest build

**Comment by bsaby** [comment]
Test passed.
Build used: dev509
