### ISSUE TITLE
Container work flow - next button is enabled but does not proceed

### ISSUE THREAD

**Issue by selvasingh** [Microsoft/azure-tools-for-java#126]
clicking on next .. nothing will happen, try multiple times, it is very stubborn

![image](https://cloud.githubusercontent.com/assets/3642444/23081656/a947999c-f50a-11e6-9eda-fa55ffa6dff3.png)

**Comment by milismsft** [comment]
can't repro in the latest build; initial error could have been triggered because the auto-generated names where not actually valid.

**Comment by bsaby** [comment]
Test passed in azure-toolkit-for-intellij.211.zip and issue closed
