### ISSUE TITLE
[IntelliJ]The Intellij.2017.2 plugin is incompatible with intelliJ versions below 2017.2.6

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1263]
![image](https://user-images.githubusercontent.com/22470312/33254686-ed4cb178-d384-11e7-98d5-f4e21d238a2a.png)

**Comment by jdneo** [comment]
It is because in the gradle.properties, the IDEA version is set to 2017.2.6. We should set it to 2017.2 (without the minor version).

https://github.com/Microsoft/azure-tools-for-java/blob/develop/PluginsAndFeatures/azure-toolkit-for-intellij/gradle.properties#L4

**Comment by ruoxinCheng** [comment]
Verified it.
