### ISSUE TITLE
[Eclipse] The installation cannot be completed as requested

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1267]
Build: develop522

![image](https://user-images.githubusercontent.com/22470312/33304962-c42f4482-d446-11e7-8278-b4566bcd203f.png)
![image](https://user-images.githubusercontent.com/22470312/33305971-4e99bedc-d44b-11e7-85db-dade39bc7f4e.png)

**Comment by jdneo** [comment]
related code seems here: https://github.com/djlan/azure-tools-for-java/blob/1767e5ec8351d93e271a2eabd1ee0c0d0188a556/PluginsAndFeatures/azure-toolkit-for-eclipse/com.microsoft.azuretools.hdinsight/META-INF/MANIFEST.MF#L18

**Comment by bsaby** [comment]
Verified installation using new build: develop523, test passed.
