### ISSUE TITLE
Azure Toolkit for IntelliJ not compatible with latest version

### ISSUE THREAD

**Issue by Oscar-21** [Microsoft/azure-tools-for-java#1282]
Current IntelliJ Build.
![image](https://user-images.githubusercontent.com/21151259/33559927-4f8207ec-d8dc-11e7-9279-a77d7197e622.png)

## First Attempt
Does IntelliJ list incompatible plugins?
![image](https://user-images.githubusercontent.com/21151259/33560048-a75189f2-d8dc-11e7-98f9-d8e878b2d328.png)

![image](https://user-images.githubusercontent.com/21151259/33560094-c20887c8-d8dc-11e7-8b03-47058311b697.png)

## Second Attempt
I am aware my version of intelliJ does not match any listed version but I don't know whether or not the two have to exactly match.
![image](https://user-images.githubusercontent.com/21151259/33559873-2cafb0c0-d8dc-11e7-9156-67598948e9a7.png)
![image](https://user-images.githubusercontent.com/21151259/33559902-3f0bf3e6-d8dc-11e7-8c9d-19d0a9aa27cb.png)

**Comment by adashen** [comment]
@Oscar-21 , Thanks for reporting the issue, we have noticed the new version of intelliJ, will fix the issue in the next releae

**Comment by wezhang** [comment]
dup #1281
