### ISSUE TITLE
Old link in Sign In form

### ISSUE THREAD

**Issue by kutsyk** [Microsoft/azure-tools-for-java#1284]
Link in the sign in form to steps in the message: 
Follow these manual [steps](https://github.com/Azure/azure-sdk-for-java/blob/master/AUTH.md#creating-a-service-principal-in-azure) if Azure Toolkit fails to create an authentication file programmatically.
Is not available: 
https://github.com/Azure/azure-sdk-for-java/blob/master/AUTH.md#creating-a-service-principal-in-azure
Should be changed to proper link.
I think this is this [link](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/azure-resource-manager/resource-group-create-service-principal-portal.md)
https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/azure-resource-manager/resource-group-create-service-principal-portal.md 
but I'm not sure. If it is, I can change it.

**Comment by Eskibear** [comment]
It seems folder structure in https://github.com/Azure/azure-sdk-for-java has been changed. Is [this one](https://github.com/Azure/azure-sdk-for-java/blob/master/archive/AUTH.md) available? https://github.com/Azure/azure-sdk-for-java/blob/master/archive/AUTH.md

**Comment by kutsyk** [comment]
In the following link, there is nothing like #creating-a-service-principal-in-azure everything there is for authentification from code by cred file. And it is in the archive folder. Maybe there is better and more trusted instruction that won't move somewhere.

**Comment by adashen** [comment]
@kutsyk in https://github.com/Azure/azure-sdk-for-java/blob/master/archive/AUTH.md#using-an-authentication-file, there is steps to create the auth file.

"The authentication file, referenced as "my.azureauth" in the example above, contains the information of a service principal. You can generate this file using Azure CLI 2.0 through the following command. Make sure you selected your subscription by az account set --subscription <name or id> and you have the privileges to create service principals.

az ad sp create-for-rbac --sdk-auth > my.azureauth"

Besides, you can also create auth file from the intelliJ plugin. When login, just select auto->create new.

**Comment by Eskibear** [comment]
Since interactive login is supported for Mooncake users, there is no need to manually generate a service principal file. Remove the hint in PR https://github.com/Microsoft/azure-tools-for-java/pull/1345
