### ISSUE TITLE
No processing file format in sign in form

### ISSUE THREAD

**Issue by kutsyk** [microsoft/azure-tools-for-java#1285]
Trying to sign in using credential files choosing some else file.
![image](https://user-images.githubusercontent.com/6589214/33616393-14e0f4c0-d9dd-11e7-9376-7c8327cbdfa3.png).

Next, proceed some error in parsing chosen file.
![image](https://user-images.githubusercontent.com/6589214/33616470-3c7058c8-d9dd-11e7-8651-bf0039e2d39a.png)

Next, a bunch of error that file services could not be loaded.
![image](https://user-images.githubusercontent.com/6589214/33616507-56bd04e2-d9dd-11e7-9481-3737e10973de.png).

In the result, it looks like an user is logged in:
![image](https://user-images.githubusercontent.com/6589214/33616573-8df0b0f8-d9dd-11e7-8b59-9472357cc4d9.png).
But it was not logged in and trying refreshing of services pops up a lot of error about failed loading of services.

**Comment by andxu** [comment]
@kutsyk Could you try to login again using service principles with arbitrary file types? I tested it should forbid you to do so now.
