### ISSUE TITLE
[IntelliJ2017.3] Can't create auth file 

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1288]
Both ultimate and community version
1. Automated -> New
2. Choose the subscription you will used
3. Click start
Result:
![image](https://user-images.githubusercontent.com/22470312/33653217-5109f8e6-daa7-11e7-8a0e-5aedc9be28c6.png)

**Comment by adashen** [comment]
@bsaby fixed, please verify on the latest build. And run more test on the intelliJ

**Comment by bsaby** [comment]
Test passed.
Build used: daily237
