### ISSUE TITLE
[Eclipse] The Azure context menu is shown for every element in project explorer

### ISSUE THREAD

**Issue by grafandreas** [microsoft/azure-tools-for-java#1289]
The Azure menu with its sign in / sign out menus are shown at the context menu of all elements in Package Explorer and Project Explorer. This clutters the UI and confuses users (why would I have an Azure menu on .java or. py files?)

The menu entries should probably be restricted to a certain type of element shown in the explorer.

**Comment by andxu** [comment]
We grouped  actions under azure sub menus, it will cause less distractions from user.
