### ISSUE TITLE
[Intellij 2017.3] cannot find suitable plugin version 

### ISSUE THREAD

**Issue by sashank** [Microsoft/azure-tools-for-java#1290]
Am currently on Intellij IDEA Community version Build 173.3727.127 version. 
I could not locate which version of azure tools plugin is suitable for this ? i tried the latest ones from the below link and they seem to be incompatible

https://plugins.jetbrains.com/plugin/8053-azure-toolkit-for-intellij

i tried to use this tutorial , it is installing very old version of plugin i.e. 1.5 

https://docs.microsoft.com/en-us/java/azure/intellij/azure-toolkit-for-intellij-installation

not sure how to install the azure tools  plugin

**Comment by Eskibear** [comment]
@sashank We have noticed the new version `2017.3`, and we will fix the issue in the next release of the azure tools plugin.

Related issues:
https://github.com/Microsoft/azure-tools-for-java/issues/1281
https://github.com/Microsoft/azure-tools-for-java/issues/1282

Related PR:
https://github.com/Microsoft/azure-tools-for-java/pull/1287

**Comment by wezhang** [comment]
Dup #1281
