### ISSUE TITLE
Revert fix for #1288 after intelliJ 2018 released

### ISSUE THREAD

**Issue by adashen** [microsoft/azure-tools-for-java#1294]
https://github.com/Microsoft/azure-tools-for-java/pull/1293 fixed #1288. The root cause is an intelliJ bug. And the fix will be in 2018. (https://github.com/JetBrains/intellij-community/commit/df6a596e15e2ffb0c2e6b6b4be8c4af0ef096a00#diff-52c7fa7387b3775c006937597017b726) So add an issue to track the status.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738847
