### ISSUE TITLE
[Intellij 2017.3]some words were truncated in configurations on windows

### ISSUE THREAD

**Issue by tankungx** [Microsoft/azure-tools-for-java#1298]
![image](https://user-images.githubusercontent.com/30617450/33875700-062cc3ec-df5e-11e7-81ab-bb783b776b6c.png)

**Comment by wezhang** [comment]
A 2017.3 regression,

Here is 2017.2 snapshot:
![image](https://user-images.githubusercontent.com/7385667/33980402-b4e8b96e-e0e3-11e7-8b2b-8bddb58ae265.png)

**Comment by ruoxinCheng** [comment]
Resolved.
