### ISSUE TITLE
<May be duplicate> Manage subscriptions let user open classic portal or upload publish settings

### ISSUE THREAD

**Issue by arroyc** [Microsoft/azure-tools-for-java#131]
![image](https://cloud.githubusercontent.com/assets/16231002/23081999/382441c8-f50c-11e6-90da-91ab5f1d7a14.png)

![image](https://cloud.githubusercontent.com/assets/16231002/23082010/450ff6ac-f50c-11e6-8394-8c8b6d743e7d.png)

![image](https://cloud.githubusercontent.com/assets/16231002/23082015/49d9693e-f50c-11e6-867d-282436bf8322.png)

**Comment by martinsawicki** [comment]
yeah, we'll want to remove this whole deprecated feature (access to P-S file, cloud services publishing etc) altogether at this point.

**Comment by lenala** [comment]
Fixed, please verify.

**Comment by bsaby** [comment]
Test passed in artifacts/azure-toolkit-for-intellij.177.zip
