### ISSUE TITLE
submit Spark job to the incorrect cluster 

### ISSUE THREAD

**Issue by voidfunction** [Microsoft/azure-tools-for-java#1312]
I'm trying to submit job to cluster **KunSparkBlob20**
![image](https://user-images.githubusercontent.com/6745693/34430091-e1421474-ec9b-11e7-895d-c1d088a1b280.png)

But seems the job was always submitted to the first cluster of cluster list.
![image](https://user-images.githubusercontent.com/6745693/34430095-ef91cfe2-ec9b-11e7-9dcd-f2064807ee75.png)

Here's the cluster list in submission window:
![image](https://user-images.githubusercontent.com/6745693/34430105-32e3f180-ec9c-11e7-859b-60c1cffa7df6.png)

**Comment by ruoxinCheng** [comment]
Resolved
