### ISSUE TITLE
the `apply` button should be disabled if the configuration is incorrenct

### ISSUE THREAD

**Issue by voidfunction** [Microsoft/azure-tools-for-java#1313]
The **apply** and **OK** button should be disabled if the configuration is incorrect:
![image](https://user-images.githubusercontent.com/6745693/34430289-6e91f6bc-ec9e-11e7-9f2f-c9346e593785.png)

**Comment by wezhang** [comment]
Click `apply` will pop up warning dialog.

**Comment by tankungx** [comment]
Fixed.

**Comment by v-jiche** [comment]
Verified. Fixed 
artifacts/azure-toolkit-for-intellij-2018.1.PR.2083.09-19-2018.zip
--
