### ISSUE TITLE
[Intellij][Spark][LocalRun]the environment variables list should be updated if the system environment changed

### ISSUE THREAD

**Issue by voidfunction** [microsoft/azure-tools-for-java#1316]
I just delete the system configuration and restart IntelliJ. Technically the environment variables should be null when I create a new run configuration.
![image](https://user-images.githubusercontent.com/6745693/34430924-f1245434-eca4-11e7-8e11-77b3cce012b9.png)

**Comment by wezhang** [comment]
It's a different meanings here. The Env vars stored is user defined, not reading from the System Environment.
