### ISSUE TITLE
Add HDInsight cluster short name on context menu

### ISSUE THREAD

**Issue by voidfunction** [microsoft/azure-tools-for-java#1317]
Something like ```Submit Spark Job 'Unnamed' to sparkclustername....```
![image](https://user-images.githubusercontent.com/6745693/34430998-b22fe4f4-eca5-11e7-81d7-5aec59b12892.png)

**Comment by wezhang** [comment]
Nice to have a context menu way to submit a job.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748183
