### ISSUE TITLE
When users are not using HDFS, we probably should not require them to configure WinUtils.exe

### ISSUE THREAD

**Issue by djlan** [Microsoft/azure-tools-for-java#1319]
This script does not have HDFS path:
![image](https://user-images.githubusercontent.com/26966861/34431328-32255fba-eca9-11e7-854a-c26e4c4f3bf2.png)

However we still require the existence of Winutils.exe:
![image](https://user-images.githubusercontent.com/26966861/34431350-5e961328-eca9-11e7-980f-5e813d1f07a0.png)

**Comment by djlan** [comment]
Another option is, can we add winutils.exe check when users click “ok” or “apply” when users creating configuration, it would be more user friendly then showing error later

**Comment by wezhang** [comment]
I'll fix the exception message to talk the user how to config it in Run/Debug configuration

**Comment by ruoxinCheng** [comment]
Resolved
