### ISSUE TITLE
Azure Explorer - Delay the creation of storage account

### ISSUE THREAD

**Issue by anuchandy** [microsoft/azure-tools-for-java#132]
In VM Create flow - when user choose to have a new storage account, after entering required params and clicking OK, explorer go ahead and creates storage account. We could delay storage account creation
and make it part of VirtualMachine.Create call. Virtual machine definition takes creatable storage 
account definition.

**Comment by martinsawicki** [comment]
future

**Comment by Flanker32** [comment]
Has implemented in the new release
