### ISSUE TITLE
[Intellij]Fail to submit “SparkSQLExample” to 2.1 cluster via right-clicking project node to submit job

### ISSUE THREAD

**Issue by tankungx** [Microsoft/azure-tools-for-java#1321]
![image](https://user-images.githubusercontent.com/30617450/34432232-7b05df3c-ecb0-11e7-96ad-dcf940ebbef6.png)
User class threw exception: java.lang.NoSuchMethodError: org.apache.spark.sql.Dataset.createGlobalTempView(Ljava/lang/String;)V ======================Finish printing out spark job log.======================= Error : Your submitted job run failed 
See detailed job information from https://zhwe-spkdbg2.azurehdinsight.net//yarnui/hn/cluster/app/application_1511284610088_0189 See detailed job log from local:C:\Users\v-kuntan\.IdeaIC2017.3\config\plugins\azure-toolkit-for-intellij\SparkJobLog\application_1511284610088_0189\log.txt

**Comment by wezhang** [comment]
Dup #1312
