### ISSUE TITLE
[IntelliJ] The option 'submit spark application to cluster' will disable when I select an not found cluster

### ISSUE THREAD

**Issue by ruoxinCheng** [Microsoft/azure-tools-for-java#1326]
1. Select the option  'submit spark application to cluster'.
2. I select the cluster with wasbs storage,
3. Then it shows bellow error:
Info : Build file://C:/Users/v-rouche/IdeaProjects/SBT202/out/artifacts/sbt202_DefaultArtifact/default_artifact.jar successfully. Error : Failed to submit application to spark cluster. Exception : Failed to get default storage account name Selected Cluster can not found. Please login in first in HDInsight Explorer and try submit job again
Actual:  the option also disabled.
![image](https://user-images.githubusercontent.com/20041888/34662447-a7313ce0-f48b-11e7-93a9-d4aa6746ae9c.png)

**Comment by wezhang** [comment]
reproed

**Comment by ruoxinCheng** [comment]
Verified.
