### ISSUE TITLE
Explorer: Should make it more obvious Docker Host node needs to be expanded to see Containers

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#133]
After expanding Docker Hosts node in explorer, there is no indication on the individual Docker host nodes that they might contain children (containers) and that the user needs to take action (refresh) to get the containers to show. This is not discoverable. What would be better is what some other popular explorers do that fill their nodes lazily: make the Docker Host show as if it has children, only in a collapse state (maybe placeholder node named "(Loading...)". So that way, when the user expands that node, that trigger the refresh. This way the user will know there is something expandable about that node. If the node turns out to have no children, THEN we remove the placeholder and the node shows up as empty, which reflects its true state.

**Comment by milismsft** [comment]
In the current UI design the node will refresh the first time the user clicks on it. If the node has any children, they will become available after the refresh completes.
