### ISSUE TITLE
[Intellij] Submit WasbIOTest sample to adls cluster will throw exception

### ISSUE THREAD

**Issue by QiaohongLiu** [Microsoft/azure-tools-for-java#1331]
YARN Diagnostics: 
User class threw exception: java.lang.IllegalArgumentException: Cannot initialize WASB file system, URI authority not recognized. 

Maybe we can change the sample or disable the adls cluster.

**Comment by wezhang** [comment]
The case `WasbIOTest` is only for Wasb IO test. 😄

**Comment by wezhang** [comment]
Maybe we can change the sample without scheme and make it available for ADLS/Wasb/Wasbs
