### ISSUE TITLE
[IntelliJ][Spark][local][RunConf] Even if set system variables, it still show 'not set winutil.exe'

### ISSUE THREAD

**Issue by ruoxinCheng** [Microsoft/azure-tools-for-java#1334]
1. Not set system variables, you can delete it.
2. Install our plugin.
3. Run 'local run' by context menu, it then show the error, ask you to set winutil.exe.
4. To set the location of  the winutil.exe, click ok to save it.
Actual: click 'local run' by context menu, it always say to set winutil. you need to trigger another configuration can work.

**Comment by wezhang** [comment]
Let's auto fix this issue
