### ISSUE TITLE
[Eclipse][Linux] Can not find locally created app insights in portal

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#1343]
![image](https://user-images.githubusercontent.com/22470312/34975411-90bca02a-facc-11e7-9e8d-01de2fb74448.png)
portal:
![image](https://user-images.githubusercontent.com/22470312/34975168-87c3eb50-facb-11e7-9106-f744c6731f8c.png)

**Comment by pl07** [comment]
Test pass in azure java toolkit for eclipse 3.23.0.
