### ISSUE TITLE
Uploading a WebApp via FTP fails in AzureGermanCloud because of FTPS server

### ISSUE THREAD

**Issue by rmontag-ap** [microsoft/azure-tools-for-java#1353]
### Environment ###

_Eclipse: Neon.3 Release (4.6.3)
    Azure Common Plugin	3.2.0.201801100754
    Azure Container Tools for Eclipse	3.2.0.201801100754
    Azure Containers for Eclipse	3.2.0.201801100754
    Azure Explorer for Eclipse	3.2.0.201801100754
    Azure HDInsight plugin for Java	3.2.0.201801100754_

### Problem ### 
When deploying a WebApp to AzureGermanCloud, the FTP upload fails with the following error:

```
java.net.ConnectException: Unable to login to FTP server
	at com.microsoft.azuretools.utils.WebAppUtils.getFtpConnection(WebAppUtils.java:87)
	at com.microsoft.azuretools.utils.WebAppUtils.deployArtifact(WebAppUtils.java:108)
	at com.microsoft.azuretools.webapp.ui.WebAppDeployDialog$9.run(WebAppDeployDialog.java:599)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

The FTP server for AzureGermanCloud is **dews-prod-fr1-001.ftp.azurewebsites.cloudapi.de**

When issuing the ftp commang from command-line, the FTP servers gives an **_534 Policy requires SSL._**:
```
$ ftp dews-prod-fr1-001.ftp.azurewebsites.cloudapi.de
Connected to dews-prod-fr1-001.drip.azurewebsites.cloudapi.de.
220 Microsoft FTP Service
Name (dews-prod-fr1-001.drip.azurewebsites.cloudapi.de:x12345):
534 Policy requires SSL.
ftp: Login failed.
421 Service not available, remote server has closed connection
ftp>
```

So the FTP server in AzureGermanCloud is using FTPS.

Checking the java code in ```com.microsoft.azuretools.utils.WebAppUtils``` the ```getFtpConnection()``` method is using the ```org.apache.commons.net.ftp.FTPClient``` class for connecting. I was able to reproduce the error extracting the code from the method in a separate test class using the above FTP url.

### Possible Solution ###

I was able to write a test class using the ```org.apache.commons.net.ftp.FTPSClient``` to login successfully:
```
...
import org.apache.commons.net.ftp.FTPSClient;
...
public class TestFTPS {

	public static void main(String[] args) throws SocketException, IOException {

		String ftpUrl= "dews-prod-fr1-001.ftp.azurewebsites.cloudapi.de/site/wwwroot";
		String ftpUser = ...;
		String ftpPwd = ...;

		URI uri = URI.create("ftp://" + ftpUrl);
		
		FTPSClient c = new FTPSClient("SSL", false);
		c.setTrustManager(TrustManagerUtils.getValidateServerCertificateTrustManager());
		c.connect(uri.getHost(), 21);
		
		if (!c.login(ftpUser, ftpPwd)) {
			throw new ConnectException("Unable to login to FTP server");
		}

		c.setControlKeepAliveTimeout(10000);
		c.setFileType(FTP.BINARY_FILE_TYPE);
		c.execPBSZ(0); // Set protection buffer size
		c.execPROT("P"); // Set data channel protection to private
		c.enterLocalPassiveMode();

                // do something with established ftp session
		c.changeWorkingDirectory("/site/wwwroot/");
		FTPFile[] files = c.listFiles();
		c.logout();
		for (FTPFile file :files) {
			System.out.println(file.getName());
		}
	}
```

which gave me the content of the folder:
```
hostingstart.html
webapps
```

**Comment by andxu** [comment]
hi @rmontag-ap, could you please try our latest version which has already switched to kudo deploy (HTTPS) from ftp, and tell us whether you can deploy or not?

**Comment by rmontag-ap** [comment]
Hi, I'm am not working with with AzureGermany anymore, so I can't test.
