### ISSUE TITLE
[Azure Toolkit][Blocking Issue][A11yMAS][Accessibility][Narrator/Inspect][MAS4.1.1][IntelliJ][Wipro] :Narrator and Inspect are not working for IntelliJ IDEA Application

### ISSUE THREAD

**Issue by WiproPSAccTest** [Microsoft/azure-tools-for-java#1357]
**Repro Steps:**

1.  Open and Start IntelliJ IDEA.
2.  Open your project with IntelliJ IDEA.
3.  Navigate to Tools menu, point to "Azure", and then select "Azure Sign In" then try to access all the interactive elements by using Inspect and Narrator 

**Expected Result:**
Narrator and Inspect focus should go for all the interactive elements present in IntelliJ IDEA Application

**Actual Result:**
Narrator and Inspect focus are moving only for the Dialog .
Narrator and Inspect focus are not moving for interactive elements present inside the Dialog for IntelliJ IDEA Application

**Platform:**
IntelliJ IDEA 2017.3.2(Community Edition)
Build #IC-173.4127.27
JRE:1.8.0_152-release-1024-b8 amd64
OS version : 1709
OS build : 16299.192

![image](https://user-images.githubusercontent.com/22956130/35498625-16f154a6-04f5-11e8-962f-14e2eb2f3f63.png)
![image](https://user-images.githubusercontent.com/22956130/35498668-4232caf0-04f5-11e8-825f-00ce5fae3ea6.png)

**Comment by Eskibear** [comment]
In IntelliJ IDEA, according to our testing, NVDA/Inspect/Narrator can only recongnize title of the dialogs.

Seems that accessibility is a long existing issue for IntelliJ IDEA.


References:
https://youtrack.jetbrains.com/issue/IDEA-111425

**Comment by vscjavaci** [comment]
Track internal issue by AB#1749825
