### ISSUE TITLE
[IntelliJ] [Eclipse]show "passWord is null" when submitting jobs on security hadoop cluster under subscription

### ISSUE THREAD

**Issue by tankungx** [Microsoft/azure-tools-for-java#1362]
Steps:
1. Sign in to get clusters(security hadoop cluster) through selecting some subscriptions.
2. Submit job to security hadoop cluster(e.g. zhwe-secspk-quick)

Actual:
List spark clusters ...
List spark clusters successfully
List additional spark clusters successfully
Info : Get target jar from /home/linux16/eclipsekunworkspace1/ScalaCLuster/ScalaCLuster.jar.
Info : Begin uploading file /home/linux16/eclipsekunworkspace1/ScalaCLuster/ScalaCLuster.jar to Azure Blob Storage Account wasbs://zhwe-secspk-quick@zhwesechdiusw.blob.core.windows.net/SparkSubmission/2018/00/31/0eb232fd-2db9-486d-bef6-6acb485694b4/ScalaCLuster.jar ...
Info : Submit file to azure blob 'wasbs://zhwe-secspk-quick@zhwesechdiusw.blob.core.windows.net/SparkSubmission/2018/00/31/0eb232fd-2db9-486d-bef6-6acb485694b4/ScalaCLuster.jar' successfully.
Error : Failed to submit application to spark cluster. ****Exception : passWord is null,**** please call getConfigurationInfo first
See detailed job information from https://zhwe-secspk-quick.azurehdinsight.net//yarnui/hn/cluster/app/application_1515077284554_0042
See detailed job log from local:/home/linux16/eclipse/../.eclipse/org.eclipse.platform_4.6.3_2037014064_linux_gtk_x86_64/configuration/org.eclipse.osgi/164/data/-1638366702/plugins/SparkJobLog/application_1515077284554_0042/log.txt

**Comment by wezhang** [comment]
The cluster is a Secure HDInsight with cluster domain account enabled, please open the HDInsight cluster context menu in Azure explorer and select `Link a cluster` to link the cluster with domain accounts.
