### ISSUE TITLE
Create Storage Account -> OK button does not get enabled after right inputs

### ISSUE THREAD

**Issue by anudeepsharma** [Microsoft/azure-tools-for-java#138]
1. Right click on storage Accounts.
2. Click Create new storage account.
3. Provide valid name.
4. Click on use Existing storage account.
5. Let the resource group be what it is already selected.

OK button is not getting enabled.

If you select the resource group explicitly even the same, then OK button is getting enabled.

Another issue, text in blue is not readable above OK/Cancel buttons. I am using Dracula on IntelliJ on MAC.
<img width="447" alt="screen shot 2017-02-17 at 12 35 49 pm" src="https://cloud.githubusercontent.com/assets/6544078/23082351/dccb7330-f50d-11e6-8611-1043cad12927.png">

**Comment by lenala** [comment]
Fixed for enabling OK button.
Separate issue will be created for links color in Dracula.

**Comment by davidliangze** [comment]
We don't have machines with Mac OS.

OS: Windows 10 Enterprise X64 ENU
IDE: IntelliJ 2017.1.1
Test build: azure-toolkit-for-intellij.2017.303.04-16-2017

Test passed.
