### ISSUE TITLE
After publishing a Docker Container, can't refresh the containers list in explorer

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#139]
1. open the explorer
2. show the containers in some docker host
3. on docker host node, click Publish and republish some app you published before
4. after publish is done, click refresh on the Containers node
RESULT: THe list of containers disappears, and refresh doesn't happen. Refresh is broken until you refresh the Docker Hosts node itself and go from there

**Comment by selvasingh** [comment]
Observed the same behavior. But never refreshed and threw an unexpected param values exception

**Comment by milismsft** [comment]
also:
Using INtelliJ, create a new docker host and publish a container
After it's successful, open the Publish as Docker Container dialog again
RESULT: The status of the docker host created earlier still shows as STARTING
EXPECT: RUNNING

**Comment by selvasingh** [comment]
@milismsft please check if this is already fixed

**Comment by bsaby** [comment]
Test passed, using artifacts/azure-toolkit-for-intellij.2017.333.04-18-2017.zip.

- Refresh successfully
- After it's successful, open the Publish as Docker Container dialog again, the status of the docker host created earlier shows as RUNNING
