### ISSUE TITLE
Container Workflow - looks like success, but unexpected param values error

### ISSUE THREAD

**Issue by selvasingh** [Microsoft/azure-tools-for-java#141]
![image](https://cloud.githubusercontent.com/assets/3642444/23082424/1845d4aa-f50e-11e6-9696-aeb67d66415e.png)

**Comment by selvasingh** [comment]
For this scenario, I completed the workflow. It successfully created everything

**Comment by milismsft** [comment]
should be fixed in the latest version. The error was caused by failing to create the corresponding Key Vault.

**Comment by bsaby** [comment]
Not repro in azure-toolkit-for-intellij.215.zip
