### ISSUE TITLE
Message boxes are too wide

### ISSUE THREAD

**Issue by rmcmurray** [Microsoft/azure-tools-for-java#142]
The message boxes which are displayed when deleting or shutting down a virtual machine are too wide; the text should be wrapped to make the dialog boxes fit better on screen. For example:

Here is the Delete VM prompt in build #165:
![delete_vm_original](https://cloud.githubusercontent.com/assets/3290593/23082486/d5eab220-f516-11e6-95e1-dfc430568f7f.png)

It would be better like the following:
![delete_vm_suggested](https://cloud.githubusercontent.com/assets/3290593/23082487/d5eb5842-f516-11e6-90a8-60b4b4b825cc.png)

In a like manner, here is the Shutdown VM prompt in build #165:
![shutdown_vm_original](https://cloud.githubusercontent.com/assets/3290593/23082488/d5ececac-f516-11e6-9e36-246247a7073a.png)

It would be better like the following:
![shutdown_vm_suggested](https://cloud.githubusercontent.com/assets/3290593/23082485/d5e90d30-f516-11e6-8af7-b0589db9c2a0.png)

**Comment by lenala** [comment]
Fixed, please verify.

**Comment by bsaby** [comment]
Test passed in artifacts/azure-toolkit-for-intellij.229.zip
