### ISSUE TITLE
Password error message from Azure when trying to create Docker host

### ISSUE THREAD

**Issue by lenala** [Microsoft/azure-tools-for-java#143]
When trying to create Docker host with password not meeting Azure requirements, error is returned from Azure. This can be handled on client side.
![image](https://cloud.githubusercontent.com/assets/6208231/23082429/1e6dc2ca-f50e-11e6-8c78-111aaa396ac5.png)

**Comment by milismsft** [comment]
fixed

**Comment by bsaby** [comment]
Repro in artifacts/azure-toolkit-for-intellij.225.zip
![image](https://cloud.githubusercontent.com/assets/22470312/23451686/ef88dd2c-fe9b-11e6-8a08-6aeeed4eb6b6.png)
Repro steps:
1.Input password which not meeting Azure requirements, for example : **test12345678** 
2.Input Confirm password.
3.Click Finish in Create Docker Host dialog
4.Click Finish in Deploy Docker Container on Azure dialog

Expected:
There is a red exclamation mark occurred  if password does not meet the Azure requirements, unless change the password that meeting requirements.

Actual:
There is an prompt error after input the password which not meeting Azure requirements, but after input confirm password in confirm box and click the password box again, the red exclamation mark disappeared and no error prompt.
![image](https://cloud.githubusercontent.com/assets/22470312/23451609/98758a26-fe9b-11e6-928e-805508e61df9.png)
![image](https://cloud.githubusercontent.com/assets/22470312/23451602/895b9de6-fe9b-11e6-9ebd-54cc5ff6433c.png)

**Comment by milismsft** [comment]
Should be fixed now.

**Comment by bsaby** [comment]
Test passed inartifacts/azure-toolkit-for-intellij.82.zip.
The cursor can not leave the password box until the input is valid when typing password not meeting Azure requirements,
