### ISSUE TITLE
TODO - Unable to deploy Spring Pet Clinic (Using Spring Boot) into Azure App Service

### ISSUE THREAD

**Issue by selvasingh** [Microsoft/azure-tools-for-java#145]
Here is the sample app https://github.com/spring-projects/spring-petclinic

**Comment by martinsawicki** [comment]
1. Let's confirm first that if you start with a proper Springboot module in IJ, you can deploy  it as an Azure webapp
2. Then see how to import a Java project into IntelliJ as a proper Springboot project, if it wasn't originally created that way

**Comment by jdneo** [comment]
Supported since v3.0.8
