### ISSUE TITLE
TODO - Unable to deploy Spring Pet Clinic (Using Spring Boot) into Containers Running on a Virtual Machine

### ISSUE THREAD

**Issue by selvasingh** [Microsoft/azure-tools-for-java#146]
Here is the sample app https://github.com/spring-projects/spring-petclinic

**Comment by milismsft** [comment]
I presume you tried this via the "Custom Dockerfile" option; what's the content of the Dockerfile you tried with?

**Comment by martinsawicki** [comment]
as discussed:
- follow the Custom file path, but in v3.0 you need to create your dockerfile that knows how to deploy a Springboot package. You need to select the packaged JAR artifact earlier in the wizard, and it your dockerfile, you should be able to reference it by its file name. But you need to write the dockerfiles steps to deploy this on top of a JDK-containing image (which you also need to reference explicitly in the Dockerfile, e.g. `from java8` or the like, `add app.jar`, and eventually something like `run java app.jar`.

See if you can get it to work this way in v3.

**Comment by selvasingh** [comment]
@bsaby - may we request you to try this scenario and publish to a docker host?

**Comment by bsaby** [comment]
Test passed in IntelliJ.
Build used:artifacts/azure-toolkit-for-intellij.2017.373.04-25-2017.zip.
The Spring Pet Clinic is successfully deployed using the Predefined Docker image or the custom Dockerfile.
