### ISSUE TITLE
Suggestions for changing the Create VM wizard

### ISSUE THREAD

**Issue by rmcmurray** [microsoft/azure-tools-for-java#147]
When running the **Create VM** wizard, there are a few UI quirks which seem counter-intuitive, as well as several features which have no descriptions for new customers, and there are some better ways to use the available UI.

### Page 1 of the Create VM Wizard

In the first page, customers are presented with a list box which *seems* like it should do something when you click on the available choices (since that's what list boxes are designed to do). However, the entries are merely used as a progress indicator for the wizard; this is both counter-intuitive and an inefficient use of the available space. In addition, it is not readily apparent what the **settings** icon will do.

![create_vm_page1_original](https://cloud.githubusercontent.com/assets/3290593/23084482/baf57578-f51f-11e6-93ed-7c1da5e82a1b.png)

My suggestion for the first page is to remove the list box and replace it with a more space-efficient progress indicator in its place, then remove the **settings** icon and add a **Select Subscriptions** entry to the drop-down menu in its place, then add context-aware help tips in some of the unused dialog box space.

![create_vm_page1_sugested](https://cloud.githubusercontent.com/assets/3290593/23084604/6543a360-f520-11e6-9716-200bfbb6fe17.png)

### Page 2 of the Create VM Wizard

In the second page, customers are once again presented with a counter-intuitive list box, as well as several fields with no descriptions as to what they mean, and there is a great deal of unused space.

![create_vm_page2_original](https://cloud.githubusercontent.com/assets/3290593/23084678/c9e35aa4-f520-11e6-88a3-69b4dfd249a8.png)

My suggestion for the second page is to remove the list box again and replace it with a progress indicator, and add context-aware help tips in some of the unused dialog box space.

![create_vm_page2_sugested](https://cloud.githubusercontent.com/assets/3290593/23084704/ef9a3a74-f520-11e6-8429-8041f08bde7e.png)

### Page 3 of the Create VM Wizard

The third page is much like the second page: customers are once again presented with a counter-intuitive list box, as well as several fields with no descriptions as to what they mean, and there is a great deal of unused space.

![create_vm_page3_original](https://cloud.githubusercontent.com/assets/3290593/23084721/0fdac150-f521-11e6-913b-9dc949e608d7.png)

My suggestion for the third page is to remove the list box again and replace it with a progress indicator, and add context-aware help tips in some of the unused dialog box space.

![create_vm_page3_sugested](https://cloud.githubusercontent.com/assets/3290593/23084742/2394ba20-f521-11e6-8cc6-d69457759132.png)

### Page 4 of the Create VM Wizard

The fourth page is like the second and third pages: customers are once again presented with a counter-intuitive list box, as well as several fields with no descriptions as to what they mean, and there is a great deal of unused space.

![create_vm_page4_original](https://cloud.githubusercontent.com/assets/3290593/23084761/3b9f55f8-f521-11e6-95a8-e0592eb82283.png)

My suggestion for the fourth page is to remove the list box again and replace it with a progress indicator, and add context-aware help tips in some of the unused dialog box space.

![create_vm_page4_sugested](https://cloud.githubusercontent.com/assets/3290593/23084780/54e228ba-f521-11e6-93ac-e2a1c22d4989.png)

### Summary

I think that removing the list box and replacing it with a progress indicator will make it easier for customers to understand how to use this wizard, and it will allow the dialog box to be resized to better dimensions. In addition, some of the unused space on the dialog box could be used to provide context-aware descriptions for the different fields in the wizard, which will help customers understand the importance of each field, and we can provide links which will guide customers to more detail in our documentation.

**Comment by andxu** [comment]
The wizard is deprecated.
![image](https://user-images.githubusercontent.com/17075863/144177562-a943d66b-38c1-483d-96ae-4b98e2bf5d34.png)
![image](https://user-images.githubusercontent.com/17075863/144177573-2030874f-e5c9-401d-a8f1-015e403a2336.png)
![image](https://user-images.githubusercontent.com/17075863/144177589-c120ab60-3de4-4921-a4bd-799a8f4df584.png)
