### ISSUE TITLE
Can't configure Proxy

### ISSUE THREAD

**Issue by grimsi** [microsoft/azure-tools-for-java#148]
Unfortunatly I cant deploy any webapps to azure because my company uses a proxy-server.
I can login, but then it wont show any subscriptions and just freezes.

**Comment by syr** [comment]
Same problem here, please add proxy support, even if it can be set in a file...so no fancy UI needed ;)

**Comment by andxu** [comment]
we need to enable proxy in  Application Insights client (com.microsoft.applicationinsights.internal.channel.simplehttp.SimpleHttpChannel::send(), Apache client)

**Comment by andxu** [comment]
Already implemented in 3.56.0
![image](https://user-images.githubusercontent.com/17075863/144177722-af1b702f-aebd-4853-a198-cc5b00f31616.png)
