### ISSUE TITLE
Eclipse - Configure Application Insights options - missing file's error

### ISSUE THREAD

**Issue by 0GiS0** [Microsoft/azure-tools-for-java#149]
I’ve noticed when I try to configure Application Insights I get this error:

![missing file](https://cloud.githubusercontent.com/assets/175379/23271301/4e301aa6-f9f7-11e6-909f-526f74fd1527.png)

When I install the Azure Tools if I access to that folder I only find this:

![eclipse - app insights - missing file](https://cloud.githubusercontent.com/assets/175379/23271232/0ae9af14-f9f7-11e6-875b-f83c7d7fcb14.png)

The azure-core-0.9.2.jar doesn’t exist ☹

Thanks

**Comment by lenala** [comment]
This is fixed, please verify for Eclipse and IntelliJ.

**Comment by lenala** [comment]
Fixed, please verify, both for Eclipse and IntelliJ.

**Comment by lenala** [comment]
Hopefully fixed this time.

**Comment by bsaby** [comment]
Good news.
Test passed in Eclipse and IntelliJ, using 
artifacts/WindowsAzurePlugin4EJ.**286**.04-13-2017.zip.
artifacts/azure-toolkit-for-intellij.2017.**282**.04-13-2017.zip
