### ISSUE TITLE
Azure Explorer shows repeated "Refreshing..." statuses

### ISSUE THREAD

**Issue by rmcmurray** [Microsoft/azure-tools-for-java#150]
When using build 190 of the Azure Toolkit for Eclipse, I get the following error when I right-click on my subscription in the Azure Explorer and choose **Refresh**:

![eclipse_refresh_error_01](https://cloud.githubusercontent.com/assets/3290593/23315882/5b40bb54-fa85-11e6-9a0e-c97dd852374e.png)

Then after the error occurs, the "Refreshing..." text is repeated multiple times (once for each attempted refresh):

![eclipse_refresh_error_02](https://cloud.githubusercontent.com/assets/3290593/23315920/87cf2390-fa85-11e6-8bdc-50ccd663f54a.png)

**Comment by lenala** [comment]
Looks like this was fixed, please verify.

**Comment by bsaby** [comment]
Repro in Azure Toolkit for **Eclispe** used: artifacts/WindowsAzurePlugin4EJ.256.zip
Not repro in Azure Toolkit for **IntelliJ** used :artifacts/azure-toolkit-for-intellij.258.zip
![image](https://cloud.githubusercontent.com/assets/22470312/23686733/5cb812ba-03e6-11e7-9a23-44f3309e8f58.png)

**Comment by milismsft** [comment]
Hi Mona,

can you please pick-up the builds from the work/v3.0.0 branch?

**Comment by bsaby** [comment]
How do I get builds  from the work/v3.0.0 branch? Could you provide me with address?

**Comment by bsaby** [comment]
Fixed and test passed in artifacts/WindowsAzurePlugin4EJ.67.zip.
