### ISSUE TITLE
Title casing should be used in dialog captions (e.g. progress bar for Docker creation)

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#151]
Title casing means each word starts with a capital letter, except for propositions, and all articles ("the", "a")are omitted.

for example, instead of "Deploying a Docker container hosted on Azure", we should say:
"Deploying Docker Container on Azure"

**Comment by milismsft** [comment]
fixed

**Comment by bsaby** [comment]
Test passed in artifacts/azure-toolkit-for-intellij.225.zip
