### ISSUE TITLE
[Azure Toolkit][A11yMAS][Accessibility][JAWS/NVDA][MAS4.2.1][IntelliJ][Wipro]:NVDA and Jaws are not announcing the content present in  Run on Web App Dialog sequentially .

### ISSUE THREAD

**Issue by WiproPSAccTest** [Microsoft/azure-tools-for-java#1513]
**Repro Steps:**

1. Open and Start IntelliJ IDEA.
2. Create a new project.
3. Tab to and select created Project ->Azure->Run on web app.
4. "Run on web app" dialog will open.
5. In Run on web App dialog, Press "Insert+B" to read  the entire dialog then observe the NVDA and JAWS Behavior

**Expected Result:**
NVDA and Jaws Should annouunce in the following manner

- Run on Web App  dialog  
- Name:  edit  alt+N
- Azure Web App: sample:sample
- Share  check box  not checked  alt+S
- Single instance only  check box  not checked  alt+I
- Use Existing Web App  radio button  checked  1 of 2
  Create New Web App  radio button  not checked  2 of 2
- Choose Web App  panel
- Refresh  button  Refresh
- table
  Name header
  JDK header
  Web container header
  Resource group header
 webapp-180112171944
 1.8
TOMCAT 8.5
adobe-rg
 webapp-180201014444
1.8
TOMCAT 8.5
rg-webapp-180201014444
- Artifact combo box  collapsed
  Please check the web.config file used to deploy this non-WAR executable.  link
- Before launch: Activate tool window  alt+B
  separator
Add (Alt+Insert)  button  Add (Alt+Insert)
Remove (Alt+Delete)  button  Remove (Alt+Delete)
Edit (Enter)  button  Edit (Enter)
Up (Alt+Up)  button  Up (Alt+Up)
 Down (Alt+Down)  button  Down (Alt+Down)
 list
-  Show this page  check box  not checked
 Activate tool window  check box  checked
- button  Show help contents
- Run  button
- Cancel  button
- Apply  button  alt+A

**Actual Result:**
**NVDA Behavior:** NVDA is annoucing as
Run on Web App  dialog  Artifact
Please check the web.config file used to deploy this non-WAR executable.
Before launch: Activate tool window
Use Existing Web App  radio button  checked  1 of 2
Create New Web App  radio button  not checked  2 of 2
Choose Web App  panel
table
webapp-180112171944
1.8
TOMCAT 8.5
adobe-rg
webapp-180201014444
1.8
TOMCAT 8.5
rg-webapp-180201014444
Name
JDK
Web container
Resource group
Refresh  button  Refresh
Artifact
combo box  collapsed
Please check the web.config file used to deploy this non-WAR executable.  link
Before launch: Activate tool window  alt+B
separator
list
Add (Alt+Insert)  button  Add (Alt+Insert)
Remove (Alt+Delete)  button  Remove (Alt+Delete)
Edit (Enter)  button  Edit (Enter)
Up (Alt+Up)  button  Up (Alt+Up)
Down (Alt+Down)  button  Down (Alt+Down)
Show this page  check box  not checked
Activate tool window  check box  checked
Name:  alt+N
Name:  edit  alt+N
Azure Web App: sample:sample
Share  check box  not checked  alt+S
Single instance only  check box  not checked  alt+I
button  Show help contents
filler
Run  button
Cancel  button
Apply  button  alt+A
**Jaws Behavior:**
Run on Web App dialog
Name JDK Web container Resource group Artifact Before launch: Launch Web Browser, Build Artifacts, Activate tool window 
Show help contents Button

**Platform:**
IntelliJ IDEA 2017.3.2 (Community edition)
Build# IC-173.4127.27
JRE:1.8.0_152-release-1024-b8amd64
JVM: OpenJDK 64 Bit Server VM by Jet brains.
OSBuild Version: Version 1709(Os Build 16299.192)

![run on web app-insert-b](https://user-images.githubusercontent.com/22956130/36150093-744035ba-10e8-11e8-86c5-7fd90b4aa9c6.jpg)
![hierarcy is incorrect for run on web app window](https://user-images.githubusercontent.com/22956130/36150100-7e17a140-10e8-11e8-9c12-863cd64ef9b5.jpg)

**Comment by Eskibear** [comment]
duplicate with #1516

**Comment by vscjavaci** [comment]
Track internal issue by AB#1749982
