### ISSUE TITLE
After VM Shutdown command from Exlorer context menu, Shutdown should be disabled

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#153]
right now, after user selects Shutdown on a VM, the shutdown begins (and the icon changes) but the Shutdown command is still enabled. 
Expected: Shutdown command to be disabled when shutting down (and after shutdown)

**Comment by lenala** [comment]
Fixed, please verify.

**Comment by bsaby** [comment]
Test passed in artifacts/azure-toolkit-for-intellij.225.zip

**Comment by lenala** [comment]
Fixed now.

**Comment by bsaby** [comment]
Test passed in artifacts/azure-toolkit-for-intellij.229.zip
