### ISSUE TITLE
[Intellij] App is throttled, telemetries are blocked from now, for 300 seconds

### ISSUE THREAD

**Issue by wezhang** [Microsoft/azure-tools-for-java#1533]
```
AI: TRACE 27-02-2018 20:29, 112: App is throttled, telemetries are blocked from now, for 300 seconds
```

**Comment by sijucm** [comment]
It is 2021 and I face this issue in Visual studio code when trying to create a new function. It just keeps on giving this message and I have no clue what is happening here. What telemetry when creating a local function. Microsoft thinks there is no need to give any extra information to the stupid developer, yes, but then please create things that work. 
What I'm trying: To create a new local Azure function (java) with StorageBus Trigger.
It is stuck at the step of creating with that message: 
AI: TRACE 02-03-2021 11:27, 30: App is throttled, telemetries are blocked from now, for 300 seconds
AI: TRACE 02-03-2021 11:32, 28: App is throttled is cancelled
AI: TRACE 02-03-2021 11:32, 31: App is throttled is cancelled
