### ISSUE TITLE
[Eclipse] The log message could not scroll down to show the latest info automatically

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#1537]
Repro Steps:
1. Submit a job in Eclips, check the log info

Result:
The log message could not scroll down automatically
![image](https://user-images.githubusercontent.com/36756024/36963993-3e1c1c80-2090-11e8-892b-ed2c80f02812.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748182
