### ISSUE TITLE
[IntelliJ] numExecutors not saved when create configure file for the first time.

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1548]
Repro Steps:
1. Create a new project, no configure file yet
2. Right click on "LogQuery"\"Create [Spark Job] LogQuery"
3. Choose "Remotely Run in Cluster"
4. Enter "2" in "Job configurations\numExecutors", and keep the focus on the field
5. Click "OK"

Result:
Reopen the configure file, the “2” is not saved

Note: only happen at the first time.

**Comment by jingyanjingyan** [comment]
key step: Create configure file from context menu, and keep the focus on the field.
attach the screenshort
![image](https://user-images.githubusercontent.com/36756024/37954583-db353d4a-31d8-11e8-8cd1-6bdba109663d.png)

**Comment by wezhang** [comment]
Thanks! One simple workaround is to click any other places to force the input field's focus lost, then the value can be saved.
