### ISSUE TITLE
[IntelliJ] continue debugging get errors

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1549]
Repro Steps:
1. Set configure file and remote debug like "SparkCore_WebIOTest", success
2. Edit output, click Re-debug button, start to debugging

Result:
![image](https://user-images.githubusercontent.com/36756024/37956942-46582500-31df-11e8-8a11-fdbf45f23aa8.png)

**Comment by wezhang** [comment]
Only occurred in password SSH auth type.
