### ISSUE TITLE
IntelliJ publish progress bar never reaches 100%

### ISSUE THREAD

**Issue by shaunm-msft** [Microsoft/azure-tools-for-java#155]
When publishing a web app from IntelliJ, the progress bar never reaches 100% even though the publish is completed.

![intellijprogressbar](https://cloud.githubusercontent.com/assets/2079544/23533544/47f70724-ff67-11e6-9404-2f45f8061b68.PNG)

**Comment by martinsawicki** [comment]
@shaunm-msft - using a nightly build or last published release?

**Comment by shaunm-msft** [comment]
I used the last published release

**Comment by martinsawicki** [comment]
@vladimir-shcherbakov looks familiar?  probably already addressed in v3.0?

**Comment by songkaiape** [comment]
Reproduced this  issue  in azure-toolkit-for-intellij.14.zip

**Comment by martinsawicki** [comment]
Vlad re-fixed it again - try again pls

**Comment by bsaby** [comment]
Not repro in artifacts/azure-toolkit-for-intellij.29.zip
