### ISSUE TITLE
[IntelliJ][Spark][Sample][local][Streaming]Warning pop up when using file"SparkStreaming_HdfsWordCount" to submit

### ISSUE THREAD

**Issue by tankungx** [microsoft/azure-tools-for-java#1550]
![image](https://user-images.githubusercontent.com/30617450/37958442-206c9836-31e3-11e8-81b9-0b05ae93b20f.png)

**Comment by wezhang** [comment]
It's an old sample case issue.

**Comment by wezhang** [comment]
The current Spark local file mock doesn't support SparkStreaming.

**Comment by wezhang** [comment]
WORKAROUND:

Use directory as text file stream input can mitigate the issue:

```
val lines = ssc.textFileStream("wasb:///HdiSamples/HdiSamples/FoodInspectionData/")
```

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748181
