### ISSUE TITLE
Sometimes creating sp using our commonly  test subscription will fail 

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#1564]
Failures appear on our commonly used test subscriptions: Java Dev Experience Tests With TTL = 7Days

Two subscriptions are used in the following example
1. Java Lib Tests with TTL = 7 Days
2. Java Dev Experience Tests With TTL = 7Days
![image](https://user-images.githubusercontent.com/22470312/38127106-38d45fd0-3427-11e8-953a-807022564af7.png)

Report:
[report-72f988bf-86f1-41af-91ab-2d7cd011db47_20180330-135937.txt](https://github.com/Microsoft/azure-tools-for-java/files/1862835/report-72f988bf-86f1-41af-91ab-2d7cd011db47_20180330-135937.txt)

**Comment by ZhengJun003** [comment]
Tester team does not have these subs, can't reproduce this issue

1. Java Lib Tests with TTL = 7 Days
2. Java Dev Experience Tests With TTL = 7Days

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738761

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
