### ISSUE TITLE
Failed to create Docker Host

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#157]
In Azure toolkit of IntelliJ, click the next button will not jump to the next window, an error occurred.
![image](https://cloud.githubusercontent.com/assets/22470312/23601119/d213fb22-0284-11e7-8d6f-1698dc408437.png)

	
[Errorlog.txt](https://github.com/Microsoft/azure-tools-for-java/files/820442/Errorlog.txt)

**Comment by songkaiape** [comment]
Not repro. Verified this issue in azure-toolkit-for-intellij.14.zip
