### ISSUE TITLE
[IntelliJ] [18.1] Job main class display in red when create new or edit from toolbar

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1575]
Steps:
1. Right click on "LogQuery" or "SparkCore_WasbIOTest", click "Create[ ]..." to launch the configure dialog
2. Click edit configure from toolbar which beside the remote debug icon
Result: the "Job main class" display in red

3. Launch Edit configuration from menu 
Result: the job main class display in white.

**Comment by wezhang** [comment]
The issue of sample files, not declare `package sample`

**Comment by jingyanjingyan** [comment]
fixed
