### ISSUE TITLE
[IntelliJ] Open ASE for storage not works for linux and mac

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1576]
Steps:
1. Right click on a cluster, click "Open Azure Storage Explorer for storage"

Result:
![image](https://user-images.githubusercontent.com/36756024/38285551-48b4e436-37f3-11e8-8fbe-d0211d21a547.png)

**Comment by wezhang** [comment]
Fixed on Mac os.

**Comment by v-jiche** [comment]
Verified. Fixed
artifacts/azure-toolkit-for-intellij-2018.1.PR.2083.09-19-2018.zip
