### ISSUE TITLE
[IntelliJ][Eclipse]Storage issues

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#1581]
1. Search does not affect to folder, only files under current path searched out, and all folders still display.
2. Should the files display with icon?
3. named folder with /aaa will create a folder without name

**Comment by t-rufang** [comment]
Storage overview under HDInsight nodes feature are deprecated.
![image](https://user-images.githubusercontent.com/32627233/85119914-11463700-b255-11ea-95a7-ec142f128beb.png)
