### ISSUE TITLE
App insights list can't be refreshed automatically when change selected subscription

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#1585]
Not a regression issue.
Also repro in AI 1.0.10 
![image](https://user-images.githubusercontent.com/22470312/38483729-8dd2046a-3c06-11e8-90d8-fc8ebf5b667c.png)

**Comment by ZhengJun003** [comment]
Can reproduce this issue in azure toolkits for Eclipse 3.23.0

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738787

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
