### ISSUE TITLE
[IntelliJ][AzureExplorer][Spark] Link cluster with uppercase will accept as different cluster

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#1586]
Link a cluster with the same name, will replace sign in cluster with [linked] label
Link a cluster with the same name but uppercase will display as a new cluster
![image](https://user-images.githubusercontent.com/36756024/38488035-bb79e9e2-3c14-11e8-98a4-4ed4832dfeba.png)

submit to the cluster with uppercase works fine

**Comment by jingyanjingyan** [comment]
IntelliJ 18.1
Azure Toolkit for IntelliJ version: 3.5.0-2.18.1
windows

**Comment by wezhang** [comment]
Confirmed with @voidfunction , the cluster DNS name is case senseless, but the internal storage is case sense. So, here, we should:

1. Duplication detect: case senseless
2. Cluster name match: case senseless
3. Cluster name in job submission: case sense

**Comment by wezhang** [comment]
@t-rufang , could you help to check it?

**Comment by v-jiche** [comment]
Bug repros in build:
develop 1135

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748180
