### ISSUE TITLE
[IntelliJ] Overload scenario with linked/sign-in cluster

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1587]
Windows+IntelliJ18.1+AzureToolkitforIntelliJ3.5.0-2.18.1

1. Remote debug with sign-in cluster
![image](https://user-images.githubusercontent.com/36756024/38489831-1be16990-3c1a-11e8-98c7-ea2006aed52e.png)

2. Remote submit with sign-in cluster, keep running for long time, even click "Stop submit" button.
![image](https://user-images.githubusercontent.com/36756024/38489886-344e7590-3c1a-11e8-9441-a3c6f7886793.png)

3. Remote debug with linked cluster
![image](https://user-images.githubusercontent.com/36756024/38489923-485b9068-3c1a-11e8-877b-2c73b59a25e7.png)

4. Remote submit with linked cluster.
![image](https://user-images.githubusercontent.com/36756024/38489973-672492f6-3c1a-11e8-8478-30b54271354f.png)

**Comment by jingyanjingyan** [comment]
i use 
![image](https://user-images.githubusercontent.com/36756024/38490670-46524c7e-3c1c-11e8-8fc8-f5a3359cdcb4.png)

**Comment by wezhang** [comment]
It's by design.
