### ISSUE TITLE
[Eclipse] Azure toolkit option is not available for installation

### ISSUE THREAD

**Issue by teemasak** [microsoft/azure-tools-for-java#1589]
I am on a windows 7 machine and have JDK 8 on it. I am using Eclipse IDE for Java EE developers(tried Oxygen and Neon). When I select Install New Software and click enter as per instructions https://docs.microsoft.com/en-us/java/azure/eclipse/azure-toolkit-for-eclipse-installation I do not see the option Azure toolkit in the list. I only see "Team Explorer Everywhere" but not the azure tool kit. Please let me know if there are any other prerequisites.

I also tried installing from Eclipse market place and I get error "The following solutions are not available Azure Toolkit for Eclipse 3.5.0"

**Comment by Eskibear** [comment]
>  I am using Eclipse IDE for Java EE developers(tried Oxygen and Neon). 

Oxygen should work.

Eclipse 3.5.0 is no longer supported. 

Supported versions are revealed in https://marketplace.eclipse.org/content/azure-toolkit-eclipse : 
> Eclipse Versions: 
Oxygen (4.7), Neon (4.6), Mars (4.5)
