### ISSUE TITLE
When clicking logining on Manage Subscriptions window, it always hanging

### ISSUE THREAD

**Issue by ruoxinCheng** [Microsoft/azure-tools-for-java#16]
![intellijonubuntu15](https://cloud.githubusercontent.com/assets/20041888/16448215/e345b880-3e22-11e6-875d-d845e9b16bc8.PNG)
Testing OS: Ubuntu 15, details see png.
After  clicking 'Sign In..' button, it always hanging Manage subscription window, and there is no error.

**Comment by voidfunction** [comment]
Close and put it to another repository.
