### ISSUE TITLE
Deploy to new dockerhost fails with "Auth Fail" message

### ISSUE THREAD

**Issue by selvasingh** [Microsoft/azure-tools-for-java#160]
Use build 22 for IntelliJ
Sign in
Create a simple Web app
Publish to a Docker container
Accept all the defaults
Publish ... after several minutes, you see "Auth Fail"

**Comment by milismsft** [comment]
fixed

**Comment by bsaby** [comment]
Test passed in artifacts/azure-toolkit-for-intellij.20.zip
