### ISSUE TITLE
[Intellij][Eclipse][HDInsight]link cluster spark22 failed

### ISSUE THREAD

**Issue by liyanp1987** [Microsoft/azure-tools-for-java#1606]
link cluster spark22 failed
![image](https://user-images.githubusercontent.com/37991481/39180946-0b60e4de-476d-11e8-8556-8aba7e197af6.png)

**Comment by wezhang** [comment]
Spark2.2 support issue, part of #1583

**Comment by t-rufang** [comment]
Fixed in [PR1610](https://github.com/Microsoft/azure-tools-for-java/pull/1610)

**Comment by jingyanjingyan** [comment]
Fixed.
