### ISSUE TITLE
"To Be Created" instead of "NEW" state for VM in teh deploy to docker container workflow

### ISSUE THREAD

**Issue by selvasingh** [Microsoft/azure-tools-for-java#161]
In the wizard "NEW" is misleading ... it is greyed out. So, I was waiting for some time to see it lighted up. Should be marked as to be created and will help me to click next or continue.

What is the right moniker to indicate status? TBD

**Comment by milismsft** [comment]
Fixed

**Comment by bsaby** [comment]
Test passed in artifacts/azure-toolkit-for-intellij.36.zip.
