### ISSUE TITLE
[IntelliJ] cannot submit job successfully sometimes(always prompt file exist)

### ISSUE THREAD

**Issue by tankungx** [microsoft/azure-tools-for-java#1613]
1.remote submit class (Sparkcore_WasbIOTest), change the path to the unique one.
2.Fail to submit. always prompt file exist.
[file existing.txt](https://github.com/Microsoft/azure-tools-for-java/files/1945596/file.existing.txt)

**Comment by wezhang** [comment]
I can run the job well. The exception may relate the log fetch issues.

**Comment by t-rufang** [comment]
Close it since it's now repro now.
