### ISSUE TITLE
Summary of Eclipse accessiblity issues

### ISSUE THREAD

**Issue by Eskibear** [Microsoft/azure-tools-for-java#1619]
### ExpandBar widget
- [x] Tracked in https://bugs.eclipse.org/bugs/show_bug.cgi?id=533977

Related issues: 
~#1379  #1530 #1404~

### Table control type
- [x] Tracked in https://bugs.eclipse.org/bugs/show_bug.cgi?id=533980

Related issues: 
~#1405~

### High Contrast Mode
- [x] Tracked in https://bugs.eclipse.org/bugs/show_bug.cgi?id=533975

Related issues:
* Project Explorer: ~#1451~
* Menu items: ~https://github.com/Microsoft/azure-tools-for-java/issues/1433~
* Toolbar: ~#1431~
* Plugin installation dialog: ~https://github.com/Microsoft/azure-tools-for-java/issues/1427~ ~https://github.com/Microsoft/azure-tools-for-java/issues/1426 https://github.com/Microsoft/azure-tools-for-java/issues/1425~
* ExpandBar widget: ~#1420~

### TitleAreaDialog message
- [x] Tracked in https://bugs.eclipse.org/bugs/show_bug.cgi?id=533976

Related issues: 
~#1410 #1407 #1401 #1397 #1395 #1394 #1392 #1378 #1380 #1384 #1389 #1399~

### Tab index for Browser widget
- [x] Tracked in https://bugs.eclipse.org/bugs/show_bug.cgi?id=533978

Related issues: 
~https://github.com/Microsoft/azure-tools-for-java/issues/1373 https://github.com/Microsoft/azure-tools-for-java/issues/1370~

### Plugin Installation dialog
- [x] Tracked in https://bugs.eclipse.org/bugs/show_bug.cgi?id=533979 

Related issues: 
~https://github.com/Microsoft/azure-tools-for-java/issues/1375 https://github.com/Microsoft/azure-tools-for-java/issues/1374 https://github.com/Microsoft/azure-tools-for-java/issues/1369~

### issues out of the toolkit's scope
- [x] Tracked in https://bugs.eclipse.org/bugs/show_bug.cgi?id=534670
Related issues:  ~#1347 #1348 #1349 #1350 #1351 #1352~

**Comment by Eskibear** [comment]
Closing it as all Eclipse external issues are properly handled.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1749989
