### ISSUE TITLE
Refresh available in "Not Signed In" state.

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#162]
Right click Azure and choose **Select Subscriptions**, after refresh subscriptions in Select Subscriptions dialog, click **Cancel**. Although the Azure status is not signed in, it can be refreshed successfully after right-clicking Azure Select **Refresh**.
Is this state called No Signed In reasonable? (Actually Azure is already logged in)
![image](https://cloud.githubusercontent.com/assets/22470312/23737518/91ac95fc-04ce-11e7-8bc3-2f743128cf04.png)

**Comment by lenala** [comment]
This is fixed, please verify.

**Comment by bsaby** [comment]
Test passed in artifacts/azure-toolkit-for-intellij.29.zip.

**Comment by bsaby** [comment]
Click cancel after refresh subscriptions, although the status shows the previous subscription, when I refresh in the Azure, I found it loading content of all subscriptions.

**Comment by bsaby** [comment]
Test passed in artifacts/azure-toolkit-for-intellij.36.zip.
Click cancel after refresh subscriptions, the Azure explorer state will display all subscriptions.
