### ISSUE TITLE
Icons are all red squares?

### ISSUE THREAD

**Issue by maartenba** [Microsoft/azure-tools-for-java#1626]
In both the Eclipse and IntelliJ plugin, all icons are red squares (e.g. https://github.com/Microsoft/azure-tools-for-java/tree/develop/PluginsAndFeatures/azure-toolkit-for-eclipse/com.microsoft.azuretools.azureexplorer/icons)

Is there a reason why the icons are not included in the repo?

**Comment by Eskibear** [comment]
making resources (like some icons) public involves legal issues, so they are placed in another private repo named `azure-tools-for-java-resources`

**Comment by maartenba** [comment]
Ok so there is no way to create a custom build that looks nice? Can an open-source icon set be used instead so that the plugin can be built + used from source?

**Comment by Eskibear** [comment]
It's under [MIT license](https://github.com/Microsoft/azure-tools-for-java/blob/develop/license.txt), You can build your own version with icons you like. Simply replace those red squares images and build.
