### ISSUE TITLE
Exception when creating webapp with service plan containing no other webapps

### ISSUE THREAD

**Issue by lenala** [Microsoft/azure-tools-for-java#163]
1. Create new webapp with new service plan
2. delete webapp in explorer.
3. try to create a new webapp with same service plan as in step 1. Following error is shown:
![image](https://cloud.githubusercontent.com/assets/6208231/23768695/b35cb338-04c1-11e7-8a05-8e1631f2d493.png)

Please note: same app service plan is not responsible on the portal and cannot be deleted unless together with resource group.

**Comment by martinsawicki** [comment]
does this repro if done entirely from the portal (from step 1)?

**Comment by martinsawicki** [comment]
@vladimir-shcherbakov can you pls figure out what's going on here?

**Comment by vladimir-shcherbakov** [comment]
if you delete the last app service from an app service plan it becomes zombie-like - it exists but unresponsive and will disappear after a while. On the portal if you select such a asp - it won't be able to show any property.
