### ISSUE TITLE
[IntelliJ] Cannot tab out from storage key area in link cluster dialog

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1631]
Repro Steps:
1. Open link a cluster dialog
2. Tab to "Storage Key" area

Result:
Cannot tab out, then no way to tab to OK button
![image](https://user-images.githubusercontent.com/36756024/39741725-8c4be402-52cd-11e8-8dd5-0848bd705958.png)

**Comment by wezhang** [comment]
The UX is changed.
