### ISSUE TITLE
[IntelliJ] Clusters are not Sort Alphabetically in run/debug configurations dialog

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1640]
Clusters are not Sort Alphabetically in run/debug configurations dialog
![image](https://user-images.githubusercontent.com/36756024/39850872-4ec3fd3e-5446-11e8-838d-0df1ffbb0c3b.png)

**Comment by v-jiche** [comment]
Verified. Fixed
artifacts/azure-toolkit-for-intellij-2018.1.PR.2083.09-19-2018.zip
