### ISSUE TITLE
[IntelliJ] Unsaved debug configure file will replace existing spark configure file

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1641]
Repro Steps:
1. Click "Edit Configurations" to open "Run/Debug Configurations" dialog
2. Create an "Azure Spark Job\HDInsight Spark" configuration file named with "Spark", Apply
3. Create an "Azure Spark Job\Spark Failure Task Debug" named with default name "spark", Apply
4. Warning that "spark" already exists. Click OK to dismiss, click "Close" to close the "Run/Debug Configuration" dialog
5. Click "Edit Configurations" to open "Run/Debug Configurations" dialog

Result:
"Spark" configuration file has debug configure options, the HDInsight spark configuration file is gone.
![image](https://user-images.githubusercontent.com/36756024/39856277-cb8f051e-5461-11e8-982a-82fb4214f9c2.png)

**Comment by wezhang** [comment]
Should be IntelliJ issue
