### ISSUE TITLE
[IntelliJ] No way to customize job name

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1647]
The job name in yarn ui use main class name, maybe could set a way to allow user name a job.
![image](https://user-images.githubusercontent.com/36756024/39917111-1f78042c-553f-11e8-9d6c-87d0fd77731f.png)

**Comment by t-rufang** [comment]
Fixed in #2649

**Comment by jingyanjingyan** [comment]
@t-rufang  link to wrong issue?

**Comment by t-rufang** [comment]
#2649 fixed this issue. You can find the [commit history here](https://github.com/Microsoft/azure-tools-for-java/pull/2649/commits)

**Comment by jingyanjingyan** [comment]
Fix in develop 961, config name will set to application name now.
