### ISSUE TITLE
[IntelliJ] Warning please select cluster when there is default cluster

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1648]
Build
https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_develop_daily/396/Azure/ 

Repro Steps
1. Sign in IntelliJ
2. Create a new maven project, there is no configuration file now
3. Right click on one script, click "local run", wait to finish
4. Click remote submit button, warning please select one cluster
5. Open the "Run/debug configuration" dialog, click "Remote" tab to check the default cluster displays, and do not change anything, click "x" at the top-right corner to dismiss dialog
6. Click "Remote submit" button agian

Result:
Warning that please choose a cluster
![image](https://user-images.githubusercontent.com/36756024/39974907-195a7b44-575e-11e8-9c3f-d50a52f3be8d.png)

**Comment by wezhang** [comment]
Should be wrong display in cluster list for nothing selected.

**Comment by v-jiche** [comment]
Verified. Fixed
artifacts/azure-toolkit-for-intellij-2018.1.PR.2083.09-19-2018.zip
