### ISSUE TITLE
[IntelliJ] UI issue in the Redis Properties Panel

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#1651]
Stable repro
![image](https://user-images.githubusercontent.com/22470312/40048687-6607f112-5865-11e8-829a-fd2a7b55cbee.png)

![image](https://user-images.githubusercontent.com/22470312/40049241-c55ad80e-5866-11e8-88ac-17c2655f20d5.png)

**Comment by bsaby** [comment]
Sometimes, some content cannot be fully displayed unless you click on the properties panel
![image](https://user-images.githubusercontent.com/22470312/47705491-abf99880-dc61-11e8-91a4-586d9f43f3f9.png)

**Comment by andxu** [comment]
Low priority of ui issue.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738753

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
