### ISSUE TITLE
Web App(Linux) properties page no responce

### ISSUE THREAD

**Issue by sallyur** [Microsoft/azure-tools-for-java#1652]
This issue can stable repro.
This is not a regression issue ,it is also repro in market place version.

Repro steps:

1. Select one linux web app in azure explorer
2. Show peoperties
3. Click new in properties page
4. Keep default value and save

Results：
The Web App(Linux) properties page no responce.
![image](https://user-images.githubusercontent.com/28860891/40049429-57418164-5867-11e8-9bdb-13c4639982ee.png)

**Comment by Eskibear** [comment]
cannot reproduce, suppose to be network issue.
