### ISSUE TITLE
The access token has been obtained from wrong audience

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#1654]
This issue cannot be reproduced steadily.

Sometimes, we will get `the access token has been obtained from wrong audience` error when getting some resources under interactive login mode.

Run on Web App
1. Interactive login  
2. Right-click a project and choose Run on Web App
3. New an App service

![image](https://user-images.githubusercontent.com/22470312/40050094-0e819c46-5869-11e8-81e7-5b78b8cec430.png)
![image](https://user-images.githubusercontent.com/22470312/40050097-127e35c0-5869-11e8-87a9-a28be76f8050.png)

Get Redis cache's property
![image](https://user-images.githubusercontent.com/22470312/40165477-aafd674a-59ee-11e8-92e5-15bd02a6af04.png)
![image](https://user-images.githubusercontent.com/22470312/40165480-ae694106-59ee-11e8-8775-40773cc086e0.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738758

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
