### ISSUE TITLE
Sometimes, no App services are displayed in the list

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#1655]
Not stable repro

1. Right-click a project and choose **Publish as Azure Web App**
2. After auto refresh

![image](https://user-images.githubusercontent.com/22470312/40050566-66b0120c-586a-11e8-9437-d1e5a8df6040.png)
Result: 
No App services are displayed unless you manually refresh the list
![image](https://user-images.githubusercontent.com/22470312/40050578-7197679c-586a-11e8-954f-c52a66810967.png)

**Comment by ZhengJun003** [comment]
Can't reproduce this issue in azure toolkits for eclipse 3.23.0
