### ISSUE TITLE
IntelliJ - container workflow using docker flow assumes a WAR package

### ISSUE THREAD

**Issue by selvasingh** [Microsoft/azure-tools-for-java#166]

**Comment by milismsft** [comment]
Fixed

**Comment by milismsft** [comment]
In the latest version if user selects a .JAR artifact then we assume root deployment by default. To see this in action you need to go on the Custom Dockerfile path (see Spring Boot deployment).

**Comment by bsaby** [comment]
Select a .WAR artifact to deploy, then the browser shows below:
![image](https://cloud.githubusercontent.com/assets/22470312/24093803/a9ecec28-0d90-11e7-9c10-01d9fc34069f.png) 
Select selects a .JAR artifact to deploy then the browser shows below:
![image](https://cloud.githubusercontent.com/assets/22470312/24093863/f521f274-0d90-11e7-957d-0ed2a900ba2a.png)
So,  is the JAR artifact page expected?

**Comment by milismsft** [comment]
When selecting a JAR file the publishing process expects a "root" deployment. The "predefined images" combo in the next wizard step need to be filtered so only relevant content can be shown; the Tomcat and JBoss are not appropriate choices when deploying a .JAR file but a SpringBoot or regular Java Runtime only are appropriate selections (they did not get implemented yet).

**Comment by martinsawicki** [comment]
for @milismsft to complete the support for this scenario

**Comment by milismsft** [comment]
fixed.

**Comment by bsaby** [comment]
Test passed.
