### ISSUE TITLE
[Intellij][Spark on ADL] the count of cores become to 0 if input number is too large

### ISSUE THREAD

**Issue by liyanp1987** [Microsoft/azure-tools-for-java#1668]
1. on Provision Spark Cluster window
2. Input 11 digit numbers

Actual result:
the number change to 0
I think it can give a hint if inputting number is exceed the limitation
![image](https://user-images.githubusercontent.com/37991481/40773386-55550304-64f5-11e8-8f81-cceff4271169.png)

**Comment by jingyanjingyan** [comment]
Fix
