### ISSUE TITLE
Container workflow - misleads deployment to the same port using container file

### ISSUE THREAD

**Issue by selvasingh** [Microsoft/azure-tools-for-java#167]
Create a container and deploy using the container file route, then redeploy using the same port no

**Comment by martinsawicki** [comment]
we could just show "Port conflict" in the act9ivity log, instead of Published in the Status column. 
And the text `<Docker container name> could not be deployed due to a conflict on port <##>'

**Comment by martinsawicki** [comment]
@milismsft to simplify the error handling here, we can simply see if there is any failure, and show this error in the activity log: "*Error deploying the container. Check for port or name conflicts, or other issues.*"

**Comment by martinsawicki** [comment]
@milismsft based on further discussion it sounds like we could catch this conflict earlier --- when exiting the public dialog itself, so might as well throw the above error as a error msg at that time.  [OK -only error msg]

**Comment by selvasingh** [comment]
The tool should provide a meaningful error and request the dev to check for conflicting port numbers. 

If you were to take this to the next step, then the tool would the dev if he would like to stop or delete the container running at the conflicting port

**Comment by milismsft** [comment]
Fixed; we now issue a dialog window if there was an error while creating the container.

**Comment by vladimir-shcherbakov** [comment]
repro on Eclipse: WindowsAzurePlugin4EJ.323.04-18-2017

**Comment by milismsft** [comment]
Could not repro this on my dev Eclipse env. To work around the issue I've added an extra message in the status to point that the publishing failed.
