### ISSUE TITLE
[IntelliJ] [Spark on ADL] List cluster does not correctly in configuration file

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1677]
Repro Steps
1. List cluster under "Azure Explorer\Azure\Azure Data Lake"
2. Create a serverless config file, click "Remotely Run in Cluster", list cluster

Result
Does not consistent
![image](https://user-images.githubusercontent.com/36756024/40833219-d8f4321e-65bf-11e8-8260-ce3c78288b80.png)

**Comment by wezhang** [comment]
`[ENDED]` cluster should not be listed.

**Comment by jingyanjingyan** [comment]
Verify as fixed
