### ISSUE TITLE
[Intellij][Spark on ADL]there is showing a error when Delete cluster 

### ISSUE THREAD

**Issue by liyanp1987** [Microsoft/azure-tools-for-java#1679]
1. Right click on created cluster and choose delete
2. Input the cluster name on delete window and then click ok button

Actual result:
There is showing a error "Delete failed: org.apache.http.client.HttpResponseException: Internal Server Error"

Screenshot:
![image](https://user-images.githubusercontent.com/37991481/40896692-17678624-67e9-11e8-9203-51a57798e515.png)

**Comment by jingyanjingyan** [comment]
Fix in market build
