### ISSUE TITLE
IntelliJ - Cannot select Deployment Slot as Web App container

### ISSUE THREAD

**Issue by syr** [microsoft/azure-tools-for-java#168]
Instead of deploying our artifacts directly to a Azure WebApp we deploy to its deployment slot (by pushing a war file to a Azure-local git that's assigned to the deployment slot).

For remote debugging purposes we want to use the _Azure Toolkit for IntelliJ_ (1.5.5).
However, under _Run/Debug Configuration -> Azure Web App_ there are only WebApps selectable 
Sadly, the deployment slots are missing.
Is there a trick to get it working or could you add this feature, please?

**Comment by martinsawicki** [comment]
Thank you for the request, this has been on our TO DO list for the future.
Would you be open to a phone conversation about your general usage patterns/needs/scenarios?  It'd be helpful to understand more deeply feedback from users like yourself, to help prioritize our future work.

**Comment by HelmesBootcamp** [comment]
How is this going? When would it be possible to add to deployment slots directly from intelij?

**Comment by Flanker32** [comment]
Deploy to slot has been supported within `Deploy to Azure` action, so close this issue.
