### ISSUE TITLE
Unselect all subscription when sign in

### ISSUE THREAD

**Issue by sallyur** [microsoft/azure-tools-for-java#1683]
This issue is not stable repro.
It is high frequency reproduce on the first time after the plugin installation.
It is not repro in market place version(3.7.0).

Sign in - interactive method/automated new method

Expected result: Select all subscriptions as default.
![image](https://user-images.githubusercontent.com/28860891/40970178-60e49d38-68ec-11e8-9c78-92271c6e39df.png)

Actual result: Unselect all subscriptions as default.

![image](https://user-images.githubusercontent.com/28860891/40970203-74bb2afc-68ec-11e8-8838-f57173e31617.png)

**Comment by ZhengJun003** [comment]
Test pass
- azure toolkits for eclipse 3.23.0
![image](https://user-images.githubusercontent.com/41051257/83709164-878d4b80-a650-11ea-830a-821def4fe86a.png)

- azure toolkits for IntelliJ 3.37.0
![image](https://user-images.githubusercontent.com/41051257/83710874-59116f80-a654-11ea-872a-4c89e9b36961.png)
