### ISSUE TITLE
[Intellij][Spark on ADL]pop up error window when refresh cluster list

### ISSUE THREAD

**Issue by liyanp1987** [Microsoft/azure-tools-for-java#1685]
**Using bits:** https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_PR/1588/Azure/ 
**Repro Step**
Right click on genericonkobo03 and choose refresh
**Actual result**
error window pop up
**Screenshot**
![image](https://user-images.githubusercontent.com/37991481/41084371-94697f7c-6a66-11e8-9ed9-d87123ff7164.png)
**Logs**
![image](https://user-images.githubusercontent.com/37991481/41084401-a7bc4f00-6a66-11e8-8857-e6d58bb11483.png)

**Comment by v-jiche** [comment]
Not repro.
Build: azure-toolkit-for-intellij-2018.3.develop.965.01-16-2019
