### ISSUE TITLE
[Mac] Error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by sallyur** [Microsoft/azure-tools-for-java#1688]
Mac: Sierra 10.12.6
Intellij: IU 182.2949.4 and IC 182.2949.4
Build: Daily 421

The following two repro steps can reproduce this issue.

Repro steps1:

1. Sign in
2. Select automated browse method
3. Click browse

Repro steps2:

1. Select one blob
2. Click upload file
3. Click browse

Results:

The lower right corner report “null" error, attached the log:
[log.txt](https://github.com/Microsoft/azure-tools-for-java/files/2083635/log.txt)

I think may be the abnormal UI leading to the above results:

![image](https://user-images.githubusercontent.com/28860891/41148769-572d7e70-6b3c-11e8-9410-2a688f3ad263.png)

**Comment by Eskibear** [comment]
`JFileChooser` goes wrong in MacOSX. Following scenarios suffer:
- Sign-in window
- Storage Blob "uploading"
- Storage Blob "save as"
- Common UI helper

### PS
`log.txt` is not consistent with the issue, it's for azure storage blob uploading. Please check before submitting in future.

**Comment by Eskibear** [comment]
@sallyur please verify the latest build.

**Comment by sallyur** [comment]
Verified using the latest build: develop daily 427, test passed.
