### ISSUE TITLE
IDE exception after in WebApps after deploying

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#169]
Assuming you have an IntelliJ web app module already, with a WAR artifact set up (can be very simple):
0. **Start Intelli** (this step appears to be critical, this only repros the first time you try this from what I can see)
1. go to **Azure** > **Publish as Azure Web App** on the context menu
2. in the Deploy dialog, add a new Web App container
   a) assume Tomcat 7
   b) select an *existing* service plan
   c) accept the other default settings as is
   d) **Create**
-> the progress bar shows up for a  few seconds, looking good so far
(-> BUG #1: note however that after it's finished, the newly created web app does NOT show up in the list of web apps. It should.)
3. Click refresh on the list (due to the above bug)
4. Select the newly created Web App container, check **Deploy to root**

RESULT:
- an IDE UI exception is reported
- but the web app publishing process continues and appears to complete successfully

![repro](https://cloud.githubusercontent.com/assets/881767/23905229/9358636a-0887-11e7-834d-4901ef2c16da.png)

**Comment by bsaby** [comment]
Test passed in artifacts/azure-toolkit-for-intellij.54.zip.
