### ISSUE TITLE
Environment Selector for Azure Government

### ISSUE THREAD

**Issue by jftl6y** [Microsoft/azure-tools-for-java#1691]
Is it possible to switch environments (similar to the Visual Studio environment selector extension) to be able to target Azure Government?

**Comment by Eskibear** [comment]
Create a file  `AadProvider.json` in `~/AzureToolsForIntelliJ` or `%USERPROFILE%\AzureToolsForIntelliJ` for Windows users.

AadProvider.json:
```
{
  "EnvironmentName":"US_GOVERNMENT"
}
```
It should work. 

Related issue: #1232

**Comment by Eskibear** [comment]
Closing. 
If there are still problems switching environments, feel free to reopen this issue and attach more details.
