### ISSUE TITLE
[IntelliJ] launch configuration take 6 seconds

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1696]
Repro Steps
1. Create a project, create a configuration file
2. Click "Edit configuration" to launch the run/debug configuration dialog

Result:
It will take 5 seconds, longer than before, a little long i think.

**Comment by wezhang** [comment]
Let's test it on production environments again.

**Comment by wezhang** [comment]
dup #1810
