### ISSUE TITLE
Notes for upgrading from v2.x to v3.x of Azure Toolkit for Eclipse/IntelliJ

### ISSUE THREAD

**Issue by martinsawicki** [microsoft/azure-tools-for-java#170]
## Deprecation of support for Cloud Services in v3.x
In the next upcoming version of Azure Toolkit for Eclipse/IntelliJ (v3.0), the old style "Classic" Cloud Service deployments and other "Classic" services will no longer be supported. That includes:
- no more Azure Deployment Project and any of the features that come with it
- no need for the Azure SDK for .NET (no longer a pre-req for Windows)
- no need for the Azure emulator (for Windows)
- no more Ant task extension for publishing to Cloud Services (cspack.jar)
- no more support for "Classic" storage accounts and "Classic" virtual machines in the Azure Explorer
- publish-settings file no longer supported as an authentication mechanism
Also, dropping support for the deprecated Azure Access Control Services filter.

### Archive of the last version supporting Cloud Services:
The last version of the Eclipse plugin supporting the "classic" Cloud Services and other "classic" features of Azure is available at an archived update site at: http://dl.microsoft.com/eclipse/azure/v2.9.5. However, users are encouraged to migrate their application to use [Azure Web Apps (App Services)](https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-get-started-java) and/or Azure support for Docker Containers, instead of Azure Cloud Services.

## Features still supported and enhanced in v3.x
The new v3.0 plugins' suport will be focused on the newer "Azure Resource Manager"-based functionality in Azure that users are encouraged to migrate to, if not using them already.  Support for the following previously released features will continue to expand:
- Azure Web Apps (App Services)
- Virtual Machines (but not "Classic")
- HDInsight
- Application Insights
- Storage (Blobs, but not "Classic")
- Active Directory-based authentication

## New features in v3.0.0 release
New functionality includes:
- Docker Host creation in VMs
- Web app publishing as Docker containers
- KeyVault integration
- Active Directory service principal-based authentication

## Upgrading to v3.x from v2.x in Eclipse
⚠️ Note: The v2.x of the Azure Toolkit for Eclipse **cannot** be automatically updated to v3.x because the changes between the two major versions are too significant. To install v3.x, you should first **manually uninstall** all of the v2.x components, and then install v3.x. The specific list of Toolkit components to look for in Eclipse and uninstall is:
- Application Insights Plugin for Java
- Azure Access Control Services Filter
- Azure Common Plugin
- Azure Explorer for Eclipse
- Azure HDInsight plugin for Java
- Azure Plugin for Eclipse with Java
- Azure Web Apps Plugin for Java
- Microsoft JDBC Driver 6.0 for SQL Server
- Package for Apache QPid Client Libraries for JMS
- Package for Microsoft Azure Libraries for Java

Then install v3.x from the usual update site at http://dl.microsoft.com/eclipse or from [Eclipse Marketplace](https://marketplace.eclipse.org/content/azure-toolkit-eclipse).

## Learn more
Visit the [Azure Java Developer Center](http://azure.com/java) to learn the latest about working with Java applications on Microsoft Azure.

**Comment by Flanker32** [comment]
Moved to [wiki](https://github.com/microsoft/azure-tools-for-java/wiki/Notes-for-upgrading-from-v2.x-to-v3.x-of-Azure-Toolkit-for-Eclipse-IntelliJ)
