### ISSUE TITLE
[IntelliJ] [Spark on ADL] Tooltip should not include hdinsight in configuration dialog

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1700]
Repro Steps:
1. Launch the "Run/Debug Configurations" dialog from toolbar
2. Click on "Remotely Run in cluster"
3. Mouse over on the dropdownlist of "Spark clusters"

Result;
"The HDInsight spark cluster...."
![image](https://user-images.githubusercontent.com/36756024/41329700-0d4819f0-6e84-11e8-8736-982f28485204.png)

Expect:
They are not HDinsight cluster.

**Comment by t-rufang** [comment]
Fixed in the latest bits
![image](https://user-images.githubusercontent.com/32627233/50967155-4273f100-1512-11e9-96c0-643e0bcea023.png)

**Comment by jingyanjingyan** [comment]
Fix in market build.
