### ISSUE TITLE
[IntelliJ]"Back to Master" fail to work in all pages.

### ISSUE THREAD

**Issue by tankungx** [microsoft/azure-tools-for-java#1701]
Spark ADL
Steps:
1. Click context menu "Open Spark Master UI".

Actual result:
1."Back to Master" not work, After click the button, no response.
2. In application page,  I think should add "Back to Master".

**Comment by t-rufang** [comment]
This is a Spark Master UI issue, it's out of the toolkit. We shouldn't own it.
