### ISSUE TITLE
[IntelliJ][Spark on ADL] link in cluster statue pops two instances

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1709]
Build: develop 640

Repro Steps:
1. Sign in IntelliJ, right click on one cluster, check the cluster status
2. Set the default browser to chrome or firefox
3. Click the link in cluster status dialog

Result:
Pops two instances.
![image](https://user-images.githubusercontent.com/36756024/41401335-6cc52580-6f74-11e8-9912-7efa853d81c3.png)

**Comment by wezhang** [comment]
Could you close all tabs and try it again?

**Comment by jingyanjingyan** [comment]
Close all tab and click the link, will pops two tabs in chrome and firefox.

**Comment by jingyanjingyan** [comment]
Fix with build dev-648
