### ISSUE TITLE
[Intellij][Spark on ADL] The state show incorrectly on view cluster status window

### ISSUE THREAD

**Issue by liyanp1987** [Microsoft/azure-tools-for-java#1710]
**Repro bit**

azure-toolkit-for-intellij-2018.1.develop.640.06-14-2018.zip

**Repro step**
1. Right click on any one cluster
2. Choose 'view cluster status'
3. Check the cluster state window

**Actual result**
the state show 'Scheduled', it is inconsistent with the cluster list

**Screenshot**
![image](https://user-images.githubusercontent.com/37991481/41403447-7aaa2a00-6ff7-11e8-9ef4-e1619b03af6f.png)

**Comment by jingyanjingyan** [comment]
Assigned and add tags

**Comment by t-rufang** [comment]
The state of the cluster node is supposed to be master state. The cluster node will show cluster state(Scheduled) if we cannot get master state, which usually happens when we just provision a new cluster.

**Comment by jingyanjingyan** [comment]
Fix with build dev-646
