### ISSUE TITLE
[Blocking issue] Can't load resources after login in

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1711]
Build: daily build427
Works on the latest regression test at 6/5 using build daily 418, so it is a regression bug
Both global and Azure China

Repro steps:
1. Install build in Eclipse
2. Choose one login method to sign in Azure

Result:
The Azure node can't be expanded
![image](https://user-images.githubusercontent.com/22470312/41409764-e6153368-7009-11e8-9bde-4368541e363d.png)

Click Refresh all, an error occurs
![image](https://user-images.githubusercontent.com/22470312/41409789-fcc3a2a2-7009-11e8-9787-da35554dbe79.png)

**Comment by Eskibear** [comment]
@bsaby Is there any detailed log?
@wezhang It looks similar with the IntelliJ issue, the ServerlessSpark one. Can you help to have a look?

**Comment by bsaby** [comment]
Error details
![image](https://user-images.githubusercontent.com/22470312/41444937-c0851676-7078-11e8-9cf7-1f906e0366d0.png)

**Comment by Eskibear** [comment]
NPE here in this statement:
```
sparkServerlessClusterRootModule.load(true);
```

https://github.com/Microsoft/azure-tools-for-java/blob/develop/Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/AzureModule.java#L172

**Comment by Eskibear** [comment]
@wezhang will help to fix the NPE issue.

**Comment by Eskibear** [comment]
please verify the latest build

**Comment by bsaby** [comment]
Test passed.
Build: develop641
