### ISSUE TITLE
[IntelliJ][Spark on ADL] Cannot open history UI when the event folder other than the default

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1712]
Repro Steps:
1. Provision a cluster with not exist folder or an exist folder but not the default value, submit
2. Right click on cluster, select history UI

Result:
![image](https://user-images.githubusercontent.com/36756024/41413006-a60e74b4-6f96-11e8-98ca-e13b1e7db140.png)

Expect:
Should show the home page of history server.

**Comment by wezhang** [comment]
@t-rufang has fixed it with creating the event folder before provisioning.

**Comment by jingyanjingyan** [comment]
Verify with private build 2230, the field is disabled now. Will check it when it enable someday.
