### ISSUE TITLE
[IntelliJ][Spark on ADL] Submit job does not show in history UI

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1713]
Repro Steps
1. Submit a job to the provisioned cluster, the history UI pops automatically
2. Check the jobs in history UI

Result:
The job does not show in job list, include the incomplete job list

**Comment by wezhang** [comment]
Is it still reproduced?

**Comment by jingyanjingyan** [comment]
Fix with market build, submit spark on cosmos job then the Master UI will pops up, and the running driver will display.
