### ISSUE TITLE
[Intellij][Spark on ADL] the cluster state show unknown on view cluster status window

### ISSUE THREAD

**Issue by liyanp1987** [Microsoft/azure-tools-for-java#1716]
**Repro bit**

azure-toolkit-for-intellij-2018.2.develop.640.06-14-2018

**Repro Steps**

1. Create a new cluster
2. Check the cluster state show queued
3. Right click on this cluster and choose view cluster status

**Actual result**

Found the cluster state show Unknown

**Screenshot**

![image](https://user-images.githubusercontent.com/37991481/41449699-3d592748-7095-11e8-8023-e7cd118777c2.png)

**Comment by t-rufang** [comment]
This is by design. State of master and worker containers might be `unknown` when cluster is not ready. But we promise that cluster state in cluster node and monitor dialog should not be `unknown`
