### ISSUE TITLE
[Intellij][Spark on ADL]The intellij will stuck when delete cluster

### ISSUE THREAD

**Issue by liyanp1987** [Microsoft/azure-tools-for-java#1717]
**Repro Bit**

azure-toolkit-for-intellij-2018.1.develop.640.06-14-2018

**Repro Steps**

1. Create two cluster 
2. Right click on the second one and choose delete
3. On the delete window, input the cluster name 
4. Click ok button

**Actual result**

The Ok button is greyed and it show 'validate the cluster name' all the time. no any log

the Intellij is stick

**Screenshot**
![image](https://user-images.githubusercontent.com/37991481/41456923-97aa7214-70b4-11e8-8d51-c618d285208f.png)

**Comment by t-rufang** [comment]
Not repro

**Comment by v-jiche** [comment]
Not repro.
Build: azure-toolkit-for-intellij-2018.3.develop.965.01-16-2019
