### ISSUE TITLE
[Eclipse]when restart the eclipse, it pop up a error window

### ISSUE THREAD

**Issue by liyanp1987** [Microsoft/azure-tools-for-java#1719]
**Repro bit**

WindowsAzurePlugin4EJ.develop.641.06-15-2018

**Repro steps**
1. Install the 641 bit and sign in
2. Then restart Eclipse

**Actual result**

it pop up error window

**Screenshot**
![image](https://user-images.githubusercontent.com/37991481/41458424-24bf6e9e-70b9-11e8-9b09-f7c2a3ce5484.png)

**Comment by tankungx** [comment]
Cannot repro on my machine.

**Comment by wezhang** [comment]
Reopen it when repro
