### ISSUE TITLE
Web Apps doesn't refresh in Azure explorer.

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#172]
IntelliJ - Used 82.zip.
After publish successfully, Web Apps doesn't refresh in Azure explorer.

**Comment by martinsawicki** [comment]
@lenala it'd be great to refresh the node with the new webapp (and other node types) afger they're created, if it is easy to achieve quickly.

**Comment by martinsawicki** [comment]
@milismsft sounds like you'll be fixing the same issue for Docker

**Comment by davidliangze** [comment]
Test passed.

OS: Windows 10 Enterprise x64 ENU
IDE: IntelliJ 2017.1.1
Plugin Version: azure-toolkit-for-intellij.2017.353.04-21-2017
