### ISSUE TITLE
Only specifies the Secure Shell (SSH) settings for Creating VM failed.

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#173]
IntelliJ - In Machines Setting tab, if I only choose upload compatible SSH key, creating virtual machine will failed.
Select one of the SSH or password, the virtual machine should be created successfully.

![image](https://cloud.githubusercontent.com/assets/22470312/24037473/e64c343a-0b38-11e7-9d82-d265a489112b.png)

**Comment by lenala** [comment]
This is fixed, please verify.

**Comment by bsaby** [comment]
Test passed in artifacts/WindowsAzurePlugin4EJ.95.zip.
