### ISSUE TITLE
[IntelliJ] Need more information in cluster status and double click node to display status

### ISSUE THREAD

**Issue by wezhang** [microsoft/azure-tools-for-java#1739]
Session ID is helper for debugging backend service.

**Comment by t-rufang** [comment]
Session ID is already supported. We have already show cluster status in the node, therefore no need tfor double click to display status 
![image](https://user-images.githubusercontent.com/32627233/50967360-e65d9c80-1512-11e9-86ca-c40c38e0057f.png)
![image](https://user-images.githubusercontent.com/32627233/50967409-11e08700-1513-11e9-8a27-cb88d5adc329.png)

**Comment by v-lanjli** [comment]
Verified and fixed this issue.
Closed this issue.
