### ISSUE TITLE
After publish as Docker Container successfully, the Key Vault is still being created.

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#174]
Intellij - After publish successfully, the Key Vault is still being created.
![image](https://cloud.githubusercontent.com/assets/22470312/24039402/ffbbff8e-0b3f-11e7-8944-85c1762a6d2b.png)

**Comment by milismsft** [comment]
This is "by design"; the key vault creation is pushed to the background task because it is not critical to publishing the artifact. The user's input credentials are stored in memory cache and key vault credentials are only used when the user restarts his IntelliJ/Eclipse session.
