### ISSUE TITLE
[IntelliJ] Align issue in provision dialog

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#1749]
Build
azure-toolkit-for-intellij-2018.1.develop.659.06-29-2018

Repro Steps:
1. Start provision cluster dialog

Result:
Fields do not align right
![image](https://user-images.githubusercontent.com/36756024/42087052-e565664a-7b49-11e8-9157-3bd448faef7a.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748179
