### ISSUE TITLE
Can not sign in

### ISSUE THREAD

**Issue by rbauer75** [Microsoft/azure-tools-for-java#1754]
I am trying to sign in to MS Azure Germany. The account i am using has MFA activated.
Trying interactive sign in I get "invalid input".
Trying to create automated sign in I get "invalid input".
Trying to sign in with an auth file create with Azure CLI (az ad sp create-for-rbac --sdk-auth > my.azureauth) I get an unhandeld event loop while the toolkit is trying to get a subscription. I tried the new and old aut file format.
This is what it looks like:

_{
  "clientId": "########-####-####-####-###########",
  "clientSecret": "########-####-####-####-###########"",
  "subscriptionId": "########-####-####-####-###########"",
  "tenantId": "########-####-####-####-###########"",
  "activeDirectoryEndpointUrl": "https://login.microsoftonline.de",
  "resourceManagerEndpointUrl": "https://management.microsoftazure.de",
  "activeDirectoryGraphResourceId": "https://graph.cloudapi.de/",
  "sqlManagementEndpointUrl": "https://management.core.cloudapi.de:8443/",
  "galleryEndpointUrl": "https://gallery.cloudapi.de/",
  "managementEndpointUrl": "https://management.core.cloudapi.de/
}_

What is wrong? Are there maybe permissions to the app registration missing. What API and permissions are necessary?

Thank you in advance,
Rene

**Comment by Eskibear** [comment]
> Trying interactive sign in I get "invalid input".

Have you set environment as `GERMAN`? Ref: https://github.com/Microsoft/azure-tools-for-java/issues/1691

> Trying to create automated sign in I get "invalid input".

Same as above.

> Trying to sign in with an auth file create with Azure CLI (az ad sp create-for-rbac --sdk-auth > my.azureauth) 

The `xxx.azureauth` file I'm using looks like:
```
baseURL=https\://management.azure.com/
client=########-####-####-####-###########
managementURI=https\://management.core.windows.net/
tenant=########-####-####-####-###########
key=########-####-####-####-###########
authURL=https\://login.windows.net/
subscription=########-####-####-####-###########
```
Hope it helps.

**Comment by rbauer75** [comment]
Thank you. That brought me on the right track.

Additionaly I had to import the certificates for the German Azure Cloud as described in Issue #356 using keytool (i used the browser for download of the certs). After restarting Eclipse ot worked.

Ticket can be closed :).
