### ISSUE TITLE
ACS filter should be removed from v3.0

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#176]
it shows up in the list of features to install
![installsoftware](https://cloud.githubusercontent.com/assets/881767/24052564/2a651b8c-0af3-11e7-85c0-9dc51b3e984d.png)

**Comment by lenala** [comment]
This is done for our latest version, as well as removing old Cloud Services plugin.

**Comment by martinsawicki** [comment]
never mind - wrong build
