### ISSUE TITLE
[IntelliJ]The Finish button should be disabled in the first VM creation page

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#1760]
Click the 'Finish' button in the first creation page, the dialog will exit directly.
![image](https://user-images.githubusercontent.com/22470312/42442690-ecc41902-839d-11e8-945b-c4b3ab1d8edc.png)
Expect:
The Finish button should be disabled

**Comment by ZhengJun003** [comment]
Can reproduce this issue in azure toolkits for IntelliJ 3.38.0

![image](https://user-images.githubusercontent.com/41051257/84642820-9832a100-af2f-11ea-88aa-819baaebc29b.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738786

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
