### ISSUE TITLE
Eclipse Mars - Sign in window is truncated

### ISSUE THREAD

**Issue by selvasingh** [Microsoft/azure-tools-for-java#177]
![image](https://cloud.githubusercontent.com/assets/3642444/24053811/6fda107e-0af7-11e7-8544-6b378ed9a83c.png)

**Comment by vladimir-shcherbakov** [comment]
no repro.

Eclipse Java EE IDE for Web Developers.

Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600

![image](https://cloud.githubusercontent.com/assets/6579928/24313660/11b958ca-109b-11e7-864f-b1c39adbcf52.png)

**Comment by reyang** [comment]
@ZhijunZhao , would you take a look at this bug? Looks like with different DPI and font size, the dialog could be truncated in some situation.

**Comment by ZhijunZhao** [comment]
I tried it on Win 10 and OS X Yosemite and couldn't reproduce it either.

**Comment by bsaby** [comment]
Not repro.
Eclipse Java EE IDE for Web Developers.
Version: Mars.2 Release (4.5.2)
