### ISSUE TITLE
[IntelliJ][Spark on ADL] 502 error

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#1777]
Environment: PPE
Repro Steps:
1. Refresh Azure node, wait for the refreshing to finish
Result:
Warning for web app loading, etc. dismiss all warning dialog, then the 502 pops
If it is not repro, try once more please. Not 100% repro.

![image](https://user-images.githubusercontent.com/36756024/42686011-311eac4e-86c7-11e8-8d73-2560d2e720f5.png)

**Comment by wezhang** [comment]
The code path is Azure Docker related.

**Comment by jdneo** [comment]
@jingyanjingyan Could you please provide more details about this issue? Like repro steps, etc...

**Comment by jingyanjingyan** [comment]
No stable steps to repro this issue, just met several times when use intellij.

**Comment by t-rufang** [comment]
Close it since it's not repro
