### ISSUE TITLE
[Intellij][Spark on ADL] Update dialog pops several times when try to submit

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1779]
Build": 1738 PR

Repro Steps:
Provision a cluster, click Update from context menu, update data then try to submit

Result:
Update dialog pops twice

![image](https://user-images.githubusercontent.com/36756024/42686768-8339c9e4-86c9-11e8-9fd7-82e0f518f6bc.png)

**Comment by jingyanjingyan** [comment]
The key step is refresh the cluster several times then submit update dialog.

**Comment by t-rufang** [comment]
Fixed in #2013

**Comment by v-jiche** [comment]
Verified. Fixed.
Build: azure-toolkit-for-intellij-2018.1.PR.2087.09-20-2018
