### ISSUE TITLE
[IntelliJ][Spark on ADL] event folder does not show in update dialog

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#1785]
Build 1743 

Steps:
Open update dialog

Result:
Event folder does not show
![image](https://user-images.githubusercontent.com/36756024/42690681-1209b564-865a-11e8-8896-656f96eb3798.png)

**Comment by t-rufang** [comment]
Need backend support

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748178
