### ISSUE TITLE
[IntelliJ][Spark on ADL] warning message of update show in context menu

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#1786]
Build : 1743

Steps:
1. Update a cluster with invalid data, pops an error
2. Click Cancel to dismiss update dialog
3. Right click on cluster to pops the context menu

Result:
Warning message show
![image](https://user-images.githubusercontent.com/36756024/42690827-a62b0400-865a-11e8-818d-506144ce124b.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748177
