### ISSUE TITLE
[Intellij][Spark on ADL] AU info cannot show completely unless resize the window

### ISSUE THREAD

**Issue by liyanp1987** [Microsoft/azure-tools-for-java#1789]
**Repro Bits**
azure-toolkit-for-intellij-2018.1.PR.1743.07-13-2018

**Repro Steps**
1. Right click on Cosmosadmin-c09 and choose provision spark cluster
2. Check the window info

**Actual result**
The AU info cannot show completely unless resize the window

**Screenshot** 
![image](https://user-images.githubusercontent.com/37991481/42742728-d365ade8-88ef-11e8-9cc8-7c36fc00fe1b.png)

**Comment by t-rufang** [comment]
fixed in #1787

**Comment by liyanp1987** [comment]
this issue is fixed on bits 1757, so closed
