### ISSUE TITLE
Interactive login not stable in Eclipse Neon 2

### ISSUE THREAD

**Issue by reyang** [Microsoft/azure-tools-for-java#179]
1. use Eclipse plugin with [Tools] -> [Azure] -> [Sign In...]
2. use Microsoft account
3. select virtual smart card
4. after input the correct PIN, the dialog went back to the login status again (looks like I haven't logged in)
5. however when I try to login again using smart card, it didn't ask for the PIN and got me signed in automatically

looks like a bug in the UI flow.

**Comment by martinsawicki** [comment]
Vlad says this is another manifestation of the timeout issue in Eclipse, for which we now have a fix

**Comment by vladimir-shcherbakov** [comment]
#268 duplicate
