### ISSUE TITLE
[Intellij] Refresh Azure node pop up the error window

### ISSUE THREAD

**Issue by liyanp1987** [microsoft/azure-tools-for-java#1790]
**Repro Bits**
azure-toolkit-for-intellij-2018.1.PR.1743.07-13-2018

**Repro Platform**
Prod & PPE

**Repro Steps**
1. After Sign in and then refresh Azure node

**Actual result**
Error window pop up

**Screenshot**
![image](https://user-images.githubusercontent.com/37991481/42743065-11e4a58a-88f3-11e8-81e8-69dcf17dd708.png)

**Comment by t-rufang** [comment]
@SummerSun, could you help to take a look at this issue? It's reproduced in the latest market bits in PROD environment.

**Comment by jingyanjingyan** [comment]
Not repro with release build v3.23.0-2019.1
