### ISSUE TITLE
[IntelliJ]Update dialog still exist after click "Cancel" or "OK" button on Spark ADL on Mac

### ISSUE THREAD

**Issue by tankungx** [Microsoft/azure-tools-for-java#1794]
ppe azure-toolkit-for-intellij-2018.1.PR.1743.07-13-2018.zip
Steps:
1.Right click "Update" under one cluster.
2.Click "Cancel" or "OK" button whether having change or not.

Actual
Update dialog still show. Should close automatically.
<img width="578" alt="update dialog" src="https://user-images.githubusercontent.com/30617450/42746681-9d5cedbc-890b-11e8-9f7b-9386145fd522.png">

**Comment by t-rufang** [comment]
Duplicate with #1779
