### ISSUE TITLE
[Intellij][Spark on ADL] Click 'open spark master/history UI' does not work when cluster status is not stable

### ISSUE THREAD

**Issue by liyanp1987** [Microsoft/azure-tools-for-java#1796]
**Repro bits**
azure-toolkit-for-intellij-2018.1.PR.1743.07-13-2018

**Repro Steps**
1. Create a new cluster under genericonkobo03
2. Right click on this cluster when the cluster status is not stable
3. Click on "open spark master/history ui" item of the menu list

**Actual result**
They do not work

**Comment by t-rufang** [comment]
It's by design, we can't open spark master UI or spark history UI when cluster is not stable.
