### ISSUE TITLE
[Intellij][Spark on ADL] On PPE enviroment, "Update" menu position is not right.

### ISSUE THREAD

**Issue by tankungx** [Microsoft/azure-tools-for-java#1797]
Repro Bits
azure-toolkit-for-intellij-2018.1.PR.1743.07-13-2018

Repro Platform
PPE

Repro Steps
Provision Spark Cluster, then wait for the cluster become stable(don't refresh on node genericonkobo03, just refresh on the cluster node ), then check the context menu.

Actual result
Update menu is at the last item.
![update on the last](https://user-images.githubusercontent.com/30617450/42747668-f406f0f0-890f-11e8-92dc-b10221e78808.PNG)

Expect result
<img width="197" alt="normal" src="https://user-images.githubusercontent.com/30617450/42747705-112c9734-8910-11e8-9020-e457cca87b62.png">

**Comment by djlan** [comment]
I think this is fine.
