### ISSUE TITLE
version 1.4.1 on idea/linux is unable to authorize

### ISSUE THREAD

**Issue by s4s0l** [Microsoft/azure-tools-for-java#18]
First of all it this plugin suppose to work on linux?

If yes, then on idea:

IntelliJ IDEA 2016.2
Build #IU-162.1121.32, built on July 9, 2016
JRE: 1.8.0_76-release-b216 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Plugin version i 1.4.1

When i use "publish as azure web app.." a browser window opens. After i enter my password, the page saying "How can we verify your account" appears (Actually i see it in polish so my translation may be inacurate).  I see my account name next to blue icon, and some dots are spinning below.  Forever....

**Comment by vladimir-shcherbakov** [comment]
Hi @s4s0l ,

Could you please perform a few simple steps:

1. Open you browser  in **private browser mode**;
2. Copy the following URL into the browser address bar:

  ```
https://login.windows.net/common/oauth2/authorize?client-request-id=fd493340-de5d-4856-8eda-562aeb3e2dac&scope=user_impersonation&response_type=code&redirect_uri=https%3A%2F%2Fmsopentech.com%2F&return-client-request-id=true&resource=https%3A%2F%2Fmanagement.core.windows.net%2F&client_id=61d65f5a-6e3b-468b-af73-a033f5098c5c
  ```
 
  and hit Enter - you'll see the login page::

  ![image](https://cloud.githubusercontent.com/assets/6579928/17274747/f65f78da-56a4-11e6-9bab-6fce9a2be1fe.png)

3. Sign in with you Azure credentials.

**Can you see the same page like on your comment above?**

**Comment by hemanthraz** [comment]
I have the same problem. I tried to login using the URL in private browsing window.
But I still could not login and the dots keep spinning.

**Comment by hemanthraz** [comment]
Manually downgraded to plugin version 1.4 and I could login

**Comment by vladimir-shcherbakov** [comment]
Hi @hemanthraz, 

Can you please try this URL:
```
https://login.windows.net/common/oauth2/authorize?client-request-id=762a8786-cf7e-4728-b0fc-bcec778002d0&response_type=code&redirect_uri=https%3A%2F%2Fmsopentech.com%2F&return-client-request-id=true&resource=https%3A%2F%2Fmanagement.core.windows.net%2F&client_id=61d65f5a-6e3b-468b-af73-a033f5098c5c
```
on the second step?

The only difference between these two URLs is tenant ID (72f988bf-86f1-41af-91ab-2d7cd011db47 vs common)

Are you able to log in?

**Comment by hemanthraz** [comment]
@vladimir-shcherbakov 
I could login with the URL you provided.

For now, I have downgraded by plugin to 1.4, and could connect to my account from Idea

**Comment by vladimir-shcherbakov** [comment]
Good to know - thanks!

**Comment by vladimir-shcherbakov** [comment]
## So, if you have the issue - please try to downgrade the plugin to version 1.4

To do that, please follow the steps:

1. Uninstall the plugin version **1.4.1**

  ![image](https://cloud.githubusercontent.com/assets/6579928/17449051/b652f3ae-5b0c-11e6-85fe-db3c2d3b1b86.png)

2. Download the plugin version **1.4** from the [page](https://plugins.jetbrains.com/plugin/8053?pr=idea)

   ![image](https://cloud.githubusercontent.com/assets/6579928/17449111/3c82b950-5b0d-11e6-86ba-fac9214042e6.png)

3. Install the plugin version **1.4** form disk

  ![image](https://cloud.githubusercontent.com/assets/6579928/17449200/e1c47980-5b0d-11e6-93d9-7c124de686da.png)

**Comment by martinsawicki** [comment]
addressed in later releases, so closing
