### ISSUE TITLE
Eclipse Mars - Window Sizing is Off

### ISSUE THREAD

**Issue by selvasingh** [Microsoft/azure-tools-for-java#180]
![image](https://cloud.githubusercontent.com/assets/3642444/24054184/918622c0-0af8-11e7-866a-0229bbbd7616.png)

**Comment by vladimir-shcherbakov** [comment]
no repro.

Eclipse Java EE IDE for Web Developers.

Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600

![image](https://cloud.githubusercontent.com/assets/6579928/24313509/4c630dc8-109a-11e7-8941-d8537ade9c01.png)

**Comment by reyang** [comment]
@ZhijunZhao , this is a similar issue related to DPI and font size. Try if you can repro it using different combination of resolution/dpi.

**Comment by ZhijunZhao** [comment]
I tried it on Win 10 and OS X Yosemite and couldn't reproduce it either.

**Comment by martinsawicki** [comment]
not reproducible (easily enough) - likely nothing we can do about this, so just please close if can't find a consistent repro on a typical machine

**Comment by bsaby** [comment]
Not repro.
Win 10.
Eclipse Java EE IDE for Web Developers.
Version: Mars.2 Release (4.5.2)
