### ISSUE TITLE
[IntelliJ]jobs list is blank on spark 2.3

### ISSUE THREAD

**Issue by tankungx** [Microsoft/azure-tools-for-java#1802]
azure-toolkit-for-intellij-2018.1.PR.1743.07-13-2018.zip

steps:
1. submit some jobs on spark 2.3
2.Lauch "Azure Explorer", then click "Jobs" under the cluster.

Actual result:
jobs list blank on the right pane.
![1db6a0e7](https://user-images.githubusercontent.com/30617450/42795814-edb00b20-89b8-11e8-8af2-f657e2a534bc.PNG)

**Comment by wezhang** [comment]
Backend history server issue
