### ISSUE TITLE
[Intellij][Spark on ADL]it show 'no completed application found' on browser after remote run

### ISSUE THREAD

**Issue by liyanp1987** [Microsoft/azure-tools-for-java#1805]
**Repro bits**
azure-toolkit-for-intellij-2018.1.PR.1757.07-16-2018

**Repro steps**
1. Create a new cluster under cosmosadmin-c09 account
2. Remote run a IO file
3. Then the browser opened

**Actual result**
it show 'no completed application found' on browser

**Screenshot**
![image](https://user-images.githubusercontent.com/37991481/42801999-0e561a20-89d4-11e8-87bc-3d3b2fbde6eb.png)

**Logs on output** 
Package and deploy the job to Spark cluster
INFO: Begin uploading file /home/yp1/IdeaProjects/project0620/out/artifacts/project0620_DefaultArtifact/default_artifact.jar to Azure Datalake store adl://cosmosadmin-c09.azuredatalakestore.net/SparkSubmission/2018/07/17/45595358-2c4b-4844-91e2-8f3e80dfc790/default_artifact.jar ...
INFO: Upload to Azure Datalake store 67650 bytes successfully.
LOG: 23503486
LOG: "D:\data\yarnnm\local\usercache\cosmosadmin\appcache\application_1531363024066_17746\container_e6086_1531363024066_17746_01_000001\wd\archive-java-spark-livy-2.3.0.zip\jdk1.8.0_144\bin\java" -Xmx128m -cp ""D:\data\yarnnm\local\usercache\cosmosadmin\appcache\application_1531363024066_17746\container_e6086_1531363024066_17746_01_000001\wd\archive-java-spark-livy-2.3.0.zip\spark\bin\..\jars"\*" org.apache.spark.launcher.Main org.apache.spark.deploy.SparkSubmit --deploy-mode cluster --class sample.SparkCore_WasbIOTest --conf spark.executor.instances=2 --conf spark.submit.deployMode=cluster --conf spark.master=spark://MW2SCH101131405:3069 adl://cosmosadmin-c09.azuredatalakestore.net/SparkSubmission/2018/07/17/45595358-2c4b-4844-91e2-8f3e80dfc790/default_artifact.jar
LOG: Invalid switch - "data".
LOG: log4j:WARN Continuable parsing error 2 and column 82
LOG: log4j:WARN Document root element "log4j:configuration", must match DOCTYPE root "null".
LOG: log4j:WARN Continuable parsing error 2 and column 82
LOG: log4j:WARN Document is invalid: no grammar found.
LOG: log4j: reset attribute= "".
LOG: log4j: Threshold ="".
LOG: log4j: Reading configuration from URL jar:file:/D:/data/yarnnm/local/usercache/cosmosadmin/appcache/application_1531363024066_17746/container_e6086_1531363024066_17746_01_000001/wd/archive-java-spark-livy-2.3.0.zip/spark/jars/spark-core_2.11-2.3.0.jar!/org/apache/spark/log4j-defaults.properties
LOG: log4j: Parsing for [root] with value=[INFO, console].
LOG: log4j: Level token is [INFO].
LOG: log4j: Category root set to INFO
LOG: log4j: Parsing appender named "console".
LOG: log4j: Parsing layout options for "console".
LOG: log4j: Setting property [conversionPattern] to [%d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n].
LOG: log4j: End of parsing for "console".
LOG: log4j: Setting property [target] to [System.err].
LOG: log4j: Parsed "console" options.
LOG: log4j: Parsing for [org.spark_project.jetty] with value=[WARN].
LOG: log4j: Level token is [WARN].
LOG: log4j: Category org.spark_project.jetty set to WARN
LOG: log4j: Handling log4j.additivity.org.spark_project.jetty=[null]
LOG: log4j: Parsing for [parquet.CorruptStatistics] with value=[ERROR].
LOG: log4j: Level token is [ERROR].
LOG: log4j: Category parquet.CorruptStatistics set to ERROR
LOG: log4j: Handling log4j.additivity.parquet.CorruptStatistics=[null]
LOG: log4j: Parsing for [org.apache.hadoop.hive.metastore.RetryingHMSHandler] with value=[FATAL].
LOG: log4j: Level token is [FATAL].
LOG: log4j: Category org.apache.hadoop.hive.metastore.RetryingHMSHandler set to FATAL
LOG: log4j: Handling log4j.additivity.org.apache.hadoop.hive.metastore.RetryingHMSHandler=[null]
LOG: log4j: Parsing for [org.spark_project.jetty.util.component.AbstractLifeCycle] with value=[ERROR].
LOG: log4j: Level token is [ERROR].
LOG: log4j: Category org.spark_project.jetty.util.component.AbstractLifeCycle set to ERROR
LOG: log4j: Handling log4j.additivity.org.spark_project.jetty.util.component.AbstractLifeCycle=[null]
LOG: log4j: Parsing for [org.apache.spark.repl.SparkILoop$SparkILoopInterpreter] with value=[INFO].
LOG: log4j: Level token is [INFO].
LOG: log4j: Category org.apache.spark.repl.SparkILoop$SparkILoopInterpreter set to INFO
LOG: log4j: Handling log4j.additivity.org.apache.spark.repl.SparkILoop$SparkILoopInterpreter=[null]
LOG: log4j: Parsing for [org.apache.parquet.CorruptStatistics] with value=[ERROR].
LOG: log4j: Level token is [ERROR].
LOG: log4j: Category org.apache.parquet.CorruptStatistics set to ERROR
LOG: log4j: Handling log4j.additivity.org.apache.parquet.CorruptStatistics=[null]
LOG: log4j: Parsing for [org.apache.spark.repl.Main] with value=[WARN].
LOG: log4j: Level token is [WARN].
LOG: log4j: Category org.apache.spark.repl.Main set to WARN
LOG: log4j: Handling log4j.additivity.org.apache.spark.repl.Main=[null]
LOG: log4j: Parsing for [org.apache.spark.repl.SparkIMain$exprTyper] with value=[INFO].
LOG: log4j: Level token is [INFO].
LOG: log4j: Category org.apache.spark.repl.SparkIMain$exprTyper set to INFO
LOG: log4j: Handling log4j.additivity.org.apache.spark.repl.SparkIMain$exprTyper=[null]
LOG: log4j: Parsing for [org.apache.hadoop.hive.ql.exec.FunctionRegistry] with value=[ERROR].
LOG: log4j: Level token is [ERROR].
LOG: log4j: Category org.apache.hadoop.hive.ql.exec.FunctionRegistry set to ERROR
LOG: log4j: Handling log4j.additivity.org.apache.hadoop.hive.ql.exec.FunctionRegistry=[null]
LOG: log4j: Finished configuring.
LOG: 18/07/16 23:50:36 WARN SparkConf: The configuration key 'spark.executor.port' has been deprecated as of Spark 2.0.0 and may be removed in the future. Not used any more
LOG: Running Spark using the REST application submission protocol.
LOG: log4j: Reading configuration from URL jar:file:/D:/data/yarnnm/local/usercache/cosmosadmin/appcache/application_1531363024066_17746/container_e6086_1531363024066_17746_01_000001/wd/archive-java-spark-livy-2.3.0.zip/spark/jars/spark-core_2.11-2.3.0.jar!/org/apache/spark/log4j-defaults.properties
LOG: log4j: Parsing for [root] with value=[INFO, console].
LOG: log4j: Level token is [INFO].
LOG: log4j: Category root set to INFO
LOG: log4j: Parsing appender named "console".
LOG: log4j: Parsing layout options for "console".
LOG: log4j: Setting property [conversionPattern] to [%d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n].
LOG: log4j: End of parsing for "console".
LOG: log4j: Setting property [target] to [System.err].
LOG: log4j: Parsed "console" options.
LOG: log4j: Parsing for [org.spark_project.jetty] with value=[WARN].
LOG: log4j: Level token is [WARN].
LOG: log4j: Category org.spark_project.jetty set to WARN
LOG: log4j: Handling log4j.additivity.org.spark_project.jetty=[null]
LOG: log4j: Parsing for [parquet.CorruptStatistics] with value=[ERROR].
LOG: log4j: Level token is [ERROR].
LOG: log4j: Category parquet.CorruptStatistics set to ERROR
LOG: log4j: Handling log4j.additivity.parquet.CorruptStatistics=[null]
LOG: log4j: Parsing for [org.apache.hadoop.hive.metastore.RetryingHMSHandler] with value=[FATAL].
LOG: log4j: Level token is [FATAL].
LOG: log4j: Category org.apache.hadoop.hive.metastore.RetryingHMSHandler set to FATAL
LOG: log4j: Handling log4j.additivity.org.apache.hadoop.hive.metastore.RetryingHMSHandler=[null]
LOG: log4j: Parsing for [org.spark_project.jetty.util.component.AbstractLifeCycle] with value=[ERROR].
LOG: log4j: Level token is [ERROR].
LOG: log4j: Category org.spark_project.jetty.util.component.AbstractLifeCycle set to ERROR
LOG: log4j: Handling log4j.additivity.org.spark_project.jetty.util.component.AbstractLifeCycle=[null]
LOG: log4j: Parsing for [org.apache.spark.repl.SparkILoop$SparkILoopInterpreter] with value=[INFO].
LOG: log4j: Level token is [INFO].
LOG: log4j: Category org.apache.spark.repl.SparkILoop$SparkILoopInterpreter set to INFO
LOG: log4j: Handling log4j.additivity.org.apache.spark.repl.SparkILoop$SparkILoopInterpreter=[null]
LOG: log4j: Parsing for [org.apache.parquet.CorruptStatistics] with value=[ERROR].
LOG: log4j: Level token is [ERROR].
LOG: log4j: Category org.apache.parquet.CorruptStatistics set to ERROR
LOG: log4j: Handling log4j.additivity.org.apache.parquet.CorruptStatistics=[null]
LOG: log4j: Parsing for [org.apache.spark.repl.Main] with value=[WARN].
LOG: log4j: Level token is [WARN].
LOG: log4j: Category org.apache.spark.repl.Main set to WARN
LOG: log4j: Handling log4j.additivity.org.apache.spark.repl.Main=[null]
LOG: log4j: Parsing for [org.apache.spark.repl.SparkIMain$exprTyper] with value=[INFO].
LOG: log4j: Level token is [INFO].
LOG: log4j: Category org.apache.spark.repl.SparkIMain$exprTyper set to INFO
LOG: log4j: Handling log4j.additivity.org.apache.spark.repl.SparkIMain$exprTyper=[null]
LOG: log4j: Parsing for [org.apache.hadoop.hive.ql.exec.FunctionRegistry] with value=[ERROR].
LOG: log4j: Level token is [ERROR].
LOG: log4j: Category org.apache.hadoop.hive.ql.exec.FunctionRegistry set to ERROR
LOG: log4j: Handling log4j.additivity.org.apache.hadoop.hive.ql.exec.FunctionRegistry=[null]
LOG: log4j: Finished configuring.
LOG: Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
LOG: 18/07/16 23:50:36 INFO RestSubmissionClient: Submitting a request to launch an application in spark://MW2SCH101131405:3069.

**Comment by wezhang** [comment]
Backend issue
