### ISSUE TITLE
[Intellij][Spark on ADL]it can update cluster when the work status is launch

### ISSUE THREAD

**Issue by liyanp1987** [Microsoft/azure-tools-for-java#1806]
**Repro bits**
azure-toolkit-for-intellij-2018.1.PR.1757.07-16-2018

**Repro Steps**
1. Create a new cluster under cosmosadmin-c09 account
2. Wait the work status is stable. the update item show up on right-click menu
3. Click update and change the container
4. View cluster status and found the work status is launcher
5. Click update again and change container

**Actual result**
It can change successfully

**Screenshot**
![image](https://user-images.githubusercontent.com/37991481/42802465-a802fdea-89d5-11e8-84e6-232591fad3f6.png)

**Comment by t-rufang** [comment]
Re-designed. We enable updating cluster when spark master is stable no matter what the state of worker is.

**Comment by jingyanjingyan** [comment]
fix with 1783
