### ISSUE TITLE
[Intellij][Spark on ADL]Error pop up when input the max number of cores and container

### ISSUE THREAD

**Issue by liyanp1987** [Microsoft/azure-tools-for-java#1808]
**Repro bits**
azure-toolkit-for-intellij-2018.1.PR.1757.07-16-2018

**Issues**
1. when input the max number of cores and container, click OK. it pop up the error as below screenshot,
![image](https://user-images.githubusercontent.com/37991481/42808093-068b8d8c-89e5-11e8-9c16-f86e94560e09.png)

2. when input the max number of container, click ok, it pop up the error as below screenshot,
![image](https://user-images.githubusercontent.com/37991481/42808146-2bfd819c-89e5-11e8-84e5-00a9a6504592.png)

**Comment by liyanp1987** [comment]
3. when calculatedAU < totalAU, click ok, will pop up the error as below,
![image](https://user-images.githubusercontent.com/37991481/42809093-5300845e-89e7-11e8-8e14-a669394fc8ba.png)
![image](https://user-images.githubusercontent.com/37991481/42809104-5a343338-89e7-11e8-89ea-70e23274a32e.png)

**Comment by wezhang** [comment]
I suppose it's clear currently.

**Comment by t-rufang** [comment]
Since the error message is updated and clear enough, I will close this issue.
