### ISSUE TITLE
Eclipse missing Azure Sign In/Out command on context menu

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#181]
a to do: need tp port this addition from IntelliJ

**Comment by lenala** [comment]
![image](https://cloud.githubusercontent.com/assets/6208231/24271429/6268ee9a-0fd6-11e7-9783-d730ec2cde4f.png)

**Comment by xscript** [comment]
Just want to confirm that we are talking about context menu for project, right?

![image](https://cloud.githubusercontent.com/assets/2300784/24285587/cb717e22-10ab-11e7-8367-c08ab45694a5.png)

**Comment by martinsawicki** [comment]
yes, at bottom, with a separator

**Comment by xscript** [comment]
Got it. Thanks for the clarification!

**Comment by lenala** [comment]
This was fixed and merged, please verify.

**Comment by bsaby** [comment]
Test passed, using artifacts/WindowsAzurePlugin4EJ.223.04-05-2017.zip.

**Before sign in:**
![image](https://cloud.githubusercontent.com/assets/22470312/24735057/8f3400da-1ab3-11e7-8489-0e1107b293b9.png)

**After sign in:**
![image](https://cloud.githubusercontent.com/assets/22470312/24735087/bd5256e2-1ab3-11e7-8893-507476c8a2f6.png)
