### ISSUE TITLE
[IntelliJ]Configurantions dialog shows slowly when add Azure HDInsight Spark

### ISSUE THREAD

**Issue by tankungx** [Microsoft/azure-tools-for-java#1810]
azure-toolkit-for-intellij-2018.1.PR.1757.07-13-2018.zip
Steps:
1.Create a new project
2.Click "Edit Configurantions..."
3.Click "+" then choose "Azure HDInsight Spark"

Actual result:
The corresponding dialog on the right pane show slowly(about 8 seconds)

**Comment by jingyanjingyan** [comment]
Fix with market build
