### ISSUE TITLE
[IntelliJ] Should allow to edit spark event in provision dialog

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#1812]
Build 1757, Product

Repro Steps:
launch provision dialog

Result: 
cannot edit event folder

![image](https://user-images.githubusercontent.com/36756024/42812222-824569e8-89ef-11e8-9918-7f8e14c39592.png)

**Comment by t-rufang** [comment]
We will fix this later

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748176
