### ISSUE TITLE
Eclipse Neon - Unable to sign-in to Azure - fails silently

### ISSUE THREAD

**Issue by joshuahinds** [Microsoft/azure-tools-for-java#182]
Using the "Interactive sign-in" method ...
1) Go to the tools menu and select Azure > Sign-in
2) Select "Interactive" option from the Azure sign in dialog
3) Complete the standard steps for 2FA in MSA sign in flow
4) Sign in progress bar appears but then returns me to the same Azure sign in dialog

- Signing in with an alternate Azure account (MSDN) was successful.
- Cleared cookies in IE (running Windows) but it did not resolve the sign-in issue.
- Cleared cookies in Edge and it worked!!

**Comment by vladimir-shcherbakov** [comment]
#268 duplicate
