### ISSUE TITLE
[Intellij][Spark] The test source file identified as a Spark job unexpected in IntelliJ

### ISSUE THREAD

**Issue by ziyel** [microsoft/azure-tools-for-java#1824]
### Version
```
Plugin version: 3.8.0-2018.1
IntelliJ IDEA 2018.1.5 (Community Edition)
Build #IC-181.5281.24, built on June 12, 2018
JRE: 1.8.0_152-release-1136-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```
### Details
One of my `Scala` source code has been identified as Spark job and the default run configuration has been override by `Run[Spark Job]`.
![image](https://user-images.githubusercontent.com/1286176/42934677-4811ad54-8b7a-11e8-9924-2f381f7da81f.png)

**Comment by wezhang** [comment]
The test source file should be ignored

**Comment by jingyanjingyan** [comment]
Repro with develop 965
![image](https://user-images.githubusercontent.com/36756024/51241476-cea07100-1975-11e9-88c1-9619bb2d9df6.png)
