### ISSUE TITLE
[IntelliJ][Spark] Spark Job with exception NoSuchClass didn't fetch the Log

### ISSUE THREAD

**Issue by wezhang** [Microsoft/azure-tools-for-java#1827]

**Comment by lcadzy** [comment]
After repo, it shows application can't launch. We classify this as user error.
![image](https://user-images.githubusercontent.com/43339305/50813125-54a63180-1350-11e9-82a4-895db7e290a5.png)

**Comment by lcadzy** [comment]
same with issue #2466
