### ISSUE TITLE
Reentering the Publish to Docker dialog doesn

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#183]

**Comment by martinsawicki** [comment]
1. Using INtelliJ, create a new  docker host and publish a container
2. After it's successful, open the Publish as Docker Container dialog again
RESULT: The status of the docker host created earlier still shows as STARTING
EXPECT: RUNNING

**Comment by milismsft** [comment]
duplicate -- see #139
