### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by santharamselva** [Microsoft/azure-tools-for-java#1830]
IntelliJ build version: 2018.1.6 IU-181.5540.7
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.9.0-2018.1

# 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).
  5
# 2. What did you like or dislike about Azure Toolkit for IntelliJ?
       like is easy to explore from intellij. Dislike is many plugins are missing with azure and some like radis not working behind proxy.
# 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?
       Proxy support for all plugins and support as much as possible plugins like functional apps. I am sure it is very hard to implement all existing azure service plugin support. But try to give as much as possible service.

**Comment by wezhang** [comment]
Issue #1858 created.
