### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by kaakaydin** [Microsoft/azure-tools-for-java#1835]
IntelliJ build version: 2018.2 IU-182.3684.101
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.9.0-2018.2

# 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).
- 8
# 2. What did you like or dislike about Azure Toolkit for IntelliJ?
- I like Easy development option and settings.
# 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?
- The current version meets my needs

**Comment by wezhang** [comment]
Thanks! Any feedbacks are welcome.
