### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback - blank Azure login page

### ISSUE THREAD

**Issue by ravikoppar** [Microsoft/azure-tools-for-java#1839]
IntelliJ build version: 2018.2 IC-182.3684.101
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.9.0-2018.2

# 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).

# 2. What did you like or dislike about Azure Toolkit for IntelliJ?
After installing Azure Toolkit Plugin, When I click on interactive login, I am getting blank popup screen, hence I am not able to login.

# 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?

**Comment by ravikoppar** [comment]
![azuretoolkitissue](https://user-images.githubusercontent.com/41771168/43302419-0e7e7aae-9188-11e8-895b-42d55b36cf99.jpg)

**Comment by wezhang** [comment]
@Eskibear , have you hit this issue?

**Comment by Eskibear** [comment]
@wezhang No I cannot reproduce. Since it's only a dialog opening the login url, can it be network issue? 
@ravikoppar Are you able to open Microsoft login page in your browser? e.g. This one https://login.microsoftonline.com/login.srf

**Comment by wezhang** [comment]
Can be fixed with #1877
