### ISSUE TITLE
[IntelliJ][ReportedByUser][Workaround] User feedback - annoyed feedback popup

### ISSUE THREAD

**Issue by hangryigor** [Microsoft/azure-tools-for-java#1840]
IntelliJ build version: 2018.1.6 IU-181.5540.7
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.9.0-2018.1

One thing to mention only: I did not even started with this plugin but I am already annoyed with this satisfaction survey message that pops up every time I start IntelliJ.

**Comment by Eskibear** [comment]
Thanks for your feedback. 
@wezhang Could you help to take a look? Does the survey pops up with a proper sampling rate or not?

**Comment by wezhang** [comment]
@hangryigor We'll add a setting page to configure it.

Before that, here is a workaround, you can follow these steps to disable it:

1. Open `Appearance & Behavior > Notifications` setting, Refer to https://www.jetbrains.com/help/idea/settings-notifications.html

2. Select `Azure Toolkit plugin` group, and change the Popup level to `No popup`. If you don't like the event is logged in Event Log window, deselect `Log` check box  please.
![image](https://user-images.githubusercontent.com/7385667/43758355-6e2adb5e-9a4e-11e8-89d5-6723f9de5cf0.png)

**Comment by wezhang** [comment]
Close it since no new comments.
