### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback - Azure GERMANY support

### ISSUE THREAD

**Issue by mcanerim** [microsoft/azure-tools-for-java#1845]
IntelliJ build version: 2018.2 IC-182.3684.101
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.9.0-2018.2

# 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).

1 - It doesn't work for Azure Germany Subscriptions... I mean, come on guys. That's also your product, you can't program it right to understand the different redirection used?

# 2. What did you like or dislike about Azure Toolkit for IntelliJ?

IT DOESN'T WORK ON AZURE GERMANY

# 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?

LET IT WORK ON AZURE GERMANY!

**Comment by Eskibear** [comment]
https://github.com/Microsoft/azure-tools-for-java/issues/1754

**Comment by Eskibear** [comment]
You may want to look at this.

**Comment by t-rufang** [comment]
Please follow the instructions in #1754. Please let us know if still need help.

**Comment by jingyanjingyan** [comment]
Thank you for your feedback, please reopen if you still need help.
