### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback - to support ServiceBus

### ISSUE THREAD

**Issue by chostrander** [microsoft/azure-tools-for-java#1849]
IntelliJ build version: 2018.2 IU-182.3684.101
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.9.0-2018.2

# 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent). 6

# 2. What did you like or dislike about Azure Toolkit for IntelliJ?
-- no option to browse the ServiceBuss

# 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?
-- give ability to browse the serviceBus

**Comment by t-rufang** [comment]
@akaroml customer ask for your information.
