### ISSUE TITLE
Unexpected error while creating Service Principal

### ISSUE THREAD

**Issue by reyang** [Microsoft/azure-tools-for-java#185]
Just followed the instruction, got FAILED from server side without knowing why. Retry doesn't seem to be helpful.

![image](https://cloud.githubusercontent.com/assets/17327289/24054816/e8825402-0afa-11e7-87ee-514a93d5344e.png)

from the log file:

== Starting for tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47'
>> Executing step : Creating Azure Active Directory application...
displayName: AzureTools4j-20170317104412
homePage: https://github.com/Microsoft/azure-tools-for-java
identifierUri: file://sp-72f988bf-86f1-41af-91ab-2d7cd011db47_20170317104412.azureauth
password: ******* 
>> Executing step FAILED: Read timed out
!! Rolling back...
<< Rolling back step: Creating Azure Active Directory application...
<< Roll back SUCCESSFUL

**Comment by martinsawicki** [comment]
is there anything that could be done here?

**Comment by vladimir-shcherbakov** [comment]
read time out duplicate
