### ISSUE TITLE
Spark batch job background task keeps running after disconnecting from cluster

### ISSUE THREAD

**Issue by Silverlight42** [Microsoft/azure-tools-for-java#1850]
Spark batch job background task keeps running after disconnecting from cluster.

Intellij Community 2018.2
JRE 1.8.0
Azure Intellij Toolkit 3.90.0-2018.2

**Comment by wezhang** [comment]
@Silverlight42 , may I get the target Spark cluster type and configurations?

**Comment by Silverlight42** [comment]
Of course.

Spark 2.3

numExecutors 150
driverMemory 24G
executorMemory 4G
executorCores 1

I'm referencing one file and Spark Remote Debug is enabled.

Thanks.

**Comment by wezhang** [comment]
Thank you @Silverlight42 ! I'd like to confirm that action you mentioned:

> disconnecting from cluster.

is to click the `Disconnect` button (![image](https://user-images.githubusercontent.com/7385667/44377312-cced9100-a52e-11e8-8b3a-f6531afa5d26.png)) of `Run` tab?

**Comment by Silverlight42** [comment]
Yes @wezhang!

Thanks.
