### ISSUE TITLE
Azure Plugin for Eclipse doesn't display function apps

### ISSUE THREAD

**Issue by kkadusumilli** [microsoft/azure-tools-for-java#1853]
Azure Plugin for Eclipse doesn't display function apps. Also no provision to deploy function apps. It has provision to build and deploy web apps only.

**Comment by Flanker32** [comment]
@kkadusumilli Function app is not supported in Azure Plugin for Eclipse, but we have enabled this feature in IntelliJ Toolkits, you may get the release notes [here](https://github.com/microsoft/azure-tools-for-java/releases/tag/azure-intellij-toolkit-v3.34.0).
