### ISSUE TITLE
[Feature] Proxy support

### ISSUE THREAD

**Issue by wezhang** [microsoft/azure-tools-for-java#1858]
Many users work behind a proxy, our tools should support it.

- [x] Auth (`com.microsoft.azuretools.adauth`, java.net.HttpURLConnection)
   Auto set with the System properties `http.proxyHost` and `http.proxyPort`
- [x] Apache client needs to fix (HDInsight codes, Apache client)
- [ ] Application Insights client (`com.microsoft.applicationinsights.internal.channel.simplehttp.SimpleHttpChannel::send()`, Apache client)

**Comment by t-rufang** [comment]
Update:  Socks5 proxy is not natively supported by Apache HTTP Client 4

**Comment by wezhang** [comment]
@andxu , Could you help following Application Insights client part? Thanks!

**Comment by andxu** [comment]
Let use #148 to track proxy.
