### ISSUE TITLE
[Eclipse] Interactive login pops up twice

### ISSUE THREAD

**Issue by jianghaolu** [Microsoft/azure-tools-for-java#186]
Please close if this is a known issue.

**Comment by martinsawicki** [comment]
today we have no way to work around the fact that each tenant requires separate auth.
Per Reiley, assigning to Rome to see if the team can figure out a fix.
(Apparently similar behavior in PowerShell)

**Comment by adashen** [comment]
It seems when there is login_hint param in requesting url of https://login.microsoftonline.com/<tenentId>, the browser should be invisible. 
In my scenario, after login the first tenent "common". login_hint is added to the next tenentId, And there is a blank browser dlg show up for a while and dismiss. We may be able fix this part.

**Comment by vladimir-shcherbakov** [comment]
PowerShell login behave similar. 
This happens because if login_hint  provided - browser reads auth cookies (if exist) instead of requesting credentials.
I would recommend you to consider using device-login authorization (like in CLI) instead - to not depend on various browser-controls implementations (SWT/JAVAFX on Mac/WIndows/Linux).

**Comment by adashen** [comment]
@vladimir-shcherbakov 
Hi Vladimir, there are two sides of this issue.
1. Is there any special reason that we need to login all the tenants of the user account? If our app is a multi-tenant one, can we just login "common" to make our app work? Besides, I checked the device-login in azure cli. The "azure login" will just login common. And I also tried just login common in the plugin. It seems we still can get all the subscriptions.
2. If we must login all the tenants, with the current experience, can we just show the dialog when it is necessary for use to input?

**Comment by vladimir-shcherbakov** [comment]
1. Yes - consider MSDN subscription - you can't predict which tenant the subscription is associated with.
2. Your browser behaves like a black-box - after you open the browser and util it redirects you to your redirect URI - you don't know what is happening inside.

**Comment by adashen** [comment]
@bsaby Please verify it in the new build

**Comment by bsaby** [comment]
@adashen  Not repro in the new build: develop409
