### ISSUE TITLE
[Intellij][Spark on ADL] Update cluster cannot work when Spark work status is launch

### ISSUE THREAD

**Issue by liyanp1987** [Microsoft/azure-tools-for-java#1860]
**Repro bits**
azure-toolkit-for-intellij-2018.1.develop.693.08-07-2018

**Repro Steps**
1. Create a new cluster
2. View the cluster status. the spark work status show launch
3. Right click cluster and choose update
4. Update the container and OK

**Actual result**
the cluster does not update successfully

**Expected result**
Should make the update as grey or not show up

**Comment by t-rufang** [comment]
Disabled update option when cluster is not stable.
![image](https://user-images.githubusercontent.com/32627233/50968947-be246c80-1517-11e9-9907-8ff983fd420d.png)

**Comment by jingyanjingyan** [comment]
Fix on market build, the update item is disabled when the cluster is not stable.
