### ISSUE TITLE
[IntelliJ][Spark on ADL] Remote submit with job configurations fails

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1861]
Build: 691
Product: Spark on ADL

Repro Steps
1. Open remote config dialog, set driveMomory, executorMemory with 1. set driverCores, executorCores with 2. 
2. Remote submit
3. Launch Master UI

Result:
Fails
![image](https://user-images.githubusercontent.com/36756024/43772894-54f432c0-9a76-11e8-93c2-652f7aa4f56e.png)

**Comment by t-rufang** [comment]
Value for `executorMemory` and `driveMomory` should be `1g` rather than `1` when we submit spark jobs.

**Comment by jingyanjingyan** [comment]
The value should use 1g or 1024m, add validation with build PR1888
