### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by emulvihill** [Microsoft/azure-tools-for-java#1862]
IntelliJ build version: 2018.2 IU-182.3684.101
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.9.0-2018.2

# 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).
8

# 2. What did you like or dislike about Azure Toolkit for IntelliJ?
Nice Maven support. But I would love if support expanded to non-java projects, such as static web site.

# 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?
More deployment options, expanded support for publishing different types of web projects.

**Comment by wezhang** [comment]
Thanks a lot!
