### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by samirissa00** [Microsoft/azure-tools-for-java#1863]
IntelliJ build version: 2018.2 IC-182.3684.101
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.9.0-2018.2

# 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).
8

# 2. What did you like or dislike about Azure Toolkit for IntelliJ?
I like that is possible upload jar to test on Spark Cluster . 
I dislike that is only for Cluster Spark type , it should be possible developer to HBASE with Phoenix query.

# 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?
Some way to debug the application , like a local program ...

**Comment by wezhang** [comment]
Thanks! @samirissa00 , have you tried this https://docs.microsoft.com/en-us/azure/hdinsight/spark/apache-spark-intellij-tool-debug-remotely-through-ssh?

**Comment by wezhang** [comment]
HBase query feature request dup #1931
