### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by ColemanTO** [Microsoft/azure-tools-for-java#1869]
IntelliJ build version: 2018.2.1 IC-182.3911.36
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.9.0-2018.2

# 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent). 
9

# 2. What did you like or dislike about Azure Toolkit for IntelliJ? 
It works as expected.

# 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?
A dashboard like the website.

**Comment by wezhang** [comment]
Thanks a lot!
