### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by santharamselva** [Microsoft/azure-tools-for-java#1871]
Irritating popup every time open the IDE, even though given comments. How many comments I need to give to stop getting the popup?

IntelliJ build version: 2018.2.1 IU-182.3911.36
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.9.0-2018.2

# 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).

# 2. What did you like or dislike about Azure Toolkit for IntelliJ?

# 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?

**Comment by wezhang** [comment]
Thanks! You can refer to #1840 as a workaround to disable the popup before we provide the specific setting.
