### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by kkzz8888** [microsoft/azure-tools-for-java#1873]
IntelliJ build version: 2018.2.1 IC-182.3911.36
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.9.0-2018.2

# 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).
5
# 2. What did you like or dislike about Azure Toolkit for IntelliJ?
not feature rich.
# 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?

want to do everything from intellij (just like from console) including end to end app dev and deployment.

**Comment by wezhang** [comment]
Thanks! @kkzz8888 which type app do you want to do end-to-end development and deployment?

**Comment by t-rufang** [comment]
Thank you for the feedback. The Azure toolkit for IntelliJ already support Scala shell like environment for interactive query as well as Scala/Java authoring and production deployment. Feel free to reopen the ticket if have additional request.
