### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by sajjad-hk** [microsoft/azure-tools-for-java#1875]
IntelliJ build version: 2018.2 IU-182.3684.101
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.10.0-2018.2

#### 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).
It is very nice and interesting idea but there are some bugs that make it hard to use from beginning

#### 2. What did you like or dislike about Azure Toolkit for IntelliJ?
bug: if you have two different resource group with two app service with same subscription and in just one of the app services you don't have write privilege. None of the app services will recognize and able to select in configuration. 
#### 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?
-

**Comment by wezhang** [comment]
Thanks!

**Comment by wezhang** [comment]
Hi, @Eskibear , could you help follow this?

**Comment by Eskibear** [comment]
> None of the app services will recognize and able to select in **configuration**.

@sajjad-hk By the word "configuration", do you mean somewhere in the RunConfiguration dialog?

**Comment by sajjad-hk** [comment]
@Eskibear Yes in RunConfiguration dialog, where app services suppose to load in the list box.
