### ISSUE TITLE
Cannot use the Azure Toolkit for IntelliJ because I cannot log into Azure

### ISSUE THREAD

**Issue by stalwalk** [microsoft/azure-tools-for-java#1877]
Details:
Support Request number filed with Premium Support: 118081318773396 
Operating System:  Windows 10 running on Dell Laptop
Azure Toolkit for IntelliJ Version: 3.10.0-2018.1
IntelliJ Version: Community Edition 2018.1.6

Problem statement:
When I click on 'Sign in' button of the Azure Toolkit from IntelliJ Idea, i am shown a login page.
Now, my organization **SIEMENS has enforced use of PKI cards(Smart cards)**. I cannot login with user id and password. I have to login with PKI Card.

When I am taken to the sign in page, i am shown an error, "Your browser hasn't submittted the certificate data kind of error. See image for details. 

![azurelogin](https://user-images.githubusercontent.com/42343737/44029954-d9a8ecc2-9f1c-11e8-8fa5-e954bb25aa91.png)

When I am on Home network, i see the same problem. THis is NOT a proxy related issue.
When I login to Azure using IE or chrome , i DONT see any issue
When I install the Azure Storage Explorer standalone application and when I login, I am shown a Login Page and my smart card works fine. There is NO issue with Storage Explorer.
When I try to sign in with Azure Toolkit from IntelliJ i see an error. See the image. I have tried different browsers in the IntelliJ.

**Comment by stalwalk** [comment]
Please note that I have deleted the browser cache, restarted the browser, restarted the machine, restarted IntelliJ. But nothing seemed to help

**Comment by wezhang** [comment]
Thanks @stalwalk ! we'll study the issue.

**Comment by jdneo** [comment]
@wezhang Seems to be a limitation of the Swing framework.

In IntelliJ we are using `WebView` from `JavaFX` which is not IE-core based.

**Comment by wezhang** [comment]
I'm considering to add a new sign-in method with device code, which can be independent with JVM web browser. How about it? @jdneo

**Comment by jdneo** [comment]
Looks cool. By `device code`, do you mean `device login`?

So do you mean the backend of the interactive login will be replaced with the device login?

**Comment by wezhang** [comment]
Yes, the https://aka.ms/devicelogin entry point.

We can add the third sign-in option for the user or as a backup option for the interactive method, after all, which needs an additional action of asking the user to paste the code into the device login web page.

**Comment by jdneo** [comment]
Device login is a great idea. Just one thing I'm concerning is: will that be confusing for users when they find there are three kinds of login methods.

**Comment by wezhang** [comment]
So, you prefer it would be a backup option of the legacy interactive method (provided when the legacy interactive sign-in fails)? 😄

**Comment by jdneo** [comment]
Emm, how about in the login dialog, besides the existing `interactive` and `automated`. There is another text field (or something else) at the bottom, saying `Have trouble with login? Try to use device login(experimental).` And when the user click the text, we go device login.

This is just my opinion.

**Comment by wezhang** [comment]
Wait a minute, refer to https://blogs.oracle.com/java-platform-group/the-future-of-javafx-and-other-java-client-roadmap-updates , **JavaFx will be removed from JDK11SE ...**

Now, I prefer a little to take the device login as the main interactive option method, and the WebView one as a legacy option in the bottom text.

**Comment by jdneo** [comment]
@wezhang Hmm, yes, that makes sense to me.

Add @Matthew-Dong into the thread.

**Comment by jdneo** [comment]
Hi @stalwalk,

While we are discussing the solution. There might be some workarounds to unblock you.

Since PKI is not supported in IntelliJ but supported in Eclipse. You can leverage the Eclipse to generate an authentication file for you:
![image](https://user-images.githubusercontent.com/6193897/44133160-d66ff0f8-a090-11e8-9bc6-560f0e42eaa5.png)

Select `Automated` > `New...` to generate the authentication file.

Then you can go back to IntelliJ, Select `Automated` > `Browse...` to choose the file that is generated in Eclipse.
![image](https://user-images.githubusercontent.com/6193897/44133217-2ece56f4-a091-11e8-9983-e7ea678e37aa.png)

**Comment by Matthew-Dong** [comment]
Suggest we support device login at the bottom of the dialog to unblock customer experience first. If there's an obvious growing adoption of device login, we can re-order login mode later.

**Comment by Flanker32** [comment]
Close as we have deprecated the browser and use device login and service principal as the auth method
