### ISSUE TITLE
Docker Run -> The  URL can't be reached

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1887]
Build: develop#700
Windows/Mac
Steps:
1. Right-click a war/jar project choose Azure -> Add docker support
2. Right-click a war/jar project choose Azure ->Docker Run
3. keep the default configuration
4. Click Run

Result:
The Container URL is shown in the log always `http://localhost:0/` and it can't be reached
![image](https://user-images.githubusercontent.com/22470312/44448044-aefe5a00-a61c-11e8-999d-47d5aa2217c8.png)
![image](https://user-images.githubusercontent.com/22470312/44448105-de14cb80-a61c-11e8-8837-433d29d56022.png)

**Comment by Eskibear** [comment]
fixed for intellij, please help to test.

Also please test whether Eclipse has the same issue, if true, open a new issue please.

**Comment by bsaby** [comment]
Test passed in Eclipse and IntelliJ.
Build used: develop#705
