### ISSUE TITLE
typo in the Azure logout page for the Eclipse plugin

### ISSUE THREAD

**Issue by reyang** [Microsoft/azure-tools-for-java#189]
"Dou you" -> "Do you" :)

![image](https://cloud.githubusercontent.com/assets/17327289/24055044/cd26c76e-0afb-11e7-9107-944b2fb485f8.png)

**Comment by bsaby** [comment]
Test passed in Eclipse, useing artifacts/WindowsAzurePlugin4EJ.128.zip.
But in IntelliJ, it also has above issue, using azure-toolkit-for-intellij.124.zip.
![image](https://cloud.githubusercontent.com/assets/22470312/24228266/1ae8962e-0fae-11e7-9952-36ca2b64b3dc.png)

**Comment by martinsawicki** [comment]
back to @vladimir-shcherbakov for IntelliJ then.

**Comment by bsaby** [comment]
Test passed, using azure-toolkit-for-intellij.132.zip.
