### ISSUE TITLE
Can't configure Application insight

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1890]
Build: develop#700
Steps:
1. Right-click a web project and select Azure-> Configure Application Insights...
2. Check `Enable telemetry with Application Insights`
3. Select an AI in the Instrumentation key list(you can create an AI before)
4. Click OK

Result: 
Can't add Application Insights for Java package to project, so can't send data to AI
![image](https://user-images.githubusercontent.com/22470312/44452404-01457800-a629-11e8-945e-9c25f0a015f3.png)

**Comment by jdneo** [comment]
@bsaby Fixed. Please help verify it in the newest bits. Thanks.

**Comment by bsaby** [comment]
Test passed.
Build used: develop#704
