### ISSUE TITLE
Duplicate account type for storage account

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1892]
Build: develop#702

Only for IntelliJ
Issue1: 
There are three account kind in Storage Account dialog, two of them have same name: Blob storage
Before version only has two account kind: General purpose and blob storage 
Now:
![image](https://user-images.githubusercontent.com/22470312/44457735-9ef37400-a636-11e8-9626-dc35146ce556.png)
Before:
![image](https://user-images.githubusercontent.com/22470312/44458825-f9da9a80-a639-11e8-9c26-c5511db7d526.png)

Issue2:
Using these account types to create storage accounts, I find that the general purpose account have the same configuration with the first blob storage type account  

Account kind: General purpose
![image](https://user-images.githubusercontent.com/22470312/44458719-a9fbd380-a639-11e8-9ab6-f30dcc33621d.png)

Account kind: the first Blob storage
![image](https://user-images.githubusercontent.com/22470312/44458746-c0a22a80-a639-11e8-8436-1690a7b160ab.png)

**Comment by jdneo** [comment]
@bsaby Fixed. Please help verify this in the newest bits. Thanks.

**Comment by bsaby** [comment]
Test passed.
Build used: develop#704

Now, the account kinds are aligned with those in Azure portal
plugin:
![image](https://user-images.githubusercontent.com/22470312/44512609-b3467800-a6ed-11e8-9221-d59a7c72f42b.png)
Portal:
![image](https://user-images.githubusercontent.com/22470312/44512657-e1c45300-a6ed-11e8-97e6-a1e8f2fc2c70.png)
