### ISSUE TITLE
Docker publish dialog: after refresh on hosts list, can't click Next

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#190]
1. Make sure you have at least one Docker Host that IJ knows about
2. Open the Publish to docker container dialog
-- you should see your docker host(s) listed, and the checkbox checked on the first one, Next button enabled
3. Click Refresh on the Docker Hosts list
RESULT: 
- The first Docker Host is unselected (shouldn't it be selected still?)
- The Next button is enabled (shouldn't it be disabled, if no Host is selected?)
EXPECT: 
- The default Docker host should be still selected, if it was selected when I first entered the dialog
- the Next button should not be enabled when no docker hosts are selected
4. Now Check the first Docker Host
RESULT: The Next and Finish buttons are disables and you're stuck
EXPECT: Next / Finish should be enabled

NOTE: If the docker host is then unchecked, and checked again, then the dialog goes into a happy state

**Comment by milismsft** [comment]
Fixed; please verify.

**Comment by martinsawicki** [comment]
@bsaby this is ready for retest

**Comment by bsaby** [comment]
Repro 3，4 ，using azure-toolkit-for-intellij.2017.212.04-04-2017.zip.
**3.** Click Refresh on the Docker Hosts list
RESULT:
The first Docker Host is unselected 
The Next button is enabled
![image](https://cloud.githubusercontent.com/assets/22470312/24695956/6346104c-1a1a-11e7-8f29-2c86a305b2f8.png)
**4.** Now Check the first Docker Host
RESULT: 
The Next and Finish buttons are disables and you're stuck
You can choose two hosts and the Next and Finish buttons are enabled.
![image](https://cloud.githubusercontent.com/assets/22470312/24695900/3ceecc36-1a1a-11e7-9aad-881551f36b9d.png)
![image](https://cloud.githubusercontent.com/assets/22470312/24696231/5856a8c6-1a1b-11e7-9877-0b196c19bc1f.png)

**Comment by milismsft** [comment]
Can you retest and let me know how it works?

**Comment by bsaby** [comment]
Test passed, using artifacts/azure-toolkit-for-intellij.2017.228.04-06-2017.zip.
1. I have at least one Docker Host that IJ knows about.
2. Open the Publish to docker container dialog.

    -  My docker host(s) listed.
    - If i had not published before , the checkbox checked on the first one.
    - If i had published before, the checkbox would choose the one I used before.
    -  The **Next** and **Finish** button are enabled.

3. Click **Refresh** on the Docker Hosts list. 

    - The Docker host selected before refresh will still be selected.
    - The **Next** and **Finish** button are enabled.
