### ISSUE TITLE
[IntelliJ][Spark on ADL]Submit job config file with errors, the icon should be consistent

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1900]
Build:
azure-toolkit-for-intellij-2018.1.PR.1823.08-13-2018

Repro Steps:
1. From Azure Data Lake Spark Pool\cluster\submit job to open the config dialog
2. Keep "Artifact from IntelliJ project" empty, input main class, click "Apply" then "Close"
3. Click "Edit Configurations" from the top-right
4. Click on the configuration file

Result:
The icon in toolbar display with x
The icon in configuration dialog does not has x 
![image](https://user-images.githubusercontent.com/36756024/44521894-5657bb80-a707-11e8-9395-a29866802d3a.png)

**Comment by wezhang** [comment]
That's IntelliJ control it, the cross means there are errors in the run configuration.
