### ISSUE TITLE
[IntelliJ][Spark on ADL] Submit Job config value will not be kept for the next launch

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1901]
Build:
azure-toolkit-for-intellij-2018.1.PR.1823.08-13-2018

Repro Steps:
1. From Azure Data Lake Spark Pool\cluster\submit job to open the config dialog
2. Enter valid value, input main class, click "Apply" then "Close"
3. Launch the config dialog from Submit Job menu item again

Result:
No values
![image](https://user-images.githubusercontent.com/36756024/44522469-388b5600-a709-11e8-8200-ef846f36bb50.png)

Expect:
The configuraiton file has been saved, should keep the values entered.

**Comment by wezhang** [comment]
Thanks! This's by design.

**Comment by jingyanjingyan** [comment]
Pops submit job dialog, enter values, save, then reopen, the values do not populated.

**Comment by v-jiche** [comment]
Verified. Fixed.
Build: azure-toolkit-for-intellij-2018.1.PR.2087.09-20-2018
