### ISSUE TITLE
[IntelliJ][Spark on ADL] Cancel confirm dialog of Submit job will continual anyway

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1904]
Build:
azure-toolkit-for-intellij-2018.1.PR.1823.08-13-2018

Repro Steps:
1. Click Submit Job from a cluster, keep default empty, click SparkJobRun
2. It pops the confirm dialog to edit or continue anyway
3. Click x to dismiss the dialog
![image](https://user-images.githubusercontent.com/36756024/44523189-a20c6400-a70b-11e8-99fb-be06f32a59bc.png)

Result:
Continue anyway

Expect:
Just cancel

**Comment by wezhang** [comment]
Thanks! It's IntelliJ design, not handled by us.
