### ISSUE TITLE
[IntelliJ][Spark on ADL] The default cluster does not show when click submit job from cluster

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1905]
Build:
azure-toolkit-for-intellij-2018.1.PR.1823.08-13-2018

Repro Steps:
1. Click submit job from a cluster, save the configuration file
2. Edit configuration, just dismiss the dialog
3. Click submit job from a cluster again

Result:
The default cluster does not show and get null reference error
Note: this issue does not repro each time, address the issue for further investigate.

**Comment by wezhang** [comment]
New A Project -> New run configuration, IntelliJ IDEA got NPE

**Comment by tankungx** [comment]
Not repro on mac.

**Comment by v-jiche** [comment]
Verified. Fixed
artifacts/azure-toolkit-for-intellij-2018.1.PR.2083.09-19-2018.zip
