### ISSUE TITLE
[IntelliJ][Spark on ADL] Config file from Submit Job, why disable local run

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1906]
Build:
azure-toolkit-for-intellij-2018.1.PR.1823.08-13-2018

Repro Steps:
1. Pops the config dialog by clicking Submit Job from a cluster

Result:
The local run tab is disabled

Expect:
Click Apply then the configuration will be saved as a normal config file that did include the local run tab, so why we disable the tab here?

**Comment by wezhang** [comment]
Thanks! That's by design, to avoid confuse the user when submitting a job. The local run configuration is reenabled when opening the run configuration dialog.
