### ISSUE TITLE
[IntelliJ][Spark on ADL] Edit config with another cluster, what will happen?

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1907]
Build:
azure-toolkit-for-intellij-2018.1.PR.1823.08-13-2018

Repro Steps:
1. Create a config file from ADLSPool\cluster\submit job
2. Edit the config file from Edit Configuration toolbar, with another cluster
3. Click Submit job again

Question:
From current design, it should apply the same configuration that use the other cluster name
It will be weird that i right click on "catest" but the pops config use "cluster2"

**Comment by wezhang** [comment]
Thanks! The run configuration name is not responsible with the cluster selection.
