### ISSUE TITLE
[IntelliJ]The same warning message show in config dialog

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1908]
Build:
azure-toolkit-for-intellij-2018.1.PR.1823.08-13-2018

Repro Steps:
1. Open configuration dialog, enter "a" in driverCores field

Result:
The warning message display below the job configurations and at the bottom of the dialog
For the error "Main Class Name should not be null" will not display at the bottom of the dialog
![image](https://user-images.githubusercontent.com/36756024/44523983-7ccd2500-a70e-11e8-8fc2-f30335c44d2d.png)

Expect:
Design should be consisten.

**Comment by tankungx** [comment]
Fixed no mac

**Comment by v-jiche** [comment]
Verified. Fixed
artifacts/azure-toolkit-for-intellij-2018.1.PR.2083.09-19-2018.zip
