### ISSUE TITLE
[IntelliJ] Submit with "Artifact from IntelliJ project" keep empty get error

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1911]
Build: azure-toolkit-for-intellij-2018.1.PR.1823.08-13-2018

Repro Steps:
1. Right click on one cluster of Spark on adl, click "Submit Job"
2. Select jar file from local, and submit
![image](https://user-images.githubusercontent.com/36756024/44635822-cbaedf00-a9da-11e8-92b9-eed4e454f17b.png)

Result:
![image](https://user-images.githubusercontent.com/36756024/44635834-de291880-a9da-11e8-99ae-044e835c170d.png)

**Comment by wezhang** [comment]
Dup #1903
