### ISSUE TITLE
[IntelliJ]Select jar file, main class will display in double

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1916]
Build: Develop 707

Repro Steps:
1. New a config file, select jar file, Click "..." to select main class

Result:
Main class display in double
![image](https://user-images.githubusercontent.com/36756024/44639637-919c0800-a9ef-11e8-85b5-d31c5c4ac975.png)

**Comment by tankungx** [comment]
Fixed on mac.

**Comment by v-jiche** [comment]
Verified. Fixed 
artifacts/azure-toolkit-for-intellij-2018.1.PR.2083.09-19-2018.zip
--
