### ISSUE TITLE
[IntelliJ]Fail to provision cluster

### ISSUE THREAD

**Issue by tankungx** [Microsoft/azure-tools-for-java#1918]
Build:
artifacts/azure-toolkit-for-intellij-2018.1.develop.708.08-27-2018.zip
Repro Steps:
1. Try to provision a cluster
 
Actual Results:

Fail to provision on Mac but work fine on Windows sometimes

<img width="604" alt="screen shot 2018-08-27 at 3 37 04 pm" src="https://user-images.githubusercontent.com/30617450/44650621-a7262780-aa19-11e8-883f-e24dbbc5cc7c.png">

**Comment by t-rufang** [comment]
We changed the information displayed in the error window so there should be more information when you provision failed now. This issue seems be caused by unstable backend. @jingyanjingyan could you help to verify this issue?

**Comment by v-lanjli** [comment]
verify and closed
