### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback, Spring boot Gradle support

### ISSUE THREAD

**Issue by aldiand** [microsoft/azure-tools-for-java#1919]
IntelliJ build version: 2018.2 IC-182.3684.101
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.10.0-2018.2

#### 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).
5

#### 2. What did you like or dislike about Azure Toolkit for IntelliJ?
No gradle option

#### 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?
Add gradle intergration for azure plugins

**Comment by wezhang** [comment]
Thanks @aldiand ! What types project for Azure you'd like to apply Gradle support?

**Comment by aldiand** [comment]
I suggest add gradle support for spring boot

**Comment by wezhang** [comment]
@Eskibear , could you help to follow this?

**Comment by Eskibear** [comment]
@aldiand Do you mean deploying a Gradle based spring-boot project to Azure Web App?


cc @Matthew-Dong for the feature request.

**Comment by aldiand** [comment]
will this feature added to plugins ?

**Comment by Eskibear** [comment]
> Do you mean deploying a Gradle based spring-boot project to Azure Web App? 

If it is the exact thing you want to do, we actually support it. But unlike maven projects,  gradle-based projects requires you to specify an artifact in IntelliJ IDEA first. I can take a simple SpringBoot project as the example.

1. At first when you click "Run on Web App", the list of artifacts might be empty.
![image](https://user-images.githubusercontent.com/2351748/45887309-f7609180-bded-11e8-9088-da58cf35793b.png)

2. Then you need to set it in **Project Structure** -> **Artifacts**.
![grad](https://user-images.githubusercontent.com/2351748/45887816-2c211880-bdef-11e8-80b6-d7b961506587.gif)


Please let us know whether it works for you.
