### ISSUE TITLE
Double clicking unrefreshed Docker Hosts node doesn't do anything

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#192]
1. Make sure you already have at least one docker host, but you have never tried to refresh the Docker HOosts node in Explorer
2. Double click on the Docker Hosts node
RESULT: Nothing happens
EXPECT: Refresh, just like we do on the other nodes

**Comment by bsaby** [comment]
Test passed, using azure-toolkit-for-intellij.2017.208.04-04-2017.zip.
