### ISSUE TITLE
[IntelliJ][Spark on ADL] Update dialog pops twice when click OK button

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1920]
Build: PR 1877

Repro Steps:
1. Sign in Azure Data Lake Spark Pool
2. Right click on one cluster, click update
3. Change the value of contianer, click OK

Result:
Update dialog pops again.

**Comment by jingyanjingyan** [comment]
Same with #1779, the key step is refresh cluster several times before submit the update dialog.

**Comment by t-rufang** [comment]
Fixed in #2013
