### ISSUE TITLE
[IntelliJ][Spark on ADL] Provision dialog and update dialog display with min size

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1921]
Build: PR 1877

Repro Steps:
1. Sign in Azure Data Lake Spark Pool
2. Pops provision dialog
3. Pops update dialog for an existing cluster

Result:
It display in min size
![image](https://user-images.githubusercontent.com/36756024/44699487-025a2780-aab7-11e8-9dae-a04783c05c12.png)

![image](https://user-images.githubusercontent.com/36756024/44699494-0e45e980-aab7-11e8-97d0-0b9c7893a3c9.png)

**Comment by t-rufang** [comment]
fixed in #1879

**Comment by tankungx** [comment]
Not repro on mac on 2018.2.

**Comment by v-jiche** [comment]
Verified. Fixed.
Build:
azure-toolkit-for-intellij-2018.1.PR.2083.09-19-2018
