### ISSUE TITLE
[IntelliJ][Spark on ADL] The border or Number of Containers is intercepted

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1922]
Build: PR 1877

Repro Steps:
0. Set the Theme with "Darcula" (i use intellij 18.1)
1. Launch Provision dialog or Update dialog
2. Focus on field "Number of Containers"

Result:
The border of "Number of Containers" field
The border of "Size of Worker Containers" section 
are intercepted
![image](https://user-images.githubusercontent.com/36756024/44699701-05a1e300-aab8-11e8-9015-f2634fb43484.png)

**Comment by t-rufang** [comment]
fixed in #1879

**Comment by tankungx** [comment]
Fixed on mac.

**Comment by v-jiche** [comment]
Verified , fixed.
Build:
azure-toolkit-for-intellij-2018.1.PR.2083.09-19-2018
