### ISSUE TITLE
Replace the icon placeholders.

### ISSUE THREAD

**Issue by Eskibear** [microsoft/azure-tools-for-java#1925]
Currently real icons are stored in a private repository. In this repository, icon placeholders(red squares) are created in the corresponding paths. 

Consider to move the icons here if there's no legal issue. Or use the [icon set](https://www.microsoft.com/en-us/download/details.aspx?id=41937) which is public available.

**Comment by wezhang** [comment]
@Eskibear , any plan for this issue?

**Comment by andxu** [comment]
This is done in azure pipeline by @Flanker32 .
