### ISSUE TITLE
[IntelliJ] wording "ool" is missed in "Azure Explorer" 

### ISSUE THREAD

**Issue by tankungx** [microsoft/azure-tools-for-java#1928]
artifacts/azure-toolkit-for-intellij-2018.1.develop.711.08-28-2018.zip

steps:
1. Launch "Azure Explorer" and check the word spelling.

Results:

"ool" is missed.
![miss ool](https://user-images.githubusercontent.com/30617450/44771689-5429ad00-ab9e-11e8-8961-7deedbd8d0d1.png)

**Comment by t-rufang** [comment]
The wording has been changed to `Apache Spark on Cosmos` and this issue does not repro now.
