### ISSUE TITLE
Intellij IDEA sign-in dialog stalls at 'Taking you to your organisation's sign-in page

### ISSUE THREAD

**Issue by redosaka** [Microsoft/azure-tools-for-java#1929]
IntelliJ build version: 2018.2.2 IC-182.4129.33
OS: Windows 7
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.10.0-2018.2

#### 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).

_Unfortunately I'm unable to get through the Azure Login Dialog on Intellij. The dialog stalls at 'Taking you to your organisation's sign-in page...' It never gets there.  Azure login works fine from Eclipse._

**Comment by wezhang** [comment]
I suppose it can be handled with #1877
