### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback -- HBase query support

### ISSUE THREAD

**Issue by samirissa00** [microsoft/azure-tools-for-java#1931]
IntelliJ build version: 2018.2.2 IC-182.4129.33
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.10.0-2018.2

#### 2. What did you like or dislike about Azure Toolkit for IntelliJ?
easy

#### 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?
HBASE QUERY

**Comment by wezhang** [comment]
Thanks @samirissa00 ! Add this feature request into backlogs.

**Comment by t-rufang** [comment]
We don't have plan to support HBase Query in IntelliJ. If you have more details about your scenarios we will be happy to pass over to HBase team.

**Comment by jingyanjingyan** [comment]
Thank you for your feedback, please reopen if you still need help.
