### ISSUE TITLE
Articulate the type of Web App to be Windows 

### ISSUE THREAD

**Issue by Matthew-Dong** [Microsoft/azure-tools-for-java#1932]
Since App Service now supports Linux platform, the Toolkits should articulate that current workflow is deploying to Web App (Windows), in order not to confuse the users. 

![image](https://user-images.githubusercontent.com/7653539/44823549-b41e6300-ac33-11e8-8f2b-f163d79f2069.png)

**Comment by Eskibear** [comment]
@SummerSun is working on #1941 . It will re-use this dialog, and list all Web Apps (both Win and Linux) as candidates. Then I don't think we need to change the title of the dialog.

**Comment by SummerSun** [comment]
Close the issue since the #1941 had been released.

**Comment by Eskibear** [comment]
Cool! Thanks @SummerSun for the new feature.
