### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by TranNgocKhoa** [Microsoft/azure-tools-for-java#1936]
IntelliJ build version: 2018.2.2 IU-182.4129.33
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.11.0-2018.2

#### 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).
8
#### 2. What did you like or dislike about Azure Toolkit for IntelliJ?
Everything runs well I think
#### 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?
None

**Comment by wezhang** [comment]
Thanks! Any feedbacks are welcome.
