### ISSUE TITLE
Double clicking unrefreshed Virtual Machines node doesn't do anything

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#194]
1. Make sure you have some VMs, but you have not refreshed the Virtual Machines node in Explorer yet, so it looks empty
2. Double-click the VMs node

RESULT: Nothing happens
EXPECT: Refresh, just like the WebApps node

(In general, double clicking on a node which lists stuff should result in Refresh)

**Comment by lenala** [comment]
Could not repro, probably already fixed. Please verify.

**Comment by bsaby** [comment]
Test passed, using azure-toolkit-for-intellij.2017.191.03-31-2017.zip.
