### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by FrankZhcz** [Microsoft/azure-tools-for-java#1950]
IntelliJ build version: 2018.1.6 IU-181.5540.7
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.11.0-2018.1

#### 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).
10

#### 2. What did you like or dislike about Azure Toolkit for IntelliJ?
Like

#### 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?
better performance

**Comment by wezhang** [comment]
Thanks! Any feedbacks are welcome.
