### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by piotr-dajlido** [microsoft/azure-tools-for-java#1952]
IntelliJ build version: 2018.2.1 IU-182.3911.36
OS: Mac OS X
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.11.0-2018.2

#### 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).
1

#### 2. What did you like or dislike about Azure Toolkit for IntelliJ?
It's not working in most cases, requires typing passwords and providing too much informations over and over again. Pulling data from Azure sometimes not working, creates plans and repositories every time because can't find already existing.

#### 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?
It should be integrated and easy to use as SpringBoot

**Comment by t-rufang** [comment]
Thank you for the feedback. We have improved the toolkit in the past year, please let us know if you still need help for the mentioned issues above.

**Comment by jingyanjingyan** [comment]
Thank you for your feedback, please reopen if you still need help.
