### ISSUE TITLE
[IntelliJ] The icon of HDInsight is smaller than the others

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1953]
Build : PR1888

Repro Steps:
1. Azure sign in, check the icon of HDInsight

Result:
The icon is smaller than the others
![image](https://user-images.githubusercontent.com/36756024/45128989-d3d2f100-b135-11e8-9638-5ccdd0245c6c.png)

**Comment by Eskibear** [comment]
See: https://github.com/Microsoft/azure-tools-for-java/issues/397

**Comment by Eskibear** [comment]
@wezhang As this has been existing for a long time, will you update the icon in this sprint?

**Comment by wezhang** [comment]
Already talked with PM about this.
