### ISSUE TITLE
[IntelliJ][Spark on ADL] Submit dialog from cluster, warning message status does not correctly

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1954]
Build: PR1888

Repro Steps:
1. Right click on one cluster under Azure Data Lake Spark Pool, click "Submit Job" 
2. Select "Artifact from local disk", leave it empty, warning message in red display
Result: 
The warning message does not display at the bottom of the dialog
3. Select "Artifact from local disk" and select from local place
Result: 
Warning that could not found local jar package at the bottom of the dialog
4. Select main class
Result: 
Warning that no main class at the bottom of the dialog

![image](https://user-images.githubusercontent.com/36756024/45129738-72f9e780-b13a-11e8-996d-462d5430cd1b.png)

**Comment by tankungx** [comment]
Fixed.

**Comment by v-jiche** [comment]
Verified. Fixed
artifacts/azure-toolkit-for-intellij-2018.1.PR.2083.09-19-2018.zip
