### ISSUE TITLE
[IntelliJ]Press upper arrow in job configuration will max the config dialog after switch input method

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1958]
Build: PR1945

Repro Steps:
1. Start a config file, in "Job Configurations", focus on a new line, value field
2. Switch the input method, i use customize Win+Space. 
3. Enter a value 
4. Click Down Arrow
5. Click Upper Arrow 

Result:
The job configuration dialog maxed
Press down arrow, the config dialog will be restore.
![image](https://user-images.githubusercontent.com/36756024/45131366-8e1c2580-b141-11e8-90dd-045d6537c352.png)

**Comment by jingyanjingyan** [comment]
The issue repro with recent PR 1945, update the title and steps and reopen.

**Comment by wezhang** [comment]
It's a Window native behavior. Thanks!
