### ISSUE TITLE
"Refreshing" text appearing twice

### ISSUE THREAD

**Issue by anuchandy** [Microsoft/azure-tools-for-java#196]
![refresh_twice](https://cloud.githubusercontent.com/assets/1471612/24055301/bb3092c8-0afc-11e7-883f-577da6c81ea2.png)

Windows | Eclipse Neon 2.0

**Comment by martinsawicki** [comment]
another duplicate

**Comment by lenala** [comment]
Fixed, please verify.

**Comment by bsaby** [comment]
Test passed, using artifacts/WindowsAzurePlugin4EJ.141.zip.
