### ISSUE TITLE
Add checkstyle to enhance the coding format

### ISSUE THREAD

**Issue by SummerSun** [microsoft/azure-tools-for-java#1960]

**Comment by wezhang** [comment]
Any ideas about it?

**Comment by Eskibear** [comment]
I remember that for `Utils` we already have checkstyle configured. 
See: https://github.com/Microsoft/azure-tools-for-java/blob/develop/Utils/check-tools/src/main/resources/checkstyle.xml

**Comment by Eskibear** [comment]
@wezhang @SummerSun 
I checked the repo, let me explain current status in 3 parts(Utils, Eclipse, IntelliJ), each part has a checkstyle.xml with exactly the same content. But for historical reason (too many existing errors that we cannot fix in a short time), we didn't enable all the check on validation. 

### Utils
Located in `azure-tools-for-java\Utils\check-tools\src\main\resources\checkstyle.xml`

Not enabled. 

### Eclipse
Located in `azure-tools-for-java\PluginsAndFeatures\azure-toolkit-for-eclipse\checkstyle.xml`

**Enabled** only for module `com.microsoft.azuretools.container` (It was started from scratch after we take over the project from the original team).

Actually we enable the check globally, and skip the check for other modules. 

### IntelliJ
Located in `azure-tools-for-java\PluginsAndFeatures\azure-toolkit-for-intellij\config\checkstyle\checkstyle.xml`

Not enabled. See:
```gradle
checkstyle {
    toolVersion = '7.7'
    configFile = new File('config/checkstyle/checkstyle.xml')
    showViolations = false
}
```


### My proposal
It looks like we're focusing on IntelliJ part for the moment, and I suggest to enable check on both "Utils" part and "IntelliJ" part (show the result but without failing the build).  So we can fix them along with our daily development. Any ideas?

**Comment by Eskibear** [comment]
cc @jdneo

**Comment by SummerSun** [comment]
@Eskibear 

Thanks for the detailed explanation of the current status and the great suggestions. I agree that we could enable `IntelliJ` and `Utils` part first. And I really do a lot of import re-ordering in some small PRs. I think we could list the modules that we want to enable, and take some time to do it one by one separately.

**Comment by Eskibear** [comment]
I myself prefer to enable them right now, it doesn’t block the build, just generates some reports.
We had a try to enable it module by module, and as you see now, months passed, little progress.

**Comment by wezhang** [comment]
Can we just enable the check for the coming changes, not the current codes? I won't hope it blocks our developments. For the legacy codes, we can enforce it with the code refactoring.

**Comment by Eskibear** [comment]
>  I won't hope it blocks our developments.

Of course we won't want it to block the development. There's always a flag to not unblock the build. E.g. for gradle checkstyle plugin, `ignoreFailures = true`. It will generate reports but won't fail the build. 

And I think we should also have a discussion to settle down the checkstyle rules, or we can start from the current rules, and change the rules step by step according to the convention and our preference. 

> For the legacy codes, we can enforce it with the code refactoring.
To clarify a little more,  when I mean "enable", I mean to execute the style check, but not that aggressive to let it block the build. According to the current rules, we have style errors in thousands lines, impossible to fix in a short time. So I'm totally agree to improve it gradually after we form into a stable rule set.

**Comment by Flanker32** [comment]
Close the issue as we have already enabled check style in dev ops pipeline
