### ISSUE TITLE
[InteiliJ] Configuration file, after clicking Apply, the button should disable

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#1961]
Build: PR1888
Repro Steps
1. Create a configuration file, enter valid data, click Apply

Result:
The button still enabled
![image](https://user-images.githubusercontent.com/36756024/45150798-8aa88e80-b181-11e8-9848-3f9bb4dd00a1.png)

Expect:
The button should be disabled

**Comment by wezhang** [comment]
Lower the priority to P2, to fix it after finding repro steps

**Comment by wezhang** [comment]
Reopen it when reproduced, please

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748174
