### ISSUE TITLE
[IntelliJ][Spark][RunConf] Submit from context menu, config populated when local config has main class

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#1964]
Build: PR1888

Repro Steps:
1. Create a sample project, right click on "SparkCore_WasbIOTest", click "Submit Spark Application to HDInsight"
2. Enter values like change "numExecutor=1", enter command line arguments=1
![image](https://user-images.githubusercontent.com/36756024/45153833-42419e80-b18a-11e8-9395-c7b4cf3b3a86.png)

3. Click "Apply" to save the configuration then close
4. Right click on "SparkCore_WasbIOTest", click "Submit Spark Application to HDInsight" to pops again, the values populates correctly
5. Open the config file from Edit Configuration, click "Locally Run"
6. Delete the value of "Job main class" and save
7. Right click on "SparkCore_WasbIOTest", click "Submit Spark Application to HDInsight" 

Result:
The config use the default value, "numExecutor=1", and command line arguments=1 are not populated.
![image](https://user-images.githubusercontent.com/36756024/45153880-71f0a680-b18a-11e8-86a0-afc7059ba20e.png)

Expect:
Populate value or not should not depand on the local run main class?

**Comment by wezhang** [comment]
Should bind to the remote run main class

**Comment by jingyanjingyan** [comment]
Still repro with develop 848

**Comment by wezhang** [comment]
@konjac , could you help to have a look?

**Comment by wezhang** [comment]
The mainclass field has been taken out of local run and remotely run configuration tabs
