### ISSUE TITLE
[IntelliJ][Linux] View job Queue is clipped in spark on adl related dialog 

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#1965]
Build: PR1888
System: **Linux**

Reporo Steps:
1. Open provision cluster dialog or update dialog

Result:
"VIew Job Queue" clips 
![image](https://user-images.githubusercontent.com/36756024/45192525-64671980-b27b-11e8-8000-a07cfa4270a9.png)

**Comment by t-rufang** [comment]
Not repro in the latest build.
