### ISSUE TITLE
[IntelliJ][Spark on ADL] User need to refresh to show the Spark on ADL node after sign in

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1966]
Build: PR1888

Repro Steps:
1. Sign in

Result:
Azure Data Lake Spark Pool does not show by default, user need refresh first but no way to know it.
![image](https://user-images.githubusercontent.com/36756024/45196281-10196500-b28e-11e8-82c6-df866a098fa5.png)

2. Sign out
Result:
Azure Data Lake Spark Pool still display, but click it nothing happened, harmless
![image](https://user-images.githubusercontent.com/36756024/45196331-579ff100-b28e-11e8-8170-47f9de313d11.png)

**Comment by wezhang** [comment]
@t-rufang , could you help to check it?

**Comment by v-jiche** [comment]
Spark on ADL node can not be seen whether logged in  or not.

build:
azure-toolkit-for-intellij-2018.1.PR.2083.09-19-2018

![image](https://user-images.githubusercontent.com/35950097/45803246-a9fbfb80-bceb-11e8-950e-34ac20fd86e4.png)
![image](https://user-images.githubusercontent.com/35950097/45803370-0c54fc00-bcec-11e8-9e70-cc39c82015db.png)
