### ISSUE TITLE
[Eclipse] No option to create new network security group

### ISSUE THREAD

**Issue by jianghaolu** [microsoft/azure-tools-for-java#197]
<img width="529" alt="screen shot 2017-03-17 at 10 33 54 am" src="https://cloud.githubusercontent.com/assets/2320445/24055440/42fef65e-0afd-11e7-833e-e94fbb5a93ea.png">

**Comment by martinsawicki** [comment]
yes, it'd be nice as a new feature, maybe next time.

**Comment by wangmingliang-ms** [comment]
please use the latest version
