### ISSUE TITLE
[IntelliJ][HDInsight] Warning message status is not correct

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1973]
Build: PR1888

Repro Steps:
1. Create a sample project
2. Right click on LogQuery, choose "Create[Spark Job] LogQuery..." to open the config dialog
3. Choose remote tab
4. Wait for a while to show the error message

Result:
Warning no cluster but it has
![image](https://user-images.githubusercontent.com/36756024/45207959-48915280-b23e-11e8-8e5d-565f490ee17c.png)

**Comment by wezhang** [comment]
Auto refreshed cluster list won't trigger validation check

**Comment by wezhang** [comment]
No warning for Spark cluster selection is "" (rather than `null`)

**Comment by wezhang** [comment]
dup #1954
