### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback -- to support WebJobs publish

### ISSUE THREAD

**Issue by lhatier** [microsoft/azure-tools-for-java#1975]
IntelliJ build version: 2018.2.3 IC-182.4323.46
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.11.0-2018.2

#### 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).
Don't use
#### 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?
I would like to publish some WebJobs on Azure but I can't. I can only deploy WebApp.... It would be perfect if i can deploy WebJob in the future!

**Comment by wezhang** [comment]
@Eskibear Could you help to follow this?

**Comment by Eskibear** [comment]
It looks a feature request for `WebJob` support. Let's keep this issue open for voting, see how many users are requesting for this feature. 
Also cc @Matthew-Dong for awareness.
