### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by sja** [microsoft/azure-tools-for-java#1978]
IntelliJ build version: 2018.2.1 IU-182.3911.36
OS: Mac OS X
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.11.0-2018.2

#### 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).
2
#### 2. What did you like or dislike about Azure Toolkit for IntelliJ?
Missing IoT and Stream Analytics stuff.
#### 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?
Add IoT Hub message render events and modify Stream Analytics jobs.

**Comment by t-rufang** [comment]
Thank you for the feedback. We will pass your request to the IoT/Stream Analytics team. Meanwhile, if you can share more details about your user scenarios, it would be great helpful! @akaroml for your information.
