### ISSUE TITLE
Eclipse Neon - Signing-in to Azure uses wrong account during MSA flow

### ISSUE THREAD

**Issue by joshuahinds** [microsoft/azure-tools-for-java#198]
Using the "Interactive sign-in" method ...

1. Go to the tools menu and select Azure > Sign-in
2. Select "Interactive" option from the Azure sign in dialog
3. Enter an email address to sign-in with a Microsoft AD account (I used a different email address, not my own).
4. The wrong user is shown on the next screen (see attachment).

![sign-in-wrong-user-01](https://cloud.githubusercontent.com/assets/4510946/24055532/98e2b7d6-0afd-11e7-8b25-3d26b21fef69.jpg)

**Comment by vladimir-shcherbakov** [comment]
The one good solution for this and other browser-interaction-authorization issues - is to switch to device login authorization model to not tinker with all the variety of browser control implementations.

**Comment by martinsawicki** [comment]
not for v3, as there isn't a way to work around this that we can tell,. Maybe in the future, someone can investigate and find a solution.

**Comment by ZhijunZhao** [comment]
Below is the reply from Stuart Kwan of Identity Dev Platform team. 

> You can’t switch accounts today in IE or Edge due to a limitation in MSIT’s AAD setup.
> 
> If you want to sign in as a different account, use Chrome or start IE/Edge under a different user account using RunAs.

**Comment by adashen** [comment]
@bsaby Please help to verify it whether it is still a issue in the new build

**Comment by bsaby** [comment]
@adashen  The same issue still repro in the new build: Develop 409

**Comment by Flanker32** [comment]
We have deprecated the interactive auth method and use device login or service principal instead, so close this issue
