### ISSUE TITLE
Customize exceptions for better categorize and more detailed descriptions 

### ISSUE THREAD

**Issue by SummerSun** [microsoft/azure-tools-for-java#1983]
We use generic `Exception` when parameters or setting models are invalid. 
```Java
if (tierSize.length != 2) {
    throw new Exception("Cannot get valid price tier");
}
```
We could use a customized exception to handle these kinds of exceptions to improve the readability of the function signature and avoid swallowing the `IOException` from SDK.

**Comment by andxu** [comment]
I would suggest to check all "throw new Exception" clauses to make sure that the proper exception is thrown.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738842
