### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by benketteridge** [microsoft/azure-tools-for-java#1989]
IntelliJ build version: 2018.2.3 IU-182.4323.46
OS: Windows 7
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.11.0-2018.2

#### 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).
5. I use the portal.

#### 2. What did you like or dislike about Azure Toolkit for IntelliJ?
Too many requests for feedback

#### 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?
Stop bugging me for feedback

**Comment by t-rufang** [comment]
Thanks for the feedback, this issue has already been addressed.
