### ISSUE TITLE
 "next" is not disabled if "size" is not selected or in loading state. 

### ISSUE THREAD

**Issue by anuchandy** [Microsoft/azure-tools-for-java#199]
![size](https://cloud.githubusercontent.com/assets/1471612/24055584/bf3aeade-0afd-11e7-930f-66312cffa01f.png)

Windows | Eclipse Neon 2.0

**Comment by lenala** [comment]
This is fixed, please verify.

**Comment by bsaby** [comment]
Test passed, using WindowsAzurePlugin4EJ.215.04-04-2017.zip.
