### ISSUE TITLE
[IntelliJ] "could not find the local jar package for Artifact" still displayed

### ISSUE THREAD

**Issue by tankungx** [Microsoft/azure-tools-for-java#1991]
Build: PR1945 windows

Repro Steps:
1. Right click a cluster, choose "Submit Job", wait all null information disappear.

2. Choose "Artifact from local disk", and browse jar file.

Actual:
still display "could not find the local jar package for Artifact"
![image](https://user-images.githubusercontent.com/30617450/45416124-c7a8df80-b6b1-11e8-8ca2-0161b7f041be.png)

**Comment by tankungx** [comment]
add lables

**Comment by v-jiche** [comment]
Verified. Fixed
azure-toolkit-for-intellij-2018.1.PR.2070.09-18-2018 (1)
