### ISSUE TITLE
[Eclipse] Create VM cannot select existing resource group

### ISSUE THREAD

**Issue by jianghaolu** [Microsoft/azure-tools-for-java#200]
The resource group dropdown doesn't show anything.

<img width="527" alt="screen shot 2017-03-17 at 10 38 42 am" src="https://cloud.githubusercontent.com/assets/2320445/24055622/eea2e600-0afd-11e7-9e3a-bad36cf66e80.png">

**Comment by martinsawicki** [comment]
?

**Comment by jianghaolu** [comment]
@martinsawicki the dropdown doesn't show the available resource groups in the subscription.

**Comment by martinsawicki** [comment]
i meant the ? for Elena ;-)

**Comment by lenala** [comment]
duplicate for #280. Fixed, please verify.

**Comment by bsaby** [comment]
Test passed, using WindowsAzurePlugin4EJ.195.03-31-2017.zip.
