### ISSUE TITLE
Icon issue for deployment slots

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#2002]
Build: https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_develop_daily/519/
OS: Windows/Mac/Linux

Result:
![image](https://user-images.githubusercontent.com/22470312/45537676-7a567a80-b837-11e8-8e44-1ae262acf952.png)

Expect(from demo metting):
![image](https://user-images.githubusercontent.com/22470312/45537684-7f1b2e80-b837-11e8-8d59-f7d92442f5d9.png)

**Comment by SummerSun** [comment]
Resolved after the icons merged.
