### ISSUE TITLE
[IntelliJ] [18.1] Job main class display in red when submit a new scala class 

### ISSUE THREAD

**Issue by v-jiche** [Microsoft/azure-tools-for-java#2007]
Build: azure-toolkit-for-intellij-2018.1.PR.1945.09-12

Steps:

1  Create a new scala class named MyClusterApp
2  Edit this new file with following query

import org.apache.spark.SparkConf
import org.apache.spark.SparkContext

object cjm{
  def main (arg: Array[String]): Unit = {
    val conf = new SparkConf().setAppName("MyClusterApp")
    val sc = new SparkContext(conf)
    val rdd = sc.textFile("wasb:///HdiSamples/HdiSamples/SensorSampleData/hvac/HVAC.csv")
    //find the rows that have only one digit in the seventh column in the CSV file
    val rdd1 =  rdd.filter(s => s.split(",")(6).length() == 1)
    rdd1.saveAsTextFile("wasb:///HVACOut")
  }
}

3  Local run this file then remote submit it to get the configure dialog,

Result: 
The Job Main Class name is red .
![image](https://user-images.githubusercontent.com/35950097/45541131-c1953900-b840-11e8-8022-8b9fc005f9a0.png)

**Comment by wezhang** [comment]
Lower priority since it doesn't block the local run.

**Comment by wezhang** [comment]
The red classname is because the class is not in any package.
