### ISSUE TITLE
UI issue in web app property explorer

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#2008]
The issue also repro in previous IDE plugins version in IntelliJ 2018.2.x

Repro steps:

1. Right-click a web app and select Show Properties
2. Click + button to add some settings

Result: 
Incomplete display when inputting
![image](https://user-images.githubusercontent.com/22470312/45541026-7b3fda00-b840-11e8-814b-5abab2ee32d3.png)
After inputing
![image](https://user-images.githubusercontent.com/22470312/45541032-7d099d80-b840-11e8-8c07-fd0b5614006c.png)

**Comment by pl07** [comment]
Test pass in azure java toolkit for intellij 3.37.0-2020.1.
