### ISSUE TITLE
[IntelliJ][Spark on ADL] Spark Run Configuration error warnings are not consistent

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2012]
Build: PR 1945

Repro Steps:
1. Right click on a serverless cluster, click "Submit Job"
2. Submit when no cluster, no class, no cluster&no class

Result:
Could not submit with any invalid data, but could proceed submit when both are invalid.
![image](https://user-images.githubusercontent.com/36756024/45604678-455c4a80-ba26-11e8-9eae-11aa657adc68.png)

**Comment by wezhang** [comment]
After the cluster list refreshed, the warning message is consistent.
