### ISSUE TITLE
Eclipse Mars - Window Sizing is Incorrect for "Deploy Web App"

### ISSUE THREAD

**Issue by selvasingh** [Microsoft/azure-tools-for-java#202]
You know how to repro this Window ...

![image](https://cloud.githubusercontent.com/assets/3642444/24056007/7d8328ca-0aff-11e7-83ae-b9e8f02d8e95.png)

**Comment by vladimir-shcherbakov** [comment]
no repro.

Eclipse Java EE IDE for Web Developers.

Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600

**Comment by martinsawicki** [comment]
@bsaby see if you can repro; we can't on other machines

**Comment by bsaby** [comment]
Not repro.
Using WindowsAzurePlugin4EJ.215.04-04-2017.zip.
Eclipse Java EE IDE for Web Developers.
Version: Mars.2 Release (4.5.2)
Version: Neon.3 Release (4.6.3)
