### ISSUE TITLE
The deployment slot name displayed incomplete on first time click

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#2021]
Build: Develop731
OS: Windows/Linux

Repro steps:
1. Install the plugin in IntelliJ
2. Sign in 
3. refresh Web App node in Azure explorer
3. Click a web app after refreshing

Result:
Clicking on the deployment slot node again will show the complete name
Global
![image](https://user-images.githubusercontent.com/22470312/45617427-e2f65f00-baa4-11e8-9257-f98cd9b55e09.png)
Azure China
![image](https://user-images.githubusercontent.com/22470312/45617431-e7bb1300-baa4-11e8-97bb-ca907f45964d.png)

**Comment by bsaby** [comment]
In today's regression test, this issue cannot be reproduced on Windows and Mac , but on the Linux platform.

Configuration:s 
```
Ubuntu 16.04.4 LTS
Desktop: xfce
```

Screenshots:
Global:
![image](https://user-images.githubusercontent.com/22470312/46243156-8596d200-c403-11e8-89f8-de77044abf36.png)

Azure China:
![image](https://user-images.githubusercontent.com/22470312/46243157-87f92c00-c403-11e8-87e7-de454ac0c500.png)

**Comment by ZhengJun003** [comment]
In today's new feature of deployment slots test, this issue can produced on Win, Mac and Linux platform.

**Comment by SummerSun** [comment]
@bsaby Please help verify

**Comment by SummerSun** [comment]
Since it is a general issue of the UI, not limited to deployment slot, let's use this one #2156 to track and close this one as duplicate.
