### ISSUE TITLE
Data Center names are not friendly while creating VM from Eclipse Azure Explorer

### ISSUE THREAD

**Issue by reyang** [Microsoft/azure-tools-for-java#203]
Minor suggestion: this doesn't align with Azure Portal, which would show friendly name as "West US", "East US 2", etc.

![image](https://cloud.githubusercontent.com/assets/17327289/24056154/d6edbb3c-0aff-11e7-8b58-c95c96f3bbae.png)

**Comment by martinsawicki** [comment]
see Location.displayName() in the java SDK. 
this would help

**Comment by lenala** [comment]
This is fixed, please verify.

**Comment by bsaby** [comment]
Test passed, using artifacts/WindowsAzurePlugin4EJ.129.zip.  
![image](https://cloud.githubusercontent.com/assets/22470312/24233869/c9ee2b72-0fcf-11e7-8945-595146bacc76.png)
