### ISSUE TITLE
Azure Explorer repeatedly displays web applications

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#2030]
Build: Dev734

In the Azure Explorer, right-click Web App node choose refresh
**Expect:**
Process status exists throughout the refresh process and the web app node cannot be refreshed again during the refresh process
![image](https://user-images.githubusercontent.com/22470312/45666202-3f11bf80-bb47-11e8-9234-6d18b9a2d285.png)

**Result:** 
The progress prompt flashes quickly, now manually refreshed again, the list will show duplicate web applications
![image](https://user-images.githubusercontent.com/22470312/45666016-51d7c480-bb46-11e8-8d3c-9b218df3b506.png)

**Comment by SummerSun** [comment]
Met the issue too when we throw the get web apps to run in other thread. The code has been reverted in PR #2028 and explains why. Please help with verification with the latest bits.

**Comment by bsaby** [comment]
Test passed on Windows/Mac.
Build used: Dev739
