### ISSUE TITLE
Missing border for controls in create VM "Associated resources" page 

### ISSUE THREAD

**Issue by anuchandy** [Microsoft/azure-tools-for-java#204]
![missing-border-for-controls](https://cloud.githubusercontent.com/assets/1471612/24056202/03e6426c-0b00-11e7-810e-549bd12bf28c.png)

Windows | Neon 2.0

**Comment by lenala** [comment]
This is fixed, please verify.

**Comment by bsaby** [comment]
Test passed, using WindowsAzurePlugin4EJ.215.04-04-2017.zip.
![image](https://cloud.githubusercontent.com/assets/22470312/24691954/1cf303b8-1a09-11e7-9f6f-a824e40e6c80.png)
