### ISSUE TITLE
Add support to operate on deployment slots

### ISSUE THREAD

**Issue by SummerSun** [Microsoft/azure-tools-for-java#2046]
Operations on deployment slots include:
- [ ] Start a deployment slot
- [ ] Stop a deployment slot
- [ ] Restart a deployment slot
- [ ] Swap with production
- [ ] Open a deployment slot URL in a browser
 - [ ] Refresh the deployment slot node to sync its state running/stop

**Comment by SummerSun** [comment]
Hide the deployment slots node until all operations are ready.

**Comment by Eskibear** [comment]
Remember to revert #2062 after all the related features are implemented.

**Comment by Eskibear** [comment]
You may want to update the description (the checkbox items)?
