### ISSUE TITLE
[IntelliJ][Linux]User need to resize provision dialog when launched

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2051]
Build: PR 2070
System: Linux
Repro Steps:
1. Right click on a cluster of Spark on ADL, click "Provision Spark Cluster"

Result:
User need to resize after launch the provision dialog.
![image](https://user-images.githubusercontent.com/36756024/45726880-c9176200-bbf3-11e8-9679-279faf6b67c5.png)

**Comment by t-rufang** [comment]
Fixed in #2672

**Comment by v-jiche** [comment]
Verified. Fixed.
Build: azure-toolkit-for-intellij-2018.3.develop.965.01-16-2019
