### ISSUE TITLE
Support for IntelliJ IDEA EAP 183

### ISSUE THREAD

**Issue by Eskibear** [Microsoft/azure-tools-for-java#2057]
See:  https://www.jetbrains.com/idea/nextversion/

Attaching v3.11.0 compatibility test result against EAP 183.
![image](https://user-images.githubusercontent.com/2351748/45739987-c84bf380-bc26-11e8-9aeb-4f31b9fb5641.png)

**Comment by wezhang** [comment]
![image](https://user-images.githubusercontent.com/7385667/45742290-3ba43400-bc2c-11e8-9ae2-7551657ad1b3.png)

Looks not a big regression than 182

**Comment by wezhang** [comment]
Intellij build can find those deprecated API invoking and warn them.
