### ISSUE TITLE
[Spark] No invisible chars check for Spark Run Configuration arguments

### ISSUE THREAD

**Issue by wezhang** [Microsoft/azure-tools-for-java#2058]
Some unseen whitespace/invisible chars in Spark Job Run configuration arguments input fields would cause the job submission error. ~~We can leverage Java function `Character.isWhitespace(char)` or `org.apache.commons.lang3.StringUtils.containsWhitespace(s)` to check them.~~

**Comment by jingyanjingyan** [comment]
Fix in develop 839, pops warning for invisible char
