### ISSUE TITLE
Error from Select Subscription Dialog

### ISSUE THREAD

**Issue by simeon4110** [microsoft/azure-tools-for-java#2060]
I get the following error in IntelliJ Build #IU-182.4505.22

It happens when I try click 'Select Subscription..." under the 'Azure' drop-down of the tools menu. I have never had this procedure working, this is my first attempt. 

IntelliJ build version: 2018.2.4 IU-182.4505.22
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.11.0-2018.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,30,2561x1378,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=updateSubscriptionWithProgressDialog, throwable=com.microsoft.azure.CloudException: Status code 401, {"error":{"code":"InvalidAuthenticationTokenAudience","message":"The access token has been obtained for wrong audience or resource 'https://graph.windows.net/'. It should exactly match with one of the allowed audiences 'https://management.core.windows.net/','https://management.core.windows.net'%

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Uncaught Exception  com.microsoft.azure.CloudException: Status code 401, The access token has been ... (#1874)

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Uncaught Exception  com.microsoft.azure.CloudException: Status code 401, The access token has been ... (#1874)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: The access token has been obtained for wrong audience or resource * It should exactly match with one of the allowed audience
