### ISSUE TITLE
[IntelliJ][Mac] Number textbox in "Available AU" and  "AU Required" should not be shown as editable

### ISSUE THREAD

**Issue by tankungx** [Microsoft/azure-tools-for-java#2065]
Build: PR 2083 mac

Repro Steps:
1. Sign in Azure Data Lake Spark Pool
2. Open Provision or update dialog

Actual:
the number textbox in "Available AU" and  "AU Required" should not be shown as editable.

![screen shot 2018-09-20 at 4 30 14 pm](https://user-images.githubusercontent.com/30617450/45806248-22b28600-bcf3-11e8-8430-0ec29e64e43a.png)

**Comment by t-rufang** [comment]
@jingyanjingyan Hi yan, can you help verify this one on Mac?

**Comment by t-rufang** [comment]
Fixed in #2672

**Comment by v-lanjli** [comment]
verify and closed

**Comment by v-lanjli** [comment]
verify and closed
