### ISSUE TITLE
[IntelliJ]value in "executorCores" will not be checked if having checked other key

### ISSUE THREAD

**Issue by tankungx** [Microsoft/azure-tools-for-java#2066]
Build:
2083 

Repro Steps:
Open configuration dialog, Modify key value "driverMemory" to 4, then enter "a" in executorCores field.

Actual:
the value in "executorCores" will not be checked.
![screen shot 2018-09-20 at 4 49 48 pm](https://user-images.githubusercontent.com/30617450/45807615-770b3500-bcf6-11e8-8fde-b705aac78ae9.png)

**Comment by wezhang** [comment]
It's checked, but we only show one error message here. After the first one is fixed, the second one will be shown.
