### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by jtomasov** [Microsoft/azure-tools-for-java#2067]
IntelliJ build version: 2018.2.4 IU-182.4505.22
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.11.0-2018.2

#### 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).
10

**Comment by wezhang** [comment]
Thanks @jtomasov ! Any feedbacks are welcome!
