### ISSUE TITLE
Minor UI issue in the VM creation dialog

### ISSUE THREAD

**Issue by reyang** [Microsoft/azure-tools-for-java#207]
1. the "Associated resources" got truncated, also the "R" needs to be upper case to keep alignment with "Machine Settings"
2. the list control on the left side (with "Subscription", "Select Image", etc.) can be clicked which is strange - either we want to make it clickable and it navigates among the steps, or we make them unclickable.

![image](https://cloud.githubusercontent.com/assets/17327289/24056300/6422685e-0b00-11e7-948b-5f4158b0beac.png)

**Comment by martinsawicki** [comment]
we've removed that nav pane in the recent builds
