### ISSUE TITLE
[IntelliJ][RunConf] Select main class dialog can't list all classes

### ISSUE THREAD

**Issue by t-rufang** [microsoft/azure-tools-for-java#2072]
OS: Windows 10
Build: Version 3.11.0-2018.2
Repro steps:
1. select `artifact from local disk`, and choose the `default_artifact.jar`
2. click `Main class name` select button, the classes list as below.
![image](https://user-images.githubusercontent.com/32627233/45858809-b6d32a80-bd91-11e8-8505-9633ed16d2d2.png)
However, Classes in the default_artifact.jar should contain `main.scala.sample.SparkSQLExample`.
3. If we force the `Main class name` field to be  `main.scala.sample.SparkSQLExample`, the job can be run successfully.

**Comment by t-rufang** [comment]
Wordaround for this issue:
1. Select `Project` tab in the `Select Main Class` dialog
2. Find the jar file in the `External Libraries`
3. Select the class you want to set as main class
![image](https://user-images.githubusercontent.com/32627233/45859096-2ac20280-bd93-11e8-803d-4b5ff229206a.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748170
