### ISSUE TITLE
[IntelliJ] IntelliJ is stuck sometimes when setting configurations.

### ISSUE THREAD

**Issue by v-jiche** [Microsoft/azure-tools-for-java#2073]
IntelliJ is stuck sometimes when setting configurations.

Build: 
azure-toolkit-for-intellij-2018.1.PR.2083.09-19-2018

Frequency: 50%

Repro steps: 
1.  Open Run/Debug configurations dialog.

Result:
IntelliJ is stuck sometimes when setting configurations.
  

![image](https://user-images.githubusercontent.com/35950097/45869674-a59f1380-bdbb-11e8-9efd-2653bcd502ed.png)
![image](https://user-images.githubusercontent.com/35950097/45869683-ac2d8b00-bdbb-11e8-86c5-05fbc68a513e.png)

**Comment by wezhang** [comment]
Could you provide the log?

**Comment by wezhang** [comment]
@v-jiche which version IntelliJ did you use? try 2018.2.4 please.

**Comment by jingyanjingyan** [comment]
The issue repro once with build Develop 763, IntelliJ 18.1, when edit configuration file. And no log for it.

**Comment by jingyanjingyan** [comment]
The issue repro with build develop 771 
Steps: In the run config file, click refresh cluster button continually until the warning message display
![image](https://user-images.githubusercontent.com/36756024/46244622-ef49b880-c3d0-11e8-8111-085867f2d962.png)

**Comment by jingyanjingyan** [comment]
Verify as fixed with private build 2230.
