### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by solnet-phiro** [microsoft/azure-tools-for-java#2074]
IntelliJ build version: 2018.2.4 IU-182.4505.22
OS: Linux
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.12.0-2018.2

#### 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).
5
#### 2. What did you like or dislike about Azure Toolkit for IntelliJ?
Connection issues with azure, sometimes losing track of the instances.
#### 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?
Integration of terraform scripts.

**Comment by t-rufang** [comment]
We would like to understand more about the terraform scripts request. Can you please share more details? Regarding connection with Azure, can you also share the error message or screenshot so we can troubleshooting?

**Comment by jingyanjingyan** [comment]
Thank you for your feedback, please reopen if you still need help.
