### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by Maxsky5** [microsoft/azure-tools-for-java#2075]
IntelliJ build version: 2018.2.4 IU-182.4505.22
OS: Linux
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.12.0-2018.2

#### 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).
I cannot rate it yet, since i was not able to use the plugin.

#### 2. What did you like or dislike about Azure Toolkit for IntelliJ?
I cannot even login to my Azure account, it's stuck on the redirection. I guess it's because it is using http instead of https

#### 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?
Same as #### 1.

**Comment by t-rufang** [comment]
@Flanker32 Could you please follow up since it's related to Azure login?

**Comment by Flanker32** [comment]
@Maxsky5 Really sorry for the inconvenience, we have deprecated the old auth method and provide device login and service principals,you may get the release notes [here](https://github.com/microsoft/azure-tools-for-java/releases), thanks a lot for your feedback.
