### ISSUE TITLE
FTP/FTPS server details (per region) or switch to HTTP/HTTPS

### ISSUE THREAD

**Issue by berndgoetz** [microsoft/azure-tools-for-java#2076]
We're in an Enterprise context and being on VMs, outgoing connections are restricted by rules that have to be put in place. For that I need host name(s) and IP ranges of the Azure FTP(S) infrastructure to be able to put it into a rule. What would be better, though, is to move away from FTP(S) to a HTTP(S) based protocol in order to get rid of FTP(S) dependencies. Any insights on the planning here would be very much appreciated. If there are no plans on this, please consider this as a change request. Thanks.

**Comment by andxu** [comment]
@berndgoetz Are you using Azure App service? We now uses kudo for deployment,m see https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file-or-url for details.
