### ISSUE TITLE
[Eclipse] Create VM fails without further error message

### ISSUE THREAD

**Issue by jianghaolu** [Microsoft/azure-tools-for-java#208]
Screen recorded:

https://vimeo.com/208872075

**Comment by martinsawicki** [comment]
sounds like an SSH config issue in the code

**Comment by lenala** [comment]
Ssh issue fixed, will fix the error message.

**Comment by lenala** [comment]
Added error message to the error window. Please verify.

**Comment by bsaby** [comment]
Test passed for ssh issue and error message. 
Build Used:
**azure-toolkit-for-intellij.2017.208.04-04-2017.zip**.
 **WindowsAzurePlugin4EJ.213.04-04-2017.zip**

![image](https://cloud.githubusercontent.com/assets/22470312/24687935/2d63de1c-19ef-11e7-8567-73df7cbe6242.png)
![image](https://cloud.githubusercontent.com/assets/22470312/24689040/8aa9b6ee-19f6-11e7-8ab1-aa954daaf09d.png)
