### ISSUE TITLE
[IntelliJ] Wrong warning in the Run/Debug configurations window

### ISSUE THREAD

**Issue by v-jiche** [Microsoft/azure-tools-for-java#2084]
Build:
azure-toolkit-for-intellij-2018.1.PR.2087.09-20-2018

Repro Steps:
1. Open Run/Debug configurations window
2. Click the plus sign to add a new configuration
3. The warning appears on the interface
4. Enter some text randomly in the Job main class filed

Result:
The warning is still here.
![image](https://user-images.githubusercontent.com/35950097/45996498-fcb02b80-c0ce-11e8-845a-e151a33854ba.png)
![image](https://user-images.githubusercontent.com/35950097/45996516-12bdec00-c0cf-11e8-9f7a-c6636d8517a6.png)

Expect:
The warning should be changed.

**Comment by wezhang** [comment]
Currently, the warning check only cover the remotely run

**Comment by jingyanjingyan** [comment]
Suggest: Could we use warning like "Remote\MainClassName should not be null." ? Current behavior might confuse user. Thx.

**Comment by jingyanjingyan** [comment]
Verify as fix with build develop 788, the warning message update to "Invalid Data: [Remotely Run in Cluster] Main Class Name should not be null" now.
