### ISSUE TITLE
Using resource group name provided in "associated resources" page in "create storage account" page

### ISSUE THREAD

**Issue by anuchandy** [microsoft/azure-tools-for-java#209]
when user give a new resource group name in create VM "associated resources" page, we  could show it as default value of "resource group" in "create storage account" page.

![reuse-rg-name](https://cloud.githubusercontent.com/assets/1471612/24056500/35d699a6-0b01-11e7-84d1-9e552a81fe18.png)

**Comment by martinsawicki** [comment]
the idea we discussed is to *lazily* create the Storage Account, not as soon as that storage account dialog is exited.

**Comment by martinsawicki** [comment]
since this would only be a convenience feature, we can postpone at this point

**Comment by Flanker32** [comment]
Duplicated with #64
