### ISSUE TITLE
[IntelliJ][LinkCluster][Spark]Unable to link a secure hadoop cluster

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#2091]
Build:
azure-toolkit-for-intellij-2018.1.PR.2087.09-20-2018

Repro Steps:
1. Open **_Azure Explore_**, Right click _**HDInsight**_ and click _**Link A Cluster**_
2. Enter the text on the picture to link a cluster.

Result:
Unable to link a cluster.

![image](https://user-images.githubusercontent.com/35950097/46008544-a7d0dd00-c0ef-11e8-954e-2118e7167e3f.png)

**Comment by t-rufang** [comment]
@wezhang Hi Wei, do you know where to find the credential for a secure hadoop cluster?

**Comment by wezhang** [comment]
No way. This cace, we need to check if it still repo.

**Comment by t-rufang** [comment]
Synced with @jingyanjingyan , seems like we don't have a secure hadoop cluster for test now.

**Comment by t-rufang** [comment]
Close this bug since it's not repro now.
