### ISSUE TITLE
Eclipse Mars - Azure Explorer -> Web Apps Keeps Refreshing But No Results

### ISSUE THREAD

**Issue by selvasingh** [Microsoft/azure-tools-for-java#210]
Open Eclipse with Azure Toolkit for Eclipse
Sign in
Go to Azure Explorer
Click on Web Apps
You will see it refreshing forever

![image](https://cloud.githubusercontent.com/assets/3642444/24056603/ad53f028-0b01-11e7-95a8-f3c276e02dee.png)

**Comment by lenala** [comment]
duplicate to #231. Fixed, please verify.

**Comment by bsaby** [comment]
Test passed, using artifacts/WindowsAzurePlugin4EJ.150.zip.
