### ISSUE TITLE
[IntelliJ][console] add hint of ctrl+enter

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#2104]
Build: Develop 762

Repro Steps:
1. Start a local console or interactive console

Result:
No hint for the submit shortcut key Ctrl+Enter
![image](https://user-images.githubusercontent.com/36756024/46125505-ea420900-c218-11e8-86fe-166f22cdeb4e.png)

**Comment by t-rufang** [comment]
Good suggestion. Please check how Kotlin REPL implement this feature.
![image](https://user-images.githubusercontent.com/32627233/85122278-e0680100-b258-11ea-8ce6-2dace2c05a0b.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748169
