### ISSUE TITLE
Eclipse Neon - Automated Azure sign-in unsuccessful with unclear result and messaging 

### ISSUE THREAD

**Issue by joshuahinds** [Microsoft/azure-tools-for-java#211]
When attempting to create a new authentication file for automated sign-in, the creation process ends with the following messaging (see screenshot). This does not seem like a sufficient error message for this type of error. The reason for the sign-in error is unclear. The same account and subscription settings were used to sign-in using the interactive method. Would prefer a much simpler error screen with clear messaging, expansion to see the details (table) and additional links to access help information, or go to the log files. 

![sign-in-12-auto-save-file](https://cloud.githubusercontent.com/assets/4510946/24056572/7c8288d8-0b01-11e7-983b-37fa89ba38af.PNG)

**Comment by martinsawicki** [comment]
this is a more complex issue as there could be multiple failures here if the user is choosing multiple subscriptions at once, so a popup dialog might not work well. Also, this error text comes directly from Azure. If we see users bumping into this a lot, it may warrant providing a more customized error message, but for now, we're just returning Azure's error message.  (Basically the credentials the users is signing in with do not have access to service principal creation in the respective AD tenant)
