### ISSUE TITLE
[IntelliJ] Launch local console without config will warning no main class

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2119]
Build: Develop 763

Repro Steps:
1. Do not have any run config file
2. Click "Tools\Spark Console\Run Spark Local Console(Scala)"

Result:
Warning "Spark job's main class isn't set"
![image](https://user-images.githubusercontent.com/36756024/46241691-1f548400-c3f0-11e8-9ee7-37241a19d5e0.png)

Expect:
Main class is not the request field for local console
May should not create config automatically, or should not give the warning

**Comment by wezhang** [comment]
Workaround is to set a mainclass

**Comment by jingyanjingyan** [comment]
Fix in develop 839
Will create a config file, and not related to the main class config.
