### ISSUE TITLE
Open wrong published link if has published link in two InteliiJ window

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-tools-for-java#2125]
The issue also repro in previous marketplace version, so it is not a regression issue.
OS: Win/Mac

Reproduce steps
1. In a IntelliJ window, open a project and publish as a docker container.
2. Click link "published" in Azure Activity Log dialog, it will navigate to the right URL
3. Open another project in a  new IntelliJ window, and publish as a docker container too.
4. Click link "published" in Azure Activity Log dialog, it will also navigate to the right URL

Result:
Now, click link "published" in step 2 Azure Activity Log dialog again, it will navigate to the URL of step 4.

![image](https://user-images.githubusercontent.com/41051257/46243074-5e8bd080-c402-11e8-8d26-a8c923822e27.png)
![image](https://user-images.githubusercontent.com/41051257/46243080-6f3c4680-c402-11e8-9500-0c30358ec75b.png)

**Comment by ZhengJun003** [comment]
According to this issue: #4353, can't reproduce this issue

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738766

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
