### ISSUE TITLE
Notify the user if operations on web app or deployment slot fail

### ISSUE THREAD

**Issue by SummerSun** [microsoft/azure-tools-for-java#2126]
We have no error handling when there is an error or exception for starting/stopping/restarting etc. operations on a web app or a deployment slot. 
It is very confusing for users to see nothing when the operation does not succeed as expected.

We could discuss the error handling, like a pop-up dialog or notifications in the notification bar.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738841
