### ISSUE TITLE
[IntelliJ] Cannot remote debug with the linked livy cluster

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2128]
Build: Develop 771

Repro Steps:
1. Link a livy cluster with the following settings
![image](https://user-images.githubusercontent.com/36756024/46244542-f15f4780-c3cf-11e8-9ae7-c976003a597e.png)

2. Open run config file, set the advanced settings

Result:
ssh authentication is fail
![image](https://user-images.githubusercontent.com/36756024/46244553-063bdb00-c3d0-11e8-99e4-ed9e8f5c71f2.png)

**Comment by t-rufang** [comment]
@jingyanjingyan Is this cluster an HDInsight cluster with SSH tunnel established?

**Comment by wezhang** [comment]
dup #2362
