### ISSUE TITLE
[IntelliJ] Link a HDInsight cluster with part of the url success

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2131]
Build: Develop 771

Repro Steps:
1. Link a cluster with the cluster url: https://spark22blobhdi.a
![image](https://user-images.githubusercontent.com/36756024/46252343-2cf12480-c457-11e8-8bd1-f24e95247447.png)

Result:
Success

Expect:
Check the whole URL?

**Comment by t-rufang** [comment]
This is by design. The cluster URL is used to extract cluster name.

**Comment by jingyanjingyan** [comment]
Close as design.
