### ISSUE TITLE
[IntelliJ] ESC could not dismiss dialog

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2133]
Build: Develop 771

Repro Steps:
1. Open following dialog and press ESC to dismiss
Provision Spark Cluster
View cluster status (Cluster Status)
Link a New Emulator
Link A Livy Cluster

Result:
Could not dismiss the dialog

Expect:
Should allow to dismiss active dialog with ESC.

**Comment by t-rufang** [comment]
@wezhang Is this common sense to use `Esc` to dismiss a dialog in IntelliJ?

**Comment by wezhang** [comment]
It is. And weird here, the `DialogWrapper::createCancelAction()` has registered `ESC` as cancel action. 

@jingyanjingyan , in my test, when you switch the focus to some input fields, the `ESC` key works.

**Comment by wezhang** [comment]
@t-rufang , let's switch the focus to the first input field automatically.

**Comment by t-rufang** [comment]
Sure, I'll take a look at this.

**Comment by t-rufang** [comment]
Fixed in #2672

**Comment by jingyanjingyan** [comment]
Fix in develop 965
