### ISSUE TITLE
[Intellij] The number of  Available AU and  total AU should not be the same 

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#2135]
Build: azure-toolkit-for-intellij-2018.1.develop.763.09-27-2018

Repro Steps: 
1.Open the  Azure Explorer ,right click on cluster,select Update to pop up dialog Update Cluster.
2.The number of  Available AU and  total AU are  same 

Result:
![image](https://user-images.githubusercontent.com/43333874/46254037-fa86fd80-c43d-11e8-9939-a7706879cb12.png)

Expect:
The number of  Available AU and  total AU should not be same

**Comment by t-rufang** [comment]
Currently there is no REST API to get token used by Spark on Cosmos clusters, this feature reply on backend support.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748168
