### ISSUE TITLE
[Intellij]Expect to add prompts during system configuration

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#2138]
Build:
azure-toolkit-for-intellij-2018.1.develop.763.09-27-2018

Repro Steps:
1. Create a new project and configure the configuration.
2. Open project structure and add libraries.
3. Run Spark Local Console(Scala).

Result:
A warning will appear.
![image](https://user-images.githubusercontent.com/35950097/46255911-f0b0d900-c4d5-11e8-9f5e-10157b31b2d2.png)

Note:
It is not a bug, It shows that the system has not finished its configuration. 
I would like to suggest that we could add a system state prompt information to improve the user experience.

**Comment by wezhang** [comment]
It's better to disable the menu item when the project is initializing

**Comment by t-rufang** [comment]
Not repro now.
