### ISSUE TITLE
Eclipse Mars - Create Docker Host Windows is Mangled

### ISSUE THREAD

**Issue by selvasingh** [Microsoft/azure-tools-for-java#214]
Open Eclipse with Azure Toolkit for Eclipse
Sign in
Create a Web App
Start the Publish to Docker workflow ..
Create Docker Host Window

Many text boxes are empty - Region, Host OS, Size and then there a red error message

![image](https://cloud.githubusercontent.com/assets/3642444/24057102/71ab82c8-0b03-11e7-9f20-005b1688aba6.png)

**Comment by selvasingh** [comment]
More empty fields 

![image](https://cloud.githubusercontent.com/assets/3642444/24057185/b8e797e4-0b03-11e7-8c89-c2ddcafe8485.png)

**Comment by selvasingh** [comment]
![image](https://cloud.githubusercontent.com/assets/3642444/24057198/cd5082b8-0b03-11e7-951d-659069ed53b6.png)

**Comment by milismsft** [comment]
Publishing to Docker was not ready for testing via Eclipse...
