### ISSUE TITLE
Application Insights web descriptor should inlude listener

### ISSUE THREAD

**Issue by littleaj** [Microsoft/azure-tools-for-java#2140]
I found the relevant pieces of code [for Eclipse](https://github.com/Microsoft/azure-tools-for-java/blob/79994cd679a092b6512972c7b8f2a836da52abda/PluginsAndFeatures/azure-toolkit-for-eclipse/com.microsoft.azuretools.core/src/com/microsoft/azuretools/core/applicationinsights/AILibraryHandler.java#L241) and [for IntelliJ](https://github.com/Microsoft/azure-tools-for-java/blob/79994cd679a092b6512972c7b8f2a836da52abda/PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/intellij/ui/libraries/AILibraryHandler.java#L229).

With the current version of the Application Insights SDK, 2.2.0, the web.xml should also include this listener, as described here: https://github.com/Microsoft/ApplicationInsights-Java/issues/744

Related issues:
https://github.com/Microsoft/ApplicationInsights-Java/issues/755
https://github.com/Microsoft/azure-tools-for-java/issues/2122

**Comment by SummerSun** [comment]
Fixed in #2144 

Thanks for the solution.
