### ISSUE TITLE
[IntelliJ][ReportedByUser] The report feature itself is too pushy

### ISSUE THREAD

**Issue by haokanga** [Microsoft/azure-tools-for-java#2142]
IntelliJ build version: 2018.1.3 IU-181.4892.42
OS: Mac OS X
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.10.0-2018.1

#### 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).
1

#### 2. What did you like or dislike about Azure Toolkit for IntelliJ?
The IntelliJ Event log is supposed to track critical events, and it should complain aloud only when things go wrong. There are several times that the event log window drew my attention but it turns out to be this survey request.

```
11:02 AM	We're listening
				Thanks for helping Microsoft improve Azure Toolkit experience!
				Your feedback is important. Please take a minute to fill out our
				user satisfaction survey
```

To be honest, I understand that you want to user feedback but asking the users to fill the survey each time they open IntelliJ is way too pushy. 

#### 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?
Limit the frequency of this survey request, and give the user the option to disable it.

**Comment by Eskibear** [comment]
Thanks for the feedback, we will improve the approach in the coming version.

For the moment, [here ](https://github.com/Microsoft/azure-tools-for-java/issues/1840#issuecomment-410948559)is a workaround to disable it. 

Also cc @wezhang for awareness.

**Comment by wezhang** [comment]
Thanks @haokanga ! It's fixed.
