### ISSUE TITLE
The header in the create new virtual machine dialog is missing

### ISSUE THREAD

**Issue by alvadb** [Microsoft/azure-tools-for-java#215]
Expected to see title text or some description.

**Comment by alvadb** [comment]
Title missing for select image panel

**Comment by martinsawicki** [comment]
the dialog template will be refactored

**Comment by lenala** [comment]
Done, please verify.

**Comment by bsaby** [comment]
Test used WindowsAzurePlugin4EJ.195.03-31-2017.zip.
The drop-down boxes can not be displayed completely.
![image](https://cloud.githubusercontent.com/assets/22470312/24574628/62ca9fde-16c8-11e7-9e0d-3469bfbee176.png)

**Comment by lenala** [comment]
This is fixed for #204.

**Comment by bsaby** [comment]
Test passed, using WindowsAzurePlugin4EJ.215.04-04-2017.zip.
