### ISSUE TITLE
No element <listener> be added when enabling the telemetry with AI in Eclipse

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#2150]
Steps:

1. Right-click a web dynamic project -> Azure -> Configure Application Insights...
2. Enable telemetry with Application Insights

Result:
![image](https://user-images.githubusercontent.com/22470312/46645070-a3a7c380-cbb5-11e8-84ad-0ce579c80ad6.png)

Expect(screeshot from IntelliJ plugin):
![image](https://user-images.githubusercontent.com/22470312/46645075-a86c7780-cbb5-11e8-8911-eb8449e0c32e.png)

**Comment by Eskibear** [comment]
See #2144

**Comment by bsaby** [comment]
Fixed and the test passed.
Build: develop1005
