### ISSUE TITLE
[IntelliJ] Re-run remote debug pops auth error 

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#2152]
Build: develop 776

Repro Steps:
1. Remote debug with spark23hdinsight, success
2. Click re-run button

Result:
Pops the error
![image](https://user-images.githubusercontent.com/36756024/46651661-48afa580-cb90-11e8-8110-371ba439c52a.png)

![image](https://user-images.githubusercontent.com/36756024/46651672-4d745980-cb90-11e8-977f-c2f7183bcf7f.png)

**Comment by jingyanjingyan** [comment]
Repro with market build, i use cluster "Spark23-hdi3-yan"

**Comment by jingyanjingyan** [comment]
Repro with dev 1137

**Comment by wezhang** [comment]
@v-lanjli , could you help repro it at most recent release? Thanks!

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748167
