### ISSUE TITLE
Wrong console log when deploying to a new Linux Web App

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#2154]
Build used: Daily536

Steps:
1. Right-click project -> Azure -> Run on Web App
2. New a Web app with Linux Runtime
3. Deploy

Result:
![image](https://user-images.githubusercontent.com/22470312/46652738-90592000-cbd6-11e8-841d-a3afe9da8074.png)

Expect:
![image](https://user-images.githubusercontent.com/22470312/46653058-913e8180-cbd7-11e8-979c-f2b53a96dea9.png)

**Comment by Eskibear** [comment]
@SummerSun please help to take a look at the message.

**Comment by bsaby** [comment]
Test passed on Windows.
Build used: develop788
![image](https://user-images.githubusercontent.com/22470312/46776574-cdd8bd00-cd3e-11e8-98a3-e580c20e259a.png)
