### ISSUE TITLE
Can't deploy to an war Windows type deployment slot without production configuration resource

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#2155]
Build used: Daily536

Repro steps:
1. Right-click a web project-> Azure -> Run on Web App
2. Deploy to a new Windows Web App
3. After deployment, create deployment-slots on portal with below configuration source
![image](https://user-images.githubusercontent.com/22470312/46653530-e29b4080-cbd8-11e8-9315-2f2629ca4260.png)
4. Right-click the web project again and deploy to this slot: slot1

Result:
Always fails with error message: FTP client can't store the artifact, reply code: 550.
![image](https://user-images.githubusercontent.com/22470312/46653561-fcd51e80-cbd8-11e8-882a-bcbd7d2ecca0.png)

Try creating a slot with production configuration source, then can deploy to this slot successfully
![image](https://user-images.githubusercontent.com/22470312/46654104-7de0e580-cbda-11e8-907f-004c65cead42.png)

![image](https://user-images.githubusercontent.com/22470312/46653726-648b6980-cbd9-11e8-8ef4-63bf8886bc98.png)

By design?

**Comment by Eskibear** [comment]
@bsaby From the screenshots, I also see that they are uploading different war files,  "helloworld.war" vs "ROOT.war".  Is there any difference between the run configuration? (e.g like deploy to root?)

@SummerSun please help to investigate if it's normal for deployment slots.

**Comment by bsaby** [comment]
Sorry for the confusion, actually the failure has nothing to do with run configuration but related to the slot creation configuration source.

Add two more screenshots：
Deploy to slot1 with root configuration： Failed
![image](https://user-images.githubusercontent.com/22470312/46774812-ddec9e80-cd36-11e8-9c67-80e7230c8e2b.png)

Deploy to slot2 with not root configuration: Successful
![image](https://user-images.githubusercontent.com/22470312/46774781-ba295880-cd36-11e8-81cd-1078f2473240.png)

**Comment by SummerSun** [comment]
The issue is caused by that there is no `webapps` folder when creating a new windows deployment slot with no configuration source. The behavior is designed by SDK/Service side. We will discuss whether to add our workaround.

**Comment by ZhengJun003** [comment]
Can't reproduce this issue in azure toolkits for IntelliJ 3.38.0
