### ISSUE TITLE
The Web App name displayed in Azure Explorer is incomplete

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#2156]
This issue isn't stable and easy to repro, it is highly repro on the first time refresh after opening IntelliJ window, maybe you can encounter it by following steps:

Repro Steps:
1. Install plugin Azure Toolkits for IntelliJ 
1. Sign in 
1. Refresh Web App node in Azure Explorer

![image](https://user-images.githubusercontent.com/22470312/46655529-6b68ab00-cbde-11e8-8d2b-d1bc31a6da4a.png)

**Comment by EricZhangzf** [comment]
I havan't meet this issue on v3.37.0
