### ISSUE TITLE
[IntelliJ]The  log will not show "job run successfully" when in Link Livy Cluster dialog, do not set “Yarn Endpoint”

### ISSUE THREAD

**Issue by v-xiaocw** [Microsoft/azure-tools-for-java#2158]
Build: azure-toolkit-for-intellij-2018.1.PR.2202.10-08-2018
Repro Steps:
1.Right click on HDInsight ,select "Link A Livy Cluster"
2.Click the dropdown list of the "cluster info,"then select "Livy service",set up other items and leave "yarn endpoint" vacant.
3.Submit job to the linked cluster with the settings above 
Result:
![image](https://user-images.githubusercontent.com/43333874/46663437-edbb8580-cb72-11e8-94c0-81c5298ecc4b.png)
Expect:
Should show "Job run successfully" like below
![image](https://user-images.githubusercontent.com/43333874/46663586-5a368480-cb73-11e8-9ff5-12dcb9e3e8dc.png)

**Comment by v-jiche** [comment]
Still Repro.
Build: azure-toolkit-for-intellij-2018.2.71.10-31-2018

**Comment by jingyanjingyan** [comment]
Repro with develop 869

**Comment by jingyanjingyan** [comment]
Consider make the log more friendly.

**Comment by lcadzy** [comment]
After check,we find out once user dosen't fill the yarn endpoint when linking the livy cluster,we can't get the job log and result since these are based on the endpoint.
