### ISSUE TITLE
[IntelliJ] Add a scroll bar in run config dialog when expand settings

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2159]
Build: Private 2219

Repro Steps:
1. Open one run config dialog, expand all settings

Result:
The last one is out of sight
![image](https://user-images.githubusercontent.com/36756024/46707995-09369700-cc2c-11e8-88cf-685fe44dd74b.png)

**Comment by v-jiche** [comment]
Verified. Fixed.
azure-toolkit-for-intellij-2018.2.develop.832.10-29-2018
