### ISSUE TITLE
Eclipse Mars - Create VM Keeps Circling

### ISSUE THREAD

**Issue by selvasingh** [Microsoft/azure-tools-for-java#216]
Open Eclipse with Azure Toolkit for Eclipse
Sign in
Open Azure Explorer
Select Virtual Machines
Right click on Virtual Machines and select Create VM
You will see circling but no action

![image](https://cloud.githubusercontent.com/assets/3642444/24057464/ac7d23e2-0b04-11e7-8179-e4415e7b1bb1.png)

**Comment by selvasingh** [comment]
After this, you will be forced to restart Eclipse

**Comment by lenala** [comment]
Cannot repro, might be already fixed. Please verify.

**Comment by bsaby** [comment]
Cannot repro, using WindowsAzurePlugin4EJ.195.03-31-2017.zip.
