### ISSUE TITLE
[IntelliJ] Warning cluster not exist when there is

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2160]
Build: Private 2219

Repro Steps;
1. Launch one run config file, wait untill the cluster display
2. Click OK

Result:
Warning cluster does not exist, and cannot save config.
![image](https://user-images.githubusercontent.com/36756024/46708173-e0fb6800-cc2c-11e8-8a52-70460de751cc.png)

**Comment by wezhang** [comment]
The issue blocks the configuration to save

**Comment by jingyanjingyan** [comment]
Verify with private build 2230, fixed.
