### ISSUE TITLE
[IntelliJ] Warning message should not use capital inside

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2161]
Build: Private 2219

Repro Steps:
1. Launch one run config file
2. Use wrong storage account name and tab away

Result:
Warning message should not use Can't inside
![image](https://user-images.githubusercontent.com/36756024/46709038-4fdac000-cc31-11e8-8857-49cefafc073a.png)

![image](https://user-images.githubusercontent.com/36756024/46733021-ab7f6a80-cc7e-11e8-8012-8fa47cf3fe49.png)

**Comment by t-rufang** [comment]
Fixed in #2209

**Comment by v-jiche** [comment]
Verified. Fixed.
azure-toolkit-for-intellij-2018.2.develop.824.10-29-2018
