### ISSUE TITLE
[IntelliJ][RunConf] Tab away make the value works, suggest use more obvious method to check.

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#2163]
Build: Private 2219

Repro Steps:
1. Launch one run config file
2. Enter valid storage account
3. Enter valid key, and try to tab away to make the value works

Result:
Could not tab away from one test area field

Expect:
Tab away does not easy to work each time, suggest use another way to check the values.

**Comment by t-rufang** [comment]
@jingyanjingyan Hi Yan, what is the `storage account` you mentioned at step 2?

**Comment by jingyanjingyan** [comment]
@t-rufang "Use Azure Blob to upload", "Storage Account", "Storage Key", then tab when focus on "Storage Key"

**Comment by t-rufang** [comment]
@jingyanjingyan We have fixed this issue as an accessibility issue long time before, could you please help verify the fix?

**Comment by jingyanjingyan** [comment]
2019.3 build 0608 & 2020.1 build 0529
After entering storage key then tab, the focus will move to next field.
Close as Fixed.
