### ISSUE TITLE
[IntelliJ] Could not change container after restart intellij

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2166]
Build: Private 2219

Repro Steps:
1. Submit with this configuration
![image](https://user-images.githubusercontent.com/36756024/46711144-97b21500-cc3a-11e8-826f-462fdd79ccf5.png)

2. Fail. 
3. Restart IntelliJ
4. Launch the config file, try to change a container

Result：
Only the selected container is listed
![image](https://user-images.githubusercontent.com/36756024/46711220-e8297280-cc3a-11e8-9b86-b4bd425f6cf6.png)

Expect:
Allow user to select a container for the first time, should allow to edit container in the future.

**Comment by t-rufang** [comment]
Duplicate with #2151
