### ISSUE TITLE
[IntelliJ] Could not launch local console when no scala file is opening

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2168]
Build: Private 2219

Repro Steps;
1. Create a new maven project, do not open any scala script
2. Click "Tools\Spark Console\Run spark local console(scala)"
![image](https://user-images.githubusercontent.com/36756024/46711877-ced5f580-cc3d-11e8-98f1-88e492d7332d.png)

Result:
Could not launch local console. 
The same with spark livy interactive session console.

**Comment by wezhang** [comment]
Workaround is to open a Scala file.

**Comment by jingyanjingyan** [comment]
Fix with market build, local console does not depend on opening scala file anymore.
