### ISSUE TITLE
Create VM dialog doesn't validate the resource group name

### ISSUE THREAD

**Issue by reyang** [microsoft/azure-tools-for-java#217]
When I leave the resource group as empty while creating VM, it failed without promoting me for the missing fields - I ended up losing the information I filled in during previous steps.
The expectation is to prompt or give a red mark from the dialog.

![image](https://cloud.githubusercontent.com/assets/17327289/24057494/c233dc6c-0b04-11e7-8c51-91484b8f0b2c.png)

**Comment by martinsawicki** [comment]
good suggestion for the future.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738854
