### ISSUE TITLE
[IntelliJ]Fields not align well on the left when selecting "Azure Blob"

### ISSUE THREAD

**Issue by tankungx** [microsoft/azure-tools-for-java#2173]
Build: Private 783

Steps:
new a config, choose "Azure Blob", then check the UI of "Job Upload  Storage"

Results:
not align well on the left
"Storage key" has no border.
![image](https://user-images.githubusercontent.com/30617450/46725399-ab975e80-ccae-11e8-812f-5de1d3e3c285.png)

**Comment by t-rufang** [comment]
Not repro in the latest build. I suppose it's already fixed.
![image](https://user-images.githubusercontent.com/32627233/85122754-a9461f80-b259-11ea-9f4f-f110694c03a3.png)
