### ISSUE TITLE
[IntelliJ] Named hdinsight cluster and livy cluster with the same name, overwrite.

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2179]
Build: develop 788

Repro Steps:
1. Create a hdinsight cluster named "catest"
2. Link a livy cluster named "catest"

Result:
Only one "catest(linked)" shows under hdinsight node
![image](https://user-images.githubusercontent.com/36756024/46776661-25a20480-ccfc-11e8-819e-c7924065ab17.png)

**Comment by wezhang** [comment]
That's by design
