### ISSUE TITLE
Eclipse Neon - Automated sign-in shows error when no auth file is specified

### ISSUE THREAD

**Issue by joshuahinds** [Microsoft/azure-tools-for-java#218]
Minor issue - An error message appears if you do not select an auth file when setting up automated sign-in. This feels unnecessary since a new one will be created anyway if you pick the "New..." button. Would it be possible to just assume a new file should be created if no file is specified? Sign in is the next step either way so the flow wouldn't be any different.

![sign-in-09-auto-message-b](https://cloud.githubusercontent.com/assets/4510946/24057539/eca343f2-0b04-11e7-832c-b34c0db84997.PNG)

**Comment by vladimir-shcherbakov** [comment]
You can create the cred file with various tools (cli, powershell) or even get it from somebody. So "Automated" option doesn't imply to create a brand new cred file.
