### ISSUE TITLE
[IntelliJ] Missing spark console entry in tool menu when user does not install scala.

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2187]
Build: Develop 788

Repro Steps:
1. Install IntelliJ and do not install scala
2. Click "Tools" to check the menu items

Result:
No "Spark Console" item
![image](https://user-images.githubusercontent.com/36756024/46780001-eb3f6400-cd09-11e8-8482-1cdabf7a6b0b.png)

**Comment by wezhang** [comment]
We keep the same behavior with Scala plugin.
