### ISSUE TITLE
new virtual machine dialog left nav is strange

### ISSUE THREAD

**Issue by alvadb** [Microsoft/azure-tools-for-java#219]
The left navigation display in the create new virtual machine dialog is strange.  It appears to be a list box that is used to indicate the current step.  It is an odd look and feel.

**Comment by martinsawicki** [comment]
we can use the Wizard dialog template, and we don't need th navigation at all (see Eclipse's new Dynamic Web Project" as an example of such a wizard)

**Comment by martinsawicki** [comment]
we're removing this left nav panel -- inheritance from the IntelliJ plugin but it doesn't look right in Eclipse

**Comment by lenala** [comment]
Done, please verify.

**Comment by bsaby** [comment]
Test passed, using artifacts/WindowsAzurePlugin4EJ.150.zip.
