### ISSUE TITLE
The windows web app will not be displayed in the service list after swapping with specific type slots

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#2193]
Repro steps:
1. Deploy to a new windows web app
1. Create a slot with configuration source: Don't clone configuration from an existing slot in plugin or Portal
1. Swap the web app with this slot
1. Open Run on Web App dialog again and click refresh 

Result:
The web app will not be displayed in the service list after swapping.

In the screenshot below, there is no monajarwin1 in the app services list.
![image](https://user-images.githubusercontent.com/22470312/46789210-8702bb80-cd6e-11e8-9117-7e5e262d5d9d.png)

![image](https://user-images.githubusercontent.com/22470312/46789192-7b16f980-cd6e-11e8-8713-65f558f39a64.png)
And I try to swap again, the web app will reappear in the list

**Comment by SummerSun** [comment]
The slot is created with the brand new configuration so the Java version is off. In the web apps table, we filter out Java runtime web apps. That's why the web app disappear after swapping.

**Comment by EricZhangzf** [comment]
i haven't meet this issue on v3.37.0
