### ISSUE TITLE
[IntelliJ][Regression] Cluster not exist error when select cluster default storage in run configuration for spark on ADL

### ISSUE THREAD

**Issue by t-rufang** [Microsoft/azure-tools-for-java#2196]
Repro step:

1. New a `Azure Data Lake Spark Pool` run configuration and select a cluster
2. Select the `Job Upload Storage` type to `Use cluster default storage`
3. Error message shows as "Can't save the configuration since cluster not exist"

**Comment by t-rufang** [comment]
FIxed in #2197

**Comment by jingyanjingyan** [comment]
Fix in Develop 839
