### ISSUE TITLE
[IntelliJ] Job upload path display error

### ISSUE THREAD

**Issue by t-rufang** [Microsoft/azure-tools-for-java#2198]
Repro steps:

1. new an `Azure HDInsight Spark` run configuration
2. select an HDInsight cluster with ADLS storage, select storage type as `Job Upload Storage`
3. the upload path display as the format of `Azure Blob` while we expect it to be `ADLS` format

![image](https://user-images.githubusercontent.com/32627233/46800639-e8388800-cd8a-11e8-8fdc-4270a0b6aee3.png)

**Comment by t-rufang** [comment]
The upload path in run configuration dialog is just for show and it's not consistent with the real upload path when you submit the spark job for now  (we will fix this issue later). That means, though the upload path displays wrong in the run configuration dialog, you can still submit spark job and upload the artifact to the right place (cluster default storage account).

**Comment by t-rufang** [comment]
Fixed in #2245

**Comment by v-jiche** [comment]
Verified. Fixed.
azure-toolkit-for-intellij-2018.2.develop.824.10-29-2018
