### ISSUE TITLE
Eclipse - Sign in Option is Missing in Azure Explorer

### ISSUE THREAD

**Issue by selvasingh** [Microsoft/azure-tools-for-java#220]
Open Eclipse with Azure Toolkit for Eclipse
Open Azure Explorer
Right click on explorer and you will not see a sign-in option

![image](https://cloud.githubusercontent.com/assets/3642444/24057733/9df80674-0b05-11e7-9fc4-6b5d7f767550.png)

**Comment by lenala** [comment]
Fixed, please verify.

**Comment by bsaby** [comment]
Test passed in artifacts/WindowsAzurePlugin4EJ.95.zip.
