### ISSUE TITLE
[IntelliJ] Use kotlin DSL to define base UI class

### ISSUE THREAD

**Issue by t-rufang** [microsoft/azure-tools-for-java#2207]
Refer to comments in #2137 
 - Save class `Place` to an independent file
 - Put `init()` and UI related codes to base class  `SparkSubmissionJobUploadStorageBaseCard`

**Comment by wezhang** [comment]
@t-rufang you can make following changes. Thanks!

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748163
