### ISSUE TITLE
Deploy Web App dialog: buttons too small, uneven and missing dots

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#221]
![smallbuttons](https://cloud.githubusercontent.com/assets/881767/24057692/7629803c-0b05-11e7-991d-84ea2950cda3.png)

The buttons are 
- too small, they should be at least the same size as the Deploy and Cancel buttons at the bottom
- not even --- they should be the same size
- "Create.." is missing a dot (should be Create...)

**Comment by bsaby** [comment]
Test passed in artifacts/WindowsAzurePlugin4EJ.95.zip.
