### ISSUE TITLE
Replace OpenJDK with Azul in Dockerfile of Web App for Containers 

### ISSUE THREAD

**Issue by Matthew-Dong** [Microsoft/azure-tools-for-java#2219]

**Comment by Eskibear** [comment]
Change image name in the following lines to `azul/zulu-openjdk-alpine:8`:
https://github.com/Microsoft/azure-tools-for-java/blob/develop/PluginsAndFeatures/azure-toolkit-for-eclipse/com.microsoft.azuretools.container/src/main/java/com/microsoft/azuretools/container/Constant.java#L45

https://github.com/Microsoft/azure-tools-for-java/blob/develop/PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/intellij/runner/container/utils/Constant.java#L46

**Comment by Eskibear** [comment]
Also add this as a workitem in the Plan.

**Comment by Estefycp** [comment]
I did two pull request, one for each link
