### ISSUE TITLE
Eclipse - Select Image Version # box appears enabled when using Recommended  image. 

### ISSUE THREAD

**Issue by alvadb** [Microsoft/azure-tools-for-java#222]

**Comment by martinsawicki** [comment]
is there anything the code is not doing?  (gray out?)

**Comment by lenala** [comment]
It is disabled, Comboboxes in swt are greyed out when disabled but Lists are not. Please verify if it enabled.

**Comment by bsaby** [comment]
Test passed, using WindowsAzurePlugin4EJ.215.04-04-2017.zip.
Select Image Version # box is disabled when using Recommended image. 
![image](https://cloud.githubusercontent.com/assets/22470312/24692756/1a4a1d46-1a0d-11e7-95b4-2558ce96cf45.png)
