### ISSUE TITLE
Eclipse Neon - Duplicate entries for Azure Activity Log and Azure Explorer views

### ISSUE THREAD

**Issue by joshuahinds** [Microsoft/azure-tools-for-java#223]
Multiple items are listed within the show view dialog and clicking on them triggers an error in the error log. This may be the result of the plug-in being installed multiple times (I did not uninstall previous versions). However, I would still expect to only see one of each type. Is it important to allow multiple versions to be installed simultaneously? This seems confusing, but if so, perhaps they should be labeled with a version number or something. 

![show-view-dialog-02](https://cloud.githubusercontent.com/assets/4510946/24058057/e41677e8-0b06-11e7-9afb-f465e2053d8c.PNG)

![output-error-01](https://cloud.githubusercontent.com/assets/4510946/24058059/e7aef1aa-0b06-11e7-8195-81f2a3489050.PNG)

**Comment by joshuahinds** [comment]
Uninstalled all Microsoft plugins and then reinstalled to still find 2 entries for the Azure Activity Log.

![show-view-dialog-dupes](https://cloud.githubusercontent.com/assets/4510946/24060728/c0092796-0b11-11e7-8442-ea9d36a97afa.PNG)

**Comment by martinsawicki** [comment]
it;';s possible that not everything got uninstalled. But this may also be tricky to clean up thoroughly b/c of how Eclipse manages versions of plugins, and b/c we have changed a lot of the naming to make it specifi to Microsoft. A mitigating factor perhaps is the new button we will be putting on the Azure Toolbar which will take the user to the right Explorer..  We'll probably need to postpone trying to figure this one out.

**Comment by selvasingh** [comment]
@bsaby - please verify as fixed and close it

**Comment by selvasingh** [comment]
@bsaby - install the current released plugin. Then try installing the new one. You should see a clean error message asking you to uninstall the current released version. That should prevent illegal states described in this issue

**Comment by bsaby** [comment]
Test passed.

Install the currently released plug-in, and then install the new plug-in, restart Eclipse will prompt a clean error message asking you to uninstall the current release version .

![image](https://cloud.githubusercontent.com/assets/22470312/25160182/1aac1552-24e7-11e7-8b8e-fddbbad3b085.png)
