### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by Hombr33** [microsoft/azure-tools-for-java#2238]
IntelliJ build version: 2018.2.5 IC-182.4892.20
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.13.0-2018.2

#### 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).
10 
#### 2. What did you like or dislike about Azure Toolkit for IntelliJ?
I like that it is extremely easy to use. I dislike the lack of verbosity (sometimes it hangs on Uploading artifact...)
#### 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?
Verbosity messages

**Comment by wezhang** [comment]
Thanks @Hombr33 ! May I get the operation to upload artifact?

**Comment by t-rufang** [comment]
Thank you for your feedback, we will refine the user experience for artifact upload.
