### ISSUE TITLE
Create new Virtual Machine -> Associated resources  -> Create new resource group

### ISSUE THREAD

**Issue by alvadb** [microsoft/azure-tools-for-java#224]
Creating new resource group with new storage account.  The issue is that the Create Storage Account dialog is not able to be associated with the new Storage account.  This is due to the fact that the Create Storage account dialog requires a name for a new resource group or allows me to select from an existing resource group.

**Comment by martinsawicki** [comment]
an interesting limitation we should look at in the future

**Comment by wangmingliang-ms** [comment]
please use the latest version
