### ISSUE TITLE
[intelliJ][Aris cluster]Two adjacent create link cluster should not affect each other

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#2243]
Build: 2331
Repro steps:
1.Link a cluster with password and then submit successfully
2. Then link a cluster without password successfully and submit failed
3. Then link a cluster  without password 
![image](https://user-images.githubusercontent.com/43333874/47288345-91ad2400-d5aa-11e8-84ad-56860713dec6.png)

Result:
Created failed with 401 error prompt
 Expected result:
Two adjacent create link cluster should not affect each other

**Comment by t-rufang** [comment]
@v-xiaocw Does this issue repro?

**Comment by v-xiaocw** [comment]
@t-rufang The livy server is down, could not verify the bug

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748162
