### ISSUE TITLE
Received error when for using upper case names when specficying resource group name

### ISSUE THREAD

**Issue by alvadb** [microsoft/azure-tools-for-java#225]
The control shouldn't allow upper case values and should bound the users input to the max character limit allowed for the resource group name.

**Comment by martinsawicki** [comment]
good suggestion, maybe in the future we can do more pre-validation

**Comment by andxu** [comment]
![image](https://user-images.githubusercontent.com/17075863/84391773-ff98da00-ac2b-11ea-99c1-14558d2dd167.png)
I think upper case characters are valid for resource group.

**Comment by andxu** [comment]
![image](https://user-images.githubusercontent.com/17075863/144178566-44b3b813-1ce6-49e4-8010-1f3798a5850e.png)
