### ISSUE TITLE
[IntelliJ][Aris cluster]Could not open the Master UI link

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2254]
Build: https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_PR/2331

Repro Steps:
1. Link an Aris cluster
Livy endpoint | https://40.121.133.199:30443/gateway/default/livy/v1
Yarn endpoint | https://40.121.133.199:30443/gateway/default/yarn

2. Submit, click the Master UI link in output

Result:
Could not launch the master UI
http://mssql-master-pool-0.service-master-pool:8088/proxy/application_1539998170284_0138/

**Comment by wezhang** [comment]
FYI:

```
        submissionState.setConsoleView(jobOutputView.getSecondaryConsoleView());
        submissionState.getConsoleView().addMessageFilter((line, entireLength) -> {
            //...
            String urlInLine = line.substring(3, 7);
            String mappedUrl = remoteProcess.getSparkJob().getCluster().mapInternalUrlToPublic(urlInLine);
            // Result = 
        });
        submissionState.setRemoteProcessCtrlLogHandler(processHandler);

```

**Comment by v-jiche** [comment]
Bug fixed on windows.
Bug repros on Linux:
Build:
azure-toolkit-for-intellij-2018.3.develop.943.12-29-2018

Repro Steps:
1. Link an Aris Cluster
  host:   10.91.134.112
  user name:    root
  password:   Yukon900
2.  Submit, click the Master UI link in output

Result:
Could not launch the master UI:
http://mssql-master-pool-0.service-master-pool:8088/proxy/application_1545336386529_0089/

**Comment by jingyanjingyan** [comment]
Verify with develop 943, it will open url like https://10.91.134.112:30443/gateway/default/yarn/
