### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by piotrpo** [Microsoft/azure-tools-for-java#2256]
IntelliJ build version: 2018.1.3 IU-181.4892.42
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.11.0-2018.1

#### 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).
1
#### 2. What did you like or dislike about Azure Toolkit for IntelliJ?
Asking me for filling this stupid survey
#### 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?

Stop this pitty attempts to attract attention

**Comment by wezhang** [comment]
Thanks @piotrpo ! It's fixed.
