### ISSUE TITLE
Create Storage Account dialog account name error message

### ISSUE THREAD

**Issue by alvadb** [Microsoft/azure-tools-for-java#226]
The error message is formatted incorrectly.  Line break happens in the middle of the dialog.

**Comment by martinsawicki** [comment]
![error](https://cloud.githubusercontent.com/assets/881767/24126091/4cbb65ae-0d89-11e7-9098-921885c14ad6.png)

**Comment by lenala** [comment]
This is fixed, please verify.

**Comment by bsaby** [comment]
Test passed in artifacts/WindowsAzurePlugin4EJ.120.zip.
![image](https://cloud.githubusercontent.com/assets/22470312/24183872/de2757c8-0f05-11e7-99f6-ca02d3a029f4.png)
