### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by manojg1981** [Microsoft/azure-tools-for-java#2264]
IntelliJ build version: 2018.2.5 IC-182.4892.20
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.13.0-2018.2

The Azure login does not show the required pop-up to sign-in using company credential. I have tried multiple times installing. Can you help

**Comment by Eskibear** [comment]
Thanks for the feedback. It's a known issue, please follow https://github.com/Microsoft/azure-tools-for-java/issues/1877 , we are planning to introduce a new way to help you sign in.
