### ISSUE TITLE
Intellij Idea Azure plugin broken, won't sign in, gets the application stuck

### ISSUE THREAD

**Issue by polarapfel** [microsoft/azure-tools-for-java#2265]
The Azure Intellij Idea plugin seems to be broken.

It will not sign into Azure. When choosing either sign-in method, the sign-in proceeds results in an endless loop, with no ability to cancel the dialog.

It's stuck here: https://developercommunity.visualstudio.com/storage/attachments/45350-annotation.png

I tried on the latest Idea release (full version) on two Windows machines and a Ubuntu 18.04 setup.

This should be a P0 issue. Please let me know what you need from me to help get to the root cause.

thanks,

Tobias Weisserth

**Comment by Eskibear** [comment]
It should pop up a new dialog to let you sign in. Sometimes we notice the dialog does pop up, but it's in the back and is blocked by the main dialog, so you might not see it. I'm not sure if it's your case, can you please have a check? IntelliJ IDEA's API and its UI behavior change very often, do you mean **2018.2 ultimate** by `latest Idea release`.

**Comment by polarapfel** [comment]
Hey,

I am running Idea Ultimate, release 2018.2.5. There is no dialog popping up, neither in the foreground, or background.

If there was a dialog in the background, that's part of Idea's windows, I couldn't switch to it anyway, as the Sign In Progress window locks the focus. There isn't even a way to cancel or close it to get back to Idea. I need to kill Idea from the task manager or process list and restart it, to get back to my workspace (and that ought to be filed as a bug as well I guess).

Please let me know how I can help you debug this. I am eager to get this resolved, as I've been looking forward to having Azure integration in Idea.

thanks,

Tobias Weisserth

**Comment by Eskibear** [comment]
@polarapfel 2018.2.5 was released after we released the plugin, that's how the regression comes. We are fixing it. 

And if you want to try this plugin now, as previous versions were covered in our test, you can use a previous version of the IDEA (e.g. [IntelliJ IDEA 2018.2.3](https://download.jetbrains.com/idea/ideaIU-2018.2.3.exe) )

**Comment by Eskibear** [comment]
It also occurs in 2018.3, see #2279

**Comment by polarapfel** [comment]
Fixed in latest release. Just tested and works. I'll re-test on my other setups and will let you know if there is still an issue. Thanks!

**Comment by Flanker32** [comment]
Close as the issue has been fixed
