### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by Fuzzi1974** [microsoft/azure-tools-for-java#2269]
IntelliJ build version: 2018.2.2 IU-182.4129.33
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.10.0-2018.2

#### 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).
9

#### 2. What did you like or dislike about Azure Toolkit for IntelliJ?
Very easy to use! Good job!

#### 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?
At the moment I have nothing to improve, It works very well for me and the projects needs!

**Comment by jingyanjingyan** [comment]
Thank you for the feedback ~
