### ISSUE TITLE
[IntelliJ] Still prompt No scala not installed even if have installed one time on 2018.3 on Mac.

### ISSUE THREAD

**Issue by tankungx** [Microsoft/azure-tools-for-java#2277]
Build: Private 824
Repro Steps:
1. Install 2018.3(183.3795.13)
2. Install the private bits, No scala installed before.
3.Create a Azure Spark project.

Result:
After installing the scala, still prompt "No scala plugin found. Do you want to install Scala plugin?" again.

Expected:
just prompt one time.

**Comment by wezhang** [comment]
IntelliJ IDEA platform issue.
