### ISSUE TITLE
[IntelliJ] Long prompt info at the bottom line is hard to browse on configuration dialog.

### ISSUE THREAD

**Issue by tankungx** [Microsoft/azure-tools-for-java#2278]
Build: Private 824
Repro Steps:
1. new an Azure HDInsight Spark run configuration(without login) and check the prompt info at the bottom line.

Result:
when the info is too long, we should adjust the window size to browse the whole text.

Expected:
when mouse hover on it, the tooltip should be prompted.
![image](https://user-images.githubusercontent.com/30617450/47637006-48099e00-db95-11e8-82b2-a5c9d70fc5bf.png)

**Comment by wezhang** [comment]
That's IntelliJ run configuration dialog limitation.
