### ISSUE TITLE
[IntelliJ] Cannot sign in successfully on 2018.3

### ISSUE THREAD

**Issue by tankungx** [Microsoft/azure-tools-for-java#2279]
Build: Private 824
Repro Steps:
1. Try to sign in with interactive mode on 2018.3
2. Or select Automated, click New...

Actual:
Cannot sign in. The sign in progress dialog is showing all the time.
If sign in with authenticate file ever, Can sign in with interactive mode successfully. Need more investigation.

Expected:
Can sign in successfully.

![image](https://user-images.githubusercontent.com/30617450/47638200-daf80780-db98-11e8-865f-6e9c239c2f0f.png)

**Comment by wezhang** [comment]
dup #2265
