### ISSUE TITLE
Eclipse Neon - Azure Explorer - the manage subscriptions toolbar button and menu item do nothing when not signed in

### ISSUE THREAD

**Issue by joshuahinds** [Microsoft/azure-tools-for-java#228]
In the Azure Explorer view, the commands for managing subscriptions should probably be disabled when not signed in. Currently, these controls are enabled but do nothing.

![manage-subscriptions](https://cloud.githubusercontent.com/assets/4510946/24058349/0fe100e0-0b08-11e7-9579-79d9b4084c98.PNG)

These controls should be disabled just like the menu item in Tools menu:
![manage-subscriptions-02](https://cloud.githubusercontent.com/assets/4510946/24058354/135ed2d8-0b08-11e7-996e-2a3fc8fcca67.PNG)

**Comment by lenala** [comment]
duplicate to #255
