### ISSUE TITLE
[IntelliJ] Run remotely failed without setting the congfig file for remote run

### ISSUE THREAD

**Issue by v-xiaocw** [Microsoft/azure-tools-for-java#2280]
Build: Develop 824
Repro Steps:
1.Create a new project 
2.Click the Remote Run button directly
3.Open the config file and close the dialog box directly after loading the cluster name
4.Click the Remote Run button again
Result:
The commit was not run  after the second step and fourth step
Expected results:
1.After step 2 there should be a warning of the following figure:
![image](https://user-images.githubusercontent.com/43333874/47638171-0b995c00-db1b-11e8-956f-b386fa9310c9.png)
2.Remote run should run normally after step 4

**Comment by wezhang** [comment]
Try build number > 831 please.

**Comment by v-xiaocw** [comment]
Fix with develop 832, Remote Run Configuration window automatically pops up when you click the Remote Run button
