### ISSUE TITLE
[IntelliJ]Can't find AU warning label when user provision a new Spark on ADL cluster.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#2283]
Build:
azure-toolkit-for-intellij-2018.2.develop.824.10-29-2018

Repro Steps:
1. Open **Provision Spark Cluster**.
2. Change the **Number of Containers**  until  required AU is greater than available AU.
3. Then tab it.

Result:
Can't find AU warning label.

![image](https://user-images.githubusercontent.com/35950097/47650781-41dae800-dbbc-11e8-919a-52837502fecc.png)

**Comment by t-rufang** [comment]
![image](https://user-images.githubusercontent.com/32627233/51176757-b50d1400-18f8-11e9-965d-c964a3ea0d83.png)
