### ISSUE TITLE
Eclipse complain about job not canceled during IDE shutdown

### ISSUE THREAD

**Issue by reyang** [microsoft/azure-tools-for-java#229]
1. create VM
2. after the VM creation job shows progress, close the IDE
3. start the IDE again, from the error window we can see a warning:

null
org.eclipse.core.jobs
Warning
Fri Mar 17 11:31:43 PDT 2017
Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: com.microsoft.azuretools.core.azureexplorer.helpers.IDEHelperImpl$1

**Comment by martinsawicki** [comment]
may be a good fix in the future, but would require a more in-depth investigation

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738853
