### ISSUE TITLE
[IntelliJ] Intellisense not work well fully in local console

### ISSUE THREAD

**Issue by tankungx** [Microsoft/azure-tools-for-java#2290]
Refer to bug 2285(Not repro on mac 2018.2)

Build: Develop 832
Repro Steps:
Create a new project
Launch local console and click auto fix when prompt

Result:
Launch local console but get errors. And enter sc.a, No keyword appear(should appear ap...)
![image](https://user-images.githubusercontent.com/30617450/47700170-80ba7d80-dc50-11e8-8352-5088e0b12f46.png)

**Comment by wezhang** [comment]
try Backspace and enter again

**Comment by tankungx** [comment]
try Backspace and enter again, it works well.
