### ISSUE TITLE
[IntelliJ]words are overlapped on config file.

### ISSUE THREAD

**Issue by tankungx** [Microsoft/azure-tools-for-java#2292]
Build: Develop 832
Repro Steps:
1.Create a new project and not set up a config file.
2.Launch Interactive console directly.

Results:

Will create a config file automatically. But the words overlap other words.

![image](https://user-images.githubusercontent.com/30617450/47700659-405bff00-dc52-11e8-9699-f0f360ee2e6a.png)

**Comment by wezhang** [comment]
Thanks! An IntelliJ limitation.
