### ISSUE TITLE
[IntelliJ]No prompt when trying to launch local console by "Tools->Spark Console->Run Spark Local Console(Scala)"

### ISSUE THREAD

**Issue by tankungx** [microsoft/azure-tools-for-java#2297]
Build: Develop 832 .  v3.14.0
Repro Steps:
1. Create a new project and not set up config file. Do not locate to a file or open any script file.
2. Click Tools->Spark Console->Run Spark Local Console(Scala).

Results:
Nothing happened. No prompt appeared.

**Comment by wezhang** [comment]
@jingyanjingyan and me can not repro that

**Comment by v-jiche** [comment]
It might be the same with bug #2168 .

**Comment by t-rufang** [comment]
Close this bug since it's not repro now.
