### ISSUE TITLE
[IntelliJ][SparkonCosmos] Provision cluster fails with max memory

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#2298]
Build: Develop 823

Repro Steps:
1. Provision a cluster with max memory 48, click OK

Result:
Fail to provision cluster.
![image](https://user-images.githubusercontent.com/36756024/47702755-d6bdff80-dc15-11e8-8870-381c8f5c753d.png)

**Comment by t-rufang** [comment]
Error message change:
![image](https://user-images.githubusercontent.com/32627233/51176969-48dee000-18f9-11e9-9959-89815a13b5a4.png)

We need to confirm the range of each item with  backend team.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748161
