### ISSUE TITLE
[IntelliJ][Spark on ADL] Artifact from local disk could not list all classes

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2302]
Build: Develop 823

Repro Steps:
1. Create a sample project, submit once to generate the artifact file, copy to local disk like D:\
2. Launch a run config dialog, select "Artifact from local disk", choose the artifact in step1
3. Click browse button of main class

Result:
Not all classes listed
![image](https://user-images.githubusercontent.com/36756024/47705882-b430e400-dc1f-11e8-885e-5fe018b27c22.png)

**Comment by wezhang** [comment]
dup #2072
