### ISSUE TITLE
[IntelliJ] "SparkJobRun" on the context menu not work when no configuration file

### ISSUE THREAD

**Issue by tankungx** [Microsoft/azure-tools-for-java#2303]
Build: Develop 832
Repro Steps:
1. Create a new project and not set up config file.
2.Locate to a java or scala file ,right click the context menu, then click "SparkJobRun"

Results:
No action.

![image](https://user-images.githubusercontent.com/30617450/47706750-047e6500-dc65-11e8-9d25-e7dac1fe119b.png)

**Comment by wezhang** [comment]
To be fixed with #2287

**Comment by jingyanjingyan** [comment]
Fix with develop 844, the SparkJobRun is disabled.
