### ISSUE TITLE
[intelliJ]Switch Container in refreshing statue, then could apply the invalid storage account value.

### ISSUE THREAD

**Issue by v-jiche** [Microsoft/azure-tools-for-java#2307]
Build:
azure-toolkit-for-intellij-2018.2.develop.832.10-29-2018

Repro Steps:
1. Launch one run config file
2. Enter valid storage account and key
3. Rename storage account
4. Change storage container, then click apply

Result:
The invalid storage account name is accepted. Wait for a long time, the warning message may display, but the config is accepted anyway.
![image](https://user-images.githubusercontent.com/35950097/47712679-4b735700-dc73-11e8-9caf-3f52095e4106.png)

**Comment by wezhang** [comment]
Nice to have in v3.14

**Comment by v-jiche** [comment]
1.  Change the storage account only and wait a long time patiently. The correct warning would display and validation would not pass.

2. Change the storage account then change the storage container, apply is accepted.

**Comment by v-jiche** [comment]
Verified. Fixed.
Build: azure-toolkit-for-intellij-2018.3.develop.953.01-02-2019

When edit storage account, the storage container will be re-refreshed.
