### ISSUE TITLE
[Publish as Docker Container]The .jar file should be added automatically if the file exists

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#2309]
IDE: IntelliJ Ultimate 2018.2/2018.3

Steps:
1. Open a spring boot project with .JAR file
1. Right-click the project  -> Azure ->Publish as Docker Container

Result:
![image](https://user-images.githubusercontent.com/22470312/47712036-aad06780-dc71-11e8-82be-c4964835fba2.png)

Expectation(like web project)：
![image](https://user-images.githubusercontent.com/22470312/47713328-00f2da00-dc75-11e8-8140-5043edc30c36.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738773

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
