### ISSUE TITLE
Eclipse Mars - Storage Accounts are Not Refreshing in Azure Explorer

### ISSUE THREAD

**Issue by selvasingh** [Microsoft/azure-tools-for-java#231]
Open Eclipse with Azure Toolkit for Eclipse
Sign in
Click on Azure Explorer
Click on Storage Accounts ... it will be refreshing forever

![image](https://cloud.githubusercontent.com/assets/3642444/24058632/103a730e-0b09-11e7-8c7f-8edb1d21eab7.png)

**Comment by lenala** [comment]
Fixed, please verify.

**Comment by bsaby** [comment]
Test used artifacts/WindowsAzurePlugin4EJ.141.zip.
The above issues also occur after creating a storage account.
![image](https://cloud.githubusercontent.com/assets/22470312/24338877/224eea0a-12db-11e7-9aeb-483a3f837dff.png)

**Comment by lenala** [comment]
Should be fixed now. Please note: storage account creation was changes from synchronous action to asynchronous, to be similar to vm creation.

**Comment by bsaby** [comment]
Test passed, using artifacts/WindowsAzurePlugin4EJ.150.zip.
