### ISSUE TITLE
[IntelliJ]After the correct warning interval of half a minute directly click Apply, the pop-up warning is not currently displayed but returns to the previous

### ISSUE THREAD

**Issue by v-xiaocw** [Microsoft/azure-tools-for-java#2311]
Build:
azure-toolkit-for-intellij-2018.2.develop.832.10-29-2018
Repro Steps:
1.Launch one run config file
2.Enter valid storage account and key
3.Rename storage account
4.Wait for two minutes to the warning display
5.Wait half a minute after displaying the check password in the warning state and click Apply
Result:
The pop-up warning is not currently displayed but returns to the previous
![image](https://user-images.githubusercontent.com/43333874/47715306-a322ab80-dbfc-11e8-947f-edbaba234e27.png)

**Comment by jingyanjingyan** [comment]
Related to the last focus.
Last focus on storage account/key, then apply will trigger refreshing, otherwise, the warning pops correctly.
