### ISSUE TITLE
[IntelliJ]Fail to submit job with ADLS gen 1 when sign in with authenticate file

### ISSUE THREAD

**Issue by tankungx** [microsoft/azure-tools-for-java#2320]
IntelliJ build version: 2018.3 OS: Windows 10
Build: https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_PR/2438/Azure/

Steps:
1. Not sign in first, then open configuration dialog
2. Choose ADLS Gen1 and sign in with automative mode with authenticate file.
 Sign in successfully.
3. Select one cluster and main class and then submit.

Results:
Fail to submit the job. Prompt "Unknown user"
![image](https://user-images.githubusercontent.com/30617450/47762741-d77b9200-dcf8-11e8-8e0f-50aa0f7e2ed2.png)

![image](https://user-images.githubusercontent.com/30617450/47762725-c599ef00-dcf8-11e8-9a24-fa6e117425b0.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748160
