### ISSUE TITLE
There is a warning in the web project Dockerfile generated by the plugin

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#2321]
IDEA: IU183.3975.18

Right-click a web project -> Azure -> Add Docker Support
![image](https://user-images.githubusercontent.com/22470312/47762973-9afc6600-dcf9-11e8-811e-14cb0b04fb04.png)

This issue cannot be reproduced in IntelliJ Ultimate 2018.2.x

**Comment by EricZhangzf** [comment]
I can not repro this issue on 3.37.0
