### ISSUE TITLE
[IntelliJ]Configuration dialog should not pop up when the settings are correct.

### ISSUE THREAD

**Issue by v-xiaocw** [Microsoft/azure-tools-for-java#2326]
Build: azure-toolkit-for-intellij-2018.2.develop.daily.558.10-30-2018
Repro steps:
1.Create a new project and right click on the script 
2.Click local run button on the content menu
3.Click remote run button directly and configuration dialog pops up, close it
4.Click  local debug button or local run button and the configuration dialog pops up, close it
5. Click remote run button directly and configuration dialog pops up ,click Apply and close the dialog
6.Click  local debug button or local run button again and the configuration dialog pops up still
Result;
![image](https://user-images.githubusercontent.com/43333874/47783365-be0a2400-dcbf-11e8-9e51-48f7ef9dfcd5.png)
Expection:
The two dialogs won't pop up

**Comment by jingyanjingyan** [comment]
Fix with develop 869, when click on local run or local debug icon with correct configs, the config dialog will not pops
