### ISSUE TITLE
Resource group not showing up in Create new Virtual Machine drop down

### ISSUE THREAD

**Issue by alvadb** [Microsoft/azure-tools-for-java#233]
I created a new resource group when I created a new storage account from the Create Storage Account dialog.  The new resource group wasn't available in the drop down until I refreshed the top node in the Azure explorer.

**Comment by lenala** [comment]
Looks like UI on the portal was refactored, there is no resource group field on create storage account form anymore when creating vm. Should we refactor our UI the same way?
![image](https://cloud.githubusercontent.com/assets/6208231/24415787/7ec019e6-1397-11e7-9f9e-20acf410d0fc.png)

**Comment by lenala** [comment]
Fixed, please verify. Note: this is duplicate to #298, but for both IntelliJ and Eclipse.

**Comment by davidliangze** [comment]
Build used in Eclipse:WindowsAzurePlugin4EJ.307.04-16-2017
Build used in IntelliJ: azure-toolkit-for-intellij.2017.303.04-16-2017

Test passed in Create New Storage Account dialog.
