### ISSUE TITLE
[IntelliJ][Windows][local][Spark] Set WINUTLS.exe location dialog need cancel twice to dismiss

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#2330]
Build: Develop 852

Repro Steps:
1. Open a config file, click "Locally Run"
2. Click "Browse" of "WINUTLS.exe location"
3. Click Cancel

Result:
The same dialog pops again
![image](https://user-images.githubusercontent.com/36756024/47834322-1b929380-ddda-11e8-8139-fb63ce5703ad.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748159
