### ISSUE TITLE
[IntelliJ] Open local console get error with SBT project: Command line is to long.

### ISSUE THREAD

**Issue by v-xiaocw** [Microsoft/azure-tools-for-java#2336]
Build：
azure-toolkit-for-intellij-2018.2.develop.854.11-01-2018

Repro steps:
1.  Create a new SBT project.
2.  Choose the spark version as 2.2 or 2.3,.
3.  Local console the LogQuery.
4.  Double click auto fix installation tips.
5.  A running error pops up.
6.  Click **ENABLE**  on the error message box .Then the local console will run successfully.

Result:
It will get an error message,. But if I click **enable** , the local console would pass.

Error running 'Spark Local Console(Scala) >> Spark Local Console(Scala)'
				Command line is too long. In order to reduce its length classpath file can be used.
				Would you like to enable classpath file mode for all run configurations of your project?
				Enable

![image](https://user-images.githubusercontent.com/43333874/47903019-57604400-de40-11e8-8313-070244919ccd.png)

**Comment by v-jiche** [comment]
It does not repro on spark 2.1.

**Comment by wezhang** [comment]
@v-xiaocw , could you try to click the `Enable` button of the error message hint?

**Comment by v-xiaocw** [comment]
Click ENABLE on the error message box .Then the local console will run successfully.

**Comment by wezhang** [comment]
Thanks! The user can follow IntelliJ's instruction to solve the issue.

**Comment by v-xiaocw** [comment]
Build: azure-toolkit-for-intellij-183.4284.118.develop.880.11-29-2018
Repro steps:
The first six steps are the same as above.
7.Click local console on the LogQuery again.
Result:
After six steps, it will get an error message. And if I click ENABLE , the local console would not luanch.
After the seventh step,it will be launched but without any tips.
It must be started the second time to run the local console properly.

**Comment by wezhang** [comment]
@v-xiaocw , is it still repro?

**Comment by jingyanjingyan** [comment]
It is repro with market build

**Comment by wezhang** [comment]
The workaround is to click `Enable` and start local console from the menu again.
