### ISSUE TITLE
Deploy Web App text tweaks

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#235]
- What currently says "*Please select App Service to deploy to*" should say "*Select App Service to deploy to.*"
  - generally "please" is not used in user prompts
  - need "." at end of sentence

**Comment by vladimir-shcherbakov** [comment]
steps to reproduce:
1) open web app deploy dialog;
2) do not select any app service row in the table and click deploy deploy button;
3) Check error message;

**Comment by bsaby** [comment]
Test passed in artifacts/WindowsAzurePlugin4EJ.95.zip.
