### ISSUE TITLE
[IntelliJ][Spark on ADL] Saved config does not show in Edit config toolbar for the first time

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#2352]
Build: PR 2478

Repro Steps:
1. From a cluster context menu, click "Submit Job"
2. Click "Apply" to save the config file

Result:
Could not select the config file from "Edit configuration" toolbar.
![image](https://user-images.githubusercontent.com/36756024/48467491-f130d500-e7e0-11e8-8034-221741e94617.png)

**Comment by jingyanjingyan** [comment]
Repro with develop 959 and market build

**Comment by wezhang** [comment]
@jingyanjingyan , is it still repro?

**Comment by jingyanjingyan** [comment]
The bug is still repro with azure-toolkit-for-intellij-2019.3.develop.12310945.06-08-2020.zip

**Comment by wezhang** [comment]
The issue depends on IntelliJ APIs.
