### ISSUE TITLE
[IntelliJ][Resource pool] Submit multiple command, format in output is different for local/livy console

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2357]
Build: Dev 860

Repro Steps:
1. Submit multiple command in local console
2. Submit multiple command in livy interactive console

Result:
Output format is different 
![image](https://user-images.githubusercontent.com/36756024/48687032-2bbab900-ebb7-11e8-9a8b-5563f8dbc883.png)

**Comment by wezhang** [comment]
Dup #2358
