### ISSUE TITLE
[IntelliJ]Submit multiple commands to HDInsight livy interactive console does not get result correctly

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2358]
Build: Develop 860

Repro Steps:
1. Submit multiple commands to Spark on cosmos livy interactive console
2. Submit multiple commands to HDInsight livy interactive console

Result:
HDInsight livy interactive console does not list all results correctly.
![image](https://user-images.githubusercontent.com/36756024/48688628-ec906600-ebbe-11e8-8505-819e27704e2f.png)

**Comment by wezhang** [comment]
@konjac , did you add some special codes for SparkCosmos interactive console?

**Comment by konjac** [comment]
There is no such change. I also repro these result on Notebook. It looks like a difference for livy on Cosmos and HDI.

**Comment by wezhang** [comment]
@jingyanjingyan , what's the Spark version of HDInsight cluster? 2.1 or 2.3?

**Comment by jingyanjingyan** [comment]
spark22blobhdi, spark23hdinsight get the error above.

zhwe-spk21
![image](https://user-images.githubusercontent.com/36756024/48816578-934d4180-ed3a-11e8-802c-ee9916388fa3.png)

zhwe-spk20
![image](https://user-images.githubusercontent.com/36756024/48816643-e921e980-ed3a-11e8-80fd-45d51368bfbc.png)

spark23hdinsighthdi4 works
![image](https://user-images.githubusercontent.com/36756024/48816763-59c90600-ed3b-11e8-8999-8130c0dcef46.png)

**Comment by wezhang** [comment]
It's backend response difference.
