### ISSUE TITLE
[Eclipse] UI issue: Refreshing text is truncated in azure explorer

### ISSUE THREAD

**Issue by jianghaolu** [microsoft/azure-tools-for-java#236]
<img width="313" alt="screen shot 2017-03-17 at 12 13 23 pm" src="https://cloud.githubusercontent.com/assets/2320445/24059176/406ecb18-0b0b-11e7-99b7-1e090f207a1f.png">

**Comment by Flanker32** [comment]
This issue has been fixed in the latest release.
