### ISSUE TITLE
[IntelliJ]names of running interactive console are the same.

### ISSUE THREAD

**Issue by tankungx** [microsoft/azure-tools-for-java#2360]
Build: Dev 860
Repro Steps:
1.Launch several interactive consoles based on different clusters.
2.Check the name on right top corner.

Results:
the names are the same.

<img width="525" alt="screen shot 2018-11-19 at 3 24 47 pm" src="https://user-images.githubusercontent.com/30617450/48692158-00b08380-ec10-11e8-8e65-1364b3b992a8.png">

Expected:
shall we add some info to identify the running interactive console?

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748157
