### ISSUE TITLE
[IntelliJ][Spark][remote][debug][LinkCluster]SSH authentication is always failed when linking a livy cluster.

### ISSUE THREAD

**Issue by tankungx** [microsoft/azure-tools-for-java#2362]
Build: Dev 860
Repro Steps:
1.Link a livy cluster successfully.
2.Enter password in Advanced Configuration(Remote Debugging)

Results:

SSH authentication is failed always. But actually it is passed through signing in mode using the same password.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748156
