### ISSUE TITLE
[IntelliJ]When running Livy console, an error occurs after two lines of commands are committed at the same time

### ISSUE THREAD

**Issue by v-xiaocw** [Microsoft/azure-tools-for-java#2363]
Build: Develop 860

Repro Steps:
1.Submit sc + Enter + .appname() + CtrlEnter  to HDInsight livy interactive console
2.Submit sc + Enter + .appname() + CtrlEnter  to Spark on cosmos livy interactive console
Result:
An error occurred
![image](https://user-images.githubusercontent.com/43333874/48702303-716e8600-eba5-11e8-9927-e29c6bfd0806.png)

**Comment by wezhang** [comment]
A known issue of Scala plugin. The workaround is using `()` to brace the commands, such as:

```
Spark> (sc
.appName)
```
