### ISSUE TITLE
[IntelliJ][Linux][AzureExplorer]Clusters can not be fully  listed

### ISSUE THREAD

**Issue by v-jiche** [Microsoft/azure-tools-for-java#2372]
Build:
artifacts/azure-toolkit-for-intellij-183.3795.13.develop.860.11-16-2018.zip
**Linux intelliJ3**

Repro steps:
1. Open Azure Explorer and sign in Azure.
2. Expand the cluster list from Azure/HDInsight.
3. Drag the scroll bar **up**, there is a blank.
4. Drag the scroll bar **down**, the blank disappears and the clusters are listed.

![image](https://user-images.githubusercontent.com/35950097/48762981-35dbd500-ece7-11e8-8a09-8542c4e10723.png)
![image](https://user-images.githubusercontent.com/35950097/48763082-66237380-ece7-11e8-9fc5-bbb1b1852835.png)

**Comment by wezhang** [comment]
@v-jiche , did you test it on Linux VM?

**Comment by v-jiche** [comment]
@wezhang  Yes, it is found on Linux.
Now I find it on windows.
Build: azure-toolkit-for-intellij-183.4284.118.develop.900.12-12-2018
![image](https://user-images.githubusercontent.com/35950097/49846086-846f2180-fe04-11e8-9cbb-c4dfb10efb83.png)

**Comment by v-jiche** [comment]
Not reproduce.
Build: market
