### ISSUE TITLE
[Mac]Deploy to Windows/Linux web app, encounter some errors

### ISSUE THREAD

**Issue by sallyur** [microsoft/azure-tools-for-java#2373]
It is not stable repro, but the frequency of occurrence ig high.

Build: 864

Repro steps:

1. Right-click a web project-> Azure -> Run on Web App
2. Deploy to a new Linux wildfly runtime Web App

Result:
Sometimes it will report error
![image](https://user-images.githubusercontent.com/28860891/48767408-a5ef5880-ecf1-11e8-972a-46cb8dddceb5.png)
![image](https://user-images.githubusercontent.com/28860891/48767414-ab4ca300-ecf1-11e8-8e47-6f1db7f9e612.png)
![image](https://user-images.githubusercontent.com/28860891/48767432-b43d7480-ecf1-11e8-9d04-424f34bb82db.png)

**Comment by SummerSun** [comment]
@sallyur For the second error screenshot, which login method did you use?

The other two problems are instability issues of the service. Let's verify them again after the service fixes it.

**Comment by sallyur** [comment]
For the second error screenshot, I used the interactive login method and want to deploy jar project using wildfly runtime.

**Comment by sallyur** [comment]
Build: 3.15.0 pre-release
The issue also repro when deploy a jar project to windows or to Linux JAVA 8-jre8 runtime.
It is always repro on mac today, no one deploy is successfully, but not repro on windows or Linix.  
I tested using market place version, it works fine.

**Comment by bsaby** [comment]
OS: Mac
Today, we no longer encounter IOException errors when testing, but we still get errors when we deploy to the web app.

**Global scenarios:** 
1. Deploy .war to Windows web app: deploy once, successfully
1. Deploy .war to Windows Linux: deploy twice, both of them successfully
1. Deploy .jar to Windows web app: deploy twice, once successfully, once failed
1. Deploy .jar to Linux web app: deploy three times, **all of them failed**

**Azure China scenarios:**
1. Deploy .war to Windows web app: deploy twice, both of them successfully
1. Deploy .jar to Windows web app: deploy twice, once successfully, once failed

**Issues:**
1. Deploy failed with below two errors
![image](https://user-images.githubusercontent.com/22470312/48927177-fa235400-ef0e-11e8-8f99-d3b9ed5ced47.png)
![image](https://user-images.githubusercontent.com/22470312/48927183-fe4f7180-ef0e-11e8-98a8-a0cc971c9a6b.png)

2. For the successful deploment, all the the web app URL can't be access
War:
![image](https://user-images.githubusercontent.com/22470312/48927243-4a021b00-ef0f-11e8-91ba-c9b6e59de756.png)
Jar:
![image](https://user-images.githubusercontent.com/22470312/48927247-55554680-ef0f-11e8-9ac1-4db149105590.png)

**Comment by andxu** [comment]
Since wildfly is not supported by now, close this issue.
