### ISSUE TITLE
Deploy to web app using wildfly runtime, the web site display 404 - Not found

### ISSUE THREAD

**Issue by sallyur** [microsoft/azure-tools-for-java#2374]
Build: 864

Repro steps:

1. Right-click a war web project-> Azure -> Run on Web App
1. Deploy to a wildfly runtime Web App
1. Click the URL to open the web site

Result:

The web site always display 404 - Not found
![image](https://user-images.githubusercontent.com/28860891/48767884-acca9b00-ecf2-11e8-92f6-584862c4c2f8.png)

**Comment by SummerSun** [comment]
This is a known issue caused by the instability of the service.

**Comment by andxu** [comment]
Wildfly support is removed by now. Closed it.
