### ISSUE TITLE
[IntelliJ][Spark][RunConf][debug]Suggest adding the correct prompt

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#2376]
Build:
artifacts/azure-toolkit-for-intellij-183.3795.13.develop.860.11-16-2018.zip
artifacts/azure-toolkit-for-intellij-2018.2.develop.860.11-16-2018.zip

Repro Steps:
1. Link a livy cluster.
2. Open the **Remote/Debug configurations** and choose **Remotely Run in Cluster**.
3. For Spark Clusters, choose the linked livy cluster.
4. Expand **Advanced Configuration(Remote Debugging)** and select **Enable Spark Remote Debug**.

Expect:
There should be a warning message showing that the livy cluster can not support remote debug.
Or disable remote debug when livy cluster is selected since SSH Authentication is always fails.

**Comment by v-jiche** [comment]
1. Choose Enable Spark Remote Debug,
2. Enter username and password, 
Result:
It would display **SSH Authentication is failed** whether the password is correct or not.
I think it is not logical. We'd better to set up a more reasonable way to disable the remote debug when livy cluster is selected.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748155
