### ISSUE TITLE
Click the "help" button in add library window, nothing shows up

### ISSUE THREAD

**Issue by sallyur** [microsoft/azure-tools-for-java#2378]
It is not a regression issue, it also repro in previous version.

Build: 864

Repro steps:

1. Right-click a web project choose Azure-Libraries Configuration
2. Click add
2. Click the "help" button in add library window

Result:

There is nothing shows up. I think it should open a page to display some info.
![image](https://user-images.githubusercontent.com/28860891/48769637-1c428980-ecf7-11e8-8a9d-432af8391efe.png)

**Comment by ZhengJun003** [comment]
Can reproduce this issue in azure toolkits for IntelliJ 3.38.0

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738774

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738815

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
