### ISSUE TITLE
Device login, user need waiting for a long time before the loading subscription window to appear

### ISSUE THREAD

**Issue by sallyur** [microsoft/azure-tools-for-java#2379]
Build: 864

Repro steps:

1. Open Azure Sign in window and choose device login 
2. Select "copy & open" in azure device login window
3. Enter code in the opened web site, click next
4. Sign in with own account
5. Return to intellij 

Result:

User need waiting for a long time before the loading subscription window to appear

**Comment by sallyur** [comment]
It < one minute, about 15 seconds on the mac, windows will be faster than mac.

**Comment by ZhengJun003** [comment]
Test pass, less than 10 seconds in windows and mac
