### ISSUE TITLE
View blob container name search is not clear

### ISSUE THREAD

**Issue by alvadb** [microsoft/azure-tools-for-java#238]
There is a textbox at the top of the blob container that seems to allows searching by blob name.  It is not clear from the UI that this is the function of this text box.

**Comment by martinsawicki** [comment]
maybe later

**Comment by Flanker32** [comment]
![image](https://user-images.githubusercontent.com/12445236/83500415-52b6b280-a4f1-11ea-9e57-e00aa274700d.png)
