### ISSUE TITLE
[IntelliJ 3][Linux]Can not select main class.

### ISSUE THREAD

**Issue by v-jiche** [Microsoft/azure-tools-for-java#2380]
Build:
azure-toolkit-for-intellij-183.4284.118.PR.2528.11-21-2018
Linux intelliJ 3

Repro Steps:
1. Create a new **SBT** project.
2. Open **Run/Debug Configurations** and choose **Locally Run**.
3. Open **Select Main Class**.
4. Choose **Project** and select one as main class, 
5. Choose **Search By Name**

Result:
1. The **OK** button is disabled(For step4).
2. Can not list the items(for step5).
![image](https://user-images.githubusercontent.com/35950097/48772685-1604db00-ed00-11e8-90ab-288cc30ddc72.png)
![image](https://user-images.githubusercontent.com/35950097/48818501-8d7d4d80-ed86-11e8-8036-f9de5286a8db.png)

Expectation:
![image](https://user-images.githubusercontent.com/35950097/48818675-39269d80-ed87-11e8-8e5b-022953afde7e.png)
![image](https://user-images.githubusercontent.com/35950097/48818688-46dc2300-ed87-11e8-9d90-0005bd0d7245.png)

**Comment by wezhang** [comment]
Looks like an IntelliJ issue.

**Comment by v-jiche** [comment]
Bug repros on build: azure-toolkit-for-intellij-2018.3.develop.946.12-30-2018

**Comment by wezhang** [comment]
@v-jiche , have you installed Scala plugin and Scala SDK?

**Comment by v-jiche** [comment]
May be I have not installed Scala plugin and Scala SDK.
