### ISSUE TITLE
Create StorageAccount for general purpose, creates blob storage in Intelij

### ISSUE THREAD

**Issue by PatrikKoskenniemi** [Microsoft/azure-tools-for-java#24]
If I create a new storage account via the Azure Explorer in Intelij and choose "General purpose" as acount kind. I end up with a blob storage which I confirm by taking a look in azure portal where I can see it is created as a blob storage. I'm using azure tool 1.5.1.

**Comment by martinsawicki** [comment]
@vladimir-shcherbakov, pls take a look along the other storage explorer issues we';ve been seeing
