### ISSUE TITLE
[IntelliJ][LinkCluster] Make ClusterManagerEx.loadHDInsightAdditionalClusters and ClusterManagerEx.saveHDInsightAdditionalClusters as common method

### ISSUE THREAD

**Issue by t-rufang** [microsoft/azure-tools-for-java#2405]
Currently linked clusters are saved independently to disk based on cluster type and manually defined property is needed to distinguish one cluster type from another.
```
DefaultLoader.getIdeHelper().setApplicationProperty(CommonConst.HDINSIGHT_ADDITIONAL_CLUSTERS, additionalClustersJson)
```
When we load clusters from disk, these properties are needed to get cluster list.
```
String additionalClustersJson = DefaultLoader.getIdeHelper().getApplicationProperty(CommonConst.HDINSIGHT_ADDITIONAL_CLUSTERS);
List<IClusterDetail> hdiAdditionalClusters = gson.fromJson(additionalClustersJson, new TypeToken<ArrayList<HDInsightAdditionalClusterDetail>>() {
                }.getType());
```
Therefore, each time we add a new cluster type we need to add a new proprty like `CommonConst.HDINSIGHT_ADDITIONAL_CLUSTERS`, which leads to redundant code.

Actually each cluster type can implement a `LinkedCluster` interface.
```
Interface LinkedCluster {
    //get cluster name with package, like "com.microsoft.azure.hdinsight.sdk.cluster.HDInsightAdditionalClusterDetail"
    String getClusterType();
}
```
When we save these linked clusters as key-value pairs, key could be `getClusterType()`, value could be list of the clusters.
Besides, we need to save a collection of cluster types when we load clusters from disk.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748153
