### ISSUE TITLE
[IntelliJ]Job Upload Storage type Azure Blob will not be saved after relaunch config dialog

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2417]
Build: Develop 880

Repro Steps:
1. Open one config dialog, click "Remotely Run in Cluster"
2. Set "Job Upload Storage" to "Azure Blog" with valid data, save the config and close.
3. Re-launch the config file, wait to refresh finished

Result:
"Job Upload Storage" change to default value "Use cluster default storage account"

Expect: 
Save "Azure Blob"

**Comment by t-rufang** [comment]
@lcadzy hi Yi, can you help to take a look at this? I guess this is related to #2354

**Comment by v-jiche** [comment]
Verified. Fixed.
Build: azure-toolkit-for-intellij-2018.3.develop.943.12-29-2018
