### ISSUE TITLE
[IntelliJ][Spark on ADL] The cluster in submit job dialog is wrong when the cluster is not stable

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2419]
Build: Develop 880

Repro Steps:
1. Provision a new cluster named "zzz"
2. Right click on the cluster and click "Submit Job", the config dialog launched.

Result:
![image](https://user-images.githubusercontent.com/36756024/49359395-198d5e80-f711-11e8-9ab8-1cf5796bf9ee.png)

**Comment by t-rufang** [comment]
Fixed in #2487

**Comment by jingyanjingyan** [comment]
Fix in develop 901, the "Submit Job" is disabled when the cluster is not stable.
