### ISSUE TITLE
Azure Toolkit for Intellij incompatible with latest Intellij Idea 2018.3 release

### ISSUE THREAD

**Issue by polarapfel** [Microsoft/azure-tools-for-java#2421]
It seems like the latest Idea release (2018.3) renders the Azure Toolkit plugin inoperable.

Any ETA on a fix?

Thanks!

**Comment by wezhang** [comment]
@polarapfel , could you please try to uninstall your current version plugin, restart IDE and re-install it? Thanks!

**Comment by polarapfel** [comment]
Update to 2018.3.1 and another version bump of the Azure plugin did the trick. Can be closed.

**Comment by wezhang** [comment]
Thanks @polarapfel !
