### ISSUE TITLE
[IntelliJ]Warning cannot find cluster when there is no main class, run livy interactive console

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2423]
Build: Develop 880

Repro Steps:
1. Make sure there is no config file
2. Open a scala file, run livy interactive console

Result:
Warning cannot find the target cluster
![image](https://user-images.githubusercontent.com/36756024/49422672-c201f800-f7cf-11e8-9c1b-1c1bf2675832.png)

The config file include cluster but does not have main class actually
![image](https://user-images.githubusercontent.com/36756024/49422710-e231b700-f7cf-11e8-8bb8-e2b29670d814.png)

**Comment by jingyanjingyan** [comment]
Repro with develop 903

**Comment by jingyanjingyan** [comment]
Expect:
When user click Edit, the cluster should be empty cause user haven't choose any one.
![image](https://user-images.githubusercontent.com/36756024/49858550-2c4e1480-fe30-11e8-9034-217c10b4f05f.png)

**Comment by jingyanjingyan** [comment]
Verify with build develop 914:
Click continue anyway, the livy interactive console does not launch and no useful warning message for it.

**Comment by v-jiche** [comment]
Verified. Fixed.
Build:
azure-toolkit-for-intellij-2018.3.develop.943.12-29-2018
