### ISSUE TITLE
[IntelliJ] Error message need update, when save config file

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2427]
Build: Develop 880

Repro Steps:
1. Save config file with invalid storage account 

Result:
![image](https://user-images.githubusercontent.com/36756024/49434985-7dd31f80-f7f0-11e8-9c4f-b933b334e009.png)

**Comment by t-rufang** [comment]
Fixed in #2506

**Comment by jingyanjingyan** [comment]
Verify with develop 946. Could not get the error since in current design, wrong storage information will not block saving config file

Note:
From the code change, it changes from "**Error** getting cluster storage configuration" to "**Error** getting cluster storage info". Not sure if it is the right fix.
