### ISSUE TITLE
[IntelliJ 3][Linux]Can not open recent project.

### ISSUE THREAD

**Issue by v-jiche** [Microsoft/azure-tools-for-java#2428]
Build:
azure-toolkit-for-intellij-183.4284.118.develop.880.11-29-2018.zip
IntelliJ 2018.3.1 RC2

Repro Steps:
1. Select **Open project in new window** from **File/Settings/Appearance&Behavior/System Settings/Project Opening**
2. Open project A(for example).
3. Open project B from **File/Open Recent.**
4. Open project A from **File/Open Recent** in the interface of B.

Result:
It will show the loading info, but the project A can not be opened.
The interface for steps 2 can not show up.
![image](https://user-images.githubusercontent.com/35950097/49432041-c0ddc480-f7e9-11e8-9b07-ac54e9b02b2d.png)

Expect:
When open project A in the interface of B, the interface of A which has been opened should display.

**Comment by v-jiche** [comment]
May be it is the problem of intelliJ itself?

**Comment by wezhang** [comment]
Could you try IntelliJ 2018.3 official release?

IntelliJ IDEA 2018.3 (Community Edition)
Build #IC-183.4284.148, built on November 20, 2018
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows Server 2012 R2 6.3

**Comment by v-jiche** [comment]
Bug repros in build:
azure-toolkit-for-intellij-183.4284.118.develop.900.12-12-2018

**Comment by wezhang** [comment]
The Intellij design.
