### ISSUE TITLE
Docker workflow picks up incorrect artifact

### ISSUE THREAD

**Issue by selvasingh** [Microsoft/azure-tools-for-java#243]
Started with a Web app
defined a JAR artifact
In the workflow, it picks up an non existent directory and it says WAR somewhere there

![image](https://cloud.githubusercontent.com/assets/3642444/24059804/99e58630-0b0d-11e7-9562-0ec24d43bcac.png)

**Comment by milismsft** [comment]
fixed

**Comment by bsaby** [comment]
Test used artifacts/azure-toolkit-for-intellij.103.zip,
Defined a JAR artifact In the workflow, it only picks up the project directory.
![image](https://cloud.githubusercontent.com/assets/22470312/24133612/25c566e2-0e39-11e7-924e-292a29b28a50.png)

**Comment by martinsawicki** [comment]
as discussed, the user expectation does not seem to match the behavior -- since the folder location is an invalid value for this anyway, it would be better to keep it blank and only use this folder as the starting folder for the browse button/file dialog.

**Comment by milismsft** [comment]
fixed; please verify.

**Comment by bsaby** [comment]
Test passed，using azure-toolkit-for-intellij.124.zip.
