### ISSUE TITLE
[intelliJ 3][Linux]Some features are missing after rebooting intelliJ

### ISSUE THREAD

**Issue by v-jiche** [Microsoft/azure-tools-for-java#2433]
Build:
azure-toolkit-for-intellij-183.4284.118.develop.880.11-29-2018.zip
 Linux
IntelliJ 2018.3.1 RC2

Repro Steps:
1. Restart intelliJ.
2. Right click LogQuery.

Result:
Some missing, some unclickable.
![image](https://user-images.githubusercontent.com/35950097/49496086-f5ac5300-f89f-11e8-9dbf-c1a078f9c069.png)

**Comment by v-jiche** [comment]
Restart intelliJ
1. When intelliJ is in the loading state, choose one of these scala files and right click it,
   features are incomplete(As shown below).
2. Then wait for the load of intelliJ to complete. 
3. Right click these scala files, only the result of LogQuery is not normal(As shown below).
![image](https://user-images.githubusercontent.com/35950097/49496086-f5ac5300-f89f-11e8-9dbf-c1a078f9c069.png)

**Comment by wezhang** [comment]
I can repro it. The IDEA 2018.3 changed some behaviors, those menu items will be shown after the index process is finished. @v-jiche

**Comment by wezhang** [comment]
![image](https://user-images.githubusercontent.com/7385667/49559902-60ff2f00-f94b-11e8-8b62-b52e22c16030.png)

**Comment by v-jiche** [comment]
@wezhang 
I can repro this bug now.
The index process has been finished.
The intelliJ version is what you said above.

![image](https://user-images.githubusercontent.com/35950097/49571506-79377400-f974-11e8-9079-37b0b69a16f6.png)

**Comment by v-jiche** [comment]
Bug repros in build:
Build: azure-toolkit-for-intellij-183.4284.118.develop.900.12-12-2018 (**only Linux**)

**Comment by v-jiche** [comment]
Verified. Fixed.
Build: azure-toolkit-for-intellij-2018.3.develop.1036.03-20-2019
