### ISSUE TITLE
[IntelliJ][RunConf][Spark][console][autofix] Click on Tools when deleting a config file, then local/livy console will not be launched

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2435]
Build: Develop 880

Repro Steps:
1. Create a new project
2. Open "LogQuery", click "Tools\Spark Console\Run Spark Local Console(Scala)"
3. Auto fix dialog pops, click "Close", a local console config file will be created.
4. Delete the config file, click OK. **Notice the config file is not deleted right away, please click "Tools" here before it is deleted**
5. Click "Tools" does not works here, wait the config file to be deleted.
6. **Click "Tools\Spark Console\Run Spark Livy Interactive Session Console(Scala)", a warning pops could not find target cluster, dismiss**
7. CLick "Tools\Spark Console\Run Spark Livy Interactive Session Console(Scala)".
8. Click "Tools\Spark Console\Run Spark Local Console(Scala)".

Result:
Nothing happened

**Comment by v-jiche** [comment]
Fixed. Verified.
Build:
azure-toolkit-for-intellij-2018.3.develop.1052.03-26-2019
