### ISSUE TITLE
Web Apps (Refreshing...)(Refreshing...) in Azure explorer

### ISSUE THREAD

**Issue by alvadb** [Microsoft/azure-tools-for-java#244]
I was able to start two refresh operations in azure explorer for Web Apps.   I double clicked the node to start the refresh upon start of the explorer and then right clicked and selected refresh from context menu.

**Comment by lenala** [comment]
Fixed, please verify.

**Comment by bsaby** [comment]
Test passed, using artifacts/WindowsAzurePlugin4EJ.150.zip.
