### ISSUE TITLE
[IntelliJ] Link aris under HDInsight, then link the same aris cluster under Big Data will be blocked

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2449]
Build: Private build 2621

Repro Steps:
1. Link aris cluster under HDInsight node with name "catest"
2. Start to link aris cluster under "SQL Big Data Cluster"

Result:
Link with "catest", result to cluster already exist.
Link with "CATEST", result to success.
![image](https://user-images.githubusercontent.com/36756024/49573578-41114080-f936-11e8-894c-dfd21e25563e.png)

**Comment by wezhang** [comment]
Duplicated naming is not allowed for all linked type clusters

**Comment by t-rufang** [comment]
Actually duplicate naming is allowed between HDInsight cluster and Aris cluster since they are totally two different clusters. Fow now code implementation mix these clusters together but naming validation are supposed to be seperated. This issue is fixed in #2469.

**Comment by jingyanjingyan** [comment]
Fixed in private build 2642:
Allow dup name between HDI and Aris.
Do not allow dup name inside HDI or inside Aris.
