### ISSUE TITLE
Web Apps (Refreshing...) stays in Azure Explorer

### ISSUE THREAD

**Issue by alvadb** [Microsoft/azure-tools-for-java#245]
Web Apps (Refreshing...) stays after starting two refresh operations at the same time.

**Comment by martinsawicki** [comment]
repro: if an exception happens during refresh, the title remains
possibly the same underlying cause as when we see Refreshing twice...?

**Comment by lenala** [comment]
Does not repro, probably already fixed. Please verify.

**Comment by bsaby** [comment]
Not rerpo, using artifacts/WindowsAzurePlugin4EJ.150.zip.
