### ISSUE TITLE
[IntelliJ] Link aris cluster with HDInsight cluster name, it will disappear from HDInsight node

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2450]
Build: Private 2621

Repro Steps;
1, Link aris cluster with name "spark3" (existing HDInsight cluster)
2. Expand HDInsight node

Result:
HDInsight cluster "spark3" is not listed any more.

![image](https://user-images.githubusercontent.com/36756024/49576691-a87ebe80-f93d-11e8-8c59-8ade699875af.png)

**Comment by wezhang** [comment]
We should keep the duplicated naming check consistent in linking and displaying.

**Comment by t-rufang** [comment]
Fixed in #2469

**Comment by jingyanjingyan** [comment]
Fix in private build 2642.
Link aris cluster with existing HDI cluster name, both display well.
