### ISSUE TITLE
[IntelliJ] Link A Spark Cluster, Unlink SQL Big Data Cluster, the dialog title need consistent

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2451]
Build: Private build 2621

Repro Steps:
1. Right click on the aris node, the context menu item is "Link A Spark Cluster"
2. Link an aris cluster, dialog title is "Link A Spark Cluster"
3. Unlink an aris cluster, dialog title is "Unlink SQL Big Data Cluster"

Result:
Need consistent.
![image](https://user-images.githubusercontent.com/36756024/49626939-0fe74d80-f9d4-11e8-9240-dc3bbd54986f.png)

![image](https://user-images.githubusercontent.com/36756024/49579113-4c1e9d80-f943-11e8-8aa7-2a87a17b934d.png)

![image](https://user-images.githubusercontent.com/36756024/49579096-4628bc80-f943-11e8-85b0-e3ea84857bac.png)

**Comment by wezhang** [comment]
Align them to `SQL Big Data Cluster` please

**Comment by jingyanjingyan** [comment]
Verify with private build 2642, right click on aris node, the context menu still use "Link A Spark Cluster"

**Comment by t-rufang** [comment]
@jingyanjingyan Hi Yan, please retry with the latest build in #2409 .

**Comment by t-rufang** [comment]
Fixed in #2506

**Comment by v-jiche** [comment]
Verified, Fixed.
Build:
azure-toolkit-for-intellij-2018.3.develop.943.12-29-2018

![image](https://user-images.githubusercontent.com/35950097/50537949-1c883d00-0b5f-11e9-9436-a70083e763a6.png)
![image](https://user-images.githubusercontent.com/35950097/50537952-2873ff00-0b5f-11e9-9638-01ba18509b0b.png)
![image](https://user-images.githubusercontent.com/35950097/50537955-332e9400-0b5f-11e9-94e3-a6a6bbe05e0f.png)
