### ISSUE TITLE
[IntelliJ] Link aris cluster does not need to check cluster name  other than duplicate

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2452]
Build: Private 2621

Repro Steps:
1. Start to link aris cluster
2. Enter "https://13.68.204.159:30443/gateway/default/livy/v1" as cluster name
3. Click OK

Result:
Warning says wrong cluster name or endpoint
![image](https://user-images.githubusercontent.com/36756024/49580647-55aa0480-f947-11e8-81a5-35a6f3d9da31.png)

Expect:
No need to check cluster name other than duplicate.

**Comment by wezhang** [comment]
We can ignore the error for this type linked cluster

**Comment by t-rufang** [comment]
Fixed in #2469

**Comment by jingyanjingyan** [comment]
Verify with private build 2642
Use the url as cluster name, click OK then nothing happened, the link dialog keep openning without any warning.
![image](https://user-images.githubusercontent.com/36756024/49844276-41f61680-fdfd-11e8-85bc-3a0b867d3d0b.png)

**Comment by t-rufang** [comment]
@jingyanjingyan hi Yan, the new pic you pasted should be posted in a new issue. Please close this one.

**Comment by jingyanjingyan** [comment]
Track in 2500
