### ISSUE TITLE
[IntelliJ] Update HDInsight Logo

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2453]
IntelliJ: 
1.	HDInsight node
![image](https://user-images.githubusercontent.com/36756024/49581465-0686c280-f98d-11e8-9fcf-098d7f46048c.png)

2.	Configuration for HDInsight
![image](https://user-images.githubusercontent.com/36756024/49581491-169ea200-f98d-11e8-9b95-b59417fcc1d1.png)

3.	Statue bar
![image](https://user-images.githubusercontent.com/36756024/49581510-23bb9100-f98d-11e8-8ce1-af4080fb99c5.png)

4.	New a project
![image](https://user-images.githubusercontent.com/36756024/49581527-303fe980-f98d-11e8-89ed-f48ae12c9ddc.png)
 
Eclipse:  HDInsight node
![image](https://user-images.githubusercontent.com/36756024/49581535-3afa7e80-f98d-11e8-91be-dc91a1ab42c6.png)

**Comment by lcadzy** [comment]
only change aris icon this millestone

**Comment by jingyanjingyan** [comment]
Verif with develop 907, aris logo fixed, the others kept
