### ISSUE TITLE
[IntelliJ] SQL Big Data Cluster logo

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2456]
Build: Develop 887

Repro Steps:
1. Sign in and expand Azure

Result:
Logo of "SQL Big Data Cluster" does not show well
![image](https://user-images.githubusercontent.com/36756024/49629806-4d74c680-fa26-11e8-906c-218e7c7fdc16.png)

**Comment by t-rufang** [comment]
Fixed in #2480

**Comment by jingyanjingyan** [comment]
Fix in develop 900
