### ISSUE TITLE
[IntelliJ]Local run and local debug blocked !

### ISSUE THREAD

**Issue by v-xiaocw** [Microsoft/azure-tools-for-java#2457]
Build: develop 887
intelliJ  2018.3.1 RC2

Repro Steps:
1. Create a new project 
2.Open  LogQuery  ,then click **local run** on conment menu 
3.Run local debug.

Result: Blocked and logs as follow:
For Windows:
![image](https://user-images.githubusercontent.com/43333874/49631117-a3555a00-f9a5-11e8-895e-85934baf5835.png)
For Linux:
![image](https://user-images.githubusercontent.com/35950097/49632603-443d2700-fa31-11e8-864d-2d1fa1f72db9.png)

**Comment by wezhang** [comment]
Java parameters `mainClass` and `moduleName`, which caused `JdkUtil::getMainClassParams` appending `-m` option:

```java
    String mainClass = javaParameters.getMainClass();
    String moduleName = javaParameters.getModuleName();
    String jarPath = javaParameters.getJarPath();
    if (mainClass != null && moduleName != null) {
      return Arrays.asList("-m", moduleName + '/' + mainClass);
    }
```

**Comment by v-xiaocw** [comment]
Verify as fixed in develop build 900
