### ISSUE TITLE
Cannot login when certificate required

### ISSUE THREAD

**Issue by tilumi** [microsoft/azure-tools-for-java#2459]
After I input username & password, it requires me to select certificate, but the selection window not shown and nothing happens.

![capture](https://user-images.githubusercontent.com/734766/49633316-e2ca8780-fa33-11e8-8499-a0425f78dc8b.PNG)

**Comment by andxu** [comment]
The login page is previously shown in java swing, but now it open the navigator, @tilumi , could you please take a try about the new experience?
