### ISSUE TITLE
Eclipse Neon - [Azure Explorer] Show ellipses for menu items that require additional info to complete the action

### ISSUE THREAD

**Issue by joshuahinds** [Microsoft/azure-tools-for-java#246]
For items in a context menu that need additional actions to be taken in order to complete the task, they should use an ellipsis at the end.

![storage-account-context-menu](https://cloud.githubusercontent.com/assets/4510946/24059852/d437a4e4-0b0d-11e7-9229-c591bc3922f7.PNG)

Note that an ellipsis is needed because the user should take additional action, not because it opens a dialog.

See here for more information:
https://msdn.microsoft.com/en-us/library/windows/desktop/dn742402(v=vs.85).aspx

**Comment by lenala** [comment]
Fixed, please verify.

**Comment by bsaby** [comment]
Test passed in artifacts/WindowsAzurePlugin4EJ.108.zip.
![image](https://cloud.githubusercontent.com/assets/22470312/24138637/f32e21c2-0e53-11e7-9649-77cb9f54f355.png)
