### ISSUE TITLE
[IntelliJ]Spark Livy interactive session console blocked!

### ISSUE THREAD

**Issue by v-xiaocw** [Microsoft/azure-tools-for-java#2472]
Build: develop 889

intellij:  IntelliJ IDEA 2018.3.1 (Community Edition)
Build #IC-183.4588.27, built on November 28, 2018
JRE: 1.8.0_152-release-1343-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
 Repro Steps:
1.Create a new project 
2.Click **Run Spark Livy interactive Session Console** on Tools drop-down menu
3.After you close the error that  **cannot find the target cluster**,fill in the configuration file with the main class.
4..Click **Run Spark Livy interactive Session Console** on Tools drop-down menu **again**.
5.Enter SC. or Spark
Result:
After step 4 must wait for more than 2 minutes,then show up as follow picture:
![image](https://user-images.githubusercontent.com/43333874/49785485-91412780-fcd5-11e8-92c8-1dd596f59ea2.png)
The result of step 5:
![image](https://user-images.githubusercontent.com/43333874/49785459-7c649400-fcd5-11e8-83da-fbb3d4eb27fd.png)

**Comment by jingyanjingyan** [comment]
Fix with develop 901
