### ISSUE TITLE
[IntelliJ] Submit with empty artifact, the error message is not clear

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2481]
Build: Develop 894

Repro Steps:
1. Create a spark on cosmos config file, choose "Artifact from local disk" and keep empty, Save
![image](https://user-images.githubusercontent.com/36756024/49795527-18bc8400-fd32-11e8-820b-76c8307b2103.png)

2. Remote run, click continue anyway when pops

Result:
Error message is not clear for user
![image](https://user-images.githubusercontent.com/36756024/49795551-2bcf5400-fd32-11e8-82cc-e87693214852.png)

**Comment by jingyanjingyan** [comment]
Repro with Build 907

**Comment by wezhang** [comment]
I suppose it can be fixed with #2554

**Comment by v-jiche** [comment]
Verified. Fixed.
Build:
azure-toolkit-for-intellij-2018.3.develop.943.12-29-2018
![image](https://user-images.githubusercontent.com/35950097/50537980-b64fea00-0b5f-11e9-92be-007aaad26d26.png)
