### ISSUE TITLE
[IntelliJ][Spark][local][console][RunConf] Local console should not running when local run?

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#2482]
Build: Develop 894

Repro Steps:
1. Create a config file, i use spark on cosmos config file
2. Launch Local console
3. Start local run, get warning could not run config parallel
![image](https://user-images.githubusercontent.com/36756024/49796109-b4022900-fd33-11e8-96be-fd67a4717f64.png)
4. Choose "Stop and Rerun"
5. In the local run process, launch local console

Result:
Launch local console successfully

Expect:
If the config should not be running parallel, then should not allow to launch local console when local running.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748150
