### ISSUE TITLE
[IntelliJ] Warning message should not include \n

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2483]
Build: Develop 894

Repro Steps:
1. Create a spark on cosmos config file, leave some area empty, save
2. Remote run

Result:
Warning message 
![image](https://user-images.githubusercontent.com/36756024/49797338-fed17000-fd36-11e8-815e-ad0beeb410ec.png)

Expect:
Should not include \n

**Comment by jingyanjingyan** [comment]
Verify with build develop 907
One kind of error message still have \n inside.

**Comment by wezhang** [comment]
I'll change it to only show the first error of list

**Comment by v-jiche** [comment]
Verified. Fixed.
Build:
azure-toolkit-for-intellij-2018.3.develop.943.12-29-2018
