### ISSUE TITLE
[IntelliJ] Only selected upload storage need be checked

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2484]
Build: Develop 894

Repro Steps:
1. Create a new spark on cosmos config file, click on "Remotely run in cluster", input valid main class
2. In "Upload Storage", select "Azure Blob" and keep it empty, click "OK"
3. Click remote run, get warning message 
![image](https://user-images.githubusercontent.com/36756024/49797830-8e2b5300-fd38-11e8-9f12-7355c6074e28.png)

4. Click "Edit", change the upload storage to "ADLS Gen1", keep it empty, click "OK"
5. Click "SparkJobRun"

Result:
Warning include invalid azure blob and adls gen1
![image](https://user-images.githubusercontent.com/36756024/49797958-ea8e7280-fd38-11e8-9091-a0d8c1af5a04.png)

Expect:
Only selected storage information need be checked.

**Comment by jingyanjingyan** [comment]
Repro with build develop 905

**Comment by wezhang** [comment]
A workaround is to click `Continue Anyway` to bypass the warning

**Comment by lcadzy** [comment]
it can't repo based on the latest bit. Only shows the selected storage type invalid.

**Comment by v-jiche** [comment]
Verified. Fixed.
Build:
azure-toolkit-for-intellij-2018.3.develop.943.12-29-2018
