### ISSUE TITLE
[intelliJ]Wrong icon in Azure Explorer.

### ISSUE THREAD

**Issue by v-jiche** [Microsoft/azure-tools-for-java#2486]
Build:
azure-toolkit-for-intellij-183.4284.118.develop.896.12-11-2018

Repro Steps:
Open Azure Explorer.

Result:
![image](https://user-images.githubusercontent.com/35950097/49799147-23e9d100-fd7f-11e8-8892-a97e844a0a9f.png)

**Comment by t-rufang** [comment]
Fixed in another [icon repo](https://github.com/Microsoft/azure-tools-for-java-resources/pull/26)

**Comment by v-jiche** [comment]
Fixed.
Verified.
azure-toolkit-for-intellij-183.4284.118.develop.900.12-12-2018
