### ISSUE TITLE
[IntelliJ] The edit Auth status will not be saved

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2488]
Build: Develop 894

Repro Steps:
1. Create a new HDInsight config file, click "Remotely run Cluster", set main class, and advanced settings, Auth pass now.
2. Re-open the config file, edit the Auth to use wrong password, Auto fails now.
3. Remote debug, click Edit when pops warning says Auth fails.
4. In the config dialog, Auth is fails
![image](https://user-images.githubusercontent.com/36756024/49801444-1e21ca80-fd42-11e8-8528-d6a964f5f474.png)

5. Cancel
6. Open the config file from tool bar, the Auth status is pass
![image](https://user-images.githubusercontent.com/36756024/49801529-56290d80-fd42-11e8-9773-34b348a31f46.png)

7. Remote debug, warning Auth fails again
![image](https://user-images.githubusercontent.com/36756024/49801541-6640ed00-fd42-11e8-8070-495e1f72a86a.png)

Result:
The config file from toolbar is different from edit entry, it makes user confuse in step 7.

**Comment by v-jiche** [comment]
Verified. Fixed.
Build: azure-toolkit-for-intellij-2018.3.develop.953.01-02-2019

Whether you click edit  or open the configuration  from the toolbar, the result is failed.
