### ISSUE TITLE
[IntelliJ] Config dialog refresh issue

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2489]
Build: Develop 894

Repro Steps:
1. Open config dialog, it will refresh sometimes, check the left panel

Result:
![image](https://user-images.githubusercontent.com/36756024/49803989-5a0c5e00-fd49-11e8-87c2-f4c4e49cb689.png)

![image](https://user-images.githubusercontent.com/36756024/49804016-698ba700-fd49-11e8-9a89-ace97ad2fe50.png)

**Comment by wezhang** [comment]
IntelliJ regression issues
