### ISSUE TITLE
Clicking on a web app after switching apps is locking up Eclipse

### ISSUE THREAD

**Issue by alvadb** [Microsoft/azure-tools-for-java#249]
Requires shutdown of Eclipse to enable UI.

**Comment by vladimir-shcherbakov** [comment]
@alvadb 
Clicking on a web app  - what do you mean?

**Comment by lenala** [comment]
Should be fixed now, please verify. There was a problem that if exception happened when loading node, there was a call Dysplay.asyncExec() already inside UI thread. I added a check that if we already are in UI thread and if yes, run UI code directly.

**Comment by bsaby** [comment]
Not repro, using WindowsAzurePlugin4EJ.141.zip.
