### ISSUE TITLE
 [IntelliJ 3][Linux][Device Login]Can not Azure sign in.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#2498]
Build:
azure-toolkit-for-intellij-183.4284.118.develop.900.12-12-2018

Repro Steps:
1. Open Azure Explorer.
2. Right Click Azure and choose Sign In.
3. Choose Interactive sign in.

Result:
**Copy&Open** button is not enabled.
![image](https://user-images.githubusercontent.com/35950097/49849136-25fd6f80-fe13-11e8-981e-5279848fb509.png)

**Comment by andxu** [comment]
@v-jiche Can you try it again, I can click the button in latest version.
