### ISSUE TITLE
[IntelliJ][Linux] Get "ADLS Root Path is invalid" error when choose "ADLS Gen 1" as job upload storage type

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2501]
Build: Develop 903

Repro Steps:
1. Create a config file, select ADLS cluster
2. In the upload storage field, set the path and keep the focus on
3. Click OK to save
4. SparkJobRun

Result:
Warning the value is invalid. Click Edit the value is display well.
![image](https://user-images.githubusercontent.com/36756024/49851283-8ae7a400-fdd8-11e8-8e79-cd0a41b4f0d2.png)

Expect:
Display but not accept makes user confuse.

**Comment by t-rufang** [comment]
Workaround for this issue:
User can choose `Continue Anyway` to continue remote run the spark job successfully. Please wait a minute when you get stuck at "Finishing. Saving caches...".

**Comment by wezhang** [comment]
You can set the upload path to `<NOT AVAILABLE>` if the path setting is not right

**Comment by v-jiche** [comment]
Build:
devlop 943

The Storage type is not stored.
![image](https://user-images.githubusercontent.com/35950097/50538551-3b8bcc80-0b69-11e9-895f-5883e7b118f5.png)

**Comment by wezhang** [comment]
Dup #2502
