### ISSUE TITLE
[IntelliJ] keep artifact empty, then the main class browse button unclickable

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2510]
Build: Private build 2675

Repro Steps:
1. Create a config, leave artifact empty and click on the browse button of main class
![image](https://user-images.githubusercontent.com/36756024/49915040-921bba00-fe8b-11e8-8ec7-2c83e572bd5b.png)

Result:
Could not launch the select main class window

**Comment by wezhang** [comment]
That's by design since the select main class window needs the artifact to provide options.
