### ISSUE TITLE
[Azure China] Now our account does not support the default pricing tier P1V2 

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#2512]
Build: 3.16.0 pre-release package

Result:
1. Run on Web App using the default pricing tier: P1V2
![image](https://user-images.githubusercontent.com/22470312/49917919-17c75600-fedc-11e8-8db5-1aaeb7412bf0.png)
1. Can deploy successfully using other available pricring tiers, e.g. Standard_S1

From Azure China Portal:
![image](https://user-images.githubusercontent.com/22470312/49918132-edc26380-fedc-11e8-8fb3-db6b17b99e43.png)

**Comment by ZhengJun003** [comment]
Because azure china accounts not ready, so can't reproduce this issue.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738805

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
