### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception updateSubscriptionWithProgressDialog com.microsoft.azure.CloudException: Status code 401

### ISSUE THREAD

**Issue by kevinchan800** [microsoft/azure-tools-for-java#2524]
IntelliJ build version: 2018.3.1 IC-183.4588.61
OS: Mac OS X
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.15.0-2018.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,2048x1191,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=updateSubscriptionWithProgressDialog, throwable=com.microsoft.azure.CloudException: Status code 401, {"error":{"code":"InvalidAuthenticationTokenAudience","message":"The access token has been obtained for wrong audience or resource 'https://graph.windows.net/'. It should exactly match with one of the allowed audiences 'https://management.core.windows.net/','https://management.core.windows.net','https://management.azure.
```

Copy and format the title:
```
Uncaught Exception updateSubscriptionWithProgressDialog com.microsoft.azure.CloudException: Status code 401, 
{
    "error": {
        "code": "InvalidAuthenticationTokenAudience",
        "message": "The access token has been obtained for wrong audience or resource 'https://graph.windows.net/'. It should exactly match with one of the allowed audiences 'https://management.core.windows.net/','https://management.core.windows.net','https://management.azure.com/','https://management.azure.com'."
    }
}: The access token has been obtained for wrong audience or resource 'https://graph.windows.net/'. It should exactly match with one of the allowed audiences 'https://management.core.windows.net/','https://management.core.windows.net','https://management.azure.com/','https://management.azure.com'.
```

**Comment by wezhang** [comment]
Thanks @kevinchan800! I suppose it's fixed in 3.16

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Uncaught Exception  com.microsoft.azure.CloudException: Status code 401, The access token has been ... (#1874)

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Uncaught Exception  com.microsoft.azure.CloudException: Status code 401, The access token has been ... (#1874)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: The access token has been obtained for wrong audience or resource * It should exactly match with one of the allowed audience

**Comment by andxu** [comment]
@kevinchan800 , sorry to keep this issue for quite a long time, we have major changes in recent releases with the support of login our plugin using azure cli. Can you retry our plugin following this [link])(https://github.com/microsoft/azure-tools-for-java/issues/4684#issuecomment-719129692)?
