### ISSUE TITLE
Remote Debugging on Eclipse 3.11 is missing 

### ISSUE THREAD

**Issue by Ahmad-Al-Ali** [microsoft/azure-tools-for-java#2533]
Hello Team, 
I can't find the remote debugging option described in the article below, I am using version 3.11 for eclipse ( marketplace ) and the latest version of IntelliJ toolkit
https://azure.microsoft.com/en-us/blog/debug-java-web-apps-on-azure-in-eclipse-or-intellij/

did you remove remote debugging option from the toolkit ? is there any workarounds or alternatives ?

**Comment by t-rufang** [comment]
@SummerSun Hi Summer, can you help to take a look at this issue?

**Comment by Eskibear** [comment]
@Ahmad-Al-Ali AFAIK, the feature was removed in early 2017. The blog you mentioned is out-of-date. See if [this repo](https://github.com/Azure/azure-websites-java-remote-debugging) can help you work around.

**Comment by Ahmad-Al-Ali** [comment]
@Eskibear thanks a lot for the feedback.

**Comment by HughDevlin** [comment]
Where is the discussion of the removal of support for remote debugging from other than VS?

**Comment by HughDevlin** [comment]
Please re-open. If the feature is removed, please remove the how-to article linked in the head post of this thread, and please state clearly debugging is available only to VS users.

**Comment by HughDevlin** [comment]
The following are part of Java:
Java Platform Debugger Architecture (JPDA)
Java Debug Wire Protocol (JDWP)
Java Debug Interface (JDI)
For example they are included in Zulu.
If they are not supported for Java applications and/or Java Web Apps on Azure, Azure documentation should clearly so state, and misleading documentation including blog posts should be captioned or removed, before this issue is closed. Thank you.

**Comment by yucwan** [comment]
Remote debug for Java Web App has been disabled from service side so it's no longer exist in Azure Toolkit for Eclipse/IntelliJ. There are other ways to debug though:
- Debug locally
- Use log stream
- Use Java Flight Recorder
- Aggregate logs and metrics in Azure Log Analytics or ELK or Splunk or any other choice of tools
- If using Spring Boot, turn on actuator

@HughDevlin We are removing the blog post, sorry for the confusion.

**Comment by HughDevlin** [comment]
Please re-open. Please do not close until:
1. misleading blog post is removed or captioned with a deprecation warning
https://azure.microsoft.com/en-us/blog/debug-java-web-apps-on-azure-in-eclipse-or-intellij/
2. Azure WebApp docs clearly state that Java Platform Debugger Architecture (JPDA), Java Debug Wire Protocol (JDWP), and
Java Debug Interface (JDI), which are all part of every Java runtime including Azul Zulu, are not supported for Java Azure WebApps.
Thank you in advance for your commitment to correct and complete documentation.

**Comment by HughDevlin** [comment]
Thank you for the list of alternative methods for remotely debugging Azure Web Apps written in Java.
Is remote debugging of Java Azure Web Apps available through:
1. Microsoft Visual Studio
2. Microsoft Visual Studio Code?

**Comment by yucwan** [comment]
> Thank you for the list of alternative methods for remotely debugging Azure Web Apps written in Java.
> Is remote debugging of Java Azure Web Apps available through:
> 
> 1. Microsoft Visual Studio
> 2. Microsoft Visual Studio Code?

It is removed from service backend so not available for Java in VS and VS Code as well.

**Comment by HughDevlin** [comment]
Thank you for re-opening this issue.

1. Is the following tutorial blog post also deprecated?

Remote debugging Azure App Services

https://devblogs.microsoft.com/premier-developer/remote-debugging-azure-app-services/

2. Is remote debugging of Azure Web Apps written in J# and ASP.NET using Visual Studio supported?

**Comment by yucwan** [comment]
> Thank you for re-opening this issue.
> 
> 1. Is the following tutorial blog post also deprecated?
> 
> Remote debugging Azure App Services
> 
> https://devblogs.microsoft.com/premier-developer/remote-debugging-azure-app-services/
> 
> 1. Is remote debugging of Azure Web Apps written in J# and ASP.NET using Visual Studio supported?

As far as I know, 1. No 2. Yes. See: https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging?view=vs-2019

**Comment by HughDevlin** [comment]
ok, thank you, please close
