### ISSUE TITLE
[IntelliJ]Error massage:"There are errors in submit model :refrshing storage containers is not completed." should not pop up .

### ISSUE THREAD

**Issue by v-xiaocw** [Microsoft/azure-tools-for-java#2537]
Build: Maket  Build

Repro Steps:
1.Create a configuration file and select the spark22blobhdi 
2.Set up "job upload storage":select "Azure Blob"as storage type ,fill in the storage account and key.
3.Storage container :Click the "Refresh",or  Cursor tabs away from the Storage key Input box,waiting for refresh to complete and Upload path loaded out .
4.Click Apply while the refresh button is triggered again,waiting for refresh to complete again.
5.Click Apply again,and then OK
6.Click the button of "Remote run"
Result:
1.Get error massage:
![image](https://user-images.githubusercontent.com/43333874/50263010-a6e6d900-03c8-11e9-91fe-5ff291ac1372.png)

**Comment by t-rufang** [comment]
Not repro
