### ISSUE TITLE
Function-specific app service plans shouldnt be listed for Web Apps

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#254]
the plugin lists all app service plans right now, including the Dynamic Pricing ones, but it turns out those cannot be used for web apps. So the plugin should not include those in the list, otherwise the following error shows up:

![badappsvcplan](https://cloud.githubusercontent.com/assets/881767/24060816/20bee788-0b12-11e7-8d39-aa63a2f3cc88.png)

**Comment by bsaby** [comment]
Test passed in  Eclipse and IntelliJ using artifacts/WindowsAzurePlugin4EJ.136.zip and  azure-toolkit-for-intellij.132.zip.
