### ISSUE TITLE
[IntelliJ]When setting up a congfig file to switch cluster while remote debug's SSH password should also follow the change

### ISSUE THREAD

**Issue by v-xiaocw** [Microsoft/azure-tools-for-java#2544]
Build: develop 913

Repro Steps:
1.Create a new project
2.Create a HDInsight configuration file ,select a commonly used cluster,then click "Apply"and "OK"
3.Reopen the configuration file ,and open Advanced Configuraton you can see that the sshuser password has automatically appeared.
4.Replace a cluster that is not commonly used,then click "Apply"and "OK"
5.Reopen the configuration file ,and open Advanced Configuraton 
Result:
You'll see that the ssuser password still exists without changing it.

Expectation:
The password of the memory changes with the cluster change

**Comment by v-jiche** [comment]
Verified. Fixed.
Build: azure-toolkit-for-intellij-2018.3.develop.953.01-02-2019

The part of SSH Authentication will be re-refreshed when make changes on spark clusters.
