### ISSUE TITLE
[IntelliJ] Reject aris certificate, warning message need update

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2547]
Build: Develop 914

Repro Steps:
1. Link an aris cluster and reject when pops certificate dialog

Result:
Warning message says livy URL
![image](https://user-images.githubusercontent.com/36756024/50436625-d1cdb180-0921-11e9-87b5-9b35d21dbd81.png)

Expect:
Should change to Host?

**Comment by v-jiche** [comment]
Verified, Fixed.
azure-toolkit-for-intellij-2018.3.develop.923.12-27-2018
Change livy URL to host.
![image](https://user-images.githubusercontent.com/35950097/50471442-844a5680-09ac-11e9-8207-9d952a59b40a.png)
