### ISSUE TITLE
Manage Subscriptions Context menu option on Azure node in Azure Explorer not functional.

### ISSUE THREAD

**Issue by alvadb** [Microsoft/azure-tools-for-java#255]

**Comment by lenala** [comment]
Fixed, please verify.

**Comment by vladimir-shcherbakov** [comment]
we also need to rename it from "Manage Subscriptions" to  "Select Subscriptions"

**Comment by bsaby** [comment]
The select subscriptions toolbar button should also not functional. But when I click Select Subscriptions button, it will refresh Azure explorer and cause the refresh to be repeated.
![image](https://cloud.githubusercontent.com/assets/22470312/24087080/e01ea82c-0d54-11e7-8ac5-f4b13e6e91b3.png)

**Comment by lenala** [comment]
Fixed, please verify.

**Comment by bsaby** [comment]
Test passed, using artifacts/WindowsAzurePlugin4EJ.141.zip.
