### ISSUE TITLE
[IntelliJ][Serverless][RunConf] Remove serverless entries

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2559]
Build: Develop 923

1. From config file
![image](https://user-images.githubusercontent.com/36756024/50466981-7bbd4480-09db-11e9-8166-2db9b0178ca7.png)

2. From the context menu of a script
![image](https://user-images.githubusercontent.com/36756024/50466999-a60f0200-09db-11e9-8f5b-1db80eefcecf.png)

3. From tool menu
![image](https://user-images.githubusercontent.com/36756024/50467016-c048e000-09db-11e9-9830-3209e46974f0.png)

4. From spark on cosmos context menu
![image](https://user-images.githubusercontent.com/36756024/50467049-0140f480-09dc-11e9-95a2-45886698bead.png)

5. From view menu
![image](https://user-images.githubusercontent.com/36756024/50467103-4d8c3480-09dc-11e9-995f-e36a0bb679cd.png)

**Comment by wezhang** [comment]
@konjac , could you confirm these?

**Comment by konjac** [comment]
I will put these two entries under the control of config settings in #2565

**Comment by jingyanjingyan** [comment]
Verify with develop 946, one more serverless entry:

Repro Step: 
1. Click "+"
2. Click "6 items more" at the bottom of config list.

Result:
![image](https://user-images.githubusercontent.com/36756024/50579946-dc89c880-0e84-11e9-8885-d96393a11306.png)

**Comment by v-jiche** [comment]
Build: azure-toolkit-for-intellij-2018.3.develop.953.01-02-2019

Result:
Section 1 has not been fixed. The button is clickable.
![image](https://user-images.githubusercontent.com/35950097/50587094-7006cd80-0e74-11e9-850b-8d14a4938291.png)

The other part is fixed. The button is gray and unclickable.
