### ISSUE TITLE
[IntelliJ][RunConf] Azure Data Lake Spark Pool config description need update

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2561]
Build: Develop 923

Repro Steps:
1. Start to create a new Azure Data Lake Spark Pool config file
2. Click on the group title

Result:
The description use Cosmos ADL Spark Job
![image](https://user-images.githubusercontent.com/36756024/50467406-d061bf00-09dd-11e9-950f-487c72c91bcb.png)

Expect:
Update to "Azure Data Lake Spark Pool"

**Comment by wezhang** [comment]
PR #2602 is reverted by #2606
