### ISSUE TITLE
[IntelliJ][RunConf] Two Azure Data Lake Spark Pool config groups

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#2562]
Build: Develop 923

Repro Steps:
1. Create a new project, make sure no config file
2. Right click on "LogQuery", select "Default Spark Application Type\CosmosSpark"
3. Right click on "LogQuery", select "Create[Cosmos Spark]LogQuery...", click OK to save
4. Click "Edit Configuration", click "+", select "Azure Data Lake Spark Pool" to create a new config

Result:
Two "Azure Data Lake Spark Pool" display, After re-open config dialog, there is only on group then.
![image](https://user-images.githubusercontent.com/36756024/50468573-9398c680-09e3-11e9-8f48-e5964056156f.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748149
