### ISSUE TITLE
[IntelliJ] Create config continually from context menu get the configs with the same name

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2564]
Build: Develop 923

Repro Steps:
1. Create a new project, make sure there is no config file
2. Right click on "LogQuery\Default Spark Application Type\HDInsight"
3. Right click on "LogQuery\Create"[Spark Job] LogQuery...", delete the local config\main class, click OK to save
4. Right click on "LogQuery\Create"[Spark Job] LogQuery...", click OK to save without change anything
5. Edit Configuration

Result:
Two config display with the same name, click OK now get warning the same name already exist
![image](https://user-images.githubusercontent.com/36756024/50471035-f727f180-09ed-11e9-8911-305cde0f8171.png)

**Comment by wezhang** [comment]
It's the behavior of IntelliJ
