### ISSUE TITLE
Need consistency in naming between Toolbar buttons and Context menu

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#257]
The toolbar shows:
![toolbar](https://cloud.githubusercontent.com/assets/881767/24061115/60e34c0e-0b13-11e7-9ee0-28de9734c5ad.png)

instead of "Publish to Azure Docker Container", it should be the same as on the context menu:
"Publish as Docker Container"

**Comment by lenala** [comment]
This is fixed, please verify.

**Comment by bsaby** [comment]
Test passed in artifacts/WindowsAzurePlugin4EJ.95.zip.
