### ISSUE TITLE
[IntelliJ][RunConf] Proper noun should be consistent

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2572]
Build: Develop 923

Repro Steps:
1. Right click on Azure Data Lake Spark Pool cluster, select "Submit Job" and save the config file
2. Right click on one script, create a cosmos spark config file
3. Create a serverless config file and check the remote debug settings

Result:
![image](https://user-images.githubusercontent.com/36756024/50475499-00ba5500-0a00-11e9-8244-fd255eefcc34.png)

![image](https://user-images.githubusercontent.com/36756024/50502267-cbd8ed00-0a55-11e9-856a-ccec584320c4.png)

Expect:
Consider make the noun consistent.

**Comment by jingyanjingyan** [comment]
Verify with Private build 2818

1. Set "Default Spark Application Type" to "Spark on HDInsight", right click on "LogQuery".
Result: In context menu, it is "Create [HDInsight Spark]..."
Expect: Maybe should change to "Create [Spark on HDInsight]..."

2. Right click on a spark on cosmos cluster, click "Submit Job"
Result: Config default title use "[Azure Data Lake Spark]catest"
Expect: Update to "[Spark on Cosmos]"

3. Serverless config is not testable in Private build 2818.

**Comment by konjac** [comment]
#2602

**Comment by wezhang** [comment]
PR #2602 is reverted by #2606

**Comment by v-jiche** [comment]
You can refer to bug  #2514.

Consider if the warning message need to be changed.
1. For airs config
![image](https://user-images.githubusercontent.com/35950097/50585626-d6d4b880-0e6d-11e9-9db5-080f42437eb8.png)
2. For SparkOnADL config
![image](https://user-images.githubusercontent.com/35950097/50585568-907f5980-0e6d-11e9-9fff-459f47b45f2f.png)
3. For HDInsight config
![image](https://user-images.githubusercontent.com/35950097/50585703-2e732400-0e6e-11e9-9b3f-8e36c4b2935b.png)
