### ISSUE TITLE
Link Aris cluster failed but get "link successfully" pop-up window

### ISSUE THREAD

**Issue by t-rufang** [Microsoft/azure-tools-for-java#2574]
build: Develop 926

Repro steps:
1. link a SQL Big Data Cluster. Fill with host, user name and password. Click `OK`
2. `Untrusted Server's Certificate` window pop up. Click `Accept`.
3. pop-up window shows that `You have successfully linked the cluster`. Close the pop-up window
![image](https://user-images.githubusercontent.com/32627233/50483717-f318c580-0a27-11e9-86cd-6334bc003ca6.png)
4.  Error message shows `Authentication failed`. However, we expect the cluster should be successfully linked.
![image](https://user-images.githubusercontent.com/32627233/50483759-24919100-0a28-11e9-9768-3642d901565a.png)

Suggesstion: Update the wording of the pop-up window in step 3.  Remove the sentence `You have successfully linked the cluster`.

**Comment by v-jiche** [comment]
Verified, Fixed.
Build:
azure-toolkit-for-intellij-2018.3.PR.2806.12-29-2018

Modified result:
The sentence **You have successfully linked the cluster** has been removed.
![image](https://user-images.githubusercontent.com/35950097/50534715-a4a71c00-0b38-11e9-9828-78f06df88325.png)
