### ISSUE TITLE
[IntelliJ][RunConf]There should pop a window to let user choose the default spark application type first

### ISSUE THREAD

**Issue by v-xiaocw** [Microsoft/azure-tools-for-java#2577]
Build: develop 928

Repro Steps:
1.Create a new project 
2.Expand the Sample list
3.Double click the "LogQuery"and click local run on the Right-click menu

Result:
Local run failed
![image](https://user-images.githubusercontent.com/43333874/50504310-974b3e00-0a21-11e9-9b70-74befc406edd.png)

Expectation:
![image](https://user-images.githubusercontent.com/43333874/50504388-2f492780-0a22-11e9-8dc5-c03827d945d1.png)
There should pop a window to let user choose the default spark application type first

**Comment by konjac** [comment]
This issue has been addressed by #2696

**Comment by v-xiaocw** [comment]
Fixed with 1021
