### ISSUE TITLE
Could we have a Publish to Docker Container icon?

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#258]
currently the plugins are using the same icon for Publish as Web App and Publish As Docker Container
![toolbar](https://cloud.githubusercontent.com/assets/881767/24061253/eb2fe0ca-0b13-11e7-9f5b-8a2733615ca9.png)

Either redoing both icons or combining our Docker icon with the up arrow used here.

**Comment by martinsawicki** [comment]
new icon in place

**Comment by davidliangze** [comment]
Test passed.

Plugin Version:
Eclipse: WindowsAzurePlugin4EJ.338.04-18-2017
IntelliJ:  azure-toolkit-for-intellij.2017.333.04-18-2017
