### ISSUE TITLE
[IntelliJ] Error '1' when submit with wrong path of ADLS gen1

### ISSUE THREAD

**Issue by v-jiche** [Microsoft/azure-tools-for-java#2587]
Build:
azure-toolkit-for-intellij-2018.3.develop.928.12-28-2018.zip

Repro Steps:
1. Create a HDInsight configuration, set spark2-1adls cluster，enter valid data
2. In upload storage type, select ADLS gen1, and **set wrong path**
3. Save config, remote run
4. Click "Continue anyway"

Result:
![image](https://user-images.githubusercontent.com/35950097/50513172-f1acc480-0a4a-11e9-8578-1702b0942309.png)

**Comment by wezhang** [comment]
Looks like a dup of #2554

**Comment by v-jiche** [comment]
The key is setting wrong path.
The key of bug #2554 is keeping empty path.

**Comment by lcadzy** [comment]
@v-jiche  could you please tell us the wrong path you have filled in.
Since I writes a wrong path ,the result is not the same.
![image](https://user-images.githubusercontent.com/43339305/50534043-519d8b00-0b71-11e9-9b91-9eee89880b66.png)

**Comment by v-jiche** [comment]
Verified. Fixed.
Build:
azure-toolkit-for-intellij-2018.3.develop.954.01-02-2019
![image](https://user-images.githubusercontent.com/35950097/50672983-1832a880-0fd3-11e9-94bc-f64a5297e8c7.png)
