### ISSUE TITLE
Eclipse Neon - [Azure Explorer View] - overflow drop-down feels redundant

### ISSUE THREAD

**Issue by joshuahinds** [Microsoft/azure-tools-for-java#259]
It seems that other views within Eclipse also include the same commands in both the toolbar and the menu, but in this case, it just seems silly because the commands are just the same 3 actions. Is there a good reason to show the commands in both places?

![view-dropdown-menu](https://cloud.githubusercontent.com/assets/4510946/24061307/279e7c24-0b14-11e7-95fb-6c0ac089d9aa.PNG)

**Comment by martinsawicki** [comment]
to reduce the redundancy while all the commands are the same in the dropdown as what we explicitly add to the top toolbar, we can hide the dropdown. in the future, if there are more commands that make sense in the dropdown, but are not important enough to be exposed on the toolbar, then the dropdown could be brought back.

**Comment by lenala** [comment]
Fixed, please verify.

**Comment by bsaby** [comment]
Test passed in artifacts/WindowsAzurePlugin4EJ.108.zip.
