### ISSUE TITLE
[IntelliJ][Linux]Data will not be saved after relaunch config dialog

### ISSUE THREAD

**Issue by v-jiche** [Microsoft/azure-tools-for-java#2598]
Build: 
azure-toolkit-for-intellij-2018.3.develop.943.12-29-2018

Repro Steps:

1. Open one config dialog, click "Remotely Run in Cluster"
2. Set "Job Upload Storage" to "Azure Blog" with valid data, save the config and close.
3. Re-launch the config file, wait to refresh finished
Result:
"Storage account "  "Storage Key" and "Storage Container" display empty.
![image](https://user-images.githubusercontent.com/35950097/50537712-74bd4000-0b5b-11e9-8936-6655d77b3692.png)

Expect:
Save "Storage account "  "Storage Key" and "Storage Container"

**Comment by wezhang** [comment]
Dup #2613
