### ISSUE TITLE
Differentiate the application code file name in customer specified storage account for staging and production slot

### ISSUE THREAD

**Issue by xingzhougmu** [microsoft/azure-tools-for-java#26]
Hi,

This is about **WindowsAzureToolkitForEclipseWithJava** when deploying to azure PaaS cloud service.

We encountered an issue when using the same azure storage account for both azure cloud service staging and production environment.

For Java application, this .war file (customer's application code) is stored at **the storage account specified when you publish your cloud service.** So when you make changes in your code and deploy to the staging environment for testing, the WAR file in your storage account will be updated. If you are using the **SAME storage account for both staging and production environment**, the production environment will be affected. For example, when reboot the role instances in production the application code in production will be updated since production slot will retrieve the WAR file from the configured storage account.

**Question:**
At this moment, we use different storage accounts for staging and production environment to work around this issue. Can we make changes to the name convention when packaging client application code? For example, different name for staging and production; or simply append some GUID to the file name to make it unique??

**Comment by vladimir-shcherbakov** [comment]
Hi @xingzhougmu,
Could you please provide steps to reproduce?

**Comment by xingzhougmu** [comment]
@vladimir-shcherbakov I will send you the reproduce step via email. Thanks for helping on looking at this issue.

**Comment by xingzhougmu** [comment]
@vladimir-shcherbakov The repro steps have been sent to you via email. Please kindly check.

**Comment by vladimir-shcherbakov** [comment]
Thank you.

**Comment by xingzhougmu** [comment]
@vladimir-shcherbakov 
Do we have any update or any plans on this issue? Thanks!

**Comment by vladimir-shcherbakov** [comment]
Hi @xingzhougmu, 
Martin is investigating the issue and he'll return with answers when he is ready.

**Comment by martinsawicki** [comment]
Your "workaround" actually looks like a good practice, better than using the same storage account for both production and staging.

**Comment by xingzhougmu** [comment]
@martinsawicki Thanks for the investigation. Do we have plan to fix this in the SDK?

**Comment by martinsawicki** [comment]
the key issue though is that this would be a new feature, possibly rather risky too, in an area (Cloud Services) which is considered deprecated by Azure and there is no new innovation happening there. So we have not been planning any enhancements to Cloud Service support in the tools anymore either.
Have you considered switching to Azure WebApps, or VM Scale Sets, or Service Fabric?

**Comment by xingzhougmu** [comment]
@martinsawicki thanks for the information. If this is the case, I think customer can take the workaround for classic cloud service. I don't see customer has plan to migrate to service fabric yet.

**Comment by Flanker32** [comment]
Close as the feature has been removed in latest release
