### ISSUE TITLE
Documentation needs to be updated to indicate that only "Eclipse JEE version" is supported

### ISSUE THREAD

**Issue by anuchandy** [Microsoft/azure-tools-for-java#260]
I started with "Eclipse for Java developers" and was unable to see option to create "web app" proj, and later came to know that only "Eclipse JEE version" is supported. Online doc over here https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-eclipse-create-hello-world-web-app needs to be updated with this info.

**Comment by martinsawicki** [comment]
i remember we had this pre-req listed in other tutorials (Cloud Sevices) --- we need Eclipse for JEE as the prereq.

**Comment by rmcmurray** [comment]
Sorry for the delay, I have been OOF.

That being said, the article referenced above already lists that in the pre-reqs; here is the exact line from the article:

"Eclipse IDE for Java EE Developers, Luna or later. This can be downloaded from http://www.eclipse.org/downloads/."
