### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by sqlsolver** [Microsoft/azure-tools-for-java#2601]
IntelliJ build version: 2018.3.2 IU-183.4886.37
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.16.0-2018.3

#### 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).
3
#### 2. What did you like or dislike about Azure Toolkit for IntelliJ?
Seemingly unresolvable problem with app deployment, was working and now:
````Uploading artifact to: /site/wwwroot/webapps/ROOT.war ...
FTP client can't store the artifact, reply code: 229.
````
I have tried restarting the IDE, and logging out and back into Azure in the IDE.
#### 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?
Consistency!

**Comment by wezhang** [comment]
Thanks @sqlsolver !  @andxu , could you help to handle it?

**Comment by sqlsolver** [comment]
I narrowed down the problem to trying to deploy while on a mobile connection. Even after entering the WAN IP as safe, deployment was not successful. This is a limitation but not an issue.
