### ISSUE TITLE
[IntelliJ] Successfully passed when submit with wrong path of ADLS gen1

### ISSUE THREAD

**Issue by v-jiche** [Microsoft/azure-tools-for-java#2608]
Build:
azure-toolkit-for-intellij-2018.3.develop.946.12-30-2018

Note:
The key is adding content after the correct path

Repro Steps:
1. Create a HDInsight configuration, set spark2-1adls cluster，enter valid data
2. In upload storage type, select ADLS gen1, and set wrong path
**adl://devtooltelemetryadls.azuredatalakestore.net/clusters/hdi-root123456**
3. Save config, remote run
4. Click "Continue anyway"

Result:
Submit successfully.
![image](https://user-images.githubusercontent.com/35950097/50581501-2efdc180-0e52-11e9-837f-354dce2b9460.png)

**Comment by lcadzy** [comment]
![image](https://user-images.githubusercontent.com/43339305/50671306-04576880-100c-11e9-87b4-83a438c6c25c.png)
This is by design.If the user has permission for the root path "adl://xx/" then it will create new folder to save the artifact if the folder dosen't exist.

**Comment by v-jiche** [comment]
Got it. It is by design.
If the user has permission for the root path "adl://xx/" then it will create new folder to save the artifact if the folder dosen't exist.
