### ISSUE TITLE
Docker hosts node in Explorer: Refresh should reopen that node

### ISSUE THREAD

**Issue by martinsawicki** [microsoft/azure-tools-for-java#261]
the whole point of doing refresh is so I can see the list inside, so showing the containing "Docker Hosts" node as collapsed after Refresh is not helpful -- Refresh should expand the node.

**Comment by martinsawicki** [comment]
since this is easy to fix in Eclipse, but not IntelliJ, let's just fix in Eclipse.

**Comment by martinsawicki** [comment]
Technically too tricky/risky at this point. May be good to revisit in the future.

**Comment by reyang** [comment]
@aovechki , this is not going to be in the v3.0 release, we need to come up with a systematic solution for managing the tree view state.

**Comment by aovechki** [comment]
assigning to @yaweiw who is looking at the Azure Explorer area all up

**Comment by Flanker32** [comment]
We have deprecated the support for docker host, close this issue.
