### ISSUE TITLE
ACR Explorer -> The tag next button cannot turn to the next page 

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#2617]
Bits: 3.17.0

### Environment:
1. IntelliJ in global environment
2. An ACR with the repository has more than 30 tags

### Steps:
2. Right-click an ACR and choose Open ACR Explorer.
3. Right click the repository to show tags 

### Behavior:
Before: show all tags in the current page and the action button: previous page and next page are disabled.
![image](https://user-images.githubusercontent.com/22470312/50672599-28b74300-1014-11e9-9956-8c5a72328cdc.png)

Now: the tag page has a paging function and the default size is 30. 
**Bug:** The next page button doesn't work, click it cannot turn to the next page.
![image](https://user-images.githubusercontent.com/22470312/50673398-42f32000-1018-11e9-8a2d-7db9452c8088.png)

**Comment by bsaby** [comment]
This issue also repro on Eclipse plugin.
### Environment:
1. Eclipse  2018-12 (4.10.0)
2. Both Global and Azure China environment
3. Bits: dev995

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738814

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
