### ISSUE TITLE
Docker SSH key export misbehaves

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#262]
1. for an already created docker host that had SSH keys created, in Azure Explorer, go to Details for that host, and click Export SSH Keys
2. In file directory the prompt that shows up, select some directory on your PC, other than the default suggested
3. Click Save
RESULT: The prompt briefly disappears and immediately reappears but showing the original default directory location again, ignoring what I specified
EXPECT: Just works
NOTE: If I select my desired location again (2nd time), then it works ok.

**Comment by milismsft** [comment]
fixed; please verify.

**Comment by bsaby** [comment]
Test passed, using azure-toolkit-for-intellij.124.zip.
