### ISSUE TITLE
[IntelliJ][console]Can't start Livy interactive session Console in Aris cluster.

### ISSUE THREAD

**Issue by v-lanjli** [Microsoft/azure-tools-for-java#2629]
Build: Market build

Repro Steps:

1. Create a new project.
2. Configure the remotely run in cluster
3. Click"Tools\Spark Console\Run Spark Livy Interactive Session Console".

Result:
Can't start Livy interactive session.
![image](https://user-images.githubusercontent.com/40199316/50820871-c1c5c100-1368-11e9-8f7c-bad612c7882a.png)

**Comment by wezhang** [comment]
Looks like the Aris's gateway doesn't proxy that session URL.

**Comment by t-rufang** [comment]
This is due to spark session is pending in `UNDEFINED` state. @konjac will help to fix this issue by showing some readable error log.
