### ISSUE TITLE
[IntelliJ] Give users opportunity to fix SSL certficate issue when they run into

### ISSUE THREAD

**Issue by djlan** [Microsoft/azure-tools-for-java#2635]
How about give users option to fix SSL certificate issue when they run into?

Currently, users need to read the document, find the option and check it, which is not going to work:

Maybe add an option here?
![image](https://user-images.githubusercontent.com/26966861/50879053-7537bf80-1414-11e9-91c9-6dd84033f261.png)

Currently it is not intuitive to find the configuration:
![image](https://user-images.githubusercontent.com/26966861/50879412-c09e9d80-1415-11e9-923d-d01f12149be7.png)

**Comment by t-rufang** [comment]
Fixed in #2663
