### ISSUE TITLE
[IntelliJ][serverless][JobTable] Job won't stop when it's successfully ended

### ISSUE THREAD

**Issue by t-rufang** [Microsoft/azure-tools-for-java#2639]
Submit a serverless spark batch job and wait a while. From serverless job list, we find that the job is in 'Ended' state. And we expect the `stop` button should be disabled. However, the `stop` button is still enable and click it you will get a exception telling that the job is successfully finished.

**Comment by t-rufang** [comment]
Fixed in #2682

**Comment by v-lanjli** [comment]
Verified in build 'azure-toolkit-for-intellij-2018.3.develop.979.01-23-2019'. Fixed and closed this issue.
