### ISSUE TITLE
Wrong font on Docker Host details dialog - error

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#264]
See the key vault error message at the bottom of the Docker Host Details dialog -- looks like TNR, but it should be the UI font.

![details](https://cloud.githubusercontent.com/assets/881767/24066032/7b0debfc-0b2c-11e7-9e35-198510b81aa3.png)

**Comment by milismsft** [comment]
Fixed.

**Comment by bsaby** [comment]
Test passed, using azure-toolkit-for-intellij.124.zip.
