### ISSUE TITLE
[IntelliJ][Spark][RunConf] Serverless warning no artifact, when there is no main class

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2644]
Build: private 2641

Repro Steps:
1. Submit serverless spark job from context menu on serverless cosmos account
2. Warning no artifact
![image](https://user-images.githubusercontent.com/36756024/50953041-20468880-14aa-11e9-859a-dcd8a0d62dff.png)
3. Click Edit

Result:
No main class
![image](https://user-images.githubusercontent.com/36756024/50953077-38b6a300-14aa-11e9-8f4e-b8ed3ab56389.png)

**Comment by t-rufang** [comment]
@konjac Hi kun, can you help verify this issue?

**Comment by konjac** [comment]
This issue is not only for cosmos serverless. It is also for cosmos spark.

**Comment by konjac** [comment]
This is introduced by #2586
