### ISSUE TITLE
[IntelliJ] Pops serverless config for the second time from context menu will not populate previous values

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2645]
Build: Private 2641

Repro Steps:
1. Right click on cosmos account under ADLSparkPool then select "Submit serverless spark job"
2. Enter main class, click Apply then close to save the config
3. Right click on cosmos account under ADLSparkPool, select "Submit serverless spark job" then "Edit"

Result:
New config with the same name pops, the main class does not populate.
![image](https://user-images.githubusercontent.com/36756024/50953391-1d986300-14ab-11e9-9f61-d49318b7f287.png)

**Comment by wezhang** [comment]
@jingyanjingyan , is it only for Spark Serverless?

**Comment by konjac** [comment]
I can not repro this. @jingyanjingyan Could you help to verify again?

**Comment by jingyanjingyan** [comment]
Close as not repro
