### ISSUE TITLE
[IntelliJ][Spark][serverless][JobTable] Click x in serverless job window, warning message should not include code

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2646]
Build: Private 2641

Repro Steps:
1. Create a serverless config file, enter invalid main class "ccc"
2. Submit the config file
3. Under ADLSparkPool, right click on ADL account, select "View serverless spark jobs"
4. Refresh to find the new submitted job, it is scheduled
5. Click x

Result:
Warning message includes code
![image](https://user-images.githubusercontent.com/36756024/50955951-5982f680-14b2-11e9-89ae-80cda54af1f9.png)

**Comment by t-rufang** [comment]
@jingyanjingyan Could you double confirm the job state before you kill the job? The table won't refresh itself unless you click refresh button on the top left of the table.

**Comment by t-rufang** [comment]
Not repro
