### ISSUE TITLE
[IntelliJ][Spark][serverless][RunConf] Serverless submission: Warning use spark cluster when config use ADL account

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2647]
Build: Private 2641

Repro Steps:
1. Create a serverless config without ADL account name, save
2. Open project, right click on "LogQuery", click "SparkJobRun"

Result:
Warning message use "cluster" but in config file, it has been change to "ADL account"
![image](https://user-images.githubusercontent.com/36756024/50957988-84237e00-14b7-11e9-9bc5-bc840d38e289.png)

Create serverless config without cluster, start interactive console and continue anyway
![image](https://user-images.githubusercontent.com/36756024/50958529-d6b16a00-14b8-11e9-80ce-6352444ed2c6.png)

**Comment by t-rufang** [comment]
@konjac Hi Kun, can you help verify this issue?
