### ISSUE TITLE
On Docker Host details, would be helpful to see allocated public IP and private IP

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#265]
if the dev plays with the created nodes via SSH, a number of docker commands expect an IP address, not a DNS address. So it would be good to show those in the Details.

**Comment by milismsft** [comment]
Fixed

**Comment by bsaby** [comment]
Test passed in artifacts/azure-toolkit-for-intellij.103.zip.

**Comment by martinsawicki** [comment]
@milismsft - removin INtelliJ tag and fixed, so that we can just track this for Eclipse now.

**Comment by milismsft** [comment]
Fixed; please verify.

**Comment by martinsawicki** [comment]
@bsaby ready for retest on Eclipse side

**Comment by bsaby** [comment]
Test passed.
But the text boxes appear to be editable in the Details dialog, actually they can not be edited. They should be displayed like IntelliJ.
**Eclipse:**
![image](https://cloud.githubusercontent.com/assets/22470312/24693299/7038aa0e-1a0f-11e7-8a11-bc76712d951d.png)
**IntelliJ:**
![image](https://cloud.githubusercontent.com/assets/22470312/24693051/4bcd18cc-1a0e-11e7-9c1e-b3a89076dd52.png)

**Comment by bsaby** [comment]
Test passed, using artifacts/WindowsAzurePlugin4EJ.226.04-05-2017.zip.
