### ISSUE TITLE
[IntelliJ][sample] Context menu of script related to two config file might confuse

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#2658]
Build: Private 2860

Repro Steps:
1. Create an HDInsight config, create a Spark on Cosmos config, and select the "Spark on Cosmos" config
2. Right click on script "LogQuery"

Result:
Context menu use "HDInsight Spark" and "Spark on Cosmos" for local/remote might confuse the user
![image](https://user-images.githubusercontent.com/36756024/51069664-8f6cda00-166e-11e9-80bd-605ce6a04eff.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748143
