### ISSUE TITLE
[IntelliJ]Build our own log console view JComponent

### ISSUE THREAD

**Issue by t-rufang** [microsoft/azure-tools-for-java#2668]
Currently console view is used in `CosmosSparkProvisionDialog` and `AddNewClusterForm` to help show error log. The problem is:
1. There are lots of duplicate codes to implement console view in different class.
2. log to file is not supported in the current implementation.

Therefore, we should implement a common JComponent to handle the error log output in a dialog. What we expect:
1. A common Jcomponent which can be reused any time we want to output log in a dialog
2. The component is hideable
3. Expose method `printLogLine(@NotNull ConsoleViewContentType logLevel, @NotNull String log)` to output log

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748142
