### ISSUE TITLE
[IntelliJ][Spark on ADL] Submit spark on cosmos dialog pops twice

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2669]
Build: Market build

Repro Steps:
0. Create a config file with empty artifact file
1. Right click on spark on cosmos cluster, click "Submit Job"
2. Pops edit/continue anyway dialog, click edit
3. Set right artifact and main class
4. Click "SparkJobRun"

Result:
The config dialog pops again, click "SubmitJobRun" will submit the job then.

**Comment by jingyanjingyan** [comment]
Fix with market build, submit spark on cosmos job then the Master UI will pops up, and the running driver will display.

**Comment by jingyanjingyan** [comment]
close wrong bug, sorry.

**Comment by wezhang** [comment]
@konjac , could you help have a look?

**Comment by konjac** [comment]
This is a behavior by design. The popup dialog should popup the previous saved run config.
