### ISSUE TITLE
Docker host creation dialog: Next disabled after selecting Region

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#267]
(Windows)
1. Start new docker host creation from explorer
2. replace the suggested host name with your own (e.g. mytest1234)
3. with the mouse, without going or clicking anywhere else, click directly on the dropdown arrow in the Region dropdown
4. Select East US
RESULT: Next gets disabled
EXPECT: Next should be enabled

**Comment by milismsft** [comment]
fixed

**Comment by bsaby** [comment]
Test passed in artifacts/azure-toolkit-for-intellij.103.zip.
