### ISSUE TITLE
[IntelliJ][Serverless]Remote run failed with error saying "Read timed out"

### ISSUE THREAD

**Issue by v-xiaocw** [Microsoft/azure-tools-for-java#2684]
Build: azure-toolkit-for-intellij-2018.3.develop.968.01-18-2019

Repro Steps:
1.Set up to PPE environment
2.Create a new project and create a Spark on Cosmos Serverless configuration
3.Click Remote run button 
4.Wait for a long time

Result:
Error:Read timed out
![image](https://user-images.githubusercontent.com/43333874/51460278-d8c4c580-1d0f-11e9-8c7c-1ec1ed15022c.png)

**Comment by t-rufang** [comment]
@v-xiaocw Could you help to paste the error stack trace here? Find `idea.log` file in `Help | Show log in Explorer`.

**Comment by t-rufang** [comment]
Synced offline with @v-xiaocw,  seems that this issue appeared several times in build 968 but hard to repro. I will leave the issue here and we can check if this issue repro on the new build.
