### ISSUE TITLE
[IntelliJ][Serverless]No window pops up when click "View Spark on Cosmos Serverless Jobs"

### ISSUE THREAD

**Issue by v-xiaocw** [Microsoft/azure-tools-for-java#2686]
Build: azure-toolkit-for-intellij-2018.3.develop.968.01-18-2019

Repro Steps:
1.Set up to PPE environment
2.Expand the Azure Data Lake Spark Pool node in Azure Explorer
3.Right click at the cosmos account "sextanscaboalki"
4.Select "View Spark on Cosmos Serverless Jobs"

Result:
No window pops up

**Comment by t-rufang** [comment]
I'll take a look at this

**Comment by t-rufang** [comment]
Fixed in #2682

**Comment by v-lanjli** [comment]
verified in 'azure-toolkit-for-intellij-2018.3.develop.978.01-23-2019', Fixed and Closed this issue.
