### ISSUE TITLE
[IntelliJ][Serverless]Created cluster does not display under the 'sextanscaboalki'

### ISSUE THREAD

**Issue by v-lanjli** [Microsoft/azure-tools-for-java#2687]
**Build:** azure-toolkit-for-intellij-2018.3.develop.968.01-18-2019

**Repro Steps:**
1.Set up to PPE environment
2.Expand the Azure Data Lake Spark Pool node in Azure Explorer
3.Right click at the cosmos account "sextanscaboalki"
4.Select "Provision Spark Cluster"
5. After configuring the relevant configuration, click the OK button
6. Check the "sextanscaboalki" node in Azure Explorer

**Result:**
There is no Cluster in it.
![image](https://user-images.githubusercontent.com/40199316/51466302-cf396d00-1da4-11e9-8169-71aeaf0966cb.png)

**Comment by t-rufang** [comment]
I'll take a look at this issue.

**Comment by t-rufang** [comment]
Not repro

**Comment by v-lanjli** [comment]
Closed~
