### ISSUE TITLE
[IntelliJ][Spark][serverless][RunConf] Serverless submission: Change Configuration Settings box is missing

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#2689]
Build:
azure-toolkit-for-intellij-2018.3.develop.968.01-18-2019

Repro Steps:
1. Create a serverless config without ADL account name, save
2. Open project, right click on "LogQuery", click "SparkJobRun"

Result:
The Edit Configuration box pops up. The Change Configuration Settings box is missing.
![image](https://user-images.githubusercontent.com/35950097/51467438-7518b780-1d64-11e9-9a05-7fa8926ccecc.png)

Expectation:
Before the Edit Configuration box pops up, the Change Configuration Settings box should be there.
![image](https://user-images.githubusercontent.com/35950097/51467715-1e5fad80-1d65-11e9-8711-1de9edec48de.png)

**Comment by t-rufang** [comment]
Hi @konjac, could you help to take a look at this issue?

**Comment by jingyanjingyan** [comment]
The behavior is different for scenarios in the summary.xlsx, we need confirm the design before deal with this issue. Thanks.
[summary.xlsx](https://github.com/Microsoft/azure-tools-for-java/files/3011351/summary.xlsx)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748141
