### ISSUE TITLE
IntelliJ forgets my credentials even if using Service Principal auth file

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#269]
1. Login using an Automated option with an authfile
2. Close IJ
3. Restart IJ

RESULT: you're signed out
EXPECT: signed in

**Comment by vladimir-shcherbakov** [comment]
For some reason AzurePlugin::initComponent() starts later than AuthMethodManager constructor. So AuthMethodManager  reads default settings file that is empty.

**Comment by bsaby** [comment]
Test passed in artifacts/azure-toolkit-for-intellij.103.zip.
Login using an Automated option with an auth file, restart IJ still signed in.
