### ISSUE TITLE
[IntelliJ][Conf][ADL] Submit job with invalid value will not pops edit window

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2693]
Build: Develop 968

Repro Steps:
1. Right click on Spark on Cosmos cluster, click "Submit Job"
2. Keep the main class empty, submit

Result:
Submit directly

Expect:
Pops edit/continue window

**Comment by wezhang** [comment]
@konjac , `main class` is not required for any interactive sessions

**Comment by jingyanjingyan** [comment]
With build develop 1005, it will pops a window says invalid main class

**Comment by jingyanjingyan** [comment]
#2831 
Keep for 2831 fix.

**Comment by jingyanjingyan** [comment]
Fix in dev 1022
