### ISSUE TITLE
[IntelliJ][Mac]"Yes" and "No" Button is not centered in Azure Sign Out dialog.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#2695]
**Build:** azure-toolkit-for-intellij-2018.3.develop.968.01-18-2019
**OS:** Mac

**Repro Steps:**
1. Make sure your Azure account is logged in.
2. Click "Sign Out" button in Azure Explorer.

**Result:**
"Yes" and "No" Button is not centered in Azure Sign Out dialog.

**Expect:** The position of the button should be centered.
![image](https://user-images.githubusercontent.com/40199316/51514311-1e85a900-1e4a-11e9-9ce0-e78a12c4008c.png)

**Comment by andxu** [comment]
It is displayed right at windows, need to verify on mac tomorrow.

![image](https://user-images.githubusercontent.com/17075863/83765515-d87f5d00-a6ad-11ea-9b66-ff8ae5908c7b.png)

**Comment by ZhengJun003** [comment]
It is not centered in Azure Sign Out dialog on mac

Azure toolkits for intellij 3.37.0
![image](https://user-images.githubusercontent.com/41051257/83828041-52493200-a712-11ea-9a7f-467dd7df1442.png)

![image](https://user-images.githubusercontent.com/41051257/83828181-a522e980-a712-11ea-9fbb-7455d65b78cc.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738838
