### ISSUE TITLE
[IntelliJ][RunConf][Spark on HDInsight][PPE Envirenment]Azure Blob storage account for linked spark22blobhdi cannot load out container

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#2699]
Build: azure-toolkit-for-intellij-2018.3.develop.972.01-22-2019
 Repro Steps:
1.Set up to PPE environment
2.Link a cluster: spark22blobhdi 
3.Create a new HDInsight configuration:
Fill in the "Storage Type"" Storage Account" and "Storage Key"
4.Click the "Refresh"button at the right of the "Storage Container"
Result:
Cannot load out container
![image](https://user-images.githubusercontent.com/43333874/51525156-8d301b80-1de4-11e9-9fd3-7683e90ff276.png)

**Comment by t-rufang** [comment]
When you log in an Azure account of **PPE environment**, you are not suppose to link a cluster in **Production environment**. Won't fix this issue.
