### ISSUE TITLE
Multiple "Refresh" when refreshing "Azure" node several times do not disappear

### ISSUE THREAD

**Issue by lenala** [Microsoft/azure-tools-for-java#270]
When signed in, right click on the "Azure" node and select "refresh". After clicking multiple times when not allowing refresh to finish:
![image](https://cloud.githubusercontent.com/assets/6208231/24116455/19a9aaf6-0d64-11e7-829d-a65a930b972b.png)

**Comment by martinsawicki** [comment]
not high pri

**Comment by lenala** [comment]
Fixed by @look4pku in his PR https://github.com/voidfunction/azure-tools-for-java-private/pull/7, I integrated his changes. Please verify.

**Comment by bsaby** [comment]
Test passed, using artifacts/WindowsAzurePlugin4EJ.319.04-17-2017.zip.
