### ISSUE TITLE
[IntelliJ][Prod Envirenment]When the storage account is set to ADLs Gen 1, the remote run will have a long wait time for the results to occur.

### ISSUE THREAD

**Issue by v-xiaocw** [Microsoft/azure-tools-for-java#2709]
Build: azure-toolkit-for-intellij-2018.3.PR.2939.01-23-2019

Repro Steps:
1.Create a Spark on HDInsight configuration
2. Select the ADLS cluster:spark2-1adls
3.Fill in the information of Job Upload Storage 
4.Click the remotely run button 
5.Wait for a long time

Result:
 IntelliJ hang on for long time
![image](https://user-images.githubusercontent.com/43333874/51593295-b1543100-1ea6-11e9-8b6e-a93e90016ae0.png)

**Comment by t-rufang** [comment]
With #2836, this should not happen again. @v-xiaocw, could you help to verify this?

**Comment by v-xiaocw** [comment]
Fixed in azuretoolkitforintellij/v3.19.0/azure-toolkit-for-intellij-2018.3.90.03-07-2019.zip
