### ISSUE TITLE
[IntellJ][Logo]The logo should update to new design

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#2710]
Build: 978

Repro Steps:
1. Make sure no config file
2. Set the default spark type to None
3. Start local console

Result:
The HDInsight logo use old design
![image](https://user-images.githubusercontent.com/36756024/51591376-bafc8980-1ee4-11e9-99c2-936e2adf53b9.png)

Expect:
Use the new design

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748140
