### ISSUE TITLE
Prompt by right-clicking on the "Azure" and selecting "Sign In" instead of "Manage Subscriptions"

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#272]
Both Eclipse and IntelliJ, click "Create Storage Account "before sign-in, prompt by right-clicking on the "Azure" and selecting "Sign In" instead of "Manage Subscriptions"
In addition, in Eclipse  click the "Create VM" before sign-in should also have a sign-in prompt.
![image](https://cloud.githubusercontent.com/assets/22470312/24180544/6e07f412-0ef0-11e7-9a3d-fd08dd4f6bf1.png)
![image](https://cloud.githubusercontent.com/assets/22470312/24180578/9cbc9f2e-0ef0-11e7-97d3-2628f58c145e.png)

**Comment by martinsawicki** [comment]
yes, when not signed in, the user should just be taken to the sign in dialog just like we recently did for WebApp publish.

**Comment by lenala** [comment]
This is done, please verify. Implemented the same behavior as for WebApp publish - if not signed in, user will be taken to Sign In dialog.

**Comment by bsaby** [comment]
Test passed. Build used:
WindowsAzurePlugin4EJ.213.04-04-2017.zip
azure-toolkit-for-intellij.2017.209.04-04-2017.zip
