### ISSUE TITLE
[intelliJ]Wrong error message when local run with a configuration including a named VM options.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#2723]
Build:
azure-toolkit-for-intellij-2018.3.88.01-24-2019

Repro Steps:
1. Open Run/Debug configurations.
2. Create a HDInsight configuration, choose the right main class, name the VM options.
3. Local run the script file.
![image](https://user-images.githubusercontent.com/35950097/51739955-a389e180-2047-11e9-9c14-eec898087165.png)

Result:
Get wrong error message. The main class name is not correct.
![image](https://user-images.githubusercontent.com/35950097/51740121-04191e80-2048-11e9-8108-2bcce86eca90.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748139
