### ISSUE TITLE
[intelliJ]Main class name changes when remote run LogQuery from context menu.

### ISSUE THREAD

**Issue by v-jiche** [Microsoft/azure-tools-for-java#2724]
Build:
azure-toolkit-for-intellij-2018.3.88.01-24-2019

Repro Steps:
1. Open Run/Debug Configurations.
2. Create a Cosmos configuration, Choose Remotely in Cluster.
3. Set a wrong main class name like "abc" or keep it empty. 
![image](https://user-images.githubusercontent.com/35950097/51746192-1e5bf800-205a-11e9-8177-3ebf9c46b1f4.png)
4. Choose a spark cluster.
5. Right click LogQuery to remote run it.
6. When Edit Configuration windows pops up, close it.
![image](https://user-images.githubusercontent.com/35950097/51746299-7c88db00-205a-11e9-8673-2d2e328726e0.png)
7. Open Run/Debug Configurations, check the main class name in Remotely in  Cluster.

Result:
The main class name changes into sample.LogQuery.
![image](https://user-images.githubusercontent.com/35950097/51746219-316ec800-205a-11e9-9168-dee840a622c3.png)

**Comment by wezhang** [comment]
May the issue is N/A for current design.

**Comment by v-jiche** [comment]
Not repro.
The design for configuration window has been changed.
Build: azure-toolkit-for-intellij-2019.1.develop.1087.04-15-2019
