### ISSUE TITLE
[intelliJ]Unreasonable display when remotely run LogQuery from context menue

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#2725]
Build:
azure-toolkit-for-intellij-2018.3.88.01-24-2019

Repro Steps:
1. Open Run/Debug Configurations.
2. Create a cosmos configuration.
3. Choose Locally  Run, keep the Job Main Class empty.
4. Choose Remotely Run in Cluster, do some settings to make it completely correct.
5. Right click LogQuery to remotely run it.

Result:
Edit configuration window pops up. The part of Locally Run is displayed.
the local tab does not have any warning message to indicate what need to update.
![image](https://user-images.githubusercontent.com/35950097/51747464-709f1800-205e-11e9-871d-488304b3ce4c.png)

**Comment by t-rufang** [comment]
We fixed this issue by moving `Main Class Name` to a common area for local run tab and remote run tab.
![image](https://user-images.githubusercontent.com/32627233/85936809-9d7cec00-b930-11ea-8761-bae5ffa9a702.png)
