### ISSUE TITLE
[intelliJ]Configuration name automatically changes When reopen Run/Debug Configurations.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#2732]
Build:
azure-toolkit-for-intellij-2018.3.88.01-24-2019.zip

Repro Steps:
1. Open Run/Debug Configurations.
2. Create a Cosmos configuration.
3. In the part of Locally Run, Choose LogQuery as Job main class.**(Please do not tab away)**
![image](https://user-images.githubusercontent.com/35950097/51836865-91cf6500-22f9-11e9-8b38-c1548ccad8d8.png)
4. Click OK button to save the configuration.
Result:
The configuration name is saved as Unamed.
![image](https://user-images.githubusercontent.com/35950097/51836872-9f84ea80-22f9-11e9-91c0-dec5c545285a.png)
5. Reopen Run/Debug Configurations.
6. Tab away or do some modifications like choose clusters in Remotely Run in Cluster.
Result:
The configuration name changes to [Spark on Cosmos] LogQuery.
![image](https://user-images.githubusercontent.com/35950097/51837012-0c988000-22fa-11e9-8058-8700ceb12850.png)
7. Modify the Job main Class in Locally Run.
Result:
The configuration name would change with it.
![image](https://user-images.githubusercontent.com/35950097/51837172-76b12500-22fa-11e9-891c-0ebd85d75d16.png)

Expectation:
The configuration name should not change without the user's knowledge.

Repro Steps:
1. Open Run/Debug Configurations.
2. Create a Cosmos configuration.
3. Change the configuration name as ccc, choose LogQuery as Job main Class in the part of Locally Run.
![image](https://user-images.githubusercontent.com/35950097/51837551-9c8af980-22fb-11e9-8b56-45bc42755e16.png)
4. Click OK button to save the configuration.
Result:
The configuration name is saved as ccc.
![image](https://user-images.githubusercontent.com/35950097/51837612-cb08d480-22fb-11e9-9665-b4cfc0e0ee7e.png)
5. Reopen Run/Debug Configurations.
6. Tab away or do some modifications like choose clusters in Remotely Run in Cluster.
Result:
The configuration name is still ccc.
7. Modify the Job main Class in Locally Run.
Result:
The configuration name is still ccc and it would not change anyway.

Note:
1. If the configuration name is artificially modified, it would not change with the change of Job main Class in Locally Run.
2. If user do not modify the configuration name, it would change with the change of Job main Class in Locally Run.
3. In the situation of 2, If users create more Cosmos configurations, in which the Job main Class is LogQuery, then the configurations can not be saved.
![image](https://user-images.githubusercontent.com/35950097/51838207-90a03700-22fd-11e9-9930-c87e02a80145.png)
![image](https://user-images.githubusercontent.com/35950097/51838238-9c8bf900-22fd-11e9-87cc-1d01d49e7418.png)

**Comment by wezhang** [comment]
@konjac could you help to have a look?

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748138
