### ISSUE TITLE
[intelliJ][RunConf]Unreasonable warning about Spark clusters in Run/Debug configurations when Azure sign out

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#2736]
Build:
azure-toolkit-for-intellij-2018.3.88.01-24-2019.zip

Repro Steps:
1. Open Azure Explorer.
2. Azure sign out.
3. Open Run/Debug Configurations.
4. Add a HDInsight configuration.
5. Choose Remotely Run in Cluster.

Result:
The warning about Spark clusters is as follows.
![image](https://user-images.githubusercontent.com/35950097/51889360-4799c280-2391-11e9-806b-d39ebf61a41b.png)

Expection:
1. In the state of sign out, linked clusters can be listed. So warning that can't list cluster is not right.
![image](https://user-images.githubusercontent.com/35950097/51890181-571a0b00-2393-11e9-9632-8b6ab81712db.png)
2. The login prompt should be changed to sign in. In Azure Explorer, it is used with signing in.
![image](https://user-images.githubusercontent.com/35950097/51890333-b546ee00-2393-11e9-9fa4-41b19e0d199f.png)

**Comment by v-jiche** [comment]
You can refer to bug #2737

**Comment by t-rufang** [comment]
Wording.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748137
