### ISSUE TITLE
[intelliJ][RunConf]Unreasonable warning about Spark clusters in Cosmos configurations when Azure sign out

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#2737]
Build:
azure-toolkit-for-intellij-2018.3.88.01-24-2019.zip

Repro Steps:

1. Open Azure Explorer.
2. Azure sign out.
3. Open Run/Debug Configurations.
4. Add a SQL Server configuration.
5. Choose Remotely Run in Cluster.

Result:
The warning about Spark clusters are as follows.
![image](https://user-images.githubusercontent.com/35950097/51890984-99444c00-2395-11e9-91ee-20338e7a5678.png)

Note:
Listing Spark clusters in SQL Server Configuration do not depend on Azure sign in.

**Comment by v-jiche** [comment]
You can refer to bug #2736

**Comment by t-rufang** [comment]
Wording.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748136
