### ISSUE TITLE
[intelliJ]Edit Configuration window appears earlier than Change Configuration Settings window

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#2741]
Build:
azure-toolkit-for-intellij-2018.3.88.01-24-2019.zip

Repro Steps:
1. Open Run/Debug configurations.
2. Add a HDInsight configuration.
3. Choose Locally Run.
4. Leave the Job main Class empty.
5. Click OK button to save configuration.
6. Click the icon to Local Run.

Result:
Edit Configuration window appears. Click Run button to continue. Change Configuration settings window appears.
![image](https://user-images.githubusercontent.com/35950097/51974120-18f61780-2477-11e9-92d6-11b6f36810c9.png)
![image](https://user-images.githubusercontent.com/35950097/51974142-23b0ac80-2477-11e9-9d3f-c2d99851c390.png)

**Comment by t-rufang** [comment]
The design has changed and the bug is fixed now. There is an error message "Main Class Name could not be null" now.
![image](https://user-images.githubusercontent.com/32627233/85937017-49730700-b932-11ea-9236-2d49a6016637.png)

**Comment by t-rufang** [comment]
Still repro

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748135
