### ISSUE TITLE
Wrong closing tags in plugin.xml

### ISSUE THREAD

**Issue by Eskibear** [microsoft/azure-tools-for-java#2743]
Wrong closing tag `<ul>` in versions between 3.4.0 and 3.9.0

https://github.com/Microsoft/azure-tools-for-java/blob/312aaece4bb80e97482741d1c49fa0b8c7bac87e/PluginsAndFeatures/azure-toolkit-for-intellij/resources/META-INF/plugin.xml#L241-L276

**Comment by Flanker32** [comment]
Issue has been fixed in latest release
