### ISSUE TITLE
[Bug] IntelliJ IDEA plugin breaks JSON file editor

### ISSUE THREAD

**Issue by pavolgolias** [microsoft/azure-tools-for-java#2748]
Version: 3.18.0-2018.3

OS: Win 10
Repro steps: Activate plugin in IntelliJ IDEA and open JSON file in IDEA editor.

Result: Editor is broken, it is unable to write or edit something in the opened JSON file. Every colon I write is deleted itself, it is unable to add new line to JSON or format JSON. Also, menu in IDEA is not working properly until I close JSON file. It seems like IDEA is non-stop indexing something in JSON file. After I deactivated Azure plugin, everything works perfectly fine.

**Comment by wezhang** [comment]
Thanks @pavolgolias ! We'll check that.

**Comment by andxu** [comment]
@pavolgolias Thanks for submitting this issue. Could you please reproduce it again and tell us the result (since we have several releases last year). I tested it , but cannot find anything wrong with json on intellij version 2020.1

**Comment by pavolgolias** [comment]
@andxu I am not able to reproduce it again as it was reported 15 months ago and I used older version of IntelliJ IDEA. Also, I no longer use this plugin. Anyway I suppose new releases of this plugin and IntelliJ IDEA resolved this issue.
