### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by danielrym** [microsoft/azure-tools-for-java#2753]
IntelliJ build version: 2018.2 IC-182.3684.101
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.9.0-2018.2

# 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent). 
9

# 2. What did you like or dislike about Azure Toolkit for IntelliJ? 
- local debugging set-up is more complicated than necessary; it would be great if there were an installer taking care of package + java + winutils.exe + provide option for auto-set up debug cluster if one is not available; 
each step is easy, but getting entire environment set-up for new user is tedious especially when they don't have previous experience with Spark and Azure and have to be handhold  thru entire process

# 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?

**Comment by t-rufang** [comment]
Thank you for the feedback, we would like to understand more on your user scenarios and your pain points around your local environment set-up. Happy to have a call with you. Please let us know your preferred date and contact information.

**Comment by jingyanjingyan** [comment]
Thank you for your feedback, please reopen if you still need help.
