### ISSUE TITLE
[IntelliJ][Spark23-gen2-yan]Remote run failed with linked cluster.

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#2755]
Build: Maket Build 

Repro steps:
1.Link the cluster:spark23-gen2-yan 
2.Create a new config and select "Use ADLS gen1 to upload"as storage type 
3.Fill in the ADLS Root Path
4.Click apply and OK
5.Click the "Remote Run" button

Result:
Waiting for a moment and failed:
 
![image](https://user-images.githubusercontent.com/43333874/52850891-8a65d500-30c9-11e9-8ff9-da4898fb38e2.png)
Package and deploy the job to Spark cluster
LOG: SLF4J: Class path contains multiple SLF4J bindings.
LOG: SLF4J: Found binding in [jar:file:/usr/hdp/2.6.5.3005-27/spark2/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
LOG: SLF4J: Found binding in [jar:file:/usr/hdp/2.6.5.3005-27/spark_llap/spark-llap-assembly-1.0.0.2.6.5.3005-27.jar!/org/slf4j/impl/StaticLoggerBinder.class]
LOG: SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
LOG: SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
LOG: Warning: Master yarn-cluster is deprecated since 2.0. Please use master "yarn" with specified deploy mode instead.
LOG: 19/02/15 10:05:24 INFO MetricsConfig: loaded properties from hadoop-metrics2-azure-file-system.properties
LOG: 19/02/15 10:05:24 INFO WasbAzureIaasSink: Init starting.
LOG: 19/02/15 10:05:24 INFO AzureIaasSink: Init starting. Initializing MdsLogger.
LOG: 19/02/15 10:05:24 INFO AzureIaasSink: Init completed.
LOG: 19/02/15 10:05:24 INFO WasbAzureIaasSink: Init completed.
LOG: 19/02/15 10:05:24 INFO MetricsSinkAdapter: Sink azurefs2 started
LOG: 19/02/15 10:05:24 INFO MetricsSystemImpl: Scheduled snapshot period at 60 second(s).
LOG: 19/02/15 10:05:24 INFO MetricsSystemImpl: azure-file-system metrics system started
LOG: 19/02/15 10:05:24 INFO RequestHedgingRMFailoverProxyProvider: Looking for the active RM in [rm1, rm2]...
LOG: 19/02/15 10:05:25 INFO RequestHedgingRMFailoverProxyProvider: Found active RM [rm2]
LOG: 19/02/15 10:05:25 INFO Client: Requesting a new application from cluster with 2 NodeManagers
LOG: 19/02/15 10:05:25 INFO Client: Verifying our application has not requested more than the maximum memory capability of the cluster (51200 MB per container)
LOG: 19/02/15 10:05:25 INFO Client: Will allocate AM container, with 4480 MB memory including 384 MB overhead
LOG: 19/02/15 10:05:25 INFO Client: Setting up container launch context for our AM
LOG: 19/02/15 10:05:25 INFO Client: Setting up the launch environment for our AM container
LOG: 19/02/15 10:05:25 INFO Client: Preparing resources for our AM container
LOG: 19/02/15 10:05:27 INFO Client: Deleted staging directory wasb://spark23-gen2-yan-2019-01-24t06-38-39-992z@fnanesrpdiag.blob.core.windows.net/user/livy/.sparkStaging/application_1548312616927_0157
LOG: Exception in thread "main" java.io.IOException: Password fs.adl.oauth2.client.id not found
LOG:         at org.apache.hadoop.fs.adl.AdlFileSystem.getPasswordString(AdlFileSystem.java:936)
LOG:         at org.apache.hadoop.fs.adl.AdlFileSystem.getConfCredentialBasedTokenProvider(AdlFileSystem.java:268)
LOG:         at org.apache.hadoop.fs.adl.AdlFileSystem.getAccessTokenProvider(AdlFileSystem.java:253)
LOG:         at org.apache.hadoop.fs.adl.AdlFileSystem.initialize(AdlFileSystem.java:159)
LOG:         at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2796)
LOG:         at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:99)
LOG:         at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2830)
LOG:         at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2812)
LOG:         at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:390)
LOG:         at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
LOG:         at org.apache.spark.deploy.yarn.Client.copyFileToRemote(Client.scala:351)
LOG:         at org.apache.spark.deploy.yarn.Client.org$apache$spark$deploy$yarn$Client$$distribute$1(Client.scala:478)
LOG:         at org.apache.spark.deploy.yarn.Client$$anonfun$prepareLocalResources$12.apply(Client.scala:590)
LOG:         at org.apache.spark.deploy.yarn.Client$$anonfun$prepareLocalResources$12.apply(Client.scala:589)
LOG:         at scala.Option.foreach(Option.scala:257)
LOG:         at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:169)
LOG:         at org.apache.spark.deploy.yarn.Client.run(Client.scala:1217)
LOG:         at org.apache.spark.deploy.yarn.YarnClusterApplication.start(Client.scala:1585)
LOG:         at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:907)
LOG:         at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
LOG:         at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
LOG:         at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
LOG:         at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
LOG: 19/02/15 10:05:27 INFO ShutdownHookManager: Shutdown hook called
LOG: 19/02/15 10:05:27 INFO ShutdownHookManager: Deleting directory /tmp/spark-c1010365-87f5-4885-97bf-743186809cef
LOG: 19/02/15 10:05:27 INFO MetricsSystemImpl: Stopping azure-file-system metrics system...
LOG: 19/02/15 10:05:27 INFO MetricsSinkAdapter: azurefs2 thread interrupted.
LOG: 19/02/15 10:05:27 INFO MetricsSystemImpl: azure-file-system metrics system stopped.
LOG: 19/02/15 10:05:27 INFO MetricsSystemImpl: azure-file-system metrics system shutdown complete.
ERROR: The Spark job failed to start due to 19/02/15 10:05:27 INFO ShutdownHookManager: Shutdown hook called
19/02/15 10:05:27 INFO ShutdownHookManager: Deleting directory /tmp/spark-c1010365-87f5-4885-97bf-743186809cef
19/02/15 10:05:27 INFO MetricsSystemImpl: Stopping azure-file-system metrics system...
19/02/15 10:05:27 INFO MetricsSinkAdapter: azurefs2 thread interrupted.
19/02/15 10:05:27 INFO MetricsSystemImpl: azure-file-system metrics system stopped.
19/02/15 10:05:27 INFO MetricsSystemImpl: azure-file-system metrics system shutdown complete.
 
stderr:
 
YARN Diagnostics:
java.lang.Exception: No YARN application is found with tag livy-batch-112-4pwnozac in 120 seconds. Please check your cluster status, it is may be very busy.
org.apache.livy.utils.SparkYarnApp.org$apache$livy$utils$SparkYarnApp$$getAppIdFromTag(SparkYarnApp.scala:182) org.apache.livy.utils.SparkYarnApp$$anonfun$1$$anonfun$4.apply(SparkYarnApp.scala:239) org.apache.livy.utils.SparkYarnApp$$anonfun$1$$anonfun$4.apply(SparkYarnApp.scala:236) scala.Option.getOrElse(Option.scala:120) org.apache.livy.utils.SparkYarnApp$$anonfun$1.apply$mcV$sp(SparkYarnApp.scala:236) org.apache.livy.Utils$$anon$1.run(Utils.scala:97)

**Comment by lcadzy** [comment]
Since we don't know the default storage type for a linked cluster ,so provides both adls and blob storage types.This cluster default storage type is blob, please choose blob storage type to run job.

**Comment by jingyanjingyan** [comment]
@lcadzy Should we give out useful information when choosing the wrong storage type after submission?

**Comment by lcadzy** [comment]
#3075
#3074

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748134
