### ISSUE TITLE
intellij: web.config overwritten by app debug preparation

### ISSUE THREAD

**Issue by syr** [microsoft/azure-tools-for-java#276]
When preparing a Web App for debugging by azure tools for intellij, an existing web.config file is overwritten unasked/without warning.
In our case that's a big one, as we use "Dspring.profiles.active=myconfig" in CATALINA_OPTS to define which configuration should be used to run the application.  If this attribute is missing it starts in default config. context.
This profile controls for example which database should be used which could lead to data loss if misconfigured.

**Comment by vladimir-shcherbakov** [comment]
@syr 
Could you please share your web.config or at least the options that were modified.

**Comment by syr** [comment]
Looks/Looked like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <handlers>
            <add name="httpPlatformHandler" path="*" verb="*" 
                 modules="httpPlatformHandler" resourceType="Unspecified" />
        </handlers>
        <httpPlatform stdoutLogEnabled="false">
	        <environmentVariables>
		        <environmentVariable name="CATALINA_OPTS" value="-Xms512M -Xmx512M -DantiResourceLocking=true -Dspring.profiles.active=myProfile" />
	        </environmentVariables>
	    </httpPlatform>
    </system.webServer>
</configuration>
```

After debug preparation "<environmentVariable name="CATALINA_OPTS" value="-Xms512M -Xmx512M -DantiResourceLocking=true -Dspring.profiles.active=myProfile" />" was replaced by 
<environmentVariable name="CATALINA_OPTS" value="-Dport.http=%HTTP_PLATFORM_PORT%"/>

**Comment by martinsawicki** [comment]
the new re-implementation of the debugging feature in v3 will take a less aggressive approach to setting up remoote debugging, but will require more menual setup on the user's side.
@vladimir-shcherbakov parking this on your plate as you work through the rework.

**Comment by martinsawicki** [comment]
after investigating in depth, we see that Azure WebApps currently do not provide sufficient info and control to enable remote debugging to be configured reliably and predictably from an IDE (i.e. purely programmatically). Therefore this feature is removed from v3, and users can fall back on the manual setup as described here: https://github.com/Azure/azure-websites-java-remote-debugging

We will continue working with the needed teams to attempt to add enough functionality to the webApp service to be able to configure it programmatically in a reliable way.

For now, parking this issue on @reyang for future exploration.

**Comment by Flanker32** [comment]
As we have removed the remote debugging feature for web apps, close this issue.
