### ISSUE TITLE
[IntelliJ][Serverless]Submit to pops edit dialog for the second time, value do not populated

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2760]
Build: Release build at 2/18/2019

Repro Steps:
1. Set PPE environment with a serverless config file
2. Sign in
3. Pops "Submit Spark on Cosmos Serverless Job" on the account context menu
4. Enter valid data, click Apply then close
5. Pops "Submit Spark on Cosmos Serverless Job" again

Result:
It is a new config file, the previous data do not populate

Expect:
In spark on cosmos, the data will be populated based on the config name, how about the serverless?

**Comment by t-rufang** [comment]
@konjac Could you help to take a look at this issue?
