### ISSUE TITLE
[MAC]There is no response when I do some operations related to azure

### ISSUE THREAD

**Issue by sallyur** [Microsoft/azure-tools-for-java#2769]
### Environment:
1. OS: Mac
2. IDE: Eclipse IDE for Enterprise Java Developers
3. Build: 993

### Steps and result: 
1. There is no response when I click tools - azure - sign in
2. There is no response when I click the show Azure explorer button in the toolbar
![image](https://user-images.githubusercontent.com/28860891/53462630-73d35c80-3a7f-11e9-9bac-17ad940d1bf5.png)
3. It can open  Azure explorer when I click Window - show view - other - Azure explorer, but there is no response when I right click Azure - sign in

**Comment by zmssp** [comment]
I have a try and can login in mac

**Comment by zmssp** [comment]
![screen](https://user-images.githubusercontent.com/7624690/53465522-38d62680-3a89-11e9-9f42-8d1ff688b590.gif)

**Comment by sallyur** [comment]
I change a mac machine with JDK 8, it works fine. 
It dosen't work with mac in the jdk11 environment.

**Comment by zmssp** [comment]
For the JDK11 problem, we should do some investigation on it. Then we can decide whether or not, or how to solve it.

**Comment by iamthewall** [comment]
Hi! I got the same problem for 3 days. Thank god I found this thread. Azure plugin is not working with Zulu11. It basically locks the functionality of most of the buttons on the IDE. The login didn't work. I changed to Zulu8 and it is working now.

**Comment by alanamircruz** [comment]
[WIN][Eclipse][JDK11] Same issue
Hi everyone,

Following this thread I attach here an exception thrown while trying to Sign-In into Azure using Eclipse + JDK11 + Win 10.

![Exception_JDK11](https://user-images.githubusercontent.com/14240398/55065930-09f9a300-507d-11e9-8f95-ac430160f6f1.png)

Hope you guys can fix this one soon, thanks and regards.

**Comment by bsaby** [comment]
Configurations: 
```
1. Bits: develop: 1072
2. OS: WIndows10/Mac/Ubuntu
3. Eclipse: 2019-03
3. JDK: Oracle jdk 11
```

The test passed. Plugin works.
