### ISSUE TITLE
[IntelliJ][Console] Launch local interactive console for the first time take times

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2771]
Build: dev991

Repro Steps:
1. Create a new project
2. Set default spark type to "Spark on HDInsight"
3. Start local interactive console

Result:
It take times without any information
Then pops the message below. Should we provide a link for the document?
![image](https://user-images.githubusercontent.com/36756024/53466692-fe4d9900-3a4a-11e9-8a9a-c150d2323727.png)

**Comment by wezhang** [comment]
@jingyanjingyan , is it still reproducible?

**Comment by jingyanjingyan** [comment]
Not Repro in Dev 1094
