### ISSUE TITLE
Eclipse HDInsight plugin miss icons

### ISSUE THREAD

**Issue by zmssp** [Microsoft/azure-tools-for-java#2772]
Some icons exists in Intellij plugin but do not sync to eclipse. For example, "HdExplorer_light_16x.png" and "HdExplorer_dark_16x.png".
For lack of these icons, when you visit the azure explorer, it may throw some exceptions.
We plan to release eclipse plugin next week. So please add these missing icons asap.

![image](https://user-images.githubusercontent.com/7624690/53468287-84da9880-3a94-11e9-8097-aeef509086c8.png)

**Comment by wezhang** [comment]
@zmssp , did you find the issue from build bits or just development run/debug?

**Comment by jingyanjingyan** [comment]
#2784

**Comment by zmssp** [comment]
Verified with build 1005, close the issue
