### ISSUE TITLE
[Mac]Can't delete the app settings completely in create app service page

### ISSUE THREAD

**Issue by sallyur** [Microsoft/azure-tools-for-java#2776]
### Environment
1. OS: Mac
2. IDE: Eclipse IDE for Enterprise Java Developers 2018-12
3. JDK: 1.8.0_191
4. Build: 994

### Steps:
1. Right click project and select Azure -> publish as Azure web app
2. Select create new
3. Click new an app settings
4. Edit the key and keep the states of value selected but key is not selected as below:
![image](https://user-images.githubusercontent.com/28860891/53479455-14437400-3ab4-11e9-9141-2180e64357db.png)
5. Click delete

### Result:
The key can't be deleted as below:
![image](https://user-images.githubusercontent.com/28860891/53479622-65ebfe80-3ab4-11e9-9255-0a037add9387.png)
If I delete the key manually, then click new, the new key can't be created：
![image](https://user-images.githubusercontent.com/28860891/53479727-a3508c00-3ab4-11e9-8c83-1cb814e59eeb.png)

**Comment by sallyur** [comment]
Verified fixed, close this issue.

**Comment by bsaby** [comment]
Build: develop1005
