### ISSUE TITLE
App settings can't show the edit status

### ISSUE THREAD

**Issue by lxhmavis** [microsoft/azure-tools-for-java#2777]
**Os**: Linux
**Eclipse build version**: 2018-12
**JDK**: 1.8.0_191
**Plugin version**: build995

### Repro steps

1. Create a webapp
2. Edit app settings

### Current result

Double click the editing area, it can't show edit status as below
![image](https://user-images.githubusercontent.com/41565966/53479318-be6ecc00-3ab3-11e9-8138-e0b58e175b93.png)
### Expected result
![image](https://user-images.githubusercontent.com/41565966/53479543-40f78b80-3ab4-11e9-9bf1-2420937e9b7e.png)

**The same condition appears in the editing the webapp properties**

**Comment by pl07** [comment]
Test pass in azure java toolkit for eclipse 3.23.0.
![image](https://user-images.githubusercontent.com/46642771/83718108-f7a6cc00-a666-11ea-9f76-72a054af95d4.png)
