### ISSUE TITLE
It can't show the progress and status after deploy web app

### ISSUE THREAD

**Issue by lxhmavis** [microsoft/azure-tools-for-java#2779]
**Os**: Linux
**Eclipse build version**: 2018-12
**JDK**: 1.8.0_191
**Plugin version**: build995

### Repro steps
1. Create a webapp
2. Deploy the webapp

### Current result
Can't show the progress and the status, maybe there are details exist, but I can't see
![image](https://user-images.githubusercontent.com/41565966/53480504-51a90100-3ab6-11e9-9a07-74eacc88cd63.png)
### Expected result
![image](https://user-images.githubusercontent.com/41565966/53480539-64233a80-3ab6-11e9-8dcf-0c802d1a2b0b.png)

**Comment by zmssp** [comment]
I can see the progress in ubuntu. 
Seems this problem only exists in some linux or eclipse version.
 
![screenshot from 2019-03-01 16-18-06](https://user-images.githubusercontent.com/7624690/53625394-f0ac3500-3c3d-11e9-90d0-d25e45c4d0eb.png)

**Comment by ZhengJun003** [comment]
Test in azure toolkits for eclipse 3.23.0, can reproduce this issue
eclipse: 2020-03
os: linux
jdk: 11.0.2

![image](https://user-images.githubusercontent.com/41051257/84347755-e8cf9480-abe5-11ea-840b-1c100adf236d.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738837
