### ISSUE TITLE
Eclipse-Storage account dialog, resource groups are not divided by location

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#278]
EXPECT:
![image](https://cloud.githubusercontent.com/assets/22470312/24387737/72733904-13a9-11e7-8e58-058aea78c759.png)
RESULT:
![image](https://cloud.githubusercontent.com/assets/22470312/24387797/d181c38e-13a9-11e7-8a18-61185b40bf67.png)

**Comment by lenala** [comment]
Actually this is correct behavior, resource group can have any location, just confirmed with @jianghaolu. I will remove filtering for all other occurrences.
