### ISSUE TITLE
[Mac]The existing app service plan doesn't change to gray when I select create new

### ISSUE THREAD

**Issue by sallyur** [microsoft/azure-tools-for-java#2780]
### Environment
1. OS: Mac
2. IDE: Eclipse IDE for Enterprise Java Developers 2018-12
3. JDK: 1.8.0_191
4. Build: 994

### Steps
1. Right click project and select Azure -> publish as Azure web app
2. Select create new
3. Select create a new app service plan

### Result:
The existing app service plan doesn't change to gray:
![image](https://user-images.githubusercontent.com/28860891/53481227-b6189000-3ab7-11e9-96b0-734668441909.png)

**Comment by ZhengJun003** [comment]
Can reproduce this issue in azure toolkits for eclipse 3.23.0

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738755

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
