### ISSUE TITLE
[Enhancement]The web app properties list should be sorted alphabetically

### ISSUE THREAD

**Issue by sallyur** [microsoft/azure-tools-for-java#2781]
### Environment
1. OS: All
2. IDE: Eclipse IDE for Enterprise Java Developers 2018-12
3. JDK: 1.8.0_191
4. Build: 994

### Actual Result:
Now the web app properties list displayed as below:
![image](https://user-images.githubusercontent.com/28860891/53482258-c7fb3280-3ab9-11e9-96fb-78321d3b0ab2.png)
### Expect result:
The web app properties list be sorted alphabetically like portal:
![image](https://user-images.githubusercontent.com/28860891/53482363-01cc3900-3aba-11e9-9c72-11e246be2801.png)

**Comment by ZhengJun003** [comment]
Can reproduce this issue in azure toolkits for eclipse 3.23.0

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738771

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
