### ISSUE TITLE
[Eclipse]HDInsight icon does not display well

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2784]
Build: dev 996

Repro Steps:
1. Open Azure Explorer in Eclipse.

Result:
The icon of HDInsight does not display well
![image](https://user-images.githubusercontent.com/36756024/53539716-a8154e80-3b4d-11e9-9764-52b977f79a1a.png)

**Comment by wezhang** [comment]
Dup #2772

**Comment by wezhang** [comment]
The private resource repo just updated.
