### ISSUE TITLE
[Eclipse] Job configuration\value is not clickable

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#2786]
Build: dev996

Repro Steps
1. Right click on one script, select submit to pops the config file
2. Click on the cell under "Job Configuration"\"Value"

Result:
Could not set focus on the value cell, could not set values easily 
![image](https://user-images.githubusercontent.com/36756024/53540886-56bb8e00-3b52-11e9-9bb1-4c76432fe4a1.png)

**Comment by wezhang** [comment]
@v-lanjli , could you help to repro it? Thanks!

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748132
