### ISSUE TITLE
[Eclipse] Fail to launch Azure Storage Explorer from cluster's context menu

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#2787]
Build: dev996

Repro Steps:
1. Open Eclipse and sign in
2. Right click on one cluster, select "Open Azure Storage Explorer for storage"

Result:
![image](https://user-images.githubusercontent.com/36756024/53541150-7e5f2600-3b53-11e9-8103-bdb219570f1d.png)

**Comment by t-rufang** [comment]
We should catch the exception and tell customer to install Azure Storage Exeplorer if it's not installed yet.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748131
