### ISSUE TITLE
Open two identical web pages at the same time for docker conatiner

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#2790]
Can't stable repro.

### Environment:
* OS: Windows/Mac/Linux
* Eclipse: 2018-12 (4.10.0)
* Bits: dev995

### Steps:
1. Publish a war/jar package as a docker container
2. Click the published link after deployment

![image](https://user-images.githubusercontent.com/22470312/53542151-19f29580-3b58-11e9-880a-278d1128340b.png)

### Result:
Open two same web pages iat the same time.
![image](https://user-images.githubusercontent.com/22470312/53542155-1bbc5900-3b58-11e9-8deb-0cdd8cf2dc2c.png)

**Comment by ZhengJun003** [comment]
According to this issue: #4353, can't reproduce this issue

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738775

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738816

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
