### ISSUE TITLE
[IntelliJ][gen2] No default storage account for gen 2 cluster

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2793]
Build: dev 991

Repro Steps:
1. Start a HDInsight config file, select one gen2 cluster
2. Check the upload path

Result:
![image](https://user-images.githubusercontent.com/36756024/53549341-e00b9a00-3b2b-11e9-9bcd-ab7b71bfed17.png)

Expect:
Should have default storage account to upload file?

**Comment by jingyanjingyan** [comment]
With build dev 1013
![image](https://user-images.githubusercontent.com/36756024/53799974-9c51cf80-3f33-11e9-8ecc-2fae9c569540.png)

**Comment by lcadzy** [comment]
Not support submitting now.

**Comment by jingyanjingyan** [comment]
@wezhang should block submission or something? In further release?

**Comment by jingyanjingyan** [comment]
Fix in dev 1094
