### ISSUE TITLE
Eclipse Toolkit 2.9.5 won't install under Ubuntu 16.10

### ISSUE THREAD

**Issue by hsirtl** [Microsoft/azure-tools-for-java#28]
After a clean install of an Ubuntu 16.10 Azure VM, OpenJDK 8 and Eclipse (Neon.1a Release 4.6.1)

Error message: "The following solutions are not available: Azure Toolkit for Eclipse 2.9.5 - Proceed with the installation anyways?" Confirming with "yes" results in several errors like

![image](https://cloud.githubusercontent.com/assets/1764309/19610940/66d0e858-97df-11e6-8aa2-5c7d5f0a5e60.png)

Obviously, the repository at https://azuredownloads.blob.core.windows.net/eclipse/content.xml can't be read.

Trying to install the Azure Plugin via http://dl.microsoft.com/eclipse (the recommended way according to the Azure documentation) doesn't list the Azure Toolkit at all. It only offers "Team Explorer Everywhere".

**Comment by milismsft** [comment]
Hi @hsirtl, I could not reproduce the issue you reported. In my local testing I used a local VM to run Ubuntu via Virtual Box (makes it easier to access the Ubuntu Desktop), installed oracle-java8 and Eclipse Neon.1a Release (4.6.1) then followed the steps from https://azure.microsoft.com/en-us/documentation/articles/azure-toolkit-for-eclipse-installation/

**Comment by hsirtl** [comment]
Hm, not sure if I did something wrong while insalling Ubuntu, Java and Eclipse... anyway, this is what Eclipse shows, when I try to follow the steps in the documentation:
![image](https://cloud.githubusercontent.com/assets/1764309/19997761/fc4fe3a0-a268-11e6-8596-5a68e637e58c.png)
I.e. I don't get the opportunity to select the Tools :(

**Comment by milismsft** [comment]
That is strange... Here's what it shows for me:
![virtualbox_ubuntu16_04_11_2016_08_21_26](https://cloud.githubusercontent.com/assets/15163996/20011456/f1fa7f78-a268-11e6-8094-482610494309.png)

Can you share a screenshot of the dialog that opens if you click "What is **already installed**?" from above?

Also can you try with a new Eclipse install? You can point to a different installation folder during the Eclipse setup so you don't have to remove the other installation.

**Comment by martinsawicki** [comment]
we cannot reproduce this issue.
maybe try with a clean Eclipse installation.

**Comment by hsirtl** [comment]
Hm, I deleted my eclipse directory, deleted my workspace, did a fresh install of Eclipse (NEON, JEE Version). Same result as above (only Team Explorer Everywhere being offered). Here's what's shown in "already installed"-dialog:
![image](https://cloud.githubusercontent.com/assets/1764309/20208464/a9cf842e-a7ee-11e6-8577-612a5e8ee8fb.png)
![image](https://cloud.githubusercontent.com/assets/1764309/20208486/d010f762-a7ee-11e6-9e29-84b0cc67c9d1.png)
