### ISSUE TITLE
Both IntelliJ and Eclipse, resource group list no content display in vm creation.

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#280]
No matter what **Location** I choose， the resource group list always no content display.
![image](https://cloud.githubusercontent.com/assets/22470312/24484544/5a01ea80-1531-11e7-91e9-bcaee9dca749.png)
![image](https://cloud.githubusercontent.com/assets/22470312/24484582/82418ff0-1531-11e7-99b4-0205b61a1114.png)

**Comment by lenala** [comment]
Fixed, please verify.

**Comment by bsaby** [comment]
Test passed in IntelliJ, using azure-toolkit-for-intellij.179.03-30-2017.zip.
**Repro in Eclipse**, using WindowsAzurePlugin4EJ.183.03-30-2017.zip.

**Comment by lenala** [comment]
Fixed for Ecipse, please verify.

**Comment by bsaby** [comment]
Test passed in Eclipse, using WindowsAzurePlugin4EJ.195.03-31-2017.zip.
