### ISSUE TITLE
Disable maven build when deploying .war of web project to Azure 

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#2814]
### Environment:

- OS: Windows/Mac/Linux
- IDE: IU18.3.5 and IU18.2.7
- JDK: 8

### How to repro:
1. New a web project in IntelliJ
2. Configure the atifact
3. Right click project and choose `Deploy to Azure`
4. New a Windows/Linux web app or select an existing web app, click `Run`
![image](https://user-images.githubusercontent.com/22470312/53722036-93afb980-3e9f-11e9-8ec5-b8051a2af15f.png)

### Result:
Plugin will execute maven package goal for this project
![image](https://user-images.githubusercontent.com/22470312/53721718-d91fb700-3e9e-11e9-9796-12874905ae05.png)

### Expect:
Disable maven build for web project

**Comment by Flanker32** [comment]
@bsaby This should be caused by force build, it was removed in #2799 , please hava a verify,

**Comment by bsaby** [comment]
Test passed.
Build used: PR3054
