### ISSUE TITLE
Slot configuration source settings are not displayed when deployed to slot

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#2815]
### Environment:

- OS: Windows/Mac/Linux
- IDE: IU/IC18.3.5,  IU/IC18.2.7
- JDK: 8

### How to repro:
1. Right-click a project and select `Deploy to Azure`
2. Select a web app
3. Expand Deployment slot 
4. Check `Deploy to Slot`

### Result:
No `Slot Configuration Source `setting
![image](https://user-images.githubusercontent.com/22470312/53722326-3ec07300-3ea0-11e9-9626-0b1b519f6bb4.png)
The `Slot Configuration Source` setting will be shown if i switch to `Use existing slot` and then switch back
### Expect:
Show all slot settings directly.
![image](https://user-images.githubusercontent.com/22470312/53722375-60215f00-3ea0-11e9-9001-47fa70813b3e.png)

**Comment by Flanker32** [comment]
Fixed in #2799,  @bsaby please have a verify.

**Comment by bsaby** [comment]
Test passed.
BUild used: PR3054
