### ISSUE TITLE
Can’t auto-refresh web app node after web app creation

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#2816]
### Environment:
OS: Windows/Mac/Linux
IDE: IU/IC18.3.5, IU/IC18.2.7
JDK: 8
### How to repro:

1. Right-click a project and select Deploy to Azure
2. Create a web app
### Result:
Cannot auto-refresh web app node in Azure Explorer after creation and deployment.
![image](https://user-images.githubusercontent.com/22470312/53723007-bfcc3a00-3ea1-11e9-9b2d-32363499f33c.png)
### Expect:
Auto-refresh web app node after creation

**Comment by Flanker32** [comment]
Fixed in #2799, @bsaby please have a verify.

**Comment by bsaby** [comment]
Now, the auto-refresh behavior will be executed at the end of each deployment inlclude slot deployment.

But I think the auto-refresh behavior should be executed only after web app creation, because:
1. If clicking `Cancel ` in `Deploy to Azure` dialog after web app creation, the newly created web app will not be auto-added in web app list of Azure Explorer.

2. The plugin will auto-refresh web app node after the slot is deployed, but now, the web app list only shows the application level by default and does not include the deployment slot level.
![image](https://user-images.githubusercontent.com/22470312/53781838-703f4a00-3f45-11e9-873e-d83b618c8f1b.png)

**Comment by bsaby** [comment]
Test passed.
Build: PR3076
