### ISSUE TITLE
There is no default value for slot name

### ISSUE THREAD

**Issue by sallyur** [Microsoft/azure-tools-for-java#2817]
### Environment:
OS: Windows/Mac/Linux
IDE: IU18.3.5 and IC 18.3.2
JDK: 8

### Repro steps:
1. Right-click  project ->Azure -> deploy to Azure
2. Select a web app which has deployed slot
3. Check the option "Deploy to slot"

### Actual Result:
There is no default value for slot name
![image](https://user-images.githubusercontent.com/28860891/53723193-20f40d80-3ea2-11e9-86eb-52ad2796201d.png)

### Expect result:
Slot name has a default value like below：
![image](https://user-images.githubusercontent.com/28860891/53725629-56e7c080-3ea7-11e9-8132-3d4d8e97e9dd.png)

**Comment by Flanker32** [comment]
Fixed in #2799, @bsaby please have a verify.

**Comment by bsaby** [comment]
Test passed.
Build used: PR3054
