### ISSUE TITLE
Should navigate to the deployment console after force build project

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#2818]
### Environment:

- OS: Windows/Mac/Linux
- IDE: IU/IC18.3.5, IU/IC18.2.7
- JDK: 8

### How to repro:
1. Right-click a project and select Deploy to Azure
2. Delete the default package task before launch and check `Force Build`
3. New a web app or select an existing web app to deploy

### Result:
Always stay in the package console(window 2)
![image](https://user-images.githubusercontent.com/22470312/53725023-1d628580-3ea6-11e9-92e5-d638bedf34fd.png)
### Expect:
Navigate to the deployment console(window1) after executing force build 
![image](https://user-images.githubusercontent.com/22470312/53724995-120f5a00-3ea6-11e9-8b79-944f132caf17.png)

**Comment by Flanker32** [comment]
@bsaby Force build was removed in #2799 , please hava a verify,

**Comment by bsaby** [comment]
Test passed.
Build used: PR3054
