### ISSUE TITLE
IntelliJ: the Azure Explorer sign in/out should match current state after successfully sign in or sign out

### ISSUE THREAD

**Issue by milismsft** [Microsoft/azure-tools-for-java#282]
See https://github.com/Microsoft/azure-tools-for-java-private/issues/266

**Comment by martinsawicki** [comment]
@reyang this is a low pri issue -- if someone on your end can figure out how to make this work as expected quickly enough, then we can consider it for v3, but this isn't a big deal, and Elena already spent some time trying to get this to work properly, so if too hard, let's postpone. Not a big deal for the user.
