### ISSUE TITLE
Sometimes, there are too many blank areas in Deploy to Azure dialog

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#2820]
### Environment:
OS: Windows/Mac/Linux
IDE: IU/IC18.3.5, IU/IC18.2.7
JDK: 8

### Result:
Sometimes, open the `Deploy to Azure` dialog, it will be shown as below:
screenshot1:
![image](https://user-images.githubusercontent.com/22470312/53725560-37509800-3ea7-11e9-87bb-64703cdf319f.png)
screenshot2:
![image](https://user-images.githubusercontent.com/22470312/53725844-c2319280-3ea7-11e9-8905-5766b93ec882.png)
Is there any better way to auto-adjust the dialog size?

**Comment by EricZhangzf** [comment]
Not repro on 3.37.0
