### ISSUE TITLE
Can not see the new UI if open a run configuration from previous plugin version

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#2821]
### Environment:

- OS: Windows/Mac
- IDE: IU/IC18.3.5, IU/IC18.2.7
- JDK: 8

### How to repro:
1. Open a project with the web app run configuration which generated by previous plugin version(e.g. marketplace version3.18.0)
2. Right-click the  project and select `Deploy to Azure`

### Result:
Plugin will open the previous configuration and you will find that the new UI can't be shown,
![image](https://user-images.githubusercontent.com/22470312/53726526-16894200-3ea9-11e9-89fb-0d67c9062e72.png)

**Comment by Flanker32** [comment]
This was by designed, user could continue use old ui with their existing configuration, and they will use new ui to create new deployment.
