### ISSUE TITLE
[IntelliJ][RunConf] valid webhdfs root path should not display in gray

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2848]
Build: Dev 1020

Repro steps:
1. Create a HDInsight config, select adls cluster, set the webhdfs root path

Result:
The webhdfs root path display in gray
![image](https://user-images.githubusercontent.com/36756024/53859118-965ffb00-3fd4-11e9-8a3d-d89251b58b56.png)

Expect:
Display as enabled

**Comment by v-jiche** [comment]
Verified. Fixed.
Build: azure-toolkit-for-intellij-2018.3.develop.1052.03-26-2019
