### ISSUE TITLE
[IntelliJ] After shutdown, the Start status of docker host is not available.

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#285]
Right click a docker host, select Shutdown.

REAULT:
After shutdown, Start is not available until refresh the docker host manually.
EXPECT:
After shutdown, docker host should auto refresh and Start should available.

Shown as below picture:
![image](https://cloud.githubusercontent.com/assets/22470312/24793271/f9c231dc-1bb3-11e7-8157-e2b3cd174c78.png)

**Comment by milismsft** [comment]
fixed

**Comment by bsaby** [comment]
Test passed in IntelliJ and Eclipse, using
 WindowsAzurePlugin4EJ.244.04-09-2017.zip
azure-toolkit-for-intellij.2017.240.04-09-2017.zip

**Comment by bsaby** [comment]
Repro in Eclipse and IntelliJ.
Build used: 
artifacts/WindowsAzurePlugin4EJ.289.04-13-2017.zip 
artifacts/azure-toolkit-for-intellij.2017.285.04-13-2017.zip

**Comment by milismsft** [comment]
Fixed.

**Comment by bsaby** [comment]
Both IntelliJ and Eclipse test passed.
Builds used:
artifacts/azure-toolkit-for-intellij.2017.333.04-18-2017.zip
artifacts/WindowsAzurePlugin4EJ.338.04-18-2017.zip
