### ISSUE TITLE
[intelliJ][RunConf]It display duplicate when create a new configuration file

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#2854]
Build:
azure-toolkit-for-intellij-2018.3.develop.1014.03-05-2019

Repro Steps:
1. Open Run/Debug configurations.
2. Click "+" to create a new SQL Server Big data cluster.
3. Click OK button to save it.
4. Reopen Run/Debug configurations.
5.  Click "+" to create a new SQL Server Big data cluster.

Result:
The type of configurations display duplicate.
![image](https://user-images.githubusercontent.com/35950097/53860876-5a04bd00-401d-11e9-84b4-ad63710c8e8e.png)

**Comment by t-rufang** [comment]
@v-jiche Does this issue repro in the latest plugin?

**Comment by v-jiche** [comment]
Frequency: Occasionally

**Comment by v-jiche** [comment]
Bug repros in build:
azure-toolkit-for-intellij-2019.1.develop.1133.05-24-2019
![image](https://user-images.githubusercontent.com/35950097/58470437-4b3d2a80-8174-11e9-9741-1f90d6140016.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748130
