### ISSUE TITLE
[IntelliJ][RunConf] Could create sql server big data config file continually from context menu

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#2856]
Build: Dev 1022

Repro Steps:
1. Set the default application type to sql server big data cluster
2. Create a project, right click on one class
3. Click "Create '[Spark on SQL]Spark...', click OK to save
4. Right click on the same class

Result:
It will still show the 'Create '[Spark on SQL]Spark...', click on it, will create <name>1 config file
![image](https://user-images.githubusercontent.com/36756024/53866115-c1c20480-402b-11e9-8f7b-fb65897dee45.png)

Expect:
Pops context menu for the second time, should not allow to create config anymore.

**Comment by t-rufang** [comment]
Not repro now. The second time right click on scala file, it indicates that `Edit...`
![image](https://user-images.githubusercontent.com/32627233/85937419-fb600280-b935-11ea-9bdf-b4564b86f73f.png)
