### ISSUE TITLE
[IntelliJ][RunConf]The main class selection box loads out of the sample list too slow or can't open the selection box

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#2857]
Build: develop 1022
Repro Steps:
1.Create a new config file
2.First,select the "Artifact from local disk"
3.Then select the main class name: 
click the button on the picture as follow:
![image](https://user-images.githubusercontent.com/43333874/53873753-d794e280-3fb5-11e9-9e92-961be424d885.png)

Result:
Windows: wait for about 3 minutes searching then load out the list 
![image](https://user-images.githubusercontent.com/43333874/53874005-5a1da200-3fb6-11e9-805a-abc410f7f144.png)

![image](https://user-images.githubusercontent.com/43333874/53873980-4ffba380-3fb6-11e9-8bd9-1f95f2b68891.png)
Lunix:
Can not open the selection box at all

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748128
