### ISSUE TITLE
[intelliJ] There is a legacy of the configuration information

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#2858]
Build:
azure-toolkit-for-intellij-2018.3.develop.1014.03-05-2019

Repro Steps:
1. Open Run/Debug Configurations.
2. Create a HDInsight configuration, set up for it.
![image](https://user-images.githubusercontent.com/35950097/53875526-a2cd6d80-403f-11e9-8fb5-cc14474fc5fc.png)
3. Click OK button to save the configuration and close the window.
4. Reopen Run/Debug Configurations.
Result:
It displays null.
![image](https://user-images.githubusercontent.com/35950097/53875028-a8768380-403e-11e9-9176-41808da42de6.png)
5. Click "+" to create a HDInsight configuration.
Result:
The original configuration displays.
![image](https://user-images.githubusercontent.com/35950097/53875560-b7116a80-403f-11e9-8d01-8dce8456d343.png)
6. Click "+" to create a HDInsight configuration.
Result:
The information of the original configuration is kept on the new configuration.
![image](https://user-images.githubusercontent.com/35950097/53875625-e1fbbe80-403f-11e9-85cd-4dd65ac3e03d.png)

Note:
Probability of Occurrence:  60%

**Comment by wezhang** [comment]
@konjac, could you have a look?

**Comment by konjac** [comment]
@v-jiche I noticed you were using Ubuntu? Does this bug could be reproduced on windows?

**Comment by v-jiche** [comment]
@konjac 
Yes. It can be found on windows and linux.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748127
