### ISSUE TITLE
[Eclipse] Storage account can't create blob container.

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#286]
Right click a storage account in Azure explorer, select create blob container.
Enter a blob container name, click OK.
RESULT:
The new blob container doesn’t appear, nor a prompt warning dialog.
EXPECT:
Create a blob container successfully.

**Comment by lenala** [comment]
This is fixed, please verify.

**Comment by bsaby** [comment]
Test passed, using WindowsAzurePlugin4EJ.**271**.04-11-2017.zip.
