### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by zachcarp** [Microsoft/azure-tools-for-java#2861]
IntelliJ build version: 2018.3.5 IU-183.5912.21
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.18.0-2018.3

#### 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).
7

#### 2. What did you like or dislike about Azure Toolkit for IntelliJ?
It's run configuration menu often has issues. When you have a long line of parameters, the parameters stretch off screen and one has to delete them in order to adjust other configurations: 
![image](https://user-images.githubusercontent.com/14919531/53976114-385a1300-40bb-11e9-836e-4e33669fc9e2.png)

#### 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?
Fixing the UI components would go a long way in making the tool easier to use.

**Comment by t-rufang** [comment]
Hi @zachcarp , thanks for your advice! we will take this into account and improve the experiences soon.
