### ISSUE TITLE
After refreshing the webapp note, webapp list will close automatically

### ISSUE THREAD

**Issue by lxhmavis** [microsoft/azure-tools-for-java#2863]
Sometimes, this issue can stable repro, sometimes not.
### Environment:

- OS: Windows/Linux/Mac
- IntelliJ build version: IU 18.2.7/IU18.3.5
- Bits: v3.19.0

### Steps:

1. Create a webapp
2. After creating it, the webapp note can refresh, but after that webapp list will close automatically

### Actual result:
![image](https://user-images.githubusercontent.com/41565966/54012321-aa605400-41b0-11e9-8889-b3a0b6847e4b.png)

### Expected result:
After refresh, the list will be open 
![image](https://user-images.githubusercontent.com/41565966/54012440-01febf80-41b1-11e9-9f65-4a57063cbaad.png)

**Comment by Flanker32** [comment]
Issue has been fixed in the latest release
