### ISSUE TITLE
[IntelliJ][Run/Debug Configurations]When the Config file name is empty, the file will still be saved successfully.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#2865]
**Build:** 
•	IntelliJ IDEA 2018.2:  https://azuredownloads.blob.core.windows.net/azuretoolkitforintellij/v3.19.0/azure-toolkit-for-intellij-2018.2.90.03-07-2019.zip 
•	IntelliJ IDEA 2018.3:  https://azuredownloads.blob.core.windows.net/azuretoolkitforintellij/v3.19.0/azure-toolkit-for-intellij-2018.3.90.03-07-2019.zip 

**Repro Steps:**
**1.** Create a new config file
**2.** In addition to the name is empty, other configurations are well equipped
**3.** Click the "OK" button at the bottom of the page
**4.** Run this Config.

**Results:** When the Config file name is empty, the file will still be saved successfully. And the name above the window is empty.

**Expectation:** Give the user some information that the prompt name is empty.
**Screenshots:**
![image](https://user-images.githubusercontent.com/40199316/54014505-eb0f9b80-41b7-11e9-8e7c-a580c5e398a5.png)

**Comment by wezhang** [comment]
@konjac , could you help to fix it?

**Comment by konjac** [comment]
> @konjac , could you help to fix it?

Intellij itself allows empty config name. So this should not be a bug but an enhanced feature beyond Intellij. Do you think we need to implement?

**Comment by t-rufang** [comment]
Close this issue since it's not a toolkit issue.
