### ISSUE TITLE
[IntelliJ][RunConf] When storage key is long, the other fields display with the same length

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2869]
Build: dev 1023

Repro Steps:
1. Start a HDInsight config file, enter with a long storage key 
2. Expand Storage type combo box

Result:
![image](https://user-images.githubusercontent.com/36756024/54105002-97749c00-43c9-11e9-9d02-36756cb10a1c.png)

**Comment by t-rufang** [comment]
`Storage Key` field is expandable so issue fixed.

**Comment by jingyanjingyan** [comment]
Fix in dev 1094
