### ISSUE TITLE
[Eclipse][Mac] Cannot sign in to Azure

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#2873]
**Azure Toolkit for Java:** WindowsAzurePlugin4EJ - https://azuredownloads.blob.core.windows.net/eclipse/v3.12.0/
**Eclipse Version:** 2018-12 (4.10.0)
**OS:** Mac

**Repro Step:**
1. Start the Eclipse IDE.
2. On the Window menu, select Show View.
3. Select Other.
4. Expand Azure, select Azure Explorer.
5. Select OK.

**Results:** 
**1.** No response when you right-click the Azure.
![image](https://user-images.githubusercontent.com/40199316/54179599-32599d00-44d4-11e9-9df4-46ccd5296d57.png)

**2.** Click the login button to sign in. The final result is also a login failure with no error message.
![image](https://user-images.githubusercontent.com/40199316/54179855-ff63d900-44d4-11e9-87da-dde9d80043cd.png)
**3.** No response when you click OK button in Sign In Error dialog.
![image](https://user-images.githubusercontent.com/40199316/54180152-e6a7f300-44d5-11e9-901c-fca11b91ab2d.png)

**Comment by zmssp** [comment]
What is your jdk version? Do you use jdk11?

**Comment by v-lanjli** [comment]
Yes, I am using jdk 11.
![image](https://user-images.githubusercontent.com/40199316/54255804-744a1800-4594-11e9-9cae-d568310a083b.png)

**Comment by v-lanjli** [comment]
I modified the path to the JDK in the **eclipse.ini** file. Changed **zulu-11.jdk** to **jdk1.8.0_202.jdk**. It can be successfully logged in using **jdk1.8.0_202.jdk**.
![image](https://user-images.githubusercontent.com/40199316/54264552-4e317180-45ae-11e9-89e0-176c0aec8ae3.png)

**Comment by zmssp** [comment]
The same issue #2769

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748126
