### ISSUE TITLE
Telemetry consistent for azure toolkit

### ISSUE THREAD

**Issue by zmssp** [microsoft/azure-tools-for-java#2874]
This issue is for telemetry consistent, we will use the same schema as vscode.

The full event name = ${platformName} + "/" +  {eventtype}
- platformName: {"AzurePlugin.Eclipse", "AzurePlugin.Intellij"}
- eventtype: {opStart, opEnd, step, info, warn, error}

Example: AzurePlugin.Eclipse/opEnd,  AzurePlugin.Intellij/info

We also define the service name and operation name.
Service name and operation name will put in properties.

The typical service name is: webapp, docker, hdinsight....
The typical operation name is: create-webapp...

**Comment by zmssp** [comment]
https://github.com/Microsoft/azure-tools-for-java/pull/2875#issuecomment-472321854

The problem is how we interact one operation with another. For example, when we deploy the web app, we may first create a new one, then deploy, can we link this two operations?

**Comment by zmssp** [comment]
In order to support transaction trace. 
- Each time when you start a transaction, we will generate a operationId(the operationId will store in thread local), then you can send info,warn,error with this operationId, you need to end this transaction.
- If you start a new transaction without close the previous one, we just generate a new operationId.
- If you send info, error, warn or end transaction without start a transaction, we just give you a new operationId.
- Take care, each time when you start a transaction you need to end it. Or you cannot correctly trace the operation.

The interface design is:

```
public interface Producer {

    void startTransaction(String eventName, String operName, Map<String, String> properties);

    void endTransaction(String eventName, String operName, Map<String, String> properties, long time);

    void sendError(String eventName, String operName, ErrorType errorType, String errMsg,
        Map<String, String> properties);

    void sendInfo(String eventName, String operName, Map<String, String> properties);

    void sendWarn(String eventName, String operName, Map<String, String> properties);

}
```

The usage code like:

```
try {
      startTransaction();
      doSomething();
      sendInfo();
} catch (Exception e) {
      sendError();
} finally {
      endTransaction();
}
```

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738828
