### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by klukhnov** [microsoft/azure-tools-for-java#2877]
IntelliJ build version: 2018.3.5 IU-183.5912.21
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.19.0-2018.3

#### 2. What did you like or dislike about Azure Toolkit for IntelliJ?
Functionality and implementation of the Toolkit is great. Pleasure to use. The only thing I could ask is to address critical bugs faster. Especially those that prevent using the app altogether. 

#### 3. What enhancements would you like Azure Toolkit for IntelliJ to implement? Make it more stable. I would love to rely solely on this Toolkit for all my development work. 

Thanks for the great work and all the best!

**Comment by wezhang** [comment]
Thanks @klukhnov ! And feedbacks are welcome!
