### ISSUE TITLE
[Eclipse] No response when you click View Blob Container.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#2879]
**Azure Toolkit for Java:** WindowsAzurePlugin4EJ - https://azuredownloads.blob.core.windows.net/eclipse/v3.12.0/
**Eclipse Version:** 2018-12 (4.10.0)

**Repro Step:**

**1.** Start the Eclipse IDE.
**2.** Sign in to Azure.
**3.** Expand the **HDInsight** node ->Expand a cluster -> Expand the **Storage Accounts** node -> Expand one of the storage account in the list.
**4.** Select one of the storage accounts in the list, and then right click on it.
**5.** Click **View Blob Container**.

**Results:** No response when you click **View Blob Container**.
![image](https://user-images.githubusercontent.com/40199316/54414905-9e870b80-4735-11e9-99b8-208ff4f15dcd.png)

**Comment by t-rufang** [comment]
Not repro with Eclipse build ID `20180308-1800` and Java `1.8.0_192`

**Comment by t-rufang** [comment]
@v-lanjli Does this issue repro in the latest plugin?
