### ISSUE TITLE
SBT support

### ISSUE THREAD

**Issue by donamk** [Microsoft/azure-tools-for-java#288]
I am enjoying to use Azure Toolkit for IntelliJ however in my company, there are many spark job which already developed using not Maven but SBT.

Will you have any plan for support SBT?

**Comment by martinsawicki** [comment]
@voidfunction for you to comment

**Comment by voidfunction** [comment]
@donamk Thanks for your feedback. We are planning to add SBT support and it should be enabled soon.

**Comment by ruoxinCheng** [comment]
Yes, it supported.

**Comment by donamk** [comment]
Thank you very much 👍
