### ISSUE TITLE
[IntelliJ][SparkonCosmos] The number of Container is missing in dark theme when provision cluster

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#2886]
Build: Dev 1034, IntelliJ 18.2, 18.3

Repro Steps:
1. Set serverless enviroment, set dark theme
2. Provision a cluster

Result:
![image](https://user-images.githubusercontent.com/36756024/54580397-dd250a80-4a42-11e9-9f72-1635d6ef0b54.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748125
