### ISSUE TITLE
[intelliJ][PPE Enviroment][Serverless]Remote run failed with Spark on Cosmos Serverless configuration.

### ISSUE THREAD

**Issue by v-xiaocw** [Microsoft/azure-tools-for-java#2888]
Build: azure-toolkit-for-intellij-2018.3.develop.1034.03-18-2019 

Repro Steps:
1.Set serverless environment 
2.Create a Spark on Cosmos Serverless configuration
3.Click the remotely run button

Result:
![image](https://user-images.githubusercontent.com/43333874/54589611-5856d400-49e3-11e9-9238-f7d0d9116782.png)

**Comment by t-rufang** [comment]
Results should be given in #2899 . Consider that PPE environment is broken, please use production environment to test.

**Comment by v-jiche** [comment]
Verified. Fixed.
Build: azure-toolkit-for-intellij-2018.3.develop.1057.03-27-2019
