### ISSUE TITLE
[Eclipse] Missing newline at title of license terms when installing plugin

### ISSUE THREAD

**Issue by xscript** [Microsoft/azure-tools-for-java#289]
Issue Type: minor text issue
How to repro: install the plugin
OS: Windows 10
IDE: Eclipse Neon.3
Plugin Version: azure-toolkit-for-intellij.2017.267.04-11-2017.zip

![image](https://cloud.githubusercontent.com/assets/2300784/24966026/52cbf7a4-1fd8-11e7-9d68-ef67a983599a.png)

**Comment by martinsawicki** [comment]
fixed

**Comment by davidliangze** [comment]
Test passed, using WindowsAzurePlugin4EJ.278.04-12-2017

**Comment by davidliangze** [comment]
Test passed, using WindowsAzurePlugin4EJ.278.04-12-2017.
