### ISSUE TITLE
[intelliJ][Serverless]Error loading storage account details.

### ISSUE THREAD

**Issue by v-jiche** [Microsoft/azure-tools-for-java#2890]
Build:
windows mac
azure-toolkit-for-intellij-2018.3.develop.1034.03-18-2019

Repro Steps:
1. Install the 1034 build
2. Start intelliJ

Result:
Error message pops up.
![image](https://user-images.githubusercontent.com/35950097/54596861-761e4a80-4a70-11e9-9870-7796a7afe412.png)
![image](https://user-images.githubusercontent.com/35950097/54596893-8504fd00-4a70-11e9-90fb-4fcbc68f1c8f.png)
![image](https://user-images.githubusercontent.com/35950097/54596915-9221ec00-4a70-11e9-8df0-dd2eb37ca3ea.png)
![image](https://user-images.githubusercontent.com/35950097/54596954-a4038f00-4a70-11e9-96c0-fb98488212be.png)
![image](https://user-images.githubusercontent.com/35950097/54596986-b1b91480-4a70-11e9-9887-d5c042821c9b.png)
![image](https://user-images.githubusercontent.com/35950097/54597021-c1d0f400-4a70-11e9-8352-0b1ff6e47bcd.png)

**Comment by wezhang** [comment]
@t-rufang , could you help have a look?

**Comment by v-jiche** [comment]
Not repro.
Build: azure-toolkit-for-intellij-2018.3.develop.1044.03-25-2019
