### ISSUE TITLE
[IntelliJ][ReportedByUser]The creation of the AzureToolsForIntelliJ in the home folder is annoying

### ISSUE THREAD

**Issue by Flanker32** [microsoft/azure-tools-for-java#2891]
The creation of the AzureToolsForIntelliJ in the home folder (in linux at least) is really annoying. It should be a hidden folder or give us the choice to change that. [link](https://plugins.jetbrains.com/plugin/8053-azure-toolkit-for-intellij#comment=31375)

**Comment by UnoSD** [comment]
Same problem here, I have to delete it every time from my desktop/home.

**Comment by Flanker32** [comment]
Fixed it by change it to `.AzureToolsForIntelliJ` and set it invisible in Windows in #3730
