### ISSUE TITLE
[intelliJ][Serverless]Warning message should not include code when kill serverless spark job.

### ISSUE THREAD

**Issue by v-jiche** [Microsoft/azure-tools-for-java#2894]
Build:
azure-toolkit-for-intellij-2018.3.develop.1036.03-20-2019

Repro Steps:
1. Open **Azure Explorer**.
2. Expand **Apache Spark on Cosmos**.
3. Right click the cluster marked in the pic.
![image](https://user-images.githubusercontent.com/35950097/54674834-31f67d00-4b38-11e9-946b-05769621785a.png)
4. Choose **View Spark on Cosmos Serverless Jobs**.
![image](https://user-images.githubusercontent.com/35950097/54674878-49356a80-4b38-11e9-8343-05389b6c342a.png)
5. Try to kill the job the state of which is Finilizing.
![image](https://user-images.githubusercontent.com/35950097/54677151-48eb9e00-4b3d-11e9-839d-a75f901a33b0.png)
Result:
Warning message pops up and it includes code.
![image](https://user-images.githubusercontent.com/35950097/54677079-2194d100-4b3d-11e9-8668-6c77df75af03.png)

Expectation:
Warning message should not include code.

**Comment by t-rufang** [comment]
Fixed in #2899

**Comment by v-jiche** [comment]
Verified. Fixed.
Build:
azure-toolkit-for-intellij-2018.3.develop.1052.03-26-2019
