### ISSUE TITLE
[IntelliJ][serverless]Warning message should not include code when kill the killed job.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#2895]
Build:
azure-toolkit-for-intellij-2018.3.develop.1036.03-20-2019

Repro Steps:
1. Open **Azure Explorer** then expand **Apache Spark on Cosmos**.
2. Right click sparkwatchdog-c11 then choose **Submit Spark on Cosmos Serverless Job**, fill in the content and then SparkJobRun it.
![image](https://user-images.githubusercontent.com/35950097/54680404-b222df80-4b44-11e9-8dea-189acfeb98d6.png)
3. Right Click sparkwatchdog-c11 then choose **View Spark on Cosmos Serverless Jobs**.
4. click refresh button on the top left of the table to wait for the 01test job to show up. 
5. When the state of 01test is Scheduled, Click x to kill it.
![image](https://user-images.githubusercontent.com/35950097/54681288-edbea900-4b46-11e9-8dde-8c5c5a72c794.png)
Result:
![image](https://user-images.githubusercontent.com/35950097/54681087-7db02300-4b46-11e9-955e-4e884309e070.png)
6. Click OK button to close the warning message window. Then Click x of 01test again.
Result:
Error message pops up and it includes code.
![image](https://user-images.githubusercontent.com/35950097/54681193-b94aed00-4b46-11e9-91b2-0fc5cdd89709.png)

Expectation:
Error message should not include code.

**Comment by t-rufang** [comment]
Should be fixed in #2899

**Comment by v-jiche** [comment]
Still repro.
Build:
azure-toolkit-for-intellij-2018.3.develop.1052.03-26-2019

**Comment by t-rufang** [comment]
Fixed in #3133. @v-jiche please help to verify this issue when the PR is approved.

**Comment by v-jiche** [comment]
Verified. Fixed.
Build: azure-toolkit-for-intellij-2019.1.develop.1131.05-23-2019

![Uploading image.png…]()
