### ISSUE TITLE
[intelliJ][Spark on Cosmos]Warning use account when config with cosmos configurartion.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#2897]
Build:
azure-toolkit-for-intellij-2018.3.develop.1036.03-20-2019

Repro Steps:
1. Create a **Apache Spark on Cosmos configuration** **without Spark Clusters** and save it.
2. Right click LogQuery and run Spark livy Interactive Session Console(Scala).
3. Click Continue anyway.
![image](https://user-images.githubusercontent.com/35950097/54738768-865d3380-4bf0-11e9-95e8-dd50c264871f.png)

Result:
Warning message use "account" rather than "cluster".
![image](https://user-images.githubusercontent.com/35950097/54738836-c7edde80-4bf0-11e9-8865-ef03297f7899.png)

**Comment by t-rufang** [comment]
Design is changed and the bug is fixed now.
![image](https://user-images.githubusercontent.com/32627233/85938361-4af6fc00-b93f-11ea-9ea0-9fcbb514573b.png)
