### ISSUE TITLE
[UI Issue]Title of the azure sign in dialog will show editable cursor

### ISSUE THREAD

**Issue by adashen** [Microsoft/azure-tools-for-java#291]
![image](https://cloud.githubusercontent.com/assets/1872137/24966515/02f95b26-1f5c-11e7-82e5-96cadc0aaf80.png)

As shown in the pic.

**Comment by vladimir-shcherbakov** [comment]
Actually, it's not a cursor. Eclipse dialog allows to select subtitle string and this is how looks empty string selection.

![image](https://cloud.githubusercontent.com/assets/6579928/24970481/50b986c6-1f69-11e7-8bf5-7cc56479a5e8.png)

**Comment by martinsawicki** [comment]
by design then?  I assume normally, nothing shows up as selected, until somebody actually puts the selection there, right?

**Comment by martinsawicki** [comment]
this is Eclipse behavior
