### ISSUE TITLE
[IntelliJ][]Remote Debug]Remote debug failed with "null" when submitted to gen2 cluster

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#2913]
Build: azure-toolkit-for-intellij-2018.3.develop.1040.03-25-2019

Repro Steps:
1.Create a remote run configuration file
2.Select a gen2 cluster ,eg. spark230-gen2-yan 
3.Fill in the Job Upload Storage and SSH password
4.Click Apply and OK
5.Click the remote debug button

Result:
![image](https://user-images.githubusercontent.com/43333874/54905609-af0a5500-4e9e-11e9-9d7f-372d60099241.png)

**Comment by jingyanjingyan** [comment]
With build dev 1085
Get NPE error when remote debug with normal(unlinked) gen2 cluster
Both default/gen2 storage type
![image](https://user-images.githubusercontent.com/36756024/56114137-8a336a00-5f92-11e9-988f-76a52e0a95ad.png)

**Comment by jingyanjingyan** [comment]
Remote debug with (signin) gen2 cluster success, with dev 1137
