### ISSUE TITLE
[Mac]The table under deployment slot is not aligned 

### ISSUE THREAD

**Issue by sallyur** [microsoft/azure-tools-for-java#2916]
### Environment:

1. OS: Mac 10.13.6
2. IDE: EC 2018 - 12
3. JDK: 8
4. Build: Dev1044

### Repro Steps：

1. Right click project and select Azure -> publish as Azure web app

### Actual result:
The table under deployment slot is not aligned as below:
![image](https://user-images.githubusercontent.com/28860891/54910150-b7a66e00-4f26-11e9-8867-56067e39b464.png)

### Expect result:
The table is aligned like windows:
![image](https://user-images.githubusercontent.com/28860891/54910232-ddcc0e00-4f26-11e9-99ee-67da7dfc894b.png)

**Comment by ZhengJun003** [comment]
Can reproduce this issue in azure toolkits for Eclipse 3.23.0

**Comment by andxu** [comment]
trivial issue.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738754

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
