### ISSUE TITLE
[Enhancement] Should auto-expand deployment slots node if user refresh it

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#2918]
### Environment:
OS: Windows/Mac/Linux
Eclipse: 2018-12 (4.10.0) /2019-03(4.11.0)
Bits: dev1044

### Repro steps:

1. Choose a web app and expand it
2. Right-click Deployment Slots and select `Refresh`

### Result:
The slot list will not auto-expand
![image](https://user-images.githubusercontent.com/22470312/54911568-baef2900-4f29-11e9-92ff-cff3fca5a401.png)

### Expect:
![image](https://user-images.githubusercontent.com/22470312/54911589-c6425480-4f29-11e9-867a-a4d1b14def6d.png)

**Comment by EricZhangzf** [comment]
v3.37.0 had finished this feature
Close this bug
