### ISSUE TITLE
The Azure Sign In dialog shows non-related text information

### ISSUE THREAD

**Issue by shsushi** [Microsoft/azure-tools-for-java#292]
Issue:
The Azure Sign In dialog shows non-related text information: **Azure Toolkits for IntelliJ IDEA and Eclipse.** It should only contain the related IDE name in the text information.

Repro:
1. Create a Java web application in IntelliJ.
2. Right click on the project, choose Azure->Azure Sign In.
3. Choose Interactive and Click Sign In.
4. Then you will see the dialog like below:
<img width="501" alt="screen shot 2017-04-12 at 8 19 50 am" src="https://cloud.githubusercontent.com/assets/6917718/24966828/e6ba9d52-1f5c-11e7-9afa-0ca7eb1b8220.png">

OS: macOS Sierra (10.12.4)

Subscription Type: Enterprise

IDE: IntelliJ Ultimate 2017.1.1

Plugin: azure-toolkit-for-intellij.2017.267.04-11-2017.zip

Feature: Interactive Login

**Comment by martinsawicki** [comment]
that's just the nature of our first party AD registration - AD shows it the way it is shown
