### ISSUE TITLE
[intelliJ][WebHDFS] WebHDFS Root Path is not recognized when  not  tab away.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#2924]
Build:
azure-toolkit-for-intellij-2018.3.develop.1044.03-25-2019

Repro Steps:
1. Create a HDInsight config. select main class name. use "zhouytest230hdi36adls" and set upload storage to "webhdfs".
2. Input right WebHDFS Root Path and **do not tab away**.
3. Click OK button to save the configuration.
3. Click icon to remotely run.

Result:
The root path has not been recognized. Click continue anyway, job run successfully.
![image](https://user-images.githubusercontent.com/35950097/54975884-83d55200-4fd3-11e9-8ae1-e89f3f1bb0b8.png)

**Comment by lcadzy** [comment]
You need to tab then the text change listener can be triggered and text in config and model level can be the same. It is a invalid operation.

**Comment by jingyanjingyan** [comment]
#2163

**Comment by t-rufang** [comment]
@lcadzy Could you please help to take a look at this issue?

**Comment by lcadzy** [comment]
lt is by design to sync path between UI and value in model.

**Comment by t-rufang** [comment]
@jingyanjingyan We have fixed this issue as an accessibility issue long time before, could you please help verify the fix?

**Comment by jingyanjingyan** [comment]
With build 2020.1+0529, the bug still repro

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748124
