### ISSUE TITLE
[intelliJ][WebHDFS]Unreasonable format of hint for Webhdfs Root Path.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#2926]
Build:
azure-toolkit-for-intellij-2018.3.develop.1052.03-26-2019

Repro Steps:
1. Create an aris configuration. Choose webhdfs for Storage type. 
Result:
The format of the hint for WEBHDFS Root Path is different from the real path.
![image](https://user-images.githubusercontent.com/35950097/54980990-34e2e900-4fe2-11e9-81c1-93cdd4ca0021.png)
![image](https://user-images.githubusercontent.com/35950097/54981782-24cc0900-4fe4-11e9-804f-bf85da5f8488.png)
2. Create a HDInsight configuration. Choose zhouytest230hdi36adls or hdiwithgen1test as Spark clusters.
   Choose webhdfs for Storage type.
Result:
The format of the hint for WEBHDFS Root Path is different from the real path.
![image](https://user-images.githubusercontent.com/35950097/54981399-26e19800-4fe3-11e9-8c8b-5f5eaf729dad.png)
![image](https://user-images.githubusercontent.com/35950097/54981565-8cce1f80-4fe3-11e9-9f23-191007721a5f.png)

Expectation:
The format of the hint adapts to different clusters.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748123
