### ISSUE TITLE
Link doesn't work on the Create New Storage Account dialog

### ISSUE THREAD

**Issue by aovechki** [Microsoft/azure-tools-for-java#293]
win10, x64, Eclipse, Mars

Clicking on the "Read more..." link doesn't do anything

**Comment by aovechki** [comment]
seems that other hyperlinks on the dialogs don't work either

**Comment by martinsawicki** [comment]
@lenala is this link an old one from the original version of the plugin?  We could remove it if we don't have anything interesting to show.

**Comment by martinsawicki** [comment]
odd issue unique to that machine (type) - hard to repro. Not worth addressing.
