### ISSUE TITLE
messy code shown in subscription selection window

### ISSUE THREAD

**Issue by juniwang** [Microsoft/azure-tools-for-java#294]
- issue type: minor display issue.
- IDE: Intellij 2017
- platform: Windows 10
- plugin version: azure-toolkit-for-intellij.2017.267.04-11-2017
- Repo steps: 
  - Apply an new free trial account on www.azure.com
  - Sign in the plugin
- additional information:I created a free trial azure account with a default subscription whose name is Chinese characters since my laptop's locale is set China. It's the Chinese version of "Free subscription".  

![2017-04-12_0848](https://cloud.githubusercontent.com/assets/8814383/24966824/e4775e04-1f5c-11e7-9e48-ef6f6d00bd30.png)

**Comment by martinsawicki** [comment]
@vladimir-shcherbakov, do we have control over this?

**Comment by juniwang** [comment]
Viewing the azure explorer in the plugin, the Chinese characters are displayed normally. So you should have control over this.

**Comment by vladimir-shcherbakov** [comment]
works on Mac

![image](https://cloud.githubusercontent.com/assets/6579928/24969241/e6d4555a-1f64-11e7-99c7-921df5279da2.png)

**Comment by vladimir-shcherbakov** [comment]
Looks like IntelliJ IDEA controls are unable to show Chinese symbols.
This is what happens if paste the string "我的訂閱-你好 Vlad-與每天晚上掃" into a standard IntelliJ control:

![image](https://cloud.githubusercontent.com/assets/6579928/24981624/676bbb7c-1f92-11e7-93c7-b84739c23e08.png)

**Comment by vladimir-shcherbakov** [comment]
Standard IJ tree can show chinese symbols but all other controls across IDE can not.
 
![image](https://cloud.githubusercontent.com/assets/6579928/24987827/db5f081c-1fb6-11e7-9f9e-6dbfbeec8265.png)

![image](https://cloud.githubusercontent.com/assets/6579928/24987868/199632b8-1fb7-11e7-8a3e-9de9b868dd06.png)

**Comment by vladimir-shcherbakov** [comment]
To fix this - switch IDE font to a that supports Chinese symbols, DialogInput for example.

![image](https://cloud.githubusercontent.com/assets/6579928/25017328/2d16aaa8-2038-11e7-9775-0c2cd8a8d183.png)


![image](https://cloud.githubusercontent.com/assets/6579928/25017356/46b640cc-2038-11e7-9418-1f49b1b631b6.png)
