### ISSUE TITLE
[Intellij] Azure Toolkit for IntelliJ incompatible with IntellijIDEA 2019.1

### ISSUE THREAD

**Issue by mktany2k** [Microsoft/azure-tools-for-java#2949]
Current version of Azure Toolkit for IntelliJ (v3.19.0-2018.3) is incompatible with latest IntelliJ 2019.1

**Comment by Flanker32** [comment]
@mktany2k Thanks for your report, we have released toolkit v3.20.0 which support IntelliJ 2019.1, you may find it in the [marketplace](https://plugins.jetbrains.com/plugin/8053-azure-toolkit-for-intellij)
