### ISSUE TITLE
[IntelliJ][Console] Cancel config should not create config anyway

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#2950]
Build: dev 1056

Repro Steps:
1. Create a new project, make sure there is no config file
2. Click Tools\Spark Console\Run Spark Local Console (Scala)
3. When pops the config dialog, click x to close the dialog

Result:
The config is created anyway

Expect:
When user want to cancel console, no need to create config anyway.

**Comment by t-rufang** [comment]
This is by design and we won't fix this issue
