### ISSUE TITLE
[IntelliJ][LinkedCluster]Interactive help session upload failed  when submitted to linked spark22blobhdi cluster

### ISSUE THREAD

**Issue by v-xiaocw** [Microsoft/azure-tools-for-java#2953]
Build: azure-toolkit-for-intellij-2018.3.develop.1065.03-28-2019
Repro Steps:
1.Link a cluster:spark22blobhdi
2.Create a remote run configuration file
3.Fill in the Job Upload Storage : Use spark interactive session to upload
4.Fill in the SSHUSER password
5.Click Apply and OK
6.Click the remote debug button

Result:
![image](https://user-images.githubusercontent.com/43333874/55138578-09025900-50f1-11e9-8a17-26a71ad8078d.png)

**Comment by lcadzy** [comment]
Cluster back to normal ,please check whether repo

**Comment by v-xiaocw** [comment]
Fixed in build dev 1095
