### ISSUE TITLE
[intelliJ][gen2 cluster] Can not delete access key.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#2956]
Build:
azure-toolkit-for-intellij-2018.3.develop.1063.03-27-2019

Repro Steps:
1. Create a new project

2. Create a HDInsight config 

3. Set main class, choose gen2 cluster, wait for the storage type refresh

4. choose another cluster, wait for the storage type refresh

5. choose gen2 cluster agian, wait for the storage type refresh

6. set access key with aaa, tab away, apply then OK

7. Submit

8. Open the "Run/Debug Configurations" dialog

9. Create a new HDInsight config

10. Set main class, choose gen2 cluster, wait for the storage type refresh

11. choose another cluster, wait for the storage type refresh

12. choose gen2 cluster agian, wait for the storage type refresh, notice the access key already entered

13. Clear the Access key field, tab away

Result:
1. The data before shows directly on the part of Access Key.
2. Delete the data then tab away, The data shows again.
![1](https://user-images.githubusercontent.com/35950097/55147886-32b79080-5182-11e9-8205-a08b61d9ef0d.gif)

**Comment by lcadzy** [comment]
same with #3054

**Comment by t-rufang** [comment]
Duplicate with #3054
