### ISSUE TITLE
[Intellij][SparkOnCosmos] Resource Pool Delete Experience

### ISSUE THREAD

**Issue by wezhang** [Microsoft/azure-tools-for-java#2958]
Some customers are reporting that they aren't able to delete spark resource pools. This maybe expected based on our recent deployment. However, they arent seeing an error message or traceId which we can use to determine what the actual issue is. Can you take a look as to how we can show the error message and at the very least the traceId.

![image](https://user-images.githubusercontent.com/7385667/55211353-95626800-5226-11e9-81d8-a408718926ad.png)

**Comment by jingyanjingyan** [comment]
With the released build IntelliJ IDEA 2019.1 RC: https://azuredownloads.blob.core.windows.net/azuretoolkitforintellij/v3.20.0/azure-toolkit-for-intellij-2019.1.95.03-28-2019.zip

Steps:
1.	Right click on cluster “catest”, select “Delete”, the cluster is remoted from the list
2.	Refresh account “sparkwatchdog-c11”, the cluster “catest” show again.
3.	Delete “catest” for the second time

Result:
Get error with “null”

**Comment by wezhang** [comment]
1. We can save last deleted cluster UUID to avoid refreshing show.
2. We can log or output more information from HTTP response for debugging.

**Comment by t-rufang** [comment]
Looking.

**Comment by t-rufang** [comment]
Fixed in #2967

**Comment by v-jiche** [comment]
Verified. Fixed.
Build:  artifacts/azure-toolkit-for-intellij-2019.1.develop.1079.04-10-2019.zip
