### ISSUE TITLE
[intelliJ][configuration] There is a problem to refresh Job Upload Storage when switch clusters.

### ISSUE THREAD

**Issue by v-jiche** [Microsoft/azure-tools-for-java#2959]
Build:
azure-toolkit-for-intellij-2018.3.develop.1063.03-27-2019

Repro Steps:
1. Create a HDInsight configuration. Choose zhouhdi36gen2 as Spark Clusers.

Result:
1. The Upload Storage behave as this pic. and it would not refresh to the right part.
2. When change clusters then switch to zhouhdi36gen2 again, it returns to normal.
![image](https://user-images.githubusercontent.com/35950097/55223857-1a12ad80-524a-11e9-9e44-8fd8e7534c03.png)

**Comment by lcadzy** [comment]
please check with latest version whether this can repo. When creating a new config, we need time to get access key now ,but it will show storage types soon.

**Comment by v-jiche** [comment]
Not repro. It looks good.
Build: azure-toolkit-for-intellij-2019.1.develop.1097.04-17-2019
