### ISSUE TITLE
[intelliJ]Unreasonable display when remotely run from context menu.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#2968]
Build:
azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.1069.04-02-2019

Repro Steps:
1. Create a new project.
2. Right click LogQuery and  locally run it.
3. Right click LogQuery and remotely run it.

Result:
The part of Locally run displays in the interface of Run/Debug Configurations.
![image](https://user-images.githubusercontent.com/35950097/55391317-bc44d500-556b-11e9-97b5-d7c9cdb42b73.png)

Expectation:
It should be the part of Remotelly run.

Note:
It only happens when **firstly remotely run LogQuery from context menu**.

**Comment by t-rufang** [comment]
Close this issue since we can't repro it.
