### ISSUE TITLE
[Eclipse] Fail to create authentication file for MFA account

### ISSUE THREAD

**Issue by xscript** [Microsoft/azure-tools-for-java#297]
- Issue Type: Automated login functionality
- How to repro:
  - Click login button in Azure Explore
  - Choose `Automated` and click `New...`
  - Sign-in in the popup window
- OS: Windows 10
- IDE: Eclipse Neon.3
- Plugin Version: WindowsAzurePlugin4EJ.271.04-11-2017.zip

![image](https://cloud.githubusercontent.com/assets/2300784/24967518/fa3a2548-1fdc-11e7-91e2-060a86da9359.png)

**Comment by vladimir-shcherbakov** [comment]
#299 duplicate
