### ISSUE TITLE
[intelliJ]Different display in the Run/Debug Configurations window.

### ISSUE THREAD

**Issue by v-jiche** [Microsoft/azure-tools-for-java#2973]
Build:
azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.1069.04-02-2019

Repro Steps:
1. Create a new project.
2. **Right click LogQuery** to locally run it.
3. Open Run/Debug Configurations.
Result:
The configuration displays in gray.
![无标题](https://user-images.githubusercontent.com/35950097/55471907-65a7cb80-563d-11e9-80ad-3443694c4adb.png)

4. Click button "+" to add a configuration.
Result:
The configuration displays in black.
![无标题](https://user-images.githubusercontent.com/35950097/55471750-0649bb80-563d-11e9-82b3-8256e8daa334.png)

Expectation:
The configuration list should show consistency.

**Comment by wezhang** [comment]
IntelliJ native behavior
