### ISSUE TITLE
[intelliJ][Spark On Cosmos Failure task debug]Suggest to modify the error message.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#2974]
Build:
v3.20.0-2019.1

Repro Steps:
1. Open Run/Debug Configurations window.
2. Click button "+" to add  a Spark Failure Debug configuration.
3. Click OK button to save the configuration.
   **Do not choose Spark Job Failure Context location.**
4. Click icon to locally run the configuration.

Result:
Error message pops up.
![无标题](https://user-images.githubusercontent.com/35950097/55476980-92aeab00-564a-11e9-9a29-57813ab0a3b5.png)

Expectation:
Suggest to change Run Configuration to Run/Debug Configurations.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748120
