### ISSUE TITLE
[IntelliJ]"Report to Microsoft" could not open git

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2977]
Build: dev 1069

Repro Steps:
1. When pops error, click button "Report to Microsoft"
![image](https://user-images.githubusercontent.com/36756024/55526440-a7a83000-5684-11e9-8991-15fcb4554eeb.png)

Result:
Could not open git
In this case, it launch the following website that fail to launch git
https://github.com/Microsoft/azure-tools-for-java/issues/new?title=%5BIntelliJ%5D%5BReportedByUser%5D+Uncaught+Exception+get+applications+list+error+com.microsoft.azure.hdinsight.sdk.common.HDIException%3A+username+is+null%2C+please+call+getConfigurationInfo+first%0D&labels=IntelliJ%2Cbug&body=IntelliJ+build+version%3A+2019.1+IC-191.6183.62%0AOS%3A+Windows+10%0AJDK%3A+JetBrains+s.r.o+1.8.0_202-release%0APlugin+version%3A+3.20.0-LATEST-EAP-SNAPSHOT%0AAdditional+Info%3A+None%0AParent+component%3A+%0A%60%60%60%0Acom.intellij.openapi.wm.impl.IdeRootPane%5B%2C8%2C31%2C1440x796%2Clayout%3Dcom.intellij.openapi.wm.impl.IdeRootPane%24MyRootLayout%2CalignmentX%3D0.0%2CalignmentY%3D0.0%2Cborder%3D%2Cflags%3D449%2CmaximumSize%3D%2CminimumSize%3D%2CpreferredSize%3D%5D%0A%60%60%60%0AError+message%3A+%0A%60%60%60%0AIdeaLoggingEvent%5Bmessage%3Dget+applications+list+error%2C+throwable%3Dcom.microsoft.azure.hdinsight.sdk.common.HDIException%3A+username+is+null%2C+please+call+getConfigurationInfo+first%0D%0A%09at+com.microsoft.azure.hdinsight.sdk.cluster.ClusterDetail.getHttpUserName%28ClusterDetail.java%3A171%29%0D%0A%09at+com.microsoft.azure.hdinsight.spark.jobs.JobUtils.getEntity%28JobUtils.java%3A416%29%0D%0A%09at+com.microsoft.azure.hdinsight.spark.jobs.SparkRestUtil.getSparkRestEntity%28SparkRestUtil.java%3A146%29%0D%0A%09at+com.microsoft.azure.hdinsight.spark.jobs.SparkRestUtil.getSparkApplications%28SparkRestUtil.java%3A58%29%0D%0A%09at+com.microsoft.azure.hdinsight.spark.jobs.SparkJobHttpHandler.handle%28SparkJobHttpHandler.java%3A54%29%0D%0A%09at+com.sun.net.httpserver.Filter%24Chain.doFilter%28Filter.java%3A79%29%0D%0A%09at+sun.net.httpserver.AuthFilter.doFilter%28AuthFilter.java%3A83%29%

**Comment by v-jiche** [comment]
Fixed in Build: azure-toolkit-for-intellij-2019.1.develop.1082.04-12-2019
