### ISSUE TITLE
[intelliJ]Can not install intelliJ build

### ISSUE THREAD

**Issue by v-jiche** [Microsoft/azure-tools-for-java#2988]
Build:
19.1
azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.1070.04-04-2019
azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.1071.04-04-2019
azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.1072.04-04-2019
azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.1073.04-08-2019

Repro Steps:
Install the intelliJ build.

Result:
![image](https://user-images.githubusercontent.com/35950097/55706485-e981ff00-5a13-11e9-9503-b9ee09e95e70.png)

**Comment by t-rufang** [comment]
Fixed in #2987

**Comment by v-jiche** [comment]
Still repro on Linux and Windows.
Build: azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.1074.04-08-2019
intelliJ 19.1.

**Comment by t-rufang** [comment]
The fix is only included after build 1075. Please try build 1075.

![image](https://user-images.githubusercontent.com/32627233/55711218-db85ab80-5a1e-11e9-91c4-f31fb390ce8f.png)

**Comment by v-jiche** [comment]
Verified. Fixed.
Build: azure-toolkit-for-intellij-2019.1.develop.1075.04-08-2019
