### ISSUE TITLE
[Authentication]Failed to create Service Principle on subscription with Contributor role assigned

### ISSUE THREAD

**Issue by adashen** [Microsoft/azure-tools-for-java#299]
Steps:
1. Sign in and select automated
2. Click New to create new authentication file
3. In the Service Principle Creation Status dialog found fail for one subscription.
4. Go to Azure Portal, check the permission of this subscription and found "Your account 'XX@microsoft.com'  has been assigned the role 'Contributor' (type BuiltInRole) and has access to scope '/subscriptions/c83d7466-0b00-4222-ab9c-3b490bd06e0a'"
5. So it means actually the account has contributor role of the subscription which conflict with the status in the dialog

Failed in service principle status dialog

![image](https://cloud.githubusercontent.com/assets/1872137/24967798/238b7b40-1f60-11e7-8af7-483fd759e7bc.png)

The permission in azure portal 
![image](https://cloud.githubusercontent.com/assets/1872137/24967866/4e537b98-1f60-11e7-833b-b7a3ac5afd8e.png)

**Comment by vladimir-shcherbakov** [comment]
Acually, I see no issue here.
The plugin is trying to add the just created application as a contributor to the subscription Access Control list but fails as not authorized.
