### ISSUE TITLE
[IntelliJ][ReportedByUser] Azure create Web App exceptions can crash IDEA

### ISSUE THREAD

**Issue by yucwan** [microsoft/azure-tools-for-java#2991]
IntelliJ build version: 2019.1 IU-191.6183.87
OS: Win 10 Enterprise version 1809 build 17763.379
JDK: 1.8.0_201
Plugin version: 3.20.0-2019.1

Found this bug when deploying a web app to Azure. Whenever trying to create a new Web APP in a subscription without enough permission, action will fail with exceptions occurs. However, this will also freeze the two pop up dialogs (clicked on OK or Cancel and nothing happened), thus causing all IDEA windows unusable. Kill all IDEA  processes and restart can fix. 
![bug](https://user-images.githubusercontent.com/49381248/55769122-2bfa1900-5ab2-11e9-8688-4de725e64c5d.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738836
