### ISSUE TITLE
Wrong font in Azure Device Login dialog

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#2995]
### Environment:
```
Bits: Dev1077
OS: Windows10/Mac/Ubuntu
Eclipse: 2019-03
```

### Result:
Windows:
![image](https://user-images.githubusercontent.com/22470312/55855730-e36a5a80-5b9a-11e9-8202-aab0f838af61.png)
Mac:
![image](https://user-images.githubusercontent.com/22470312/55855735-e5341e00-5b9a-11e9-8e14-bf102a05852d.png)

### Expect:
 We should use the same (UI) font everywhere.

**Comment by wezhang** [comment]
As far as I know, it can't be since the different platform fonts have different copyrights. If we align it with IntelliJ UI font, it should be ok.
