### ISSUE TITLE
The prompt message in Azure Sign out dialogue is wrong

### ISSUE THREAD

**Issue by sallyur** [Microsoft/azure-tools-for-java#2996]
### Environment:
```
Bits: Dev1077
OS: Windows10/Mac/Ubuntu
Eclipse: 2019-03
```

### Actual result:
It prompts "Signed in using file 'null"":
![image](https://user-images.githubusercontent.com/28860891/55856317-82438680-5b9c-11e9-84d5-be45b78936b6.png)

### Expect result:
It should display account message like IntelliJ:
![image](https://user-images.githubusercontent.com/28860891/55856425-db131f00-5b9c-11e9-8b27-a7f75ad9a70b.png)

**Comment by bsaby** [comment]
The test passed.
Bits: daily724
