### ISSUE TITLE
Error importing subscriptions from publish settings file on Azure China

### ISSUE THREAD

**Issue by ShirleyCAT2016** [Microsoft/azure-tools-for-java#3]
When I tried to publish a "Dynamic Web project" to Azure Cloud Service, I got the following error:

C:\Users\shiwang\workspace\MyHelloWorld_onAzure\package.xml:158: com.microsoft.tooling.msservices.helpers.azure.AzureCmdException: Error importing subscriptions from publish settings file.

My Eclipse info:
- Azure Plugin for Eclipse with Java: 2.8.2
- Eclipse version: Mars. 1 Release (4.5.1)
- I set "windowsazure.cn(China)" in my project preference:
![preference](https://cloud.githubusercontent.com/assets/18413146/14450815/5f69bed6-00b4-11e6-9e85-70b7d5ed56b7.png)
- The publishsetting file I use:
<?xml version="1.0" encoding="utf-8"?>
<PublishData>
  <PublishProfile
    PublishMethod="AzureServiceManagementAPI"
    Url="https://management.core.chinacloudapi.cn"
    ManagementCertificate="xxxxkK0nkDWgaSjQQUsl0h9Rk08Fz7knFKjPvbgaKbgsQ=">
    <Subscription
      Id="03042fd8-7b09-4c73-9217-xxxxxxxx"
      Name="teamshare" />
  </PublishProfile>
</PublishData>

**Comment by pednekarprajakta** [comment]
Issue has been fixed in next version of the plugin. Azure Plugin for Eclipse with Java version 2.9.0 is available publically.

**Comment by ShirleyCAT2016** [comment]
Yeah. Just verified version 2.9.0 works fine! Thank you.
