### ISSUE TITLE
[intelliJ][right-click menu]There may be confusion about running configurations.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3000]
Build:
v3.20-2019.1

Repro Steps:
1. Create a new project and open Run/Debug Configurations.
2. Create a spark on cosmos configuration. 
![image](https://user-images.githubusercontent.com/35950097/55861779-b07b9300-5ba9-11e9-83de-2022fdffe924.png)
3. Create a spark on cosmos configuration.
![image](https://user-images.githubusercontent.com/35950097/55861750-a194e080-5ba9-11e9-981d-b458929a1733.png)
Result:
02 configuration shows here.
![image](https://user-images.githubusercontent.com/35950097/55862256-ae660400-5baa-11e9-981b-513209754cc1.png)
4. Right click LogQuery.

Result:
![无标题](https://user-images.githubusercontent.com/35950097/55862630-65627f80-5bab-11e9-87a8-e0f06718ee61.png)
  1.  For locally run/locally debug/select configuration, the configuration is 01 configuration.
  2. For spark job run configuration, the configuration is 02 configuration.
  3. However, user can not distinguish it from the right-click menu.

**Comment by v-jiche** [comment]
You can refer to bug #2999

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748119
