### ISSUE TITLE
[IntelliJ][Reader account] Should pops link dialog when click on hdinsight cluster

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#3004]
Build: Dev 1079

Repro Steps:
1. Sign in with reader account
2. Click on HDInsight cluster to expand

Result:
Nothing happened

Expect:
According to the doc, should pops link cluster dialog here
![image](https://user-images.githubusercontent.com/36756024/55941648-331d5480-5c75-11e9-9950-562eb16ef717.png)

**Comment by t-rufang** [comment]
Design changed. For now, `Jobs` node and `Storage Accounts` node will show up when cluster node is clicked. Please help verify the change.
