### ISSUE TITLE
[intelliJ]There are some problems when open job view.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3005]
Build:
artifacts/azure-toolkit-for-intellij-2019.1.develop.1079.04-10-2019.zip

Repro Steps:
1. Open Azure Explorer and expand HDInsight.
2. Click Jobs node under the cluster.
![image](https://user-images.githubusercontent.com/35950097/55952825-11c86280-5c8d-11e9-885c-2ec571db62dc.png)
Result:
Unable to switch tabs.
![1](https://user-images.githubusercontent.com/35950097/55952937-610e9300-5c8d-11e9-95ef-d5718ac10219.gif)
3. Click jobs node under the other clusters.
Result:
The switching of the job view is not smooth.
![2](https://user-images.githubusercontent.com/35950097/55953007-961ae580-5c8d-11e9-8a85-18e98061f972.gif)

**Comment by v-jiche** [comment]
The problem is also found in reader account.

Repro Steps:
1. Sign in with reader account,
2. Right click cluster and choose link this cluster.
3. Click Jobs node.

**Comment by t-rufang** [comment]
Hi @v-jiche Could you please check if this issue repro in the previous release `v3.20.0` plugin?

**Comment by v-jiche** [comment]
Bug repros in the release v3.20.0 plugin.
![2](https://user-images.githubusercontent.com/35950097/56193569-83285c80-6063-11e9-8d10-1d389266720f.gif)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748118
