### ISSUE TITLE
[IntelliJ]Show "Fails to get the sample resource folder for project." when you create a new project.

### ISSUE THREAD

**Issue by v-lanjli** [Microsoft/azure-tools-for-java#3008]
**Build:** 
artifacts/azure-toolkit-for-intellij-2019.1.develop.1082.04-12-2019.zip 
**IntelliJ Version:**
IntelliJ IDEA 2019.1
**OS:** Mac\Windows\Linux
**Spark Version:** 2.3.2

**Steps:**
**1.** Open the IntelliJ IDEA 2019.1
**2.** Create a new project.
**3.** Select 'Spark Project with Samples(Scala)'

**Results:**
Show "Fails to get the sample resource folder for project." when you create a new project.
![image](https://user-images.githubusercontent.com/40199316/56019824-3a596680-5d38-11e9-8fa6-58570f07e27b.png)

**Comment by wezhang** [comment]
Fixed

**Comment by v-lanjli** [comment]
Verified and Closed
