### ISSUE TITLE
Should validate username when creating a VM

### ISSUE THREAD

**Issue by aovechki** [microsoft/azure-tools-for-java#301]
win10, x64, Eclipse.Mars

Create new VM dialog allows to proceed when user enters "admin" as the username. Subsequently VM creation fails with an error that the admin username is not allowed. Would be better to validate user input prior to submission.

**Comment by andxu** [comment]
![image](https://user-images.githubusercontent.com/17075863/144178280-8c4b38d2-9139-468e-afa0-d873c3281324.png)
shall not allow

"administrator", "admin", "user", "user1", "test", "user2", "test1", "user3", "admin1", "1", "123", "a", "actuser", "adm", "admin2", "aspnet", "backup", "console", "david", "guest", "john", "owner", "root", "server", "sql", "support", "support_388945a0", "sys", "test2", "test3", "user4", "user5".

**Comment by andxu** [comment]
Category: "Validation in more scenarios"

**Comment by ivywei0125** [comment]
add validation rule for vm's username
https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines/create-or-update?tabs=HTTP#osprofile
