### ISSUE TITLE
[IntelliJ][Serverless]Set default type to None, local console do not allow to set to serverelss option

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3012]
Build: Dev 1082

Repro Steps:
0. Enable serverless feature with json file.
1. Create a new project, make sure there is no config file
2. Set default application type to None
3. Start Local console

Result:
Could not select serverless
![image](https://user-images.githubusercontent.com/36756024/56027587-ee62ed80-5d48-11e9-8346-bc3a0a7e1a13.png)

Expect: 
Serverless support local console, should allow to select serverless in this way.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748117
