### ISSUE TITLE
[intelliJ][Reader account]The link can not go back to the first scene.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3015]
Build:
azure-toolkit-for-intellij-2019.1.develop.1082.04-12-2019

Repro Steps:
1. Sign in azure with reader account.
2. Open Run/Debug Configurations.
3. Create a HDInsight configuration.
4. Choose  Spark clusters.
Result:
Warning message pops up. The color of Link the cluster displays as blue.
![image](https://user-images.githubusercontent.com/35950097/56030500-8f54a700-5d4f-11e9-9ab0-cee7424e8fb9.png)
5. Click Link the cluster.
Result:
It will take a long time to show the Link HDInsight Cluster window.
![image](https://user-images.githubusercontent.com/35950097/56030717-1f92ec00-5d50-11e9-9dab-b078aef533e2.png)
6. Click cancel to close Link HDInsight Cluster window.
Result:
The color of Link the cluster changes to purple and it would not be back to blue.
![image](https://user-images.githubusercontent.com/35950097/56030828-6bde2c00-5d50-11e9-9419-f6a13ab2d454.png)

Expectation:
1. Reduce response time for opening Link HDInsight Cluster window for the first time.
2. Should the color of Link the cluster be back to blue?

**Comment by t-rufang** [comment]
It's by design. The color of the link would change if it's clicked before
