### ISSUE TITLE
The text box to provide azure authentication file path is not editable

### ISSUE THREAD

**Issue by ghost** [Microsoft/azure-tools-for-java#302]
Issue:
The text box to provide authentication file in the automated sign in is not editable.

Expected:
User can directly paste the path to the authentication file or edit it in the text box.

Repro:
1. Create a Java web application in IntelliJ.
2. Tools->Azure->Azure Sign In.
3. Choose Automated and move focus to the text box.
<img width="470" alt="screen shot 2017-04-12 at 9 28 41 am" src="https://cloud.githubusercontent.com/assets/6917718/24968899/a79e923e-1f63-11e7-9321-8a4c88829b9a.png">

OS: macOS Sierra (10.12.4)

Subscription Type: Enterprise

IDE: IntelliJ Ultimate 2017.1.1

Plugin: azure-toolkit-for-intellij.2017.267.04-11-2017.zip

Feature: Authentication file path text box is not editable.

**Comment by martinsawicki** [comment]
true...

**Comment by vladimir-shcherbakov** [comment]
This is by design.

**Comment by vladimir-shcherbakov** [comment]
moved to backlog
