### ISSUE TITLE
[intelliJ][Reader account][Linux]Display errors in the Run/Debug Configurations window.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3025]
Build:
azure-toolkit-for-intellij-2019.1.develop.1087.04-15-2019

Repro Steps:
1. Open Run/Debug Configurations.
2. Create a HDInsight Configuration.
3. Choose Remotely run in Cluster.
3. Select an unlinked cluster.

Result:
The cluster display error.
![image](https://user-images.githubusercontent.com/35950097/56134515-51f75000-5fc1-11e9-913e-80f0287d9d90.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748116
