### ISSUE TITLE
Cannot sign in to company account in IntelliJ

### ISSUE THREAD

**Issue by JunyiYi** [Microsoft/azure-tools-for-java#303]
**OS**
Mac OS Sierra

**IntelliJ**
2016.3

**Plugin**
azure-toolkit-for-intellij.2016.79.04-12-2017.zip

**Feature**
Sign in

**Issue**
Cannot sign in to the company account.

1. Click *Tools*->*Azure*->*Azure Sign In...*
2. Click *Automated*->*New...*
3. Enter the credentials and approve the 2FA in mobile device
4. The dialog infinitely shows "in progress": *We've sent a notification to your mobile device. Please respond to continue*

**Comment by vladimir-shcherbakov** [comment]
We can't control browser communication with AD endpoint.

**Comment by JunyiYi** [comment]
It works now.

**Comment by vladimir-shcherbakov** [comment]
ok
