### ISSUE TITLE
[intelliJ][Azure Explorer]Display issues for jobs view.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3031]
Build:
azure-toolkit-for-intellij-2019.1.develop.1087.04-15-2019

Repro Steps:
1. Open Azure Explorer
2. Expand HDInsight
3. Click jobs node

Result:
1. The display is not clear.
![image](https://user-images.githubusercontent.com/35950097/56182254-dc809380-6043-11e9-82e8-49bb6bac38c9.png)
2. The content is beyond table borders.
![image](https://user-images.githubusercontent.com/35950097/56182287-0934ab00-6044-11e9-8aa6-9c9403ae2a9a.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748115
