### ISSUE TITLE
[IntelliJ] When submitting a job to HDI as a reader, the error message is not clear.

### ISSUE THREAD

**Issue by v-lanjli** [Microsoft/azure-tools-for-java#3036]

**Comment by v-lanjli** [comment]
**Build:** https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_develop/1092/artifacts/azure-toolkit-for-intellij-2019.1.develop.1092.04-16-2019.zip
**OS:** Win\OS\Linux

**Steps:**
1. Create a new 'Spark Project with Sample' project.
2. Submit the job to an unlinked cluster.

**Results:** Have error message: Exception without detail message.
**Expectation:** Need more detailed tips, like: **No permission to submit to the current cluster; Or the current cluster is not linked.**
![image](https://user-images.githubusercontent.com/40199316/56193682-cb477f00-6063-11e9-814a-0aa1976a7b2e.png)

**Comment by t-rufang** [comment]
Fixed in #3040

**Comment by v-lanjli** [comment]
Verified and closed
