### ISSUE TITLE
[Eclipse] Error icon should be hidden when creating docker host

### ISSUE THREAD

**Issue by xscript** [Microsoft/azure-tools-for-java#305]
- Issue Type: Creating docker host when deploy project as docker container
- How to repro:
  - Click `Deploy as docker container`
  - Add new docker host
  - In SSH section, click `Import from directory` and then click `Auto-generate`
- OS: Windows 10
- IDE: Eclipse Neon.3
- Plugin Version: WindowsAzurePlugin4EJ.271.04-11-2017.zip

![image](https://cloud.githubusercontent.com/assets/2300784/24969137/4297b81e-1fe2-11e7-9ce4-93714baf2860.png)

**Comment by milismsft** [comment]
Fixed; please verify.

**Comment by davidliangze** [comment]
Test passed.

OS: Windows 10 Enterprise x64 ENU
IDE: Eclipse Neon/ Mars
Plugin Version:

**Comment by davidliangze** [comment]
Test passed.

OS: Windows 10 Enterprise x64 ENU
 IDE: Eclipse Neon
 Plugin Version: WindowsAzurePlugin4EJ.319.04-17-2017
