### ISSUE TITLE
[intelliJ]Run/Debug Configurations window is stuck.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3053]
Build:
azure-toolkit-for-intellij-2019.1.develop.1097.04-17-2019

Repro Steps:
1. Create a HDInsight Configuration.
2. Click OK button to close Run/Debug Configurations window.
3. Reopen Run/Debug Configurations window immediately.

Repro Steps:
1. Open Run/Debug Configurations windows.
2. Try to create **some** configurations.

Result:
The Run/Debug Configurations window is stuck.
![image](https://user-images.githubusercontent.com/35950097/56277674-63626880-6137-11e9-8bda-f66d101f7f43.png)

Note:
1. When create new configuration from open Run/Debug Configurations window, the problem of being stuck is frequent.
2. Wait for some time, it returns to normal.

**Comment by t-rufang** [comment]
@v-jiche , could you help to verify if the status bar is showing something like "Refresh cluster list..." when run config UI get stuck?

**Comment by v-jiche** [comment]
![image](https://user-images.githubusercontent.com/35950097/57271749-47f9d600-70c3-11e9-8c72-edd066135339.png)
@t-rufang  This is the state.
