### ISSUE TITLE
[intelliJ][gen2 cluster]Can not save HDInsight configuration with empty access key.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3054]
Build:
azure-toolkit-for-intellij-2019.1.develop.1097.04-17-2019

Repro Steps:
1. Create a HDInsight Configuration.
Choose spark-230-gen2-yan for spark clusters.Select gen2 for Storage type. Input the **right** root path, Input 123 for access key.
![无标题](https://user-images.githubusercontent.com/35950097/56280224-55fbad00-613c-11e9-99b1-e698a04b2cfa.png)
2. Click OK button to save it.
3. Reopen Run/Debug Configurations to create a HDInsight Configuration .
Choose spark-230-gen2-yan for spark clusters.Select gen2 for Storage type. Input the **right** root path.
Result:
Access Key shows automaticallly.
![image](https://user-images.githubusercontent.com/35950097/56281008-1930b580-613e-11e9-9713-5aae70e6558f.png)
4.  In order to save the configuration with empty access key. Try to delete access key.
Result:
Can not save the configuration with empty access key.
![2](https://user-images.githubusercontent.com/35950097/56281291-d6bba880-613e-11e9-8ee5-cdd7ab8884ca.gif)
5. Create a new project then create a HDInsight configuration.
Choose spark-230-gen2-yan for spark clusters.Select gen2 for Storage type. Input the **right** root path.
Result:
The same result with step3 and step4.

Expectation:
Could save configuration with empty acess key.

**Comment by lcadzy** [comment]
After saving a configuration , storage account and access key is stored to intelliJ .
In this way, 
1.the next time we open the  configuration ,it shows again. 
2.once storage account is same which can be get from root path and access key is empty, we auto shows the key from intelliJ store which is by design.
