### ISSUE TITLE
[Eclipse] Nothing happens when publishing project as docker container

### ISSUE THREAD

**Issue by xscript** [Microsoft/azure-tools-for-java#306]
- Issue Type: Creating docker host when deploy project as docker container
- How to repro:
  - Click `Deploy as docker container`
  - Add new docker host
  - Configure the new docker host
  - Click `finish`. Nothing happened and nothing appears in Azure Activity log.
- OS: Windows 10
- IDE: Eclipse Neon.3
- Plugin Version: WindowsAzurePlugin4EJ.271.04-11-2017.zip

**Comment by milismsft** [comment]
duplicate of https://github.com/Microsoft/azure-tools-for-java/issues/329
