### ISSUE TITLE
[Eclipse]Unable to switch tabs in the job view.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3063]
Version: 2019-03 (4.11.0)
Build id: 20190314-1200

Repro Steps:
1. Open Azure Explorer.
2. Expand HDInsight.
3. Click Jobs node.

Result:
1. Jobs view show out and can not switch tabs.
2. Can not open the two link for history UI and Yarn UI.
![2](https://user-images.githubusercontent.com/35950097/56357763-3da89280-620f-11e9-9a41-022e183f0193.gif)

**Comment by t-rufang** [comment]
Duplicate with #3005

**Comment by t-rufang** [comment]
Close this issue since duplicate
