### ISSUE TITLE
[Eclipse]Main class is not match with the currently selected scala file.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3064]
Version: 2019-03 (4.11.0)
Build id: 20190314-1200

Repro Steps:
1. Create a Spark on HDInsight Cluster Run Sample(Scala) project.
![image](https://user-images.githubusercontent.com/35950097/56359667-cb3ab100-6214-11e9-9ebe-2e9bb2c4c6ca.png)
2. Right click SparkSQL_RDDRelation.scala scala file, Choose Run as/ Run Configurations.
![image](https://user-images.githubusercontent.com/35950097/56359720-ec030680-6214-11e9-98d8-27b3f6e455f3.png)
Result:
Main class is not the selected scala file.
![无标题](https://user-images.githubusercontent.com/35950097/56359846-51ef8e00-6215-11e9-8d80-cb3916246764.png)
3. Click search button to find the scala file.
![image](https://user-images.githubusercontent.com/35950097/56359962-98dd8380-6215-11e9-8929-358f07c1cee8.png)
Result:
Can not find the scala file.
![image](https://user-images.githubusercontent.com/35950097/56360003-c0cce700-6215-11e9-816d-b7678f57ccf4.png)
4. Create a new project named cjm03. Right click the scala file and choose Run as/Run Configuration.
Result:
It shows the last project's name.
![image](https://user-images.githubusercontent.com/35950097/56360152-4486d380-6216-11e9-8555-38509a424e59.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748112
