### ISSUE TITLE
[IntelliJ][Reader Account]Warning massage should be more accurate.

### ISSUE THREAD

**Issue by v-xiaocw** [Microsoft/azure-tools-for-java#3066]
Build: azure-toolkit-for-intellij-2019.1.develop.1102.04-18-2019

Repro Steps:
1.Create a new run configuration 
2.Select Spark230-gen2-yan as the target cluster
3.Hang the mouse over the red prompt and you can see a line of prompts
![image](https://user-images.githubusercontent.com/43333874/56410735-1b287080-6233-11e9-8751-0534799c872e.png)
Expectation:
The warning massage should be more accurate. 
Change it to"Please ask the administrator to upgrade your role to  **hdinsight cluster operator or contributor.**"

**Comment by t-rufang** [comment]
Wording is updated from our PM: `No Ambari permission to submit job to the selected cluster. Please ask the cluster owner or user access administrator to upgrade your role to HDInsight Cluster Operator in the Azure Portal, or link to the selected cluster`. 
Won't include `contributor` role in the wording from PM side.

**Comment by jingyanjingyan** [comment]
Fixed
