### ISSUE TITLE
[IntelliJ][ReaderAcct]Link one linked cluster might need useful message

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3067]
Build: https://azuredownloads.blob.core.windows.net/azuretoolkitforintellij/v3.21.0/azure-toolkit-for-intellij-2019.1.106.04-19-2019.zip 

Repro Steps:
1. Sign in account that include read-only cluster
2. Expand HDInsight node
3. Create HDInsight config, select the read-only cluster
4. Link cluster from config file
5. In the expanded HDInsight node, right click on the read-only cluster
6. Click "Link this cluster"
7. Enter valid username and password, click OK

Result: 
Nothing happened
![image](https://user-images.githubusercontent.com/36756024/56417560-daa51300-6283-11e9-8e73-3b881c2ba124.png)

**Comment by t-rufang** [comment]
Force refresh,

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748111
