### ISSUE TITLE
Minor UI issues on the Create Docker Host dialog

### ISSUE THREAD

**Issue by aovechki** [Microsoft/azure-tools-for-java#307]
win10, x64, Eclipse.Mars

Region list should be sorted
The default name should use a prefix that is more specific, as opposed to a generic "remotesystemstem460904"

**Comment by martinsawicki** [comment]
sounds like a dupe of another issue we discussed a few weeks ago - alphabetical would match the portal

**Comment by lenala** [comment]
Done for sorted region list.

**Comment by davidliangze** [comment]
Test passed.
Build used for IntelliJ: azure-toolkit-for-intellij.2017.282.04-13-2017
Build used for Eclipse Mars 2: WindowsAzurePlugin4EJ.286.04-13-2017
