### ISSUE TITLE
[IntelliJ]Refresh HDInsight will not update role change

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3071]
Build: https://azuredownloads.blob.core.windows.net/azuretoolkitforintellij/v3.21.0/azure-toolkit-for-intellij-2019.1.106.04-19-2019.zip 

Repro Steps:
1. Sign in with account that includes read-only cluster
2. In portal, change role to contributor; or add one more contributor role
3. Refresh HDInsight node

Result:
The cluster still is Reader role

Note:
Re-signin the role display correctly.

If the change is add/remove role assignment, refresh HDInsight node will take effect right away.
If the change is change role(Reader to contributor)/add one more role(First as reader, then add contributor role), refresh HDInsight note does not take effect. Need to sign out to take effect

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748110
