### ISSUE TITLE
unrelated folder is visible while searching blobs in azure blob container viewer

### ISSUE THREAD

**Issue by juniwang** [microsoft/azure-tools-for-java#308]
- issue type: minor issue
- IDE: Intellij 2017
- platform: Windows 10
- plugin version: azure-toolkit-for-intellij.2017.267.04-11-2017
- Repo steps: 
  - Open Azure explorer and select storage, View any blob container 
  - upload files both with and without folders. My hierarchy in my testing container:
      - /sub1/sub2/design.html
      - /CN-OSSLAB-9-26-2014-credentials.publishsettings
      - /ct.txt
  - input any string("CN" in my example) and click search
- expected: Only blob "CN-OSSLAB-9-26-2014-credentials.publishsettings" is displayed
- actual: the folder "sub1" is also visible
![2017-04-12_1002](https://cloud.githubusercontent.com/assets/8814383/24969884/2d5eb964-1f67-11e7-95eb-2e6cb688127a.png)

**Comment by martinsawicki** [comment]
minor inconvenience, can be addressed in the future

**Comment by Flanker32** [comment]
Storage explorer and related features has been removed in the latest release, close this issue
