### ISSUE TITLE
[Intellij][Spark on Cosmos] Extened properties dialog does not support Ctrl+C/V in a cell

### ISSUE THREAD

**Issue by konjac** [microsoft/azure-tools-for-java#3083]
![image](https://user-images.githubusercontent.com/2101973/56795012-11f65f80-6842-11e9-844c-91fab1b568e0.png)

Ctrl+C and Ctrl+V are copying and pasting a line. They are not working inside a cell.

**Comment by t-rufang** [comment]
You can use `contrl + shift + insert` to paste the value.
