### ISSUE TITLE
[Suggestion][Eclipse] storage account creation error doesn't appear in Azure Activity Log

### ISSUE THREAD

**Issue by xscript** [Microsoft/azure-tools-for-java#309]
- How to repro:
  - In Azure Explore, try to create a new storage account with a conflicting account name.
  - Error shows in the pop-up window. But it doesn't appear in Azure Activity log.
- OS: Windows 10
- IDE: Eclipse Neon.3
- Plugin Version: WindowsAzurePlugin4EJ.271.04-11-2017.zip

**Comment by xscript** [comment]
Nothing appears even when creation is successful.

**Comment by martinsawicki** [comment]
by design: activity log only shows app deployments
