### ISSUE TITLE
[intelliJ][Reader account]Suggest to add reader role in the Run/Debug Configuration window.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3091]
Build:
azure-toolkit-for-intellij-2019.1.develop.1111.04-29-2019

Repro Steps:
1. Sign in azure with reader account.
2. Open Run/Debug Configurations window.
3. Choose Remotely Run in Cluster.
4. Select a cluster for Spark Clusters.

Expectation:
Suggest to add reader role for reader clusters.
![image](https://user-images.githubusercontent.com/35950097/57188287-94f87380-6f2e-11e9-819f-bb6d62d4a3e4.png)

**Comment by t-rufang** [comment]
@v-jiche Do you mean that we should show the cluster as `spark22blobhdi  (Spark 2.2) (Role: Reader)`

**Comment by v-jiche** [comment]
Yes, @t-rufang

**Comment by t-rufang** [comment]
Thanks! This issue will be fixed in #3075

**Comment by t-rufang** [comment]
Fixed in #3075

**Comment by v-jiche** [comment]
Verified. Fixed.
Build:1115
