### ISSUE TITLE
[IntellJ][RunConf] Remote run should be displayed on the status bar

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3093]
**Build:**
https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_develop/1111/Azure/artifacts/azure-toolkit-for-intellij-2019.1.develop.1111.04-29-2019.zip

**Repro Steps:**

1. create a new project.
2. Select a file and right click.
3. Select "**Submit Spark Application**" in list.
4. Edit configuration, then click "**SparkJobRun**" or "**Apply**"
5. Check the job status bar.

**Results**: Job status bar has no changes.
![image](https://user-images.githubusercontent.com/40199316/57191712-35fd2380-6f5b-11e9-9c8e-93a0a9439570.png)

**Expectation:**
Suggest to display the status of the remote running job.
**Note: It is displayed on the status bar when running locally.**
![image](https://user-images.githubusercontent.com/40199316/57191781-e10ddd00-6f5b-11e9-87a0-84b1297e1fba.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748106
