### ISSUE TITLE
[IntelliJ][Reader Account]There is a spelling mistake in the warning.

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3094]
Build: azure-toolkit-for-intellij-2019.1.develop.1112.05-05-2019
Repro Steps:
1.Select a sign in cluster to create a run config 
2.Click Apply and SparkJobrun or OK then run button
Result:
Pops up a warning and there is a spelling mistake in the warning:
Should change ready-only to read-only 
![image](https://user-images.githubusercontent.com/43333874/57205815-0c9dc100-6f76-11e9-8d8e-9751adba2851.png)
![image](https://user-images.githubusercontent.com/43333874/57205819-17585600-6f76-11e9-9b7d-35b0082d8abf.png)

**Comment by t-rufang** [comment]
Fixed in #3100

**Comment by jingyanjingyan** [comment]
Fix in dev 1137, the message update as following
![image](https://user-images.githubusercontent.com/36756024/58606808-a6cffb00-82cf-11e9-94b8-e8d5e43fa2d3.png)

![image](https://user-images.githubusercontent.com/36756024/58606819-b3545380-82cf-11e9-83d6-af2e6c63f8c0.png)
