### ISSUE TITLE
Error Create Azure Deployment Projetc

### ISSUE THREAD

**Issue by Mickeyrr** [Microsoft/azure-tools-for-java#31]
good morning. In the week update the latest version of Azure Toolkit. Now I can not create a new Azure Deployment Project, I get an alert message with the caption "Project configuration files are not valid.Check your * .cscfg, * .csdef and * .xml files for syntax errors or other integrity issues"
![eclipseerrorazure](https://cloud.githubusercontent.com/assets/23528486/20398213/26d6147a-acb2-11e6-8455-609d5bf7beed.png)

**Comment by martinsawicki** [comment]
yep, our new build process broke it accidentally. It'd fixed now in the latest update (posted a couple of days ago)
