### ISSUE TITLE
[IntelliJ][Reader Account]The list of storage account types is different if link cluster from defferent entrances

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3104]
Build: azure-toolkit-for-intellij-2019.1.develop.1115.05-07-2019

Repro Steps:
1.Link a cluster from Azure Explorer HDInsight ,eg. spark23-hdi3-japan
2.Create a run config and select the linked cluster,eg.spark23-hdi3-japan
3.Click the drop-down button for the storage account to display four types.
Result:
![image](https://user-images.githubusercontent.com/43333874/57291231-e3635a80-7073-11e9-9300-bec3e773bc92.png)

Another situation:
1..Create a run config and  link a cluster at the prompt,eg.spark23-hdi3-japan
![image](https://user-images.githubusercontent.com/43333874/57289228-d6446c80-706f-11e9-8659-eda1bb448989.png)
2..Click the drop-down button for the storage account after linking successfully to display two types.
Result:
![image](https://user-images.githubusercontent.com/43333874/57290772-f9bce680-7072-11e9-831f-6d58399fdcac.png)
 Expectation:
The storage account type list should show consistent

**Comment by wezhang** [comment]
This is by design -- priority the storage type we can find

**Comment by t-rufang** [comment]
Fixed in #3109

**Comment by v-xiaocw** [comment]
Fixed in build dev 1124
