### ISSUE TITLE
[intelliJ][spark on cosmos]Get error message when submit job with clusters provisioned by others  

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3105]
Build:
1115

Repro Steps:
1. Create a cosmos configuration.
2. Choose a cluster provisioned by others.
![image](https://user-images.githubusercontent.com/35950097/57293417-477b3280-70f7-11e9-9c5c-223258ff0315.png)
3. Click icon to remotely run.
Result:
Get error message.
![image](https://user-images.githubusercontent.com/35950097/57293787-426ab300-70f8-11e9-8be0-a7da83b20266.png)
4. Click Ok button to close the window.
Result:
Get error message.
![image](https://user-images.githubusercontent.com/35950097/57293978-d472bb80-70f8-11e9-9162-fca67e01d1e2.png)
5. Open Run/Debug Configurations window, choose this cluster, then remotely run.
![image](https://user-images.githubusercontent.com/35950097/57293387-287ca080-70f7-11e9-8435-81c799491595.png)
Result:
Error message pops up.
![image](https://user-images.githubusercontent.com/35950097/57293362-16026700-70f7-11e9-9ed7-6e3760705020.png)

**Comment by wezhang** [comment]
I suppose it should be handled as an user error.

**Comment by wezhang** [comment]
@t-rufang , is it still repro?

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738949
