### ISSUE TITLE
cannot search blobs in sub folders in container viewer

### ISSUE THREAD

**Issue by juniwang** [microsoft/azure-tools-for-java#311]
- issue type: major feature issue
- IDE: Intellij 2017
- platform: Windows 10
- plugin version: azure-toolkit-for-intellij.2017.267.04-11-2017
- Repo steps: 
  - Open Azure explorer and select storage, View any blob container 
  - upload files both with and without folders. My hierarchy in my testing container:
      - /sub1/sub2/design.html
      - /CN-OSSLAB-9-26-2014-credentials.publishsettings
      - /ct.txt
  - input "design" and click search
- expected: blob "design.html" inside folder sub1/sub2 is displayed in the result window
- actual: it's nonvisible

**Comment by martinsawicki** [comment]
@lenala probably as old as the feature?

**Comment by Flanker32** [comment]
Storage explorer and related features has been removed in the latest release, close this issue
