### ISSUE TITLE
[intelliJ][Reader account]It is invalid to click refresh button.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3112]
Build:
azure-toolkit-for-intellij-2019.1.develop.1122.05-08-2019

Repro Steps:
1. Expand HDInsight node in Azure Explorer.
2. Open Run/Debug Configurations window
3. Create a HDInsight configuration.
4. Choose a cluster the stage of which is reader.
![image](https://user-images.githubusercontent.com/35950097/57373233-7910fe00-71ca-11e9-9998-92e87e0ce85d.png)
5. Link this cluster.
![image](https://user-images.githubusercontent.com/35950097/57373296-a2318e80-71ca-11e9-8b8c-55d406801b9d.png)
6. Close the Run/Debug Configurations window until link cluster successfully.
![image](https://user-images.githubusercontent.com/35950097/57373394-d311c380-71ca-11e9-92a8-f3d8203b32eb.png)
7. View HDInsight in Azure Explorer.
Result:
The state of the cluster is still reader role.
![image](https://user-images.githubusercontent.com/35950097/57373534-2f74e300-71cb-11e9-8edc-2d807427d86b.png)
8. Right click the cluster node then select refresh.
![无标题](https://user-images.githubusercontent.com/35950097/57373594-5a5f3700-71cb-11e9-8734-abb1a1bfcde2.png)
Result:
It does not work. The state can not change to linked.
![image](https://user-images.githubusercontent.com/35950097/57373647-7662d880-71cb-11e9-8907-04bffd8094dd.png)

Expectation:
HDInsight would refresh itself when the operation of linking a cluster is successful.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738948
