### ISSUE TITLE
[IntelliJ][Debug] Encounter Failed to create SSH session error when click re-debug button

### ISSUE THREAD

**Issue by t-rufang** [microsoft/azure-tools-for-java#3114]
Repro Steps:
1. Set up remote debug configurations for HDI cluster.
2. Click remote debug button. Wait for remote debug process successfully terminate.
3. Click re-run button. 
![image](https://user-images.githubusercontent.com/32627233/57428754-59c2b100-725c-11e9-96fe-0f84159519e1.png)
4. Error message pop up. However, I expect it should re-run debug process.
![image](https://user-images.githubusercontent.com/32627233/57428766-66dfa000-725c-11e9-98ab-43291f306d4a.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738947
