### ISSUE TITLE
[Eclipse] Newly created storage account doesn't show when creating VM

### ISSUE THREAD

**Issue by xscript** [Microsoft/azure-tools-for-java#312]
- How to repro:
  - Create a storage account first. And click the refresh button in Azure Explore.
  - Try to create a VM, but the new storage account doesn't appear in the storage account list.
- OS: Windows 10
- IDE: Eclipse Neon.3
- Plugin Version: WindowsAzurePlugin4EJ.271.04-11-2017.zip

**Comment by martinsawicki** [comment]
@lenala another caching issue?

**Comment by martinsawicki** [comment]
no caching for storage accounts. 
It's probably filtered out because of its type not being compatible with VMs or the region.
If this is due to the filtering, then keep as is. Maybe revisit in the future.

**Comment by lenala** [comment]
filtered based on this condition: (storageAccount.regionName().equals(model.getRegion().name())
                    && storageAccount.kind() == Kind.STORAGE
                    && storageAccount.sku().name() != SkuName.STANDARD_ZRS).
 As discussed, vm and storage account do not have to be in the same location, but it does not make sense to create vm with a storage account in a different location. Shall we remove filtering by region?
Zone-redundant storage cannot be used to create vm. Same behavior on the portal, and as far as I remember, there was exception when trying to create vm with zone-redundant storage account.

**Comment by lenala** [comment]
zone redundant storage account type is selected by default when creating storage account. Should other type be pre-selected? Currently default portal value is RA-GRS.

**Comment by martinsawicki** [comment]
- we can remove the location filter
- default storage account type: match portal defaults to make sure it is usable for VMs

**Comment by lenala** [comment]
Done, please verify.

**Comment by davidliangze** [comment]
Test passed.

OS: Windows 10 Enterprise x64 ENU
IDE: Eclipse Neon.3
Plugin Version: WindowsAzurePlugin4EJ.321.04-17-2017
