### ISSUE TITLE
[Eclipse] Cannot create new project when spark version is 2.3.2

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3121]
**Packages:** https://azuredownloads.blob.core.windows.net/eclipse/v3.15.0/
**Eclipse Version:** clipse for RCP and RAP Developers; Version: Oxygen.3 Release (4.7.3); Build id: 20180308-1800

**Steps:**

1. Open Eclipse.
2. Select **File**->**New**->**Project**.
3. **Use Maven to configure Spark SDK** select **Spark2.3.2**
![image](https://user-images.githubusercontent.com/40199316/57506548-b1315180-732e-11e9-8439-45cca9584397.png)
4. Click **Finish**
**Results:** No response.
5. Click **Back**
**Results:**An error dialog poop-up.
![image](https://user-images.githubusercontent.com/40199316/57506736-492f3b00-732f-11e9-8531-5c1f633650a8.png)

**Comment by t-rufang** [comment]
Hi @v-lanjli , could you please help verify if this issue still repro in the latest bits?

**Comment by v-lanjli** [comment]
Verified and fixed in this build (https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_develop/1135/Azure/artifacts/WindowsAzurePlugin4EJ.develop.1135.05-28-2019.zip)
Closed this issue.

**Comment by v-lanjli** [comment]
Sorry, I closed the wrong issue. This issue still repro in this build.(https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_develop/1135/Azure/artifacts/WindowsAzurePlugin4EJ.develop.1135.05-28-2019.zip)

**Comment by t-rufang** [comment]
@wezhang Currently for Eclipse user, if we create a new template project with sample codes and specify Spark version as 2.3.2, it will fail.

**Comment by v-lanjli** [comment]
Verified and fixed in https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_develop/1247/
Closed this issue.
