### ISSUE TITLE
Unable to terminate loading resource process if an exception occurs

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#3122]
### Environment:
```
OS: Windows10/Mac
Plugin version:
Azure java toolkit for IntelliJ: 3.22.0
Azure java toolkit for Eclipse: 3.15.0
JDK: oracle jdk8/11
```

### Result:
If an exception occurs while loading the resource, the user cannot terminate the loading process unless forced to exit the IDE.

Take the web app for example: 
Deploy web app: exception when updating Azure Local Cache, cannot cancel the process unless forced to exit IDE.
![image](https://user-images.githubusercontent.com/22470312/57507818-6d404b80-7332-11e9-839d-b54f9c85cbae.png)

**Comment by zmssp** [comment]
The same as 3116
