### ISSUE TITLE
[Docker Host]Should disable existing rg list in the default settings

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#3126]
This issue also reproduces in previous marketplace version.

### Repro Steps:
1. Right-Click `Docker Host` node in Azure Explorer
2. Select `New Host`
3. Switch to Resource Group tab

### Result:
The default radio button selected as default is `New resource group`, but I also can expand the existing resource group list.
![image](https://user-images.githubusercontent.com/22470312/57607625-0f17a080-759e-11e9-9726-4d01cc8e4a05.png)
### Expected:
![image](https://user-images.githubusercontent.com/22470312/57607767-5f8efe00-759e-11e9-8884-9e9d3e7d4f87.png)

**Comment by EricZhangzf** [comment]
Can not repro it on v3.37.0
