### ISSUE TITLE
[Docs][Price-Tier]Unclear description to pricing tiers

### ISSUE THREAD

**Issue by andxu** [microsoft/azure-tools-for-java#3129]
> It was quite difficult as a new user to Azure to understand the pricing tier when deploying to Azure. I was given the options for creating a VM on the Azure CLI, website and with the Azure Toolkit for IntelliJ.
> With a free tier, it was ambiguous as to what server is free for 12 months or the free trial as the website states the payments per hour/day and not clearly what was the free trial. Needs clearer descriptions
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 030836ed-1156-5711-95cc-fab5f1e114e9
> * Version Independent ID: eaeaf287-db87-a811-3e0b-00f3fb1c19a5
> * Content: [Create a Hello World web app for Azure using IntelliJ](https://docs.microsoft.com/en-us/java/azure/intellij/azure-toolkit-for-intellij-create-hello-world-web-app?view=azure-java-stable)
> * Content Source: [docs-ref-conceptual/intellij/azure-toolkit-for-intellij-create-hello-world-web-app.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-conceptual/intellij/azure-toolkit-for-intellij-create-hello-world-web-app.md)
> * Service: **app-service**
> * GitHub Login: @selvasingh
> * Microsoft Alias: **robmcm;asirveda**

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738835
