### ISSUE TITLE
[IntelliJ][Job View] Job view is blank and open Spark history UI from job view get exception.

### ISSUE THREAD

**Issue by t-rufang** [microsoft/azure-tools-for-java#3131]
Repro steps.
1. Click "Jobs" node for HDI 3.6 spark cluster.
2. We find the job view page is blank. However, we expect there are jobs listed in the job view page.
3. Click "Open Spark History UI" button in the job view page. There is an uncaught exception dialog.  However, we expect it should jump to spark history UI web page.

![image](https://user-images.githubusercontent.com/32627233/57769626-f8f61580-7740-11e9-887b-e5ac72cb4250.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738946
