### ISSUE TITLE
"Next" is enabled when there is no docker host in publish docker dialog

### ISSUE THREAD

**Issue by adashen** [Microsoft/azure-tools-for-java#314]
Steps
1. Right click the project -> azure -> publish as docker container
2. In the deploying docker container on azure dialog, there is no docker host listed. But the "Next" button is enabled and there is no warning message
3. Click Next to the next page. 
4. Click Finish -> The dialog will not close, however the values in the dialog will change.

![image](https://cloud.githubusercontent.com/assets/1872137/24971027/4980098c-1f6b-11e7-85f1-6b990b807122.png)

**Comment by martinsawicki** [comment]
the shaking is standard IntelliJ behavior (instead of disabling the button neecssarily) but the values shouldn't be changing

**Comment by selvasingh** [comment]
@milismsft should investigate, we have solved similar problems before in Eclipse

**Comment by milismsft** [comment]
Fixed; please verify.

**Comment by davidliangze** [comment]
Test passed.
The Next button is not available while no docker hosts listed in the dialog.

OS: Windows 10 Enterprise x64 ENU
IDE: Eclipse Neon
Plugin Version: WindowsAzurePlugin4EJ.307.04-16-2017
