### ISSUE TITLE
[IntelliJ][Mac][Spark on HDInsight] SparkCore_WasbIOTest always failed when remote run and locally.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3143]
**build**: https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_develop/1129/Azure/artifacts/azure-toolkit-for-intellij-2019.1.develop.1129.05-20-2019.zip
**OS**: Mac

**Steps**: 

1. Create a new **Spark Project with Samples (Scala)**.
2. Local Run and Remote run **[Spark on HDInsight] SparkCore_WasbIOTest**.

**Results:** Running failed.
**Local Run**:
![image](https://user-images.githubusercontent.com/40199316/58314707-a9030700-7e42-11e9-8340-2b7fbbaabe47.png)
**Remote Run:**
![image](https://user-images.githubusercontent.com/40199316/58314769-c637d580-7e42-11e9-9b0c-3b0401acfb3c.png)

**Comment by t-rufang** [comment]
This is supposed to be a user error.
![image](https://user-images.githubusercontent.com/32627233/58447190-3b9ef100-8136-11e9-908d-81ffef8b4242.

**Comment by v-lanjli** [comment]
Closed this issue.
