### ISSUE TITLE
[IntelliJ] stuck during deployment of Java web app

### ISSUE THREAD

**Issue by Jh4ck** [microsoft/azure-tools-for-java#3144]
Azure Toolkit for IntelliJ Version: v3.22.0-2019.1
IntelliJ version:
IDEA 2019.1.2 (Community Edition)
Build #IC-191.7141.44, built on May 7, 2019
JRE: 1.8.0_202-release-1483-b49 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Repro steps:

- Run Azure deployment from IntelliJ
![image](https://user-images.githubusercontent.com/6827784/58329129-1c514c80-7e34-11e9-9fe8-cb40ac2ce36e.png)

- Deployment is stuck
![image](https://user-images.githubusercontent.com/6827784/58329186-3e4acf00-7e34-11e9-8c7c-9cc87896551b.png)

- By checking via FTP, the file is created with size 0 bytes
![image](https://user-images.githubusercontent.com/6827784/58329220-53bff900-7e34-11e9-869a-7c6885bed8a4.png)

**Comment by yucwan** [comment]
@zmssp @andxu

**Comment by andxu** [comment]
@Jh4ck  Could you please try our latest version which has already switched to kudo deploy (HTTPS) from ftp, and tell us whether you can deploy or not?
