### ISSUE TITLE
[intelliJ][Spark on Cosmos]Can not submit with correct cluster  when provision several clusters of the same name.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3149]
Build:
azure-toolkit-for-intellij-2019.1.develop.1133.05-24-2019

Repro Steps:
1. Provision several clusters of the same name.
![无标题](https://user-images.githubusercontent.com/35950097/58468150-9dc81800-816f-11e9-9f35-72819fe126ea.png)
2. Open Run/Debug Configurations window, then click OK button to save the configuration.
3. Choose cluster provisioned in sparkwatchdog-c14.
![image](https://user-images.githubusercontent.com/35950097/58468377-031c0900-8170-11e9-976e-c018221996bb.png)
4. Reopen Run/Debug Configurations window.
Result:
The spark cluster becomes the cluster provisioned in sparkwatchdog-c11.
![image](https://user-images.githubusercontent.com/35950097/58468518-45454a80-8170-11e9-9db8-7a836f20d8e3.png)
5. Choose cluster provisioned in sparkwatchdog-c15 then save it.
![image](https://user-images.githubusercontent.com/35950097/58468610-73c32580-8170-11e9-9daf-e3ad096f8dc6.png)
6. Reopen the Run/Debug Configurations window.
Result:
The spark cluster becomes the cluster provisioned in sparkwatchdog-c11.
![image](https://user-images.githubusercontent.com/35950097/58468694-9d7c4c80-8170-11e9-8663-ac326fbf5c8f.png)

**Comment by t-rufang** [comment]
Add @konjac to help take a look at this issue.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738944
