### ISSUE TITLE
cannot create storage account in existing resource group

### ISSUE THREAD

**Issue by juniwang** [Microsoft/azure-tools-for-java#315]
- issue type: major issue.
- IDE: Intellij 2017
- platform: Windows 10
- plugin version: azure-toolkit-for-intellij.2017.267.04-11-2017
- Repo steps: 
  - click "Create Storage Account" in Azure explorer
  - input the storage account name and leave all the dropdown items as the default value
  - click Use Existing
- expected result: the OK button is enabled 
- actual: the OK button is disabled so I cannot proceed.

![2017-04-12_1031](https://cloud.githubusercontent.com/assets/8814383/24971183/d5e689e6-1f6b-11e7-9639-3a6b6127e91d.png)

**Comment by martinsawicki** [comment]
OK shoudl be enabled when ready to go

**Comment by lenala** [comment]
This is fixed, please verify.

**Comment by davidliangze** [comment]
Test passed.

OS: Windows 10 Enterprise X64 ENU
IDE: IntelliJ 2017.1.1
Test build: azure-toolkit-for-intellij.2017.303.04-16-2017
