### ISSUE TITLE
[IntelljJ][ReferProject]When the storage type is USE ADLS GEN 2 to upload, the selectable items are not displayed in the path selection dialog of the referenced jars.

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3150]
Build: azure-toolkit-for-intellij-2019.1.develop.1135.05-28-2019

Repro Steps:
1.Create a new project for ReferProject test
2.Select  zhouyhdi36gen2si as the target cluster
3.Select use ADLS Gen 2 to upload as storage type and fill in the root path and key
4.Click the folder icon at the right of the Referanced Jars

Result:
![image](https://user-images.githubusercontent.com/43333874/58468757-00c79980-80f3-11e9-9ad8-7c9665e48c17.png)

**Comment by lcadzy** [comment]
![image](https://user-images.githubusercontent.com/43339305/58477864-33bb6d00-8187-11e9-94aa-8c1f89986c18.png)

First make sure you input the right root path and access key.
Then the folders can be shown only the **upload path** text is ready ,so if you instantly click the button ,it won't work. Please retry.

**Comment by v-xiaocw** [comment]
@lcadzy  Sorry ,it caused by the wrong access key
