### ISSUE TITLE
[IntelliJ][ReferProject] It is recommended that after switch to another cluster, the warning message is displayed after click the "Apply" button and the "OK" button.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3151]
**Build:** azure-toolkit-for-intellij-2019.1.develop.1135.05-28-2019

**Repro Steps:**
1. Create a new project for ReferProject test.
2. Open Run\Debug Configuration.
3. Select zhouyhdi36gen2si as the target cluster, click Apply button.
4. Switch to another cluster, e.g spark22blobhdi
5. Click Apply and OK button.

**Results:** No warning message.
Currently, the warning message is displayed only when you click the folder icon to the right of Referenced Jars after switching clusters.
**Expectation:** The warning message is displayed when the configuration is saved.

**Comment by lcadzy** [comment]
It is by design.Once user click the folder icon then we check whether it is supported ,the warning message pop .Because user can also input jars by hand.

**Comment by v-lanjli** [comment]
Close this issue because this is by design.
