### ISSUE TITLE
[IntelliJ][Mac][ReferProject] The file inside the container cannot be loaded.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3152]
**Build:** azure-toolkit-for-intellij-2019.1.develop.1135.05-28-2019
**OS**: Mac

**Repro Steps:**

1. Create a new project for ReferProject test.
2. Open Run\Debug Configuration.
3. For Storage Type, select **Use ADLS Gen 2 to upload**.
4. Enter the correct **Root Path** and **Access Key**.
5. Click the folder icon to the right of Referenced Jars.

**Results:** The file inside the container cannot be loaded.
**Note**: If you not repro it on your side, you can turn off the select path dialog and reopen it. Repeat this step and try several times.
![image](https://user-images.githubusercontent.com/40199316/58474812-cefc1480-817e-11e9-8726-66f075423b5b.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738943
