### ISSUE TITLE
[IntelliJ]Show Azure Plugin for IntelliJ Error when input a wrong root path with a linked gen2 cluster

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3153]
**Build**: azure-toolkit-for-intellij-2019.1.develop.1135.05-28-2019

**Repro Steps**:

1. Link a gen2 cluster, and use this linked cluster as the target cluster.
2. For Storage Account, select **Use ADLS Gen 2 to upload**.
3. For Root Path, enter a wrong path.
4. Enter the correct Accesskey.
5. Click Apply button and OK button.
6. Run this Configuration.

**Results:** Show Azure Plugin for IntelliJ Error dialog.
![image](https://user-images.githubusercontent.com/40199316/58475867-b2151080-8181-11e9-90a7-9ae88fb67ade.png)

**Comment by t-rufang** [comment]
Fixed in #3157

**Comment by jingyanjingyan** [comment]
Fix in dev 1137, after submit, get the warning below.
Package and deploy the job to Spark cluster
ERROR: Failed to upload Spark application artifacts. ADLS Gen2 root path does not match with access key.
