### ISSUE TITLE
[Eclipse]Launch config for the first time, reader role cluster does not have link cluster entry

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3154]
Build: dev 1135

Repro Steps:
1. Sign in reader account
2. Right click on project, click submit to pops the config dialog

Result:
The reader role cluster does not have link cluster entry
After choose another reader role cluster, the link "link cluster" display well
![image](https://user-images.githubusercontent.com/36756024/58527851-f4346580-8206-11e9-9adb-619eebdf01e0.png)

**Comment by t-rufang** [comment]
Fixed in #3160

**Comment by jingyanjingyan** [comment]
Fix in dev 1137
