### ISSUE TITLE
[IntelliJ]Cancel select jar will clear existing input

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3155]
Build: dev 1135

Repro steps:
1. Sign in 
2. Create a hdinsight config, select gen2 cluster
3. Select valid jar file
4. Click the folder icon of the select jar file command
5. Just cancel

Result:
The existing jar value will be cleared

Expect:
Cancel should not clear existing value

**Comment by t-rufang** [comment]
Fixed in #3157

**Comment by jingyanjingyan** [comment]
Fix in dev 1137
