### ISSUE TITLE
[IntelliJ] Click ref-jar-folder-icon when refreshing will make intellij stuck

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3156]
Build: dev 1135

Repro Steps:
1. Create a hdinsight config
2. Select gen2 cluster, the upload path updated right
3. Select a cluster that never been used，the upload path still display with gen2
4. Click the folder icon of "Reference jar"

Result:
IntelliJ stuck
![image](https://user-images.githubusercontent.com/36756024/58535449-9d3b8a00-8220-11e9-85ec-203145b64b81.png)

**Comment by t-rufang** [comment]
We need to investigate why the stuck happens

**Comment by lcadzy** [comment]
Fixed in #3166

**Comment by jingyanjingyan** [comment]
Fix with dev 1140
