### ISSUE TITLE
[intelliJ]Get warning message sometimes when submit job.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3158]
Build:
develop 1135

Repro Steps:
1. Create a hdinsight configuration.
2. Choose main class and select cluster.
3. Click icon to remotely run.

Result:
Get warning message.
![image](https://user-images.githubusercontent.com/35950097/58548310-aa19a700-823b-11e9-9b72-06abc3035d0f.png)

Frequency:
Sometimes.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738942
