### ISSUE TITLE
[intelliJ]Run/Debug Configurations window blocks when switch cluster then select jar package.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3159]
Build:
develop 1135

Repro Steps:
1. Add the jar package for intelliJ.
2. Add the new LogQuery file to the project.
3. Create a HDInsight configuration, choose main class.
4. Choose a cluster for Spark clusters which is not gen2 cluster.
5. Click icon to select jar package for Referenced jars.
Result:
Waring message pops up.
6. Click Ok button to close the warning message.
7. Repeat the step4, step5 and step6.
Result:
Run/Debug Configuraions window blocks.

**Comment by lcadzy** [comment]
#3166

**Comment by v-jiche** [comment]
Still repro in build: 1140 develop.

**Comment by lcadzy** [comment]
#3247

**Comment by lcadzy** [comment]
Block is caused by preparing upload path delay which is by design. Refine this scenario to give more useful hint.

**Comment by v-jiche** [comment]
Build:
azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.1172.07-10-2019

I can still repro it on Linux and windows, and I will track the bug.

**Comment by v-jiche** [comment]
Build:
azure-toolkit-for-intellij-2019.2.4.develop.1342.01-08-2020

Fixed. Verified.
