### ISSUE TITLE
The Create Storage window won't get closed automatically after clicking OK

### ISSUE THREAD

**Issue by juniwang** [Microsoft/azure-tools-for-java#316]
- issue type: minor display issue.
- IDE: Intellij 2017
- platform: Windows 10
- plugin version: azure-toolkit-for-intellij.2017.267.04-11-2017
- Repo steps: 
  - click Create Storage Account in Azure explorer
  - input storage account name and resource group name, leave other fields as it is
  - Click OK button
- Expected: The Create Storage Account window get closed automatically or some tips is shown.
- Actually: The window remains and no dialog is shown so I clicked the OK button again which leading to another display issue. I manually close the Create Storage Account dialog and open it again. At this time the resource group created previously is shown twice while actually only one get created on Azure.

![2017-04-12_1042](https://cloud.githubusercontent.com/assets/8814383/24971699/b1df1fac-1f6d-11e7-84de-06c5d44b31c0.png)
![2017-04-12_1042_001](https://cloud.githubusercontent.com/assets/8814383/24971698/b1c4cbac-1f6d-11e7-9699-3ace1a8fd5d4.png)

**Comment by martinsawicki** [comment]
sounds like OK should be disabled when there is no name

**Comment by lenala** [comment]
Fixed, please verify.

**Comment by davidliangze** [comment]
Test passed.

•IDE: IntelliJ  2017.1.1
•platform: Windows 10 Enterprise
•plugin version: WindowsAzurePlugin4EJ.307.04-16-2017
