### ISSUE TITLE
[Eclipse][Mac] 'Link this cluster' is truncated in spark submission dialog.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3163]
**Build:** https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_develop/1138/Azure/artifacts/WindowsAzurePlugin4EJ.develop.1138.05-30-2019.zip
**OS:** Mac

**Repro Steps:**

1. Submit Spark Application to HDInsight.
2. Select a cluster as reader role.

**Results:** 'Link this cluster' is truncated
![image](https://user-images.githubusercontent.com/40199316/58612070-e274c000-82e3-11e9-8526-e0c22e989a1c.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738941
