### ISSUE TITLE
[Eclipse]Can not show the result of submiting job.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3170]
Build: 
https://azuredownloads.blob.core.windows.net/eclipse/v3.16.0/

Result:
1. Create a project.
2. Open Spark Submision windows.
3. Submit the job.
Result:
The result of the submision shows out.
4. **Close the Spark Submision windows.**
5. Submit the job.
6. Reopen the Spark Submision windows.
Result:
Can not see any result.
7. Restart Eclipse.
8. Submit the job. (**The state of Spark Submision windows is opening now** )
Result:
The result of the submision shows out again.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738939
