### ISSUE TITLE
[Eclipse]Cluster name can not show completely.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3171]
Build:
WindowsAzurePlugin4EJ.develop.1140.05-30-2019

Repro Steps:
1. Right click project to submit.

Result:
![image](https://user-images.githubusercontent.com/35950097/58691878-db22e480-83bf-11e9-9212-352798c89f18.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738938
