### ISSUE TITLE
[Eclipse][Linux only]Failed to submit project.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3172]
Build:
WindowsAzurePlugin4EJ.develop.1140.05-30-2019

Repro Steps:
1. Right click project to submit.
2. Choose a cluster to submit.
The state of the cluster is linked or normal.

Result:
Failed to submit.
![image](https://user-images.githubusercontent.com/35950097/58692327-fe01c880-83c0-11e9-85cd-ec5652af8daa.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738937
