### ISSUE TITLE
Cannot create VM using custom images

### ISSUE THREAD

**Issue by juniwang** [Microsoft/azure-tools-for-java#318]
- issue type: critical issue.
- IDE: Intellij 2017
- platform: Windows 10
- plugin version: azure-toolkit-for-intellij.2017.267.04-11-2017
- Repo steps: 
  - Click Create VM in Azure explorer
  - On the second step, select Custom Image
- Expected result: The Next button is enabled
- Actual: It's disabled.

![2017-04-12_1058_001](https://cloud.githubusercontent.com/assets/8814383/24972232/8972d03e-1f6f-11e7-8b0d-d91a4fe2e669.png)

**Comment by lenala** [comment]
duplicate to #322 - should be fixed now, please verify.

**Comment by juniwang** [comment]
fixed
