### ISSUE TITLE
Still can connect to log streaming after turn off web app streaming log on portal

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-tools-for-java#3194]
### Environment:

1. OS: Windows10/Mac/Linux
2. IntelliJ 2019.1.x/2018.3.x
3. Bits: PR/3491
4. JDK: Oracle JDK8/11

### Reproduce Step:
1. Deploy a web app on Azure and enable app service log feature.
2. Start streaming logs of this web app.
3. Turn off web server logging on the portal after connecting to log-streaming service.

### Result:
Plugin disconnects from log-streaming service automatically.
But click start streaming logs to start again now, it still can connect to log stream service successfully.
![image](https://user-images.githubusercontent.com/41051257/59667567-8a95ee80-91e9-11e9-880d-2ee777b425e5.png)

**Comment by ZhengJun003** [comment]
Can reproduce this issue in azure toolkits for IntelliJ 3.38.0

![image](https://user-images.githubusercontent.com/41051257/84639211-a92ce380-af2a-11ea-85a5-95cd6f763d6b.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738802

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
