### ISSUE TITLE
Azure streaming log tool window issue

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-tools-for-java#3196]
### Environment:

1. OS: Windows10/Mac/Linux
2. IntelliJ 2019.1.x/2018.3.x
3. Bits: PR/3491
4. JDK: Oracle JDK8/11

### Reproduce step:
1. Deploy a web app to azure after install plugin.
2. Right-click web app node and click start streaming log, the toolkit will open a console in Azure Streaming Log Tool window and show logs like this:
![image](https://user-images.githubusercontent.com/41051257/59664666-1016a000-91e4-11e9-84e4-e9cc08b4b119.png)
3. Click 'X' of your web app streaming log window, it shows like this and always initializing.
![image](https://user-images.githubusercontent.com/41051257/59664958-97641380-91e4-11e9-9502-ea6f28656bb2.png)
4. Click 'X' of streaming log tool window, it shows like this:
![image](https://user-images.githubusercontent.com/41051257/59665139-eca02500-91e4-11e9-994a-4eb8064d6ceb.png)
5. Right-click web app node and click start streaming log again, it shows like this:
![image](https://user-images.githubusercontent.com/41051257/59665278-2b35df80-91e5-11e9-9fe5-6164591462ed.png)

### Expect:
![image](https://user-images.githubusercontent.com/41051257/59665320-3db01900-91e5-11e9-94a9-e418b101eaa0.png)

![image](https://user-images.githubusercontent.com/41051257/59665418-718b3e80-91e5-11e9-90e1-2a06c38450e4.png)

**Comment by Flanker32** [comment]
Fixed in latest build
