### ISSUE TITLE
Error while trying to check for tools-update in Eclipse: "Unable to read repository..."

### ISSUE THREAD

**Issue by hsirtl** [Microsoft/azure-tools-for-java#32]
Checking for updates of the Azure Tools from within Eclipse leads to the following error:

Unable to read repository at https://dl.microsoft.com/eclipse/compositeContent.xml.
hostname in certificate didn't match: <dl.microsoft.com> != <*.azurewebsites.net> OR <*.azurewebsites.net> OR <*.scm.azurewebsites.net> OR <*.azure-mobile.net> OR <*.scm.azure-mobile.net>

**Comment by martinsawicki** [comment]
i have not been able to reproduce this issue..

**Comment by hsirtl** [comment]
Tried it again. Same result. I get this error dialog:
![image](https://cloud.githubusercontent.com/assets/1764309/20456542/d099c08e-ae78-11e6-8ff4-f6e8653b3994.png)

I entered the URL in several browsers (Chrome, IE, ...), always with a certificate error. Chrome example:
![image](https://cloud.githubusercontent.com/assets/1764309/20456578/8bc0dcda-ae79-11e6-914f-167e06ae0b71.png)

**Comment by martinsawicki** [comment]
the team that owns the site has been contacted about this.

having said that, why are you accessing the update site via https://?  Tried http://?  That's the published URL.

**Comment by hsirtl** [comment]
Hi,
I'm terribly sorry. Must have been a mistake on my side. Yes, http:// works fine.
I can't tell whether I really used https for installing and the update (where you don't enter a URL) trying to access https.
Anyway, it works (installing and updating). Thanks so much.
Kind regards,
Holger

**Comment by martinsawicki** [comment]
glad it worked out.
