### ISSUE TITLE
cannot search image when Create VM

### ISSUE THREAD

**Issue by juniwang** [microsoft/azure-tools-for-java#320]
- issue type: major improvement
- IDE: Intellij 2017
- platform: Windows 10
- plugin version: azure-toolkit-for-intellij.2017.267.04-11-2017

While creating a new VM, the recommended image list is really short and I usually cannot find the one I want. And for the custom image, the publisher list is too long to find something. I would suggest to adding a search feature to either search image by name or by publisher

**Comment by andxu** [comment]
Already implemented:
![image](https://user-images.githubusercontent.com/17075863/144178791-968eb3c9-ebe4-42d5-a02b-fa8b55f36f0c.png)
