### ISSUE TITLE
[Eclipse]Submit to MFA ESP cluster fails

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3203]
Build: Dev 1150

Repro Steps:
1. Submit script to a linked ESP cluster

Result:
Error
Error : Failed to submit application to spark cluster. Exception : com.microsoft.azure.hdinsight.sdk.common.errorresponse.UnclassifiedHttpErrorStatus:

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738936
