### ISSUE TITLE
Issues launching web browser from the Azure Explorer

### ISSUE THREAD

**Issue by aovechki** [Microsoft/azure-tools-for-java#321]
win10, x64, Eclipse.Mars

There are a couple of issues when trying to use Open in Browser menu command to open a web app from the Azure Explorer.

1. Eclipse is configured to use the default browser (Chrome on my system)
Nothing happens when clicking on the Open in Browser context menu

2. Eclipse is configured to use Internet Explorer
The web site opens in IE, but when IE window is subsequently closed, there is an error message: 
![ie](https://cloud.githubusercontent.com/assets/21356612/24972506/82ef4f0c-1f70-11e7-8def-5e9599bc1dbc.PNG)

**Comment by vladimir-shcherbakov** [comment]
@aovechki can you please check the link in Deploy Web App dialog

![image](https://cloud.githubusercontent.com/assets/6579928/24973078/5c3607a0-1f72-11e7-84dd-4ca66f8fd746.png)

**Comment by vladimir-shcherbakov** [comment]
Can't get repro.

Eclipse Java EE IDE for Web Developers.

Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600

@bsaby please verify.

**Comment by martinsawicki** [comment]
shippable either way, since it's not preventing a user scenario

**Comment by bsaby** [comment]
win10, x64, Eclipse.Mars.2
Not repro. Both Chrome and Internet Explorer are work fine.
Use artifacts/WindowsAzurePlugin4EJ.286.04-13-2017.zip.
