### ISSUE TITLE
Azure login not possible with "Device Login"

### ISSUE THREAD

**Issue by ChelbTerem** [microsoft/azure-tools-for-java#3213]
I'm currently developing an azure function with java and IntelliJ. In order to deploy my code / the artifact to azure, I installed the plugin "Azure Toolkit for IntelliJ" (Version: v3.23.0-2019.1). 

Prior deploying, the plugin tells me to login either via:

1. Device Login 
2. Service Principal

The 2nd of those options is not viable in our situation. Therefore I have to use the Device Login which will send me to an Microsoft Azure login page. After logging in, I get an error message that analogous reads: 

> "Your login was successfull. But your administrator has configured it in a way, that the requesting device has to be manged by "YOUR COMPANY" in order to access that resource".

After consulting with my administrator he told me that this configuration is right. But there shouldn't be an error at this point if all necessary informations would have been provided by IntelliJ/the plugin. As my administrator told me, the logs indicate that my "Device ID" is missing during the logon process and therefore I am recognized as an unknown device which is obviously not managed by "YOUR COMPANY".

**Comment by Flanker32** [comment]
@ChelbTerem Thanks for your feedback, this may more likely an issue of the auth method and could you please try sign in azure cli with device login? 
Here is the link for [azure cli](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest), you may use `az login --use-device-code` to sign in azure cli with device login.

**Comment by ChelbTerem** [comment]
@Flanker32 thank you for the quick response. Indeed, using the azure cli results in the same problem :-(

**Comment by yucwan** [comment]
@ChelbTerem by the way, in the log, "YOUR COMPANY" seems should be the name of your company which indicates that your subscription isn't well configured. If none of your colleges have successfully logged in with device login before, you may need to double check with your administrator about the configurations.

**Comment by ChelbTerem** [comment]
The text "YOUR COMPANY" is just a concealed placeholder. In my case, my company name is shown.

**Comment by donschoof** [comment]
We are facing the same problem. Device Code Login is not working when you have conditional access policies active that check for device compliance. When using device code login the device compliance is not checked in the process. The result is the error message you get. You can reproduce the result with every device code based login (like azure cli or VS Code). Only interactive login is working as expected at the moment with conditional access.

**Comment by Flanker32** [comment]
@ChelbTerem @donschoof We have released the support for Azure CLI credentials, you may get the release notes [here](https://github.com/microsoft/azure-tools-for-java/releases/tag/azure-intellij-toolkit-v3.39.0). You could sign in Azure CLI first with OAuth or other supported authentication method and then sign in IntelliJ toolkit with Azure CLI credential. Hope this could helps if you meet the same issue again.
