### ISSUE TITLE
Wrong default name for parameters file

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#3216]
### Environment: 
- OS: Windows/Mac/Linux
- JDK: 8/11
- IDE version: IU19.1.3/IC18.3.6
- Build:  PR3526
		
### Steps To Reproduce
1. View template file
2. Modify parameter file
3. Exit file
4. Click `Yes` in the following dialog
![image](https://user-images.githubusercontent.com/22470312/60565705-39642e00-9d97-11e9-927b-4e38d213cb4f.png)

### Result: 
![image](https://user-images.githubusercontent.com/22470312/60565712-3cf7b500-9d97-11e9-8972-6237b6b045bc.png)

### Expect
![image](https://user-images.githubusercontent.com/22470312/60565747-53057580-9d97-11e9-91e2-5f2e6a443f9c.png)

**Comment by Flanker32** [comment]
Fixed in https://github.com/microsoft/azure-tools-for-java/pull/3214

**Comment by bsaby** [comment]
The test passed.
Bits:  PR3516
![image](https://user-images.githubusercontent.com/22470312/60873677-543c1400-a269-11e9-9227-77d448a136f1.png)
