### ISSUE TITLE
Cannot widen the template file  area by manually dragging

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#3217]
### Environment: 
- OS: Windows/Mac/Linux
- JDK: 8/11
- IDE version: IU19.1.3/IC18.3.6
- Build: PR3526
		
### Steps To Reproduce
View template file
		
### Result: 
1. Unable to widen the template file area by manually dragging
![image](https://user-images.githubusercontent.com/22470312/60565878-c4ddbf00-9d97-11e9-928b-850ec08a46aa.png)
2.  If you increase the width by dragging the outermost border, the width of the template file area and parameters file area are relatively fixed at the beginning, but after reaching a certain width, the width of the former suddenly becomes larger, and the later suddenly becomes smaller.
the attachment is a video to repro the issue2.
[sizeissue.zip](https://github.com/microsoft/azure-tools-for-java/files/3353432/sizeissue.zip)

**Comment by Flanker32** [comment]
Fixed in #3214

**Comment by bsaby** [comment]
The test passed.
Bits: PR3561
