### ISSUE TITLE
Properties view UI issue

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-tools-for-java#3218]
### Environment:
OS: Mac/Linux
IntelliJ 2019.1.x/2018.3.6
Plugin version: Azure java toolkit for IntelliJ: PR/3526
JDK: Oracle JDK8/11

### Steps:

1. Click "View Template File" button
2. Return to the properties view

### Result:
this issue not stable reproduce on Mac
![image](https://user-images.githubusercontent.com/41051257/60566352-43872c00-9d99-11e9-9ce9-936be183e164.png)

**Comment by bsaby** [comment]
Now on windows, The UI issue can stably repro.
Bits: PR3628
### Repro steps:
1. Show properties:
![image](https://user-images.githubusercontent.com/22470312/61339866-640fb580-a872-11e9-8126-92753555ef0e.png)
2. Click `Edit Deployment` button
3. Switch back to the properties window
![image](https://user-images.githubusercontent.com/22470312/61339896-7f7ac080-a872-11e9-9790-9d272c1f3a8b.png)

**Comment by ZhengJun003** [comment]
Can reproduce this issue in azure toolkits for IntelliJ 3.38.0

![image](https://user-images.githubusercontent.com/41051257/84742938-cffb2080-afe3-11ea-9417-d242a94f709b.png)

![image](https://user-images.githubusercontent.com/41051257/84742982-dc7f7900-afe3-11ea-8915-54ac2a1f8950.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738768

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
