### ISSUE TITLE
cannot create VM

### ISSUE THREAD

**Issue by juniwang** [Microsoft/azure-tools-for-java#322]
- issue type: critical issue.
- IDE: Intellij 2017
- platform: Windows 10
- plugin version: azure-toolkit-for-intellij.2017.267.04-11-2017
- Repo steps: 
  - click Create VM in Azure Explorer
  - Select default region and image in the Select Image step
  - input VM name and username/password in the Machine Settings step
- expected: the Next button is enabled 
- actual: it's disabled

![2017-04-12_1108](https://cloud.githubusercontent.com/assets/8814383/24972600/d0ade938-1f70-11e7-96bd-98053eae4918.png)

**Comment by lenala** [comment]
There is empty "Confirm password" field below. Dialog can be resized to see it. So this is correct that Next and Finish disabled. @juniwang what is the resolution on your machine?

**Comment by juniwang** [comment]
1920*1080, x1 Carbon. I guess there should be a scroll bar for this case?

**Comment by lenala** [comment]
This is fixed, works on my Windows machine with high resolution.
@juniwang could you please verify for the latest build from http://13.88.12.33:8080/job/azure-toolkit-for-intellij-2017/ ?

**Comment by juniwang** [comment]
Yes, it's fixed. I can see a scrollbar now which indicates me that there are more fields to fill.
