### ISSUE TITLE
Inaccurate warning message when template file is not modified

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#3220]
### Environment:
OS: Windows/Mac/Linux
JDK: 8/11
IDE version: IU19.1.3/IC18.3.6
Build: PR3526
### Steps To Reproduce
1. View template file
2. Click on `Update Deployment `button

### Result:
The message is inaccurate because I have not modified the template file before.
![image](https://user-images.githubusercontent.com/22470312/60566567-d922bb80-9d99-11e9-86dd-4863b9960bb5.png)

### Expect
It would be better to change the warning message to: `Are you sure you want to update the deployment?`

**Comment by Flanker32** [comment]
Fixed in https://github.com/microsoft/azure-tools-for-java/pull/3214

**Comment by bsaby** [comment]
Bits: PR3561

Result: 
For the question message, should add `?` at the end of the sentence.
![image](https://user-images.githubusercontent.com/22470312/60873833-936a6500-a269-11e9-9493-9751f925fc90.png)

**Comment by bsaby** [comment]
3.24.0:
![image](https://user-images.githubusercontent.com/22470312/61194190-8c70a600-a6f2-11e9-9bc0-bf125542e31b.png)
