### ISSUE TITLE
[IntelliJ][aris]Missing main class and cluster after re-open IntelliJ

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3223]
Build: dev 1154

Repro Steps:
1. Create a new aris configuration with main class and cluster
2. Re-open IntelliJ

Result:
The main class and cluster is missing
![image](https://user-images.githubusercontent.com/36756024/60571049-60296100-9da5-11e9-8a67-408d3f60ed94.png)

**Comment by t-rufang** [comment]
Hi @jingyanjingyan , please help to check if this issue repro in the previous released plugin.

**Comment by jingyanjingyan** [comment]
The issue also happens with the last released build

**Comment by wezhang** [comment]
reproduced

**Comment by wezhang** [comment]
I can find the those configurations (`main-class` and `cluster_name`) in persistent .idea/workspace.xml file:

```
  <component name="RunManager" selected="Apache Spark on SQL Server Big Data Cluster.aris">
    <configuration name="aris" type="ArisOnSparkConfiguration" factoryName="Aris On Spark">
      <spark-job-configuration>
        <local-run>
          <spark-local-run-configurable-model>
...
            <main-class>sample.LogQuery</main-class>
...
          </spark-local-run-configurable-model>
        </local-run>
...
        <aris_spark_submission artifact_name="issues_3250_DefaultArtifact" cluster_name="13.68.227.206" is_local_artifact="false" job_name="aris" local_artifact_path="" classname="sample.LogQuery">
...
```

**Comment by v-jiche** [comment]
Build:
azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.1172.07-10-2019
azure-toolkit-for-intellij-2019.1.develop.1172.07-10-2019

Result:
![image](https://user-images.githubusercontent.com/35950097/60963839-7fdffc80-a344-11e9-9f76-4df33c804a50.png)
![image](https://user-images.githubusercontent.com/35950097/60963863-8bcbbe80-a344-11e9-8187-de49cd00b66b.png)

You can refer to bug #3260

**Comment by v-jiche** [comment]
Verified. Fixed.
Build:
azure-toolkit-for-intellij-2019.1.develop.1173.07-10-2019
azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.1173.07-10-2019
