### ISSUE TITLE
Weird tooltip text in the Azure Publish button

### ISSUE THREAD

**Issue by shsushi** [Microsoft/azure-tools-for-java#323]
Issue:
There's "()" in the tooltip text in both "Publish as Azure Web App" and "Publish as Docker Container".

Expected:
() should not occur in the tooltip text.

Repro:
1. Create a  Dynamic Web Project Eclipse Neon.
2. Click the dropdown list on toolbar for Azure:
3. Move the mouse to either of the menu item and wait for the tooltip to occur:
<img width="476" alt="screen shot 2017-04-12 at 11 03 14 am" src="https://cloud.githubusercontent.com/assets/6917718/24972441/48603162-1f70-11e7-990f-3700ec9389eb.png">

OS: macOS Sierra (10.12.4)

Subscription Type: Enterprise

IDE: Eclipse Neon.3

Plugin: WindowsAzurePlugin4EJ.273.04-12-2017.zip

Feature: Publish as "Azure Web App" or "Docker Container".

**Comment by davidliangze** [comment]
Test passed.

We don't have machines with Mac OS.
OS: Windows 10 Enterprise X64 ENU
IDE: Eclipse Neon.3
Test build: WindowsAzurePlugin4EJ.307.04-16-2017
