### ISSUE TITLE
[IntelliJ][Aris]Link aris dialog, Click OK without port, nothing happens

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3240]
Build: https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_PR/3568/Azure/

Repro Steps:
1, Launch Link aris cluster dialog
2. Enter valid values, set port empty
3. Click OK

Result:
Nothing happens, link aris cluster dialog keep opening
![image](https://user-images.githubusercontent.com/36756024/60855192-597f6b80-a235-11e9-906e-9c7c6f9d6a77.png)

Expect:
Give out warning message like "please enter valid port"

**Comment by t-rufang** [comment]
Add validation for `port` field

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738934
