### ISSUE TITLE
[IntelliJ] Add customized tool bar for output log window

### ISSUE THREAD

**Issue by t-rufang** [microsoft/azure-tools-for-java#3248]
We can add a customized tool bar in output log window. We can do many interesting things in the tool window, like
1.  Add a `Go to jobs table view` for serverless job, which would provide some insights when job run failed.
2. Add `Go to Yarn UI`, `Go to Spark History UI` link for all kinds of Spark jobs.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738929
