### ISSUE TITLE
[IntelliJ]The error message is unknown

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3254]
Build: azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.1164.07-09-2019
Repro Steps:
1.Create a new project
2.Create the serverless cosmos config
3.Right-click menu opens the settings window and displays an error message but opens the settings window directly but does not display
![image](https://user-images.githubusercontent.com/43333874/60879721-071f5a00-a1f7-11e9-980b-aa92766bf1a4.png)

![gjhgj](https://user-images.githubusercontent.com/43333874/60883001-e9a1be80-a1fd-11e9-93fe-71d7fc04d153.gif)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738927
