### ISSUE TITLE
Deselect from tools->azure subscription didn't take effect (IntelliJ 2016)

### ISSUE THREAD

**Issue by adashen** [Microsoft/azure-tools-for-java#326]
Steps.
1. Login in an account with several subscriptions. In my case I have two subscriptions. And only one has docker host created.
2. Go to Menu Tools->Azure->Select subscriptions
3. In the pop up selection window. Deselect the on has docker host.
4. Right click the project azure->Publish as docker container
5. The docker host in the deselected subscription still shows.

![image](https://cloud.githubusercontent.com/assets/1872137/24973121/7fefa9a8-1f72-11e7-9f64-99f6ece9aee6.png)

![image](https://cloud.githubusercontent.com/assets/1872137/24973161/af82c420-1f72-11e7-9a3b-5d1dd55e5963.png)

**Comment by martinsawicki** [comment]
interesting catch

**Comment by selvasingh** [comment]
5 minutes for Millis

**Comment by milismsft** [comment]
Fixed; please verify. The publishing to Docker container needs to be triggered from the main menu or right click on the project rather than the Azure Explorer window in order to repro the issue.

**Comment by bsaby** [comment]
Test passed, Both IntelliJ2017 and IntelliJ2016.
Builds used:
artifacts/azure-toolkit-for-intellij.2017.318.04-18-2017.zip
artifacts/azure-toolkit-for-intellij.2016.129.04-18-2017.zip
