### ISSUE TITLE
[IntelliJ][Linux]Can not save login status.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3260]
Build:
azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.1172.07-10-2019
azure-toolkit-for-intellij-2019.1.develop.1172.07-10-2019

Repro Steps:
1. Start intelliJ.
2. Azure sign in.
3. Close intelliJ.
4. Start intelliJ.

Result:
It changes to sign out state.
![image](https://user-images.githubusercontent.com/35950097/60961869-a2234b80-a33f-11e9-9770-f58233ab2e27.png)

**Comment by wezhang** [comment]
@Flanker32 , could you please help this auth related issue? Thanks!

**Comment by v-jiche** [comment]
Build:
azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.1173.07-10-2019

Result:
It get back to normal.
