### ISSUE TITLE
[intelliJ[windows]Can not select main class.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3262]
Build:
azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.1173.07-10-2019

Repro Steps:
1. Create a configuration
2. Select main class.

Result:
Can not select main class.
![image](https://user-images.githubusercontent.com/35950097/61029590-f71d9b00-a3ed-11e9-8cce-63e3658ac699.png)
![image](https://user-images.githubusercontent.com/35950097/61029825-85921c80-a3ee-11e9-8049-b48e31f8f92d.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738925
