### ISSUE TITLE
Deploy to Docker Container does not pick up an artifact defined in project structure

### ISSUE THREAD

**Issue by selvasingh** [microsoft/azure-tools-for-java#327]
Dev machine - Mac with IntelliJ 2016 and Azure Toolkit for IntelliJ 2016.78.04-11-2017

Clone a Spring Boot on Docker Web App sample code
git clone https://github.com/spring-guides/gs-spring-boot-docker.git

Open the project in IntelliJ by opening ./complete/POM.xml

Open View -> Tool Windows -> Maven Projects

Run "package" target in the Spring Boot Docker / Lifecycle / package

Open File -> Project Structure -> Artifacts

Add an artifact "gs-spring-boot-docker-0.1.0" of type JAR and point the output directory to ./complete/out/artifacts/gs-spring-boot-docker-0.1.0.jar and do not include in project build

Start Deploy to Docker Container on Azure .. you will not see any artifact picked by the wizard

**Comment by selvasingh** [comment]
![image](https://cloud.githubusercontent.com/assets/3642444/24973999/ac47eecc-1f75-11e7-9aa3-1b235dad01c1.png)

**Comment by martinsawicki** [comment]
maybe in the future we can offer more convenience here, but right now disambiguating among possible artifacts is too tricky.

**Comment by Flanker32** [comment]
We have deprecated the support for docker host, close this issue.
