### ISSUE TITLE
No .war file filled automatically in the publish as docker dialog (InelliJ 2016)

### ISSUE THREAD

**Issue by adashen** [Microsoft/azure-tools-for-java#328]
Steps
1. Right click a folder which contains a war file under it directly.
2. Select Azure->Publish as docker container
3. In the dialog the field "Artifact to deploy" is empty, which is different from eclipse
4. Besides, close the dialog and right click the war file, no azure context menu shows.

![image](https://cloud.githubusercontent.com/assets/1872137/24973528/f5f8fdba-1f73-11e7-97e8-e91e352f9ed0.png)

**Comment by milismsft** [comment]
This is "by design". The plugin will try to find the artifact via the IntelliJ's artifact list and it will only select one that is of an expected type (Web Archive); if it can't find one an empty field is shown and the user will have to select one via browsing to it.
