### ISSUE TITLE
The toolkit will trigger the loading web app when creating an existing deployment

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#3280]
This issue can stable repro.

### Environment:
1. OS: Windows10
2. IntelliJ: 
```
IntelliJ IDEA 2019.2 (Ultimate Edition)
Build #IU-192.5728.74, built on July 18, 2019
Runtime version: 1.8.0_212-release-1586-b4 amd64
```
3. Plugin: Azure Toolkit for IntelliJ 3.24.0

### Repro steps:
1. Right-click `Resource management` node and select `Create Deployment`
2. Create with an existing deployment name

### Result:
Toolkit pops up an error and triggers the loading of Web Apps behavior.
![image](https://user-images.githubusercontent.com/22470312/61586231-8c185500-aba1-11e9-9307-f8a69a473417.png)

### Expect:
The toolkit will not trigger the loading web app when creating deployment failed.

**Comment by EricZhangzf** [comment]
Can not repro it on v3.37.0
