### ISSUE TITLE
Survey window UI issue

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#3285]
This issue can stable repro.

### Environment:
OS: Windows10/Mac
IntelliJ: IC19.1.3-jre11
Bits: PR3638

### Result:

- Issue1: repro on Windows and Mac
- Issue2: Only repro on Mac + IntelliJ theme

![image](https://user-images.githubusercontent.com/22470312/61695063-6045cc80-ad65-11e9-974c-3df511d50fa6.png)

**Comment by EricZhangzf** [comment]
Test in version 3.25.0:
Issue1 is fixed on Mac and Windows
Issue2 is not fixed on Mac.
![image](https://user-images.githubusercontent.com/44559777/62342421-52d4d300-b519-11e9-9aa0-ef8b6e1933bd.png)

**Comment by ZhengJun003** [comment]
OS: Windows10/Mac
High contrast theme and Darcula theme
![image](https://user-images.githubusercontent.com/41051257/62346914-75bbb300-b52a-11e9-874c-bf4f082023b1.png)

**Comment by EricZhangzf** [comment]
Test Pass
Fixed on bits PR/3673
