### ISSUE TITLE
Survey window will not disappear in 10s without interaction

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#3286]
This issue can stable repro.

### Environment:
1. OS: Windows10/Mac
2. IntelliJ: 
   - IC19.1.3-jre11
   - IU19.2-jre8
5. Bits: PR3638

### Result:
1. After the dialog box pops up, the mouse does not move to the dialog box, the time is far more than 10s, and it may not disappear.
![image](https://user-images.githubusercontent.com/22470312/61695449-17dade80-ad66-11e9-815d-14dccbd0074c.png)

2. After the dialog box pops up, as long as the mouse has been moved into the dialog box, the dialog box will disappear in 10s.

**Comment by EricZhangzf** [comment]
Test pass in version 3.25.0
