### ISSUE TITLE
[Mac] 30 days more than the expected survey days

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#3287]
This issue can stable repro.
Can not repro this issue on IC19.1.3-jre11 on Windows, 

### Environment:

1. OS: Mac
2. IntelliJ: 
   - IC19.1.3-jre11
5. Bits: PR3638
#### Step: 
In the survey dialog, choose `Don't show again.`
#### Result:
Change the `nextSurveyDate `to the 30 days later.
Before:
![image](https://user-images.githubusercontent.com/22470312/61695871-dd257600-ad66-11e9-9c9c-01d68ac640d8.png)
After:
![image](https://user-images.githubusercontent.com/22470312/61695875-e0206680-ad66-11e9-9450-b3d8cce6bbd8.png)

#### Step: 
In the survey dialog, click `Give Feedback`
#### Result:
The toolkit will pop up again after 210 days.
![image](https://user-images.githubusercontent.com/22470312/61696268-a4d26780-ad67-11e9-8de2-35301c23c8b2.png)

**Comment by EricZhangzf** [comment]
Test pass in version 3.25.0
