### ISSUE TITLE
No response after pressing Esc in survey dialog

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#3289]
### Environment:
1. OS: Windows10/Mac
2. IntelliJ:
   - IC19.1.3-jre11
   - IU19.2-jre8
3. Bits: PR3638

### Result:
In survey dialog, no response after pressing Esc

### Expect:
Users could press Esc to close survey dialog

**Comment by EricZhangzf** [comment]
1. OS: Mac
2. IntelliJ: IU19.1-jre8
3. Bits version: v3.25.0

Result:
Press ESC, the survey dialog no response.

**Comment by EricZhangzf** [comment]
This issue is not reproduce on 3.37.0
