### ISSUE TITLE
Publish to Docker Container doesn't work when launched from the Project Explorer context menu

### ISSUE THREAD

**Issue by aovechki** [Microsoft/azure-tools-for-java#329]
Win10, x64, Eclipse.Mars.
Mac Sierra, Eclipse.Neon.

Using Publish to Docker Container context menu from the Project Explorer. The wizard dialog opens:
![d1](https://cloud.githubusercontent.com/assets/21356612/24973538/ff3500ea-1f73-11e7-9c3d-bd488575afd8.PNG)
Clicking Finish closes the dialog, but nothing happens. This may be related to not using Key Vault for this particular Docker Host

**Comment by milismsft** [comment]
Fixed; please verify

**Comment by vladimir-shcherbakov** [comment]
Verified: 
azure-toolkit-for-intellij.2017.320.04-18-2017
WindowsAzurePlugin4EJ.323.04-18-2017

no repro
