### ISSUE TITLE
[IntelliJ]'Error running: Unknown error' when submit job to Spark on Cosmos

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3297]
**Build:**
artifacts/azure-toolkit-for-intellij-2019.1.develop.1189.07-25-2019.zip

**Repro Steps:**
 1. Provision Spark Cluster.
 1. Submit the job by editing the configuration or right-clicking on this cluster.

**Result:**
'Error running: Unknown error'
![image](https://user-images.githubusercontent.com/40199316/62035691-ef019000-b222-11e9-8ddc-217a6c3e3cf6.png)

**Comment by t-rufang** [comment]
Fixed in #3296

**Comment by v-lanjli** [comment]
Verified and fixed, closed this issue.
