### ISSUE TITLE
Unable to update authentication settings for a docker host

### ISSUE THREAD

**Issue by aovechki** [Microsoft/azure-tools-for-java#330]
win10, x64, Eclipse.Mars

Trying to update docker host's authentication settings via Azure Explorer->Docker Hosts->[docker host]->Details and selecting Update...
The following dialog comes up:
![cred](https://cloud.githubusercontent.com/assets/21356612/24974130/04d83452-1f76-11e7-8df2-6e3af0ab2aa5.PNG)
Clicking Finish doesn't do anything.
This may be related to not using Key Vault for this Docker Host's configuration initially.

**Comment by selvasingh** [comment]
Limit investigation to no more than a few minutes for v3.0. Otherwise, please disable the update entry point for existing docker host for 3.0

**Comment by davidliangze** [comment]
Test passed. 
The Update button works for both the Docker host with Key Vault and the one without Key Vault.

OS: Windows 10 Enterprise x64 ENU
IDE: Eclipse Mars
Plugin Version: WindowsAzurePlugin4EJ.338.04-18-2017
