### ISSUE TITLE
The Name property of a focusable element must not be null.

### ISSUE THREAD

**Issue by Flanker32** [microsoft/azure-tools-for-java#3302]
The following accessibility issue needs investigation.

![image](https://user-images.githubusercontent.com/12445236/62195606-f3f34a80-b3ae-11e9-8446-a372c299f481.png)

**App:** eclipse

**Element path:** dialog ''

**Issue Details:** The Name property of a focusable element must not be null. [Section 508 502.3.1](https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/single-file-version#502-interoperability-assistive-technology)

**How To Fix:** Provide a UI Automation Name property that concisely identifies the element.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.

**Comment by Flanker32** [comment]
Close as the message text field is controlled by Eclipse UI

**Comment by vscjavaci** [comment]
Track internal issue by AB#1749805
