### ISSUE TITLE
An element must not have the same Name and LocalizedControlType as its parent.

### ISSUE THREAD

**Issue by Flanker32** [microsoft/azure-tools-for-java#3304]
The following accessibility issue needs investigation.

![image](https://user-images.githubusercontent.com/12445236/62196288-539e2580-b3b0-11e9-8df5-eb630eccbd32.png)

**App:** eclipse

**Element path:** dialog ''

**Issue Details:** An element must not have the same Name and LocalizedControlType as its parent. [Section 508 502.3.1](https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/single-file-version#502-interoperability-assistive-technology)

**How To Fix:** Provide unique names for controls that have a parent/child relationship and the same ControlType property.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.

**Comment by Flanker32** [comment]
Close as the name of dialog is controlled by Eclipse UI

**Comment by vscjavaci** [comment]
Track internal issue by AB#1749807
