### ISSUE TITLE
Focusable sibling elements must not have the same Name and LocalizedControlType.

### ISSUE THREAD

**Issue by Flanker32** [microsoft/azure-tools-for-java#3306]
The following accessibility issue needs investigation.

![image](https://user-images.githubusercontent.com/12445236/62196827-4a618880-b3b1-11e9-9aba-cdf5613c9db8.png)

**App:** eclipse

**Element path:** text 'demojenkinsansible'

**Issue Details:** Focusable sibling elements must not have the same Name and LocalizedControlType. [WCAG 4.1.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html)

**How To Fix:** Provide unique names for sibling controls that have the same ControlType property.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.

**Comment by Flanker32** [comment]
This is by design, we need JDK/WebContainer value are enum

**Comment by vscjavaci** [comment]
Track internal issue by AB#1749809
