### ISSUE TITLE
The Name must not include the same text as the LocalizedControlType.

### ISSUE THREAD

**Issue by Flanker32** [microsoft/azure-tools-for-java#3307]
The following accessibility issue needs investigation.

![image](https://user-images.githubusercontent.com/12445236/62197045-b93ee180-b3b1-11e9-8af7-b2ad12796c7b.png)

**App:** eclipse

**Element path:** group 'Resource group'

**Issue Details:** The Name must not include the same text as the LocalizedControlType. [Section 508 502.3.1](https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/single-file-version#502-interoperability-assistive-technology)

**How To Fix:** Provide a UI Automation Name property for the element that:
 · Concisely identifies the element, AND
 · Does not include the same text as the element's LocalizedControlType property.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.

**Comment by Flanker32** [comment]
This is by design, Resource group is a common parameter in Azure services.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1749804
