### ISSUE TITLE
[intelliJ[Linux Mac]Can not spark console successfully.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3308]
**Build:**
azure-toolkit-for-intellij-2019.2.develop.1196.07-31-2019 (1)
**OS:** Linux and Mac
**IntelliJ Version:** 2019.2

**Repro Steps:**

1. Create a new HDInsight project.
2. Right click LogQuery to Spark console.

![image](https://user-images.githubusercontent.com/35950097/62198173-c1981c00-b3b3-11e9-97a6-555001ddde67.png)

**Result:**
Get error message.
![image](https://user-images.githubusercontent.com/35950097/62198013-78e06300-b3b3-11e9-974d-1b173f250f56.png)

**Comment by t-rufang** [comment]
Key to repro this issue is to upgrade scala plugin to version `2019.2.15`

**Comment by v-jiche** [comment]
Verified. Fixed.
Build: azure-toolkit-for-intellij-2019.2.develop.1208.08-15-2019
