### ISSUE TITLE
[IntelliJ] "Previous" button enabled for the first step in "Publish Docker" wizard

### ISSUE THREAD

**Issue by JunyiYi** [Microsoft/azure-tools-for-java#331]
**OS**
MacOS Sierra

**IDE**
IntelliJ 2016.3

**Plugin**
azure-toolkit-for-intellij.2016.79.04-12-2017.zip

**Feature**
Deploy Docker Container on Azure wizard

**Repro Steps**
1. *Publish as Docker Container*
2. After the wizard shows up, click the *Refresh* icon button in the *Hosts* tab
3. The *Previous* button is enabled, and click it
4. Close the wizard and click the *little error icon* in the right-bottom corner of IntelliJ
5. The exception is "java.lang.ArrayIndexOutOfBoundsException"

**Comment by milismsft** [comment]
Fixed; please verify.

**Comment by davidliangze** [comment]
We don't have machines with Mac OS.
OS: Windows 10 Enterprise x64 ENU
IDE: Eclipse Neon/ Mars
Plugin Version:

Test passed.

**Comment by davidliangze** [comment]
We don't have machines with Mac OS.
OS: Windows 10 Enterprise x64 ENU
IDE: IntelliJ 2016.3 
Plugin Version: azure-toolkit-for-intellij.2016.128.04-17-2017

Test passed.
