### ISSUE TITLE
There's no status in Azure Activity Log for Docker Container bapublish

### ISSUE THREAD

**Issue by shsushi** [Microsoft/azure-tools-for-java#333]
Issue:
There's not status in Azure activity log for docker container publish.

Expected:
Show status of container publish.

Repro:
1. Create a Java Dynamic Web Application.
2. Sign in with your azure subscription.
3. Open Azure Explorer and navigate to some docker host.
4. Right click the Publish, then you will see below log window:
<img width="668" alt="screen shot 2017-04-12 at 11 58 19 am" src="https://cloud.githubusercontent.com/assets/6917718/24974569/7852818e-1f77-11e7-9a7c-8b9047770c6f.png">

OS: macOS Sierra (10.12.4)

Subscription Type: Enterprise

IDE: Eclipse Neon.3

Plugin: WindowsAzurePlugin4EJ.273.04-12-2017.zip

Feature: Azure Activity Log

**Comment by martinsawicki** [comment]
@milismsft by design?

**Comment by milismsft** [comment]
Yes, this is "by design"; only if there are errors while publishing we will leave something in the status. However, the Web App publishing needs to remove the "Success" in order to have overall consistency across both publishing paths.

**Comment by bsaby** [comment]
Test used artifacts/WindowsAzurePlugin4EJ.289.04-13-2017.zip.

Below is my test result:
Both WebApp and Docker container, **Process** Displays the progress bar, **Status** displays the progress content. After publish successfully, they will not show status in the Azure activity log. 
![image](https://cloud.githubusercontent.com/assets/22470312/25032926/00324a8c-210b-11e7-8248-6a21778a445a.png)
