### ISSUE TITLE
[IntelliJ] Focus sticks to "Artifact to deploy" textbox in "Publish Docker" wizard

### ISSUE THREAD

**Issue by JunyiYi** [Microsoft/azure-tools-for-java#334]
**OS**
MacOS Sierra

**IDE**
IntelliJ 2016.3

**Plugin**
azure-toolkit-for-intellij.2016.79.04-12-2017.zip

**Feature**
Publish Docker wizard focus issue

**Repro Steps**
1. *Publish as Docker Container*
2. After the wizard shows up, put the focus to the "Artifact to deploy" text box
3. Try to move the focus to the "name" text box or other controls
4. You can not move the focus, although you can still click the buttons

**Comment by martinsawicki** [comment]
this is standard IntelliJ behavior for validated text controls as long as input is not valid
