### ISSUE TITLE
[IntelliJ][RunConf] The changed config is not displayed

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3369]
**Build:**
IntelliJ IDEA 2019.1: https://azuredownloads.blob.core.windows.net/azuretoolkitforintellij/v3.25.0/azure-toolkit-for-intellij-2019.1.127.07-31-2019.zip 
IntelliJ IDEA 2019.2: https://azuredownloads.blob.core.windows.net/azuretoolkitforintellij/v3.25.0/azure-toolkit-for-intellij-2019.2.127.07-31-2019.zip

**Repro Steps:**

1. Create a new project.
2. Click the config display box to open edit Run/Debug Configurations dialog.
3. Select a template e.g. Apache Spark on HDInsight.
4. Fill in the Main class name and select a spark cluster, then, click Apply and OK button to save this config.
5. Re-open edit Run/Debug Configurations dialog.
6. Delete the saved template and create a new template.
7. Fill in the Main class name and select a spark cluster, then, click Apply and OK button to save this config.
8. Check the config display box.

**Result:**
The changed config is not displayed.

**Comment by v-lanjli** [comment]
Add .Gif for this issue:
![12](https://user-images.githubusercontent.com/40199316/62266061-5c970180-b459-11e9-9363-b9cf424670ff.gif)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738923
