### ISSUE TITLE
The delete is not working for pre-defined image under docker host

### ISSUE THREAD

**Issue by shsushi** [Microsoft/azure-tools-for-java#337]
Issue:
User is allowed to delete the tomcat base image under the docker host in Azure Explorer, but it comes back after you refresh the docker host.

Expected:
Disable the delete functionality of base image, it's meaningless.

Repro:
1. Create a Java Dynamic Web Application.
2. Sign in with your azure subscription and publish the web app as docker container.
3. Open Azure Explorer and navigate to the docker host which is running the container above.
4. Choose the Tomcat image, and right click to delete it.
5. It will disappear under the host immediately, but if you refresh the host, it comes back:

<img width="673" alt="screen shot 2017-04-12 at 12 07 23 pm" src="https://cloud.githubusercontent.com/assets/6917718/24974962/d8c2985a-1f78-11e7-9eb1-cdb1f9e34804.png">

OS: macOS Sierra (10.12.4)

Subscription Type: Enterprise

IDE: Eclipse Neon.3

Plugin: WindowsAzurePlugin4EJ.273.04-12-2017.zip

Feature: Azure Activity Log

**Comment by martinsawicki** [comment]
error: "This image cannot be deleted."

**Comment by milismsft** [comment]
This is fixed now (sort of...); we will issue a error dialog if the selected Docker image failed to be deleted. BTW you can not delete the "base" image (in this case "tomcat...") until all the derived images are deleted first; this is a Docker limitation and not a plugin limitation.

**Comment by davidliangze** [comment]
We don't have machines with Mac OS.
OS: Windows 10 Enterprise x64 ENU
IDE: IntelliJ 2017.1.1
Plugin Version: azure-toolkit-for-intellij.2017.303.04-16-2017

Test passed.
When deleting the "base" image, which is tomcat in this issue, an error dialog will appear, saying the Docker image tomcat failed to delete.

**Comment by davidliangze** [comment]
We don't have machines with Mac OS.
OS: Windows 10 Enterprise x64 ENU
IDE: Eclipse Neon 3
Plugin Version: WindowsAzurePlugin4EJ.307.04-16-2017

Test passed.
When deleting the "base" image, which is tomcat in this issue, an error dialog will appear, saying the Docker image tomcat failed to delete.
