### ISSUE TITLE
[IntelliJ] Job submitted to spark on cosmos finished but all the workers are killed

### ISSUE THREAD

**Issue by t-rufang** [microsoft/azure-tools-for-java#3370]
Repro steps:
1. Submit a spark batch job to Spark on Cosmos Cluster.
2. When the job is finished, check spark master UI, you can find the job is in `finished` state. Dive into the applciation, you can find that all the workers are in `killed` state.

![image](https://user-images.githubusercontent.com/32627233/62214201-29ac2980-b3d7-11e9-914f-4fd235a6cbe7.png)

![image](https://user-images.githubusercontent.com/32627233/62214226-34ff5500-b3d7-11e9-81e1-d333116acd91.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738922
