### ISSUE TITLE
[IntelliJ][Job View]Get 'Open browser error' dialog after click the 'Open Spark History UI' in Job View page.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3373]
**Build:**
IntelliJ IDEA 2019.1: https://azuredownloads.blob.core.windows.net/azuretoolkitforintellij/v3.25.0/azure-toolkit-for-intellij-2019.1.127.07-31-2019.zip
IntelliJ IDEA 2019.2: https://azuredownloads.blob.core.windows.net/azuretoolkitforintellij/v3.25.0/azure-toolkit-for-intellij-2019.2.127.07-31-2019.zip

**Repro Steps:**

1. Create a project or open an existing project.
2. Click on Azure Explorer.
3. Expand HDInsight node.
4. Expand a spark version is a 2.3 or 2.4 cluster. (e.g. mandywne; spark230-gen2-yan; spark242-lanjun)
5. Click Jobs.
6. Click 'Open Spark History UI' in job view page.
7. Check results.

**Result:**
Shown 'Open browser error' dialog.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/40199316/62279878-83ffc580-b47d-11e9-88ec-443489c9294d.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/40199316/62280289-346dc980-b47e-11e9-819b-0f48481f796b.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738921
