### ISSUE TITLE
Deploy Docker Container to Azure does not populate published link with correct port no

### ISSUE THREAD

**Issue by selvasingh** [Microsoft/azure-tools-for-java#338]
Continue steps in #327 - explicitly specify an artifact ./complete/out/artifacts/gs-spring-boot-docker-0.1.0.jar

Click next and provide a port mapping say - 2000:8080 ... continue to deploy. When deployed you will see a hyperlinked "Published"

Click on that ... it points to http://asir-simplewebapp111717.westus2.cloudapp.azure.com:23732

However it should be http://asir-simplewebapp111717.westus2.cloudapp.azure.com:2000

**Comment by milismsft** [comment]
Fixed; please verify.

**Comment by vladimir-shcherbakov** [comment]
verified:
azure-toolkit-for-intellij.2017.320.04-18-2017
WindowsAzurePlugin4EJ.323.04-18-2017

no repro.
