### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by brookegravitt** [microsoft/azure-tools-for-java#3382]
IntelliJ build version: 2019.2 IU-192.5728.98
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.3
Plugin version: 3.24.0-2019.2

#### 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).
It's pretty good. 
I'll give it a 5.5

#### 2. What did you like or dislike about Azure Toolkit for IntelliJ?
A little clunky, UI & Setup-wise

#### 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?
streamlined UI elements & easier deploy tasks

**Comment by wezhang** [comment]
@yucwan @Jejiang
