### ISSUE TITLE
cannot take me to the application page directly after publish to container

### ISSUE THREAD

**Issue by juniwang** [Microsoft/azure-tools-for-java#340]
- issue type: minor issue.
- IDE: Intellij 2017
- platform: Windows 10
- plugin version: azure-toolkit-for-intellij.2017.267.04-11-2017
- Repo steps: 
  - Create a HelloWorld web application and publish it to Azure Docker Container using predefined Tomcat iamge
  - In the Azure Explorer, select the published app and click Browse
- Expected: the browser takes me to the HelloWorld page(http://helloworld506932.westus.cloudapp.azure.com:20720/HelloWorld/) directly
- Actual: It takes me to the Tomcat default page(http://helloworld506932.westus.cloudapp.azure.com:20720).

![2017-04-12_1207](https://cloud.githubusercontent.com/assets/8814383/24975206/c3e1ede0-1f79-11e7-9efc-d6fce9315a7e.png)
![2017-04-12_1208](https://cloud.githubusercontent.com/assets/8814383/24975207/c3e70f64-1f79-11e7-9bfd-0b17bcb63d07.png)

**Comment by milismsft** [comment]
I could not repro this issue with the latest plugin...

**Comment by davidliangze** [comment]
Not repro in Microsoft Edge.

OS: Windows 10 Enterprise X64 ENU
IDE: IntelliJ 2017.1.1
Test build: azure-toolkit-for-intellij.2017.303.04-16-2017
