### ISSUE TITLE
[Intellij][Arcadia][Interactive console]An error occurred when starting the interactive session console

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3401]
Build: azure-toolkit-for-intellij-2019.2.develop.1205.08-14-2019

Repro Steps:
1.Create a new project with spark 2.4
2.Create a config on Spark Arcadia 
3.Select a spark compute and fill in the information of Job upload Storage.
4.Click apply and OK
5.Click the remotely run button.
6.Right click the Tools and select the Interactive Session Console.

Result:
![image](https://user-images.githubusercontent.com/43333874/63013913-305c8700-be42-11e9-927b-06823b2e2681.png)

7.Click Continue Anyway 
Result:
![image](https://user-images.githubusercontent.com/43333874/63013993-58e48100-be42-11e9-8955-84b9ab4e232d.png)

**Comment by t-rufang** [comment]
Fixed in #3412

**Comment by v-xiaocw** [comment]
Fixed in dev build 1218
