### ISSUE TITLE
[IntelliJ][HDInsight]Run interactive session console gets error.

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3402]
Build: dev 1206
Repro Steps:
1.Create a new project
2.Click Tools-->Default Spark Application Type-->Spark on HDInsight
3.Click  Tools-->Spark Console-->Run Spark Livy interactive session console
4.Fill in the config file then apply and run
Result:
![image](https://user-images.githubusercontent.com/43333874/63078074-3197bd80-beef-11e9-8def-77f74fe6c1ad.png)

**Comment by t-rufang** [comment]
Fixed in #3412

**Comment by v-xiaocw** [comment]
Fixed  in  dev build 1218
