### ISSUE TITLE
[Intellij][Arcadia]Remote run failed with arcadia configration.

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3404]
Build:azure-toolkit-for-intellij-2019.2.develop.1206.08-14-2019
Repro Steps:
1.Create a new project with spark 2.4
2.Create a config on Spark Arcadia 
3.Select a spark compute,
![image](https://user-images.githubusercontent.com/43333874/63078727-4c6b3180-bef1-11e9-8251-8321137a0259.png)
 and fill in the information of Job upload Storage.
4.Click apply and OK
5.Click the remotely run button.
Result:
![image](https://user-images.githubusercontent.com/43333874/63078648-0746ff80-bef1-11e9-857c-1563ed1bb41e.png)

**Comment by t-rufang** [comment]
Fixed in #3406

**Comment by v-xiaocw** [comment]
Fixed in dev  1218
