### ISSUE TITLE
[Intellij][Arcadia]Suggest to change cluster into spark computes.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3405]
Build:
azure-toolkit-for-intellij-2019.2.develop.1206.08-14-2019

Repro Steps:
1. Create a new Apache Spark on Arcadia configuration.(Keep the Spark computes empty)
![无标题](https://user-images.githubusercontent.com/35950097/63078942-b0343f80-bf6f-11e9-8bdc-b77524cd4562.png)
Result:
Get error message. Suggest change cluster to Spark computes.
![无标题](https://user-images.githubusercontent.com/35950097/63079179-436d7500-bf70-11e9-8fb4-1a7926950919.png)

2. Click the icon to remotely run it.
![image](https://user-images.githubusercontent.com/35950097/63079003-d35eef00-bf6f-11e9-87eb-328f5ed71576.png)

Result:
Get warning message. Suggest change cluster to Spark Computes.
![image](https://user-images.githubusercontent.com/35950097/63079307-96dfc300-bf70-11e9-98fb-a1b15c469726.png)

**Comment by jingyanjingyan** [comment]
Build dev 1340 19.2&bundle, windows

1. Create a synapse config, submit, the statue information use "cluster" might need update 
![image](https://user-images.githubusercontent.com/36756024/71868844-ece51b00-314a-11ea-9169-ed250f034eb8.png)

2. Create a synapse config, start interactive console, "cluster" need update
![image](https://user-images.githubusercontent.com/36756024/71868886-1605ab80-314b-11ea-896e-c40d19ffad2d.png)

3. Submit synapse, check the log. Should add one space between "pool" and the url
![image](https://user-images.githubusercontent.com/36756024/71868918-32094d00-314b-11ea-93cb-2cb4249b214c.png)

4. Do not sign in, create a synapse config, refresh the spark pool list. In the warning message, "cluster" need update.
![image](https://user-images.githubusercontent.com/36756024/71868950-4cdbc180-314b-11ea-82df-d9ba29a9b3c3.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738920
