### ISSUE TITLE
[Intellij][Arcadia]Suggest to make error message much clearer.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3407]
Build:
azure-toolkit-for-intellij-2019.2.develop.1206.08-14-2019

Repro Steps:
1. Create a new Apach Spark on Arcadia configurartion.
2. Do not set any value.
![image](https://user-images.githubusercontent.com/35950097/63080706-584c0780-bf74-11e9-99a9-465db32175b3.png)
3. Click icon to remotely run it.
Result:
Change Configuration settings window pops up.
![image](https://user-images.githubusercontent.com/35950097/63080762-816c9800-bf74-11e9-9943-3be830bfa504.png)
4. Click Continue Anyway button.
Result:
Error message pops up. Suggest to make it much clearer.
![image](https://user-images.githubusercontent.com/35950097/63080796-9b0ddf80-bf74-11e9-81d6-92024905a623.png)
5. Set Spark Computes and do not set main class. Then repeat the third and the fourth steps.
![image](https://user-images.githubusercontent.com/35950097/63080982-08217500-bf75-11e9-9055-19815157f409.png)
Result:
Suggest to make error message much clearer.
![image](https://user-images.githubusercontent.com/35950097/63080998-153e6400-bf75-11e9-9f8e-03acd4911552.png)
![image](https://user-images.githubusercontent.com/35950097/63081025-24bdad00-bf75-11e9-81d8-7ed2d6214e5b.png)
6. Set main class and spark computes and do not set storage information. Then repeat the step 3 and step 4.
![image](https://user-images.githubusercontent.com/35950097/63081137-6fd7c000-bf75-11e9-99af-2d3aa80e857f.png)
![image](https://user-images.githubusercontent.com/35950097/63081149-76fece00-bf75-11e9-8610-848e5a286e96.png)
Result:
Suggest to make error message much clearer.
![image](https://user-images.githubusercontent.com/35950097/63081187-94cc3300-bf75-11e9-9193-c75d8420c4bc.png)
![image](https://user-images.githubusercontent.com/35950097/63081205-a3b2e580-bf75-11e9-84d6-60fbee507e3a.png)

**Comment by v-jiche** [comment]
Add one scenario:
Right click Arcadia cluster to submit job. 
![image](https://user-images.githubusercontent.com/35950097/63257658-d9750880-c2ac-11e9-92ac-ecb7fc9e6b7a.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738919
