### ISSUE TITLE
[IntelliJ] No error message in "Publish Docker" wizard

### ISSUE THREAD

**Issue by JunyiYi** [Microsoft/azure-tools-for-java#341]
**OS**
MacOS Sierra

**IDE**
IntelliJ 2016.3

**Plugin**
azure-toolkit-for-intellij.2016.79.04-12-2017.zip

**Feature**
Deploy Docker Container on Azure

**Repro Steps**
1. Click *Publish as Docker Container*
2. Select a WAR file in *Artifact to deploy* text box
3. Try to click the *Next* button (there are no hosts in the *Hosts* list)
4. The dialog shakes (means some error occur), but there are no error messages in this dialog
5. The *Previous* button is enabled, but an exception will be triggered when you click it

**Comment by martinsawicki** [comment]
previous should be disabled - other than that, we can keep as is.

**Comment by milismsft** [comment]
Fixed; please verify.

**Comment by bsaby** [comment]
Both InteliiJ2017 and IntelliJ2016 test passed.
Builds  used:
artifacts/azure-toolkit-for-intellij.2016.129.04-18-2017.zip
artifacts/azure-toolkit-for-intellij.2017.319.04-18-2017.zip.
