### ISSUE TITLE
[Intellij]Build error in azure-toolkit-for-intellij

### ISSUE THREAD

**Issue by SparkSnail** [microsoft/azure-tools-for-java#3410]
```
* What went wrong:
Could not determine the dependencies of task ':prepareSandbox'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not find com.microsoft.azuretools:azuretools-core:3.26.0.
   > Could not find com.microsoft.azuretools:azure-explorer-common:3.26.0.
   > Could not find com.microsoft.azuretools:hdinsight-node-common:3.26.0.
```
When I download the source code of azure-toolkit-for-intellij, I failed to run the plugin. I am a beginner of intellij plugin-in, could anyone give me advice?

**Comment by Flanker32** [comment]
@SparkSnail Thanks for your feedback, you need to install the dependencies before run azure toolkit, here are detail steps [CONTRIBUTING](https://github.com/microsoft/azure-tools-for-java/blob/develop/CONTRIBUTING.md)

**Comment by SparkSnail** [comment]
Hi, @Flanker32 
     Thanks for your response, I've tried to install dependencies using the `mvn clean install -f Utils/pom.xml` command, and get some errors.
![image](https://user-images.githubusercontent.com/22682999/63206597-6cb21080-c0ea-11e9-9ada-6d226af6cb71.png)
the full error log is here:
[mvn.log](https://github.com/microsoft/azure-tools-for-java/files/3511640/mvn.log)
Could you please help to figure out the error reason?

Best regards

**Comment by Flanker32** [comment]
@SparkSnail Could you please verify the java version you use? This project could only be compiled within Java 8.

**Comment by SparkSnail** [comment]
problem has solved, thanks for your reply.
