### ISSUE TITLE
Open in browser from AZ Explorer didn't jump to the application path (Both from Eclipse and IntelliJ 2016)

### ISSUE THREAD

**Issue by adashen** [Microsoft/azure-tools-for-java#342]
Steps
1. Sign in to the azure account. 
2. Open Azure Explore and navigate to a started webapp.
3. Right click the app and choose "Open in browser".
4. Browser opened and the url is just the root url, instead of the path to the app. 

For example my web app host is https://webapp-170412101538.azurewebsites.net/, and my app name is FirstEclipse. And the url jumped to is "https://webapp-170412101538.azurewebsites.net/" instead of "http://webapp-170412101538.azurewebsites.net/FirstEclipse/"

**Comment by vladimir-shcherbakov** [comment]
Azure terminology is a little confusing - Web App really means Web App Service - it's a service on Azure that hosts your java web applications. Explorer lists Web App Services - it knows nothing about your java web application just because Azure SDK doesn't expose an interface for that

**Comment by vladimir-shcherbakov** [comment]
It's a good fiture for the next release.
moved to backlog
