### ISSUE TITLE
[intelliJ][Spark on cosmos]Get error message when submit Job from Spark on Cosmos node.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3427]
Build:
azure-toolkit-for-intellij-2019.2.PR.3707.08-16-2019

Repro Steps:
1. Open Azure Explorer.
2. Expand Spark on Cosmos node. 
3. Right click a cluster to submit job.
![image](https://user-images.githubusercontent.com/35950097/63243315-b76b8e00-c28c-11e9-9562-b0bd01a880b0.png)

Result:
**Spark Clusters** is not selected automatically. And get error message.
![image](https://user-images.githubusercontent.com/35950097/63243338-cf431200-c28c-11e9-8e4f-790538c384b1.png)

Expectation:
Spark Clusters should be selected automatically.

**Comment by t-rufang** [comment]
Fixed in #3412

**Comment by v-jiche** [comment]
Verified, Fixed.
Build: azure-toolkit-for-intellij-2019.2.PR.3708.08-19-2019
Result: Spark Cluster can be selected automatically.
![image](https://user-images.githubusercontent.com/35950097/63253463-839c6280-c2a4-11e9-90f2-c63996b38df4.png)
