### ISSUE TITLE
[IntelliJ][RunConf]After right-clicking the submitted job, the configuration cannot be displayed in the upper right corner.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3428]
**IntelliJ build version:** 2019.2 IC-192.5728.98
**OS:** Mac OS X; Windows; Linux
**Plugin version:** https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_develop/1210/Azure/processDownloadRequest/artifacts/azure-toolkit-for-intellij-2019.2.develop.1210.08-16-2019.zip
**Repro Step:**

**a:**
1. Create a new project.
2. In project, right-clicking on LogQuery.
3. Click **Submit Spark Application**.
![image](https://user-images.githubusercontent.com/40199316/63245868-c9046400-c293-11e9-99f7-d404dd1cb552.png)
4. Edit the Config, click Apply and OK to close it.
5. Check the upper right corner.

**b:**
1. Provision a spark cluster in Apache Spark on Cosmos.
2. On this cluster, submit the job by right-clicking on the submit job.
![image](https://user-images.githubusercontent.com/40199316/63245906-e33e4200-c293-11e9-9af6-03ecb359601d.png)
3. Edit the Config, click Apply and OK to close it.
4. Check the upper right corner.

**Result:** The configuration cannot be displayed in the upper right corner.
![image](https://user-images.githubusercontent.com/40199316/63245932-04069780-c294-11e9-9168-59897dc1e0c8.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738918
