### ISSUE TITLE
[IntelliJ] Icons are too small compared to native IntelliJ icons

### ISSUE THREAD

**Issue by xscript** [microsoft/azure-tools-for-java#343]
- IDE version: 
```IntelliJ IDEA 2017.1.1
Build #IU-171.4073.35, built on April 7, 2017
Licensed to IntelliJ IDEA Evaluator
Expiration date: May 13, 2017
JRE: 1.8.0_112-release-736-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```
- Plugin version: azure-toolkit-for-intellij.2017.267.04-11-2017.zip

- Resolution: 2560x1440, with the blew Windows setting
![image](https://cloud.githubusercontent.com/assets/2300784/24975408/1e2d8ae2-1ff8-11e7-9d86-c76365bb0789.png)

- Repro steps:
  - Open Azure Explorer

![image](https://cloud.githubusercontent.com/assets/2300784/24975351/e3b01f4c-1ff7-11e7-8208-f262cb77547e.png)

**Comment by martinsawicki** [comment]
@lenala do we even have control over this?

**Comment by martinsawicki** [comment]
maybe in the future we can figure out how this could be possible, but we have fixed icon sizes today

**Comment by Flanker32** [comment]
Issue has been fixed in latest releases
