### ISSUE TITLE
[intelliJ][Spark on Arcadia cluster]Get error message when submit Spark on Arcadia job by right clicking Arcadia cluster.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3435]
Build:
azure-toolkit-for-intellij-2019.2.PR.3699.08-15-2019

Repro Steps:
1. Open Azure Explorer.
2. Right click Arcadia cluster to submit job.
![image](https://user-images.githubusercontent.com/35950097/63256623-8732e800-c2aa-11e9-8509-faa42e4882d1.png)
3. Fill in the correct information.
![image](https://user-images.githubusercontent.com/35950097/63256681-a893d400-c2aa-11e9-8096-6859fb969124.png)
Result:
Get error message.
![image](https://user-images.githubusercontent.com/35950097/63256707-b6e1f000-c2aa-11e9-85e2-fb4f8a5875ad.png)
4. Continue to run it.
Result:
Job submit successfully.
![image](https://user-images.githubusercontent.com/35950097/63256790-e85abb80-c2aa-11e9-8df7-780e6aae0dc1.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738917
