### ISSUE TITLE
[Eclipse] Cannot create Docker Host (invalid password)

### ISSUE THREAD

**Issue by JunyiYi** [Microsoft/azure-tools-for-java#344]
**OS**
MacOS Sierra

**IDE**
Eclipse Mars

**Plugin**
WindowsAzurePlugin4EJ.273.04-12-2017.zip

**Feature**
Create Docker Host wizard

**Repro Steps**
1. Right click *Docker Hosts* in *Azure Explorer*
2. Click *New Host*
3. Fill in the information and click *Next*
4. Type "abcdABCD1234!@#$" in the *Password* text box
5. Leave *Confirm* text box empty
6. The error of the password is always "Invalid Password", but it meets all the requirements

**Comment by milismsft** [comment]
This is "by design" for now, there is only one error message that rules all error cases for password input.
