### ISSUE TITLE
[intelliJ][SQL Server Big Data Cluster]Can not open yarn UI normally.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3440]
Build:
azure-toolkit-for-intellij-2019.2.develop.1211.08-19-2019

Repro Steps:
1. Open Azure Explorer.
2. Right click SQL Server node to link a cluster.
![image](https://user-images.githubusercontent.com/35950097/63322889-109ff400-c357-11e9-8192-b3c2882c500f.png)
3. Right click the linked cluster, then select **Open Yarn UI**.
![image](https://user-images.githubusercontent.com/35950097/63322935-29100e80-c357-11e9-8890-c66ca19091c8.png)
Result:
![image](https://user-images.githubusercontent.com/35950097/63322985-41802900-c357-11e9-9fc5-b72f3e31f679.png)
Expectation:
![image](https://user-images.githubusercontent.com/35950097/63323011-53fa6280-c357-11e9-8d4d-e70c2d136930.png)

**Comment by t-rufang** [comment]
Fixed in #3455

**Comment by v-jiche** [comment]
Verified. Fixed.
Build: develop 1219
Result: 
![image](https://user-images.githubusercontent.com/35950097/63578171-7cd26000-c5c2-11e9-9d0b-d66ad068ae09.png)
