### ISSUE TITLE
[intelliJ]Different performance when locally run and remotely run without main class.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3443]
Build:
azure-toolkit-for-intellij-2019.2.develop.1211.08-19-2019

Repro Steps:
1. Create an HDInsight configuration, do not choose main class., then save it.
![image](https://user-images.githubusercontent.com/35950097/63327868-9e80dc80-c361-11e9-9add-9e5506a9ed0a.png)
2. Click icon to locally run it.
Result:
Edit Configuration window pops up.
![image](https://user-images.githubusercontent.com/35950097/63327940-c96b3080-c361-11e9-9008-a2871a9747f7.png)
3. Click Run button.
Result:
Error message pops up.
![image](https://user-images.githubusercontent.com/35950097/63328005-e69fff00-c361-11e9-9ac1-daa504f255db.png)
4. Reopen Run/Debug Configuration window to edit HDInsight configuration.
Click **Remotely Run in Cluster**, do not select main class, choose a spark cluster, then save it.
![image](https://user-images.githubusercontent.com/35950097/63328255-6af28200-c362-11e9-967c-b728bafd3935.png)
5. Click Remotely run icon.
Result:
Error message pops up.
![image](https://user-images.githubusercontent.com/35950097/63328363-97a69980-c362-11e9-9ff6-3ac82cdd96db.png)

Expectation:
1. Make error message much clearer.
![image](https://user-images.githubusercontent.com/35950097/63328005-e69fff00-c361-11e9-9ac1-daa504f255db.png)
2. Maybe it is better to make the performance of the two consistent.

**Comment by wezhang** [comment]
Thanks @v-jiche ! These differences depend on IntellliJ behaviors.
