### ISSUE TITLE
[intelliJ][Spark on Arcadia cluster]Get error message when remotely run Arcadia configuration.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3444]
Build:
azure-toolkit-for-intellij-2019.2.PR.3715.08-20-2019

Repro Steps:
1. Create a Arcadia configuration.
2. Choose main class and computes, do not fill in Storage account information, then save it.
![image](https://user-images.githubusercontent.com/35950097/63333039-47800500-c36b-11e9-88e6-dcd096ca3379.png)
![image](https://user-images.githubusercontent.com/35950097/63333090-62eb1000-c36b-11e9-9142-0135efba3d69.png)
3. Click Remotely run button.
![image](https://user-images.githubusercontent.com/35950097/63333118-6f6f6880-c36b-11e9-9df6-ffac6d49d79f.png)
Result:
Change Configuration Settings window pops up.
![image](https://user-images.githubusercontent.com/35950097/63333139-7bf3c100-c36b-11e9-9af8-c724fc6385a1.png)
4. Click Edit button.
Result:
Edit Configuration window pops up.
![image](https://user-images.githubusercontent.com/35950097/63333199-99288f80-c36b-11e9-8521-f113ccb7d6bd.png)
5. Fill in the correct Storage information.
Result:
Get error message.
![image](https://user-images.githubusercontent.com/35950097/63333307-caa15b00-c36b-11e9-808d-eb5fd0ec8743.png)

Expectation:
The information filled in is correct, so there should not be error message.

**Comment by t-rufang** [comment]
Duplicate with #3429

**Comment by v-jiche** [comment]
Duplicate with #3429
