### ISSUE TITLE
[intelliJ]Different result on linux, windows and Mac when stop local console.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3445]
Build:
azure-toolkit-for-intellij-2019.2.PR.3715.08-20-2019

Repro Steps:
1. Create a new project.(HDInsight/Arcadia/cosmos..)
2. Local console.
3. Stop Local console.
![image](https://user-images.githubusercontent.com/35950097/63338693-dd209200-c375-11e9-82af-a455ba14259b.png)

Result:
Linux/Mac
![image](https://user-images.githubusercontent.com/35950097/63338577-a480b880-c375-11e9-9700-8f468a3e6bf1.png)
Windows:
![image](https://user-images.githubusercontent.com/35950097/63338597-ad718a00-c375-11e9-999a-87d29ca37026.png)

**Comment by v-lanjli** [comment]
This issue is also reproduced on the Mac.
![image](https://user-images.githubusercontent.com/40199316/64510139-fdf45b80-d313-11e9-944a-fd4b929c1617.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738916
