### ISSUE TITLE
Create a Docker container that can not display all available storage accounts.

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#345]
Win10 x64
Build used: 
artifacts/WindowsAzurePlugin4EJ.289.04-13-2017.zip
artifacts/azure-toolkit-for-intellij.2017.285.04-13-2017.zip

Both Eclipse and IntelliJ, when creating a Docker container, select the "Existing storage" account, nothing in the drop-down list or can not display all available accounts.
![image](https://cloud.githubusercontent.com/assets/22470312/25037522/1c38be84-212c-11e7-8787-0d7c03f8a055.png)
![image](https://cloud.githubusercontent.com/assets/22470312/25037527/242b3f4a-212c-11e7-8b4e-3c0a564b1f33.png)

**Comment by martinsawicki** [comment]
@bsaby could you pls clarify when exactly you are seeing the missing storage account screenshot? And where did you get the screenshot showing the storage account?  How do I repro?

**Comment by davidliangze** [comment]
Repro step( for both Eclipse and IntelliJ):
In Azure Explorer, right click Docker Host node -> New Host. 
Then in Create Docker Host dialog, choose Storage.
Select Existing storage account.

The dropdown list can't show all the available storage account.
![capture](https://cloud.githubusercontent.com/assets/26756696/25111173/ed0f9b30-241b-11e7-8ae3-99ef858b6e64.PNG)

**Comment by milismsft** [comment]
When creating a Docker Host we try to pair the virtual machine size with the right storage account. For instance the "_DS" will expect a premium storage account type (standard storage accounts are filtered out) while "Basic" will expect a standard storage account (premium storage does not even work). These are default settings when creating a VM via the Azure Portal as well.

**Comment by bsaby** [comment]
When creating a Docker Host ,the "_DS" will expect to use advanced storage account types and "Basic" will expect a standard storage account , but why the default storage account type created is standard when creating the - DS or Basic VM?  Are these default settings?
**Picture1:**
![image](https://cloud.githubusercontent.com/assets/22470312/25120416/910879da-2450-11e7-9095-7a1d51ee9e53.png)
**Picture2:**
![image](https://cloud.githubusercontent.com/assets/22470312/25120462/c2dffbb8-2450-11e7-9ea0-e4a26656c09e.png)

**Comment by milismsft** [comment]
hmm... this seems to be a change with the latest Azure SDK because couple months back the case was it will create a Premium storage for the non basic VM sizes. In this case it's better to remove the filter for _DS, only filter Premium if VM size is not _DS (default to Standard).

**Comment by milismsft** [comment]
I'm working on a fix for this, I should be able to get it checked in in couple minute... Please check if that fixes the storage account listings (Standard only for "Basic" VM sizes, both Standard and Premium for _D sizes).

**Comment by milismsft** [comment]
Just pushed a fix for this; can you let me know if it works now?

**Comment by bsaby** [comment]
Both IntelliJ and Eclipse test passed.
Builds used:
artifacts/azure-toolkit-for-intellij.2017.319.04-18-2017.zip.
artifacts/WindowsAzurePlugin4EJ.323.04-18-2017.zip
