### ISSUE TITLE
[IntelliJ]Save template buttons intercepted

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3467]
Build: develop 1221

Repro Steps:
1. Open configuration dialog, expand Template
2. Choose arcadia, cosmos, aris, hdinsight or serverless
![image](https://user-images.githubusercontent.com/36756024/63679034-08e2c280-c823-11e9-9c81-cd14c27059a6.png)

Result:
The OK, Cancel, Apply buttons are intercepted

Expect:
Display well

**Comment by t-rufang** [comment]
@jingyanjingyan  I can't repro this issue in the latest bits, please help verify.

**Comment by jingyanjingyan** [comment]
The issue also happens with other template that includes too much content. Close as IntelliJ issue.
