### ISSUE TITLE
Eclipse Remote debugging crashes the Azure App Service

### ISSUE THREAD

**Issue by nyuen** [microsoft/azure-tools-for-java#35]
Following the steps described in https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-debug-java-web-app-in-eclipse

Create a web app : Windows + Tomcat (newest) + Java (newest)
Configure the app service and eclipse as described in the documentation
Deploy a sample java web application
Run the remote debugger

=> the debugger keeps waiting for the connection without timeout, the app service plan is crashed with the following message:
**The specified CGI application encountered an error and the server terminated the process”, I’m then unable to retrieve the service and the only workaround is to delete the web app**

The only workaround is to delete the web app and create a new one

**Comment by martinsawicki** [comment]
part of webapp revamp in v3.0 - let's make sure remote debugging is stable, even though it won't work from behind proxy which doesn't support websockets.

**Comment by vladimir-shcherbakov** [comment]
move to backlog

**Comment by Ahmad-Al-Ali** [comment]
Hello Team, is remote debugging still supported by the latest version of the toolkit for eclipse ( 3.11 ) ?

**Comment by Ahmad-Al-Ali** [comment]
as per this issue https://github.com/microsoft/azure-tools-for-java/issues/2533 Remote debugging is no longer supported on Eclipse as it was removed in early 2017.

**Comment by Flanker32** [comment]
Close as the remote debugging feature is removed from Eclipse
