### ISSUE TITLE
[intelliJ][spark interactive console]Get error when run livy interactive console for airs cluster.

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3513]
Build:
azure-toolkit-for-intellij-2019.2.develop.1234.09-05-2019

Repro Steps:
1.Create a SQL Server Big Data Cluster configuration, choose spark cluster and main class.
2.Run livy interactive console from Tools/spark console.
Result:
Get error message.
![image](https://user-images.githubusercontent.com/43333874/64527478-e937a980-d2ba-11e9-872d-713bac07693b.png)

**Comment by t-rufang** [comment]
Fixed in #3529
