### ISSUE TITLE
[IntelliJ] Submitting an invalid script, the output window still prompts that the run was successful.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3519]
Build:
develop 1237

Repro Steps:

1. Create a project with a failure debug sample.
2. Submit "Age.Mean_Div0" to spark on Cosmos.
3. Check the output window

Result:
Still show "Job run Successfully."
![image](https://user-images.githubusercontent.com/40199316/64607336-e774ff80-d3fa-11e9-8560-d94edd6fd2e9.png)

Expectation:
Job should failed.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738915
