### ISSUE TITLE
[intelliJ][interactive console]Different performance when run interactive console for different application type

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3524]
Build:
develop 1241

Repro Steps:
1. Create a configuration, do not input any value then save it.
2. Run interactive console from Tools/Spark console.

Result:
The performance is different.
1. Spark on HDInsight
![image](https://user-images.githubusercontent.com/35950097/64668266-877c6880-d48f-11e9-8744-dd0fb938b246.png)
2. Spark on SQL Server Big data
![image](https://user-images.githubusercontent.com/35950097/64668432-22754280-d490-11e9-9e91-37d7c2d35b8f.png)
3. Spark on Cosmos
![image](https://user-images.githubusercontent.com/35950097/64668371-f35ed100-d48f-11e9-8736-7fde53efd2fe.png)
4. Spark on Arcadia
![image](https://user-images.githubusercontent.com/35950097/64668414-14bfbd00-d490-11e9-8b09-4e5e3964d1f0.png)

**Comment by t-rufang** [comment]
Will align the experience of HDInsight and Aris to Spark on Cosmos.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738914
