### ISSUE TITLE
[IntelliJ][RunConf]In Configuration dialog, "Remotely Run in Cluster" tab isn't disabled when you select local console from right click on project.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3528]
**Build:** https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_develop/1241/Azure/artifacts/azure-toolkit-for-intellij-2019.2.develop.1241.09-10-2019.zip

**Repro Steps:**

1. Create a new project.
2. Right click on LogQuery (Project->src->main->scala->sample->LogQuery)
3. Select Spark Console.
4. Click on Run Spark Local Console.
5. Check the "Remotely Run in cluster" tab in Configuration dialog.

**Result:**
 "Remotely Run in Cluster" tab isn't disabled
![image](https://user-images.githubusercontent.com/40199316/64683115-367f6b00-d4b5-11e9-80f8-d5a3dcf6442a.png)

**Expectation:**
 "Remotely Run in Cluster" tab should disabled, just like when you select the "Run Spark Livy Interactive Session Console", the "Locally Run" tab in the configuration window is disabled.
![image](https://user-images.githubusercontent.com/40199316/64683179-59118400-d4b5-11e9-9d70-814dbaba7551.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738913
