### ISSUE TITLE
App service creation can't use the existing service plan

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#353]
Repro steps:
Deploy a Web App with a new App service plan
Refresh Web App node after deployment
Right click the web app and choose delete.
After delete, not refresh Web App, right click the project and select Publish as Azure Web App...
Create a App service , using the service plan of the deleted Web App 
Error occurs, shown as below picture:
![image](https://cloud.githubusercontent.com/assets/22470312/25221766/db9aebce-25e8-11e7-8d10-0cef1bb5a518.png)

RESULT:
If not refresh App service container manually, the service plan of deleted web app will not disappear in the use existing list.
EXPECT:
The App service plan of deleted web app will not show in the list after refresh the app service container.
So either auto refresh after select publish as azure web app or  allow to use service plan of deleted web app.

**Comment by vladimir-shcherbakov** [comment]
Looks like a duplicate of
Exception when creating webapp with service plan containing no other webapps #163

**Comment by vladimir-shcherbakov** [comment]
@bsaby please verify ASAP.

**Comment by bsaby** [comment]
Repro in both IntelliJ and Eclipse.
Builds used:
artifacts/azure-toolkit-for-intellij.2017.373.04-25-2017.zip.
artifacts/WindowsAzurePlugin4EJ.378.04-25-2017.zip

**Comment by vladimir-shcherbakov** [comment]
Fixed only web app deletion on Deploy Web App form.

**Comment by bsaby** [comment]
Test passed on Web App deletion.
Builds used:
artifacts/WindowsAzurePlugin4EJ.383.04-26-2017.zip
artifacts/azure-toolkit-for-intellij.2017.378.04-26-2017.zip
