### ISSUE TITLE
[intelliJ][SQL Server big data]Get error when run interactive console twice using the same cluster.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3533]
Build:
develop 1246

Repro Steps:
1. Create a SQL Server Big data configuration, choose cluster and main cluster.
2. Run interactive console for it.
Result:
Job run successfully.
![image](https://user-images.githubusercontent.com/35950097/64750927-21561b00-d54d-11e9-91ab-e20283d42f6a.png)
3. Rerun interactive console for it.
Result:
Get error.
![image](https://user-images.githubusercontent.com/35950097/64751034-72fea580-d54d-11e9-95bc-7e8ac28a9994.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738912
