### ISSUE TITLE
[IntelliJ][SparkonSQL][Console] "Spark Livy Interactive session console is error" run interactive console after config rename. 

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3535]

**Comment by v-lanjli** [comment]
Build: https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_develop/1246/Azure/

Repro Steps:

1. Create a new project.
2. Create a Config for Spark on SQL.
3. Click on Tools->Spark Console->Run Spark Livy Interactive Session Console.
4. Reopen the config and rename.
5. Click Run Spark Livy Interactive Session Console again.
6. Check the results.

Result:
"Spark Livy Interactive session console is error" 
![image](https://user-images.githubusercontent.com/40199316/64753431-caa10f00-d555-11e9-8de6-417258880906.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738911
