### ISSUE TITLE
[intelliJ][Spark on Cosmos Serverless]Remotely run failed sometimes.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3536]
Build:
develop 1247

Repro Steps:
1. Create a Spark on Cosmos Serverless configuration.
2. Remotely run it.

Result:
Job run failed.
![image](https://user-images.githubusercontent.com/35950097/64755294-3d61b880-d55d-11e9-8a66-35e48e7a88f3.png)
Frequency: 
Sometimes.

**Comment by t-rufang** [comment]
This is supposed to be a backend issue
