### ISSUE TITLE
Cannot run war package using jetty9.3 with Java 11 configuration

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-tools-for-java#3545]
**Environment:**

1. OS: Windows10
2. Plugin version: Azure java toolkit for IntelliJ: 3.27.0
4. IntelliJ IDEA 2019.2.2 (Ultimate Edition)
   JRE: 11.0.3+12-b304.56 amd64
5. JDK: oracle jdk11.0.2

**Repro steps:**

1. Create a web project with AI config
2. In the Project tool window, right-click a project, and then select `Azure `> `Deploy to Azure`
3. Create and deploy to Windows Web App with the following runtime  
    JDK: 11
    Web Container: Jetty 9.3
4. Access URL

**Result:**

![图片](https://user-images.githubusercontent.com/41051257/64948012-ba1bcc00-d8a8-11e9-9ea3-8bd04e254d06.png)

**Comment by ZhengJun003** [comment]
Test in Azure java toolkit for IntelliJ: 3.27.0
Create a web project without AI config, then deploy to azure can access URL.

**Comment by ZhengJun003** [comment]
Test in Azure java toolkit for IntelliJ: 3.37.0, can reproduce this issue

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738776

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738817

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
