### ISSUE TITLE
Error when trying to connect to Microsoft Azrue with Eclipse Neon 3

### ISSUE THREAD

**Issue by dkdenkin** [Microsoft/azure-tools-for-java#356]
Hello,

I'm trying to connect from Eclipse (Neon 3) to a german Microsoft Azure subscription. I have installed the Azure Toolkit for Eclipse and still getting an error. Hence, I can't connect:

AD Auth token endpoint returned HTTP status code 400. Error info: {"error":"invalid_grant","error_description":"AADSTS70000: Transmission data parser failure: Authorization Code is malformed or invalid.\r\nTrace ID: a9e8c6b2-d0f9-483b-8917-426ead5e1800\r\nCorrelation ID: 44f46631-628a-40fd-9c2a-ac2978861eef\r\nTimestamp: 2017-04-24 13:31:55Z","error_codes":[70000],"timestamp":"2017-04-24 13:31:55Z","trace_id":"a9e8c6b2-d0f9-483b-8917-426ead5e1800","correlation_id":"44f46631-628a-40fd-9c2a-ac2978861eef"}

I believe the reason for this error is because of the german subscription. If I try to connect to an american subscription, I'm able to connect without any errors. But this doesn't help me because I necessarily need to connect to the german subscription. 

I know that my issue may be very country related, but does anyone know how to fix this problem? Or it is just not supported yet?

Many thanks in advance :)

**Comment by vladimir-shcherbakov** [comment]
You may want to [create Service Principal](https://github.com/Azure/azure-sdk-for-java/blob/master/AUTH.md#creating-a-service-principal-in-azure) and use service principal-based credentials file in Automated sign-in mode.

![image](https://cloud.githubusercontent.com/assets/6579928/25451590/8778ba92-2a77-11e7-9625-d57aa453792b.png)

**Comment by martinsawicki** [comment]
since it's the German cloud, which is sovereign and has special restrictions that the Toolkit currently cannot get past, you can try creating the auth file manually per these steps: https://go.microsoft.com/fwlink/?linkid=847862
Additionally, you will probably need to import the CER certificate for the German cloud (from the browser) and use Java's keytool to add it to JDK cert store. 
(We're working on publishing more detailed instructions soon, but if you want to give it a try on your own, pls let us know if you succeeded)

**Comment by jianghaolu** [comment]
Hi @dkdenkin 
Please follow the link given by @vladimir-shcherbakov to create a service principal.

In the case if you encounter a certificate error logging in, please run the following script to add the German cloud's certificate to your IntelliJ's trusted certificate store.

## German cloud on Mac:

1. Make sure you have OpenSSL installed.
2. Run the following to download the certificates:

```bash
echo -n | openssl s_client -connect management.core.cloudapi.de:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > azuregermancore.cer
echo -n | openssl s_client -connect management.microsoftazure.de:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > azuregermancloud.cer
echo -n | openssl s_client -connect login.microsoftonline.de:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > azuregermanlogin.cer
```

3. Run the following to import them to IntelliJ

```bash
sudo keytool -import -file azuregermanlogin.cer -keystore /Applications/IntelliJ\ IDEA.app/Contents/jdk/Contents/Home/jre/lib/security/cacerts -alias AzureGermanLogin
sudo keytool -import -file azuregermancloud.cer -keystore /Applications/IntelliJ\ IDEA.app/Contents/jdk/Contents/Home/jre/lib/security/cacerts -alias AzureGermanCloud
sudo keytool -import -file azuregermancore.cer -keystore /Applications/IntelliJ\ IDEA.app/Contents/jdk/Contents/Home/jre/lib/security/cacerts -alias AzureGermanCore
```

## German cloud on Windows:

1. Run the following in PowerShell to download the certificates:

```powershell
$webRequest = [Net.WebRequest]::Create("https://login.microsoftonline.de")
try { $webRequest.GetResponse() } catch {}
$cert = $webRequest.ServicePoint.Certificate
$bytes = $cert.Export([Security.Cryptography.X509Certificates.X509ContentType]::Cert)
set-content -value $bytes -encoding byte -path "azuregermanlogin.cer"
	
$webRequest = [Net.WebRequest]::Create("https://management.microsoftazure.de")
try { $webRequest.GetResponse() } catch {}
$cert = $webRequest.ServicePoint.Certificate
$bytes = $cert.Export([Security.Cryptography.X509Certificates.X509ContentType]::Cert)
set-content -value $bytes -encoding byte -path "azuregermancloud.cer"
	
$webRequest = [Net.WebRequest]::Create("https://management.core.cloudapi.de")
try { $webRequest.GetResponse() } catch {}
$cert = $webRequest.ServicePoint.Certificate
$bytes = $cert.Export([Security.Cryptography.X509Certificates.X509ContentType]::Cert)
set-content -value $bytes -encoding byte -path "azuregermancore.cer"
```

2. Run the following to import them to IntelliJ

```batch
keytool -import -file azuregermanlogin.cer -keystore "%INTELLIJ_INSTALLATION_ROOT%\jre\jre\lib\security\cacerts"  -alias AzureGermanLogin
keytool -import -file azuregermancloud.cer -keystore "%INTELLIJ_INSTALLATION_ROOT%\jre\jre\lib\security\cacerts"  -alias AzureGermanCloud
keytool -import -file azuregermancore.cer -keystore "%INTELLIJ_INSTALLATION_ROOT%\jre\jre\lib\security\cacerts"  -alias AzureGermanCore
```

## German cloud on Linux:

1. Make sure you have OpenSSL installed.
2. Run the following to download the certificates:

```bash
echo -n | openssl s_client -connect management.core.cloudapi.de:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > azuregermancore.cer
echo -n | openssl s_client -connect management.microsoftazure.de:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > azuregermancloud.cer
echo -n | openssl s_client -connect login.microsoftonline.de:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > azuregermanlogin.cer
```
3. Run the following to import them to IntelliJ

```bash
sudo keytool -import -file azuregermanlogin.cer -keystore $IDEA_INSTALLATION_ROOT/jre/jre/lib/security/cacerts -alias AzureGermanLogin
sudo keytool -import -file azuregermancloud.cer -keystore $IDEA_INSTALLATION_ROOT/jre/jre/lib/security/cacerts -alias AzureGermanCloud
sudo keytool -import -file azuregermancore.cer -keystore $IDEA_INSTALLATION_ROOT/jre/jre/lib/security/cacerts -alias AzureGermanCore
```

**Comment by martinsawicki** [comment]
@dkdenkin we think we know how to make the plugins work against the German cloud. It will require a manual step of creating the SP, but we should be able to automate the other steps mentioned above (the certs etc).
Now - here's the question: we don't have access to the German cloud, so can't test this support easily enough.
If we point you at a release candidate download by Monday, would you be able to try it and let us know if it works with your German subscription?

**Comment by dkdenkin** [comment]
Thank you so much for all your help! Im going to try out your suggestions throughout the weekend. Give you guys a feedback then.
@martinsawicki Of course I can test the release candidate for you. Point me at the download whenever you like and I will test it with my German subscription to let you know if it works. :)

**Comment by martinsawicki** [comment]
After the fix that we are about to publish, the only manual step needed in the case of sovereign clouds will be the creation of the auth file (and the service principal) as described [here](https://go.microsoft.com/fwlink/?linkid=847862).

**Comment by martinsawicki** [comment]
ok, we have now staged a release candidate at this unofficial update location: http://azuredownloads.blob.core.windows.net/eclipse/v3.0.1, which should enable support for Azure in Germany and China, assuming the user uses the automated login method and creates the auth file manually, as per [these steps](https://go.microsoft.com/fwlink/?linkid=847862). 
If you have access to Azure in Germany and China, pls let us know if this works for you before we make this update official. Thanks!

**Comment by dkdenkin** [comment]
I'm still trying to create the auth file with the "Creating a Service Principal in Azure" steps you have provided. In order to connect to the german cloud I have to switch the server by running

`az cloud set --name AzureGermanCloud`

However, after selecting the subscription and logging in, I put in the command to create a service principal authentication file

`curl -L https://raw.githubusercontent.com/Azure/azure-sdk-for-java/master/tools/authgen.py | python > my.azureauth`

and get the following error (on MAC OS X):


> File "<stdin>", line 22, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

By running the same command in Windows 10 (on "Bash on Ubuntu on Windows") I get the same error. An azureauth-file has been created though, but the file empty. What am I doing wrong?

**Comment by martinsawicki** [comment]
@jianghaolu ?

**Comment by jianghaolu** [comment]
@dkdenkin Can you manually run `az ad sp create-for-rbac` and see if you have the permission to create service principals?

**Comment by dkdenkin** [comment]
@jianghaolu 
That might be it!

>Role assignment creation failed.
role assignment response headers: {'Content-Length': '311', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'x-ms-failure-cause': 'gateway', 'x-ms-request-id': '(...)', 'Expires': '-1', 'x-ms-correlation-request-id': '(...)', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Date': 'Wed, 03 May 2017 19:03:50 GMT', 'x-ms-routing-request-id': '(...)', 'Content-Type': 'application/json; charset=utf-8'}
The client '(...)' with object id '(...)' does not have authorization to perform action 'Microsoft.Authorization/roleAssignments/write' over scope '/subscriptions/(...)'.

It seems I don't have the permission to create service principals. I'm going to contact the person who is responsible for setting the authorisation first. If you have any other suggestions for me please let me know.

**Comment by jianghaolu** [comment]
@dkdenkin Great! You found the issue. If you have access to any existing service principal you might also make use of that. In the portal you can navigate to Azure Active Directory -> App registrations -> Select one -> Keys. 
Then you can create an auth file manually by using the application ID as the `client` field, the tenant ID & subscription same as your user account's, and the key is the key you just added, in this format
```
subscription=########-####-####-####-############
client=########-####-####-####-############
key=XXXXXXXXXXXXXXXX
tenant=########-####-####-####-############
authURL=https\://login.microsoftonline.de/
managementURI=https\://management.core.cloudapi.de/
baseURL=https\://management.microsoftazure.de/
graphURL=https\://graph.cloudapi.de/
```

**Comment by martinsawicki** [comment]
Since we have now released the 3.0.1 update at the usual Eclipse update site (http://dl.microsoft.com/eclipse) with the discussed fixes in place, I believe we can close this issue now.
thanks

**Comment by dkdenkin** [comment]
I just wanted to let you guys know that the german cloud works fine. Thank you for all your support! Really appreciate it :)

**Comment by martinsawicki** [comment]
great to know this worked!  Thank you for validating.
