### ISSUE TITLE
The SSH key information can not be displayed correctly in Details dialog.

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#357]
Eclipse Neon.3 and Eclipse Mars.2
Build used: artifacts/WindowsAzurePlugin4EJ.383.04-26-2017.zip

1. Deploy a project as Docker Host without an SSH keys

2. After deployment, the Log in using SSH keys content shows "Yes" in Details dialog, even can export the SSH keys .
![image](https://cloud.githubusercontent.com/assets/22470312/25476091/9a68756c-2b6b-11e7-927f-ab12ee703070.png)

**Comment by milismsft** [comment]
Not a critical bug but since it was couple lines to fix it I checked in a fix for it; can you please verify?

**Comment by bsaby** [comment]
Test passed, using artifacts/WindowsAzurePlugin4EJ.389.04-27-2017.zip.
