### ISSUE TITLE
[Accessibility]MAS 4.2.8: (eclipse/edit '') An element of the given ControlType must support the Text pattern.

### ISSUE THREAD

**Issue by Tanushagottipati** [microsoft/azure-tools-for-java#3580]
The following accessibility issue needs investigation.

GitHubTags: #A11yTCS; #A11yMAS; #A11yAuto; #AI4D; #DesktopApp; #Win10; #A11y_Java Tooling for IntelliJ/Eclipse-New Feature; #MAS4.2.8; #C+E-H; #Java tooling for IntelliJ/Eclipse

**Note: This issue is found for** 
**'Main class Name', 'Command Line Arguments', 'Reference jars', 'Referenced Files' fields in Spark** **Submission popup**

**App:** eclipse

**Environment Details:**
Eclipse IDE for Enterprise Java Developers.
Version: 2019-06 (4.12.0)
Build id: 20190614-1200
Solution Installed: The Azure Toolkit for Eclipse 3.17.0
**OS Details:**
OS: Windows (Version 1903, Build: 18362.175)

**Element path:** edit ''

**Issue Details:** An element of the given ControlType must support the Text pattern. [Section 508 502.3.10](https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/single-file-version#502-interoperability-assistive-technology)

**How To Fix:** 1. Make sure the element has the appropriate ControlType property for its function.
2. If the current ControlType is correct, modify the element to support the Text pattern.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.

**MAS Reference:**
https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={2f57ba18-487d-4adc-a077-377be980e7d5}

![Eclipse keros 1](https://user-images.githubusercontent.com/41109135/65406984-b636ff00-ddfe-11e9-953f-cff9b47d03f9.png)

**Comment by Tanushagottipati** [comment]
Regressed in the below environment and the issue is not reproing. Hence closing the bug and attaching latest screenshot for reference
**Environment Details:**
Eclipse IDE for Enterprise Java Developers.
Version: 2019-06 (4.12.0)
Build id: 20190614-1200
Solution Installed: The Azure Toolkit for Eclipse 3.17.0
**OS Details:**
OS: Windows (Version 1903, Build: 18362.175)

![Screenshot (491)](https://user-images.githubusercontent.com/41109135/65950266-5a522300-e45b-11e9-8b4e-edd96de25c59.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1749684
