### ISSUE TITLE
[Accessibility]MAS 4.2.8: (eclipse/edit '') An element of the given ControlType must support the Text pattern.

### ISSUE THREAD

**Issue by Tanushagottipati** [microsoft/azure-tools-for-java#3587]
The following accessibility issue needs investigation.

GitHubTags: #A11yTCS; #A11yMAS; #A11yAuto; #AI4D; #DesktopApp; #Win10; #A11y_Java Tooling for IntelliJ/Eclipse-New Feature; #MAS4.2.8; #C+E-H; #Java tooling for IntelliJ/Eclipse

**Environment Details:**
Eclipse IDE for Enterprise Java Developers.
Version: 2019-06 (4.12.0)
Build id: 20190614-1200
Solution Installed: The Azure Toolkit for Eclipse 3.17.0
**OS Details:**
OS: Windows (Version 1903, Build: 18362.175)

**App:** eclipse

**Element path:** edit ''

**Issue Details:** An element of the given ControlType must support the Text pattern. [Section 508 502.3.10](https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/single-file-version#502-interoperability-assistive-technology)

**How To Fix:** 1. Make sure the element has the appropriate ControlType property for its function.
2. If the current ControlType is correct, modify the element to support the Text pattern.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.

**MAS Reference:**
https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={2f57ba18-487d-4adc-a077-377be980e7d5}

![Screenshot (467)](https://user-images.githubusercontent.com/41109135/65408689-863e2a80-de03-11e9-8d2e-d80cae865ee2.png)

**Comment by Tanushagottipati** [comment]
Regressed in the below environment and the issue is not reproing. Hence closing the bug and attaching latest screenshot for reference
**Environment Details:**
Eclipse IDE for Enterprise Java Developers.
Version: 2019-06 (4.12.0)
Build id: 20190614-1200
Solution Installed: The Azure Toolkit for Eclipse 3.17.0
OS Details:
OS: Windows (Version 1903, Build: 18362.175)

![Screenshot (490)](https://user-images.githubusercontent.com/41109135/65950403-9b4a3780-e45b-11e9-8989-4240e781b190.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1749731
