### ISSUE TITLE
Can't create new resource group deploying web app in Eclipse

### ISSUE THREAD

**Issue by shaunm-msft** [Microsoft/azure-tools-for-java#36]
Eclipse Java EE IDE for Web Developers.
Version: Neon.2 Release (4.6.2)
Build id: 20161208-0600
+
Azure Toolkit for Eclipse 2.9.5

Click "Publish as Azure Web App..."
Click "New..." to create a new container
Click "New..." to create a new Resource Group.

No regions are selectable.
The OK button is disabled.

**Comment by martinsawicki** [comment]
looks like something got broken in how Azure returns regions for *some* subscriptions. This issue does not actually repro for an MSDN subscription we tried, but it repros for another, non-MSDN subscription, which used to work just fine before...
On v3.0, we are switching to a new SDK/new Compute API version, so maybe this API is more resilient there.
(Currently, in the live builds of v3.0, everything works ok)

**Comment by vladimir-shcherbakov** [comment]
old plugin.
