### ISSUE TITLE
Error reading Dockerfile content.

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#360]
Eclipse Neon.3
BUild used:artifacts/WindowsAzurePlugin4EJ.389.04-27-2017.zip.

If I deploy a project as Docker Container using Dockerfile, it always show that error reading Dockerfile content.
![image](https://cloud.githubusercontent.com/assets/22470312/25511201/fb53cda4-2bf7-11e7-901c-1500b63d7585.png)

**Comment by milismsft** [comment]
Fixed; can you please verify?

**Comment by bsaby** [comment]
Test passed, using artifacts/WindowsAzurePlugin4EJ.390.04-27-2017.zip.
