### ISSUE TITLE
IntelliJ: Could not initialize class retrofit2.Platform java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by vladimir-shcherbakov** [microsoft/azure-tools-for-java#363]
Also getting Sign In error. When trying to sign into my Azure account via the toolkit on IntelliJ via the Interactive option, immediately after entering my credentials I get either a null or could not initalize class retrofit2 error. I have signed in perfectly fine before but for some reason, I'm getting this current error. This is all while trying to deploy a simple Java Web App.

Could not initialize class retrofit2.Platform java.lang.NoClassDefFoundError: Could not initialize class retrofit2.Platform at retrofit2.Retrofit$Builder.<init>(Retrofit.java:402) at com.microsoft.rest.RestClient$Builder.<init>(RestClient.java:165) at com.microsoft.azure.management.resources.fluentcore.arm.implementation.AzureConfigurableImpl.<init>(AzureConfigurableImpl.java:34) at com.microsoft.azure.management.Azure$ConfigurableImpl.<init>(Azure.java:190) at com.microsoft.azure.management.Azure$ConfigurableImpl.<init>(Azure.java:190) at com.microsoft.azure.management.Azure.configure(Azure.java:161) at com.microsoft.azuretools.sdkmanage.AccessTokenAzureManager.authTid(AccessTokenAzureManager.java:133) at com.microsoft.azuretools.sdkmanage.AccessTokenAzureManager.getTenants(AccessTokenAzureManager.java:118) at com.microsoft.azuretools.authmanage.AdAuthManager.signIn(AdAuthManager.java:84) at com.microsoft.azuretools.ijidea.ui.SignInWindow$5.run(SignInWindow.java:203) at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726) at com.intellij.openapi.progress.impl.CoreProgressManager$6.run(CoreProgressManager.java:410) at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176) at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556) at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501) at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66) at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163) at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:594) at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745)

**Comment by martinsawicki** [comment]
This is a bug in 3rd party component(s) that both INtelliJ and Azure Toolkit rely on. It looks like there is logic in some of them which checks for Android OS, but the check is done in an incorrect way - it's catching Exception (checked), not Throwable (unchecked), but the call used to check for it throws Throwable. So it is effectively not caught and hence the exception.
There is nothing (reasonable enough) we can do about this on the Azure Toolkit end that we have been able to find.

Simplest workarounds seem to be:
a) disable the Android Support plugin in INtelliJ
b) install the Android SDK

(the Azure Toolkit has nothing to do with Android - this is just due to sharing some of the same 3rd party libraries between the Toolkit and IntelliJ's Android support, which have this issue.)

**Comment by milismsft** [comment]
This issue has to do with how 3rd party libraries (Retrofit2 and RxJava) account for the Android as a supported platform. 

For instance in [retrofit](https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit2/Platform.java#L36) the expected exception when Android is not a supported platform is ClassNotFoundException but instead when Android Support plugin is enabled IntelliJ throws a NoClassDefFoundError. 

Similarly in [RxJava](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/internal/util/PlatformDependent.java#L66) where the code expects an Exception when Android is not found and a Throwable object is issued instead.

**Comment by martinsawicki** [comment]
Bottom line: no reasonable enough code workaround possible in the Azure Toolkit.
Known manual workarounds:
- disable the Android Support plugin in IntelliJ
- or install the Android SDK

**Comment by Flanker32** [comment]
Close as we have deprecated the interactive login method and use service principal/device login instead
