### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading Web Apps

### ISSUE THREAD

**Issue by Neco-Menzies** [microsoft/azure-tools-for-java#3653]
IntelliJ build version: 2019.2.3 IU-192.6817.14
OS: Windows 10
JDK: JetBrains s.r.o 11.0.4
Plugin version: 3.27.0-2019.2
Error message: 
```
java.lang.RuntimeException: com.microsoft.azuretools.adauth.AuthException: AD Auth token endpoint returned HTTP status code 400. Error info: {"error":"invalid_request","error_description":"AADSTS90002: Tenant 'null' not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator.\r\nTrace ID: f765fd94-a7aa-40b7-a632-6bcd18430b00\r\nCorrelation ID: d0441044-b861-40c4-982e-55adffeea242\r\nTimestamp: 2019-10-11 06:48:49Z","error_codes":[90002],"timestamp":"2019-10-11 06:48:49Z","trace_id":"f765fd94-a7aa-40b7-a632-6bcd18430b00","correlation_id":"d0441044-b861-40c4-982e-55adffeea242","error_uri":"https://login.microsoftonline.com/error?code=90002"}
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.list(WebAppsInner.java:1703)
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.TopLevelM

**Comment by Neco-Menzies** [comment]
Signing out and back in again from intellij temporarily solved the issue.

**Comment by Flanker32** [comment]
@Neco-Menzies Thanks for your feedback, could you please share a bit more information for this issue? Like how do you auth to Toolkits and could it be reproduced?

**Comment by Neco-Menzies** [comment]
not sure on how to reproduce. I use the auth flow from the plugin. it seems to only happen on startup sometimes. I need to log out of the Azure plugin and back in to fix.

**Comment by Flanker32** [comment]
@Neco-Menzies Thanks for your information, one more question, did you use `Device Login` or `Service Principal`?
![image](https://user-images.githubusercontent.com/12445236/66633216-e1ae4c00-ec3c-11e9-9f5e-c1e2d8ad5b23.png)

**Comment by Neco-Menzies** [comment]
Device Login

**Comment by Flanker32** [comment]
@Neco-Menzies Got it, will update here once there are progress.

**Comment by TarunKurella** [comment]
facing the same error

**Comment by TarunKurella** [comment]
singing-out then in  makes it back to normal as stated

**Comment by Flanker32** [comment]
@TarunKurella @Neco-Menzies  Thanks for your report, we have released a fix about authentication, could this issue still be reproduced?

**Comment by Neco-Menzies** [comment]
@Flanker32 Thanks, it seems to be fine again now without having to log out and back in again.

**Comment by andxu** [comment]
seems fixed from Neco-Menzies' message
