### ISSUE TITLE
[IntelliJ][ESP] Uncaught Exception get applications list error com.microsoft.azure.hdinsight.sdk.common.HDIException: - Authentication failed

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3676]
**IntelliJ build version:** 2019.2.3 IC-192.6817.14
**OS:** Windows 10
**JDK:** JetBrains s.r.o 11.0.4
**Plugin version:** https://dev.azure.com/mseng/_apis/resources/Containers/10741572?itemPath=drop%2Fazure-toolkit-for-intellij-2019.2.develop.10712075.10-22-2019.zip
**Additional Info:** None

**Repro Steps:**
1. Install the private build: https://dev.azure.com/mseng/_apis/resources/Containers/10741572?itemPath=drop%2Fazure-toolkit-for-intellij-2019.2.develop.10712075.10-22-2019.zip  
2. Sign in to Azure use this account: jejiang@hdicore.com
3. Expand **HDInsight** node in Azure Explorer
4. Expand **hib003** 
5. Click on **Jobs** node

**Screen:**
![image](https://user-images.githubusercontent.com/40199316/67386898-63e92980-f5c8-11e9-83e6-dbcd284c78b2.png)

Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1441x860,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=get applications list error, throwable=com.microsoft.azure.hdinsight.sdk.common.HDIException: - Authentication failed
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.getEntity(JobUtils.java:424)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkRestUtil.getSparkRestEntity(SparkRestUtil.java:146)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkRestUtil.getSparkApplications(SparkRestUtil.java:58)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkJobHttpHandler.handle(SparkJobHttpHandler.java:54)
```

**Comment by lcadzy** [comment]
https://github.com/microsoft/azure-tools-for-java/pull/3729

**Comment by jingyanjingyan** [comment]
Build：azure-toolkit-for-intellij-2019.2.4.develop.1317.12-10-2019.zip
Could open job nodes of ESP cluster.
