### ISSUE TITLE
[IntelliJ][ReportedByUser] HDInsight Explorer

### ISSUE THREAD

**Issue by weiss-gal** [microsoft/azure-tools-for-java#3681]
IntelliJ build version: 2018.3.2 IC-183.4886.37
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.17.0-2018.3
Error message: 
```
{"code":"MethodNotAllowed","message":"Getting cluster configurations using HTTP method 'GET' is not supported. Please use HTTP method 'POST' instead."}
```

**Comment by wezhang** [comment]
Thanks @weiss-gal ! Could you upgrade to the most new version and try it again?

**Comment by fengshuaihu** [comment]
Please update to the latest version and try again, if you encounter this issue again, feel free to turn it on again
