### ISSUE TITLE
[IntelliJ][ReportedByUser][2019.3EAP] Uncaught Exception  java.lang.Throwable: HIDE_DEFAULT_EDITOR is supported only for DumbAware providers; class com.microsoft.azure.hdinsight.jobs.framework.JobViewEditorProvider is not DumbAware.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3684]
**IntelliJ build version:** 2019.3 EAP IC-193.4778.7
**OS:** Mac OS X
**JDK:** JetBrains s.r.o 11.0.4
**Plugin version:** 3.28.0-LATEST-EAP-SNAPSHOT
**Additional Info:** None

**Repro Steps:**

1. Open IntelliJ with 2019.3 EAP
2. Install the EAP plugin
3. Sign in to Azure
4. Expand HDInsight in Azure Explorer
5. Select a cluster in list and expand it
6. Click on Job node
7. Check the red exclamation point in the lower right corner

**Parent component:** 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1280x691,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
**Error message:** 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: HIDE_DEFAULT_EDITOR is supported only for DumbAware providers; class com.microsoft.azure.hdinsight.jobs.framework.JobViewEditorProvider is not DumbAware.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.microsoft.azure.hdinsight.common.HDInsightHelperImpl$1.run(HDInsightHelperImpl.java:116)
```
![image](https://user-images.githubusercontent.com/40199316/67825659-02afe180-fb05-11e9-8d56-3c2bf25df839.png)

**Comment by wezhang** [comment]
@lcadzy , could you help to check it?

**Comment by Flanker32** [comment]
Fixed in the latest releasse
