### ISSUE TITLE
[IntelliJ][EAP][Config]Can't get arcadia compute connection URL.

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3688]
Build:azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.10727955.10-24-2019

Repro Steps:
1.Create a new project
2.Create an arcadia configuration
3. Fill in all the information you need include Job upload Storage
4.Click Apply 

Result:
Can't get URL prompt pop-up

![image](https://user-images.githubusercontent.com/43333874/67833434-da42cb80-faa1-11e9-92f5-4022e1de4c47.png)

**Comment by t-rufang** [comment]
@v-xiaocw This issue should not repro now. Please help verify.

**Comment by v-xiaocw** [comment]
Verified and fixed
