### ISSUE TITLE
[IntelliJ][2019.3 EAP][console]Cannot run local console directly without config

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3691]
**IntelliJ build version:** 2019.3 EAP IC-193.4778.7
**OS:** Mac/Win/Linux
**JDK:** JetBrains s.r.o 11.0.4
**Plugin version:** 3.28.0-LATEST-EAP-SNAPSHOT

**Repro Steps:**

1. Create a new project or open an unconfigured project
2. Click Tools -> Spark Console -> RunSpark Local Console(Scala)
3. Fill in the Main class name in Configuration
4. Click Run button

**Actual:** Error running
![image](https://user-images.githubusercontent.com/40199316/67836454-a14d3a00-fb27-11e9-899b-7cc81267859d.png)

**Comment by v-xiaocw** [comment]
Interactive console is the same result.
![image](https://user-images.githubusercontent.com/43333874/67839762-a1125780-fab1-11e9-999d-60a6768c9279.png)

**Comment by v-lanjli** [comment]
Verified and fixed, closed this issue.
