### ISSUE TITLE
[IntelliJ][2019.2]The Spark job failed to start

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3694]
**IntelliJ build version:** IntelliJ IDEA 2019.2.3 (Community Edition)
**OS:** Mac/Win/Linux
**Plugin version:** artifacts/azure-toolkit-for-intellij-2019.2.develop.1279.10-29-2019.zip

**Repro Steps:**

1. Open IntelliJ and install the plugin
2. Sign in to Azure
3. Create Apach Spark on HDInsight Config
4. Select a Spark cluster
5. Configure the storage type
6. Click on OK button
7. Click on SparkJobRun button
8. Check the result in output window

**Actual:** ERROR: The Spark job failed to start.
![image](https://user-images.githubusercontent.com/40199316/67849248-3e689c80-fb41-11e9-964e-33b66ebcc302.png)
ERROR: The Spark job failed to start due to 19/10/30 10:06:05 INFO AzureFileSystemThreadPoolExecutor: Time taken for Delete operation is: 21 ms with threads: 0
19/10/30 10:06:05 INFO ShutdownHookManager: Shutdown hook called
19/10/30 10:06:05 INFO MetricsSystemImpl: Stopping azure-file-system metrics system...
19/10/30 10:06:05 INFO MetricsSinkAdapter: azurefs2 thread interrupted.
19/10/30 10:06:05 INFO MetricsSystemImpl: azure-file-system metrics system stopped.
19/10/30 10:06:05 INFO MetricsSystemImpl: azure-file-system metrics system shutdown complete.

For more detailed output, check the application tracking page: https://mandywne.azurehdinsight.net/yarnui/hn/cluster/app/application_1562219906207_0037 Then click on links to logs of each attempt.
. Failing the application.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738909
