### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3696]
**IntelliJ build version**: 2019.2/2019.3 EAP
**OS**: Windows/Mac/Linux
**JDK**: JetBrains s.r.o 11.0.4
**Plugin version**: Market build
**Additional Info**: None
**Repro Steps**:

1. Open IntelliJ and install the plugin
2. Sign in to Azure with reader-only role permission
3. Click on HDInsight node in Azure Explorer
4. Click on Reader-only role permission cluster, then the cluster is expanded
5. Click on Jobs node
6. Check the red exclamation point in the lower right corner

**Parent component:** 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1441x860,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
**Error message:** 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException
	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:217)
	at com.microsoft.azuretools.ijidea.ui.WarningMessageForm.$$$setupUI$$$(WarningMessageForm.java)
	at com.microsoft.azuretools.ijidea.ui.WarningMessageForm.<init>(WarningMessageForm.java:48)
	at com.microsoft.azure.hdinsight.common.HDInsightHelperImpl$4$1.<init>(HDInsightHelperImpl.java:203)
	at com.microsoft.azure.hdinsight.common.HDInsightHelperImpl$4.run(HDInsightHelperImpl.java:203)
```
![image](https://user-images.githubusercontent.com/40199316/67927642-19813180-fbf4-11e9-9d67-441388b8200d.png)

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Uncaught Exception  java.lang.NullPointerException (#3814)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:217)

**Comment by t-rufang** [comment]
@v-lanjli Please help verify this issue in the latest release, it should have been fixed now.
