### ISSUE TITLE
Can't create new App Service Plan in Eclipse

### ISSUE THREAD

**Issue by shaunm-msft** [Microsoft/azure-tools-for-java#37]
Eclipse Java EE IDE for Web Developers.
Version: Neon.2 Release (4.6.2)
Build id: 20161208-0600
+
Azure Toolkit for Eclipse 2.9.5

Click "Publish as Azure Web App..."
Click "New..." to create a new container
Click "New..." to create a new App Service Plan.

No locations are selectable.
The OK button is disabled.

**Comment by martinsawicki** [comment]
from what we can see, the released plugin version was broken by a change in Azure after release and what functioned ok stopped working later, apparently as a result of a change on the service side..
Need to make sure this works again in the next version.

**Comment by vladimir-shcherbakov** [comment]
old plugin.
