### ISSUE TITLE
[intelliJ][19.3 EAP]There are errors in displaying context menu.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3700]
Build:
azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.10727955.10-24-2019

Repro Steps:
1. Right click LogQuery then select locally run.
2. Right click LogQuery after localy running.

Result:
1. It is different from 19.2.
2. There is extra " ... "
19.3 EAP Linux/windows:
![image](https://user-images.githubusercontent.com/35950097/67937877-56a3ee80-fc09-11e9-8983-d66fdc9145ee.png)
19.2 Windows:
![无标题](https://user-images.githubusercontent.com/35950097/67938430-6b34b680-fc0a-11e9-9459-e3ae401f61ff.png)

**Comment by v-jiche** [comment]
Build:
azure-toolkit-for-intellij-2019.2.develop.1314.12-03-2019
azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.11021963.12-04-2019

Result:
Need to know the design of the location of the "..."
19.2 windows 1314 build
![image](https://user-images.githubusercontent.com/35950097/70133079-64dda280-16c0-11ea-80d7-43998aa43d37.png)
![image](https://user-images.githubusercontent.com/35950097/70133092-6d35dd80-16c0-11ea-89db-a80d0444b679.png)
19.3 windows:
![image](https://user-images.githubusercontent.com/35950097/70133109-7626af00-16c0-11ea-93de-fce6e64fba1f.png)
![image](https://user-images.githubusercontent.com/35950097/70133127-80e14400-16c0-11ea-9409-c18b8d25a30c.png)

**Comment by wezhang** [comment]
The fix is only for 193 now.

**Comment by v-jiche** [comment]
Build: 
azure-toolkit-for-intellij-2019.3.develop.11178477.12-26-2019

Fixed in 193.
