### ISSUE TITLE
[intelliJ]Suggest to change the warning message when submit job with empty cluster

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3701]
Build:
azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.10727955.10-24-2019
azure-toolkit-for-intellij-2019.2.develop.1281.10-31-2019

Environment:
2019.2
2019.3 EAP

Repro Steps:
1.  Create a new project.
2.  Right click LogQuery then select locally run.
3.  Right click LogQuery then select remotely run, select "Continue anyway"
Result:
Get error message.
![image](https://user-images.githubusercontent.com/35950097/67941789-632c4500-fc11-11e9-84d9-9a901380511a.png)
5. Right click LogQuery then select submit Spark application, select "Continue anyway".
Result:
![image](https://user-images.githubusercontent.com/35950097/67941946-a71f4a00-fc11-11e9-8a90-48ac22633a3c.png)
7. Click remotely icon then select "continue anyway".
Result:
![image](https://user-images.githubusercontent.com/35950097/67942061-f2395d00-fc11-11e9-85fc-8ae1ef156c19.png)

Expectation:
Get error message.
![image](https://user-images.githubusercontent.com/35950097/67942139-23199200-fc12-11e9-9555-2c306e360f4e.png)

Key:
Right click LogQuery then select locally run to create a configuration.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738908
