### ISSUE TITLE
[intelliJ][spark on arcadia]Unreasonable error message when compute is empty.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3702]
Build:
azure-toolkit-for-intellij-2019.2.develop.1281.10-31-2019
azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.10727955.10-24-2019

Env:
19.3 EAP
19.2

Repro Steps:
1. Sign in Azure 
2. Open Run/Debug Configurations window then create an arcadia configuration.
Result:
Suggest to change the error message.
![image](https://user-images.githubusercontent.com/35950097/67943565-35e19600-fc15-11e9-9ede-92523bfd987c.png)
3. Sign out azure.
4. Open Run/Debug Configurations window.
Result:
![image](https://user-images.githubusercontent.com/35950097/67943670-7e00b880-fc15-11e9-9582-23bd28a8c377.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738907
