### ISSUE TITLE
[intelliJ][Spark on cosmos]Ureasonable error message when submit with empty cluster.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3703]
Build:
azure-toolkit-for-intellij-2019.2.develop.1281.10-31-2019
azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.10727955.10-24-2019

Env:
2019.2
2019.3 EAP

Repro Steps:
1.  Sign in Azure.
2.  Open Run/Debug Configurations window
3. Create a spark on cosmos configuration, do not select spark cluster.
4.  Click remotely run icon to run job.
Result:
![image](https://user-images.githubusercontent.com/35950097/67944324-2c592d80-fc17-11e9-9ac5-8f3865489642.png)
5. Right click LogQuery then select remotely run.
Result:
![image](https://user-images.githubusercontent.com/35950097/67944367-45fa7500-fc17-11e9-83a7-e091a2d7dd9a.png)

Expectation:
1. The text "sign in" should not be there cause it is in the state of sign-in.
2.  Should "Azure Serverless" be there? May be "Spark cluster" is enough.

**Comment by t-rufang** [comment]
Duplicate with #3705. Please help verify and close this issue.

**Comment by v-jiche** [comment]
Duplicate.
Closed.
