### ISSUE TITLE
[intelliJ]Suggest to make the format of the error message consistent.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3705]
Build:
azure-toolkit-for-intellij-2019.2.develop.1281.10-31-2019
azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.10727955.10-24-2019

Env:
19.3 EAP
19.2

Repro Steps:
Azure: sign in/sign out
1. Open Run/Debug configurations window.
2. Create an empty arcadia configuration then click icon to remotely run it.
Result:
![image](https://user-images.githubusercontent.com/35950097/67946488-742e8380-fc1c-11e9-828c-6f9de09557fe.png)
3. Create an empty cosmos  configuration then remotely run it.
Result:
![image](https://user-images.githubusercontent.com/35950097/67946534-890b1700-fc1c-11e9-9da7-7b28c0b74ad2.png)
4. Create an empty serverless  configuration then remotely run it.
Result:
There is one  ' ' .
![image](https://user-images.githubusercontent.com/35950097/67946591-9f18d780-fc1c-11e9-92f5-a483cf59831c.png)
5. Create an empty hdinsight  configuration then remotely run it.
Result:
![image](https://user-images.githubusercontent.com/35950097/67946627-b48e0180-fc1c-11e9-9738-08d461ca86e3.png)
5. Create an empty SQL Server configuration then remotely run it.
Result:
![image](https://user-images.githubusercontent.com/35950097/67946655-c2438700-fc1c-11e9-8e5b-5cbb7884ac01.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738905
