### ISSUE TITLE
[intelliJ][19.3 EAP][Spark on arcadia]Can not list computes.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3713]
Build:
azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.10727955.10-24-2019

Repro Steps:
1. Open Azure Explorer then refresh "Apache Spark on Arcadia" node.
2. Open Run/Debug Configurations window.
3. Create an arcadia configuration.
4. Choose Remotely run in cluster tab.
5.  Click Spark clusters(Linux only) part.

Result:
Can not list computes.
![1](https://user-images.githubusercontent.com/35950097/68018473-33924100-fcd4-11e9-8235-79f0c23fb2b8.gif)

All the computes can be listed in windows 19.2 with the same operation.

**Comment by t-rufang** [comment]
This issue should have been fixed, @v-jiche please help verify.

**Comment by v-jiche** [comment]
Build:
azure-toolkit-for-intellij-2019.3.develop.11178477.12-26-2019

Verified. Fixed.
