### ISSUE TITLE
[intelliJ][Arcadia]Some workspace can not refresh.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3715]
Build:
azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.10727955.10-24-2019
azure-toolkit-for-intellij-2019.2.develop.1282.10-31-2019

Env:
19.3 EAP
19.2

Repro Steps:
1. Open Azure Explorer.
2. Refresh Apache Spark on Arcadia node.
3. Click the workspace to refresh.

Result:
Some workspace can not refresh.
![1](https://user-images.githubusercontent.com/35950097/68019854-ce404f00-fcd7-11e9-9e5b-01f7a2ebefe0.gif)

**Comment by t-rufang** [comment]
This issue should be fixed in #3822. @v-jiche please help verify this issue.

**Comment by jingyanjingyan** [comment]
In build dev 1322, refresh workspace could display it's computes success, unless the workspace does not include any spark pool.

**Comment by v-jiche** [comment]
Build:
azure-toolkit-for-intellij-2019.3.develop.11178477.12-26-2019
azure-toolkit-for-intellij-2019.2.4.develop.1342.01-08-2020

Verified. Fixed.
