### ISSUE TITLE
Azure subscriptions are not listing in eclipse

### ISSUE THREAD

**Issue by dduleep** [microsoft/azure-tools-for-java#3716]
Even though I install the Azure eclipse plugin, the Azure subscriptions are not listing after the click on refresh icon.

Eclipse IDE Version: 2019-09 R (4.13.0)

Build id: 20190917-1200

AND

Eclipse IDE Version: Photon Release (4.8.0)

Build id: 20180619-1200

![image](https://user-images.githubusercontent.com/14990589/68084388-cbfc0300-fe45-11e9-8f74-4fdd849b6b4c.png)

![image](https://user-images.githubusercontent.com/14990589/68084400-f8178400-fe45-11e9-8a14-4d40d2d363e8.png)

**Comment by Flanker32** [comment]
@dduleep Thanks for your report, is this issue reproducible after logout and login? And could you please share us which auth method did you use to auth Azure?

**Comment by dduleep** [comment]
Authentication Method: direct login
It is reproducible after logout and login

![image](https://user-images.githubusercontent.com/14990589/68185482-ac361d80-ffb2-11e9-85a5-16a2ddbb894e.png)

**Comment by Flanker32** [comment]
@dduleep Thanks for your information, i tried to login in with device login and refresh the subscription list in subscription dialog, but it seems works well. (Eclipse 4.13.0).
Could you auth in azure cli with device login? you may do the auth by execute `az login --use-device-code`. Besides, could you please try to remove `AzureToolsForEclipse` folder in user home and try again?

**Comment by wezfaas** [comment]
Mine issue is similar, it only shows 2 subscriptions, but I have more than a few subscriptions.  And the one I need isn't showing, very frustrating, tried logout-login twice...

**Comment by BIJUSR** [comment]
I'm facing something similar but the app service list is not getting refreshed.. It's sporadic in nature, for a few days it works well but then stops for a few days and again starts working. It happens with my colleagues also at the same time.

![image](https://user-images.githubusercontent.com/54603631/187824516-55e6eb09-d53a-4970-9e18-2885087ff053.png)

**Comment by Flanker32** [comment]
> I'm facing something similar but the app service list is not getting refreshed.. It's sporadic in nature, for a few days it works well but then stops for a few days and again starts working. It happens with my colleagues also at the same time.
> 
@BIJUSR Thanks for your report and sorry for the trouble,  could you please help share the log file of your workspace (should locate in `${work spapce}\.metadata\.log`) to help us investigate this issue. By the way, does azure explorer works in your toolkit? Could you see your web apps in Azure explorer?
