### ISSUE TITLE
[IntelliJ][ESP]Can't start Livy interactive session

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3734]
**Build:** https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_develop/1292/Azure/processDownloadRequest/artifacts/azure-toolkit-for-intellij-2019.2.develop.1292.11-12-2019.zip
**IntelliJ Version:** 2019.2
**OS:** Windows

**Repro Steps:**

1. Open IntelliJ IDEA.
2. Click on Edit Configuration
3. Navigate to Tools -> Spark console -> Run Spark Livy Interactive Session Console(Scala)

**Results:** Can't start Livy interactive session.
**Error Message:** Can't start Livy interactive session: {"Code":"Unauthorized","Message":"Ambari user name or password is incorrect: admin","CorrelationId":"177e7e273a6f4e048cbce8cccd2e4302","ResponseTimestamp":"2019-11-13T03:44:30.6501515Z"}
![image](https://user-images.githubusercontent.com/40199316/68731783-2c403100-060c-11ea-8c4a-8705e77df037.png)

**Comment by lcadzy** [comment]
https://github.com/microsoft/azure-tools-for-java/pull/3744

**Comment by jingyanjingyan** [comment]
Could launch livy interactive console session success in build azure-toolkit-for-intellij-2019.2.4.develop.1317.12-10-2019.zip.
