### ISSUE TITLE
[IntelliJ][ESP][AzureExplorer]Containers cannot be listed.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3740]
**Build:** https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_develop/1295/Azure/processDownloadRequest/artifacts/azure-toolkit-for-intellij-2019.2.develop.1295.11-14-2019.zip
**IntelliJ Version:** 2019.2
**OS:** Windows

**Repro Steps:**

1. Open IntelliJ IDEA
2. Install the build
3. Use this account(jejiang@hdicore.com) to sign in to Azure
4. Expand Azure node in Azure Explorer
5. Expand HDInsight -> zhouyhib cluster -> Storage Accounts
6. Click on hdicorehns 
7. Check the results

**Results:** Unable to list containers. In fact, there are containers in this storage account.
![IntelliJ ESP Containers cannot be listed](https://user-images.githubusercontent.com/40199316/68917335-c6d37800-07a4-11ea-85f9-5aa3b29aa661.gif)

![image](https://user-images.githubusercontent.com/40199316/68917120-d7cfb980-07a3-11ea-8af5-4a87f1de367c.png)

**Comment by lcadzy** [comment]
store SDK for listing container is not valid for gen2 account. Will fix for next iteration.
