### ISSUE TITLE
[IntelliJ][ESP][RunConf]When from 'Change Configuration Settings' dialog to the 'Edit Configuration' dialog, some red font warnings appear in it and the computer is obviously slower

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3741]
**Build:** https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_develop/1295/Azure/processDownloadRequest/artifacts/azure-toolkit-for-intellij-2019.2.develop.1295.11-14-2019.zip
**IntelliJ Version:** 2019.2
**OS:** Windows

**Repro Steps:**

1. Open IntelliJ IDEA
2. Install the build
3. Use this account(jejiang@hdicore.com) to sign in to Azure
4. Click on Edit Configurations
5. Select Apache Spark on HDInsight template
6. Fill in Main class name
7. Switch to Remotely Run in Cluster
8. For Spark cluster, select zhouyhib
9. For Storage Type, select Use cluster default storage account to upload
10. Enable Spark remote debug
11. In SSH password, feel free to fill out
12. Click on Apply button
13. Click on SparkJobDebug button, then Change Configuration Settings pops up
14. Click on Edit button, then Edit configuration pops up
15. Check the results

**Results:** Show some red font warnings and obvious stuck.
![Show some red font warnings and obvious stuck](https://user-images.githubusercontent.com/40199316/68918522-6c88e600-07a9-11ea-8e05-a4513f939337.gif)

**Comment by wezhang** [comment]
@v-lanjli , it this issue still reproduced?

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738903
