### ISSUE TITLE
[IntelliJ][ESP][Debug]The Spark job remote debug is cancelled due to UnknowServiceException

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3742]
**Build:** https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_develop/1295/Azure/processDownloadRequest/artifacts/azure-toolkit-for-intellij-2019.2.develop.1295.11-14-2019.zip
**IntelliJ Version:** 2019.2
**OS:** Windows

**Repro Steps:**

1. Open IntelliJ IDEA
2. Install the build
3. Use this account(jejiang@hdicore.com) to sign in to Azure
4. Click on Edit Configurations
5. Select Apache Spark on HDInsight template
6. Fill in Main class name
7. Switch to Remotely Run in Cluster
8. For Spark cluster, select zhouyhib
9. For Storage Type, select Use cluster default storage account to upload
10. Enable Spark remote debug, and enter the correct password
11. Click on Apply button
12. Click on SparkJobDebug button
13. Check the results

**Results:** Error running.
![image](https://user-images.githubusercontent.com/40199316/68923624-b24daa80-07b9-11ea-9b5a-40800f21258f.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738902
