### ISSUE TITLE
[IntelliJ][RunConfig]The prompt should be aligned with the input box

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3745]
Build: azure-toolkit-for-intellij-2019.2.develop.1295.11-14-2019

Repro Steps:
1.Open IntelliJ IDEA
 2.Install the build
3.Use this account(jejiang@hdicore.com) to sign in to Azure
4.Click on Edit Configurations
5.Select Apache Spark on HDInsight template

Result:
![image](https://user-images.githubusercontent.com/43333874/68926728-0ebdb500-073b-11ea-8679-4bd281e956ab.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738901
