### ISSUE TITLE
[IntelliJ][RunConfig]The input box should not move as the characters entered increase

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3746]
Build: azure-toolkit-for-intellij-2019.2.develop.1295.11-14-2019

Repro Steps:
1.Open IntelliJ IDEA
2.Install the build
3.Use this account(jejiang@hdicore.com) to sign in to Azure
4.Click on Edit Configurations
5.Select Apache Spark on HDInsight template
6.Fill in the blanks of Advanced Configuration

Result:
![02](https://user-images.githubusercontent.com/43333874/68929350-23478f00-07c7-11ea-9485-7fa9e8958482.gif)

**Comment by wezhang** [comment]
Thanks @v-xiaocw !
