### ISSUE TITLE
[Eclipse]Can't create a project for Spark 2.3.0.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3750]
**Azure Toolkit for Java:** https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_develop/1297/Azure/processDownloadRequest/artifacts/WindowsAzurePlugin4EJ.develop.1297.11-18-2019.zip
**Eclipse Version:** 2019-09 R (4.13.0)
**Build id:** 20190917-1200
**OS:** Windows\Mac\Linux

**Repro Step:**

1. Open Eclipse
2. Install the build
3. Navigate to File -> New -> Project
4. Expand HDInsight Project
5. Click on Spark on HDInsight (Scala), and click on Next button
6. Fill in the Project name
7. For Spark SDK, select Spark 2.3.0 (2.11.8), and click on Next button
8. Click on Finish button

**Results:** No response

9. Click on "< Back" button

**Results:** Show an Error dialog.
![image](https://user-images.githubusercontent.com/40199316/69034164-86316400-0a1b-11ea-89bf-d54a4295a0f9.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738900
