### ISSUE TITLE
[Eclipse][Mac]Show an Problem Occurred dialog when create a HDInsight project

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3751]
**Azure Toolkit for Java:** https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_develop/1297/Azure/processDownloadRequest/artifacts/WindowsAzurePlugin4EJ.develop.1297.11-18-2019.zip
**Version:** Oxygen.3a Release (4.7.3a)
**Build id:** 20180405-1200
**OS:** Mac

**Repro Step:**

1. Open Eclipse
2. Install the build
3. Navigate to File -> New -> Project
4. Expand HDInsight Project
5. Click on Spark on HDInsight (Scala), and click on Next button

**Results:** Show an Problem Occurred dialog.
![image](https://user-images.githubusercontent.com/40199316/69034614-a281d080-0a1c-11ea-856f-82a3c016f7f9.png)
**Details:**
The selected wizard could not be started.
Plug-in com.microsoft.azuretools.hdinsight was unable to load class com.microsoft.azuretools.hdinsight.projects.HDInsightsScalaProjectWizard.
An error occurred while automatically activating bundle com.microsoft.azuretools.hdinsight (1071).

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738899
