### ISSUE TITLE
[intelliJ][Linux]The text of Job View shows gray.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3752]
Build:
azure-toolkit-for-intellij-2019.2.develop.1297.11-18-2019.zip

Repro Steps:
1. Open Azure Explorer
2. Expand HDInsight node then select one cluster and expand it.
3. Double click Jobs node.

Result:
The text shows gray.
![image](https://user-images.githubusercontent.com/35950097/69035877-a19e6e00-0a1f-11ea-85b9-0998408721ab.png)

Expectation:
The text should show black.
![image](https://user-images.githubusercontent.com/35950097/69035919-b5e26b00-0a1f-11ea-9c7c-41062873df42.png)

**Comment by wezhang** [comment]
The feature is in deprecating.
