### ISSUE TITLE
[intelliJ][Linux]Suggest to change the text font and remove extra lines

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3753]
Build:
azure-toolkit-for-intellij-2019.2.develop.1297.11-18-2019

Repro Steps:
1. Azure Sign in

Result:
Suggest to change the text font and remove extra lines
![image](https://user-images.githubusercontent.com/35950097/69037071-1672a780-0a22-11ea-9976-793d972c4cf5.png)

![image](https://user-images.githubusercontent.com/35950097/69036328-9b5cc180-0a20-11ea-8835-8b85a6ac6b8e.png)

Expectation:
![image](https://user-images.githubusercontent.com/35950097/69036421-cf37e700-0a20-11ea-850d-8c7814428a1e.png)

2. Right click one hdinsight cluster then select Open Azure Management Portal.

Result:
![image](https://user-images.githubusercontent.com/35950097/69037350-b2041800-0a22-11ea-939b-990d6a7ff6c3.png)

**Comment by lcadzy** [comment]
Not so sure whether it is related with device ,can't repo
