### ISSUE TITLE
[intelliJ]Get error when link cluster.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3754]
Build:
azure-toolkit-for-intellij-2019.2.develop.1297.11-18-2019

Repro Steps:
1. Sign in with jenny's account.
2. Right click HDInsight node then select link cluster.
3. Input the info of zhouyhib then click OK button.

Result:
![image](https://user-images.githubusercontent.com/35950097/69038072-0f4c9900-0a24-11ea-97d6-93ab35568c49.png)

**Comment by lcadzy** [comment]
Not support link esp cluster.
