### ISSUE TITLE
[IntelliJ][ESP][Console]When two commands are executed, only the results of one command are displayed.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3756]
**Build:** https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_develop/1298/Azure/processDownloadRequest/artifacts/azure-toolkit-for-intellij-2019.2.develop.1298.11-18-2019.zip
**IntelliJ Version:** 2019.2
**OS:** Windows

**Repro Steps:**

1. Open IntelliJ IDEA
2. Install the build
3. Use this account(jejiang@hdicore.com) to sign in to Azure
4. Click on Edit Configurations
5. Select Apache Spark on HDInsight template
6. Fill in Main class name
7. Switch to Remotely Run in Cluster
8. For Spark cluster, select zhouyhib
9. For Storage Type, select Use cluster default storage account to upload
10. Navigate to Tools -> Spark console
11. Click on Run Spark Livy Interactive Session Console(Scala)
12. Execute the following two commands:
sc.appName
spark.sessionState
13. Check the results

**Results"** Only the results of one command are displayed.
![image](https://user-images.githubusercontent.com/40199316/69040240-710f0200-0a28-11ea-9240-49c6f5dae70e.png)

**Comment by wezhang** [comment]
The return result depend on backend Livy service session API implementations.
