### ISSUE TITLE
[intelliJ][Linux]The reaction is too slow when choose Spark clusters.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3757]
Build:
azure-toolkit-for-intellij-2019.2.develop.1297.11-18-2019

Repro Steps:
1. Crete a new hdinsight project.
2. Right click LogQuery then locally run it.
3. Right click LogQuery then select remotely run.
Result:
Edit configuration window pops.
4. Choose clusters.
Result:
The reaction is too slow when choose clusters.
![1](https://user-images.githubusercontent.com/35950097/69042501-3f983580-0a2c-11ea-8e77-019ca7574874.gif)

**Comment by wezhang** [comment]
@v-jiche , it this issue still reproduced?

**Comment by v-jiche** [comment]
Build:
azure-toolkit-for-intellij-2019.2.4.develop.1342.01-08-2020

@wezhang  Still repro.

**Comment by v-jiche** [comment]
Do not repro.
