### ISSUE TITLE
[intelliJ][Linux]Unknown error when remotely run hdinsight configuration.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3758]
Build:
azure-toolkit-for-intellij-2019.2.develop.1297.11-18-2019

Repro Steps:
1. Create a HDInsight configuration
2. Choose cluster as zhouyhib, Choose main class name.
3. Remotely run it.

Result:
Get unknown error.
![image](https://user-images.githubusercontent.com/35950097/69043338-d7e2ea00-0a2d-11ea-8c9b-0bf9d8ebe00c.png)

**Comment by lcadzy** [comment]
Can't repo
