### ISSUE TITLE
[intelliJ][windows]Can not Azure sign in.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3759]
Build:
azure-toolkit-for-intellij-2019.2.develop.1297.11-18-2019

Repro Steps:
1. Azure sign in with jenny's account

Result:
It is always waiting.
![image](https://user-images.githubusercontent.com/35950097/69043496-22646680-0a2e-11ea-9835-7ab734538a7f.png)
![image](https://user-images.githubusercontent.com/35950097/69043564-44f67f80-0a2e-11ea-8578-fac7f78d99fb.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738898
