### ISSUE TITLE
[IntelliJ][ESP][Sign in]Azure authentication for switching users scenarios

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3761]
Build:azure-toolkit-for-intellij-2019.2.develop.1298.11-18-2019

Repro Steps:
1.Sign in with jejiang@hdicore.com first
2.Sign out 
3.Then Sign in with omid@hdicore.com
4.Select sign out after successful login

Result:The prompt also shows the account records that were used

![038](https://user-images.githubusercontent.com/43333874/69112430-29858600-0abb-11ea-8c1b-5591ab9d3857.gif)

**Comment by v-xiaocw** [comment]
Here's the result of clearing the cache
![image](https://user-images.githubusercontent.com/43333874/69113632-69575980-0a38-11ea-904d-e5c16c4ad186.png)
![image](https://user-images.githubusercontent.com/43333874/69113650-73795800-0a38-11ea-8e00-7c4660182048.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738897
