### ISSUE TITLE
[IntelliJ][ESP][Console]The result of sparkuser query for local console when sign in account jejiang@hdicore.com is not jejiang

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3762]
Build: azure-toolkit-for-intellij-2019.2.develop.1299.11-19-2019

Repro Steps:
1.Sign in with jejiang@hdicore.com
2.Lanch local console
3.Enter sc.sparkuser
4.Ctrl+Enter

Result:
String=v-xiaocw

![image](https://user-images.githubusercontent.com/43333874/69115375-2055d400-0a3d-11ea-88ea-f1019adda48a.png)

**Comment by wezhang** [comment]
The local console is running as your current desktop login user. It's by-design.
