### ISSUE TITLE
[IntelliJ][RunConfig]The upload path in the config file of Cosmos shows null.

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3765]
Build: azure-toolkit-for-intellij-2019.2.develop.1301.11-19-2019
Repro Steps:
1.Provision a cluster 
2.Create a cosmos config with the cluster 

Result:Upload path shows null and  After the submission is successful, the null is still displayed
![image](https://user-images.githubusercontent.com/43333874/69137020-c66f0180-0a70-11ea-978c-a277fbe7e7d4.png)

**Comment by lcadzy** [comment]
#3768

**Comment by jingyanjingyan** [comment]
Fix in build dev 1322, display with /SparkSubmission/
