### ISSUE TITLE
[IntelliJ][RunConfig]When the storage type selects default, the layout shows too large a blank area.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3770]
**Build:** Market build
**IntelliJ Version:** 2019.2
**OS:** Windows\Mac\Linux

**Repro Steps:**

1. Open IntelliJ
2. Install the build
3. Sign in to Azure
4. Click on Edit Configurations
5. Add a new configuration from list
6. Fill in the Name, Main class
7. Switch to Remotely Run in Cluster
8. Select a cluster
9. For Storage Type, use Default
10. Check the results

**Results:** The layout shows too large a blank area.
![image](https://user-images.githubusercontent.com/40199316/69225552-8d8e7400-0bb9-11ea-893d-d4500e39ce24.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738896
