### ISSUE TITLE
Existing groups don't in alphabetical order.

### ISSUE THREAD

**Issue by EricZhangzf** [microsoft/azure-tools-for-java#3786]
#### Environment:
1. OS: Windows10/Mac
2. Plugin version
   - Azure java toolkit for IntelliJ: 3.30.0
3. IntelliJ: IU19.3-jre11/IC19.2-jre8

#### Repro steps:
1. Right-click a web app and Azure -> Deploy to Azure
2. Create a WebApp
3. Choose Use Existing

#### Result:
The existing groups don't in alphabetical order
![image](https://user-images.githubusercontent.com/44559777/69608363-42b1a800-1062-11ea-82c7-ab3a1a875a13.png)

**Comment by EricZhangzf** [comment]
Fixed
Test in BuildId=10972437

**Comment by EricZhangzf** [comment]
This is issue also reproduce on docker host dialog.
![image](https://user-images.githubusercontent.com/44559777/71348320-43792380-25a7-11ea-8adb-fbb9a7319787.png)
So, reopen it.

**Comment by andxu** [comment]
Only fixed on intellij

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738770

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
