### ISSUE TITLE
[IntelliJ]Link duplicate cluster with space append should get error message

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3801]
Build: https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_develop/1313/Azure/ 

Repro Steps:
1. Link a cluster "aaa" success
2. Link a cluster "aaa     ", click OK

Result:
The link dialog display still, ok button enabled, and no reaction
The same with HDInsight cluster and ESP cluster
![image](https://user-images.githubusercontent.com/36756024/70109573-41e2cc80-1687-11ea-8b6a-a2da83480d16.png)

Expect:
Warning the cluster already exist

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738895
