### ISSUE TITLE
[IntelliJ][ESP]User have to restart config to get the valid path

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3803]
Build: https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_develop/1313/Azure/ 

Repro Steps:
1. Sign in Azure, and link an ESP cluster
2. Create a new HDInsight cluster, choose the linked cluster, input valid Gen2 root path, tab away
3. Notice that it is Invalid Upload Path
![image](https://user-images.githubusercontent.com/36756024/70110505-1e6d5100-168a-11ea-95d9-87326893339f.png)

4. Save config, submit

Result:
Warning invalid root path
![image](https://user-images.githubusercontent.com/36756024/70110514-2c22d680-168a-11ea-9483-d99693de8ee4.png)
Click edit config, notice the root path is available now, the process confuses user.
To proceed a normal submission, user have to reload config file.

Expect:
Make the path valid without reload config file.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738894
