### ISSUE TITLE
[IntelliJ][ESP]Two tips for List HDInsight Custer Error pop-up

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3804]
Build: https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_develop/1313/Azure/processDownloadRequest/artifacts/azure-toolkit-for-intellij-2019.2.develop.1313.12-02-2019.zip
IntelliJ Version: 2019.2
OS: Windows/Mac/Linux

Repro Steps:
1.Open IntelliJ IDEA
2.Install the build
3.Use this account (omid@hdicore.com) to sign in to Azure
4.Right click on HDInsight node, and select Link A Cluster
5.For Clucter Name/URL, enter jeasadhib
6.For Authentication Type, select Azure Account
7.Click OK button in Link A Cluster dialog

Result: Pop up the following error
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/43333874/70114378-263cdf00-1611-11ea-869d-a7b7484670b8.png)

**Tips for the error:**
1.In the absence of cluster, the prompt box can be ejected after clicking HDInsight node for a refresh 
**The prompts include checking the sign in status, selecting subscriptions, or linking cluster**
2.**The prompt box should not pop up after the HDInsight node automatically refreshed or manually refreshed after it has been successful**

**Comment by v-xiaocw** [comment]
@wezhang When a linked cluster already exists, refreshing HDInsight node again will also have that prompt pop-up

**Comment by wezhang** [comment]
@v-xiaocw , if you refresh from menu, the prompt pop-up is by design.
