### ISSUE TITLE
[IntelliJ][2019.3 EAP][console]Show two 'scala>' when run Spark Local Console

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3806]
**IntelliJ build version:** 2019.3 EAP IC-193.4778.7
**OS:** Mac/Win/Linux
**JDK:** JetBrains s.r.o 11.0.4
**Plugin version:** https://dev.azure.com/mseng/_apis/resources/Containers/11319627?itemPath=drop%2Fazure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.11021963.12-04-2019.zip

**Repro Steps:**

1. Open IntelliJ and install the plugin
2. Run Spark Local Console
3. Enter 'sc.appName'
4. Check the results

**Actual:** Show two **'scala>'**
![image](https://user-images.githubusercontent.com/40199316/70132708-b20d4480-16bf-11ea-9e65-8ba6604caac3.png)

**Comment by t-rufang** [comment]
Fixed in #3842

**Comment by v-lanjli** [comment]
Verified and fixed, closed this issue.
