### ISSUE TITLE
[IntelliJ][Console]Local console without config will pops dialog ask for main class

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3807]
Build: azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.11021963.12-04-2019.zip

Repro Steps:
1. Create a maven or sbt product, do not create any config file
2. Select one default spark type
3. Local console

Result:
Pops dialog ask for main class
![image](https://user-images.githubusercontent.com/36756024/70213821-438abe00-1775-11ea-8095-a708263c0209.png)

Expect:
Local console should not related to main class.

**Note:
If user create a config without main class, the local console could be launched success.**

**Comment by wezhang** [comment]
Is it still repro?

**Comment by jingyanjingyan** [comment]
The issue still repro with build azure-toolkit-for-intellij-2019.3.develop.12471931.06-29-2020.zip

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738893
