### ISSUE TITLE
[IntelliJ][2019.3 EAP][console]Launch local console error after manually creating config file When build tool is SBT.

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3808]
IntelliJ build version: 2019.3 EAP IC-193.4778.7
OS: Mac/Win/Linux
JDK: JetBrains s.r.o 11.0.4
Plugin version: https://dev.azure.com/mseng/_apis/resources/Containers/11319627?itemPath=drop%2Fazure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.11021963.12-04-2019.zip

Repro Steps:
1.Open IntelliJ and install the plugin
2.Create any type of configuration  file 
3.Click Tools>Spark Console>Run Spark Local Console

Result:The following error prompt struck up
![image](https://user-images.githubusercontent.com/43333874/70215029-725f5080-16f1-11ea-8cda-18702aed6722.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738892
