### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Exception in early startup java.lang.Throwable: Control-flow exceptions (like ProcessCanceledException) should never be logged

### ISSUE THREAD

**Issue by fsousa310** [microsoft/azure-tools-for-java#3811]
IntelliJ build version: 2019.3 IC-193.5233.102
OS: Windows 10
JDK: JetBrains s.r.o 11.0.4
Plugin version: 3.30.0-2019.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1050,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Exception in early startup, throwable=java.lang.Throwable: Control-flow exceptions (like ProcessCanceledException) should never be logged
	at com.intellij.openapi.diagnostic.Logger.checkException(Logger.java:196)
	at com.microsoft.intellij.AzurePlugin.initComponent(AzurePlugin.java:162)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.microsoft.intellij.AzurePlugin.loadWebappsSettings(AzurePlugin.java:301)
	at com.microsoft.intellij.AzurePlugin.initComponent(AzurePlugin.java:158)
```

**Comment by wezhang** [comment]
Thanks @fsousa310 ! @Flanker32 , could you help look at it?

**Comment by Flanker32** [comment]
@fsousa310 Thanks for your report, and could you please provide a bit more information about this issue? Like when did this issue occurs and is there any way to reproduce it?

**Comment by fsousa310** [comment]
This problem occurred when starting IntelliJ. I have no evidence of when it occurs.

**Comment by andxu** [comment]
Dup as https://github.com/microsoft/azure-tools-for-java/issues/4230

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: Control-flow exceptions (like ProcessCanceledException) should never be logged
