### ISSUE TITLE
[intelliJ][ESP][omid account]It has no reaction when select sparkJobRun node.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3815]
Build:
azure-toolkit-for-intellij-2019.2.4.develop.11056471.12-09-2019

Repro Steps:
1. Create a new project.
2. Right  click LogQuery then select locally run, wait until it run successfully.
3. Right click LogQuery then select Spark Job run node.

Result:
It has no reaction sometimes.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738891
