### ISSUE TITLE
[intelliJ][omid account][ESP]Unreasonable warning when submit job in sign-out state.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3816]
Build:
azure-toolkit-for-intellij-2019.2.4.develop.11056471.12-09-2019

Repro Steps:
1. Sign out with omid account.
2. Create an HDInsight configuration, input main class, spark cluster(linked cluster), gen 2 root path.
3. Click remotely run icon,
Result:
Change Configuration Settings window pops.
![image](https://user-images.githubusercontent.com/35950097/70419418-59172500-1aa0-11ea-9fb7-5087f629fcf2.png)
4. Click continue anyway button.
Result:
Get error message. The gen2 root path has been selected.
![image](https://user-images.githubusercontent.com/35950097/70419503-895ec380-1aa0-11ea-815f-bce2e673f8fd.png)
5. Right click LogQuery then select remotely run or submit Spark Application.
Result:
![image](https://user-images.githubusercontent.com/35950097/70419503-895ec380-1aa0-11ea-815f-bce2e673f8fd.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738890
