### ISSUE TITLE
[IntelliJ][ESP]The prompt under the spark cluster selection box shows incomplete

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3817]
Build: ideaIC-bundle-win-x64-2019.2.4.develop.1316.12-09-2019
IntelliJ Version: 2019.2
OS: Windows/Mac/Linux
Repro Steps:
1.Open IntelliJ IDEA
2.Install the build
3.Use this account (omid@hdicore.com) to sign in to Azure
4.Right click on HDInsight node, and select Link A Cluster
5.For Clucter Name/URL, enter jeasadhib
6.For Authentication Type, select Azure Account
7.Click OK button in Link A Cluster dialog
8.Sign out with omid account.
9.Create a HDInsight configuration

Result:The prompt is not full
![image](https://user-images.githubusercontent.com/43333874/70421908-9d161580-1a1f-11ea-8fc8-b8c79bfcc2a1.png)

**Comment by t-rufang** [comment]
@v-xiaocw I suppose if you drag the dialog horizontally first, you can find the missing words.

**Comment by jingyanjingyan** [comment]
Resize dialog, the warning message display well, in build dev 1322.
