### ISSUE TITLE
[IntelliJ][ESP]Show hints that can't be listed when you can show a list of clusters

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3818]
Build: ideaIC-bundle-win-x64-2019.2.4.develop.1316.12-09-2019
IntelliJ Version: 2019.2
OS: Windows/Mac/Linux
Repro Steps:
1.Open IntelliJ IDEA
2.Install the build
3.Use this account (omid@hdicore.com) to sign in to Azure
4.Right click on HDInsight node, and select Link A Cluster
5.For Clucter Name/URL, enter jeasadhib
6.For Authentication Type, select Azure Account
7.Click OK button in Link A Cluster dialog
8.Sign out with omid account.
9.Create a HDInsight configuration
10.Click the Spark Cluster  drop-down menu

Result:Still show tips that can't be listed
![1209001](https://user-images.githubusercontent.com/43333874/70422774-3e947a00-1aa7-11ea-8c5d-c0816f4a34f8.gif)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738889
