### ISSUE TITLE
[intelliJ][Synapse]Need to update the error message when remotely run with empty Spark Pools.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3819]
Build:
azure-toolkit-for-intellij-2019.2.4.develop.11056471.12-09-2019

Repro Steps:
1. Create a synapse configuration. Do not choose Spark Pools. Choose Main class name.
Result:
Suggest to change "cluster name" to "Spark pools".
![image](https://user-images.githubusercontent.com/35950097/70425808-d2b51000-1aac-11ea-813f-7fe2e24af6ef.png)
2. Click remotely run icon.
Result:
Change Configuration Settings window pops. Suggest to change "Spark Compute" to "Spark pools".
![image](https://user-images.githubusercontent.com/35950097/70425738-b022f700-1aac-11ea-82fd-71ed6bb05fba.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738888
