### ISSUE TITLE
[intelliJ][ESP][Synapse]There is no result when click Spark Job Details UI.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3820]
Build:
azure-toolkit-for-intellij-2019.2.4.develop.11056471.12-09-2019

Repro Steps:
1. Create a Spark on Synapse configuration.
2. Remotely run it.
3. Click Spark Job Details UI link.

Result:
There is no result.
![image](https://user-images.githubusercontent.com/35950097/70428362-6be62580-1ab1-11ea-878c-47bd67e22510.png)

**Comment by t-rufang** [comment]
This is a bug from Azure Synapse Studio. Find the work item at https://msdata.visualstudio.com/A365/_workitems/edit/560249
