### ISSUE TITLE
[IntelliJ][EAP][Remotely Run]Remotely run on arcadia failed 

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3828]
Build:azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.11021963.12-04-2019
Repro Steps:
1.Create a new project
2.Create an arcadia configuration
3. Fill in all the information you need 
4.Click Apply and OK
5.Click remotely run button
Result:
![image](https://user-images.githubusercontent.com/43333874/70499949-27698280-1acf-11ea-93f2-488dd425d170.png)

**Comment by t-rufang** [comment]
@v-xiaocw this issue should have been fixed in the latest develop build. Please help verify.

**Comment by v-xiaocw** [comment]
Verified and fixed in market build
