### ISSUE TITLE
Do we really need to put the .idea and .gradle folder in the repo?

### ISSUE THREAD

**Issue by jdneo** [Microsoft/azure-tools-for-java#383]
Some of these local setting files can be put into .gitignore I guess.

For example:
[Gradle.gitignore](https://github.com/github/gitignore/blob/master/Gradle.gitignore)
[JetBrains.gitignore](https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore)

**Comment by wezhang** [comment]
JetBrains.gitignore has already been in

**Comment by jdneo** [comment]
@wezhang Yes, I forgot to close this issue.
