### ISSUE TITLE
[Eclipse]It has no reaction when click Finish button.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3843]
Build:
WindowsAzurePlugin4EJ.develop.11088651.12-13-2019

Repro Steps:
1. Create a new Project.

Result:
It has no reaction when click finish button.
![f](https://user-images.githubusercontent.com/35950097/70797204-fd6dd400-1dde-11ea-9b17-07f10981ed3e.gif)

**Comment by t-rufang** [comment]
Duplicate with #3750
