### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by gwdsss** [microsoft/azure-tools-for-java#3849]
IntelliJ build version: 2018.3.4 IU-183.5429.30
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.23.0-2018.3

#### 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).
9
#### 2. What did you like or dislike about Azure Toolkit for IntelliJ?
I'm using it
#### 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?
I'm using it

**Comment by wezhang** [comment]
Thanks @gwdsss ! Any feedbacks are welcome!

**Comment by andxu** [comment]
Close since no further actions are needed
