### ISSUE TITLE
[IntelliJ][Run Config]The upload path is not in the correct format.

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3856]
Build: azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.11021963.12-04-2019.zip
or  ideaIC-bundle-win-x64-2019.2.4.develop.1328.12-13-2019

Repro Steps:
1.Create a new project
2.Create a HDInsight configuration 
3.Select a cluster and select the default storage account to upload
4.Click Apply and then upload path automatically loaded successfully

Result:
![image](https://user-images.githubusercontent.com/43333874/70983204-2c997500-206d-11ea-9f4a-c5447bb74a08.png)
Expectation Result:
![image](https://user-images.githubusercontent.com/43333874/70983992-88b0c900-206e-11ea-9ced-aead710fd6f6.png)

**Comment by t-rufang** [comment]
Fixed in #3857

**Comment by v-xiaocw** [comment]
Verified and fixed
