### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading Web Apps

### ISSUE THREAD

**Issue by LeftistTachyon** [microsoft/azure-tools-for-java#3859]
IntelliJ build version: 2019.3 IC-193.5233.102
OS: Windows 10
JDK: JetBrains s.r.o 11.0.4
Plugin version: 3.30.0-2019.3
Error message: 
```
java.lang.RuntimeException: com.microsoft.azuretools.adauth.AuthException: AD Auth token endpoint returned HTTP status code 400. Error info: {"error":"invalid_request","error_description":"AADSTS90002: Tenant 'null' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.\r\nTrace ID: d8805fc0-6784-460a-9120-ddad54241900\r\nCorrelation ID: 15700d65-64ca-48f3-9979-f70cc2a2fc5b\r\nTimestamp: 2019-12-18 04:22:05Z","error_codes":[90002],"timestamp":"2019-12-18 04:22:05Z","trace_id":"d8805fc0-6784-460a-9120-ddad54241900","correlation_id":"15700d65-64ca-48f3-9979-f70cc2a2fc5b","error_uri":"https://login.microsoftonline.com/error?code=90002"}
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.list(WebAppsInner.java:1847)
	at com.microsoft.azure.m
```
Happens when I try to get a listing of my Azure Web Apps without first going through the Microsoft login to ensure that IntelliJ has access to my Microsoft account. I don't think it should do that; instead, I should be asked to log in or something like that to ensure that the actions that I would execute would be verified under my account.

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  MS Services - Error Getting Subscriptions (#2226)

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  MS Azure Explorer - Error Loading Web Apps (#3653)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: Tenant 'null' not found. This may happen if there are no active subscriptions for the tenant.
