### ISSUE TITLE
[IntelliJ][193]The results of only one command are displayed when multiple commands of interactive console are executed simultaneously

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3861]
Build: azure-toolkit-for-intellij-2019.3.develop.11114708.12-17-2019
IntelliJ IDEA 2019.3 (Community Edition)
Build #IC-193.5233.57, built on November 20, 2019
Runtime version: 11.0.4+10-b520.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2008M
Cores: 4
Registry:
Non-Bundled Plugins: org.intellij.scala, com.microsoft.tooling.msservices.intellij.azure
Repro Steps:
1.Create a new project
2.Craate a new HDInsight config
3.Click Tools->Spark Console->Run Spark Livy Interactive console
4.Enter four commands
5.Check the result
Result:Show only one result
![image](https://user-images.githubusercontent.com/43333874/71077099-a5670280-213b-11ea-8270-5a4ef07c5f04.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738885
