### ISSUE TITLE
[IntelliJ][EAP][Mac][Console] From the second line, the input is not visible in IntelliJ 193

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3867]
**IntelliJ build version:**
IntelliJ IDEA 2019.3 (Community Edition)
Build #IC-193.5233.102, built on November 28, 2019
Runtime version: 11.0.4+10-b520.11 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 4
Registry:
Non-Bundled Plugins: org.intellij.scala, com.microsoft.tooling.msservices.intellij.azure, org.jetbrains.plugins.hocon
**OS:** Mac
**JDK:** JetBrains s.r.o 11.0.5
**Plugin version:** https://dev.azure.com/mseng/_apis/resources/Containers/11500112?itemPath=drop%2Fazure-toolkit-for-intellij-2019.3.develop.11114708.12-17-2019.zip
**Repro Steps:**

1. Edit Configuration
2. Tools->Spark Console->Livy Console/Local Console
3. Type the command in the console and press Enter to continue typing
4. Check the results

**Current results:** From the second line, the input is not visible.

![IntelliJ EAP Mac Console  From the second line, the input is not visible](https://user-images.githubusercontent.com/40199316/71157392-df8bed80-227c-11ea-8b85-e06ca2ff86cf.gif)

**Comment by wezhang** [comment]
It's a scala plugin behavior.
