### ISSUE TITLE
[IntelliJ][193]Run remotely without remote settings in configurations, no popup window to change configuration settings.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3871]
**IntelliJ build version:**
IntelliJ IDEA 2019.3.1 (Community Edition) / IntelliJ IDEA 2019.3
Build #IC-193.5662.53, built on December 18, 2019
Registry:
Non-Bundled Plugins: org.intellij.scala, com.microsoft.tooling.msservices.intellij.azure
**OS:** Windows/Mac/Linux
**Plugin version:** https://dev.azure.com/mseng/_apis/resources/Containers/11500112?itemPath=drop%2Fazure-toolkit-for-intellij-2019.3.develop.11114708.12-17-2019.zip

**Repro Steps:**

1. Install the IntelliJ193/193.1
2. Install the above plugin
3. Create a new project
4. Just fill in the Main class name, do not make any settings in Remotely Run in Cluster
5. Click Apply and OK button to save and close the config dialog
6. Click on SparkJobRun button
7. Check the results

**Current results:** Just show Error running, and no popup window to change configuration settings.
![IntelliJ EAP Run remotely without remote settings in configurations, no popup window to change configuration settings](https://user-images.githubusercontent.com/40199316/71232268-3f8d9d00-232c-11ea-9747-80ba14a5e6a9.jpg)

**Comment by wezhang** [comment]
@v-lanjli , is it only reproduced at 193?

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738884
