### ISSUE TITLE
[IntelliJ]Cannot be restarted automatically after build is installed

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3880]
Build: azure-toolkit-for-intellij-2019.3
IntelliJ IDEA 2019.3.1 (Community Edition)
Build #IC-193.5662.53, built on December 17, 2019
Runtime version: 11.0.5+10-b520.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2008M
Cores: 4
Registry: 
Non-Bundled Plugins: org.intellij.scala, com.microsoft.tooling.msservices.intellij.azure

Repro Steps:
1.Start intellij
2.Click Files->Settings->Plugins->Setting->Install Plugin from disk
3.Select  the build that has been download
4.Click 'OK' and Apply

Result: There is no automatic restart and a dialog box is popping up asking if to restart
![1223001](https://user-images.githubusercontent.com/43333874/71335585-4ff27300-24f8-11ea-98eb-492c3edd76c9.gif)

Expectation:The following dialog box pops up automatically after clicking ok
![image](https://user-images.githubusercontent.com/43333874/71335614-6d274180-24f8-11ea-86e4-7dcdee712b0e.png)
ctation:

**Comment by t-rufang** [comment]
@v-xiaocw You should uninstall the plugin if it already exists and then install the plugin from disk

**Comment by andxu** [comment]
Hi @v-xiaocw, can you solve this issue by uninstalling the plugin first? This installation experience is determined by Intellij, not by us, am I right?
