### ISSUE TITLE
Wrong notification message when click 'get publish profile'

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-tools-for-java#3883]
This is a compatibility issue.
This issue only occur in eclipse 2019-12, when installing new software in eclipse 2019-09, this issue not happen.

### Environment:

- OS: Windows10/Mac
- Azure java toolkit for Eclipse: 3.20.0
- Eclipse: 2019-12
- JDK: oracle jdk8

### Repro steps:

1. Right-click a web app and choose Show Properties
2. Click on Get Publish Profile button
3. Choose where you want to save the profile

### Result:
![image](https://user-images.githubusercontent.com/41051257/71349924-1595de00-25ab-11ea-8fba-c1484659586a.png)

However, Publish profile saved in the local system
![image](https://user-images.githubusercontent.com/41051257/71350108-83420a00-25ab-11ea-8975-00949592bfb1.png)

### Expect:
![image](https://user-images.githubusercontent.com/41051257/71350419-40ccfd00-25ac-11ea-9ec4-0adaadab5d2f.png)

**Comment by Flanker32** [comment]
Unable to reproduce it in test machine, this may related with Mac OS, will revisit this issue later.

**Comment by ZhengJun003** [comment]
Can't reproduce in azure toolkits for eclipse 3.23.0 on mac
