### ISSUE TITLE
[IntelliJ][Spark on Synapse]Synapse workspace cannot be listed.

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3884]
**Build:** Market Build (192/193)
**OS**: Mac/Windows/Linux

**Repro Steps:**

1.Install build
2.Sign in with Azure account 
3.Select aII subscriptions
4.Refresh the **Apache Spark on Synapse** node

**Result:** Can not list synapse workspace, but when only **Apache Spark on Synapse** is selected, the workspace list is displayed.

**Comment by t-rufang** [comment]
Checked log, we find there are exceptions when list workspaces. We have fixed this in #3857. Currently workaround to mitigate this issue is to select only subscriptions that contains Synapse workspaces.

**Comment by v-xiaocw** [comment]
Verified  and  fixed
