### ISSUE TITLE
Cannot generate new Authentication file

### ISSUE THREAD

**Issue by Elvira-sxr** [microsoft/azure-tools-for-java#3890]
## Environment:
OS: Windows10/Mac
Azure java toolkit for Eclipse: 3.21.0
Eclipse: 2019-12
JDK: oracle jdk8/11

## Repro steps:
1.Right click on Azure Explorer and select sign in
2.Select Service Principal and click new
3.Azure device login
## Result:
Cannot generate new Authentication file
![image](https://user-images.githubusercontent.com/51812626/71653852-8ab2a180-2d69-11ea-9ecd-29f2ae19f0cf.png)

**Comment by pl07** [comment]
Environment:
1. OS: Windows10/Mac
2. Plugin version
         Azure java toolkit for IntelliJ: 3.31.0
3. IntelliJ: IU19.2-jre11/IC19.2-jre8

The same problem occurs on IntelliJ.

**Comment by jingyanjingyan** [comment]
With build dev 1340 19.2&19.2bundle, windows
Sign in with new Authentication file will general 2 files, they include different subscriptions.

**Comment by ZhengJun003** [comment]
Test pass in azure java toolkit for eclipse 3.23.0.
