### ISSUE TITLE
In ACR Explorer, there are problems with inconsistent fonts and word sizes

### ISSUE THREAD

**Issue by Elvira-sxr** [microsoft/azure-tools-for-java#3891]
## Environment:
OS: Windows10
Azure java toolkit for Eclipse: 3.21.0
Eclipse: 2019-12
JDK: oracle jdk8

## Repro steps:
Right click  on the registry to open ACR Explorer 

## Actual:
![image](https://user-images.githubusercontent.com/51812626/71659792-cf4b3680-2d83-11ea-91ff-3f2e516f615d.png)

## Expected :

![image](https://user-images.githubusercontent.com/51812626/71659809-e853e780-2d83-11ea-8eff-a1f387b3f612.png)

**Comment by ZhengJun003** [comment]
Test pass in azure toolkits for eclipse 3.23.0

![image](https://user-images.githubusercontent.com/41051257/83708698-77c13780-a64f-11ea-995a-10a25dac807d.png)
