### ISSUE TITLE
[IntelliJ]VFS of synapse not works

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3899]
Build: ideaIC-bundle-win-x64-2019.2.4.develop.1338.01-03-2020.zip

Repro Steps:
1. Create a synapse config, choose one workspace that has permission
2. Click the VFS button

Result:
![image](https://user-images.githubusercontent.com/36756024/71717918-9f1f9880-2e54-11ea-84d2-b5e33ab17412.png)

**Comment by jingyanjingyan** [comment]
with 19.2 build azure-toolkit-for-intellij-2019.2.4.develop.11290224.01-13-2020.zip
Select a workspace with permission, click VFS always pops dialog below.
![image](https://user-images.githubusercontent.com/36756024/72245638-f5968f00-362b-11ea-854f-021b7844d4ce.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738881
