### ISSUE TITLE
Create Hello Worls web app documentation is out of date - the login step is different

### ISSUE THREAD

**Issue by clguimanMSFT** [Microsoft/azure-tools-for-java#39]
https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-intellij-create-hello-world-web-app
Step 1 for publishing azure web app is not correct. If you just follow the instructions that menu option will be grayed out because the user first has to login and not as the docs say to login afterwards.

**Comment by martinsawicki** [comment]
doc update
