### ISSUE TITLE
[IntelliJ][193]Shown the Prepare Azure Virtual File System Error when select the Gen 2 cluster.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3909]
**Build Version:** https://dev.azure.com/mseng/_apis/resources/Containers/11609883?itemPath=drop%2Fazure-toolkit-for-intellij-2019.3.develop.11178477.12-26-2019.zip
**IntelliJ Version:** IntelliJ IDEA 2019.3 (Community Edition)

**Repro Steps:**

1. Open IntelliJ and create a project
2. Click Edit Configuration, and add a new configuration e.g Apache Spark on HIDnsight
3. For Spark clusters, select a Gen2 cluster e.g spark242-gen2-lanjun
4. Click on Browse icon with Referenced Jars and Referenced Files

**Results:** Shown Prepare Azure Virtual File System Error. But, the cluster has been confirmed to be of Gen 2 type.
![image](https://user-images.githubusercontent.com/40199316/71947384-a1447700-3207-11ea-8cd4-afa9b85eb6a9.png)

**Comment by t-rufang** [comment]
Please test IntelliJ 193 when the build is ready in release week

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738880
