### ISSUE TITLE
[IntelliJ][Mac][193]Cannot display linked clusters in Run/Debug Configuration (Tools->Spark Console->Run Spark Livy Interactive Session Console).

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3910]
**IntelliJ Version**: 193
**Build Version** Market version
**OS**: Mac

**Repro Steps**:

1. Open IntelliJ an d install the market build
2. Link a cluster
3. Open Run/Debug Configuration dialog from Tools->Spark Console->Run Spark Livy Interactive Session Console
4. Expand the spark cluster list

**Results**: Cannot display linked clusters.
![IntelliJ Mac 193 Cannot display linked clusters in RunDebug Configuration ](https://user-images.githubusercontent.com/40199316/72048509-e516a980-32f7-11ea-9e56-9ec754076520.gif)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738879
