### ISSUE TITLE
[Synapse][VFS]Add colon in the warning message when no such host

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3918]
Build: azure-toolkit-for-intellij-2019.2.4.develop.11290224.01-13-2020.zip

Repro Steps:
1. Create a synapse config
2. Choose one workspace that the related gen2 storage has been deleted
3. Click the VFS icon

Result:
Should add one colon in the warning message
![image](https://user-images.githubusercontent.com/36756024/72237535-c83ee680-3615-11ea-8564-07272f7d303c.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738878
