### ISSUE TITLE
[IntelliJ][VFS]VFS not works with authentication file

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3919]
Build: azure-toolkit-for-intellij-2019.2.4.develop.11290224.01-13-2020.zip

Repro Steps:
1. Sign in with authentication file
2. Create a synapse config
3. Select a workspace with permission, click VFS

Result:
It always pops dialog below
![image](https://user-images.githubusercontent.com/36756024/72245638-f5968f00-362b-11ea-854f-021b7844d4ce.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738877
