### ISSUE TITLE
[IntelliJ][VFS]Consider update the gen2 cluster to gen2 storage account

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3920]
Build: azure-toolkit-for-intellij-2019.2.4.develop.11290224.01-13-2020.zip

Repro Steps:
1. Create a synapse config
2. In the job upload storage section, select "Use Azure Blog to upload"
3. Click the VFS icon

Result:
Warning says we only support gen2 cluster
![image](https://user-images.githubusercontent.com/36756024/72247443-d7cb2900-362f-11ea-9602-1d6309e16e48.png)

Expect:
Synapse feature should not includes cluster concept, and the warning is triggered by the selection of the upload storage type?

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738876
