### ISSUE TITLE
[Intellij.2017.Storage.ActionIcon] The action icon in storage explorer looks strange

### ISSUE THREAD

**Issue by jdneo** [microsoft/azure-tools-for-java#393]
Platform: windows10, intellij 2017

![image](https://cloud.githubusercontent.com/assets/6193897/25886183/0afca91a-358f-11e7-9fcb-5a25a10f7d9c.png)

**Comment by jdneo** [comment]
Also the search button looks like a audio player

**Comment by Flanker32** [comment]
Storage explorer has been deprecated and removed from toolkit, so close this issue
