### ISSUE TITLE
[IntelliJ][ESP]VFS of ESP not works

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3930]
**Build:** https://dev.azure.com/mseng/_apis/resources/Containers/11855838?itemPath=drop%2Fazure-toolkit-for-intellij-2019.2.4.develop.11299072.01-14-2020.zip

**Repro Steps:**

1. Open IntelliJ and Install the build
2. Sign in with jejiang's (jejiang@hdicore.com) account
3. Open Cinfiguration, and click the VFS button
4. Check the results

Result:
![image](https://user-images.githubusercontent.com/40199316/72408608-4e863480-379e-11ea-90fa-00a4e0fa738c.png)

**Comment by t-rufang** [comment]
Fixed in #3941

**Comment by v-lanjli** [comment]
Verified and fixed in this build(https://dev.azure.com/mseng/VSJava/_build/results?buildId=11321005)
Closed this issue.
