### ISSUE TITLE
[IntelliJ][ESP]Linked cluster has been displayed, but the list HDInsight cluster error dialog will pop up after refreshing the HDInsight node.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3932]
**Build:** https://dev.azure.com/mseng/_apis/resources/Containers/11855838?itemPath=drop%2Fazure-toolkit-for-intellij-2019.2.4.develop.11299072.01-14-2020.zip

**Repro Steps:**

1. Open IntelliJ and Install the build
2. Sign in with omid (omid@hdicore.com) account
3. Right click on HDInsight node, and select Link a cluster
4. Refresh HDInsight node after link cluster
5. Check the results

**Results:** Show list HDInsight cluster error dialog.
![image](https://user-images.githubusercontent.com/40199316/72412457-56e36d00-37a8-11ea-9e27-a22c84280816.png)

**Comment by wezhang** [comment]
@v-lanjli , could you help repro it?

**Comment by v-lanjli** [comment]
This issue appears on this build(https://dev.azure.com/mseng/VSJava/_build/results?buildId=11299072), but no longer reproduced on this build(https://dev.azure.com/mseng/VSJava/_build/results?buildId=11321032)
Closed this issue~
