### ISSUE TITLE
[IntelliJ][ESP]Warning says link cluster use ambari credentials might need update

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3933]
Build: azure-toolkit-for-intellij-2019.2.4.develop.11290224.01-13-2020.zip

Repro Steps:
1, Sign in with omid account, link cluster
2. Expand cluster, click "Storage Account"

Result:
Warning says link cluster with ambari credentials, but we link esp cluster with cluster name only.
![image](https://user-images.githubusercontent.com/36756024/72413707-5698a100-37ab-11ea-926f-9491f0b4a86b.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738873
