### ISSUE TITLE
[Intellij.2017.Storage.CodingIssue]Text coding Issue

### ISSUE THREAD

**Issue by jdneo** [microsoft/azure-tools-for-java#394]
Platform: Windows 10, intellij 2017

Text coding issue in Last Modified field

![image](https://cloud.githubusercontent.com/assets/6193897/25886293/820d095a-358f-11e7-93db-84cf1f592e04.png)

**Comment by Flanker32** [comment]
Storage explorer has been removed in latest release so close this issue
