### ISSUE TITLE
[IntelliJ][Synapse][Config]Sign with authentication file, failed to list Spark pool in configuration

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3948]
**Build:** https://dev.azure.com/mseng/VSJava/_build/results?buildId=11321005

**Repro Steps:**

1. Sign with authentication file
2. Create a synapse config
3. Expand Spark pool list
4. Check the results

**Result:**
Cannot be list spark pool.
![image](https://user-images.githubusercontent.com/40199316/72606266-3c9cc100-3959-11ea-80da-b7b98c1a9734.png)

**Comment by wezhang** [comment]
Is it still repro?

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738872
