### ISSUE TITLE
[IntelliJ][193][Mac/Linux] Button is truncated in Unlink HDInsight Cluster dialog.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3953]
**Build:** https://dev.azure.com/mseng/VSJava/_build/results?buildId=11333335
**IntelliJ Version:** 193
**OS:** Mac/Linux

**Repro Steps:**

1. Unlink a cluster
2. Check the Unlink HDInsight Cluster dialog

**Result:**
Button is truncated.
![image](https://user-images.githubusercontent.com/40199316/72677053-100cb480-3ad3-11ea-8f2c-375680da0ce4.png)

**Comment by v-lanjli** [comment]
Add Azure sign out dialog.
![image](https://user-images.githubusercontent.com/40199316/72677082-71cd1e80-3ad3-11ea-9caf-ddcc7d002620.png)

**Comment by wezhang** [comment]
@v-lanjli , is it still repro?

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738871
