### ISSUE TITLE
The status is displayed incorrectly during shut down a docker host.[All os][IntelliJ2016/IntelliJ2017/Eclipse]

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#396]
Right click a docker host in azure list.
Select Shutdown.
**EXPEXT:**
All other states should grayed and not available when shutting down
**RESULT:**
![image](https://cloud.githubusercontent.com/assets/22470312/25886592/dcb87ea6-3590-11e7-849c-f0d354a793a6.png)
![image](https://cloud.githubusercontent.com/assets/22470312/25886596/e1341de6-3590-11e7-9846-2fd845389f07.png)

**Comment by bsaby** [comment]
The status of  Web App and Virtual Machine are displayed incorrectly.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738811

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
