### ISSUE TITLE
[IntelliJ][SOCsynapse]Fail to start livy interactive session

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3974]
Build: azure-toolkit-for-intellij-2019.2.4.develop.11464009.02-07-2020.zip IntelliJ19.2

Repro Steps:
1. Create a new synapse config, choose the SOC workspace, apply
2. Start livy interactive session

Result:
Fails

```
Start Spark Livy Interactive Session Console in cluster rufanws0204.dev.azuresynapse-dogfood.net...
Can't start Livy interactive session: com.microsoft.azure.hdinsight.sdk.common.livy.interactive.exceptions.SessionNotStartException: Session SOCsynapse >> Synapse Spark Livy Interactive Session Console(Scala) is ERROR. 
```

**Comment by jingyanjingyan** [comment]
livy interactive console fails in build azure-toolkit-for-intellij-2019.2.4.develop.11507847.02-14-2020

**Comment by t-rufang** [comment]
This is a backend issue and we have internal email thread to track this issue.
