### ISSUE TITLE
[IntelliJ][ESP]Livy interactive console fails

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3985]
Build: Both bundle and only, on windows.
ideaIC-bundle-win-x64-2019.2.4.develop.11507847.02-14-2020

Repro Steps:
1. Signin omid account
2. Link a ESPHIB cluster, create a config with the ESPHIB cluster
3. Start livy interactive console

Result:
Fails
Start Spark Livy Interactive Session Console in cluster zhwe01hib.azurehdinsight.net...
Can't start Livy interactive session: {"Code":"ServiceUnavailable","Message":"Error while authenticating the request. Please try again after some time.","CorrelationId":"97320d5910644d639d7f10f840811b66","ResponseTimestamp":"2020-02-14T07:20:19.8052113Z"}

**Comment by wezhang** [comment]
May dup #3965
