### ISSUE TITLE
Unable to close "Publish as Docker Container" by clicking Cancel or Finish

### ISSUE THREAD

**Issue by akaroml** [Microsoft/azure-tools-for-java#399]
Steps:
1. Right click on a project
2. In the context menu, click Azure -> Publish As Docker Container...
3. Wait till the dialog is shown
4. Try to click Cancel or Finish
Now you see the Dialog persists without disappearing.

Expected:
The dialog should be gone when clicking Cancel or Finish.

Workaround:
Clicking the close button on window caption bar.

**Comment by adashen** [comment]
@bsaby Please help to verify this use the new build:
http://vscjavaci.cloudapp.net/job/AzureToolsManager_hotfix/1/Azure/

**Comment by bsaby** [comment]
Test passed.
Build used: http://vscjavaci.cloudapp.net/job/AzureToolsManager_hotfix/1/Azure/
