### ISSUE TITLE
[IntelliJ][VFS]Submit fails when the reference jar file includes space

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3999]
Build: azure-toolkit-for-intellij-2019.2.4.develop.11509042.02-14-2020

Repro Steps:
1. Submit HDInsight config with VFS reference jar file : abfs://spark24-gen2-yan5-2020-02-18t08-19-36-892z@catestgen2jw.dfs.core.windows.net/tmp/Refer%20Project.jar

Result:
Package and deploy the job to Spark cluster
INFO: Spark Batch submission Response: status [201], content [Created], headers [Content-Type: application/json;charset=utf-8; Location: /batches/13; request-id: deeccf618c844a6cb9852db458f1af66; x-ms-hdi-active: hn0-spark2.5s4jh3n4ixsergrpcwsxwrrthc.mx.internal.cloudapp.net; x-ms-hdi-http-host: hn0-spark2.5s4jh3n4ixsergrpcwsxwrrthc.mx.internal.cloudapp.net:8998; Strict-Transport-Security: max-age=31536000; includeSubDomains; Date: Wed, 19 Feb 2020 07:06:05 GMT; Content-Length: 146], body [{"id":13,"state":"starting","appId":null,"appInfo":{"driverLogUrl":null,"sparkUiUrl":null},"log":["stdout: ","\nstderr: ","\nYARN Diagnostics: "]}]
LOG: Warning: Master yarn-cluster is deprecated since 2.0. Please use master "yarn" with specified deploy mode instead.
LOG: 20/02/19 07:06:11 WARN DependencyUtils: Skip remote jar abfs://spark24-gen2-yan5-2020-02-18t08-19-36-892z@catestgen2jw.dfs.core.windows.net/SparkSubmission/2020/02/19/d824493d-7a9c-4969-9859-57b6a73f4f48/default_artifact.jar.
LOG: 20/02/19 07:06:11 WARN DependencyUtils: Skip remote jar abfs://spark24-gen2-yan5-2020-02-18t08-19-36-892z@catestgen2jw.dfs.core.windows.net/tmp/Refer%20Project.jar.
LOG: 20/02/19 07:06:11 INFO RequestHedgingRMFailoverProxyProvider: Created wrapped proxy for [rm1, rm2]
LOG: 20/02/19 07:06:12 INFO RequestHedgingRMFailoverProxyProvider: Looking for the active RM in [rm1, rm2]...
LOG: 20/02/19 07:06:12 INFO RequestHedgingRMFailoverProxyProvider: Found active RM [rm2]
LOG: 20/02/19 07:06:12 INFO Client: Requesting a new application from cluster with 1 NodeManagers
LOG: 20/02/19 07:06:12 INFO Configuration: found resource resource-types.xml at file:/etc/hadoop/3.1.2.2-1/0/resource-types.xml
LOG: 20/02/19 07:06:12 INFO Client: Verifying our application has not requested more than the maximum memory capability of the cluster (51200 MB per container)
LOG: 20/02/19 07:06:12 INFO Client: Will allocate AM container, with 4480 MB memory including 384 MB overhead
LOG: 20/02/19 07:06:12 INFO Client: Setting up container launch context for our AM
LOG: 20/02/19 07:06:12 INFO Client: Setting up the launch environment for our AM container
LOG: 20/02/19 07:06:12 INFO Client: Preparing resources for our AM container
LOG: 20/02/19 07:06:12 INFO Client: Falling back to uploading libraries in this host
LOG: 20/02/19 07:06:12 INFO Client: Uploading resource file:/tmp/spark-324e20b8-a7b6-41b9-8a13-74670c8f8a39/__hive_libs__5858888627168081921.zip -> abfs://spark24-gen2-yan5-2020-02-18t08-19-36-892z@catestgen2jw.dfs.core.windows.net/user/livy/.sparkStaging/application_1582014819300_0007/__hive_libs__5858888627168081921.zip
LOG: 20/02/19 07:06:16 INFO Client: Uploading resource file:/tmp/spark-324e20b8-a7b6-41b9-8a13-74670c8f8a39/__spark_conf__4124332312050592291.zip -> abfs://spark24-gen2-yan5-2020-02-18t08-19-36-892z@catestgen2jw.dfs.core.windows.net/user/livy/.sparkStaging/application_1582014819300_0007/__spark_conf__.zip
LOG: 20/02/19 07:06:16 INFO SecurityManager: Changing view acls to: livy
LOG: 20/02/19 07:06:16 INFO SecurityManager: Changing modify acls to: livy
LOG: 20/02/19 07:06:16 INFO SecurityManager: Changing view acls groups to: 
LOG: 20/02/19 07:06:16 INFO SecurityManager: Changing modify acls groups to: 
LOG: 20/02/19 07:06:16 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(livy); groups with view permissions: Set(); users  with modify permissions: Set(livy); groups with modify permissions: Set()
LOG: 20/02/19 07:06:18 INFO Client: Submitting application application_1582014819300_0007 to ResourceManager
LOG: 20/02/19 07:06:18 INFO YarnClientImpl: Submitted application application_1582014819300_0007
LOG: 20/02/19 07:06:18 INFO Client: Application report for application_1582014819300_0007 (state: ACCEPTED)
LOG: 20/02/19 07:06:18 INFO Client: 
LOG: 	 client token: N/A
LOG: 	 diagnostics: AM container is launched, waiting for AM container to Register with RM
LOG: 	 ApplicationMaster host: N/A
LOG: 	 ApplicationMaster RPC port: -1
LOG: 	 queue: default
LOG: 	 start time: 1582095978163
LOG: 	 final status: UNDEFINED
LOG: 	 tracking URL: http://hn1-spark2.5s4jh3n4ixsergrpcwsxwrrthc.mx.internal.cloudapp.net:8088/proxy/application_1582014819300_0007/
LOG: 	 user: livy
LOG: 20/02/19 07:06:18 INFO ShutdownHookManager: Shutdown hook called
LOG: 20/02/19 07:06:18 INFO ShutdownHookManager: Deleting directory /tmp/spark-761acc34-d454-4861-87fa-d12ed2745159
LOG: 20/02/19 07:06:18 INFO ShutdownHookManager: Deleting directory /tmp/spark-324e20b8-a7b6-41b9-8a13-74670c8f8a39
ERROR: The Spark job failed to start due to 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.deploy.yarn.Client$.getSecondaryJarUris(Client.scala:1451)
	at org.apache.spark.deploy.yarn.Client$.getUserClasspath(Client.scala:1439)
	at org.apache.spark.deploy.yarn.ApplicationMaster.<init>(ApplicationMaster.scala:86)
	at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:796)
	at org.apache.spark.deploy.yarn.ApplicationMaster.main(ApplicationMaster.scala)

For more detailed output, check the application tracking page: https://spark24-gen2-yan5.azurehdinsight.net/yarnui/hn/cluster/app/application_1582014819300_0007 Then click on links to logs of each attempt.
. Failing the application.

**Comment by t-rufang** [comment]
We have encoded the Gen2 URI but Spark backend can't handle the URI properly. This is Spark backend issue and should not be handled by our client tool.
