### ISSUE TITLE
Importing Azure publish settings fails

### ISSUE THREAD

**Issue by condig** [Microsoft/azure-tools-for-java#4]
I´ve done the tutorial to integrate the Azure Plugin for Eclipse and tried to import my publish settings. But after I imported the file and click refresh on the storage Account following error occurs with no additional information

![image](https://cloud.githubusercontent.com/assets/1215964/14497190/40b831d8-0196-11e6-92d0-8fa45fc2bfe0.png)

Note: I´m connected to the internet behind a proxy.

**Comment by martinsawicki** [comment]
publish settings support getting removed in v3.0
