### ISSUE TITLE
Updating Azure local cache after subscription selection hangs

### ISSUE THREAD

**Issue by jianghaolu** [Microsoft/azure-tools-for-java#40]
------- UPDATE ------
You can reproduce by switching subscriptions without having to open 2 projects.

Reproduce:
- Open 2 IntelliJ windows (2 projects)
- In one window, Sign in, select all subscriptions
- In the same windows, uncheck all but one subscription
- Apply. 
- The 2nd window pops up an "Updating Azure local cache" dialog, which hangs and cannot be canceled. The only way out is to force quit IntelliJ

<img width="1280" alt="screen shot 2017-02-17 at 9 43 16 am" src="https://cloud.githubusercontent.com/assets/2320445/23076487/8c3a92f6-f4f5-11e6-9c41-47446d1a4766.png">

**Comment by bsaby** [comment]
Test passed in artifacts/azure-toolkit-for-intellij.197.zip
