### ISSUE TITLE
[Intellij.2017.VM]Unable to set Availability set [Windows]

### ISSUE THREAD

**Issue by zackliu** [microsoft/azure-tools-for-java#401]
Platform: Windows 10, Intellij 2017

![image](https://cloud.githubusercontent.com/assets/7847428/25889751/8b5e0bfe-359d-11e7-8dbe-976d30d96f03.png)

I can't fill in the Availability set blank because there is no scrollbar and  I can't change the size of dialog as well.

**Comment by andxu** [comment]
![image](https://user-images.githubusercontent.com/17075863/83528426-a9d17d00-a51b-11ea-85ee-f0f6afba5182.png)
