### ISSUE TITLE
[IntelliJ][config] Lack of one < in the warning message

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#4014]
Build: azure-toolkit-for-intellij-2019.2.4.develop.11569707.02-24-2020

Repro Steps:
1. Create a HDI config file
2. Do not enter gen2 path, save
3. Submit, when pops warning, click cancel submit
4. Warning message display at the bottom-left corner

Result:
Lack of one <
![image](https://user-images.githubusercontent.com/36756024/75141337-b29c0100-572b-11ea-9820-ae8901091f95.png)

Expect:
![image](https://user-images.githubusercontent.com/36756024/75141370-c47da400-572b-11ea-87b2-8383fd7fb430.png)

The same with 
![image](https://user-images.githubusercontent.com/36756024/75164743-3241c400-575c-11ea-968b-a853868ae92c.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738868
