### ISSUE TITLE
Double-Checked Locking

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [microsoft/azure-tools-for-java#4015]
https://github.com/microsoft/azure-tools-for-java/blob/d599b052bb809fdf331ed1e3975d3c5511ed7367/Utils/hdinsight-node-common/src/com/microsoft/azure/hdinsight/sdk/cluster/ClusterManager.java#L48-L55

Double-Checked Locking is widely cited and used as an efficient method for implementing lazy initialization in a multithreaded environment.
Unfortunately, it will not work reliably in a platform independent way when implemented in Java, without additional synchronization.

**Comment by andxu** [comment]
good catch of checkpoint at sonar: 
https://rules.sonarsource.com/java/tag/multi-threading/RSPEC-2168

**Comment by andxu** [comment]
I suggest to use this way:
```java
public class SafeLazyInitialization {
    private static Resource resource;

    public static synchronized Resource getInstance() {
        if (resource == null)
            resource = new Resource();
        return resource;
    }

    static class Resource {
    }
}
```

**Comment by andxu** [comment]
We can use lombok: http://peichhorn.github.io/lombok-pg/Singleton.html

**Comment by andxu** [comment]
Close it since no concrete plan and no evidence of breaking the singleton logic in current implementation
