### ISSUE TITLE
[IntelliJ][ESP] Link cluster will show duplicate clusters

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#4017]
Build: azure-toolkit-for-intellij-2019.2.4.develop.11569707.02-24-2020

Repro Steps:
1. Link a ESP HIB cluster

Result:
Duplicate clusters display
![image](https://user-images.githubusercontent.com/36756024/75165820-ec85fb00-575d-11ea-9b83-03e4b7b24913.png)

2. Unlink cluster

Result:
The cluster will not display in the list, unless refresh HDInsight node.
![image](https://user-images.githubusercontent.com/36756024/75167019-b34e8a80-575f-11ea-95cb-8fcebee4ee0a.png)

**Comment by t-rufang** [comment]
Fixed in #4052

**Comment by jingyanjingyan** [comment]
With build: azure-toolkit-for-intellij-2019.2.4.develop.11601023.02-28-2020

Fix: link cluster will not show duplicate clusters now
**Still Repro: Unlink then the cluster will not display then.**

**Comment by jingyanjingyan** [comment]
“Still Repro: Unlink then the cluster will not display.” sync offline, the behavior is expect since auto refresh is disabled. Close the issue as FIx
