### ISSUE TITLE
[IntelliJ]Cancel job will get warning Failed to cancel spark job

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#4019]
Build:

Repro steps:
1. Create a HDInsight config with ESPHIB cluster
2. Submit
3. Click "Cancel" when the cancel button is enabled ASAP

Result:
In the output window, get warning message says failed to cancel spark job

Package and deploy the job to Spark cluster
ERROR: Failed to stop spark job. error code: 404, reason: Not Found.

Expect:
The job is canceled.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738867
