### ISSUE TITLE
[Intellij.2017.Docker] Help button in New Host and Publish doesn't work

### ISSUE THREAD

**Issue by zackliu** [microsoft/azure-tools-for-java#402]
Platform: Windows 10, Intellij 2017

![image](https://cloud.githubusercontent.com/assets/7847428/25891422/8f268bf2-35a3-11e7-9e46-a7f9d4e1f0f6.png)

![image](https://cloud.githubusercontent.com/assets/7847428/25891463/bbe07af4-35a3-11e7-9a45-dc257715662a.png)

1.Right click on [Docker Hosts]
2.Enter New Host or Publish dialog
3.Click Help button

**Comment by Flanker32** [comment]
The issue has been fixed in the latest release
