### ISSUE TITLE
[IntelliJ]Re-run does not work well

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#4021]
Build: azure-toolkit-for-intellij-2019.2.4.develop.11569707.02-24-2020

Repro Steps:
1. Submit a synapse config
2. Re-run

Result:
It seems the re-run does not start
![wei2](https://user-images.githubusercontent.com/36756024/75177119-7f2f9580-5770-11ea-89c9-e01a8c6bd7ef.gif)

**Comment by t-rufang** [comment]
Fixed in #4036

**Comment by jingyanjingyan** [comment]
Fix in build azure-toolkit-for-intellij-2019.2.4.develop.11601023.02-28-2020
Re-run works well
