### ISSUE TITLE
[IntelliJ]Check remote debug password message does not display

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#4026]
Build: azure-toolkit-for-intellij-2019.2.4.develop.11569707.02-24-2020

Repro Steps:
1. Create a HDInsight config file, enable the advanced configuration for remote debug
2. Enter password

Result:
No message about "checking the auth xxx..."
![image](https://user-images.githubusercontent.com/36756024/75221048-cacb5900-57db-11ea-8d42-17aaa592c19e.png)

**Comment by wezhang** [comment]
Dup #4031
