### ISSUE TITLE
[IntelliJ][Config] The "cluster name" in the warning should be changed to "spark pool name" in Spark on Synapse configuration dialog

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#4035]
**IntelliJ build version:** 2019.2.4 IC-192.7142.36
**OS:** Windows 10
**JDK:** JetBrains s.r.o 11.0.4
**Plugin version:** https://dev.azure.com/mseng/VSJava/_build/results?buildId=11571266&view=artifacts&type=publishedArtifacts

**Repro Steps:**

1. Open Run/Debug config dialog
2. Add a new Spark on Synapse config
3. Check the warning that under the spark pool

**Expect:**  The "cluster name" in the warning should be changed to the "spark pool name".
![image](https://user-images.githubusercontent.com/40199316/75322667-34b43300-58ae-11ea-973d-c892822cb037.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738866
