### ISSUE TITLE
[Eclipse] Cannot create Ubuntu16.04 VM [Mac]

### ISSUE THREAD

**Issue by testforstephen** [microsoft/azure-tools-for-java#406]
There are two issues at this wizard.
**issue1** 
At the last step of new vm wizard, when i leave "Storage Account" to empty, and click "Finish" button. It failed with error dialog.
<img width="526" alt="screen shot 2017-05-11 at 11 18 03 am" src="https://cloud.githubusercontent.com/assets/14052197/25931237/b10a4f84-363d-11e7-93d5-969979c437db.png">

<img width="522" alt="screen shot 2017-05-11 at 11 18 26 am" src="https://cloud.githubusercontent.com/assets/14052197/25931099/d43b111a-363c-11e7-970b-3b8c565156b4.png">
 
**issue2**
At the last step of new vm wizard, when i select "Create new" storage account there, and click "Finish" button. It failed with null dialog.
<img width="518" alt="screen shot 2017-05-11 at 11 23 31 am" src="https://cloud.githubusercontent.com/assets/14052197/25931224/9e6c3b8a-363d-11e7-956e-9befc8f7ee88.png">

**Comment by Matthew-Dong** [comment]
Same issue on Windows, fail to create a CentOS VM

**Comment by Flanker32** [comment]
Duplicated with #400, creating virtual machine wizard didn't stop user when information is not complete
