### ISSUE TITLE
[Eclipse] New VM doesn't list newly created resource group [Mac]

### ISSUE THREAD

**Issue by testforstephen** [microsoft/azure-tools-for-java#407]
At the last step of new vm wizard, when select "use existing" resource group, it didn't list one of my resource group (jinbwan_ej_rg).  But i can find this resource group at azure portal.
<img width="524" alt="screen shot 2017-05-11 at 11 37 58 am" src="https://cloud.githubusercontent.com/assets/14052197/25931495/2b122472-363f-11e7-9952-775c4dc99ab8.png">

P.S. This resource group is created about 10 minutes ago, not sure if there is latency.

**Comment by andxu** [comment]
I can see RG created 30 second  ago. @testforstephen  would you please try it again  about this issue?
