### ISSUE TITLE
[IntelliJ][ESPHIB] Gen2 root path could not be edit after saving with invalid value

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#4071]
Build: azure-toolkit-for-intellij-2019.2.4.develop.11606681.02-29-2020

Repro Steps:
1. Link one esphib cluster
2. Create one HDI config, select the linked esphib cluster
3. In upload field, input one invalid root path, save config
4. Re-open the config, try to edit the root path

Result:
Could not edit the root path
![intellij2](https://user-images.githubusercontent.com/36756024/75647540-39029680-5c88-11ea-8eee-7ba48140b751.gif)

**Comment by t-rufang** [comment]
Fixed in #4132

**Comment by v-lanjli** [comment]
Verified and fixed.
Closed this issue.
