### ISSUE TITLE
[IntelliJ] ADLS gen1 config ask for sign in when it is already sign-in in file level

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#4072]
Build: azure-toolkit-for-intellij-2019.2.4.develop.11606681.02-29-2020

Repro Steps:
1. Sign in IntelliJ
2. Create a ADLS gen1 cluster
3. Refresh HDI cluster node, the adls cluster display well
4. Create a HDInsight config, select the adls cluster, check the settings below

Result:
Ask for sign in
![image](https://user-images.githubusercontent.com/36756024/75647836-2a68af00-5c89-11ea-8ac7-9d5b75d2359f.png)

Expect:
Detect the sign in status automatically.

**Comment by wezhang** [comment]
Reopen it when repro
