### ISSUE TITLE
Application insights show Resource not found on the portal.

### ISSUE THREAD

**Issue by Elvira-sxr** [microsoft/azure-tools-for-java#4077]
#### Environment：

- OS : Win&Mac
- Plugins Version : Azure java toolkit for IntelliJ: 3.33.0
- IDE Version: IU-jre11 & IC-jre8

#### Repro steps:
1. Create a java project, and configure application insights.
2. Run project, make sure run successfully,
3. Go to portal and found your resource

#### Result:
![image](https://user-images.githubusercontent.com/51812626/75764975-ae9a5f80-5d79-11ea-9f22-a89fc35eb243.png)

**Comment by ZhengJun003** [comment]
Test pass in azure toolkits for IntelliJ 3.37.0
