### ISSUE TITLE
[IntelliJ][193]Remote run/debug get error

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#4078]
Build: azure-toolkit-for-intellij-2019.3.develop.11618228.03-02-2020

Repro Steps:
1. Create a HDInsight/sparkoncosmos/serverless/synapse config, remote run/debug

Result:
Invalid config dialog pops,the warning message might need update, and the submission is block
![image](https://user-images.githubusercontent.com/36756024/75846112-33d35200-5e16-11ea-99ae-789cf6b3bb16.png)

**Comment by v-lanjli** [comment]
After clicking the "Edit" button in this "Change Configuration" settings dialog, the edit configuration dialog with error is displayed.
![image](https://user-images.githubusercontent.com/40199316/75904641-8b0d0d00-5e7e-11ea-9a03-8ed7a39fa9f8.png)

**Comment by v-lanjli** [comment]
Verified and fixed in this issue (https://dev.azure.com/mseng/VSJava/_build/results?buildId=11640620&view=artifacts&type=publishedArtifacts)
Closed this issue.
