### ISSUE TITLE
[Eclipse][Linux]Can't open Show FTP deloyment credentials link in Web app dialog

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#408]
![image](https://cloud.githubusercontent.com/assets/22470312/25931212/9136b6ac-363d-11e7-9af8-d68fe679c21e.png)
**RESULT:**
No response after clicking
**EXPEXT:**
![image](https://cloud.githubusercontent.com/assets/22470312/25931874/a0166984-3641-11e7-998f-0eac01f261b1.png)

**Comment by bsaby** [comment]
Also repro  in the latest released build:  3.0.1.201705020538 on Linux.

**Comment by Flanker32** [comment]
The issue has been fixed in the latest release
