### ISSUE TITLE
[IntelliJ][193]Remote run/debug get error with bundle build

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#4083]
Build: ideaIC-bundle-win-x64-2019.3.develop.11618228.03-02-2020
Repro Steps:
Create a HDInsight/sparkoncosmos/serverless/synapse config, remote run/debug
Result:
Invalid config dialog pops,the warning message might need update, and the submission is block
![image](https://user-images.githubusercontent.com/43333874/75872488-19bc5400-5dc3-11ea-910a-ab4f6e6af0f6.png)

**Comment by wezhang** [comment]
It would be fixed at release.next branch with hotfixes. Could you try it again? Thanks!

**Comment by v-xiaocw** [comment]
Fixed and verified
