### ISSUE TITLE
[Eclipse][Linux] A no content dialog box appears when creating new storage account in vm creation

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#409]
In vm creation, choosing create new storage or create new Virtual Network in Associated Resources tab , A no content dialog box appears and can't close .
![image](https://cloud.githubusercontent.com/assets/22470312/25931364/78011c8a-363e-11e7-87ac-4919ac0f83b9.png)
![image](https://cloud.githubusercontent.com/assets/22470312/25932061/7c00cc6e-3642-11e7-9fbf-e1a69ba378b2.png)

**Comment by bsaby** [comment]
Also repro  in the latest released build:  3.0.1.201705020538

**Comment by pl07** [comment]
Test pass in azure java toolkit for eclipse 3.23.0.
