### ISSUE TITLE
[IntelliJ][2020.1 EAP] Get error running when running remote debug.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#4108]
**IntelliJ Verison:** IntelliJ 2020.1
**Build:** https://dev.azure.com/mseng/VSJava/_build/results?buildId=11679560&view=artifacts&type=publishedArtifacts
**Repro Steps:**

1. Create a HDInsight application
2. Run remote debug

**Results:**
Error running '[Spark on HDInsight] LogQuery': com.intellij.execution.ExecutionException: Spark Batch Job execution result is not ready.
![image](https://user-images.githubusercontent.com/40199316/76405547-3f4ced00-63c3-11ea-8564-5eef8d5365f8.png)

**Comment by wezhang** [comment]
![image](https://user-images.githubusercontent.com/7385667/77028772-c65a2080-69d4-11ea-9d8b-40310c53bea7.png)
`remoteProcessCtrlLogHandler` is null,  `executionResult` is null and `consoleView` is null

**Comment by v-lanjli** [comment]
Verified and fixed in this build (https://dev.azure.com/mseng/VSJava/_build/results?buildId=11760285&view=artifacts&type=publishedArtifacts)
Closed this issue.
