### ISSUE TITLE
[IntelliJ][2020.1 EAP] The distance between the Locally Run tab and Remotely Run in Cluster tab is too close.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#4112]
**IntelliJ Verison:** IntelliJ 2020.1
**Build:** https://dev.azure.com/mseng/VSJava/_build/results?buildId=11679560&view=artifacts&type=publishedArtifacts
**Repro Steps:**

1. Create a  project, or open a project.
2. Open Config Edit dialog.
3. Check the Locally Run tab and Remotely Run in Cluster tab.

**Results:**
 The distance between the Locally Run tab and Remotely Run in Cluster tab is too close.
![image](https://user-images.githubusercontent.com/40199316/76489871-91921a80-6464-11ea-8d20-21dff677113c.png)

**Comment by wezhang** [comment]
This is by IntelliJ design.
