### ISSUE TITLE
[IntelliJ][Debug]After uncheck the Enable Spark remote debug, show this error "Error: SparkJobDebug: there are no runners for Apache Spark on HDInsight: [Spark on HDInsight] LogQuery".

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#4113]
**IntelliJ Verison:** IntelliJ 192/192
**Build:** Market build

**Repro Steps:**

1. Create a project, or open a project.
2. Enable remote debug in Config with a wrong password, then run remote debug.
3. Click Edit when show change configuration settings dialog.
4. Uncheck the Enable Spark remote debug
5. Check the results

**Results:**
Show this error "Error: SparkJobDebug: there are no runners for Apache Spark on HDInsight: [Spark on HDInsight] LogQuery".
![After disable the Spark remote debug, show this error ](https://user-images.githubusercontent.com/40199316/76491452-aa9cca80-6468-11ea-9a84-1ec624cc38ea.gif)

**Comment by t-rufang** [comment]
This is by design. User can't run a remote debug feature without enabling remote debug checkbox.
