### ISSUE TITLE
[IntelliJ] Support dynamic loading for our plugin

### ISSUE THREAD

**Issue by t-rufang** [microsoft/azure-tools-for-java#4119]
Following [Jetbrains SDK document](https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/dynamic_plugins.html), in order to support dynamic loading for our plugin, we need to finish the following tasks.
 - [x] @t-rufang Migrate application component JobViewApplicationComponent to ApplicationListener  
 - [x] @t-rufang Migrate application component HDInsightActionsComponent to ApplicationListener
 - [x] @t-rufang Migrate application component AzureActionsComponent to ApplicationListener
 - [x] @t-rufang Migrate project component AzurePlugin to StartupActicity Extension
 - [ ] @t-rufang Add unique ID for all groups in Plugin.xml
 - [ ] @Flanker32 Replace non-dynamic extension fileTypeFactory with filetype
 - [ ] @t-rufang Implement Configurable.WithEpDependencies for AzureConfigurable

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738864
