### ISSUE TITLE
[IntelliJ]Still show error running after clicking Cancel Submit button.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#4136]
**IntelliJ Version:** 193
**Plugin Version:** https://dev.azure.com/mseng/VSJava/_build/results?buildId=11721960&view=artifacts&type=publishedArtifacts

**Repro Step:**
1. Edit incorrect configuration
2. Submit this job
3. Click on Cancel Submit button in Change Configuration settings dialog
4. Check the results

**Results**: Still show error running. 
**Expect:** It is recommended to display the message "Job has been canceled submit".
![2](https://user-images.githubusercontent.com/40199316/76888599-265ea300-68bf-11ea-9979-afe978e56724.gif)

**Comment by wezhang** [comment]
This's by design.
