### ISSUE TITLE
[IntelliJ][Config]After switching to another cluster, the info of the job storage upload section will not be refreshed.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#4137]
IntelliJ Version: 193
Plugin Version: https://dev.azure.com/mseng/VSJava/_build/results?buildId=11721960&view=artifacts&type=publishedArtifacts

Repro Steps:

1. Create anew project, or open an existing project
2. Edit Config
3. For Storage Type, select Use Azure Blob to upload
4. Fill in Storage Account and Key
5. Save this Config
6. Switching to another cluster, and check the info of the job storage upload section.

Results: The information in the job store upload section is not refreshed. Continue to submit job, error will occur.
![3](https://user-images.githubusercontent.com/40199316/76892431-af78d880-68c5-11ea-842f-38bb90feef00.gif)
![image](https://user-images.githubusercontent.com/40199316/76892469-bb649a80-68c5-11ea-920a-8a7d5ac41635.png)

**Comment by wezhang** [comment]
This is by design, the user may reuse the specified blob storage for other cluster. Thanks @v-lanjli !
