### ISSUE TITLE
[IntelliJ][SparkonCosmos][Console]Get this error: Livy interactive session failed to start to the error com.microsoft.azure.hdinsight.sdk.common.HDIException: the storage type should be ADLS

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#4141]
IntelliJ Version: 193
Plugin Version: https://dev.azure.com/mseng/VSJava/_build/results?buildId=11721960&view=artifacts&type=publishedArtifacts

Repro Steps:

1. Provision Spark Cluster
2. Edit config
3. Tools->Spak Console-> Run Spark Livy Interactive Session Console
 
Results: Livy interactive session failed to start to the error com.microsoft.azure.hdinsight.sdk.common.HDIException: the storage type should be ADLS
![image](https://user-images.githubusercontent.com/40199316/76922436-a3b00500-690b-11ea-8fc0-97d2c1630116.png)

**Comment by t-rufang** [comment]
Fixed in #4143

**Comment by v-lanjli** [comment]
Veried and fixed in this build (https://dev.azure.com/mseng/VSJava/_build/results?buildId=11727349&view=artifacts&type=publishedArtifacts)
Closed this issue.
