### ISSUE TITLE
[201] Select Subscriptions bydefault dialog is too small

### ISSUE THREAD

**Issue by wezhang** [microsoft/azure-tools-for-java#4147]
![image](https://user-images.githubusercontent.com/7385667/77028245-35cf1080-69d3-11ea-8e82-d8ee561e1951.png)

**Comment by wezhang** [comment]
My Windows 10 display setting: 
![image](https://user-images.githubusercontent.com/7385667/77028439-ba219380-69d3-11ea-9192-11f6f905e4c0.png)

**Comment by Flanker32** [comment]
Fixed in #4184
