### ISSUE TITLE
[IntelliJ][EAP]Missing synapse type in default spark application type.

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#4151]
Build: 
azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.develop.11734430.03-19-2020
Repro Steps:
1.Create a new project
2.Click Tools->Default spark application type OR   Right Click the name of sample "LogQuery" select Default spark application type

Result:Missing synapse type in default spark application type
![image](https://user-images.githubusercontent.com/43333874/77043361-565d9180-69f8-11ea-834f-62f542b87463.png)

**Comment by wezhang** [comment]
Not yet merged
