### ISSUE TITLE
[IntelliJ][193]“Spark on arcadia cluster” in Default spark application type should be modified to "Spark on synapse"

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#4152]
Build: ideaIC-bundle-win-x64-2019.3.develop.11727977.03-18-2020
azure-toolkit-for-intellij-2019.3

Repro Steps:
1.Create a new project
2.Click Tools->Default spark application type OR Right Click the name of sample "LogQuery" select Default spark application type

Result:
![image](https://user-images.githubusercontent.com/43333874/77044317-27481f80-69fa-11ea-9853-4b7f3860916e.png)

**Comment by t-rufang** [comment]
Fixed in #4153

**Comment by v-lanjli** [comment]
Verified and fixed in this build (https://dev.azure.com/mseng/VSJava/_build/results?buildId=11760285&view=artifacts&type=publishedArtifacts)
Closed this issue.
