### ISSUE TITLE
[IntelliJ][193]Synapse spark livy Interactive session failed

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#4154]
Build: ideaIC-bundle-win-x64-2019.3.develop.11727977.03-18-2020
azure-toolkit-for-intellij-2019.3

Repro Steps:
1.Create a synapse config
2.Click Tools->Spark Console->Spark livy interactive session console

Result:Failed
Livy interactive session failed to start due to the error java.lang.RuntimeException: com.microsoft.azure.hdinsight.sdk.common.livy.interactive.exceptions.SessionNotStartException: Session Unnamed >> Synapse Spark Livy Interactive Session Console(Scala) is DEAD. stdout:  ;
stderr:  ;
YARN Diagnostics:  ;     at com.twitter.util.Timer$$anonfun$schedule$1$$anonfun$apply$mcV$sp$1.apply(Timer.scala:39) ;     at com.twitter.util.Local$.let(Local.scala:4904) ;     at com.twitter.util.Timer$$anonfun$schedule$1.apply$mcV$sp(Timer.scala:39) ;     at com.twitter.util.JavaTimer$$anonfun$2.apply$mcV$sp(Timer.scala:233) ;     at com.twitter.util.JavaTimer$$anon$2.run(Timer.scala:264) ;     at java.util.TimerThread.mainLoop(Timer.java:555) ;     at java.util.TimerThread.run(Timer.java:505) ; 20/03/19 07:09:55 WARN InMemoryCacheClient: Token not found in in-memory cache ;
YARN Diagnostics:  ; No YARN application is found with tag livy-session-3-y0vypazx in 300 seconds. This may be because 1) spark-submit fail to submit application to YARN; or 2) YARN cluster doesn't have enough resources to start the application in time. Please check Livy log and YARN log to know the details.
![image](https://user-images.githubusercontent.com/43333874/77057806-78aed980-6a0f-11ea-8c16-6fe44d551c9b.png)

**Comment by wezhang** [comment]
Looks like a backend issue, could you help try last release version?

**Comment by v-xiaocw** [comment]
@wezhang OK

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738863
