### ISSUE TITLE
Will show panel format issue with some operations

### ISSUE THREAD

**Issue by EricZhangzf** [microsoft/azure-tools-for-java#4155]
#### Environment
```
OS: Mac
Plugins Version : Azure java toolkit for IntelliJ: 3.34.0
IDE Version: IC2019.3.4-jre11
```
#### Repro steps
1. Sign in with your account
2. Right click your account and select sign out

your will meet panel format issue

#### Result
- sign in with sp file:
![image](https://user-images.githubusercontent.com/44559777/77063176-36d66100-6a18-11ea-84d5-d515f5600424.png)
- sign in with device login:
![image](https://user-images.githubusercontent.com/44559777/77063246-566d8980-6a18-11ea-8461-b9254b717ef4.png)

#### NOTE:
- If your sign out with `signout button`, result is correct.
![image](https://user-images.githubusercontent.com/44559777/77063381-8e74cc80-6a18-11ea-9178-521801443655.png)
- Delete/restart/shutdown your VM can also repro this issue.
![image](https://user-images.githubusercontent.com/44559777/77063451-af3d2200-6a18-11ea-9caf-904ce5362ebd.png)

**Comment by ZhengJun003** [comment]
Plugins Version: Azure java toolkit for IntelliJ: 3.36.0

The dialog of the delete function app and delete the spring cloud app also have this issue

![image](https://user-images.githubusercontent.com/41051257/80304782-d4c50480-87ea-11ea-8baa-280b85c5fc41.png)

![image](https://user-images.githubusercontent.com/41051257/80304783-d7bff500-87ea-11ea-95cf-de3ec37150d3.png)

**Comment by EricZhangzf** [comment]
Not repro in v3.37.0, close it.
