### ISSUE TITLE
[Eclipse] Submit to emulator successful, but get log failed

### ISSUE THREAD

**Issue by ruoxinCheng** [microsoft/azure-tools-for-java#416]
List spark clusters ...
List spark clusters successfully
List additional spark clusters successfully
Info : Get target jar from C:/Users/v-rouche/workspace/MyEmulator\MyEmulator.jar.
Info : Submit to spark cluster successfully.
See spark job view from http://127.0.0.1:8998/sparkhistory
======================Begin printing out spark job log.=======================
Error : Failed to getting running log. Exception : com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

**Comment by voidfunction** [comment]
@ruoxinCheng Please verify.

**Comment by voidfunction** [comment]
No repo in my environment. Seems emulator problem. I will do more investigation about it.
