### ISSUE TITLE
Cancel button doesn't work

### ISSUE THREAD

**Issue by pl07** [microsoft/azure-tools-for-java#4165]
#### Environment：
 - OS : Win Mac
 - Plugins Version : Azure java toolkit for IntelliJ: 3.34.0
 - IDE Version: IC2019.3.4-jre11 & IU 2019.3.3-jre8
#### Repro steps:
1. Create webapp or add new function
2. Click `Cancel` button, the `Cancel` button doesn't work,
![image](https://user-images.githubusercontent.com/46642771/77143617-b0c12580-6abe-11ea-8206-923c8b4b5558.png)

#### Note:
When publishing docker container on azure,  the `Cancel` button doesn't work too.

**Comment by andxu** [comment]
Add to back log

**Comment by ZhengJun003** [comment]
Test in: Azure java toolkit for IntelliJ: 3.35.0

Can't cancel creating new function app

![image](https://user-images.githubusercontent.com/41051257/78976157-324d2600-7b48-11ea-9970-94f232f5c8a8.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738813

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
