### ISSUE TITLE
Duplicate 'Azure' item

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-tools-for-java#4188]
**Environment:**
```
OS: Mac & Win
Plugins Version : Azure java toolkit for IntelliJ: 3.34.0
IDE Version: IU19.2.4 - jre11 & IC19.2.4 - jre8
```
**Repro steps:**

1. Git clone: [spring-petclinic](https://github.com/spring-projects/spring-petclinic.git)
2. Right-click the project

**Result:**

![image](https://user-images.githubusercontent.com/41051257/77522430-3548e500-6ebf-11ea-9f57-641fd03ebde3.png)

**Comment by andxu** [comment]
fixed in https://github.com/microsoft/azure-tools-for-java/pull/4211

**Comment by ZhengJun003** [comment]
Test pass
