### ISSUE TITLE
List subscriptions in Azure Explorer throws exception

### ISSUE THREAD

**Issue by lenala** [Microsoft/azure-tools-for-java#419]
1. Updated plugin from 3.0.1 to 3.0.2 in IntelliJ 2017.1, MacOS
2. Clicked on Select Subscriptions button from Azure Explorer
3. Got exception:
![image](https://cloud.githubusercontent.com/assets/6208231/26011724/11ef7ad0-3707-11e7-9785-be0fb44b8df9.png)
4. Same exception trying to sign out. Note: was logged in with service principal before plugin update. However, able to list subscriptions and sign in/sign out from Tools->Azure menu

**Comment by martinsawicki** [comment]
regression - worked ok in 3.0.1

**Comment by adashen** [comment]
@bsaby please help to add this case to test plan. (Original logged in, and upgrade version)

**Comment by Eskibear** [comment]
I also reproduce it on both Windows & Mac OS. 
It only occur when clicking **buttons** on **Azure Explorer**, `Menu->Tools->Azure->Select Subscriptions / Azure Sign out` are ok
@juniwang  FYI

**Comment by juniwang** [comment]
fixed. Included in the existing PR https://github.com/Microsoft/azure-tools-for-java/pull/384

**Comment by adashen** [comment]
@bsaby please verify the fix on the the daily build

**Comment by bsaby** [comment]
Test passed in IntelliJ2017.1 on Mac and Windows.
Build used: artifacts/azure-toolkit-for-intellij.2017.develop.daily.2.05-15-2017.zip
