### ISSUE TITLE
The title "Update Azure Spring cloud dependency" is not correct

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-tools-for-java#4190]
**Environment:**
```
OS: Mac & Win
Plugins Version: Azure java toolkit for IntelliJ: 3.34.0
IDE Version: IU19.2.4 - jre11 & IC19.2.4 - jre8
```
**Result:**

1. "cloud" should be "Cloud"
![image](https://user-images.githubusercontent.com/41051257/77524119-c7ea8380-6ec1-11ea-9c88-0202152ed34a.png)
2. The title is "Update Azure Spring cloud dependency" whether the progress is adding or updating
![image](https://user-images.githubusercontent.com/41051257/77523571-e7cd7780-6ec0-11ea-8f85-451d2d54cc29.png)

**Comment by andxu** [comment]
fixed in https://github.com/microsoft/azure-tools-for-java/pull/4211

**Comment by ZhengJun003** [comment]
Test pass
