### ISSUE TITLE
Event log message is wrong when updating azure Spring Cloud dependency

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-tools-for-java#4191]
**Environment:**
```
OS: Mac & Win
Plugins Version: Azure java toolkit for IntelliJ: 3.34.0
IDE Version: IU19.2.4 - jre11 & IC19.2.4 - jre8
```
**Repro steps:**

1. Git clone: [spring-petclinic](https://github.com/spring-projects/spring-petclinic.git) and change `spring-boot-starter-parent` version to 2.2.5.RELEASE 
2. Right-click the project and click 'Azure', then select "Add Azure Spring Cloud dependency"
3. Change `spring-boot-starter-parent` version to 2.2.2.RELEASE 
4. Right-click the project and click 'Azure', then select "Add Azure Spring Cloud dependency"

**Result:**

It displays "Azure Spring Cloud dependency is updated……." when changing version 2.2.5.RELEASE to 2.2.2.RELEASE, but Azure Spring Cloud dependencies in the pom are not changed.

![image](https://user-images.githubusercontent.com/41051257/77526236-3715a700-6ec5-11ea-9554-d07bf440c697.png)

**Comment by andxu** [comment]
fixed in https://github.com/microsoft/azure-tools-for-java/pull/4211

**Comment by ZhengJun003** [comment]
Test pass
