### ISSUE TITLE
Wrong content display of URL when clicking “Unassign endpoint”

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-tools-for-java#4193]
**Environment:**
```
OS: Mac & Win
Plugins Version: Azure java toolkit for IntelliJ: 3.34.0
IDE Version: IU19.2.4 - jre11 & IC19.2.4 - jre8
```
**Result:**

![image](https://user-images.githubusercontent.com/41051257/77527382-f74fbf00-6ec6-11ea-909b-c94a7c2600a7.png)

**Expect:**

The URL display content should be N/A when clicking “Unassign endpoint”
![image](https://user-images.githubusercontent.com/41051257/77527460-1d755f00-6ec7-11ea-871d-e3bf6af3ebcb.png)

**Comment by andxu** [comment]
Resolved, please verify

**Comment by ZhengJun003** [comment]
Test pass
