### ISSUE TITLE
[IntelliJ][SpringCloud]The tab key needs to be clicked twice

### ISSUE THREAD

**Issue by Elvira-sxr** [microsoft/azure-tools-for-java#4194]
## Environment:
OS: Mac & Win
Plugins Version: Azure java toolkit for IntelliJ: 3.34.0
IDE Version: IU19.2.4 - jre11 & IC19.2.4 - jre8

## Repro steps:
1. Git clone: spring-petclinic
2. Add spring cloud dependency
3.  Deploy apps from current project
4. Add new environment variables and switch with tab key in Azure Spring Cloud apps Explorer
## Result:
Need to click the tab key twice to switch to another space
![image](https://user-images.githubusercontent.com/51812626/77527853-e5225080-6ec7-11ea-8be1-a197ad477b1f.png)

**Comment by andxu** [comment]
external issue, it is caused by intellij

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738780

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738821

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
