### ISSUE TITLE
[IntelliJ][SpringCloud]The status is not updated in time, and you need to refresh it manually

### ISSUE THREAD

**Issue by Elvira-sxr** [microsoft/azure-tools-for-java#4196]
## Environment:
OS: Mac & Win
Plugins Version: Azure java toolkit for IntelliJ: 3.34.0
IDE Version: IU19.2.4 - jre11 & IC19.2.4 - jre8

## Repro steps:
1. Git clone: spring-petclinic
2. Add spring cloud dependency
3. Deploy apps from current project
4. Change the running state of the app in Azure Spring Cloud apps Explorer
## Result:
After a long time, the latest running status of the app cannot be actively updated

![image](https://user-images.githubusercontent.com/51812626/77528366-c7a1b680-6ec8-11ea-92d0-8ad997a82fff.png)

**Comment by andxu** [comment]
DUP as https://github.com/microsoft/azure-tools-for-java/issues/4228
