### ISSUE TITLE
Error logs not send to the portal when JVM option is out of bounds

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-tools-for-java#4199]
**Environment:**
```
OS: Mac & Win
Plugins Version: Azure java toolkit for IntelliJ: 3.34.0
IDE Version: IU19.2.4 - jre11 & IC19.2.4 - jre8
```
**Result:**

When the value of JVM options is out of bounds, there is local error information, but no corresponding logs in portal
![image](https://user-images.githubusercontent.com/41051257/77528734-69c19e80-6ec9-11ea-9143-1ed64b11f034.png)

![image](https://user-images.githubusercontent.com/41051257/77528757-6d552580-6ec9-11ea-994e-3bf9755753ee.png)

**Comment by ZhengJun003** [comment]
Can reproduce this issue in azure toolkits for IntelliJ 3.38.0

![image](https://user-images.githubusercontent.com/41051257/84638403-85b56900-af29-11ea-9e17-025bb043e3ea.png)

**Comment by Flanker32** [comment]
@ZhengJun003 We will not collect the spring cloud app name which is out of the scope, could you please search the error message instead?

**Comment by ZhengJun003** [comment]
Test in azure toolkits for IntelliJ 3.38.0, can see this message in the application insight, so close this issue.

![image](https://user-images.githubusercontent.com/41051257/84844617-51eb5800-b07d-11ea-9216-491d2a277ce5.png)
