### ISSUE TITLE
[Suggestion] Better message in the signin progress dialog

### ISSUE THREAD

**Issue by anuchandy** [microsoft/azure-tools-for-java#42]
While we log in we show a dialog with message "Signing InProgress.." and if we have multiple subscriptions, another window pops up multiple times. It would be good if we can update static message in the first Window with dynamic data. 

Instead of just "Signing InProgress.." may be "Signing InProgress.. [tenant: &lt;tenantId&gt;]"

**Comment by martinsawicki** [comment]
nice idea for the future, but today, we don't even get this info (or know how to get it) from AD

**Comment by andxu** [comment]
@anuchandy, we have major changes over sign in experience, there will not be any window pops up multiple times, would you please reevaluate this issue again?
