### ISSUE TITLE
[IntelliJ][SpringCloud]Deploy Azure Spring Cloud App dialog default value is apply

### ISSUE THREAD

**Issue by Elvira-sxr** [microsoft/azure-tools-for-java#4204]
## Environment:
OS: Mac & Win
Plugins Version: Azure java toolkit for IntelliJ: 3.34.0
IDE Version: IU19.2.4 - jre11 & IC19.2.4 - jre8

## Repro steps:
1. Git clone: spring-petclinic
2. Add spring cloud dependency
3. Deploy apps from current project
## Result:
![image](https://user-images.githubusercontent.com/51812626/77530116-d342ac80-6ecb-11ea-8e95-9a02800a4f61.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738812

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
