### ISSUE TITLE
Download Plug-In link is 404

### ISSUE THREAD

**Issue by MikeDodaro** [microsoft/azure-tools-for-java#4207]
The following link in documentation (https://github.com/microsoft/azure-tools-for-java/wiki/Azure-Spring-Cloud-support(preview))
doesn't work:

Preview Bits:
You may get the alpha bits for :
https://mseng.visualstudio.com/_apis/resources/Containers/12799228/drop?itemPath=drop%2Fazure-toolkit-for-intellij-2019.2.4.develop.11760558.03-23-2020.zip

{"$id":"1","innerException":null,"message":"The container 12799228 could not be found.","typeName":"Microsoft.VisualStudio.Services.FileContainer.ContainerNotFoundException,

**Comment by Flanker32** [comment]
@MikeDodaro Thanks for your report, we have uploaded the bits to azure storage and update the link, you may download it from [here](https://azuredownloads.blob.core.windows.net/azuretoolkitforintellij/preview/azure-toolkit-for-intellij-2019.2.4.develop.11760558.03-23-2020.zip)
