### ISSUE TITLE
[Azure Functions] unhandled error when creating function app

### ISSUE THREAD

**Issue by yucwan** [microsoft/azure-tools-for-java#4213]
If you click ok without app service plan selected:
![image](https://user-images.githubusercontent.com/49381248/77852859-73257080-7213-11ea-8401-948057895238.png)

it will throw an unhandled error:
![image](https://user-images.githubusercontent.com/49381248/77852850-69037200-7213-11ea-992e-fad4ba64197a.png)

**Comment by Flanker32** [comment]
Fixed in #4239
