### ISSUE TITLE
[IntelliJ][SpringCloud]After selecting "Spring Cloud", nothing is displayed in the App selection box

### ISSUE THREAD

**Issue by Elvira-sxr** [microsoft/azure-tools-for-java#4227]
## Environment:
OS: Win
Plugins Version: Azure java toolkit for IntelliJ: 3.34.0
IDE Version: IU19.3.4 - jre8

## Repro steps:
1. Add spring cloud dependency
2. Add deploy configuration
3. First select a "Spring Cloud" whose Apps are empty, then select any "Spring Cloud"
 
## Result:
![image](https://user-images.githubusercontent.com/51812626/78218362-3f3a9b80-74f0-11ea-845c-b2463f3ae756.png)

**Comment by andxu** [comment]
Fixed in https://github.com/microsoft/azure-tools-for-java/pull/4247

**Comment by Elvira-sxr** [comment]
Issue  fixed
