### ISSUE TITLE
[IntelliJ][SpringCloud]Status is not updated unless refresh "Spring Cloud"

### ISSUE THREAD

**Issue by Elvira-sxr** [microsoft/azure-tools-for-java#4228]
## Environment:
OS: Win
Plugins Version: Azure java toolkit for IntelliJ: 3.34.0
IDE Version: IU19.3.4 - jre8

## Repro steps:
1. Add spring cloud dependency
2. Add deploy configuration
3. Run deploy configuration
4. Restart App
 
## Result:
Status is not updated unless refresh "Spring Cloud"
![image](https://user-images.githubusercontent.com/51812626/78218870-18c93000-74f1-11ea-99ad-24e28d9325c5.png)

**Comment by ZhengJun003** [comment]
Test pass in azure toolkits for IntelliJ 3.37.0, can update status automatically
