### ISSUE TITLE
[IntelliJ][Theme] The color of warning log in dark theme is difficult to distinguish

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#4229]
Build: azure-toolkit-for-intellij-2019.3.develop.11824857.04-01-2020

Repro Steps:
1. Set IntelliJ to dark theme
2. Submit a script to esphib cluster, check the log

Result:
Warning log in dark theme is difficult to distinguish
![image](https://user-images.githubusercontent.com/36756024/78220755-afe3b700-74f4-11ea-8fbe-7c48489269bb.png)

Reference:
In "IntelliJ" theme:
![image](https://user-images.githubusercontent.com/36756024/78220836-dace0b00-74f4-11ea-9bfb-725bd03b094d.png)

In "High contract" theme:
![image](https://user-images.githubusercontent.com/36756024/78220895-f6d1ac80-74f4-11ea-858d-ae42e51d0978.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738860
