### ISSUE TITLE
[IntelliJ][SpringCloud]Cannot use Auth file for spring cloud authentication

### ISSUE THREAD

**Issue by Elvira-sxr** [microsoft/azure-tools-for-java#4231]
## Environment:
OS: Win
Plugins Version: Azure java toolkit for IntelliJ: 3.34.0
IDE Version: IU19.3.4 - jre8

## Repro steps:
1. Login with sp file
2. Right your project select Azure
3. Deploy to azure spring cloud
## Result:
![image](https://user-images.githubusercontent.com/51812626/78315082-85463c80-758e-11ea-97e9-48a784e5f978.png)

**Comment by andxu** [comment]
Will not support auth-file for spring in this sprint

**Comment by andxu** [comment]
https://github.com/microsoft/azure-tools-for-java/pull/4303

**Comment by Elvira-sxr** [comment]
Test pass
