### ISSUE TITLE
When running the function locally, there is no prompt for deploy function

### ISSUE THREAD

**Issue by Elvira-sxr** [microsoft/azure-tools-for-java#4234]
## Environment
OS : Win
Plugins Version : Azure java toolkit for IntelliJ: 3.34.0
IDE Version: IU19.3.4-jre8
## Repro steps
1. Run function locally
2. At the same time deploy function

## Result
It should be reminded that there are function running
![image](https://user-images.githubusercontent.com/51812626/78331203-24cbf500-75b8-11ea-945e-988a75b0b9ef.png)

**Comment by andxu** [comment]
Will fix it in next sprint.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738778

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738819

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
