### ISSUE TITLE
Can not cancel delete function apps

### ISSUE THREAD

**Issue by EricZhangzf** [microsoft/azure-tools-for-java#4253]
#### Environment
OS: Win
Plugins Version : Azure java toolkit for IntelliJ: 3.34.0
IDE Version: IC2019.3.4-jre8
#### Repro steps
1. Right your function app and select delete button
2. When in process, click cancel to cancel delete process.

#### Result
Can not cancel this process.

**Comment by EricZhangzf** [comment]
OS: Mac & Win
Plugins Version : Azure java toolkits for Eclipse: 3.23.0
IDE Version: 2020-03

1. Select your webapps to delete it on Azure Explorer
2. In delete process click stop to cancel delete

Can not cancel delete process

**Comment by Flanker32** [comment]
Now we don't support cancel while deleting function apps, and this feature is not provided in Azure Java SDK

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738779

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738820

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
