### ISSUE TITLE
[IntelliJ][SpringCloud]"show properties" interface is not adaptive

### ISSUE THREAD

**Issue by Elvira-sxr** [microsoft/azure-tools-for-java#4263]
## Environment:
OS: Win
Plugins Version: Azure java toolkit for IntelliJ: 3.34.0
IDE Version: IU19.3.4 - jre8

## Repro steps:
1.  Add spring cloud dependency in pom.xml
2.  Deploy app from current project
3.  In Azure explorer, right-click the app in Spring Cloud, select "show properties"

## Result:
![image](https://user-images.githubusercontent.com/51812626/78854559-33049000-7a54-11ea-9da7-db5cada46aec.png)

**Comment by ZhengJun003** [comment]
When you collapse instances, it will also shrink IntelliJ window

![image](https://user-images.githubusercontent.com/41051257/78970615-4f7bf780-7b3c-11ea-8610-506c13f56685.png)

**Comment by Elvira-sxr** [comment]
Test pass
