### ISSUE TITLE
[IntelliJ][SpringCloud]Right-clicking instance in the "show properties" interface fails to stream log

### ISSUE THREAD

**Issue by Elvira-sxr** [microsoft/azure-tools-for-java#4264]
## Environment:
OS: Win
Plugins Version: Azure java toolkit for IntelliJ: 3.34.0
IDE Version: IU19.3.4 - jre8

## Repro steps:
1.  Add spring cloud dependency in pom.xml
2.  Deploy app from current project
3. Right-clicking instance in the "show properties" interface fails to stream log
## Result:
![image](https://user-images.githubusercontent.com/51812626/78854781-c4740200-7a54-11ea-900f-9a235e9f2e68.png)

**Comment by Flanker32** [comment]
Feature enabled in latest version, check release notes [here](https://github.com/microsoft/azure-tools-for-java/releases)
