### ISSUE TITLE
unable to install azure toolkit from eclipse IDE 2019-09

### ISSUE THREAD

**Issue by shashidivak** [microsoft/azure-tools-for-java#4272]
Hi,

I am unable to install the software from http://dl.microsoft.com/eclipse/ from my eclipse IDE 2019-09 version.
It keeps timing out the connection and ends with an error. 
I tried marketplace for installation and gets the same error.

Error snippet:
Unable to connect to repository http://dl.microsoft.com/eclipse/compositeContent.xml
Connect to dl.microsoft.com:80 [dl.microsoft.com/40.76.210.54] failed: Connection timed out: connect

Appreciate any help on this.

Thanks,
Shashi

**Comment by andxu** [comment]
Hi Shashi,
Can you navigate to the url http://dl.microsoft.com/eclipse/compositeContent.xml through a navigator?

**Comment by shashidivak** [comment]
Hi Andxu,

I am unable to reach the URL http://dl.microsoft.com/eclipse/compositeContent.xml

Thanks,
Shashi

**Comment by andxu** [comment]
External network issue. Close it here.
