### ISSUE TITLE
Function app properties view's column not align

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-tools-for-java#4277]
### Environment:

- OS: Win/Mac
- Plugins Version: Azure java toolkit for IntelliJ: 3.35.0
- IDE Version: IC2019.3.4-jre8/IU19.3 - jre11

### Repro steps:
1. Right-click a function app in azure explorer
2. Select show properties

### Result:
![image](https://user-images.githubusercontent.com/41051257/78975939-c5d22700-7b47-11ea-85ae-354035b790da.png)

**Comment by ZhengJun003** [comment]
Test in Azure java toolkit for IntelliJ: 3.37.0, can reproduce this issue.

![image](https://user-images.githubusercontent.com/41051257/84478245-8f3d9780-acc3-11ea-8415-74bbfe3a1a35.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738781

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
