### ISSUE TITLE
When there are multiple processes, the format of the first process in the background tasks panel is incorrect

### ISSUE THREAD

**Issue by EricZhangzf** [microsoft/azure-tools-for-java#4278]
#### Environment:
```
OS: Mac
Plugins Version: Azure java toolkit for IntelliJ: v3.35.0
IDE Version: IC2019.3.4-jre8
```
#### Repro steps:
1. New a Redis server
2. When in process, new a VM
3. Open the background tasks panel.

#### Result:
![image](https://user-images.githubusercontent.com/44559777/78976771-73920580-7b49-11ea-913d-a2f96eda62b0.png)

**Comment by EricZhangzf** [comment]
Background task has two attribute values to control redis, not created twice.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738782

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
