### ISSUE TITLE
Can't auto select an app setting after click 'Remove' button

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-tools-for-java#4279]
### Environment:

- OS: Win/Mac
- Plugins Version: Azure java toolkit for IntelliJ: 3.35.0
- IDE Version: IC2019.3.4-jre8

### Repro steps:

1. Right-click a function/web app in azure explorer
2. Select show properties
3. Select an app setting and click the 'Remove' button
4. Click the 'Remove' button again

### Result:
'Remove' button is disable
![image](https://user-images.githubusercontent.com/41051257/78978553-8f4adb00-7b4c-11ea-8ff7-9ed41a7ca9ea.png)

**Comment by ZhengJun003** [comment]
Test in Azure java toolkit for IntelliJ: 3.37.0, can reproduce this issue.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738784

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
