### ISSUE TITLE
Add a wheel on the right to improve the experience on properties panel

### ISSUE THREAD

**Issue by EricZhangzf** [microsoft/azure-tools-for-java#4293]
#### Environment：
```
OS: WIN/Mac
Plugins Version: Azure java toolkit for IntelliJ: 3.34.0
IDE Version: IU19.3.4 - jre11/IC19.3 - jre8
```

#### Repro steps:
1. Add spring cloud dependency
2. Run deploy configuration
3. Right click to open "show properties".

#### Result:
The border blocks the instance bar, so I suggest that you should add a wheel on the right to improve the experience
![image](https://user-images.githubusercontent.com/44559777/79097309-ff966e00-7d91-11ea-84ce-46e1574ca57a.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738801

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
