### ISSUE TITLE
[IntelliJ][SpringCloud]Cannot open properties

### ISSUE THREAD

**Issue by Elvira-sxr** [microsoft/azure-tools-for-java#4306]
## Environment
OS: Win/Mac
Plugins Version : Azure java toolkit for IntelliJ: 3.35.0
IDE Version: IU2020.1-jre11

## Repro steps
1. Add spring cloud dependency in pom.xml
2. Deploy app from current project
3. In Azure explorer, right-click the app in Spring Cloud, select "show properties"
## Result
Cannot  open properties
![image](https://user-images.githubusercontent.com/51812626/79311397-f216ea80-7f2f-11ea-83f7-1a37d82df061.png)

**Comment by andxu** [comment]
This issue is resolved.
