### ISSUE TITLE
Selecting the wrong module automatically when adding configuration for gradle function project

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-tools-for-java#4307]
### Environment:

- OS: Win/Mac
- Plugins Version: Azure java toolkit for IntelliJ: 3.35.0
- IDE Version: IC2019.3.4-jre8/IC20.1 - jre11

### Repro steps:

1. Create a gradle function project
2. Add azure functions run/deploy configuration for the project you created

### Result:

![image](https://user-images.githubusercontent.com/41051257/79311294-cc89e100-7f2f-11ea-87c1-7fe661f04755.png)

![image](https://user-images.githubusercontent.com/41051257/79311354-e4616500-7f2f-11ea-861b-242e68a8ce4c.png)

### Expect:

![image](https://user-images.githubusercontent.com/41051257/79311533-28546a00-7f30-11ea-80f6-5ad484bdcdd7.png)

**Comment by ZhengJun003** [comment]
Test in Azure java toolkit for IntelliJ: 3.37.0, can reproduce this issue.

![image](https://user-images.githubusercontent.com/41051257/84477803-cf504a80-acc2-11ea-8114-651e29268d66.png)

**Comment by andxu** [comment]
Don't support gradle project by now.

**Comment by ZhengJun003** [comment]
Test in build: #12391950 

Plugin not auto add module and staging folder for gradle project now
Run configuration
![image](https://user-images.githubusercontent.com/41051257/85006328-8e59a980-b18c-11ea-8685-c2a70e100748.png)
Deploy configuration
![image](https://user-images.githubusercontent.com/41051257/85006451-bb0dc100-b18c-11ea-8003-94a1671aaf77.png)

**Comment by EricZhangzf** [comment]
Tess Pass on build #12399291
![image](https://user-images.githubusercontent.com/44559777/85109894-aa208680-b244-11ea-9a03-b9696485fdcb.png)
