### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

### ISSUE THREAD

**Issue by kulkarnisonia16** [microsoft/azure-tools-for-java#4312]
IntelliJ build version: 2020.1 IC-201.6668.121
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.6
Plugin version: 3.34.0-2020.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1400x911,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
Caused by: java.io.IOException: Cannot run program "func" (in directory "/Users/sokulkar/IdeaProjects/azure-function-examples-wbc/target/azure-functions/azure-function-examples-1586966588218"): error=2, No such file or directory
	at com.microsoft.intellij.runner.functions.localrun.FunctionRunState.runFunctionCli(FunctionRunState.java:121)

**Comment by andxu** [comment]
Add dev to fix this issue.

**Comment by shayannyc25** [comment]
i am getting the same exact error using IntelliJ  ide on windows:

IntelliJ IDEA 2020.1.1 (Community Edition)
Build #IC-201.7223.91, built on April 30, 2020
Runtime version: 11.0.6+8-b765.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows Server 2019 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 733M
Cores: 2
Non-Bundled Plugins: com.microsoft.vso.idea, training, com.microsoft.tooling.msservices.intellij.azure, com.jetbrains.edu

**Comment by Flanker32** [comment]
@shayannyc25 Thanks a lot for your report, could you please help us check whether the directory in error message exist in your machine? If not, could you please compile the project first(By Build->Build Project) and try again?

**Comment by shayannyc25** [comment]
> @shayannyc25 Thanks a lot for your report, could you please help us check whether the directory in error message exist in your machine? If not, could you please compile the project first(By Build->Build Project) and try again?

**Comment by shayannyc25** [comment]
Yes it exists, I had compiled project

**Comment by Flanker32** [comment]
@shayannyc25 Thanks for your information, so did you install azure function core tools as well? Could you please try `func -v` in terminal?

**Comment by andxu** [comment]
@kulkarnisonia16, seem this is related to a mac/intellij issue of "PATH" environment variable: see https://depressiverobot.com/2016/02/05/intellij-path.html, in short, please run the following script on terminal and restart your intellij:
```
curl https://gist.githubusercontent.com/depressiveRobot/9cb8f799c970f0cd57ea/raw/964253533dd46e0202c4873468b3a1ef304b0af1/osx-intellij-set-path.sh > osx-intellij-set-path.sh
chmod +x osx-intellij-set-path.sh
./osx-intellij-set-path.sh "/Applications/IntelliJ IDEA.app" "$PATH"
```

Please change `/Applications/IntelliJ IDEA.app` accordingly to the idea installation path.

**Comment by andxu** [comment]
see https://github.com/microsoft/azure-tools-for-java/wiki/FAQ

**Comment by daytonkevin** [comment]
I know this isssue is closed but I had a similar issue on Windows 10/IntelliJ which I caused myself by creating an Azure project and installing the core tools afterwards.  Core tools must be installed first before project is created.
