### ISSUE TITLE
IntelliJ, Azure Explorer, Sql Server BigData Cluster, Connectivity Issue

### ISSUE THREAD

**Issue by sunilm-css** [microsoft/azure-tools-for-java#4319]
2020-04-20T19:39:04.925-05:00 ERROR_OUTPUT Authentication Error: Connect to 52.188.28.163:30443 [/52.188.28.163] failed: Operation timed out (Connection timed out)

While creating BDC cluster:
Cluster controller endpoint is available at 52.186.164.199:30080.

azdata bdc endpoint list -o table
Gateway to access HDFS files, Spark                     https://52.188.28.165:30443
Spark Jobs Management and Monitoring Dashboard          https://52.188.28.165:30443/gateway/default/sparkhistory
Cluster Management Service                              https://52.186.164.199:30080
SQL Server Master Instance Front-End                    52.188.28.163,31433 
...

I tried login with both SQLServerMaster and ClusterManagementService. No luck
Please see image:

![image](https://user-images.githubusercontent.com/63519129/79812870-b91bb300-833f-11ea-9ad7-a3544c322f05.png)

Note: With "52.188.28.163,31433", azure data studio got connected.

Env: MacOS 10.15.4
IntelliJ: 2019.3.3 Community Edition
Azure: 3.35.0-2019.3

**Comment by t-rufang** [comment]
@sunilm-css Could you please try fill in `Server` with `52.188.28.165` and `Knox Port` with `30443`? In IntelliJ we use HDFS/Spark Gateway endpoint to connect the cluster

**Comment by t-rufang** [comment]
Close this issue since no reply for a long time. Feel free to reopen it if the issue still exists.
