### ISSUE TITLE
[IntelliJ][ReportedByUser] Customer Issues

### ISSUE THREAD

**Issue by kmurray30** [microsoft/azure-tools-for-java#4334]
#### Setup

IntelliJ build version: 2019.3.4 IC-193.6911.18
OS: Windows 10
JDK: JetBrains s.r.o 11.0.6
Plugin version: 3.35.0-2019.3

####  Describe the bug

Followed these steps: https://www.handsonarchitect.com/2017/09/submit-apache-spark-job-from-intellij.html

And anytime I select "Submit Spark Application" nothing occurs. No dialogue box or window pops up, no error, nothing.

I tried reinstalling intellij, and it only made things worse. Now the option no longer appears at all for .scala files (yes I have both the scala plugin and the azure toolkit for intellij plugin installed). It still appears when I select directories, but still nothing happens when I select it.

####  To Reproduce

See above

#### Exception or Stack Trace

N/A

#### Screenshots

![issue](https://user-images.githubusercontent.com/10807012/80191981-5b9b9680-85cb-11ea-880c-28d363bf42e5.png)

![issue2](https://user-images.githubusercontent.com/10807012/80191707-f0ea5b00-85ca-11ea-92c4-85b40fef10e8.png)

**Comment by t-rufang** [comment]
@kmurray30 Sorry for the delayed response. Seems like you are using JDK11 as your system default JDK. Could you try to intall JDK8 and setup environment and then restart IntelliJ?
 - Where to download Oracle JDK8: https://www.oracle.com/java/technologies/javase-jdk8-downloads.html
 - How to setup JDK environment: https://stackoverflow.com/a/26640589
 - You might also need to setup project JDK in IntelliJ: https://www.jetbrains.com/help/idea/sdk.html#set-up-jdk

**Comment by kmurray30** [comment]
> @kmurray30 Sorry for the delayed response. Seems like you are using JDK11 as your system default JDK. Could you try to intall JDK8 and setup environment and then restart IntelliJ?
> 
> * Where to download Oracle JDK8: https://www.oracle.com/java/technologies/javase-jdk8-downloads.html
> * How to setup JDK environment: https://stackoverflow.com/a/26640589
> * You might also need to setup project JDK in IntelliJ: https://www.jetbrains.com/help/idea/sdk.html#set-up-jdk

I've done this but it still shows up as JRE 11 when I create a support ticket. Not sure why?

![image](https://user-images.githubusercontent.com/10807012/80697842-6f913d80-8a8e-11ea-90ef-0b77f0d000cd.png)

![image](https://user-images.githubusercontent.com/10807012/80697888-83d53a80-8a8e-11ea-8b7f-2c5e0b13c809.png)

**Comment by fengshuaihu** [comment]
We have removed this feature in the latest version, please update the latest version
