### ISSUE TITLE
[IntelliJ][ReportedByUser] Customer Issues

### ISSUE THREAD

**Issue by madushajg** [microsoft/azure-tools-for-java#4335]
#### Setup

IntelliJ build version: 2019.2.2 IU-192.6603.28
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.3
Plugin version: 3.30.0-2019.2

####  Describe the bug

new Project wizard does not show Azure Functions.

#### Screenshots

![image](https://user-images.githubusercontent.com/26219651/80203521-e8cf0180-8644-11ea-8cdf-79eea3a71c88.png)

**Comment by Flanker32** [comment]
@madushajg Thanks for your report, we released the Azure Function support in IntelliJ Toolkits v3.34.0, you may get the release note [here](https://github.com/microsoft/azure-tools-for-java/releases/tag/azure-intellij-toolkit-v3.34.0)
