### ISSUE TITLE
'Stop Streaming Logs' will never enable for Linux function app

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-tools-for-java#4338]
### Environment:

- OS: Win/Mac
- Plugins Version: Azure java toolkit for IntelliJ: 3.35.0
- IDE Version: IC2019.3.4-jre11

### Result:
Will open portal Live Metrics Stream for linux function app, so 'Stop Streaming Logs' will never enable for Linux function app
![image](https://user-images.githubusercontent.com/41051257/80304466-94fd1d80-87e8-11ea-8b64-9d44424d5363.png)

**Comment by Flanker32** [comment]
This is a by designed behavior, for now we will open browser before service new log streaming api, so streaming log will always be closed. Synced with PM, no need to fix or hide this action.
