### ISSUE TITLE
[Eclipse+IntelliJ] Redis Cache icon issue

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#434]
Eclipse
![image](https://cloud.githubusercontent.com/assets/22470312/26090521/1a3ec432-3a38-11e7-964a-e1c67954d1ea.png)
IntelliJ 2017 + IntelliJ2016
![image](https://cloud.githubusercontent.com/assets/22470312/26090528/22cf7f1a-3a38-11e7-885b-7cf6b5ce60c1.png)
@jdneo

**Comment by adashen** [comment]
fixed @bsaby please verify

**Comment by bsaby** [comment]
IntelliJ 2017 + IntelliJ2016
Icon size in Azure explorer  is not uniform, Redis Cache icon size is larger than others.

![image](https://cloud.githubusercontent.com/assets/22470312/26182781/f3bde916-3bac-11e7-9873-b63b3dc5fc72.png)

**Comment by jdneo** [comment]
@bsaby Yes, this icon is a temporary icon resource. A later build version can use the right version of redis cache icon

**Comment by adashen** [comment]
@bsaby fixed please verify on the new build

**Comment by bsaby** [comment]
Icon background color problem reproduction.
Build used:
artifacts/azure-toolkit-for-intellij.2016.develop.52.05-18-2017.zip
artifacts/azure-toolkit-for-intellij.2017.develop.52.05-18-2017.zip
![image](https://cloud.githubusercontent.com/assets/22470312/26186295/25be5570-3bc3-11e7-870f-62fb4f4c32ad.png)

**Comment by jdneo** [comment]
@bsaby fixed please verify on the new build

**Comment by bsaby** [comment]
Test passed.
BUilds used:
artifacts/azure-toolkit-for-intellij.2016.develop.56.05-18-2017.zip
artifacts/azure-toolkit-for-intellij.2017.develop.56.05-18-2017.zip
artifacts/WindowsAzurePlugin4EJ.develop.56.05-18-2017.zip
