### ISSUE TITLE
Text overlap error occurred on Push Image Panel

### ISSUE THREAD

**Issue by EricZhangzf** [microsoft/azure-tools-for-java#4341]
#### Environment
```
OS： WIN
Plugins Version: Azure java toolkit for IntelliJ: 3.36.0
IDE Version: IU2020.1-jre11
```

#### Repro steps
1. Prepare a webapp project,
2. Right click your project select Azure -> Push Image

#### Result
A text overlap error occurred
![image](https://user-images.githubusercontent.com/44559777/80343299-33948780-8898-11ea-8f87-145a3e45ec11.png)

**NOTE**: Run on Web App for Containers Panel also has this error.

**Comment by andxu** [comment]
![image](https://user-images.githubusercontent.com/17075863/84752783-c9bf7100-aff0-11ea-9652-d76d3679b389.png)
layout issue, workaround is to enlarge the window height.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738772

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
