### ISSUE TITLE
[IntelliJ][Mac] Azure sign out dialog is broken

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#4342]
**IntelliJ Version**: 
IntelliJ IDEA 2020.1 (Community Edition)
Build #IC-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
**macOS** 10.12.6
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 4
Non-Bundled Plugins: org.jetbrains.plugins.hocon, org.jetbrains.kotlin, org.intellij.scala, com.microsoft.tooling.msservices.intellij.azure

**Build Version**https://dev.azure.com/mseng/VSJava/_build/results?buildId=11997663&view=artifacts&type=publishedArtifacts

**Repro Steps**:

1. Azure Sign out 
2. Check the Azure Sign out dialog
![image](https://user-images.githubusercontent.com/40199316/80357272-4e252b80-88ad-11ea-9ca7-d4511180d452.png)

**Expect**: Azure Sign out dialog should show well, link this
![image](https://user-images.githubusercontent.com/40199316/80359230-1a97d080-88b0-11ea-9b31-bef2448a48c6.png)

**Comment by Flanker32** [comment]
Fixed in #4343
