### ISSUE TITLE
Progress layer is higher than others

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-tools-for-java#4349]
### Environment:
OS: Mac
Plugins Version: Azure java toolkit for Eclipse: 3.22.0
IDE Version: Eclipse 2020-03

### Result:
This isn't a regression issue
![image](https://user-images.githubusercontent.com/41051257/80568226-37a3df00-8a29-11ea-997f-5089e1f4227b.png)

**Comment by andxu** [comment]
Duplicate as #405
