### ISSUE TITLE
[Eclipse+IntelliJ] Properties function issue

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#435]
Redis Cache workflow:
[Eclipse +IntelliJ2017 +IntelliJ2016]
The Properties function has not beenimplemented, so the Properties menu should not appear
![image](https://cloud.githubusercontent.com/assets/22470312/26090646/e952c4da-3a38-11e7-9630-51173121c22a.png)
@jdneo

**Comment by adashen** [comment]
@bsaby fix merged please use the latest build for verification

**Comment by bsaby** [comment]
Test passed.
Build used:
artifacts/azure-toolkit-for-intellij.2016.develop.daily.4.05-17-2017.zip
artifacts/azure-toolkit-for-intellij.2017.develop.daily.4.05-17-2017.zip
artifacts/WindowsAzurePlugin4EJ.develop.daily.4.05-17-2017.zip
