### ISSUE TITLE
Null value in spring cloud property view

### ISSUE THREAD

**Issue by Flanker32** [microsoft/azure-tools-for-java#4350]
Persistent storage size may be null in spring cloud property view

![image](https://user-images.githubusercontent.com/12445236/80569310-455a6400-8a2b-11ea-98c8-e9e392edf31b.png)

**Comment by andxu** [comment]
It should already been fixed in https://github.com/microsoft/azure-tools-for-java/commit/e487cfac72136f3c08ed13388b911bebf9b64d53
