### ISSUE TITLE
Cannot publish as Docker container…

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-tools-for-java#4353]
### Environment:
OS: Win/Mac
Plugins Version: Azure java toolkit for Eclipse: 3.22.0
IDE Version: Eclipse 2020-03

### Repro:

1. Create a Dynamic Web Project
2. Right-click project
3. Click `Azure`  and select `Publish as Docker container…`

### Result:

![image](https://user-images.githubusercontent.com/41051257/80574130-d6cdd400-8a33-11ea-9f39-f870548f12ac.png)

**Comment by Flanker32** [comment]
It seems that Azure VM removed docker so we can't run docker in vm, as docker host will be deprecated soon, this will not be fixed in toolkit, user who want to use docker host could install docker in VM first and then the issue should be resolved.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738764

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
