### ISSUE TITLE
[Eclipse] Resource group sorting issue

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#436]
Redis Cache workflow:
The same letters at the beginning of the group should be put together to facilitate the user to use the letter search function to find their own group, just like the arrangement of the group in IntelliJ.

RESULT:
![image](https://cloud.githubusercontent.com/assets/22470312/26090691/2d7f2ae0-3a39-11e7-92ed-ef2c906b237e.png)
EXPEXT:
![image](https://cloud.githubusercontent.com/assets/22470312/26090696/371e931a-3a39-11e7-828c-e2cd749aa2f9.png)

@jdneo

**Comment by adashen** [comment]
@bsaby fixed please verify

**Comment by bsaby** [comment]
Test passed.
Build used: artifacts/WindowsAzurePlugin4EJ.develop.daily.4.05-17-2017.zip
