### ISSUE TITLE
[IntelliJ][193]The first letter of the name of subscriptions is not aligned

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#4360]
Build:azure-toolkit-for-intellij-2019.3.develop.11993161.04-25-2020

IntelliJ IDEA 2019.3.4 (Community Edition)
Build #IC-193.6911.18, built on March 17, 2020
Runtime version: 11.0.6+8-b520.43 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2008M
Cores: 4
Registry: 
Non-Bundled Plugins: org.intellij.scala, com.microsoft.tooling.msservices.intellij.azure

![image](https://user-images.githubusercontent.com/43333874/80674550-cfb2ce80-8ae4-11ea-9527-badc0280ea2b.png)

**Comment by t-rufang** [comment]
This is because the icon for "Apache Spark on Cosmos" node is 13x13 while other nodes are 16x16. To fix this we need to provide a 16x16 icon for soc node.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738859
