### ISSUE TITLE
[Eclipse] Location soting issue

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#437]
Redis Cache workflow:
The same letters at the beginning of the Location should be put together.
![image](https://cloud.githubusercontent.com/assets/22470312/26090760/873c295c-3a39-11e7-87ab-dfa5c61c3ac4.png)
@jdneo

**Comment by adashen** [comment]
@bsaby fixed please verify

**Comment by bsaby** [comment]
Test passed.
Build used: artifacts/WindowsAzurePlugin4EJ.develop.daily.4.05-17-2017.zip
