### ISSUE TITLE
[Eclipse] Redis Cache:  after clicking OK in the alert box， the interface should return to the New Redis Cache dialog

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#438]
[Eclipse]
If the DNS name user entered is invalid, after clicking OK in New Redis Cache dialog

EXPEXT:
The alert box appears and after clicking OK in the alert box, 
the interface should return to the New Redis Cache dialog 
Or show an error message like the below picture in IntelliJ.
![image](https://cloud.githubusercontent.com/assets/22470312/26090877/359cff44-3a3a-11e7-9a60-00c48128373a.png)
RESULT: The alert box appears and after clicking OK in the alter box, can’t return to the New Redis Cache dialog
![image](https://cloud.githubusercontent.com/assets/22470312/26090918/71f07d86-3a3a-11e7-8338-284bcc49fb62.png)

@jdneo

**Comment by adashen** [comment]
@bsaby fixed in the previous pull request please verify with the newest version

**Comment by bsaby** [comment]
Test passed.
Build used: artifacts/WindowsAzurePlugin4EJ.develop.daily.4.05-17-2017.zip

If the DNS name user entered is invalid, the input box will have an error message and Create button will not be available.
Shown as below picture:
![image](https://cloud.githubusercontent.com/assets/22470312/26184816/a4892448-3bb9-11e7-8860-2857a4d6b60d.png)
