### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

### ISSUE THREAD

**Issue by debinaik** [microsoft/azure-tools-for-java#4384]
IntelliJ build version: 2020.1.1 IC-201.7223.91
OS: Windows 10
JDK: JetBrains s.r.o 11.0.6
Plugin version: 3.36.0-2020.1
Additional Info: Creating first azure function
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,8,0,824x507,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
Caused by: java.io.IOException: Cannot run program "func" (in directory "C:\Users\80228766\IdeaProjects\azure-function-examples\target\azure-functions\azure-function-examples-1590043510133"): CreateProcess error=2, The system cannot find the file specified
	at

**Comment by Flanker32** [comment]
@debinaik Thanks a lot for your report, could you please share a bit more infos like the function core tools version? You may get the result by run `func -v` in powershell

**Comment by debinaik** [comment]
@Flanker32 please find below details from my power-shell

PS C:\WINDOWS\system32> func -v
3.0.2534
PS C:\WINDOWS\system32>

**Comment by debinaik** [comment]
@Flanker32, request you to share your findings ..

**Comment by Flanker32** [comment]
@debinaik Thanks for your help and really sorry for the late reply, i could repro this issue only if the PATH is not set correctly, but it seems fine in your PC. Could you please try invoke `func host start` directly in the staging folder? which is `C:\Users\80228766\IdeaProjects\azure-function-examples\target\azure-functions\azure-function-examples-1590043510133` in your project

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Uncaught Exception  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thr... (#4312)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: Cannot run program "func"
