### ISSUE TITLE
[Eclipse] Dropdown List doesn't work in New Redis Cache dialog.[Linux][Mac]

### ISSUE THREAD

**Issue by davidliangze** [Microsoft/azure-tools-for-java#439]
Operating System: Linux Ubuntu / Mac
Plugin Version: WindowsAzurePlugin4EJ.develop.daily.2.05-15-2017.zip
IDE: Eclipse Neon 3

**Repro step:**
1. In Azure Explorer, right click the top node to sign in (I tried both Automated-Browse and Interactive method).
2. In Azure Explorer, right click Redis Caches node, select Create Redis cache.
3. In New Redis Cache dialog, try to click any dropdown list (for Subscription, Existing Resource Group, Location and Pricing tier).

**Expected:**
All the valid items are listed correctly.
![redis1](https://cloud.githubusercontent.com/assets/26756696/26091146/f330f9e2-3a3b-11e7-9bce-0c0317bbc807.JPG)

**Actual:**
Nothing shows after clicking for **all the dropdown list**.
![redis2](https://cloud.githubusercontent.com/assets/26756696/26091164/1e80f6a6-3a3c-11e7-811d-ec80a4dee243.JPG)

This action can be completed in IntelliJ2016/2017 for Linux and Eclipse, IntelliJ2016/2017 for Windows.
@jdneo

**Comment by jdneo** [comment]
Cannot reproduce this issue on my mac. Does this issue still occur in the new build?

**Comment by davidliangze** [comment]
Not reproducing either on Linux or Mac OS using the latest build.

OS: Ubuntu 16.04.2 LTS / Mac
Build Used: WindowsAzurePlugin4EJ.develop.daily.4.05-17-2017.zip
