### ISSUE TITLE
Unable to clone repository from MSFT devops

### ISSUE THREAD

**Issue by debinaik** [microsoft/azure-tools-for-java#4400]
Hi Team,
I was trying to clone GIT repository from Microsoft Devops by following https://docs.microsoft.com/en-us/previous-versions/azure/devops/java/labs/eclipsegit/?view=azure-devops .
But While adding Team foundation server in step 12 of above link , eclipse throws  below attached error.  Please help me to fix.

![Error](https://user-images.githubusercontent.com/28619627/82801466-fae9cd00-9e9a-11ea-9be3-9e5ea3833c08.png)

**Comment by Flanker32** [comment]
@debinaik Thanks for your report, this is the repository for Azure Toolkit for Java, and here is the [link ](https://github.com/microsoft/team-explorer-everywhere) for Team Explorer Everywhere Plug-in for Eclipse
