### ISSUE TITLE
[E2E] Web Container is confusing in intellij quick-start

### ISSUE THREAD

**Issue by andxu** [microsoft/azure-tools-for-java#4402]
TOMCAT 8.5-jre8 as Web Container 

https://docs.microsoft.com/en-us/azure/developer/java/toolkit-for-intellij/create-hello-world-web-app

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738809

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
