### ISSUE TITLE
[Eclipse\IntelliJ] Not auto-refreshing the Redis Cache node in Azure Explorer after creating Redis Cache is done  

### ISSUE THREAD

**Issue by davidliangze** [Microsoft/azure-tools-for-java#441]
Plugin Version: WindowsAzurePlugin4EJ.develop.daily.2.05-15-2017.zip
 IDE: Eclipse / IntelliJ

**Repro step:**
1. In Azure Explorer, right click Redis Cache node to create new Redis Cache.
2. After configuring done in New Redis Cache dialog, click OK.

Expected:
When the creating process is completed, the Redis Cache node in Azure Explorer should be auto-refreshed, so that the new created Redis Cache can be shown in the explorer.

Actual:
It doesn't auto-refresh the Redis Cache node, which lead that the new created Redis Cache won't show in the explorer until you refresh the Redis Cache node manually.
@jdneo

**Comment by adashen** [comment]
@davidliangze fixed please verify in the new build

**Comment by davidliangze** [comment]
Test passed in the latest daily build.

OS: Windows 10 Enterprise x64 ENU
IDE: Eclipse Neon/ IntelliJ 2017.1.2
Plugin Version:
WindowsAzurePlugin4EJ.develop.daily.4.05-17-2017.zip
azure-toolkit-for-intellij.2017.develop.daily.4.05-17-2017.zip
