### ISSUE TITLE
[IntelliJ][2020.1]No response after click on Submit Spark Application in context menu.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#4410]
**Build:** https://dev.azure.com/mseng/VSJava/_build/results?buildId=12223546&view=artifacts&type=publishedArtifacts
**IntelliJ Version:** 2020.1
**OS:** Windows/Mac/Linux

**Repro Steps:**

1. Install the above build.
2. Open or create a project.
3. Expand the Project->src->main->scala->sample
4. Right click on LogQuery
5. Select and click on Submit Spark Application
6. Check the results

**Result:** No response.
![image](https://user-images.githubusercontent.com/40199316/83010161-6e7e0c80-a04a-11ea-838d-a6b48c586f3c.png)
**Expect**: Should show the Edit Spark Job submission run configuration dialog.

**Comment by t-rufang** [comment]
This issue reproes with IntelliJ 2020.1 on both Windows and Mac

**Comment by t-rufang** [comment]
Fixed in #4418

**Comment by v-xiaocw** [comment]
Verified and fixed in build azure-toolkit-for-intellij-2020.1.develop.12240149.05-29-2020
