### ISSUE TITLE
[IntelliJ][2020.1]When selecting any default Spark application type, "Run and Debug" in the context menu still does not display any type.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#4411]
Build: https://dev.azure.com/mseng/VSJava/_build/results?buildId=12223546&view=artifacts&type=publishedArtifacts
IntelliJ Version: 2020.1
OS: Windows/Mac/Linux

Repro Steps:

1. Install the above build.
2. Open or create a project.
3. Expand the Project->src->main->scala->sample
4. Right click on LogQuery
5. Selecting any default Spark application type
6. Check the Run and Debug in context menu

Result: "Run and Debug" in the context menu still does not display any type. 
![image](https://user-images.githubusercontent.com/40199316/83014376-2dd5c180-a051-11ea-92ba-aa79d5235366.png)
Expect: Run and debug should show the corresponding default application type. As shown below:
![image](https://user-images.githubusercontent.com/40199316/83015095-7b9ef980-a052-11ea-95a6-73dd7587265b.png)

**Comment by t-rufang** [comment]
@v-lanjli When you click "Run 'LogQuery'", which config exactly will the application apply?

**Comment by t-rufang** [comment]
Not repro in IntelliJ 2020.1 on Mac. @v-lanjli Please help verify.

**Comment by t-rufang** [comment]
@v-lanjli has helped verified the fix and it doesn't repro now.
