### ISSUE TITLE
[IntelliJ][2020.1]In the executed run configuration, the upload path will not change with the cluster bind different subscription gen2 account during the switching of the cluster.

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#4412]
Build: https://dev.azure.com/mseng/VSJava/_build/results?buildId=12223546&view=artifacts&type=publishedArtifacts
IntelliJ Version: 2020.1
OS: Windows/Mac/Linux

Repro Steps:

1.Install the above build.
2.Open or create a project.
3.Create a new config with a cluster,eg.lanjuntest0311
4.Save config and click Apply and OK.
5.Click the Remote Run button
6.Open run configuration again, switch cluster and select any gen2 cluster.

Result: When I switch to gen2, it freezes and the upload path does not change.
![2020052709](https://user-images.githubusercontent.com/43333874/83043432-bde71d00-9ff7-11ea-8f0e-3b530cd49501.gif)
7.If you close the config dialog after clicking on apply, reopen config, the upload path will become like this:
![image](https://user-images.githubusercontent.com/43333874/83043670-01418b80-9ff8-11ea-8547-72d7acf052d8.png)

**Comment by t-rufang** [comment]
Another scenario:
1. Save a gen2 config, apply and ok, close the config dialog
2. Re-open the config dialog, the upload path field displays something like "<No selected cluster>".

**Comment by wezhang** [comment]
This is a corner case that occurs ony when the storage account is located at different subscription than cluster.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738858
