### ISSUE TITLE
java.lang.RuntimeException: Can't get progess

### ISSUE THREAD

**Issue by EricZhangzf** [microsoft/azure-tools-for-java#4415]
#### Environment
- OS : Mac
- Plugins version: 3.37.0
- IDE version: IC2020.1-jre11

#### Details:
Show this exception message usually.
![image](https://user-images.githubusercontent.com/44559777/83107420-d6872e00-a0f0-11ea-9f80-407fcaafc4b2.png)
[log.txt](https://github.com/microsoft/azure-tools-for-java/files/4693689/log.txt)

**Comment by Flanker32** [comment]
Can not reproduced later, feel free to reopen it when you meet the same issue
