### ISSUE TITLE
Redis explorer properties has format issue

### ISSUE THREAD

**Issue by EricZhangzf** [microsoft/azure-tools-for-java#4416]
#### Environment:
- OS：Win/Mac
- Plugin Version: 3.37.0
- IDE Version: IC2020.1-jre11 /IU2019.3-jre11

#### Repro steps:
1. Right click your redis db to select Show Properties

#### Result:
The url and type lack some data in redis explorer
![image](https://user-images.githubusercontent.com/44559777/83108046-ccb1fa80-a0f1-11ea-9062-1792a7df88fb.png)

**Comment by ZhengJun003** [comment]
duplicate to [#1651](https://github.com/microsoft/azure-tools-for-java/issues/1651)
