### ISSUE TITLE
[Intellij][Spark][RunConf][Synapse] The numexecutors setting in run configuration didn't take effects

### ISSUE THREAD

**Issue by wezhang** [microsoft/azure-tools-for-java#4419]
Reported by Priyanka:
 
![image](https://user-images.githubusercontent.com/7385667/83225486-76f15700-a1b2-11ea-8c8d-26a4c478a937.png)

The numexecutors should be 2, but the log says:

azuretool: The Spark Batch job has been submitted to Synapse Spark poolhttps://prgomatamissinglogs.dev.azuresynapse-dogfood.net/livyApi/versions/2019-11-01-preview/sparkPools/messwithvm/batches with the following parameters: {"className":"org.apache.spark.sparkcruise.SparkCruiseApp","name":"sparkcruiseapp","file":"abfs://.../default_artifact.jar","driverMemory":"4G","driverCores":1,"numExecutors":5,"executorCores":1,"executorMemory":"4G"}

**Comment by jingyanjingyan** [comment]
2019.3 build0608 + System windows
2020.1 build0529 + System windows/mac

Repro Steps:
1. Create a new synapse configuration, edit the "numExecutors" from 5 to 2
2. Close the config window by clicking x (key step)
3. Submit then check the log

Result:
It says "numExecutors" = 5.
![IntelliJ4419](https://user-images.githubusercontent.com/36756024/83996342-787b0600-a98e-11ea-9f0a-b83759cab637.gif)

**Comment by v-lanjli** [comment]
Verified and fixed this issue in this [build](https://dev.azure.com/mseng/VSJava/_build/results?buildId=12323080&view=artifacts&type=publishedArtifacts)

Closed this issue~
