### ISSUE TITLE
[Eclipse+IntelliJ] Using the C5 basic and C5 standard pricing tier to create the redis cache failed

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#443]
[Eclipse+IntelliJ2017+IntelliJ2016]

Repro steps:
Create a redis cache and Pricing tier choose C5 Basic or C5 Standard
Click OK , then a no content error dialog occured.
![image](https://cloud.githubusercontent.com/assets/22470312/26094389/6ae9a136-3a4c-11e7-977a-672c0cf158eb.png)

**(A Redis cache with the above configuration can be created successfully on the portal)**
@jdneo

**Comment by adashen** [comment]
@davidliangze Please help to verify when the build is ready

**Comment by davidliangze** [comment]
Test passed in the latest build.

OS: Windows 10 Enterprise x64 ENU
IDE: Eclipse Neon/ IntelliJ 2017.1.2
Plugin Version: 
WindowsAzurePlugin4EJ.develop.52.05-18-2017.zip
azure-toolkit-for-intellij.2017.develop.52.05-18-2017.zip
