### ISSUE TITLE
[IntelliJ] When the upload path is invalid, message need update

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#4433]
Build: 2019.3 build 0608; 2020.1 build 0529
System: windows/mac

Repro Steps:
1. Open a project, 
2. Right click on "LogQuery", set default spark application type to “Apache spark on HDInsight"
3. Right click on "LogQuery", select "Submit Apache spark application"
3. Enter a gen2 cluster, upload path always display with < No selected cluster >, 

Result:
the warning message in config dialog missing " < ".
![image](https://user-images.githubusercontent.com/36756024/83999813-132b1300-a996-11ea-98d1-fd4fa7bb4ca1.png)

**Comment by wezhang** [comment]
`catestgen2eastus` storage account is gone

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738856
