### ISSUE TITLE
[IntelliJ][Spark on Cosmos] Open the Notebook in the right-click menu and display "This site can't be reached".

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#4436]
Build: https://dev.azure.com/mseng/VSJava/_build/results?buildId=12323080&view=artifacts&type=publishedArtifacts
IntelliJ Version: 2019.3/2020.1
OS: Windows/Mac/Linux

Repro Steps:

1. Install the above build
2. Open IntelliJ and sign in to Azure
3. Right click on "Apache Spark on Cosmos" in Azure Explorer
4. Select the "Open Notebook"
5. Check the results

Results: The opened webpage displays "This site can't be reached".
![image](https://user-images.githubusercontent.com/40199316/84242590-9d5cae00-ab33-11ea-956c-d7aad8cbeacd.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738857
