### ISSUE TITLE
Can execute run with wrong parameters and empty subs in dialog

### ISSUE THREAD

**Issue by pl07** [microsoft/azure-tools-for-java#4442]
### Environment:
 - OS: Win
 - Plugins Version: Azure java toolkit for IntelliJ: 3.37.0
 - IDE Version: IU2020.1.1 - jre11
### Repro steps:
1. Right click project -> Azure -> Push image
2. Fill in blank with right format
![image](https://user-images.githubusercontent.com/46642771/84364945-5c33cf00-ac03-11ea-954b-62a386f6254d.png)

3. Apply and run
#### Push image:
Can excute run, build image and error when push to acr

#### Run on web app for containers
Same repro steps as Push image, but sign in with no-subs  account
![image](https://user-images.githubusercontent.com/46642771/84365093-88e7e680-ac03-11ea-8c3d-e9b2b5d2ca4c.png)
It can execute run, build image and error when push to acr

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738759

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
