### ISSUE TITLE
Pop up no subscription error window twice

### ISSUE THREAD

**Issue by pl07** [microsoft/azure-tools-for-java#4443]
### Environment:
 - OS: Win
 - Plugins Version: Azure java toolkit for IntelliJ: 3.37.0
 - IDE Version: IU2020.1.1 - jre11
#### Ecilpse:
1. Sign in with a no-subs account
2. In azure explorer, new a docker host
#### Intellij:
1. Sign in with a no-subs account
2. In azure explorer, new a docker host/ refresh docker host / publish as docker container

#### Eclipse
![image](https://user-images.githubusercontent.com/46642771/84365805-92258300-ac04-11ea-8eb8-286495accd55.png)
#### Intellij
Click ok and the window pop up again
![image](https://user-images.githubusercontent.com/46642771/84365888-abc6ca80-ac04-11ea-9df3-6d793005e028.png)

Or after click ok in below window, pop the above window twice
![image](https://user-images.githubusercontent.com/46642771/84366250-255eb880-ac05-11ea-82ed-8e88aa52004c.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738763

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
