### ISSUE TITLE
ARM Editor with autocomplete

### ISSUE THREAD

**Issue by angelcervera** [microsoft/azure-tools-for-java#4451]
I edit ARM templates using *Visual Code* because there is autocomplete, templates, etc.
It should be not difficult to do the same for Idea.
Is this feature in the roadmap?

Regards.

**Comment by angelcervera** [comment]
There is partial autocomplete functionality, but it is so slow and some time is not accurate. For example, autocomplete for apiVersion usually does not contain the right values.

**Comment by andxu** [comment]
@angelcervera, what do you mean  by "here is partial autocomplete functionality, but it is so slow and some time is not accurate", are you talking about vscode or intellij? for intellij, the roadmap in the nearest half year, there is no to support ARM templates. For vscode, I think it might be easier, see the [vscode-kubernetes-plugin](https://marketplace.visualstudio.com/items?itemName=ms-kubernetes-tools.vscode-kubernetes-tools), the auto completion of kubernetes part was implemented by me(https://github.com/redhat-developer/yaml-language-server/commits?author=andxu)

**Comment by yucwan** [comment]
Hi @angelcervera, the feature is in our backlog but not in the plan for next semester. If you are using VS Code as well, you can find full authoring experience there for now. Thank you for requesting though, let's keep this issue to collect thumb ups for future prioritization.
