### ISSUE TITLE
Can't skip creating application insights while creating new function app

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-tools-for-java#4452]
### Environment:

- OS: Win 10/Mac 10.15.4
- IDE: IU19.3 - jre11/IU20.1-jre11
- Plugins Version: Azure java toolkits for IntelliJ 3.38.0

### Repro Steps：

1. Create a function project
2. Add azure function deploy configurations
3. Click `Create Function App...` and select `No` for `Enable Application Insights`
4. Deploy function app

### Actual result:
![image](https://user-images.githubusercontent.com/41051257/84721847-349e8700-afb4-11ea-9fe0-ec625326c697.png)

**Comment by EricZhangzf** [comment]
Test Pass
