### ISSUE TITLE
Cannot refresh after switch app properties window  

### ISSUE THREAD

**Issue by pl07** [microsoft/azure-tools-for-java#4454]
### Environment:
 - OS: Win 10/Mac 10.15.4
 - IDE: IU19.3 - jre11/IU20.1-jre11
 - Plugins Version: Azure java toolkits for IntelliJ 3.38.0
### Repro Steps：
1. Deploy two apps to azure spring cloud
2. In azure explorer, right click two apps -> Show Properties
3. Switch to the first app properties window
### Actual result:
It cannot refresh to the right page
![image](https://user-images.githubusercontent.com/46642771/84734274-1300c800-afd3-11ea-9440-c3cdf64d38f2.png)

**Comment by EricZhangzf** [comment]
Test Pass
