### ISSUE TITLE
[IntelliJ] Azure toolkit- Can't select tenant at sign-in

### ISSUE THREAD

**Issue by munishm** [microsoft/azure-tools-for-java#4456]
Issue: When working with multiple tenants  Azure toolkit plugin directs to default login and I couldn't find a way to set another tenant ID while configuring the plugin or after?
Sign-in it doesn't show an option to select a tenant or any setting which allow me to add a tenant.

On probable solution could be to use the service principal but device support should be available for seamless integration. If this is available and I missed it, Please let me know and we can improve the documentation as well.

**Comment by andxu** [comment]
@munishm, we have a plan to improve login experience this sprint(3.39.0), we might be a little short of time to create UI to support tenant, we can provide some workaround way of specifying tenantId.
