### ISSUE TITLE
Only showing Signin in STS 

### ISSUE THREAD

**Issue by georgethms10** [microsoft/azure-tools-for-java#4489]
Azure toolkit for STS is only showing the Sign in button , publish as webapp and all are not present. 

After sign in using Azure CLI i can see the subscription and all but i cant publish my webapp , what is the solution .

<img width="472" alt="Screenshot 2020-07-01 at 12 24 09 PM" src="https://user-images.githubusercontent.com/6296111/86242424-56a62500-bbc2-11ea-8ef4-630a83d16b13.png">

**Comment by andxu** [comment]
Currently we are not supporting STS, if you are using java web app, the suggest IDE will be intellij ( which we spend most of our time), but we might re-think of STS since we now are on boarding new Azure Spring Cloud services, I will add your request in the backlog and review it periodically.
