### ISSUE TITLE
[IntelliJ][ReportedByUser] Customer Issues

### ISSUE THREAD

**Issue by sum-coderepo** [microsoft/azure-tools-for-java#4494]
#### Setup

IntelliJ build version: 2020.1.2 IC-201.7846.76
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.39.0-2020.1

####  Describe the bug

Intellij keeps asking to signin in a loop while connecting to Azure Microsoft.visualstudio

![image](https://user-images.githubusercontent.com/11211336/86541384-14664600-bf2a-11ea-8b01-885682f073ad.png)

**Comment by andxu** [comment]
Hi @sum-coderepo, can you login azure through azure cli: `az login` ? If so, the newest version of intellij plugin has supported azure cli login
![image](https://user-images.githubusercontent.com/17075863/86872968-f65a3a80-c10f-11ea-9e0d-53c47c67163f.png)
