### ISSUE TITLE
Would be helpful to see more information about VM during creation wizard.

### ISSUE THREAD

**Issue by hovsepm** [microsoft/azure-tools-for-java#45]
during VM creation wizard on Machine Settings page I can select from a drop-down list VM size but the list does not provide any hint what is the actual VM. e.g. if I do not remember by heart what is the difference between Basic_A0 and Standard_F1S I'll have to go to browser google it or ,even worse, login to portal try to create VM there to get the list with descriptions. There is a free space on the right of the combo-box that could be used to print out the information about the VM that i'm going to create.

**Comment by martinsawicki** [comment]
nice feature idea for the future.

**Comment by Flanker32** [comment]
In the latest release, we added a pricing link to Azure virtual machine pricing page, where you could get configuration details for different VM sizes.
![image](https://user-images.githubusercontent.com/12445236/84471519-14bb4a80-acb8-11ea-8d6d-67355c1889a8.png)
