### ISSUE TITLE
Running Azure Function App locally in Intellij does not work

### ISSUE THREAD

**Issue by t-cezhan-msft** [microsoft/azure-tools-for-java#4502]
I'm trying to create an Azure Functions project using Intellij by using the Azure Toolkit for Intellij (version 3.39.0-2020.1), primarily by following the guide here: https://docs.microsoft.com/en-us/azure/developer/java/toolkit-for-intellij/quickstart-functions.

The creation of the HttpTrigger and TimerTrigger function app work perfectly fine, however when I try to run the function app locally the only output I see is "Func host start at port : 7071".

In addition, if I deploy the app onto Azure, I can see that the function does perform as expected (able to access function url, timer does trigger according to schedule).

**Comment by Flanker32** [comment]
@t-cezhan-msft Thanks a lot for your report, is the run process terminated after shown `Func host start at port : 7071` or the process hang there, could you please share a screen shot for it? Besides, could you please share your os infos and function core tools version?

**Comment by t-cezhan-msft** [comment]
Hi, the process does not terminate after it shows that output. I'm working on Windows 10, and the function core tools version I'm using is 2.7.2628.

<img width="986" alt="bug" src="https://user-images.githubusercontent.com/67927617/87570858-1644ad80-c67e-11ea-89a6-771977432939.PNG">

**Comment by Flanker32** [comment]
@t-cezhan-msft Thanks for your information, i tried to reproduce this issue but no luck, could you please try `func host start` in your target folder? which should be `${project_folder}\target\functions\${your_proejct_name}` , besides, could local run works with only `HTTPTrigger` or `TimerTrigger`

**Comment by t-cezhan-msft** [comment]
Hi, when I tried running the HTTPTrigger directly in cmd, it seemed to run fine, with the expected outputs as described in the website I linked earlier. However, running within Intellij still seems to hang.

**Comment by andxu** [comment]
there are some staging folder changes in next version, your issue might be related to the multiple program running on the same staging folder, please let us known whether the new release(will be released this week) can solve your problem.

**Comment by Flanker32** [comment]
@t-cezhan-msft Thanks a lot for your report and help, this issue should be fixed in the latest release, you may get the release notes [here](https://github.com/microsoft/azure-tools-for-java/releases/tag/azure-intellij-toolkit-v3.41.0), could you please upgrade to the latest version and try again?

**Comment by t-cezhan-msft** [comment]
Hi! It appears to work now. Thanks for your help!
