### ISSUE TITLE
Device login is not working

### ISSUE THREAD

**Issue by konjac** [microsoft/azure-tools-for-java#4504]
![image](https://user-images.githubusercontent.com/2101973/87560017-981fef80-c6ed-11ea-967b-c582da8ae3b4.png)

**Comment by andxu** [comment]
Hi @konjac, thanks for your finding,  would you mind tell us which Os are you using? linux or mac?

**Comment by konjac** [comment]
@andxu This is Win10.
But I now can't repro the issue after a system reboot. I think I can mark it as transient. I will reopen if reproducing.
