### ISSUE TITLE
Azure plugin is not compatible with intellij

### ISSUE THREAD

**Issue by arunan123** [microsoft/azure-tools-for-java#4522]
Today I got an IDE update and it throws error that Azure plugin is not compatible. I have to uninstall the Azure plugin to make that error go away.

**Comment by Nosbielc** [comment]
That's right version 2020.2. I have disable

**Comment by Flanker32** [comment]
@arunan123  @Nosbielc Thanks a lot for your report, we are working on the IntelliJ 2020.2 support but there are still some compatibility issues, i'll update here once the release done.

**Comment by t-rufang** [comment]
@arunan123  @Nosbielc  As a workaround, you can install IntelliJ 2020.1 at the same machine. You could use [Jetbrains toolbox](https://www.jetbrains.com/toolbox-app/) to help install and manage multiple versions intelliJ at one machine,

**Comment by Flanker32** [comment]
@arunan123 @Nosbielc  @debinaik Thank you all for your support, we have released the [Azure Toolkit for IntelliJ v3.40.0](https://github.com/microsoft/azure-tools-for-java/releases/tag/azure-intellij-toolkit-v3.40.0) which support IntelliJ 2020.2, you may get the release [here](https://plugins.jetbrains.com/plugin/8053-azure-toolkit-for-intellij/versions/stable/93620).
