### ISSUE TITLE
Azure Toolkit Incomaptible

### ISSUE THREAD

**Issue by debinaik** [microsoft/azure-tools-for-java#4524]
Hi Team,

I am using Intellij Version 2020.2 version. Today I have updated the patch. Post update , "Azure Toolkit incompatible" issue encountered ? Please find the attached error message for reference . 

When this issue will be fixed ? Do I need to use previud version of IntelliJ to work with"azure toolkit". 

[

![Azure-Toolkit-error](https://user-images.githubusercontent.com/28619627/88933542-2cb55080-d29d-11ea-888d-3d3bfdda97f0.png)
](url)

**Comment by Flanker32** [comment]
@debinaik Thanks for your report, we are working on the IntelliJ 2020.2 support but there are still some compatibility issues, please track the issue here https://github.com/microsoft/azure-tools-for-java/issues/4522
