### ISSUE TITLE
Cloud Shell API - The client with application Id '04b07795-8ddb-461a-bbee-02f9e1bf7b46' is not permitted to access this API

### ISSUE THREAD

**Issue by maartenba** [microsoft/azure-tools-for-java#4529]
Similar to #2101

Using the `AzureCliAzureManager`, crafting a request to Azure Cloud Shell:

```
GET https://management.azure.com/providers/Microsoft.Portal/userSettings/cloudconsole?api-version=2017-12-01-preview
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer xxxxxxxxx
```

Getting the following error response:

```
{
  "error": {
    "code": "ClientNotAllowed",
    "message": "The client with application Id '04b07795-8ddb-461a-bbee-02f9e1bf7b46' is not permitted to access this API."
  }
}
```

Just like in #2101, can access to the Cloud Shell API's be provided for client id/application id `04b07795-8ddb-461a-bbee-02f9e1bf7b46` (Azure CLI)?

**Comment by andxu** [comment]
hi @maartenba, could you please let me known the details:
Are you complaining about the azure credential cannot be got in cloud shell environment?
How can user start a intellij idea in a cloud shell?

**Comment by maartenba** [comment]
Hi @andxu, it's about consuming cloud shell from inside the IDE, using Azure CLI credentials.

In an IDE action, I want to make a request to `{url}/providers/Microsoft.Portal/consoles/default?api-version=2017-12-01-preview`, which is currently not possible with the Azure CLI credential.

It works with Device Login credential, which uses a different app is. My guess is the Azure CLI app is needs to be allowed to access cloud shell in the MS Azure AD.

**Comment by maartenba** [comment]
Any chance this can be reopened?

**Comment by andxu** [comment]
@maartenba , do you mean the plugin for Rider are encountering errors when calling api for operating Cloud Shell?

**Comment by maartenba** [comment]
Yes indeed

**Comment by maartenba** [comment]
This seems to be fixed now on the portal side 🤷‍♀️
