### ISSUE TITLE
[Intellij] Can't list webapps after upgrading to 3.41

### ISSUE THREAD

**Issue by yucwan** [microsoft/azure-tools-for-java#4576]
![image](https://user-images.githubusercontent.com/49381248/91396385-c86eb800-e86d-11ea-8c2a-f70467ff5aaa.png)
 
not working in explorer as well.

**Comment by Flanker32** [comment]
Fixed in IntelliJ Toolkit 3.41.1, you may get it [here](https://plugins.jetbrains.com/plugin/8053-azure-toolkit-for-intellij)
