### ISSUE TITLE
[IntelliJ][ReportedByUser] Push image either wrong name for option or not working properly

### ISSUE THREAD

**Issue by haris-zynka** [microsoft/azure-tools-for-java#4580]
#### Setup

IntelliJ build version: 2020.2.1 IU-202.6948.69
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.8
Plugin version: 3.41.1-2020.2

####  Describe the bug

Trying to push image to the Azure. However it's still requested to have .war file: "Invalid Data: A web archive (.war) artifact has not been configured.". This was from before so I disabled plugin and didn't use it a while. Now I tried again and it still has the same issue. I have images already built, just wanted to have simple tool to push it on button click or shortcut. I'm not sure what is the actual purpose of this option but it's named "Push Image" so I assumed it will be just that. Maybe it want's to build Docker file + build image and then push it. Not sure but I'm reporting it as a bug as name of the feature is "Push Image".
####  To Reproduce

1. Install Azure tools
2. Open Azure Explorer
3. Open Container Registries in Azure Explorer
4. Right click Container Registry you want to push image to
5. Choose Push Image
6. Fill in info
At this step Artifact field is required which is confusing as to why. Image was build already I just need to push it, why would I need .war. A lot of us use .jar nowadays.

#### Exception or Stack Trace

Add the exception log and stack trace if available.

#### Screenshots

Add screenshots to help explain your problem if available.

**Comment by Flanker32** [comment]
@haris-zynka  Thanks for your report and sorry for the trouble, the push image feature will help you build the image and push it, and for now we didn't support push the existing images, before we support the feature, please use docker command as workaround, you may refer this document for [details](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-get-started-docker-cli).
