### ISSUE TITLE
Popup login doesn't mention Intellij

### ISSUE THREAD

**Issue by elhoo** [microsoft/azure-tools-for-java#4585]
I occasionally get this popup on my computer. Since I do not have Visual Studio installed on my computer I thought it was some kind of malware etc.... after a while I got to the conclusion that it must be connected to the Intellij plugin.

Please add some more information from which application this popup origins from.

![image](https://user-images.githubusercontent.com/1180446/92381179-a77a5280-f10a-11ea-9e6a-35db448b8b85.png)

Thanks!

**Comment by andxu** [comment]
Hi @elhoo, I am curious about how you can get a pop up windows like that, in my machine, it seems like this
![image](https://user-images.githubusercontent.com/17075863/92552877-3666a680-f294-11ea-94ab-a8378ac71775.png). Are you signing in from azure toolkit plugin?

**Comment by elhoo** [comment]
Hi,
I have no idea. Probably there is a way to check which application that did open the windows but nothing I know about..

When starting to think about it more - my popup could also be from the Windows Git Credential.... but as I said - I do not know how to check.

**Comment by andxu** [comment]
hi @elhoo, do you sign in at this place and meet the pop up window?
![image](https://user-images.githubusercontent.com/17075863/92849478-f4696c00-f41d-11ea-8f1c-851f318aff90.png)

**Comment by elhoo** [comment]
Hi,

When clicking on that I got:
![image](https://user-images.githubusercontent.com/1180446/92870743-79478c00-f404-11ea-88f8-f4af1bfcbf64.png)

But then I didn't get any login window.

I guess the popup was not from this plugin - sorry about the trouble, you can close this.
