### ISSUE TITLE
[IntelliJ][Spark] Spark job configuration is overridden by blob uploading seeting

### ISSUE THREAD

**Issue by wezhang** [microsoft/azure-tools-for-java#4601]
Plugin version: 3.42

When selects Blob uploading and sets Job Configuration as below:
![image](https://user-images.githubusercontent.com/7385667/93728810-45364d00-fbf4-11ea-852f-d1cb1cd7fc35.png)

But only has the following conf in submission:

    "conf": {
        "spark.hadoop.fs.azure.account.key.xxxx.blob.core.windows.net": "..."
    },

Other spark.yarn... configurations are missing

**Comment by wezhang** [comment]
@v-lanjli @v-xiaocw

**Comment by t-rufang** [comment]
@v-lanjli This bug is fixed in #4603. Please help verify the fix.

**Comment by v-lanjli** [comment]
Verified and fixed. Closed this issue.
