### ISSUE TITLE
 eclipse-inst-jre-win64.exe hangs after it starts deploying in Windows 10

### ISSUE THREAD

**Issue by SanjayaKumarS** [microsoft/azure-tools-for-java#4619]
while installing Azure Toolkit for Eclipse, the installer - eclipse-inst-jre-win64.exe hangs after it starts deploying in Windows 10
Following software details for Java8 is being used
Java JDK : zulu8.48.0.53-ca-jdk8.0.265-win_x64
Java JRE : zulu8.48.0.53-ca-jre8.0.265-win_x64

**Comment by andxu** [comment]
hi @SanjayaKumarS could you please let me known the result of the following command?
```
java -version
```

**Comment by SanjayaKumarS** [comment]
Hi @andxu 

'java -version' command displays current Java version with the build type as well as the Java(TM) SE Runtime Environment installed in your machine,

**Comment by andxu** [comment]
Hi @SanjayaKumarS , thank you for your response,  the jdk installed on your machine is oracle java, not zulu jdk, you might need to report it to eclipse installer.
