### ISSUE TITLE
Azure Toolkit for Intellij plugin incorrectly shows “No subscriptions” after Azure device logon

### ISSUE THREAD

**Issue by antbewes** [microsoft/azure-tools-for-java#4648]
I have 2 Azure accounts both have subscription which I can see via portal.azure.com but when I login via the plugin on Intellij it claims I have no subscriptions which is blocking my use of the toolkit.

I'm using Intellij Ultimate 2019.3.5

(also raised here: https://stackoverflow.com/questions/64332550/azure-toolkit-for-intellij-plugin-incorrectly-shows-no-subscriptions-after-azu)

**Comment by andxu** [comment]
Can you upgrade your intellij to 2020.1 or 2020.2 and install the latest plugin version: v3.43.0, and try to login using azure cli (use `az login`)? If the issue are still occurring, please let us know, thanks.
