### ISSUE TITLE
[IntelliJ2017+2016]Virtual Machine Workflow-Repeated display issue

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#465]
OS: MAC

There are two same VM in VM list after creating VM. Refresh the list , one of them will disappear.
![image](https://cloud.githubusercontent.com/assets/22470312/26194788/22738e5c-3bec-11e7-9bfe-a415b37bf120.png)

**Comment by bsaby** [comment]
Also repro in released build.

**Comment by adashen** [comment]
mooncake only or not?

**Comment by bsaby** [comment]
Also repro in global.

**Comment by sallyur** [comment]
Also repro in windows, using build develop daily 427.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738800

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
