### ISSUE TITLE
[IntelliJ2017+2016]Virtual Machine Workflow: the status of failed vm is displayed incorrectly

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#466]
OS:MAC

The icon doesn’t change to failed state if creating VM failed.
![image](https://cloud.githubusercontent.com/assets/22470312/26194958/ba30027a-3bec-11e7-9e72-cda4f0b8d7f5.png)

**Comment by bsaby** [comment]
Also repro in released build.

**Comment by bsaby** [comment]
Also repro in global.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738799

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
