### ISSUE TITLE
[IntelliJ][ReportedByUser] Customer Issues

### ISSUE THREAD

**Issue by gjeevanm** [microsoft/azure-tools-for-java#4664]
#### Setup

IntelliJ build version: 2019.1.4 IU-191.8026.42
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_212-release
Plugin version: 3.28.0-2019.1

####  Describe the bug

Spark Cluster not found issue whenever login to azure which is happening with all version of IntelliJ Ide

#### Screenshots

![image](https://user-images.githubusercontent.com/8406964/96543046-25f91100-12c1-11eb-857f-c252585ac7e7.png)

**Comment by wezhang** [comment]
Thanks @gjeevanm ! I'd like to suggest upgrade to most recent version IntelliJ with our plugin and try again.
