### ISSUE TITLE
Crowded Context Menu

### ISSUE THREAD

**Issue by akaroml** [microsoft/azure-tools-for-java#4721]
![Screen Shot 2020-11-05 at 3 30 07 PM](https://user-images.githubusercontent.com/16755094/98210644-d6326f00-1f7b-11eb-9333-8d8182b122cf.png)

Try right click on the node in Azure Explorer, there are many items but lack proper grouping. Suggest that we group those entries in a more logical way.

**Comment by shenqianjin** [comment]
It's already resolved in 3.47.0 Edition. (Dec 2020).

**Comment by shenqianjin** [comment]
![image](https://user-images.githubusercontent.com/19339116/104146901-54d9db80-5407-11eb-8534-244678fdf3eb.png)
