### ISSUE TITLE
Inconsistent Input Values when Switching to "More Settings"

### ISSUE THREAD

**Issue by akaroml** [microsoft/azure-tools-for-java#4722]
1. Change the default values in the initial view
![Screen Shot 2020-11-05 at 3 31 42 PM](https://user-images.githubusercontent.com/16755094/98210893-3e815080-1f7c-11eb-9be2-9353e3d14a2c.png)

2. Select "More Settings" and you see those two values were not the same in the new view
![Screen Shot 2020-11-05 at 3 33 59 PM](https://user-images.githubusercontent.com/16755094/98210999-640e5a00-1f7c-11eb-9a63-e5323bcbb412.png)

Both views should share the same set of values specified by the users.

**Comment by andxu** [comment]
Fixed, close this issue.
