### ISSUE TITLE
Wrong initial focus in various dialogs (resource creation)

### ISSUE THREAD

**Issue by akaroml** [microsoft/azure-tools-for-java#4724]
Check out those dialogs that are presented when creating a web app. None of them has the right focus when shown. This makes super inconvenient for the users and they have to click using the mouse to start typing.
![Screen Shot 2020-11-05 at 3 42 20 PM](https://user-images.githubusercontent.com/16755094/98211829-9e2c2b80-1f7d-11eb-9533-655e27b236b9.png)
![Screen Shot 2020-11-05 at 3 42 36 PM](https://user-images.githubusercontent.com/16755094/98211836-a1271c00-1f7d-11eb-8b84-42245d1fc591.png)
![Screen Shot 2020-11-05 at 3 42 47 PM](https://user-images.githubusercontent.com/16755094/98211843-a3897600-1f7d-11eb-82a9-c31d1817a45f.png)

The picture below demonstrates the expected state:
![Screen Shot 2020-11-05 at 3 42 27 PM](https://user-images.githubusercontent.com/16755094/98212004-ea776b80-1f7d-11eb-8aa7-0249d8e023f6.png)
![Screen Shot 2020-11-05 at 3 42 40 PM](https://user-images.githubusercontent.com/16755094/98212006-ecd9c580-1f7d-11eb-9054-d28f76dff413.png)
![Screen Shot 2020-11-05 at 3 42 53 PM](https://user-images.githubusercontent.com/16755094/98212012-efd4b600-1f7d-11eb-97c5-181738d16a25.png)

**Comment by andxu** [comment]
Categorized in "Focus enhance in Azure components"

**Comment by wangmingliang-ms** [comment]
this feature has been added since v3.63.0.
