### ISSUE TITLE
Misaligned label in Web App property view

### ISSUE THREAD

**Issue by akaroml** [microsoft/azure-tools-for-java#4725]
![Screen Shot 2020-11-05 at 3 47 34 PM](https://user-images.githubusercontent.com/16755094/98212286-5063f300-1f7e-11eb-9b6d-4fa30a71734a.png)

The URL is misaligned compared to other fields in the same column.

**Comment by andxu** [comment]
Rephrase this issue as categorized as "Property view UI enhancement"
