### ISSUE TITLE
Confusing workflow of "Get Publish Profile"

### ISSUE THREAD

**Issue by akaroml** [microsoft/azure-tools-for-java#4726]
After clicking the "Get Publish Profile" button, a file explorer is presented without any extra hint
![Screen Shot 2020-11-05 at 3 49 25 PM](https://user-images.githubusercontent.com/16755094/98212528-afc20300-1f7e-11eb-8948-b7b7d874874a.png)
![Screen Shot 2020-11-05 at 3 49 52 PM](https://user-images.githubusercontent.com/16755094/98212534-b18bc680-1f7e-11eb-8be5-7e5087939c85.png)

We can do the following:
1. Change the button text to "Download Publish Profile" to hint that you need to specify a location to save the file
2. In the file explorer, change the button text from "Open" to "Save" to explicitly tell the users what they are about to do.

**Comment by wangmingliang-ms** [comment]
> Change the button text to "Download Publish Profile" to hint that you need to specify a location to save the file

it's also `Get Publish Profile` in Azure Portal, so I tend to keep it as it is, but I will add a download icon on the button to reduce ambiguity, same as that in Azure Portal.
![image](https://user-images.githubusercontent.com/69189193/191900626-ca485590-94a8-48e3-8dd4-e85ed63e7461.png)
![image](https://user-images.githubusercontent.com/69189193/191900725-fa1640d4-f3bf-4af0-999f-7be8a890313f.png)

> In the file explorer, change the button text from "Open" to "Save" to explicitly tell the users what they are about to do.

IntelliJ doesn't expose such API to set the text.
