### ISSUE TITLE
Web App - SSH not working

### ISSUE THREAD

**Issue by akaroml** [microsoft/azure-tools-for-java#4727]
Try the following:
![Screen Shot 2020-11-05 at 4 01 24 PM](https://user-images.githubusercontent.com/16755094/98213570-388d6e80-1f80-11eb-9fc6-2f24fb1eb323.png)

And got this:
![Screen Shot 2020-11-05 at 4 01 12 PM](https://user-images.githubusercontent.com/16755094/98213566-362b1480-1f80-11eb-8c48-5026426cd5e2.png)

But actually, azure cli is installed and properly running:
![Screen Shot 2020-11-05 at 4 03 10 PM](https://user-images.githubusercontent.com/16755094/98213726-74283880-1f80-11eb-8c68-6010ff2c7fb4.png)

And the Azure Toolkit login is done by consuming Azure CLI logins. So they should be already using the same account.

**Comment by shenqianjin** [comment]
@akaroml Hi Rome, Thank for your testing and feedback.

Sorry to tell that we can reproduce this error according to what you described.

Can you please try to execute 'az account show' with azure-cli command and share with us the log of console ?

btw, please note that the dialog will come out in the below three cases:
1. Azure CLI is not installed.
2. There is no account signed-in Azure CLI.
3. The account signed-in Azure CLI has no permission to access your web app (maybe different account with what logned-in in your Intellij).

**Comment by akaroml** [comment]
I ran `az account show` from the terminal in IntelliJ and the output was the details of my default subscription. So it proves:
1. Azure CLI is installed properly
2. I logged in properly
3. I have a valid subscription

But the webapp I was trying to SSH to was not in the default subscription. According to our discussion, that is not the problem. Please keep investigating.

**Comment by andxu** [comment]
Hi @akaroml , we have implemented a Pure java version of ssh tunnel, can you try it again?
![image](https://user-images.githubusercontent.com/17075863/144198363-c4274d43-7c82-4d78-b3fc-ec3af1eecb4e.png)
