### ISSUE TITLE
Low fidelity icons

### ISSUE THREAD

**Issue by akaroml** [microsoft/azure-tools-for-java#4729]
![Screen Shot 2020-11-05 at 4 11 09 PM](https://user-images.githubusercontent.com/16755094/98214531-979fb300-1f81-11eb-959e-1f8d8e474dd3.png)

This is ugly.

**Comment by andxu** [comment]
Fixed
![image](https://user-images.githubusercontent.com/17075863/144190589-525af05e-b5fd-4198-b594-62ac7bc3adc6.png)
