### ISSUE TITLE
[Intellij] Integrate custom data source to enable MFA AD token based login for azure managed databases

### ISSUE THREAD

**Issue by mocleiri** [microsoft/azure-tools-for-java#4752]
Hello, 

I have code that allows users of intellij to login using the database to Azure Managed Instance SQL-Server using active directory identities; including those with MFA enabled.

I have plans to refactor to also handle the new Azure Managed Postgresql servers and potentially others.

My approach is to create a custom jdbc driver that bundles the msal4j token acquistion logic with the underlying database driver:
https://github.com/mocleiri/sharepoint-online-oauth-client-credentials

I want to integrate this code into intellij to make it easier for end users to use.  Does this project have a way to adjust the drivers that appear in datagrip?

I would like to publish my bundled drivers via maven central and then have a screen within intellij where they can be automatically downloaded like any other driver.

![postgresql - download driver](https://user-images.githubusercontent.com/250942/99479792-dab83980-2924-11eb-8508-a5d8e79caac5.png)

I found out some API extension points that can be used for this purpose:

- https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000690844-Is-it-possible-to-create-a-data-source-via-an-API-

- https://intellij-support.jetbrains.com/hc/en-us/community/posts/207655685-Datagrip-plugin-SDK

Is integrating these drivers into this plugin an option or should I make my own intellij plugin?

**Comment by andxu** [comment]
Hi @mocleiri, in short to answer your questions: we welcome all kinds of contributions from community, you can start from branch develop and create PRs, additional notes would be:
you need to run mvn install at `Utils` folder and then run `./gradlew runIde` in `PluginsAndFeatures\azure-toolkit-for-intellij`

For PR, you need to make sure your new or updated java files pass the checkstyle(https://github.com/andxu/java-checkstyle/tree/master/checkstyle)

**Comment by andxu** [comment]
You can also attach a gif indicating how your UI would look like in a PR. We are integrating mysql recently, which should be code ready in about two weeks.

**Comment by andxu** [comment]
See an example of sql server at : https://github.com/JetBrains/azure-tools-for-intellij/pull/106/files#diff-89f9b67bee9d8e9b4c05970ce9fabae13410904cda5a8e0ff01ce08568f63225

**Comment by mocleiri** [comment]
@andxu thanks for the example it looks very useful.  I will try and integrate my code and then file a pull request.  Hopefully something I can put together over the holidays.

**Comment by mocleiri** [comment]
I just found out that the mssql-jdbc driver just implemented the token aqcuisition logic in the 9.1.1 preview driver: https://github.com/microsoft/mssql-jdbc/pull/1456

I just filed a feature request there to have them also add support for the device code flow which can be used to allow developers with MFA enabled accounts to login when debugging locally.

https://github.com/microsoft/mssql-jdbc/issues/1483

If that is accepted then there will be no need to integrate my wrapper driver for mssql.  

I will keep this ticket open for now because I may refactor my wrapper code to cater for the azure managed mysql and managed postgresql solutions.

But for MS SQL Server it won't be needed anymore.

**Comment by mocleiri** [comment]
It looks like 9.1.1 also handles MFA using _authentication=ActiveDirectoryInteractive_

Thank for the pointers on how to debug the plugin to add new features.

I'm not sure on ETA for the other types so will not keep this open.  I will file a pull request when I implement the wrapper layer for MySQL and PostgreSQL.
