### ISSUE TITLE
[Eclipse] Publish as Web App is not available in toolbar in login state.

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#478]
Not regression issue
Build used:  daily.5.05-18-2017.zip

Sometimes, Publish as Web App is not available in toolbar in login state.

![image](https://cloud.githubusercontent.com/assets/22470312/26236354/9047b0aa-3ca2-11e7-981b-f124b27e2782.png)

**Comment by jdneo** [comment]
Hi @bsaby . Please provide more information about this issue.

**Comment by bsaby** [comment]
Close it since this issue can repro in current Plugin version 3.11.0 in Eclipse.
