### ISSUE TITLE
[IntelliJ2017+IntelliJ2016] There is no smart search when choosing a location

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#479]
Not regression issue.
Build used: daily.5.05-18-2017.zip

Storage account workflow; VM workflow; 
There is no smart search when choosing a location.

![image](https://cloud.githubusercontent.com/assets/22470312/26237471/d8433c3a-3ca7-11e7-9b90-28a0a75327b4.png)

**Comment by andxu** [comment]
Smart search will not be that important given the region count is small.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738822

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
