### ISSUE TITLE
"Machine settings" tab during VM creation wizard should validate my input as I type

### ISSUE THREAD

**Issue by hovsepm** [Microsoft/azure-tools-for-java#48]
now it validates only on Next button click. In my case I tried to give "A1" name to VM and on next click it complained that I need to have at least 3 character name VM.

**Comment by hovsepm** [comment]
Same thing with password validation.

**Comment by martinsawicki** [comment]
not quite, in general we do not validate during typing. Maybe in the future we could revisit
