### ISSUE TITLE
[Eclipse/IntelliJ2017/IntelliJ2016]The deleted resource group still shows in the Existing resource group dropdown list.

### ISSUE THREAD

**Issue by davidliangze** [microsoft/azure-tools-for-java#480]
Repro Step:
1. Delete a existing resource group on Azure Portal.
![capture1](https://cloud.githubusercontent.com/assets/26756696/26237753/fd7112ce-3ca8-11e7-8a1d-9faa2cee7c9d.JPG)

2. In Azure Explorer, try to create new **Storage Account, Web App Service** or **Virtual Machine** with existing resource group. (DO NOT refresh the top node)

**Expected:**
The deleted resource group will NOT show in the dropdown list.

**Actual:**
The deleted resource group still shows in the Existing resource group dropdown list.
![capture2](https://cloud.githubusercontent.com/assets/26756696/26237922/94344384-3ca9-11e7-9d97-9ae8a26bd47e.JPG)
![capture3](https://cloud.githubusercontent.com/assets/26756696/26237931/99d95d56-3ca9-11e7-9ba0-5ed730b6d695.JPG)
![capture4](https://cloud.githubusercontent.com/assets/26756696/26237939/a2ad3bbe-3ca9-11e7-81a0-10621abd9605.JPG)

**Comment by andxu** [comment]
@davidliangze Test on latest version, the resource group in the option list will be updated after cancel and reopen the dialog, could you please verify if this issue is resolved?
