### ISSUE TITLE
Intellij Azure java remote debugging issue.

### ISSUE THREAD

**Issue by anoomicael** [microsoft/azure-tools-for-java#4808]
https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-maven-intellij

followed above link to set up Azure function program in Intellij. I am using Windows 10 and Intellij Idea 2020.2.4 Community Edition i am using.

When I start program in debug mode , execution not stopping at break point. Then I set up remote debugging getting below message
"Error running 'Remote Debugging': Unable to open debugger port (localhost:5009): java.net.ConnectException "Connection refused: connect" "

**Comment by Flanker32** [comment]
@anoomicael Thanks for your report, it seems that you are using a new version of function core tools which was not fully supported in IDE toolkit yet, so we didn't attach the debugger automatically, as a workaound, you may attach the debugger manually by click `Attach debugger` in console, we will fix this issue in next release.
![image](https://user-images.githubusercontent.com/12445236/102043443-5d8ec000-3e0f-11eb-987d-9a635df84d98.png)
