### ISSUE TITLE
[IntelliJ] Spring Cloud Deployment Configuration does not work for multi-module projects

### ISSUE THREAD

**Issue by xinyi-joffre** [microsoft/azure-tools-for-java#4822]
Currently, we have a multi-module project that uses an aggregator pom.xml. In order to compile and package all dependencies, the mvn package command needs to be executed at the aggregator level.

The IntelliJ plugin for Spring Cloud only allows us to specify a single artifact project, and then does not allow us to modify the build steps. Even if we modify the build step to remove the one that builds the single project, after I save and come back, it will be there again.

This means that we currently cannot use the Spring Cloud extension for deployment because the package step does not work for us.

One suggestion is to support two fields:

- Package target
- Artifact target

The first field will allow us to specify where to call package from
The second field will allow us to specify where to grab the final jar file

**Comment by andxu** [comment]
@xinyi-joffre, thanks for using our intellij plugin, we will consider your scenarios in later releases.

**Comment by andxu** [comment]
@xinyi-joffre , we now support select a jar to deploy:
![image](https://user-images.githubusercontent.com/17075863/144199988-e82a0ed3-56a1-43c0-8491-8aff98ec33c0.png)
can you try it on 3.56.0 and tell us whether this feature unblocks you?
