### ISSUE TITLE
[Spark-Debug] The Job configuration - Dynamic Configuraiton's component of Spark Debug Run Configuration editor only show '...'

### ISSUE THREAD

**Issue by wezhang** [Microsoft/azure-tools-for-java#485]
![image](https://cloud.githubusercontent.com/assets/7385667/26241387/0788fb56-3cb7-11e7-84e2-3362b585eaeb.png)

**Comment by djlan** [comment]
Fix checked in. Please verify.

**Comment by wezhang** [comment]
Fixed, thanks!
