### ISSUE TITLE
[Intellij2016&2017] Spark version is null for sparklisttest cluster 

### ISSUE THREAD

**Issue by ruoxinCheng** [Microsoft/azure-tools-for-java#488]
![capture](https://cloud.githubusercontent.com/assets/20041888/26242877/8e955b26-3cbc-11e7-809c-f7e889fd4031.PNG)

**Comment by voidfunction** [comment]
It's cached additional HDInsight cluster. We should put a tag to such clusters to distinguish from others.

**Comment by ruoxinCheng** [comment]
This cluster was a linked cluster and was already deleted on portal, but it did not throw any error from Azure Explorer.
