### ISSUE TITLE
[Intellij2016&2017] Sorting and description these option for choosing spark version

### ISSUE THREAD

**Issue by ruoxinCheng** [Microsoft/azure-tools-for-java#489]
![capture2](https://cloud.githubusercontent.com/assets/20041888/26243030/0d565c3a-3cbd-11e7-879b-d0947b40b8a4.PNG)

**Comment by ziyel** [comment]
Fix in https://github.com/Microsoft/azure-tools-for-java/pull/537

**Comment by ruoxinCheng** [comment]
Verified on mac, Linux, window, they are work.
