### ISSUE TITLE
Azure toolkit for eclipse 

### ISSUE THREAD

**Issue by yaseenmd** [microsoft/azure-tools-for-java#4906]
After installing the Azure toolkit for java in eclipse , getting pop up whenever i launch eclipse IDE.

![image](https://user-images.githubusercontent.com/13603644/105671236-6099c780-5f08-11eb-83f5-279f52a34e96.png)
![image](https://user-images.githubusercontent.com/13603644/105671424-b4a4ac00-5f08-11eb-9cb5-20e7aa7af32e.png)

**Comment by andxu** [comment]
By design, if you don't use scala, click 'x' on the right corner
