### ISSUE TITLE
[Intellij.2017.RedisCache] Create Redis Cache form look strage

### ISSUE THREAD

**Issue by jdneo** [Microsoft/azure-tools-for-java#494]
![image](https://cloud.githubusercontent.com/assets/6193897/26289731/ef427b42-3ed4-11e7-98f4-6cd9ca7975d2.png)

**Comment by jdneo** [comment]
@bsaby Fixed, Please verify this in tomorrow's daily build, thanks.

**Comment by bsaby** [comment]
Test passed, using artifacts/azure-toolkit-for-intellij.2017.develop.daily.10.05-22-2017.zip.
![image](https://cloud.githubusercontent.com/assets/22470312/26334946/2f3186b4-3f9b-11e7-8fd9-e12f37eda2b1.png)
