### ISSUE TITLE
How to set run/debug configurations of Azure Functions in python project (forwarded)

### ISSUE THREAD

**Issue by nikonov91-dev** [microsoft/azure-tools-for-java#4945]
Hi there, 
"How to set up the run/debug configuration of Azure Functions for Run Functions?" - I posted this question in [azure-toolkit-for-intellij team](https://github.com/JetBrains/azure-tools-for-intellij/issues/441) and they forwarded me here.

**The principal idea**: I have Python web-application using Azure services and I work in Intellij. I'd like to know how to set the Run/Debug configuration for Azure-Functions (please see the picture) 

![106959086-e0af0100-6742-11eb-8390-9f1efc96682e](https://user-images.githubusercontent.com/31586394/107858443-cb219180-6e3c-11eb-978d-dce7ad393f59.png)

Because I've installed sdk for python but your config-toolkit doesnt see it.

I'm looking for a way to debug it in Intellij (not VSCode) but I dont know how to use the tool.
Thanks

**Comment by Flanker32** [comment]
@nikonov91-dev Thanks for your report, Azure Toolkits for IntelliJ is a plugin for Java projects, which did not include the python function support. 

If you want to debug your python function locally, please using following command and attach to the process in IntelliJ.([refers](https://github.com/Azure/azure-functions-core-tools/wiki/Enable-Debugging-for-language-workers))
```
# Where 9091 is the python debug port you can attach to. 
func host start \
  --language-worker -- "-m ptvsd --host 127.0.0.1 --port 9091"
```

**Comment by nikonov91-dev** [comment]
thanks for your help,  
Currently when I execute your line and get this error: *Exceeded language worker restart retry count for runtime:python. Shutting down Functions Host*
```
azure_functions$ func host start  --language-worker -- "-m ptvsd --host 127.0.0.1 --port 9091"
Found Python version 3.8.2 (python3.8).

Azure Functions Core Tools
Core Tools Version:       3.0.2996 Commit hash: c54cdc36323e9543ba11fb61dd107616e9022bba
Function Runtime Version: 3.0.14916.0

[2021-02-21T10:41:47.807Z] Exceeded language worker restart retry count for runtime:python. Shutting down and proactively recycling the Functions Host to recover
[2021-02-21T10:41:47.893Z] /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8: No module named ptvsd
[2021-02-21T10:41:47.894Z] /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8: No module named ptvsd
[2021-02-21T10:41:47.894Z] /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8: No module named ptvsd
```
At this moment i'm googling the solution but in VSCode it runs without any error.
I'll mail you soon as I get it solved

**Comment by Flanker32** [comment]
@nikonov91-dev Thanks for your info!

@pragnagopa Could you please help check @nikonov91-dev's issue?

**Comment by nikonov91-dev** [comment]
update: 
I've globally installed that module ***ptvsd*** 
with next command: */Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -m pip install ptvsd*
but my IDE (Intellij Idea) debugger does not stops at because IDE editor (as I understand) must be specified in that line
```
func host start  --language-worker -- "-m ptvsd --host 127.0.0.1 --port 9091"
```
Now I'm looking for a way to refer to my IDE from running debug server

**Comment by nikonov91-dev** [comment]
one more question may be it's better to use **debugpy** instead of **ptvsd** ? because I see Microsoft marked it as deprecated [ptvsd repo](https://github.com/microsoft/ptvsd)

**Comment by pragnagopa** [comment]
Is this the right repo for python-tooling?

**Comment by pragnagopa** [comment]
Tagging @vrdmr @Hazhzeng - for Azure Functions  Python related questions

**Comment by nikonov91-dev** [comment]
> Is this the right repo for python-tooling?

what do you mean? I mentioned **ptvsd**  because you colleague proposed to use it to run debug server locally. But never mind, that was just important question

**Comment by nikonov91-dev** [comment]
I found the way to debug in ***Intellij Idea/PyCharm***  and seem to be we may close this question. 
To debug in JebBrains products you need to 

1. add these lines at the top of your file/module:
```
import pydevd_pycharm
pydevd_pycharm.settrace('127.0.0.1', port=9091, stdoutToServer=True, stderrToServer=True)
```
2. set your Run/Debug Configs with host and port 
![Screenshot at Feb 22 20-29-45](https://user-images.githubusercontent.com/31586394/108752900-b768e000-754c-11eb-91b6-edebf0ce923b.png)

3. run your azure functions as used to (```func host start```) and start debugging.

There is no need in **debugpy**
