### ISSUE TITLE
403 for eclipse update site

### ISSUE THREAD

**Issue by smai** [microsoft/azure-tools-for-java#4947]
http://dl.microsoft.com/eclipse/ 

displays the following message 

The web app you have attempted to reach is currently stopped and does not accept any requests. Please try to reload the page or visit it again soon.

If you are the web app administrator, please find the common 403 error scenarios and resolution here. For further troubleshooting tools and recommendations, please visit Azure Portal.

**Comment by ranvir8101** [comment]
Hi,

Did you get the resolution? I am facing a similar issue.

**Comment by smai** [comment]
@ranvir8101  No, I have not found a resolution to this issue or received a reply.

**Comment by Flanker32** [comment]
@smai @ranvir8101 Thanks for your report, we will fix this issue soon, as a workaround, please use `https://azuredownloads.blob.core.windows.net/eclipse/` to get the latest Eclipse Azure Toolkit.

**Comment by ranvir8101** [comment]
Thanks @Flanker32 . 
Please let us know when the issue is resolved.

**Comment by ddarling85** [comment]
Hi @Flanker32. Still unable to access http://dl.microsoft.com/eclipse/, but the alternate site (https://azuredownloads.blob.core.windows.net/eclipse/) did work for me.  Thanks.

**Comment by Eugeniu-N** [comment]
I also want to confirm that `http://dl.microsoft.com/eclipse/` didn't work for installing the toolkit from eclipse but `https://azuredownloads.blob.core.windows.net/eclipse/` worked

**Comment by alirezazamani** [comment]
@Flanker32 I encountered the same issue. I need to install Eclipse plugin for service fabric and there is no alternative way to do it.

**Comment by yucwan** [comment]
> @Flanker32 I encountered the same issue. I need to install Eclipse plugin for service fabric and there is no alternative way to do it.

Which plugin are you referring to? could you share a link?

**Comment by yucwan** [comment]
> @Flanker32 I encountered the same issue. I need to install Eclipse plugin for service fabric and there is no alternative way to do it.

Which plugin are you referring to? could you share a link?

**Comment by alirezazamani** [comment]
> > @Flanker32 I encountered the same issue. I need to install the Eclipse plugin for service fabric and there is no alternative way to do it.
> 
> Which plugin are you referring to? could you share a link?

I am following this doc/page: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-linux?tabs=sdksetupubuntu%2Clocalclusteroneboxcontainer#set-up-java-development

In order to get "AzureServiceFabric Plugin for Eclipse" I need to use this link:  http://dl.microsoft.com/eclipse/. However, this does not seem to work and the workaround mentioned in this issue only works for Azure Toolkit for Java.

**Comment by andxu** [comment]
Hi @alirezazamani , can you see any broken links now?
