### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Error creating this Application Insights resource. 

### ISSUE THREAD

**Issue by shubhamJ12** [microsoft/azure-tools-for-java#4950]
IntelliJ build version: 2020.3.2 

[IntelliJ][ReportedByUser] Uncaught Exception Error creating this Application Insights resource. Try again. com.microsoft.azure.CloudException: Status code 400, {"error":{"code":"LocationNotAvailableForResourceType","message":"The provided location 'West Central US' is not available for resource type 'microsoft.insights/components'. List of available regions for the resource type is 'eastus,southcentralus,northeurope,westeurope,southeastasia,westus2,uksouth,canadacentral,centralindia,japaneast,australiaeast,koreacentral,francecentral,centralus,eastus2,eastasia,westus,southafricanorth,northcentralus,brazilsouth,switzerlandnorth,norwayeast,australiasoutheast,australiacentral2,germanywestcentral,switzerlandwest,uaecentral,ukwest,japanwest,brazilsoutheast,uaenorth,australiacentral'."}}: The provided location 'West Central US' is not available for resource type 'microsoft.insights/components'. List of available regions for the resource type is 'eastus,southcentralus,northeurope,westeurope,southeastasia,westus2,uksouth,canadacentral,centralindia,japaneast,australiaeast,koreacentral,francecentral,centralus,eastus2,eastasia,westus,southafricanorth,northcentralus,brazilsouth,switzerlandnorth,norwayeast,australiasoutheast,australiacentral2,germanywestcentral,switzerlandwest,uaecentral,ukwest,japanwest,brazilsoutheast,uaenorth,australiacentral'.

**Comment by andxu** [comment]
Hi @shubhamJ12 , could you please try to change the region to the list below and take a try?
'eastus,southcentralus,northeurope,westeurope,southeastasia,westus2,uksouth,canadacentral,centralindia,japaneast,australiaeast,koreacentral,francecentral,centralus,eastus2,eastasia,westus,southafricanorth,northcentralus,brazilsouth,switzerlandnorth,norwayeast,australiasoutheast,australiacentral2,germanywestcentral,switzerlandwest,uaecentral,ukwest,japanwest,brazilsoutheast,uaenorth,australiacentral'.
