### ISSUE TITLE
[Eclipse.Redis Cache] OK button should be disabled

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#497]
[Linux]
BUild used:  artifacts/WindowsAzurePlugin4EJ.develop.daily.9.05-21-2017.zip
![image](https://cloud.githubusercontent.com/assets/22470312/26290224/984f499c-3ed8-11e7-939a-1f9dc056a883.png)
Repro steps:
1. Type DNS Name
2. Resource Group: choose Use Existing
3. Now, the OK button is enabled
4.Change the Resource Group option to Create New
EXPECT: OK button should  be disabled
RESULT: OK button is still enabled

**Comment by davidliangze** [comment]
Also reproduce in IntelliJ 2017 [Linux]

**Comment by jdneo** [comment]
Fixed please verify in the new build, thanks.

**Comment by bsaby** [comment]
Test passed. 
Build used: artifacts/WindowsAzurePlugin4EJ.develop.70.05-22-2017.zip.
