### ISSUE TITLE
IntelliJ login problem: Failed to get details of all cached subscriptions, as get all authorized tenants failed

### ISSUE THREAD

**Issue by andromed2** [microsoft/azure-tools-for-java#4977]
When signing into my azure account I get the following error message:

Failed to get details of all cached subscriptions, as get all authorized tenants failed
Details: - Get details of all cached subscriptions
- Flush subscriptions cache
- Flush subscriptions cache
- Load subscriptions from authorized tenants
- Get all authorized tenants

This happens every time, and is independent from signin-method (consume existing Azure CLI credential or Device Login)

Login via CLI (az login) oder on the web portal works without a problem. The problem only happens inside Azure Toolkit for IntelliJ.

Toolkit version: 3.49.1-2020-2
IntelliJ version: 2020-2.1 (Ultimate)

**Comment by andxu** [comment]
Hi @andromed2 , we are refactoring auth modules in intellij  plugin in this month, will fix this issue of device code

**Comment by harry12345678910** [comment]
I am facing the same issue. The problem seems to be, that there is a disabled user existing in another tenant (another company I had access to in former days). It  then fails to get the subscriptions for all tenants.

**Comment by psmgeelen** [comment]
Hi there, I have the exact same issue. The 'joke' is that this does work on laptop, but does not work on desktop for some reason. I tried reinstalling azure-cli, reinstalling snap IntelliJ, flushed all imaginable cache's and user settings and still no luck. I also tried different version of software, but to no avail. And all of this whilst it does work on my laptop. Could it be some kind of dependency issue?

**Comment by andxu** [comment]
The reason of this issue is you have no permission over some tenants, eg: https://github.com/microsoft/azure-tools-for-java/pull/4991, we will fix this issue at the end of March.

**Comment by psmgeelen** [comment]
@andxu , thanks for your fast response. I do not follow entirely. So the exact same route DOES work on my laptop, but DOESNT work on Desktop. We are talking identical OS, IDE and Azure-CLI version. I current login with a Service Principal already. Why would the file work?

**Comment by harry12345678910** [comment]
@psmgeelen: do you have the same version of the azure toolkit in place? My problems started with a later version of the toolkit. I had to downgrade to make it work again.

**Comment by psmgeelen** [comment]
@andxu , tried the ServicePrinciple file, got the exact same response. @harry12345678910 , I will try that now, thanks for idea!

**Comment by psmgeelen** [comment]
@harry12345678910 , I am using IntelliJ 2020.3 and have the version 3.49.1-2020.3; which btw is the only supported version for the IDE version of 2020.3. What are you proposing that I should do? Again, something that I can still not figure out is how this doesnt work on my desktop and does work on my laptop..

**Comment by harry12345678910** [comment]
I downgraded Intellij and also the corresponding plugin. Not nice, but a workaround that works for us so far.

**Comment by psmgeelen** [comment]
Lets see what @andxu can do for us by the end of the month!

**Comment by psmgeelen** [comment]
Hi there, I just wanted to check in to share that it seems to be working now. I am not sure whether this has anything to do with explicit code changes that you guys made or because of other updates. Anyhow, thanks a bunch!

**Comment by andxu** [comment]
Close this issue since the owner said 'it is working now'.
