### ISSUE TITLE
[Intellij] Expired authorization triggers annoying dialogs

### ISSUE THREAD

**Issue by konjac** [microsoft/azure-tools-for-java#5003]
As the following screen shot, the authorization expired. However, refreshing the tree node will still attempt list resources and show a batch of annoying dialogs. Such expired authorization should be processed more gracefully.

![AuthorizationExpired](https://user-images.githubusercontent.com/2101973/110566563-2a986600-818b-11eb-985b-5eff4d5cefa3.gif)

**Comment by andxu** [comment]
@konjac could you please upgrade you intellij plugin to the latest version and tell us whether this issue still occurs?

**Comment by andxu** [comment]
The latest version is : 3.50+
