### ISSUE TITLE
Unable to install Azure Tooling in Eclipse 2020-12 (4.18.0)

### ISSUE THREAD

**Issue by subhendu-de** [microsoft/azure-tools-for-java#5012]
Hi All,

I'm using Eclipse 2020-12 (4.18.0) and installed the Azure toolkit for Java using both the ways (from marketplace as well as installing new software). The component shows installed and restarted after installation. However I don't see any Azure explorer from Windows ->Show view -> Others

Is there anything I'm missing?

Thanks
Subhendu

**Comment by Flanker32** [comment]
@subhendu-de Thanks for your report, could you please try a new workspace and try again?

**Comment by subhendu-de** [comment]
@Flanker32 I reinstalled eclipse and azure plugin as well. Now I'm able to see the Azure plugin.

I checked the jars in plugins folder and unable to find them though Azure plugin was showing installed.
I tried to switch to new workspace but that didn't solve the problem.

**Comment by Flanker32** [comment]
@subhendu-de Thanks a lot for your efforts, it seems there are some exceptions with Eclipse during installing plugins, glad to see the issue is resolved.
