### ISSUE TITLE
[Spark-Debug] The 'Artifact from Intellij project' can only see the default artifact

### ISSUE THREAD

**Issue by wezhang** [Microsoft/azure-tools-for-java#502]
![image](https://cloud.githubusercontent.com/assets/7385667/26291156/08cc685c-3edf-11e7-924f-b4ebaf2f2ce3.png)

**Comment by ziyel** [comment]
Could not reprod.

**Comment by jingyanjingyan** [comment]
Verify as fix with build develop 788. Add a new artifact, could listed in the "Artifact from intelliJ project"
