### ISSUE TITLE
Resources Are Not Added To Jar When Debugging With IDEA

### ISSUE THREAD

**Issue by opticyclic** [microsoft/azure-tools-for-java#5035]
When debugging a function using IDEA it is not possible to get resources from the classpath. e.g. `application.properties`

I paused the debugger and found a jar in `/tmp/azure-functions10656607994858773786/`. 

When I unzipped the jar it only contained compiled classes and none of the resource files.

When I run the gradle task the resources are in the jar.

When I run the compile task from idea the files are in the out/production/resources directory as expected.

How are you creating the jar for debugging and why are you excluding the resource files?

**Comment by Flanker32** [comment]
@opticyclic Thanks a lot for your report, @andxu Could you please investigate this issue?

**Comment by opticyclic** [comment]
See also this related issue https://github.com/microsoft/azure-tools-for-java/issues/5038

**Comment by andxu** [comment]
Fixed in #6225
