### ISSUE TITLE
no tips for Spark project on IntelliJ if without Scala plugin

### ISSUE THREAD

**Issue by voidfunction** [Microsoft/azure-tools-for-java#504]
We should have such a tips for customers to enable Scala plugin for Spark project.
![fdsf](https://cloud.githubusercontent.com/assets/6745693/26291281/d3ade7d0-3edf-11e7-80d9-7aee01d89eb8.png)

**Comment by ziyel** [comment]
Fix in https://github.com/Microsoft/azure-tools-for-java/pull/545.

**Comment by ruoxinCheng** [comment]
It works.
