### ISSUE TITLE
[Eclipse.Signin]Can't sign in azure by clicking Publish as Docker Container... 

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#506]
Also repro released build: 3.0.2.201705100318
Build used: artifacts/WindowsAzurePlugin4EJ.develop.daily.9.05-21-2017.zip

Choose **Publish as Docker Container...** from right clicking project or toolbar before azure sign in .

EXPEXT:
Pop-up Azure Sign In window

RESULT:
Quickly flashed the below  window
![image](https://cloud.githubusercontent.com/assets/22470312/26291371/62ddecac-3ee0-11e7-9e1a-61de1bd3d5f2.png)

**Comment by Flanker32** [comment]
The issue has been fixed in the latest release
