### ISSUE TITLE
[IntelliJ 2017]  show user-friendly error message

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/azure-tools-for-java#509]
Should not show javax.swing.xxxxx to users.

![image](https://cloud.githubusercontent.com/assets/1050213/26292982/09e008f8-3eed-11e7-94ed-9a466db5bc75.png)

**Comment by jdneo** [comment]
Repeoduce step:
Create an exising Redis Cache in the subscription

@bsaby Fixed, Please verify this in tomorrow's daily build, thanks.

**Comment by bsaby** [comment]
Test passed, using artifacts/azure-toolkit-for-intellij.2017.develop.daily.10.05-22-2017.zip.
![image](https://cloud.githubusercontent.com/assets/22470312/26335008/913f098a-3f9b-11e7-83c8-ac6dba71d29d.png)
