### ISSUE TITLE
UI issues with wizard to create a new VM 

### ISSUE THREAD

**Issue by jansorg** [microsoft/azure-tools-for-java#5094]
The wizard to create a new VM (context menu of "Virtual machines" in the "Azure Explorer" tool window) has a few UI issues on my environment (Linux, KDE, 4k display):
- it's not resizable. The initial size a bit small for my screen resolution
- Title "Choose a Subscription" is difficult to read
- The list on the left has a scrollbar and can't be resized to show all of the content.
- The gear icon seems misaligned
![Screenshot_063](https://user-images.githubusercontent.com/11473063/114010172-203dba80-9864-11eb-8ec5-3becbc518712.png)

**Comment by Flanker32** [comment]
We have refactor the creation wizard for VM creation, here is the snapshot.

![image](https://user-images.githubusercontent.com/12445236/144199854-952542ac-7a28-4668-a877-5136c823fada.png)
