### ISSUE TITLE
Deploy web app window doesn't render subscription info 

### ISSUE THREAD

**Issue by arroyc** [Microsoft/azure-tools-for-java#51]
Probably a form size issue
![image](https://cloud.githubusercontent.com/assets/16231002/23077199/64883f80-f4f8-11e6-8843-f7f30e1e58d5.png)

**Comment by martinsawicki** [comment]
pls make sure to indicate your OS and resolution for sizing issues. 
(I see it ok on Windows)

**Comment by arroyc** [comment]
resolution 2560X1440 in windows 10 enterprise

**Comment by bsaby** [comment]
Test passed in artifacts/azure-toolkit-for-intellij.197.zip

**Comment by martinsawicki** [comment]
@vladimir-shcherbakov  can you confirm  and close?

**Comment by vladimir-shcherbakov** [comment]
sure
