### ISSUE TITLE
Azure Toolkit for Intellij doesn't work with 2021.1 CE

### ISSUE THREAD

**Issue by andjorg** [microsoft/azure-tools-for-java#5102]
Plugin 'Azure Toolkit for IntelliJ' (version '3.49.1-2020.3') is not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is IC-211.6693.111

**Comment by Flanker32** [comment]
@andjorg Thanks for your report. We have released v3.51.0 with IntelliJ 2021.1 support, you may get it [here](https://plugins.jetbrains.com/plugin/8053-azure-toolkit-for-intellij)
