### ISSUE TITLE
Subscriptions not listed in eclipse after login

### ISSUE THREAD

**Issue by Ananthasuri** [microsoft/azure-tools-for-java#5122]
My azure subscriptions are not listed Eclipse after I login to my Azure account using Eclipse IDE. I followed all the steps mentioned here - 
https://docs.microsoft.com/en-us/azure/developer/java/toolkit-for-eclipse/sign-in-instructions

Eclipse version - 
Version: Photon Release (4.8.0)
Build id: 20180619-1200

**Comment by andxu** [comment]
Hi @Ananthasuri , I am sorry that the current eclipse plugin is not well considered because of low priority, for walk-aground, please use intellij azure toolkit plugin instead. We will start eclipse plugin development when the main features in intellij plugin side is almost finished.

**Comment by Ananthasuri** [comment]
Then is there any reason for this article to be present in Microsoft? Nowhere it is mentioned that eclipse is not supported yet.

**Comment by andxu** [comment]
@Ananthasuri , I am not meaning we don't support eclipse in future, but our priority for tooling is: maven -> intellij plugin -> eclipse plugin. I guess your are you using device login? Are you seeing no subscriptions or only a few of them?
