### ISSUE TITLE
[Eclipse] Azure Toolkit for Eclipse "Sign In" not working

### ISSUE THREAD

**Issue by MicuSebastian** [microsoft/azure-tools-for-java#5136]
Azure Toolkit for Eclipse: v.3.25.0
Eclipse: Eclipse IDE for Enterprise Java Developers
JDK: 16

After successfully installing the package, Eclipse recognizes it, but the "Sign In" button does not work after pressing it. Even if I try to open Azure Explorer or Azure Code Samples, it doesn't react at all.

![prob1](https://user-images.githubusercontent.com/63539167/115762969-aef61f80-a3ac-11eb-82bb-f80a597bc34e.png)

What's even weirder is that if you click Azure Explorer fast enough after Eclipse is starting, a window opens, but it doesn't help.

![prob2](https://user-images.githubusercontent.com/63539167/115763489-2d52c180-a3ad-11eb-99e0-678fbe5f1fc6.png)

**Comment by GeorgianaRaluca** [comment]
Hello! I have the same problem. But I don't know how to solve it.

**Comment by dragossolca** [comment]
I also have the same problem

**Comment by andxu** [comment]
Will fix this issue at this month, 3.27( in two weeks)

**Comment by shenqianjin** [comment]
resolved in [V3.27.0](https://github.com/Microsoft/azure-tools-for-java/releases/tag/azure-eclipse-toolkit-V3.27.0)
