### ISSUE TITLE
[Eclipse] Azure Toolkit for Eclipse "Sign In" button not working

### ISSUE THREAD

**Issue by GeorgianaRaluca** [microsoft/azure-tools-for-java#5137]
Azure Toolkit for Eclipse: v.3.25.0
Eclipse: Eclipse IDE for Enterprise Java Developers
JDK: 16

From "Eclipse Marketplace" I installed successfully "Azure Toolkit for Eclipse 3.25.0" package, I restarted Eclipse and when I tried to press the "Sing In" button from Azure it did not work.

![Captură ecran (164)](https://user-images.githubusercontent.com/59791050/115766767-026a6c80-a3b1-11eb-8324-b96987778a4a.png)

I tried also here and no response. 
![Captură ecran (165)](https://user-images.githubusercontent.com/59791050/115766915-35146500-a3b1-11eb-8619-8a969cc0a1ee.png)

The "Sing In" button it's only working from here:
![Captură ecran (167)](https://user-images.githubusercontent.com/59791050/115767066-60974f80-a3b1-11eb-8805-7cce0e822625.png)

After I tried to sing in with my account, I receive on my browser "You have signed in to the Azure Toolkits for IntelliJ IDEA and Eclipse application on your device. You may now close this window.", but not reaction from Eclipse, it remains the same:

![image](https://user-images.githubusercontent.com/59791050/115767565-f632df00-a3b1-11eb-9423-b57551d1bf5b.png)
Also the "Cancel" button is not working.

I would be grateful if you could help me!

**Comment by GeorgianaRaluca** [comment]
Also if I close Eclipse and I reopen it, I receive this:
![image](https://user-images.githubusercontent.com/59791050/115769084-d0a6d500-a3b3-11eb-8e30-f3023fb0f2a6.png)

**Comment by MicuSebastian** [comment]
For the last part, "Incompatible JVM", you need to edit the "eclipse.ini" file and try adding the next lines on top:

-vm
C:/Program Files/Java/jdk-16/bin/javaw.exe (-> here is the path to your jdk-16)

**Comment by shenqianjin** [comment]
resolved in [V3.27.0](https://github.com/Microsoft/azure-tools-for-java/releases/tag/azure-eclipse-toolkit-V3.27.0)
