### ISSUE TITLE
[Eclipse] Azure Tookit for Eclipse buttons not working

### ISSUE THREAD

**Issue by dragossolca** [microsoft/azure-tools-for-java#5151]
Azure Toolkit for Eclipse: v.3.25.0
Eclipse: Eclipse IDE for Enterprise Java Developers
JDK: 16

I installed the Azure Tookit plugin from Eclipse Marketplace. After that, I restarted Eclipse. I tried to sign in to no avail. No pop-up window appears.
![image](https://user-images.githubusercontent.com/56224261/115895793-7a916a80-a463-11eb-8724-3807816510ef.png)

Furthermore, none of the Azure associated buttons respond when clicked upon
![image](https://user-images.githubusercontent.com/56224261/115896277-ebd11d80-a463-11eb-834d-b19110581581.png)

Could you please give me some guidance on what the issue could be?

**Comment by junsaw** [comment]
I am experiencing the similar issue, does anyone have an update ?

**Comment by dragossolca** [comment]
I managed to make it work using jdk 13

**Comment by andxu** [comment]
We will fix it in this month.

**Comment by shenqianjin** [comment]
resolved in [V3.27.0](https://github.com/Microsoft/azure-tools-for-java/releases/tag/azure-eclipse-toolkit-V3.27.0)
