### ISSUE TITLE
Azure Toolkit for Eclipse "Sign in" not working

### ISSUE THREAD

**Issue by IonutDH** [microsoft/azure-tools-for-java#5152]
Azure Toolkit for Eclipse: v.3.25.0
Eclipse: Eclipse IDE for Enterprise Java Developers
JDK: 16

After I managed to install the package, the buttons are shown in the up menu but none of them seem to work.
I tried doing it with a fresh copy of Eclipse, with no previous projects and this window appears in the right bottom corner even though the buttons does not work: 
![image](https://user-images.githubusercontent.com/63075009/115985394-542f1480-a5b4-11eb-959e-d900b1e50e54.png)

The only button that works here is the highlighted one:
![Untitled](https://user-images.githubusercontent.com/63075009/115985549-0a92f980-a5b5-11eb-8635-4dc8bed3b08c.png)

and this opens:
![image](https://user-images.githubusercontent.com/63075009/115985517-da4b5b00-a5b4-11eb-901d-cb2eb45ef75d.png)

but when I'm trying to Sign in, it looks like the process fails.

**Comment by andxu** [comment]
Will fix this issue at this month, 3.27( in two weeks)

**Comment by shenqianjin** [comment]
resolved in [V3.27.0](https://github.com/Microsoft/azure-tools-for-java/releases/tag/azure-eclipse-toolkit-V3.27.0)
