### ISSUE TITLE
[Eclispse] Azure Toolkit dosen't show up after installation

### ISSUE THREAD

**Issue by CraciunRAlexandra** [microsoft/azure-tools-for-java#5154]
Azure Toolkit for Eclipse: v.3.25.0
Eclipse: Eclipse IDE for Enterprise Java Developers
JDK: 16
From "Eclipse Marketplace" I installed successfully "Azure Toolkit for Eclipse 3.25.0" package, I restarted Eclipse but in toolbar dosen't show the "Tools" button.

![33e7667e4e21c3faee17f3027d158a2b](https://user-images.githubusercontent.com/56547343/116009888-93954980-a624-11eb-85aa-5146870a66aa.png)

But in "Eclipse Marketplace" it shows up as installed.

![70c8be4e91936dca9e0c5a7cf7546787](https://user-images.githubusercontent.com/56547343/116009931-c93a3280-a624-11eb-950d-f2dfab41c2be.png)

![62a073b8b1621241fe9a93acd4f01deb](https://user-images.githubusercontent.com/56547343/116009936-cc352300-a624-11eb-8fc6-44fc78b5d5f0.png)

**Comment by shenqianjin** [comment]
resolved in [V3.27.0](https://github.com/Microsoft/azure-tools-for-java/releases/tag/azure-eclipse-toolkit-V3.27.0)
