### ISSUE TITLE
[Eclispse] Azure dosen't show the "Tools" option.

### ISSUE THREAD

**Issue by ZamfirAndreiPaul** [microsoft/azure-tools-for-java#5158]
Azure Toolkit for Eclipse: v.3.25.0
Eclipse: Eclipse IDE for Enterprise Java Developers
JDK: 16

I try to install from "Eclipse Marketplace" -> "Azure Toolkit for Eclipse 3.25.0" package. This work fine. It show that is installed.

![image](https://user-images.githubusercontent.com/56279630/116147460-6ca04b80-a6e8-11eb-9b76-8f4e57b5acc8.png)

I tried to restart several times but in the toolbar , "Tools" still does not appear.

**Comment by andxu** [comment]
Will fix this issue at this month, 3.27( in two weeks)

**Comment by shenqianjin** [comment]
resolved in [V3.27.0](https://github.com/Microsoft/azure-tools-for-java/releases/tag/azure-eclipse-toolkit-V3.27.0)
