### ISSUE TITLE
Azure sign in pop up window in tools menu doesn't have expand option (maximize) when it pops up initially, so the sign-in/cancel options are kind of invisible, unless user drag and expand the window.

### ISSUE THREAD

**Issue by arroyc** [Microsoft/azure-tools-for-java#52]
![image](https://cloud.githubusercontent.com/assets/16231002/23077243/8ffa171a-f4f8-11e6-8c68-f483353cb345.png)

**Comment by arroyc** [comment]
resolution 2560X1440 in windows 10 enterprise

**Comment by bsaby** [comment]
Test passed in artifacts/azure-toolkit-for-intellij.197.zip

**Comment by martinsawicki** [comment]
Vlad confirmed on hi -res monitoro
