### ISSUE TITLE
[Eclipse 3.0.1] Cannot show clusters after signing sucessful

### ISSUE THREAD

**Issue by ruoxinCheng** [Microsoft/azure-tools-for-java#523]
![image](https://cloud.githubusercontent.com/assets/20041888/26297525/c6fdfee6-3f05-11e7-8d2e-7e44a8e13f76.png)

**Comment by voidfunction** [comment]
Fixed.

**Comment by ziyel** [comment]
Fix in #686
@ruoxinCheng , could you please help to verify in the latest daily build.

**Comment by ruoxinCheng** [comment]
Yes, verified on Eclipse mars and Neon, it works
