### ISSUE TITLE
App insight object is created everytime when sending telemetry

### ISSUE THREAD

**Issue by mybayern1974** [Microsoft/azure-tools-for-java#524]
The problem is at both eclipse and intellij. Just take eclipse as example. In the file AppInsightsCustomEvent.java, an object of class [TelemetryClient] is created every time when calling [create] for sending telemetry. Creating this object and [setInstrumentationKey()] for it is very time consuming: on my machine the latency is longer than 5 seconds. As a result, every time we send a metric to AI, there is such a performance penalty. A solution could be to create a global object rather than a temporary one in each call, if so, then be aware to add proper "lock" logic to avoid resource collision.

The counterpart file in IntelliJ is still called AppInsightsCustomEvent.java.

**Comment by adashen** [comment]
@Eskibear make TelemetryClient as singleton, and take care of the multi thread scenario. Not in the sprint. We can do it later
