### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Operator called default onErrorDropped reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by BgRva** [microsoft/azure-tools-for-java#5242]
IntelliJ build version: 2020.3.1 IU-203.6682.168
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.9.1
Plugin version: 3.52.0-2020.3
Additional Info: Just trying to login with the new OAuth2 capability.  I am already logged in to my subscription in the browser, by this happens.
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,8,0,824x512,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Operator called default onErrorDropped, throwable=reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.microsoft.azuretools.sdkmanage.IdentityAzureManager.fromAccountEntity(IdentityAzureManager.java:201)
	at com.microsoft.azuretools.sdkmanage.IdentityAzureManager.lambda$signInOAuth$3(IdentityAzureManager.java:102)
```

**Comment by BgRva** [comment]
This occurs even though I am logged into the CLI via the terminal window, and logged in via a browser, before I click the Sign-In button in the Az Explorer.  The ability to authenticate via CLI is greyed out and does not accept the current cli login.

**Comment by andxu** [comment]
could you please let us known the output of `az account list`? you can strip the sensitive info

**Comment by BgRva** [comment]
I'm trying to connect to another azure cloud, not commercial.  It seems to be attempting to connect to commercial, hence the errors.  I had the same issue with the plugin for VS Code, but was able to find a setting in that plugin to specify a different Azure Cloud to connect to, then it worked.

**Comment by Flanker32** [comment]
@BgRva The issue should be fixed in https://github.com/microsoft/azure-tools-for-java/pull/5159, could you please try upgrade to the latest toolkit and see whether the issue could be reproduced?
