### ISSUE TITLE
[Intellij2016&2017] Build project no response, When i have not setup scala SDK

### ISSUE THREAD

**Issue by ruoxinCheng** [Microsoft/azure-tools-for-java#532]
1. create a new project and not setup scala sdk.
2. Build project no response.
And we should give a strongly reminder to setup scala sdk.

**Comment by ziyel** [comment]
If the `Scala Intellij plugin` installed, the maven will auto import the `Scala SDK` when create new project.
We can update the new project created process to make sure the Scala plugin installed while creating Scala project.

**Comment by ziyel** [comment]
Fix in https://github.com/Microsoft/azure-tools-for-java/pull/545.

**Comment by ruoxinCheng** [comment]
Verified on windows, Linux, mac, they work.
