### ISSUE TITLE
Unable to sign in to Azure from Eclipse

### ISSUE THREAD

**Issue by madhavaram123** [microsoft/azure-tools-for-java#5365]
Unable to sign in to Azure from Eclipse(Eclipse IDE 2021‑03). 
Error is as below:
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Tried Below steps:

From home page portal.azure.com, I downloaded the certificate by clicking on the lock icon in Google Chrome. Is this the correct certificate? or do I need to download from anywhere else. If yes kindly provide the steps or the link to do so.

Added to all the below places, verified the certificate in cacerts using Portecle. 
- java\jdk1.7.0_79\jre\lib\security\cacerts 
- Java\jre7\lib\security\cacerts 
- Java\jre1.8.0_241\lib\security\cacerts 
- Java\jdk1.8.0_241\jre\lib\security\cacerts

Eclipse is using the Java C:\Program Files\Java\jdk1.8.0_241\jre

Am I missing something here?

**Comment by andxu** [comment]
Will work on eclipse login issue this month, target to release at end of August

**Comment by DNGSlug** [comment]
<html>
 <body>
   <b><% out.println("Hello World!"); %></b>
 </body>
</html>

**Comment by andxu** [comment]
Hi @madhavaram123, could you try this article, and tell us whether you can solve this problem?
https://mkyong.com/webservices/jax-ws/suncertpathbuilderexception-unable-to-find-valid-certification-path-to-requested-target/
