### ISSUE TITLE
[IntelliJ2017+IntelliJ2016][Mac+Linux] Telemetry: Help improve unchecked in clean install

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#539]
Clean install
Expect:
Verify Preference -> Azure -> Help improve checked.
Result:
Verify Preference -> Azure -> Help improve unchecked.

**Comment by adashen** [comment]
Duplicate with https://github.com/Microsoft/azure-tools-for-java/issues/505
@bsaby please close if it is duplicate
