### ISSUE TITLE
[Eclipse][Win10 / Mac / Linux]Telemetry: OS telemetry data display: other

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#540]
Result:
![image](https://cloud.githubusercontent.com/assets/22470312/26344038/c9b6b044-3fd0-11e7-8fb0-2e1498440f82.png)
Expect:
![image](https://cloud.githubusercontent.com/assets/22470312/26344130/2357d7f4-3fd1-11e7-8dbd-7dc5a13daddb.png)

**Comment by jdneo** [comment]
@bsaby fixed, please verify in the new build, thanks.

**Comment by bsaby** [comment]
Test passed.
Build used:artifacts/WindowsAzurePlugin4EJ.develop.95.05-24-2017.zip.
