### ISSUE TITLE
[IntelliJ2017/2016] Upgrade the plugin after uncheck Help improve. The checkbox turns checked. [Windows] 

### ISSUE THREAD

**Issue by davidliangze** [Microsoft/azure-tools-for-java#541]
On IntelliJ with a previous plugin (I used daily.9), go File->Settings->Microsoft Tools->Azure, uncheck  Help improve. Then upgrade the Azure plugin (I used daily.10). 

**Expected:**
The checkbox should still be unchecked.

**Actual:**
The checkbox is checked.

**Comment by Eskibear** [comment]
It seems by design of IntelliJ IDEA. The operation `Upgrade` actually re-install the plugin when restarting IDE. It will first removes the whole plugin folder, including the file `data.xml` where settings are stored.
@davidliangze
