### ISSUE TITLE
[IntelliJ2016/2017] Telemetry message is not correct.[Windows/Mac/linux]

### ISSUE THREAD

**Issue by davidliangze** [Microsoft/azure-tools-for-java#543]
Upgrade the plugin and see the telemetry on portal.

Expected:
Show trace like AzurePlugin.Intellij.Plugin.Upgrade

Actual:
Show trace like AzurePlugin.Intellij.Plugin.Install

![capture](https://cloud.githubusercontent.com/assets/26756696/26344977/0437fcf2-3fd4-11e7-94d1-6b455a7e28b2.JPG)

**Comment by adashen** [comment]
It seems plugin upgrade in intelliJ is same as install, it will delete the plugin, and then install the new one

**Comment by davidliangze** [comment]
So is it by design?
