### ISSUE TITLE
[Intellij spark debug] The submit spark application to HDInsight will diabled after when run 'resume program F9'

### ISSUE THREAD

**Issue by ruoxinCheng** [Microsoft/azure-tools-for-java#558]
steps 1: Click Debug button
steps 2: Click 'Rusume program' to continue to run script
Then right click on project, you can see 'Submit Spark application to HDInsight' disabled.

![image](https://cloud.githubusercontent.com/assets/20041888/26400209/7c75f7b2-40b2-11e7-9365-002e4d8adf11.png)

**Comment by voidfunction** [comment]
Fix by #565

**Comment by ruoxinCheng** [comment]
Verified on windows, mac, Linux, it works.
