### ISSUE TITLE
[Intellij] we should auto restart after downloading scala Ide

### ISSUE THREAD

**Issue by ruoxinCheng** [Microsoft/azure-tools-for-java#559]
1. create project without install scala ide
2. popup a tips to download scala ide
Expect: we can auto restart after installing scala ide

**Comment by ziyel** [comment]
We can use the tips window mentioned in https://github.com/Microsoft/azure-tools-for-java/issues/582 to let user choose `restart` or `postpone`.

**Comment by ruoxinCheng** [comment]
Yes, it works.
