### ISSUE TITLE
[VM creation] SSH file selection dialog doesn't show hidden folders

### ISSUE THREAD

**Issue by jianghaolu** [Microsoft/azure-tools-for-java#56]
It makes sense for developers to use public keys under `.ssh` folder on Mac and Linux. But today the dialog doesn't show them.

Also I don't have the option NOT to provide a password.

<img width="1280" alt="screen shot 2017-02-17 at 10 17 11 am" src="https://cloud.githubusercontent.com/assets/2320445/23077648/55d5992c-f4fa-11e6-85d3-6a558d971cff.png">

**Comment by milismsft** [comment]
It's an issue on Mac only (Finder does not show the hidden directories by default); the user has the option to input the desired folder by typing it rather then browsing to it (or browse to the parent and type the rest of the path).

**Comment by jdneo** [comment]
By pressing `Command` + `Shift` + `.`  can reveal hidden files in Finder on Mac.
