### ISSUE TITLE
Plugin is not compatible with IntelliJ IDEA 2021.2

### ISSUE THREAD

**Issue by jonmclean** [microsoft/azure-tools-for-java#5639]
The plugin is not compatible with IDEA 2021.2.  See the JetBrains plugin page:  https://plugins.jetbrains.com/plugin/8053-azure-toolkit-for-intellij/versions

Since it is not compatible IDEA 2021.1 fails to load the plugin and no Azure integration is available.  Feel free to contact me if you have any questions.

This is the error in the IDEA Event Log:
8:52 AM	Plugin error: File '~\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\212.4746.92.plugins\azure-toolkit-for-intellij\lib\azure-toolkit-for-intellij.jar' contains invalid plugin descriptor

Thank you.

**Comment by Flanker32** [comment]
@jonmclean  Thanks a lot for your report, we are working on the IntelliJ 2021.2 migration and should be release in this week. Here is the related PR https://github.com/microsoft/azure-tools-for-java/pull/5634.

**Comment by Flanker32** [comment]
@jonmclean Thanks for your support, IntelliJ toolkit v3.55.1 has been released with IntelliJ 2021.2 support, you may get it [here](https://plugins.jetbrains.com/plugin/8053-azure-toolkit-for-intellij/versions/stable/131380)
