### ISSUE TITLE
Create service principal window has margin issues windows 10, 64 bit, 2560X1440 res

### ISSUE THREAD

**Issue by arroyc** [Microsoft/azure-tools-for-java#57]
![image](https://cloud.githubusercontent.com/assets/16231002/23077765/c164805e-f4fa-11e6-9f4f-b7ef8efbbd9b.png)

**Comment by bsaby** [comment]
My test machine doesn't support 2560X1440 resolution, so I can't verify this issue

**Comment by martinsawicki** [comment]
per Vlad, this is fixed
