### ISSUE TITLE
[Intellij ] dark theme issue

### ISSUE THREAD

**Issue by ruoxinCheng** [Microsoft/azure-tools-for-java#576]
![image](https://cloud.githubusercontent.com/assets/20041888/26517415/7677b82c-42ca-11e7-86d4-69b9f6b0745f.png)

**Comment by wezhang** [comment]
Related to #351

**Comment by ziyel** [comment]
Fixed. @ruoxinCheng , please help to test.

**Comment by ruoxinCheng** [comment]
Verified daily build, it fixed.
