### ISSUE TITLE
InteliJ IDEA plugin: Empty value for config-file causes issues on plugin load

### ISSUE THREAD

**Issue by ant-druha** [microsoft/azure-tools-for-java#5825]
Reported here https://stackoverflow.com/q/69203962/2000323

I've [checked](https://github.com/microsoft/azure-tools-for-java/blob/develop/PluginsAndFeatures/azure-toolkit-for-intellij/src/main/resources/META-INF/plugin.xml#L52) and the plugin has empty value for `config-file` attribute in the plugin descriptor:

```
  <depends optional="true" config-file="">org.intellij.scala</depends>
```

Now it may lead to problem when loading the plugin, see also this comment: https://youtrack.jetbrains.com/issue/IDEA-270963#focus=Comments-27-5056928.0-0

**Comment by t-rufang** [comment]
Fixed in #5857
