### ISSUE TITLE
Can't sign in to national cloud, such as Azure China?

### ISSUE THREAD

**Issue by allenhula** [Microsoft/azure-tools-for-java#586]
In the past, we can use publishsettings, but now this option is not available. Then how we can sign in Azure China and deploy?

**Comment by allenhula** [comment]
Another change is no service endpoint configuration provided any more. Which was like this [https://docs.microsoft.com/en-us/azure/azure-toolkit-for-eclipse-azure-service-endpoints](https://docs.microsoft.com/en-us/azure/azure-toolkit-for-eclipse-azure-service-endpoints). I am using latest build with latest eclipse.

**Comment by allenhula** [comment]
I tried to change values inside settings.json (path: %Program Files%\eclipse\jee-neon2\eclipse\configuration\org.eclipse.osgi\1211\0\.cp\resources\settings.json) to be:
  "adAuthority": "https://login.chinacloudapi.cn",
  "azureServiceManagementUri": "https://management.core.chinacloudapi.cn/",
  "graphApiUri": "https://graph.chinacloudapi.cn/",
But when I click sign in, it still routes to public azure. So seems like the used authority is hardcoded.

**Comment by Matthew-Dong** [comment]
If you attempt to access Azure China, could try the steps in "Java Developer connect to Azure China" at https://www.azure.cn/documentation/articles/developerdifferences/ 

For other national clouds, the steps are similar. First to generate auth file with Azure CLI, setting up the connection with that national cloud. Then to sign in with Automated Method from Azure Toolkits.

**Comment by allenhula** [comment]
Thank you.

**Comment by bbetstcw** [comment]
Hi Matthew, the steps to login is not working for Azure China any more. It's used to be good. But now, just cannot refresh any subscriptions. Can you help to find out what the issue really is.

**Comment by forester123** [comment]
Any update on this issue? Try both 1rmb and PIA subscriptions, still cannot see the subscription listed when using automated authentication method

**Comment by Eskibear** [comment]
Fixed, both interactive/automated sign-in methods are supported.

Ref:
https://github.com/Microsoft/azure-tools-for-java/issues/1109
https://github.com/Microsoft/azure-tools-for-java/issues/1146
