### ISSUE TITLE
"Deploy to cloud service" feature is removed

### ISSUE THREAD

**Issue by allenhula** [Microsoft/azure-tools-for-java#588]
After installed latest 3.0.3 version of Azure toolkit for Eclipse, "deploy to cloud service" is not there anymore. Is this feature removed?
![image](https://cloud.githubusercontent.com/assets/20550718/26712170/03bef084-4798-11e7-9272-7e02929038c6.png)

**Comment by martinsawicki** [comment]
as noted in https://github.com/Microsoft/azure-tools-for-java/issues/170
