### ISSUE TITLE
Can't remotely debug an WebApp in IntelliJ

### ISSUE THREAD

**Issue by clguimanMSFT** [microsoft/azure-tools-for-java#59]
* The configuration page doesn't allow the user to select a web app to remote debug:
![image](https://cloud.githubusercontent.com/assets/22645093/23077878/21e4c218-f4fb-11e6-9f15-98279f22807b.png)
The docs show this as working:
https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-debug-java-web-app-in-intellij

**Comment by martinsawicki** [comment]
as far as we know, this is due to proxy settings at MS Corp which prevent webSockets from working internally. If you try to do this from another network that doesn't use a proxy, or uses one that enables WebSockets, it would work. For example, from another Azure VM or from home typically.

**Comment by martinsawicki** [comment]
at least we'll want to make sure that the "non-Microsoft Corp" network scenario keeps working as it did

**Comment by vladimir-shcherbakov** [comment]
Move to backlog.

**Comment by selvasingh** [comment]
We are temporarily removing debug experience. Will bring it as soon as it is ready for prime time

**Comment by solutionsdirekt** [comment]
I'm a couple years late to the issue. But it seems like prime time didn't happen by now. Maybe the Microsoft documentation should be changed to something like not working anymore. Is there are workaround to this issue?

**Comment by Flanker32** [comment]
Close the issue as remote debugging is removed from IntelliJ toolkit
