### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception: Cannot create class mobi.hsz.idea.gitignore.lang.IgnoreParserDefinition

### ISSUE THREAD

**Issue by kad-eversa** [microsoft/azure-tools-for-java#5934]
IntelliJ build version: 2021.2.2 IU-212.5284.40
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.12
Plugin version: 3.57.1-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.intellij.diagnostic.PluginException: Cannot create class mobi.hsz.idea.gitignore.lang.IgnoreParserDefinition (classloader=PluginClassLoader(plugin=PluginDescriptor(name=.ignore, id=mobi.hsz.idea.gitignore, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2021.2\plugins\.ignore, version=4.2.0, package=null)

**Comment by Flanker32** [comment]
@kad-eversa Thanks for your report, could you please help share some more info like is there any way to reproduce this issue? 

Besides, `IgnoreParserDefinition` seems to be a class of [.​ignore](https://plugins.jetbrains.com/plugin/7495--ignore/versions) plugin, could you please try upgrade [.​ignore](https://plugins.jetbrains.com/plugin/7495--ignore/versions) plugin to the latest version and try again?
