### ISSUE TITLE
[IntelliJ2017/2016]Application insight: Error during artifact deployment.

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#594]
Build: 
artifacts/azure-toolkit-for-intellij.2016.develop.113.06-06-2017.zip
artifacts/azure-toolkit-for-intellij.2017.develop.113.06-06-2017.zip

Right click project choose Configure Application Insights...
After insight configuration , run the project

 **Server Log:**
......
Connected to server
[2017-06-06 12:44:01,801] Artifact hello9: Artifact is being deployed, please wait...
06-Jun-2017 00:44:03.114 INFO [RMI TCP Connection(5)-127.0.0.1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
AI: INFO 06-06-2017 00:44, 57: Registering WebApp with name 'ROOT'
AI: ERROR 06-06-2017 00:44, 57: Failed to register 'ApplicationInsightsWebFilter', exception: 'com/microsoft/applicationinsights/agent/internal/coresync/AgentNotificationsHandler'
AI: INFO 06-06-2017 00:44, 57: Configuration file has been successfully found as resource
06-Jun-2017 00:44:03.538 SEVERE [RMI TCP Connection(5)-127.0.0.1] org.apache.catalina.core.StandardContext.startInternal One or more Filters failed to start. Full details will be found in the appropriate container log file
06-Jun-2017 00:44:03.539 SEVERE [RMI TCP Connection(5)-127.0.0.1] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors
[2017-06-06 12:44:03,555] Artifact hello9: Error during artifact deployment. See server log for details.
06-Jun-2017 00:44:11.462 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [C:\Users\v-sunxi\Desktop\apache-tomcat-8.5.15\webapps\manager]
06-Jun-2017 00:44:11.536 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [C:\Users\v-sunxi\Desktop\apache-tomcat-8.5.15\webapps\manager] has finished in [72] ms

**Tomcat Catalina Log:**
06-Jun-2017 00:44:03.539 SEVERE [RMI TCP Connection(5)-127.0.0.1] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors

**Comment by adashen** [comment]
It seems the library added to the web app project missing httpcore, httpclient jars

**Comment by adashen** [comment]
https://github.com/Microsoft/azure-tools-for-java/blob/a315479aae801a710dee4d010d77b09aced01004/PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/intellij/ui/libraries/AzureLibrary.java

Lots of hard coded package version in this file need to update the packages

**Comment by adashen** [comment]
Also need to check "Libraries Configuration"

**Comment by adashen** [comment]
Please try the this build to test
http://vscjavaci.cloudapp.net/job/AzureToolsManager_develop/127/Azure/

**Comment by adashen** [comment]
fixed by [https://github.com/Microsoft/azure-tools-for-java/pull/614](url)

**Comment by bsaby** [comment]
Test passed.
BUild used:
artifacts/azure-toolkit-for-intellij.2016.develop.127.06-09-2017.zip
artifacts/azure-toolkit-for-intellij.2017.develop.127.06-09-2017.zip
