### ISSUE TITLE
The Create App Service dialog box never appears

### ISSUE THREAD

**Issue by mfrancisco1977** [microsoft/azure-tools-for-java#598]
I have upgraded the Eclipse Azzure toolkid  up to version 3.0.3 and now when I start my Eclipse, the following message appears:

![image](https://cloud.githubusercontent.com/assets/19196128/26826273/15ad509a-4a7e-11e7-8d04-f0df77d6266d.png)

After upgraded the plug-in version, I was able to connect sucessfully to the Azure Plataform; however when I trieded to publish my application on my free azure account, the boton Create on the Deploy Web App dialog box didnn't work and the create app service dialogo box never appears.

![image](https://cloud.githubusercontent.com/assets/19196128/26826819/0ff07a5e-4a80-11e7-9ef8-202b18fbdadd.png)

When I went to uninstall those old versions of Azure plugin components I found that those didn't exist.

![image](https://cloud.githubusercontent.com/assets/19196128/26827528/4fa1c9c0-4a83-11e7-8962-6c58880ec777.png)

I really apreciate your help with this issue. Thanks!

**Comment by Flanker32** [comment]
The issue should be fixed in the latest release
