### ISSUE TITLE
Provide quick link/better message to setup docker host

### ISSUE THREAD

**Issue by anuchandy** [Microsoft/azure-tools-for-java#60]
Trying to follow the doc container-work-flow-by-milis.pdf, I don't have any "DocketHost" and "LoginSessions" exists in my editor, hence while trying to "Deploy as docker container" we show below message:

It would be nice if we can show what to do 

![unexpectedparamvaules](https://cloud.githubusercontent.com/assets/1471612/23077873/1ed69448-f4fb-11e6-8e75-8558608ecf0c.png)

(a). Instructions about where to go in plugin to setup docker host 
OR
(b) A link from this message box that point to 'setup docker host' dialog

**Comment by anuchandy** [comment]
Ok ignore this issue, as soon as i click "OK", plugin shows dialog to set up dicker host.

**Comment by milismsft** [comment]
Should be fixed in the latest version. This error was triggered while trying to get a status of the Docker images and containers for all the VMs that we detect as possible Docker hosts but there was an error reading the log in credentials (they were missing).
