### ISSUE TITLE
[Eclispe] Redis Cache-> Creating an existing resource group doesn't prompt an error or message

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#600]
Build: daily27

EXPEXT:
Check the resource group name and there is a message prompt if the name already exists.
RESULT:
No error or message.

**Comment by jdneo** [comment]
@bsaby Fixed in **Intellij**(Eclipse is not ready yet). Please help verify, thanks.

**Comment by bsaby** [comment]
Test passed in Intellij.
BUild used: artifacts/azure-toolkit-for-intellij.2017.develop.146.06-13-2017.zip
![image](https://user-images.githubusercontent.com/22470312/27114986-2070320e-50fa-11e7-8149-2deef759f6f7.png)

**Comment by jdneo** [comment]
@bsaby Fixed in Eclipse, please help verify it, thanks.

**Comment by bsaby** [comment]
Test passed. 
Build used:
