### ISSUE TITLE
[IntelliJ][ReportedByUser] class com.microsoft.azure.toolkit.intellij.connector.Connection cannot be cast to class com.microsoft.azure.toolkit.lib.springcloud.SpringCloudApp

### ISSUE THREAD

**Issue by dvag-joerg-winter** [microsoft/azure-tools-for-java#6020]
IntelliJ build version: 2021.2.3 IU-212.5457.46
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.12
Plugin version: 3.57.1-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,3841x1599,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=update failed for AnAction(com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager$AnActionWrapper, id=action.springcloud.app.stream_log), throwable=java.lang.ClassCastException: class com.microsoft.azure.toolkit.intellij.connector.Connection cannot be cast to class com.microsoft.azure.toolkit.lib.springcloud.SpringCloudApp (com.microsoft.azure.toolkit.intellij.connector.Connection and com.microsoft.azure.toolkit.lib.springcloud.SpringCloudApp are i

**Comment by Flanker32** [comment]
Error message: Uncaught Exception update failed for AnAction(com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager$AnActionWrapper, id=action.springcloud.app.stream_log) java.lang.ClassCastException: class com.microsoft.azure.toolkit.intellij.connector.Connection cannot be cast to class com.microsoft.azure.toolkit.lib.springcloud.SpringCloudApp (com.microsoft.azure.toolkit.intellij.connector.Connection and com.microsoft.azure.toolkit.lib.springcloud.SpringCloudApp are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @14e94b02)

**Comment by wangmingliang-ms** [comment]
Can you update the plugin to the latest version and retry?
