### ISSUE TITLE
[IntelliJ][ReportedByUser] Not all web apps in subscription are displaying

### ISSUE THREAD

**Issue by ash-skelton** [microsoft/azure-tools-for-java#6042]
#### Setup

IntelliJ build version: 2021.2 IU-212.4746.92
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.58.0-2021.2

####  Describe the bug

After logging in to the Azure Explorer in IntelliJ, I can see all relevant subscriptions that I have access to. However, after selecting one, not all web apps under that subscription are being displayed. However, I have access to them directly in the Azure Portal. I've tried logging out/in, refreshing etc... 

Is there something else that could be blocking the plugin from locating all web apps? Permissions issue?

**Comment by Flanker32** [comment]
@ash-skelton Thanks for your report, is there any exception during refresh the azure explorer? Could you please help share the log for intellij? You may get them by `Help` -> `Open log in explorer`.

Besides, could you please help check whether this issue occurs in other tools like azure cli? You may list the web apps with `az webapp list`.

**Comment by ash-skelton** [comment]
Hi @Flanker32... thanks for the quick reply!

idea.log attached (just from an empty project, attempting to refresh the Azure Explorer).... from what I can see, there's no specific errors. 

The issue does not occur in azure cli and `az webapp list` shows the webapps that are missing in IntelliJ. I can even see the Resource Groups that the missing webapps belong to in the Azure Explorer plugin. I'm not sure what else I can look at

[idea.log](https://github.com/microsoft/azure-tools-for-java/files/7475778/idea.log)


It's also worth noting that other members of my team who have the same access to the subscriptions are able to see Web Apps that don't show up for me!

**Comment by Flanker32** [comment]
@ash-skelton Thanks for your information, yes there should be no exception during list the resources, but more like an authentication issue as your teammates could see the full resources. 
Could you try other authentication methods and see whether the issue still reproduce? Besides, could you please try sign in with your teammates account to see whether this is an issue for the toolkit installation?

**Comment by ash-skelton** [comment]
> @ash-skelton Thanks for your information, yes there should be no exception during list the resources, but more like an authentication issue as your teammates could see the full resources. Could you try other authentication methods and see whether the issue still reproduce? Besides, could you please try sign in with your teammates account to see whether this is an issue for the toolkit installation?

I tried logging in to the Explorer via Azure CLI (consuming existing CLI credentials).... and that still didn't work. It's strange as Azure CLI works fine outside of IntelliJ and lists all of the web apps I would expect to see, so you would expect that the plugin in IntelliJ would get the same list when logging in using this method. 

Some webapps in the selected subscription display, just not all of them so I don't know how it could be an authentication issue either - otherwise I'd expect no web apps to be listed at all.

**Comment by Flanker32** [comment]
@ash-skelton Thanks for your report, I used to guess some auth method may auth you with account without access to some of the webapp, but this issue could be reproduced with azure cli so this should not be the casue.  
And as you said your teammates could see the all the web apps, so could you please try auth your account in your teammates' PC and also try auth your teammates account in your installation to see whether this is an issue with your toolkit installation or an issue with the account?
