### ISSUE TITLE
Icon in dracula theme on MAC, is not visible (properly) unless you select item.

### ISSUE THREAD

**Issue by anudeepsharma** [Microsoft/azure-tools-for-java#61]
This is applicable for items under HDInsights and Virtual Machines.

<img width="293" alt="screen shot 2017-02-17 at 1 18 26 pm" src="https://cloud.githubusercontent.com/assets/6544078/23083659/a619d6fa-f513-11e6-8773-bd11f18375fe.png">
<img width="157" alt="screen shot 2017-02-17 at 1 18 40 pm" src="https://cloud.githubusercontent.com/assets/6544078/23083658/a6192c14-f513-11e6-8a5e-7021a65200ec.png">

**Comment by martinsawicki** [comment]
need better icons

**Comment by martinsawicki** [comment]
too late for v3 if we don';t have them yet

**Comment by lenala** [comment]
Icons were updated, please verify.

**Comment by bsaby** [comment]
Test passed, using artifacts/azure-toolkit-for-intellij.2017.318.04-18-2017.zip.
