### ISSUE TITLE
[Eclipse]Docker: An error dialog pops out after clicking Docker Run[Linux]

### ISSUE THREAD

**Issue by davidliangze** [Microsoft/azure-tools-for-java#610]
Build: artifacts/WindowsAzurePlugin4EJ.develop.125.06-08-2017.zip

Repro step:
1. New a dynamic web project and new a JSP file under the directory WebContent.
2. Right click the project ->Azure ->Add Docker Support
3. A message shows the Dockerfile successfully created, click OK.(It did when I check in the project) 
4. Right Click the project ->Azure ->Docker Run.

**Expected:**
It will package war file, build image, create and start a container. Then a dialog will pop out to show the details.

**Actual:**
An error dialog pops out.
![1](https://user-images.githubusercontent.com/26756696/26919459-59fb39ba-4c68-11e7-9c39-6b16303fb1b7.JPG)
Click and another dialog shows.
![2](https://user-images.githubusercontent.com/26756696/26919502-8b67e160-4c68-11e7-935c-5cea76940474.JPG)

Then I check in Terminal, neither environment variables can be shown.
![3](https://user-images.githubusercontent.com/26756696/26919718-2f7b4058-4c69-11e7-80c8-1816be3aa28b.JPG)
@Eskibear

**Comment by bsaby** [comment]
Build daily32
Click Docker run, then shown as below:
![image](https://user-images.githubusercontent.com/22470312/27019530-d4f3e04e-4f6b-11e7-8ba8-851bc2f51785.png)

**Comment by adashen** [comment]
@bsaby  More information of the os information? And docker version

**Comment by bsaby** [comment]
Linux: ubuntu 16.04.2 LTS
Docker: 17.03.1-ce

**Comment by bsaby** [comment]
Build image using command line :
![image](https://user-images.githubusercontent.com/22470312/27021166-1e652406-4f79-11e7-8e93-416b19d4787a.png)

**Comment by adashen** [comment]
@Eskibear It seems a linux specific issue

**Comment by bsaby** [comment]
The eclipse from the desktop does not have permission to access the docker daemon, that's why the image building  failed.Only the eclipse which start in the root authority can normally use this feature.

**Comment by adashen** [comment]
Need detail error message

**Comment by Eskibear** [comment]
It can show detailed error messages now.  e.g.
```
[INFO]    Connecting to docker daemon ... 
[ERROR]    Error occurred in Docker Run, with exception:
java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: Permission denied
```
Please verify it, thx.

**Comment by davidliangze** [comment]
Test passed using latest build dev.146
