### ISSUE TITLE
[Eclipse]Docker: Icon issue

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#611]
Build: dev125
![image](https://user-images.githubusercontent.com/22470312/26923249-1c8e9124-4c74-11e7-8a0d-d3777ca9b94e.png)

![image](https://user-images.githubusercontent.com/22470312/26923189-e88a0854-4c73-11e7-9e8e-7a6c5170ead1.png)

**Comment by Eskibear** [comment]
It's by design, once there's a Dockerfile detected in `dockerContext` folder, it hides `Add Docker Support` button and shows `Docker Run`

**Comment by Eskibear** [comment]
The temporary icon is now removed. 
Icon will be added once it's ready.

**Comment by Eskibear** [comment]
please verify latest develop build

**Comment by bsaby** [comment]
Test passed.
BUild used:
![image](https://user-images.githubusercontent.com/22470312/28060138-f469c64c-6658-11e7-9009-ee7fe933254e.png)

![image](https://user-images.githubusercontent.com/22470312/28060087-ce58b83c-6658-11e7-91b2-1f5a5635355c.png)
