### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception update failed for AnAction(com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction, id=Actions.SubmitSparkApplicationAction) with text=Submit Apache Spark Application

### ISSUE THREAD

**Issue by zluoabr** [microsoft/azure-tools-for-java#6121]
IntelliJ build version: 2021.2.3 IU-212.5457.46
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.12
Plugin version: 3.58.0-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=update failed for AnAction(com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction, id=Actions.SubmitSparkApplicationAction) with text=Submit Apache Spark Application, throwable=java.lang.RuntimeException: Cannot find service software.aws.toolkits.jetbrains.core.experiments.ToolkitExperimentManager (classloader=PluginClassLoader

**Comment by Flanker32** [comment]
Exception:
 java.lang.RuntimeException: Cannot find service software.aws.toolkits.jetbrains.core.experiments.ToolkitExperimentManager (classloader=PluginClassLoader(plugin=PluginDescriptor(name=AWS Toolkit, id=aws.toolkit, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2021.2\plugins\aws-toolkit-jetbrains, version=1.34-212, package=null), packagePrefix=null, instanceId=198, state=active))

**Comment by wezhang** [comment]
Thanks! Dup #5955
