### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Scheduler worker in group main failed with an uncaught exception com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: deploy artifact to web app ()

### ISSUE THREAD

**Issue by michaelNGV** [microsoft/azure-tools-for-java#6143]
IntelliJ build version: 2021.2 IU-212.4746.92
OS: Linux
JDK: Oracle Corporation 11.0.10
Plugin version: 3.58.0-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,2,29,1920x1080,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Scheduler worker in group main failed with an uncaught exception, throwable=com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: deploy artifact to web app ()
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:81)
	at com.microsoft.azure.toolkit.intellij.webapp.runner.webappconfig.WebAppRunState.executeSteps(WebAppRunState.java:76)
	at com.microsoft.azure.toolkit.intellij.webapp.runner.webappconfig.WebAppRunState.executeSteps(WebAppRunState.java:51)
	at com.microsoft.azure.toolkit.intellij.common.AzureRunProfileState.lambda$execute$0(AzureRunProfileState.java:55)
Caused by: com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: upload artifact(kitten-0.0.1-SNAPSHOT.jar) to app(rabbitv2)

**Comment by Flanker32** [comment]
@michaelNGV Thanks a lot for your report, could you please help share some more info like the full error stack?

**Comment by michaelNGV** [comment]
I can't now because I've moved-on from the point of the crash.  If you needed that information, the plugin should be programmed to save it.  I can't provide any further information, so if you _need_ further information, you can't process this report so you might as well close it.

**Comment by Flanker32** [comment]
@michaelNGV Sorry for the confusing, IntelliJ should save the error stacks to the .idea log file, could you please help check and share the stack if exists? You may get the log from `Help` -> `Show Log in Explorer`

**Comment by michaelNGV** [comment]
[idea.log](https://github.com/microsoft/azure-tools-for-java/files/7599977/idea.log)

**Comment by Flanker32** [comment]
@michaelNGV Thanks for the info, it seems that there is no related stack trace in the log. Could the you please re-try the deployment and see whether the issue could be reproduced?

**Comment by michaelNGV** [comment]
Pretty sure the attached contains the trace.  Sorry about previously -- too much haste.
[idea.log](https://github.com/microsoft/azure-tools-for-java/files/7600618/idea.log)

**Comment by Flanker32** [comment]
@michaelNGV Thanks a lot help! It seems that the error track did not append to idea.log, I'll check the issue later.

For this issue, is the issue stable reproduced? If so, could you please share the output of deployment console? Besides, we used to meet a similar issue that terminate the deployment process may not kill the deployment thread in some cases, and it will throw exception, did you meet the same issue?

**Comment by michaelNGV** [comment]
I don't know how to reproduce the issue.  It happens occasionally so next time it occurs, I will open another GH ticket.
