### ISSUE TITLE
Redis Cache ->The subscription name can appear in the property table

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#616]
I think that the subscription name also can appear in the property table.
RESULT:
![image](https://user-images.githubusercontent.com/22470312/26959736-40301af4-4d04-11e7-84cb-7ac83f34e8ad.png)
EXPECT:
![image](https://user-images.githubusercontent.com/22470312/26959762-6acb7218-4d04-11e7-8512-dc1b1f25cb30.png)
@jdneo

**Comment by jdneo** [comment]
Will try to add Subscription name in the property panel

**Comment by andxu** [comment]
Very trivial

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738752

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
