### ISSUE TITLE
Netty Error on M1: Unable to load io.netty.resolver.dns.macos

### ISSUE THREAD

**Issue by mariussoutier** [microsoft/azure-tools-for-java#6168]
Using the Azure Tools in IntelliJ doesn't work, I'm getting `Unable to load io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS.`. This seems to be a bug in Netty when used on an M1 Mac. Upgrading Netty to 4.1.68.Final should resolve the problem.

Also see https://github.com/netty/netty/issues/11693.

**Comment by andxu** [comment]
see #6048, it is already on the next milestone(Dec release).

**Comment by mariussoutier** [comment]
Sorry and thanks!
