### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Scheduler worker in group main failed with an uncaught exception

### ISSUE THREAD

**Issue by gagandeep-singh-maersk** [microsoft/azure-tools-for-java#6188]
IntelliJ build version: 2021.3 IU-213.5744.223
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.59.0-2021.3
Additional Info: None
Parent component: 
`

reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.resourcemanager.appservice.models.DefaultErrorResponseErrorException: Status code 403, "{"error":{"code":"AuthorizationFailed","message":"The client 'g.singh@maersk.com' with object id 'ecc1c0dd-8028-4bc5-8a6c-12b6478b15aa' does not have authorization to perform action 'Microsoft.Web/sites/config/list/action' over scope '/subscriptions/b102078a-e5f0-4de2-b65a-121765959be5/resourceGroups/rg-docm-commoninfra-pp/providers/Microsoft.Web/sites/docm-audit-event-consumerpp/config/appsettings' or the scope is invalid. If access was recently granted, please refresh your credentials."}}": The client 'g.singh@maersk.com' with object id 'ecc1c0dd-8028-4bc5-8a6c-12b6478b15aa' does not have authorization to perform action 'Microsoft.Web/sites/config/list/action' over scope '/subscriptions/b102078a-e5f0-4de2-b65a-121765959be5/resourceGroups/rg-docm-commoninfra-pp/providers/Microsoft.Web/sites/docm-audit-event-consumerpp/config/appsettings' or the scope is invalid. If access was recently granted, please refresh your credentials.

**Comment by Flanker32** [comment]
@gagandeep-singh-maersk Thanks for your report and really sorry for the late response. It seems that the toolkit are trying to list the resources without privilege and the request was rejected by Azure. If you have the access, could you please try re-sign in the toolkit and try again?
