### ISSUE TITLE
When running and stopping functions locally using the plugin, func processes keep running on the system

### ISSUE THREAD

**Issue by peterdemaeyer** [microsoft/azure-tools-for-java#6197]
I just got started with Azure's sample `HttpTriggerFunction` function (the "hello world" of Azure) in IntelliJ (on Ubuntu impish).
I am running on my local system, so not on the Azure cloud.
I can start and run a function using the "Play" button in the marging, and it's working - it's accepting HTTP requests.
![image](https://user-images.githubusercontent.com/1440594/145729054-22c57a3c-ac6c-4480-9ff6-76e7bced2eb4.png)
I can stop the function using the "Stop" button in the "Run" panel.
![image](https://user-images.githubusercontent.com/1440594/145729079-97d90042-9b67-4c24-8712-367b596a2a73.png)
However, the processes keep on running: `jps` shows a pile-up of `<pid> azure-functions-java-worker.jar` processes.

It seems that, whenever I change code and restart the function, it restarts on a new port, and all the previous ones on the previous ports continue to run too. That is not what I expect, I expect that when I hit the "Stop" button, the function stops running.

As a workaround, I regularly do `killall -9 func` on my system to get rid of the lingering processes.

**Comment by Flanker32** [comment]
@peterdemaeyer Thanks for your report, this may be an issue of function core tools configuration, could you please help share the screen shot of your azure settings?  You may get it by `File` -> `Settings` -> `Microsoft` -> `Azure`
![image](https://user-images.githubusercontent.com/12445236/146112485-0f0e1165-495a-4153-9ea9-f12fe2df7449.png)

**Comment by peterdemaeyer** [comment]
![image](https://user-images.githubusercontent.com/1440594/146143886-244f9f54-90b4-4e8b-bf93-dc74ef452e48.png)

**Comment by Flanker32** [comment]
@peterdemaeyer Thanks for your help and really sorry for the late response, we have released toolkit v3.62.0 with fix for this issue, could you please upgrade to the latest version and try again? Many thanks!
