### ISSUE TITLE
[VM creation] Provider namespace not registered

### ISSUE THREAD

**Issue by jianghaolu** [Microsoft/azure-tools-for-java#62]
Someone has to do this. Either SDK or plugin.

<img width="1280" alt="screen shot 2017-02-17 at 10 29 07 am" src="https://cloud.githubusercontent.com/assets/2320445/23078029/ef8cf3b6-f4fb-11e6-9e46-0a9264752ea3.png">

**Comment by martinsawicki** [comment]
probably better done in the SDK but need to figure out an approach

**Comment by selvasingh** [comment]
I am bumping into this when I use a new subscription. Tool should take care of this

**Comment by milismsft** [comment]
This is already fixed...
