### ISSUE TITLE
[RedisCache] The redis cache node does not show creating identifier when creating

### ISSUE THREAD

**Issue by jdneo** [Microsoft/azure-tools-for-java#620]
<img width="390" alt="screen shot 2017-06-12 at 10 15 41 am" src="https://user-images.githubusercontent.com/6193897/27017069-27019b06-4f58-11e7-9d69-39de0e0e4d1b.png">

reproduce step:
1. right click the redis cache node, and click "creating redis cache"
2. fill the form and click ok button

expect:
The creating node will show (creating...) identifier

result:
No such identifier is shown.

**Comment by jdneo** [comment]
@bsaby Fixed, please verify this in tomorrow's daily build. Thanks

**Comment by bsaby** [comment]
Test passed.
Builds used:
artifacts/azure-toolkit-for-intellij.2016.develop.137.06-12-2017.zip
artifacts/azure-toolkit-for-intellij.2017.develop.137.06-12-2017.zip
artifacts/WindowsAzurePlugin4EJ.develop.137.06-12-2017.zip
