### ISSUE TITLE
[Eclipse.RedisCache][Mac]UI Issue of the redis cache property view

### ISSUE THREAD

**Issue by jdneo** [Microsoft/azure-tools-for-java#622]
The Redis Cache Property View has some UI problem on Mac. The background color of the textfield should be the same as the view panel.

<img width="509" alt="screen shot 2017-06-12 at 10 25 49 am" src="https://user-images.githubusercontent.com/6193897/27017298-160018da-4f5a-11e7-9e45-9ca4aeaaaff0.png">

**Comment by bsaby** [comment]
Linux has the same UI problem

**Comment by jdneo** [comment]
@bsaby Fixed please help verify this issue in tomorrow's daily build, thanks!

**Comment by bsaby** [comment]
Mac Repro:
Build used: Daily 33
![image](https://user-images.githubusercontent.com/22470312/27064650-0eda2664-502b-11e7-988b-94dbb071585c.png)

**Comment by jdneo** [comment]
@bsaby Fixed please help verify this issue in the new build, thanks!

**Comment by bsaby** [comment]
Test passed in Mac.
Build used: artifacts/WindowsAzurePlugin4EJ.develop.142.06-13-2017.zip.
![image](https://user-images.githubusercontent.com/22470312/27068138-112f76ce-5041-11e7-8076-1e1702551221.png)
