### ISSUE TITLE
Azure Toolkit: “Copy&Open” action name is confusing

### ISSUE THREAD

**Issue by tkapustina** [microsoft/azure-tools-for-java#6228]
The original report: https://youtrack.jetbrains.com/issue/RIDER-71782

STR:
Try to sign in to Azure via Device Login
![image](https://user-images.githubusercontent.com/48007045/146338828-2bf22382-519c-4aa9-a7f0-5597a1bcd64b.png)

ACTUAL: The name is not clear enough

**Comment by wangmingliang-ms** [comment]
`Copy the code and Open browser` may be too long to be button text.
how about simplify the button text to `Open` but add a _copy icon_ right after the code?
