### ISSUE TITLE
[Eclipse.RedisCache]Should display multiple property view for different Redis Cache resource

### ISSUE THREAD

**Issue by jdneo** [Microsoft/azure-tools-for-java#626]
Currently, we can only  show one property view for redis cache node. When the user want to see another redis cache's property, the older one will be covered.

**Comment by jdneo** [comment]
@bsaby Fixed, please verify this in tomorrow's daily build, thanks

**Comment by bsaby** [comment]
Test passed.
Builds used: artifacts/WindowsAzurePlugin4EJ.develop.137.06-12-2017.zip
