### ISSUE TITLE
[Eclipse.Container]Eclipse will be hung when running docker run for the first time

### ISSUE THREAD

**Issue by jdneo** [Microsoft/azure-tools-for-java#629]
When I click docker run for the first time. The eclipse will be hung. Maybe we can put the building image process to the background thread.

**Comment by Eskibear** [comment]
Exactly.
It's probably due to: For the first time, downloading Tomcat image takes time.

**Comment by adashen** [comment]
@jdneo help to verify and close

**Comment by jdneo** [comment]
Test passed.
Build used: artifacts/WindowsAzurePlugin4EJ.develop.146.06-13-2017.zip
