### ISSUE TITLE
Canceling "Updating Azure Local Cache" dialog will hang IntelliJ indefinitely 

### ISSUE THREAD

**Issue by clguimanMSFT** [Microsoft/azure-tools-for-java#63]
I clicked "Refresh Subscriptions" and after a few seconds I canceled the "Updating Azure Local Cache" operation. 
The cancel operation doesn't have a timeout so IntelliJ will hang for ever and I need to kill the process.

**Comment by hovsepm** [comment]
+1 reproed

**Comment by songkaiape** [comment]
Reproduced this issue in azure-toolkit-for-intellij.14.zip

**Comment by vladimir-shcherbakov** [comment]
@songkaiape,
Could please give me detailed steps to reproduce?

**Comment by bsaby** [comment]
Not repro in artifacts/azure-toolkit-for-intellij.18.zip
