### ISSUE TITLE
[Eclipse.Container]Cannot perform "Docker Run" again if the container is removed through docker cli

### ISSUE THREAD

**Issue by jdneo** [Microsoft/azure-tools-for-java#632]
Reproduce steps:
1. Create a dynamic web project
2. Click "Add docker support"
3. Click "Docker run"
4. Remove the container through docker cli in terminal
5. Click "Docker run" again

expect:
Docker successfully run

result:
The console shows: **[ERROR]	Error occurred in Docker Run**

**Comment by Eskibear** [comment]
fixed in #634
