### ISSUE TITLE
[IntelliJ] https://msopentech.com/ does not reply during initial login

### ISSUE THREAD

**Issue by denissp** [Microsoft/azure-tools-for-java#633]
I'm using SSO with Azure within my organization and during login process everything stops at redirecting to https://msopentech.com/?code=XXX&session_state=XXX

**Comment by adashen** [comment]
Can you provide more information like,
1. Which plugin version are you using?
2. Is there any log file
3. Screen Shot?

**Comment by denissp** [comment]
Hi

Plugin version 3.0.30-2017.1

I'm using interactive login

This is list of request from plugin
https://login.microsoftonline.com/common/oauth2/authorize?return-client-request-id=true&resource=https%3A%2F%2Fmanagement.azure.com%2F&client-request-id=XXX&response_type=code&**redirect_uri=https%3A%2F%2Fmsopentech.com%2F**&prompt=login&client_id=XXXX

https://login.microsoftonline.com/common/oauth2/authorize?return-client-request-id=true&resource=https%3A%2F%2Fmanagement.azure.com%2F&client-request-id=XXX&response_type=code&redirect_uri=https%3A%2F%2Fmsopentech.com%2F&prompt=login&client_id=XXXX

https://login.microsoftonline.com/login.srf

https://msopentech.com/?code=XXX&session_state=XXX

and on last request system hung.

I also unable to open https://msopentech.com/ from browser (only unsecure version is available)
