### ISSUE TITLE
log4j-core-2.14.1.jar.  reported on the Azure Toolkit for IntelliJ plugin on MacBook

### ISSUE THREAD

**Issue by sabarinathankrish** [microsoft/azure-tools-for-java#6334]
Hi Team, 

We are using the Azure Toolkit for IntelliJ plugin on the IntelliJ IDEA application. Based on the recent scan results we can see the plugin is using the log4j-core-2.14.1.jar. files and its showing as vulnerable in our console. Please find the below infected path and suggest. 

/Users/Username/Library/Application Support/JetBrains/IntelliJIdea2021.2/plugins/azure-toolkit-for-intellij/lib/log4j-core-2.14.1.jar#

Thanks, 
Sabarinathan K

**Comment by akaroml** [comment]
@sabarinathankrish Thanks for reaching out. There's a new version (3.60.2) in the marketplace that has the updated log4j (2.17.1). Please try to update to the newest version to resolve this problem.
