### ISSUE TITLE
[Eclipse]Redis Cache-> Each property window should have a specific name

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#635]
RESULT:
![image](https://user-images.githubusercontent.com/22470312/27064109-3ba8dc92-5028-11e7-881b-6f007b27ccb1.png)
EXPEXT:
![image](https://user-images.githubusercontent.com/22470312/27064114-4a7075fa-5028-11e7-9522-e53b5139fc99.png)
@jdneo

**Comment by jdneo** [comment]
@bsaby Fixed, please help verify this issue in the new build, thanks!

**Comment by bsaby** [comment]
Test passed.
Build used: artifacts/WindowsAzurePlugin4EJ.develop.144.06-13-2017.zip.
