### ISSUE TITLE
[IntelliJ]Redis Cahce ->One redis cahce should display one property window

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#636]
Right click a redis cache
Click Show properties multiple times

RESULT:
Show mulitiple  properties windows with the same name
![image](https://user-images.githubusercontent.com/22470312/27064402-b847cf00-5029-11e7-9796-9fdc40d26e40.png)

EXPEXT:
One redis cahce should only display one property window
@jdneo

**Comment by jdneo** [comment]
@bsaby Fixed, please help verify this issue in the new build, thanks.

**Comment by bsaby** [comment]
Test passed.
Build used: 
artifacts/azure-toolkit-for-intellij.2016.develop.144.06-13-2017.zip
artifacts/azure-toolkit-for-intellij.2017.develop.144.06-13-2017.zip
