### ISSUE TITLE
Intellij - For gradle projects, azure function debug does not pre-package inter-module  dependencies, resulting in classdefnotfound error

### ISSUE THREAD

**Issue by wcom939** [microsoft/azure-tools-for-java#6376]
For gradle projects, create a vanilla gradle project
then create two modules:
1. with an azure function using v4
2.  some other gradle module with a custom class

3. In the build.gradle of the azure function module refer to the module from step two in the dependencies block
4. In the function refer to the custom class from the module created in step 2.

Debug the function using the azure functions debug run configuration template, when it hits the custom class it will result in a "classdefnotfound" exception

Debugging the function using the azure functions gradle plugin + remote java debug intellij run configuration results in the function proceeding as expected

**Comment by Flanker32** [comment]
@wcom939 Thanks for your help, this issue should been resolved in the latest release v3.62.0, could you please upgrade to the latest version and try again, many thanks!
