### ISSUE TITLE
Intellij - Azure function gradle template does not properly link to project, and does not work if integrating into existing gradle project

### ISSUE THREAD

**Issue by wcom939** [microsoft/azure-tools-for-java#6377]
1. Create a new gradle azure functions project
2. the build.gradle does not auto link, resulting in intellij suggesting an auto linkage, this should be fixed

--existing project:
1. create a vanilla gradle java project
2. right click project and create a new module
3. create a new azure functions gradle project

several issues here:
1. The azure functions gradle project has its own settings.gradle file which is incorrect, instead the child module should be part of the parent settings.gradle file
2. same issue as above the build.gradle is not auto linked so it doesnt appear in the gradle side build menu

**Comment by Flanker32** [comment]
@wcom939 Thanks for your report, we will investigate this issue soon.

**Comment by Flanker32** [comment]
@wcom939 Thanks again for your help, the auto import issue for new gradle project has been resolved in the latest release v3.62.0, could you please upgrade to the latest version and try again, many thanks!

We are still working on the submodule support for gradle, will update here once there are updates.
