### ISSUE TITLE
[IntelliJ][ReportedByUser] Customer Issues - spuriously adding before launch package command

### ISSUE THREAD

**Issue by tschn** [microsoft/azure-tools-for-java#6380]
#### Setup

IntelliJ build version: 2021.3.2 IU-213.6777.52
OS: Linux
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.61.1-2021.3

####  Describe the bug
Azure webapp deployment IDE configuration, appends new 'before launch' run maven goal (package) to existing after every run. If the maven package command requires a profile or any other arguments, this breaks the configuration.  

####  To Reproduce
customize the before launch maven package goal (add profiles), notice that an additional package goal gets added after running  

#### Exception or Stack Trace

Add the exception log and stack trace if available.

#### Screenshots

Add screenshots to help explain your problem if available.
![Screenshot from 2022-02-08 10-29-24](https://user-images.githubusercontent.com/4493756/153019668-8faffc81-ebec-4e95-9677-a5dd1f7dcfff.png)

**Comment by wangmingliang-ms** [comment]
this issue should have been fixed by 37818039d295d5c4bcefae61c56089ed9ec1d16c, can you try with the latest snapshots in the marketplace.
https://plugins.jetbrains.com/plugin/8053-azure-toolkit-for-intellij/versions/dev

**Comment by wangmingliang-ms** [comment]
close as it has been fixed since v3.69.0, you can upgrade to the latest and try. Feel free to reopen it when you encounter this error again.
