### ISSUE TITLE
While specifying Associating resources with VM during VM creation I need to specify new resource group name several times

### ISSUE THREAD

**Issue by hovsepm** [microsoft/azure-tools-for-java#64]
![image](https://cloud.githubusercontent.com/assets/7052173/23078132/4a507e4e-f4fc-11e6-8a63-95b928ab6571.png)

while in my sample it is a simple a1 name that I need to specify for storage account, it would be really painful and error prone to type in long names.

**Comment by martinsawicki** [comment]
a nice usability feature idea for the future

**Comment by andxu** [comment]
The feature will be described as "default resource group in VM shall be the same as VM"

**Comment by wangmingliang-ms** [comment]
please use the latest version
