### ISSUE TITLE
Intellij - Azure function deploy does not update host.json file

### ISSUE THREAD

**Issue by wcom939** [microsoft/azure-tools-for-java#6415]
Azure function deployment via the azure explorer does not update the host.json file of the function resulting in an error regarding extension bundles on the azure function resource.

Doing this manually using the AZ CLI for a zip file using: az functionapp deployment source config-zip results in a proper update.

**Comment by Flanker32** [comment]
@wcom939 Thanks for your report, we will investigate this issue soon.

**Comment by Flanker32** [comment]
@wcom939 Thanks for your report, I tried to deploy maven/gradle function app with host.json changes from azure explorer and it seems works fine. Could this issue be stable reproduced in your side? If so, could you please help share a demo project and related changes to reproduce this issue?
