### ISSUE TITLE
[Eclipse]Redis Cache-> Icon issue in properties windows

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#642]
RESULT:
![image](https://user-images.githubusercontent.com/22470312/27072267-7f2fbeac-5052-11e7-8916-eec79c235d77.png)

EXPECT:
![image](https://user-images.githubusercontent.com/22470312/27072280-8aadfd3e-5052-11e7-8e59-06e05415e78f.png)
@jdneo

**Comment by jdneo** [comment]
@bsaby Fixed, please help verify this issue in the new build, thanks.

**Comment by bsaby** [comment]
Test passed.
BUild used: artifacts/WindowsAzurePlugin4EJ.develop.146.06-13-2017.zip
![image](https://user-images.githubusercontent.com/22470312/27073745-850b9abc-5057-11e7-9973-9c011658fd33.png)
