### ISSUE TITLE
Azure Web App Configuration; non-canonical hostname

### ISSUE THREAD

**Issue by mounty1** [microsoft/azure-tools-for-java#6451]
Hello, I'm using the Azure Web App Configuration to deploy a Kotlin/Spring app. to an Azure instance. However, the 'canonical' hostname for the instance does not work. By this I mean that if our app. is called companyapp for example, the plugin assumes that its hostname is companyapp.azurewebsites.net but in our case (owing to network/DNS configuration) that name does not work and the site is known by ourapp.company.com.au so is there some way to override the name that the plugin uses when it deploys?

**Comment by Flanker32** [comment]
@mounty1 Thanks for your feedback. Could you please share the error stack and toolkit version if the deploy run configuration failed to complete? 
IntelliJ toolkit will call kudu api through Azure SDK for deployment, which should be `https://companyapp.scm.azurewebsites.net/`, it may not be easy to overwrite it as the url was defined in Azure SDK, refers [here](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager-appservice/src/main/java/com/azure/resourcemanager/appservice/implementation/KuduClient.java#L68). Could  this issue be resolved by set up a proxy? Azure toolkit support IntelliJ proxy configuration, please refer this [doc](https://www.jetbrains.com/help/idea/settings-http-proxy.html) for proxy configuration set up.
