### ISSUE TITLE
IntelliJ Crash When logging in to Azure

### ISSUE THREAD

**Issue by odinsonkylebonnici** [microsoft/azure-tools-for-java#6505]
Sign in to azure using the using OAuth 2.0 and device login result in a crash of the IDE

InteliJ version: 2021.3.3
Azure Toolkit for InteliJ: 3.62.-2021.
[plugins.txt](https://github.com/microsoft/azure-tools-for-java/files/8339412/plugins.txt)
[crash.txt](https://github.com/microsoft/azure-tools-for-java/files/8339413/crash.txt)
3

**Comment by odinsonkylebonnici** [comment]
Intelij support are reporting that issue is in the plugin mainly the below stack trace

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.sun.jna.Native.invokeVoid(Lcom/sun/jna/Function;JI[Ljava/lang/Object;)V+0
j  com.sun.jna.Function.invoke([Ljava/lang/Object;Ljava/lang/Class;ZI)Ljava/lang/Object;+42
j  com.sun.jna.Function.invoke(Ljava/lang/reflect/Method;[Ljava/lang/Class;Ljava/lang/Class;[Ljava/lang/Object;Ljava/util/Map;)Ljava/lang/Object;+271
j  com.sun.jna.Library$Handler.invoke(Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;)Ljava/lang/Object;+390
j  com.sun.proxy.$Proxy222.CFRelease(Lcom/sun/jna/Pointer;)V+16
j  com.microsoft.azuretools.sdkmanage.IdentityAzureManager.shallEnablePersistence()Z+10
j  com.microsoft.azuretools.sdkmanage.IdentityAzureManager.signInOAuth()Lreactor/core/publisher/Mono;+13
j  com.microsoft.intellij.actions.AzureSignInAction.lambda$doLogin$21(Lcom/intellij/openapi/progress/ProgressIndicator;)Lcom/microsoft/azuretools/authmanage/models/AuthMethodDetails;+4
j  com.microsoft.intellij.actions.AzureSignInAction$$Lambda$7334.call()Ljava/lang/Object;+4
j  com.microsoft.intellij.actions.AzureSignInAction.call(Ljava/util/concurrent/Callable;Ljava/lang/String;)Ljava/lang/Object;+76
j  com.microsoft.intellij.actions.AzureSignInAction.doLogin(Lcom/intellij/openapi/progress/ProgressIndicator;Lcom/microsoft/azure/toolkit/lib/auth/model/AuthConfiguration;)Lcom/microsoft/azuretools/authmanage/models/AuthMethodDetails;+93
j  com.microsoft.intellij.actions.AzureSignInAction.lambda$loginNonDeviceCodeSingle$16(Lcom/microsoft/azure/toolkit/lib/auth/model/AuthConfiguration;)Lcom/microsoft/azuretools/authmanage/models/AuthMethodDetails;+16
j  com.microsoft.intellij.actions.AzureSignInAction$$Lambda$7328.get()Ljava/lang/Object;+4
j  com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$0(Lrx/Emitter;Lcom/microsoft/azure/toolkit/lib/common/task/AzureTask;)V+5
j  com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager$$Lambda$4520.run()V+8
j  com.microsoft.azure.toolkit.lib.common.task.AzureTaskContext.run(Ljava/lang/Runnable;Lcom/microsoft/azure/toolkit/lib/common/task/AzureTaskContext;)V+20
j  com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$1(Lrx/Emitter;Lcom/microsoft/azure/toolkit/lib/common/task/AzureTask;Lcom/microsoft/azure/toolkit/lib/common/task/AzureTaskContext;)V+8
j  com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager$$Lambda$4324.run()V+12

**Comment by Flanker32** [comment]
@odinsonkylebonnici Thanks for your report and sorry for the trouble, the issue should be resolved in https://github.com/microsoft/azure-tools-for-java/pull/6512, we will release the fix this week.

**Comment by odinsonkylebonnici** [comment]
Thanks :) appreciate the swift action 👍 🥇

**Comment by wangmingliang-ms** [comment]
@odinsonkylebonnici the fix is shipped within the latest v3.63.0, can you try it?

**Comment by odinsonkylebonnici** [comment]
Tested and working fine thanks
