### ISSUE TITLE
Add "Copy link to portal" for resource groups

### ISSUE THREAD

**Issue by sshquack** [microsoft/azure-tools-for-java#6525]
For databases there is an option to "Open in portal"
![Screenshot 000135@2x](https://user-images.githubusercontent.com/5678459/160894385-29025a38-f3d7-4c10-8778-92228b420260.png)

Currently it is painful to navigate from the IntelliJ Azure toolkit from a resource group to the portal.
![Screenshot 000136@2x](https://user-images.githubusercontent.com/5678459/160894408-01a91f41-7add-4910-96ff-e7f3d1be58d6.png)

Many times I want to share a link to the resource group with my team and it is painful to go through 10 clicks just to copy the URL to the portal. Please add a "Copy link to portal" on right-click.

**Comment by wangmingliang-ms** [comment]
Which version are you using, can you upgrade to v3.62.0? 
`Open in Portal` was added to `Resource group`s in v3.62.0
![image](https://user-images.githubusercontent.com/69189193/160969205-c42babc8-48e1-4060-98e3-09467b12e485.png)

**Comment by sshquack** [comment]
@wangmingliang-ms Here is my version:

JetBrains Rider 2021.3.4
.NET 6.0.1
Azure Toolkit plugin 3.50.0.1314-2021.3

I don't see those options under resource groups. Can you please publish the new version for Jetbrains Rider?

https://plugins.jetbrains.com/plugin/11220-azure-toolkit-for-rider/versions

**Comment by wangmingliang-ms** [comment]
@sshquack  sorry, `azure-toolkit-for-rider` is forked from this repo but developed by JetBrains's team, can you post an issue here:
https://github.com/JetBrains/azure-tools-for-intellij

**Comment by sshquack** [comment]
Thanks @wangmingliang-ms I've requested here https://github.com/JetBrains/azure-tools-for-intellij/issues/548

Feel free to close this issue. I will create a separate feature request for "Copy link to portal"

**Comment by wangmingliang-ms** [comment]
we do have `Open in Portal`. so, I don't think `Copy link to portal` is required.
