### ISSUE TITLE
[IntelliJ2016/2017]Redis Cache: Can't show entire subscription ID in the tab [Mac]

### ISSUE THREAD

**Issue by davidliangze** [Microsoft/azure-tools-for-java#654]
Right Click a Redis Cache->Show properties.

![1](https://user-images.githubusercontent.com/26756696/27120556-a1d96fd8-5116-11e7-8533-b377b84b1c25.JPG)

**Comment by bsaby** [comment]
Build: develop 161
OS:  Linux
![image](https://user-images.githubusercontent.com/22470312/27274039-4677edda-5504-11e7-87e4-05f27508e9a4.png)

**Comment by jdneo** [comment]
@bsaby fixed, please help verify, thanks.

**Comment by bsaby** [comment]
Test passed.
Build:  dev400
