### ISSUE TITLE
[Eclipse]Application Insight: the available Application Insight can't be listed [Mac]

### ISSUE THREAD

**Issue by davidliangze** [microsoft/azure-tools-for-java#655]
Using build dev152.

Repro step:
Right click a project->Azure->Configure Application Insight;
Click Instrumentation keys.

**Expected:**
The available App Insight are listed in the table.

**Actual:**
There is no available App Insight listed.
![2](https://user-images.githubusercontent.com/26756696/27121252-14f0dc20-5119-11e7-86e4-45d3dfefe7d3.JPG)

Also repro in the released build, so **NOT a regression issue.**

**Comment by andxu** [comment]
Hi @davidliangze , I cannot reproduce this bug,  can you try it again and tell us whether it is fixed(BTW: must login to azure first, you won't see Application Insights list when you are not logged in)
![image](https://user-images.githubusercontent.com/17075863/83833382-63983b80-a71e-11ea-8f33-e037e72112b6.png)
