### ISSUE TITLE
[IntelliJ]  if you don't install scala plugin, once you click ok button, it will show restart tip.

### ISSUE THREAD

**Issue by ruoxinCheng** [Microsoft/azure-tools-for-java#658]
![image](https://user-images.githubusercontent.com/20041888/27125630-7b889424-5127-11e7-95e2-a35e804ce36e.png)

**Comment by ziyel** [comment]
@ruoxinCheng . Fixed in #670. Please help to test.

**Comment by ruoxinCheng** [comment]
Verified it.
