### ISSUE TITLE
[IntelliJ][ReportedByUser] Customer Issues I can't login to the azure tool 

### ISSUE THREAD

**Issue by moabduikea** [microsoft/azure-tools-for-java#6624]
####  Describe the bug

I can't login to azure tool in IntelliJ with any login method

**Comment by wangmingliang-ms** [comment]
is it Mac OS?
same as this issue : https://github.com/microsoft/azure-tools-for-java/issues/6576?

**Comment by moabduikea** [comment]
Yes MacOS

**Comment by moabduikea** [comment]
> is it Mac OS?
> same as this issue : #6576?

**Comment by moabduikea** [comment]
> is it Mac OS?
> same as this issue : #6576?

**Comment by moabduikea** [comment]
@wangmingliang-ms Please I need your support to solve it !

**Comment by wangmingliang-ms** [comment]
@moabduikea  did you try this temp solution?
https://github.com/microsoft/azure-tools-for-java/issues/6576#issuecomment-1106180545

**Comment by Flanker32** [comment]
@moabduikea Thanks for your report and really sorry for the issue. 
Our toolkit leverage the `Azure Identity` library for azure authentication, the official Java Support for Mac M1 architecture was recently supported in Java 17 GA, and old java version (lower than Java 17 ) are not stable on Mac M1 according to @g2vinay, you may track the origin issue here https://github.com/Azure/azure-sdk-for-java/issues/23622

As a workaround, could you please sign in azure cli first and then try azure cli authentication by open idea through bash (refers https://github.com/microsoft/azure-tools-for-java/issues/6576#issuecomment-1106180545). Besides, you may also try create a service principal and sign in with sp, you may find references in this [doc](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli)

**Comment by moabduikea** [comment]
<img width="504" alt="Screen Shot 2022-05-17 at 1 10 55 PM" src="https://user-images.githubusercontent.com/102519185/168797979-882af747-fe3e-40d7-897a-856783a4188e.png">

**Comment by Flanker32** [comment]
@moabduikea Thanks for your message and really sorry for the issue. Could you please help share the `idea.log` to us for investigation? You may get it by `Help` -> `Show Log in Explorer`, besides, could you please try `az account list --output json` in your bash and see whether this command could work?

**Comment by Flanker32** [comment]
@moabduikea Thanks a lot for your report, we have released the fix of this issue to dev channel, could you please try and see whether the issue could be reproduced? You may get the bits [here](https://plugins.jetbrains.com/plugin/8053-azure-toolkit-for-intellij/versions/dev)
