### ISSUE TITLE
[IntelliJ] There is no option 'submit spark applicaltion to HDInsight' when you create a scala project with SBT

### ISSUE THREAD

**Issue by ruoxinCheng** [Microsoft/azure-tools-for-java#665]
![image](https://user-images.githubusercontent.com/20041888/27165939-f8faa990-51c9-11e7-9f8c-30b15e3045ea.png)

**Comment by ruoxinCheng** [comment]
just it reproes on IntelliJ 2016

**Comment by ziyel** [comment]
@ruoxinCheng . Fixed in #668 .
Please help to test.

**Comment by ruoxinCheng** [comment]
Verified it.
