### ISSUE TITLE
At the last step of VM definition got "The provided location 'koreacentral' is not available for resource group. List of available regions is..."

### ISSUE THREAD

**Issue by hovsepm** [Microsoft/azure-tools-for-java#67]
Plus again top massage says Message from Azure: "null"

![image](https://cloud.githubusercontent.com/assets/7052173/23078259/ced0ebae-f4fc-11e6-9975-0d788f606813.png)

**Comment by hovsepm** [comment]
Ideally we should filter/query availability during region selection.

**Comment by martinsawicki** [comment]
anything to do left here?

**Comment by lenala** [comment]
Already fixed, now we display only storage accounts that are available to subscription.

**Comment by bsaby** [comment]
Test passed, using azure-toolkit-for-intellij.2017.191.03-31-2017.zip.
