### ISSUE TITLE
[IntelliJ2017+2016] An error occured when install plugin

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#673]
Build: Daily 39
OS: all os

Whether it is clean installed or updated, an error occured after installing the plugin.
LOG:
![image](https://user-images.githubusercontent.com/22470312/27267202-6e08421c-54d9-11e7-8fc1-f33dd2ad5824.png)

**Comment by ziyel** [comment]
The `icons` and  `hdinsight_jobview_html.zip` in `azure-toolkit-for-intellij.jar` are corrupt. And I have used the latest code in develop to build in my local, no issue found. @adashen Could you help to check if there is something wrong in build server?

![image](https://user-images.githubusercontent.com/1286176/27268234-ebb1db7c-54e0-11e7-9037-24000af3d4ff.png)

![image](https://user-images.githubusercontent.com/1286176/27268241-f34c5290-54e0-11e7-949a-c39a611e23fc.png)

**Comment by Eskibear** [comment]
I've checked the develop build, the issue occurs after commit e429f8e.  Investigating now.

@ziyel BTW I have also built the latest code in my local machine, it suffers from the same issue.

**Comment by adashen** [comment]
It may be caused by the gradle resource filter. I will have a look later

**Comment by bsaby** [comment]
Test passed on Windows/Mac/Linux.
Build used:
artifacts/azure-toolkit-for-intellij.2017.develop.161.06-19-2017.zip
artifacts/WindowsAzurePlugin4EJ.develop.161.06-19-2017.zip
