### ISSUE TITLE
[Eclipse]Rsdis Cache->Open Explorer prompt dialog issue  

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#682]
Build: Daily45
OS: Windows/Mac/Linux

Right click a Redis Cache and select Open Explorer, then a prompt dialog shown as below picture will appear.
Don't close the explorer windows, then click Open Explorer again, this prompt dialog will not appear.
![image](https://user-images.githubusercontent.com/22470312/27464276-0a76a0d0-57ff-11e7-9360-e9287dc1c01b.png)
@jdneo

**Comment by adashen** [comment]
It seems cannot connect to SSL only redis cache

**Comment by jdneo** [comment]
@bsaby Fixed, please help verify this issue in the new build, thanks.

**Comment by bsaby** [comment]
Test passed.
Build used: dev174.
