### ISSUE TITLE
API APP missing in the subscription

### ISSUE THREAD

**Issue by zeevblu** [microsoft/azure-tools-for-java#689]
I installed the new Azure Toolkit from "http://dl.microsoft.com/eclipse"
But, after I logged in to my account - the API APPs not included in the web app list. 
Before the upgrade all the API APP shown under the web apps section.

**Comment by Eskibear** [comment]
What do you mean by `API APPs`, is it `API Connection` or anything else? Please provide more details so as to figure it out. 
E.g. 
What's the precise type of those app displayed in azure portal? 
And what's your current plugin version? v3.0.4? 
Those details might help.

**Comment by adashen** [comment]
Currently azure java sdk doesn't provide a valid api to get API Apps. We will only list the web apps in the explorer

**Comment by andxu** [comment]
Wont fix since api app is out of our scope

**Comment by andxu** [comment]
Wont fix since api app is not our scope
