### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')

### ISSUE THREAD

**Issue by SagivDev** [microsoft/azure-tools-for-java#6935]
IntelliJ build version: 2022.1.4 IU-221.6008.13
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.15
Plugin version: 3.68.0-2022.1
Additional Info: Pressing the Modify Run Configuration.
Reprodcued ALWAYS, cannot modify Azure Function run configuration. I think it started after Azure plugin update
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1046,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at com.microsoft.azure.toolkit.intellij.legacy.appservice.table.AppSettingsTable.lambda$addAppSettings$5(AppSettingsTable.java:98)
	at com.microsoft.azure.toolkit.intellij.legacy.appservice.table.AppSettingsTable.addAppSettings(AppSettingsTable.java:98)
	at com.microsoft.azure.toolkit.intellij.legacy.appservice.table.AppSettingsTable.setAppSettings(AppSettingsTable.java:125)
	at com.microsoft.azure.toolkit

**Comment by Flanker32** [comment]
@SagivDev Thanks for your report and sorry for the trouble, this should be an issue of our config parse and we will fix this issue soon. As a workaround, could you please try wrap numbers in your `local.settings.json` to string and try edit the configuration again?

**Comment by SagivDev** [comment]
Thanks Liu, the workaround you suggested seems to be working.

**Comment by Flanker32** [comment]
@SagivDev The issue should be resolved in https://github.com/microsoft/azure-tools-for-java/commit/c12883669975ef7e773228def2ab2083cc297f7b, which will be included in the next stable release. Thanks for your support.
