### ISSUE TITLE
[Eclipse] Cannot show job view

### ISSUE THREAD

**Issue by ruoxinCheng** [Microsoft/azure-tools-for-java#694]
![image](https://user-images.githubusercontent.com/20041888/27622188-156915e2-5c08-11e7-940d-4c8427870be2.png)
No log.

**Comment by ziyel** [comment]
Fix in https://github.com/Microsoft/azure-tools-for-java/pull/716
@ruoxinCheng , please test in the daily build.

**Comment by ruoxinCheng** [comment]
Verified it is resolved.
