### ISSUE TITLE
[Eclipse] Can we support option to select main class name, like IntelliJ

### ISSUE THREAD

**Issue by ruoxinCheng** [Microsoft/azure-tools-for-java#698]
![image](https://user-images.githubusercontent.com/20041888/27626024-1eda1426-5c19-11e7-9a2c-9411c17d88f1.png)

**Comment by voidfunction** [comment]
Fixed. @ruoxinCheng Please verify.

**Comment by ruoxinCheng** [comment]
Verified it.
