### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Scheduler worker in group main failed with an uncaught exception java.io.FileNotFoundException: Cannot find target file: (C:\git\integration\maven\b2b\ssek\target\spring-boot-starter-parent-2.6.6.jar)

### ISSUE THREAD

**Issue by TomasFureh** [microsoft/azure-tools-for-java#7003]
Trying to deploy to Azure from IntelliJ. Works from Maven but not from Azure-tools-for-java (Azure Explorer)

IntelliJ build version: 2022.2.3 IC-222.4345.14
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.4.1
Plugin version: 3.69.0-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,2561x1401,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Scheduler worker in group main failed with an uncaught exception, throwable=java.io.FileNotFoundException: Cannot find target file: (C:\git\integration\maven\b2b\ssek\target\spring-boot-starter-parent-2.6.6.jar)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.runner.webappconfig.WebAppRunState.executeSteps(WebAppRunState.java:95)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.runner.webappconfig.WebAppRunState.executeSteps(WebAppRunState.java:68)
	at com.microsoft.azure.toolkit.intellij.legacy.common.AzureRunProfileState.lambda$execute$0(AzureRunProfileState.java:57)
```

**Comment by Flanker32** [comment]
@TomasFureh Thanks a lot for your report and really sorry for the late response. It seems that IntelliJ could not find the built jar in deployment. Could you please try adding a before launch task to build the project and see whether the issue could be resolved?

![image](https://user-images.githubusercontent.com/12445236/204551153-0d05dea4-76e6-4da9-b4f6-580550eb8809.png)

**Comment by TomasFureh** [comment]
@Flanker32 Hi thank you for looking into this. 
I once again tried deploying and now its working without the same problem.
I'm not sure but the only reason I can think of for this is that, I now remember that I have renewed my security token for our maven-repo since last time I tried to deploy using the plugin.
Appearantly I'm new to this stuff so sorry for taking your time.
