### ISSUE TITLE
[Eclipse]Redis Cache: UI issue[Mac]

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#701]
OS: Mac
Build:dev174

![image](https://user-images.githubusercontent.com/22470312/27631360-cdb6b1aa-5c2a-11e7-93a3-0cd9ce77b06e.png)
@jdneo

**Comment by jdneo** [comment]
@bsaby Fixed, please help verify this issue in the new build, thanks.

**Comment by bsaby** [comment]
Repro in daily 52.
![image](https://user-images.githubusercontent.com/22470312/27721812-b9be84a4-5d95-11e7-8fa3-2b35b86127fa.png)

**Comment by davidliangze** [comment]
Repro in daily 62.
![11](https://user-images.githubusercontent.com/26756696/28011647-a004fd56-6595-11e7-9d12-4da2a560576c.png)

**Comment by jdneo** [comment]
@bsaby Fixed, please help verify this issue in the new build, thanks.

**Comment by davidliangze** [comment]
Test passed. Please close it.
Build:  artifacts/WindowsAzurePlugin4EJ.develop.207.07-11-2017.zip
