### ISSUE TITLE
[Eclipse]Docker publish: UI issue [Mac/Windows/Linux]

### ISSUE THREAD

**Issue by davidliangze** [Microsoft/azure-tools-for-java#704]
Build: Daily 51

![2](https://user-images.githubusercontent.com/26756696/27678236-1d7a4514-5ce7-11e7-9706-5b5ac1e0ee65.png)

The dialog has **no title**, and the highlight part should specify it is to configure **resource group**.

**Comment by Eskibear** [comment]
new UI now
