### ISSUE TITLE
[Eclipse]Publish to Linux WebApp: the web page display 404[Linux]

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#707]
OS: Linux
Build:daily51

Project structure:(Dynamic web project)
![image](https://user-images.githubusercontent.com/22470312/27682233-6dd63204-5cf4-11e7-9d4f-169650f06ddf.png)

Web page:
![image](https://user-images.githubusercontent.com/22470312/27682264-8a49920a-5cf4-11e7-9976-d3c503f8ab58.png)

**Comment by Eskibear** [comment]
fixed in #706

**Comment by Eskibear** [comment]
you may verify the daily build @bsaby

**Comment by bsaby** [comment]
Test passed.
Build used: Daily 52.
