### ISSUE TITLE
The location dropdown in the 'Create Docker Host' dialog in IntelliJ is using Azure regions and not the user-friendly ones

### ISSUE THREAD

**Issue by clguimanMSFT** [Microsoft/azure-tools-for-java#71]
![image](https://cloud.githubusercontent.com/assets/22645093/23078392/6a1ada0c-f4fd-11e6-9d0c-1921f8eb3d29.png)

Instead of 'eastus' it should be 'East US'. The same for all other regions

**Comment by milismsft** [comment]
Fixed (https://github.com/Microsoft/azure-tools-for-java-private/commit/d61b9f0fa3fe606fe2050673957e0ae8e38e37d2)
