### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed startRefreshLocationTimerAsync()

### ISSUE THREAD

**Issue by JoaoFeichasXOM** [microsoft/azure-tools-for-java#7123]
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed startRefreshLocationTimerAsync() - Unable to refresh database account from any location. Exception: {"ClassName":"CosmosException","userAgent":"azsdk-java-cosmos/4.38.0 MacOSX/13.0.1 JRE/17.0.5","statusCode":403,"resourceAddress":"https://cosmos-lcds-cn-data-load-southcentralus.documents.azure.com:443/","error":"{\"code\":\"Forbidden\",\"message\":\"Request originated from IP 168.181.48.244 through public internet. This is blocked by your Cosmos DB account firewall settings. More info: https://aka.ms/cosmosdb-tsg-forbidden\\r\\nActivityId: a2d4abbb-3d83-4bdf-b2f5-bcfeb65ba808, Microsoft.Azure.Documents.Common/2.14.0, StatusCode: Forbidden\",\"additionalErrorInfo\":null}","innerErrorMessage":"Request originated from IP 168.181.48.244 through public internet. This is blocked by your Cosmos DB account firewall settings. More info: https://aka.ms/cosmosdb-tsg-forbidden\r\nActivityId: a2d4abbb-3d83-4bdf-b2f5-bcfeb65ba808, Microsoft.Azure.Documents.Common/2.14.0, StatusCode: Forbidden","causeInfo":null,"responseHeaders":"{Transfer-Encoding=chunked, Strict-Transport-Security=max-age=31536000, Server=Microsoft-HTTPAPI/2.0, Content-Location=https://cosmos-lcds-cn-data-load-southcentralus.documents.azure.com/,

**Comment by Flanker32** [comment]
@JoaoFeichasXOM Thanks for your report, could you please help share the repo steps for this issue if possible? Besides, it seems to be an issue of cosmos db account firewall setting. Could you please try adding your local Ip to the firewall of your cosmos account and see whether this could help? Please refer https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-configure-firewall for more info
