### ISSUE TITLE
[IntelliJ] After uninstalling scala plugin and reinstall, it cannot detect scala already installed

### ISSUE THREAD

**Issue by ruoxinCheng** [Microsoft/azure-tools-for-java#714]
1. Open Intellij with any project
2. uninstall scala plugin 
3. reinstall it and restart
it shows no scala SDK, pls setup.
![image](https://user-images.githubusercontent.com/20041888/27727562-93f14f7e-5db1-11e7-8fc9-91568a67458e.png)

**Comment by ruoxinCheng** [comment]
Create new project , it still repro.

**Comment by ruoxinCheng** [comment]
before uninstalling scala plugin, I update Scala plugin. Then uninstall, reinstall.
current, It relates to update scala plugin. because,  local run and cluster run  all failed with SBT scala application. Maven application still work.

**Comment by ruoxinCheng** [comment]
It just only repros on IntelliJ2017

**Comment by ruoxinCheng** [comment]
Submit job to cluster also failed on IntelliJ2016

**Comment by ziyel** [comment]
@ruoxinCheng , I have reproduced the issue via below steps.
1. Open Intellij with any project
2. uninstall scala plugin
3. reinstall it and restart

But I cannot reproduce the issue when `Create new project`.

**Comment by ziyel** [comment]
I have reproduced the issue via below steps as well.
1. Create a scala sbt project with `scala plugin`.
![image](https://user-images.githubusercontent.com/1286176/27784158-bc7dcf6a-600b-11e7-9367-a5332c4c4454.png)
2. Reinstall the scala plugin.

There will come up error `No Scala SDK in module`.

Actually the hdinsight plugin create the sbt project in the some logic with scala plugin. Just call the funciton in scala plugin.

The workaround is click the `Setup Scala SDK` link and set up the suitable version of scala sdk.
![image](https://user-images.githubusercontent.com/1286176/27784359-5ca6ecf6-600c-11e7-802a-a54760f4b598.png)

**Comment by ziyel** [comment]
@ruoxinCheng Fix in #724 . Please test in daily build.

**Comment by ruoxinCheng** [comment]
Verified it.
