### ISSUE TITLE
[IntelliJ][ReportedByUser] Azure Function Deployment Not Working from IntelliJ

### ISSUE THREAD

**Issue by jkim34** [microsoft/azure-tools-for-java#7251]
Setup / Pre-requisite
-----------------------
![image](https://user-images.githubusercontent.com/27513386/215301115-c8766bd6-9903-4baf-8684-a9a816b5f0ad.png)

OS: Windows 11
Plugin version: 3.63.1-2021.2

Describe the bug
-------------------
When I deploy function, it runs forever. I've been waiting for now almost an hour, thinking that this particular one takes longer time.
No logs, activity, or events showing me what is going on behind the scene.

Screen shot as below:
![image](https://user-images.githubusercontent.com/27513386/215300946-4d9638fb-2c4c-4526-8f91-c6cd30d45e58.png)

To Reproduce
---------------
Follow the instruction here:
https://learn.microsoft.com/en-us/azure/azure-functions/functions-create-maven-intellij

**Comment by jkim34** [comment]
Tested with latest product, but still the same result. 
- IntelliJ: IntelliJ IDEA 2022.3.2 (Community Edition)
- Plugin: Azure Tool 3.72.0

One thing to note: I've modified the settings to use non-default region (e.g. WUS to EUS, etc.)

**Comment by Flanker32** [comment]
@jkim34 Thanks for your report and sorry for the trouble, we will investigate this issue soon. By the way, did you use proxy in Intellij or system?

**Comment by jkim34** [comment]
> @jkim34 Thanks for your report and sorry for the trouble, we will investigate this issue soon. By the way, did you use proxy in Intellij or system?

Thanks so much for looking into it!
In terms of deployment from local, there is no proxy.

**Comment by jkim34** [comment]
@Flanker32 This one may be tough one to figure out. BUT after spending several hours, I've managed to deploy.
It seems that this bug has to do with issue I raised in StackOverflow below:
https://stackoverflow.com/questions/75273041/deploying-azure-function-from-intellij-removes-all-app-settings

With app settings configured correctly from my local, issue seems to be gone. I'll continue to monitor and see if it reoccurs, but to free-up your time, feel free to close this ticket for now, unless you think this can be fixed once-and-for-all :)
Thanks so much for your attention on this matter!

**Comment by Flanker32** [comment]
> @Flanker32 This one may be tough one to figure out. BUT after spending several hours, I've managed to deploy. It seems that this bug has to do with issue I raised in StackOverflow below: https://stackoverflow.com/questions/75273041/deploying-azure-function-from-intellij-removes-all-app-settings
> 
> With app settings configured correctly from my local, issue seems to be gone. I'll continue to monitor and see if it reoccurs, but to free-up your time, feel free to close this ticket for now, unless you think this can be fixed once-and-for-all :) Thanks so much for your attention on this matter!

@jkim34 Thanks a lot for your efforts and sorry for the confusion! IntelliJ toolkit will read your remote azure app settings and show in deployment dialog, modifications here will be applied to Azure after deployment. I'll close the issue for now, feel free to re-open the issue once you have any more questions~
