### ISSUE TITLE
`corelibs.log` duplicates all the logs from the IDE

### ISSUE THREAD

**Issue by ForNeVeR** [microsoft/azure-tools-for-java#7272]
In a fork repository, we have [an issue reported by a user](https://github.com/JetBrains/azure-tools-for-intellij/issues/657).

The report is that the `corelibs.log` file grows infinitely (and was over 400 GB at the moment of the report).

One possible reason for this is that [IntelliJ platform has recently migrated from log4j to java.util.logging](https://blog.jetbrains.com/platform/2022/02/removing-log4j-from-the-intellij-platform/), and the plugin seems to be using the same java.util.logging package for its own purposes.

IntelliJ tends to log _a lot_ of stuff sometimes (though 400 GB was unprecedented before now), and thus has defined some rolling parameters for its log file: by default, [there will be up to 12 files of up to 10 MB in size](https://github.com/JetBrains/intellij-community/blob/fab6d931f166c7407a70ba326a847464ea49d074/platform/util/src/com/intellij/openapi/diagnostic/JulLogger.java#L148-L159).

Azure Tools for Java currently adds a new handler to the root logger, and causes everything logged in IntelliJ to also be written to the `corelibs.log`, except there are no rolling settings defined:
https://github.com/microsoft/azure-tools-for-java/blob/7be83b1562f1bbbc378d855dd85d17d6ae061bc7/PluginsAndFeatures/azure-toolkit-for-eclipse/com.microsoft.azuretools.core/src/com/microsoft/azuretools/core/Activator.java#L181-L186

We'd recommend the Azure Toolkit for IntelliJ to avoid additional root logger configuration: either specify custom loggers and only configure them, or just use the IDE log for your purposes.

**Comment by wangmingliang-ms** [comment]
@ForNeVeR  thanks for reporting this problem to us. 
That code has a long history, but we very much agree with you that we should avoid adding root logger configuration.
I added a [commit](https://github.com/microsoft/azure-tools-for-java/commit/4549b702ac03a81df5f030d666fd492db9884b9c) to remove them.
