### ISSUE TITLE
Create VM Flow -> Custom image -> Publisher drop down does not offer typing.

### ISSUE THREAD

**Issue by anudeepsharma** [microsoft/azure-tools-for-java#73]

**Comment by Flanker32** [comment]
The drop list for publisher may contains many items and no way to filter it by typing
![image](https://user-images.githubusercontent.com/12445236/84472188-687a6380-acb9-11ea-9a5e-2df6c26b6439.png)

**Comment by andxu** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/17075863/144176363-dfe773f6-a03e-452b-895c-9d1ed5af6f64.png)
