### ISSUE TITLE
[IntelliJ] clicking run button have no react after configuration

### ISSUE THREAD

**Issue by ruoxinCheng** [Microsoft/azure-tools-for-java#730]
![image](https://user-images.githubusercontent.com/20041888/27849805-7e58c866-6182-11e7-9c2c-d036dc2bb25b.png)

**Comment by wezhang** [comment]
Reproed, the build is done, but not job submission.

**Comment by wezhang** [comment]
Since the 'Run' action is different than 'Submit the job' action, we need to define it clear firstly.

**Comment by wezhang** [comment]
We can use 'Run' as submitting the job, and 'Stop' as disconnect the log receiving from the job, not stopping it.

**Comment by wezhang** [comment]
Fixed by #1123

**Comment by ruoxinCheng** [comment]
Verified it.
