### ISSUE TITLE
[IntelliJ][ReportedByUser] Customer Issues

### ISSUE THREAD

**Issue by bbm5265** [microsoft/azure-tools-for-java#7307]
#### Setup

IntelliJ build version: 2022.3.1 IC-223.8214.52
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.5
Plugin version: 3.72.0-2022.3

####  Describe the bug

A clear and concise description of what the bug is, including expected behavior and actual behavior

####  To Reproduce

Steps to reproduce the bug

#### Exception or Stack Trace

Add the exception log and stack trace if available.

#### Screenshots

Add screenshots to help explain your problem if available.

**Comment by bbm5265** [comment]
Code will compile but will not run unless signed into Azure. My project isn't even connected to my Azure SQL database.

**Comment by Flanker32** [comment]
@bbm5265 Thanks for your report and sorry for the trouble. Is there any resource connection created by mistake in your project? You may manage your connection in Azure connection view (`View` -> `Tool Windows` -> `Resource Connections`).

If this did not resolve your issues, could you please help provide the error stacks or a demo project for us to investigate the issue? Many thanks!
