### ISSUE TITLE
Settings not being picked up from local.settings.json while debugging in Intellij Idea

### ISSUE THREAD

**Issue by puneetpawaia** [microsoft/azure-tools-for-java#7377]
Hi,
I am using Intellij Idea version 22.3.3 and developing an Azure Function in Java. The root folder of the the project contains the local.settings.json file. But when I make any changes to this file, like updating a vaule or adding any new setting, it is not being picked up in the debugging session. I am using Azurite for the local storage emulation. 
How can I get this working?
Thanks

**Comment by Flanker32** [comment]
@puneetpawaia Thanks for your report, you may set app settings for function local run in the run configuration of IntelliJ toolkit (You may also get it by right click your module, Azure -> Run Function), here is the screen shot.

![image](https://user-images.githubusercontent.com/12445236/224520638-51863821-4236-42b2-af54-1fa6b10b1682.png)

By default Azure toolkit will read your `local.settings.json` when create run configuration, you may also click the import button to import your app settings in `local.settings.json` to toolkit run configuration

**Comment by puneetpawaia** [comment]
Thanks. This works for me.
