### ISSUE TITLE
Cannot list service instances of Azure Spring Apps

### ISSUE THREAD

**Issue by moarychan** [microsoft/azure-tools-for-java#7396]
When signing in to the Azure Explorer with Azure Cli, select the using subscription,there's no any the service instances of Azure Spring Apps listed, then refresh the Spring Apps manually, still nothing, and the below error message will be shown:
```console
Azure: Failed to preload Spring Appss, resource provider 'Microsoft.AppPlatform' failed to return collection response for type 'Spring'.
```

![image](https://user-images.githubusercontent.com/19926623/225549461-e983c348-1109-4ac0-8f80-4c65ca422b1e.png)

Tool version: `3.70.1-2022.1`
Idea version: `2022.1.4 Ultimate Edition`

**Comment by wangmingliang-ms** [comment]
thanks for reporting this error to us, @moarychan 
This is a server-side problem, our service team fixed it yesterday. Can you try again?

**Comment by moarychan** [comment]
Still error
![image](https://user-images.githubusercontent.com/19926623/225872352-b0455879-de22-4d7d-af91-26058c81d7f6.png)

**Comment by wangmingliang-ms** [comment]
It seems you are using an internal test env, the fix may not have been applied to your environment. your teammate will explain it to you.
