### ISSUE TITLE
The default storage account name in 'Create Docker Host' may contain dashes (IntelliJ)

### ISSUE THREAD

**Issue by clguimanMSFT** [Microsoft/azure-tools-for-java#74]
![image](https://cloud.githubusercontent.com/assets/22645093/23078661/652df0be-f4fe-11e6-95de-5f94679e847e.png)
If the Web App has dashes the default storage account will have dashes. Those aren't allowed for strorage account names

**Comment by milismsft** [comment]
Should be fixed in the latest plugin.
