### ISSUE TITLE
Azure Data Lake Tools for Visual Studio Fails

### ISSUE THREAD

**Issue by philipr88** [microsoft/azure-tools-for-java#741]
Hi, I am trying to use the Azure DL tools for VS to create a DL project, but it keeps failing with the following message:

An unhandled exception of type 'System.Xml.XmlException' occurred in System.Xml.dll

Additional information: For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.

I've tried to update the tools but am also running into issues. Inside of VS, in the extensions and updates list I see Azure DL tools for VS, but I can't uninstall it (greyed out).

If I select check for updates on the tools -> data lake -> check for updates then it fails as well and VS crashes. Any idea on the issue here?

**Comment by t-rufang** [comment]
The issue is not related to this repo. We have forwarded your request to VS Azure Data Lake team.

**Comment by yanancai** [comment]
@philipr88 , are you using VS 2015, 2017 or 2019? 
If you are using VS 2015, you can find the lasted Azure Data Lake Tools for VS here: http://aka.ms/adltoolsvs
If you are using VS 2017 or 2019, you can find the lasted Azure Data Lake Tools for VS here: https://marketplace.visualstudio.com/items?itemName=ADLTools.AzureDataLakeandStreamAnalyticsTools

If you still have this issue after upgrading, can you share your script with me? My email is yanacai@microsoft.com.
