### ISSUE TITLE
LongMixin.java

### ISSUE THREAD

**Issue by jayjieh** [microsoft/azure-tools-for-java#7423]
IntelliJ build version: 2022.3.3 IU-223.8836.41
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.74.1-2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,6,6,1922x1153,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.AssertionError: 1

**Comment by wangmingliang-ms** [comment]
Thank you very much for reporting the issue, but the information provided is too little, so that we have no way to find the root of the problem or reproduce it, can you provide more information? For example, a more complete exception stacktrace?
