### ISSUE TITLE
[Eclipse]Redis Cache: invalid resource group name issue

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#746]
Create a Redis Cache with new resource group
Resouce group name is invalid

**1.Creation failed.**
![image](https://user-images.githubusercontent.com/22470312/28008752-5c1e5f74-658b-11e7-8248-de03418420cd.png)
![image](https://user-images.githubusercontent.com/22470312/28008754-5ed6e6fa-658b-11e7-9241-892df20b02a8.png)
![image](https://user-images.githubusercontent.com/22470312/28008756-60c0f7d0-658b-11e7-9c8d-c3877196ada3.png)

**2.Creation successful**
![image](https://user-images.githubusercontent.com/22470312/28008759-62c560de-658b-11e7-8923-e4ddab649fd2.png)
![image](https://user-images.githubusercontent.com/22470312/28008780-77281c9c-658b-11e7-871e-181b29f89132.png)

**EXPEXT:**
![image](https://user-images.githubusercontent.com/22470312/28008762-66e1aaa6-658b-11e7-91a2-890bca98b909.png)
@jdneo

**Comment by bsaby** [comment]
In Intellij, 
Type a invalid resource name: eg cache```
Click OK
The dialog will close directly and no error message prompt.

**Comment by jdneo** [comment]
@bsaby Fixed, please help verify it in the new build, thanks.

**Comment by bsaby** [comment]
Test passed. 
Build: dev321
**Eclipse**
![image](https://user-images.githubusercontent.com/22470312/29441447-fa496488-83fd-11e7-9b7c-66a7bf74be6d.png)
**IntelliJ**
![image](https://user-images.githubusercontent.com/22470312/29441510-5619a8e0-83fe-11e7-914f-a507526b26ba.png)
