### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Can't get synchronizer

### ISSUE THREAD

**Issue by christian-matzat-gcx** [microsoft/azure-tools-for-java#7476]
IntelliJ build version: 2023.1 IU-231.8109.175
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.75.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2560x1354,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Can't get synchronizer
	at com.jetbrains.rdserver.codeInsight.hint.BeHintBuilder.build(BeHintBuilder.kt:107)
```

**Comment by wangmingliang-ms** [comment]
Thank you very much for reporting the issue, but the information provided is too little, we have no way to find the root of the problem or reproduce it, can you provide more information? For example, a more complete exception stacktrace?
