### ISSUE TITLE
[Eclipse]Icon issue for  Publish to Web App on Linux 

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#748]
The icon background color should not be white.

![image](https://user-images.githubusercontent.com/22470312/28011010-763e81ba-6593-11e7-854c-904246367e27.png)
@Eskibear

**Comment by Eskibear** [comment]
please verify latest develop build

**Comment by bsaby** [comment]
Test passed.
BUild used: artifacts/WindowsAzurePlugin4EJ.develop.207.07-11-2017.zip
![image](https://user-images.githubusercontent.com/22470312/28059844-141957b0-6658-11e7-9690-c193a9ac240f.png)
