### ISSUE TITLE
[Eclipse]Publish to Web App on Linux: UI issue for Refresh List 

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#749]
BUild: Daily62
Mac
![image](https://user-images.githubusercontent.com/22470312/28011166-f3dfe71c-6593-11e7-9c5b-2d4bcaf194aa.png)
Linux
![image](https://user-images.githubusercontent.com/22470312/28011167-f57d9844-6593-11e7-80f5-dddb403c46a0.png)
@Eskibear

**Comment by Eskibear** [comment]
please verify latest develop build

**Comment by bsaby** [comment]
Test passed.
Build used; dev207
