### ISSUE TITLE
WebApps list table cells are editable

### ISSUE THREAD

**Issue by lenala** [Microsoft/azure-tools-for-java#75]
Right click on J2EE project ->Azure-> Publish as Azure Web App.
The table containing webapps list is editable. 
![image](https://cloud.githubusercontent.com/assets/6208231/23078608/3c8468be-f4fe-11e6-98d2-f929078ecca6.png)

**Comment by bsaby** [comment]
Test passed inartifacts/azure-toolkit-for-intellij.234.zip.
And WebApps list table cells are not editable.
