### ISSUE TITLE
[Eclipse]Publish to Web App on Linux: refresh list issue

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#750]
Build:daily63
When you manually refresh the list, a link appears in the Azure activity log
![image](https://user-images.githubusercontent.com/22470312/28047201-1b1b18ba-661b-11e7-8628-fa4cc11e26f7.png)
@Eskibear

**Comment by Eskibear** [comment]
please verify latest develop build

**Comment by bsaby** [comment]
Test passed.
Build used: dev207
