### ISSUE TITLE
[IntelliJ2017+2016]Redis Cache explorer: font size issue

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#751]
BUild:daily63
OS: all
1. The font size in the explorer is larger than the other fonts in the plugin.
2. The value font of the string type is different from other fonts
![image](https://user-images.githubusercontent.com/22470312/28052667-e5b33468-663e-11e7-8cf6-a4d3203df711.png)
@jdneo

**Comment by jdneo** [comment]
@bsaby Fixed, please help verify it in the new build, thanks!

**Comment by bsaby** [comment]
Test passed.
BUild used:
artifacts/azure-toolkit-for-intellij.2016.develop.206.07-11-2017.zip
artifacts/azure-toolkit-for-intellij.2017.develop.206.07-11-2017.zip
