### ISSUE TITLE
[IntelliJ][RL] Azure Intellij Plugin is keep on loading the resources but not completing.

### ISSUE THREAD

**Issue by LOKITHRAJ** [microsoft/azure-tools-for-java#7516]
#### Setup

IntelliJ build version: 2023.1.1 IU-231.8770.65
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.76.0-2023.1

####  Describe the bug

Azure IntelIj Plugin is not  loading the resources.

It was working well last well, but now it has failed.

![Screenshot 2023-05-06 at 10 14 23 PM](https://user-images.githubusercontent.com/9805877/236636646-995c66f7-1c4b-4f03-a66f-9a03680e4a66.png)
![Screenshot 2023-05-06 at 10 14 56 PM](https://user-images.githubusercontent.com/9805877/236636664-aaa3a5d3-6224-4884-936b-cf8f0d2045b0.png)

**Comment by LOKITHRAJ** [comment]
Azure: authentication ation... take moretime and never ends.

**Comment by Flanker32** [comment]
@LOKITHRAJ Thanks for your report and sorry for the trouble. Did you use Mac with intel chips or M1/2? Could you please help share your idea.log to help us better investigate this issue? 

As a workaround, could you please try other authentication methods like `OAuth` or `Azure Cli`, if it failed with JNA exception, could you please try disable authentication cache (Settings -> Tools -> Azure -> Uncheck `Enable authentication cache`) and try again?

**Comment by wangmingliang-ms** [comment]
Hi, @LOKITHRAJ, we released a hotfix today, can you upgrade the plugin the v3.76.1 and try again.

----
This bug currently only occurs on macOS machines using Intel chips. According to the information obtained, this error is related to a certain underlying lib related to Netty. We recently upgraded these libs, and the upgrade caused this bug.
We fixed this issue and released a hotfix: v3.76.1 by downgrading them.

Thanks.

**Comment by wangmingliang-ms** [comment]
this issue should have been fixed in later versions than v3.76.0. feel free to reopen it if you get this problem again.
