### ISSUE TITLE
[IntelliJ2017+2016]The value should not be editable

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#752]
Build: daily63
OS: all
The value table shouldn't be editable.
![image](https://user-images.githubusercontent.com/22470312/28052803-a559702a-663f-11e7-9c88-86c8ad983015.png)
@jdneo

**Comment by jdneo** [comment]
@bsaby Fixed, please help verify it in the new build, thanks!

**Comment by bsaby** [comment]
Test passed.
Build used:
artifacts/azure-toolkit-for-intellij.2016.develop.206.07-11-2017.zip
artifacts/azure-toolkit-for-intellij.2017.develop.206.07-11-2017.zip
