### ISSUE TITLE
The default vnet name in 'Create Docker Host' may be longer than the maximum allowed (IntelliJ)

### ISSUE THREAD

**Issue by clguimanMSFT** [Microsoft/azure-tools-for-java#76]
![image](https://cloud.githubusercontent.com/assets/22645093/23078715/a1257fc4-f4fe-11e6-8a9b-a4cf98bb00ca.png)

If the web app name is too long the vnet name will be too long. The default value should always be valid

**Comment by milismsft** [comment]
Fixed in the latest plugin.
