### ISSUE TITLE
Reformat Code does not work any longer

### ISSUE THREAD

**Issue by ghost** [microsoft/azure-tools-for-java#7602]
Reformat code is no longer working if the plugin is installed.

After removal the Intellij functionality is working again. Google Code Formatter is used.

* IntelliJ IDEA 2023.1.2 (Ultimate Edition)
* JVM Runtime 10.0.6+10
* Azure Toolkit for IntelliJ 3.77.0-2023.1
* google-java-format 1.16.0.2

**Comment by Xaseron** [comment]
I have the same problem and had to remove the plugin. Please fix it asap.

**Comment by Flanker32** [comment]
@gschmidt-nordlb @Xaseron Thanks a lot for your report and sorry for the trouble. I tried to reproduce this issue in my machine but the google code formatter seems works fine with azure toolkit. Could you please help provide some more info like a demo project or related error stack traces?

**Comment by Xaseron** [comment]
There is no error in the logs if you click reformat code on a folder nothing happens. Normally you would get a popup:
![grafik](https://github.com/microsoft/azure-tools-for-java/assets/1352894/6953b6d2-4593-4ae2-ac8e-af7f93b05a45)

**Comment by coding-jj** [comment]
The Intellij include formatter isn't working too.
I'm using a MacBook.

Just right click on a project File in the File Tree on the left side and choose "Reformat Code" from the context menu. The reformatter in the code with Option+Command+L (Windows: Ctrl+Alt+L) is still working.

**Comment by M4rcDev** [comment]
I can confirm the same behaviour. Im not using any third party code formatter.

When I right click on a Folder and select "Reformat Code" a popup should appear with Options:
![image](https://github.com/microsoft/azure-tools-for-java/assets/19869755/51e798f7-a6fb-4b77-99b0-44f4f7914c93)

It works without the Azure plugin installed. But when I install the Azure plugin, it no longer works. No popup appears.
Formatting the code in a single file in the code editor works. Formatting multiple files via the right-click context menu no longer works.

**Comment by Flanker32** [comment]
@gschmidt-nordlb @Xaseron @M4rcDev @coding-jj Thanks a lot for your message and help and really sorry for this trouble. The issue should be resolved in https://github.com/microsoft/azure-tools-for-java/pull/7740/commits/c0f65be72e75e19916c9b7c03e114fc136d75c57 and will be release soon. Will update here once the fix is released.
