### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Network failure java.net.UnknownHostException: cos-tccc-udp-dev-01-37-eastus2.documents.azure.com

### ISSUE THREAD

**Issue by willpeterson** [microsoft/azure-tools-for-java#7618]
IntelliJ build version: 2022.3.3 IU-223.8836.41
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.76.1-2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1578x1025,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarUtil$3@22588138,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Network failure, throwable=java.net.UnknownHostException: cos-tccc-udp-dev-01-37-eastus2.documents.azure.com
	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:801)
```

**Comment by Flanker32** [comment]
@willpeterson Thanks for your report and sorry for the late response, it seems to be an issue of network. Please check whether related resources exists and restart the toolkit. Please feel free to re-open the issue once it could still be reproduced.
