### ISSUE TITLE
Azure Login Fails

### ISSUE THREAD

**Issue by vardan3dtuning** [microsoft/azure-tools-for-java#7646]
Hello,
I'm trying to login to azure but with no success. 
On Intellij IDEA I **open tools > azur > azure sign in**, then I select **OAuth 2.0** in the popup window and select **sign in**,  browser opens Microsoft Azure sign-in page, I sign-in , then opens up a prompt **this is a non-secure form**, I select **send** , a message shows up in the browser **Authentication complete. You can close the browser and return to the application.**, however in intellij Idea this error occurs.

```
Azure: Failed to login with (OAUTH2), you are not signed-in or there are no subscriptions in your current Account.
Call Stack:
● Login with (OAUTH2)
● Sign in to Azure
```
I'm definitely signed in and I have subscriptions in my current account and I have the latest plugin version I just downloaded and installed it.

![image](https://github.com/microsoft/azure-tools-for-java/assets/49686907/42550cb3-a97e-49fe-a25a-aaee9a20a17e)
![image](https://github.com/microsoft/azure-tools-for-java/assets/49686907/727ee801-bb03-4a4f-850f-b4ec91371c11)
![image](https://github.com/microsoft/azure-tools-for-java/assets/49686907/8c2e8102-7b8e-48c0-bd25-1326d99e6b0b)
![image](https://github.com/microsoft/azure-tools-for-java/assets/49686907/621220f2-122d-49c3-98f3-ca890efa6c22)

IntelliJ build version: 2023.1
OS: Mac OS X 12.6.3 (Monterey)

Is there any idea why this is happening and how to solve it? 
Thanks in advance.

**Comment by Flanker32** [comment]
@vardan3dtuning Thanks for your report and sorry for the trouble. So is this issue has been addressed now? If not, this might be an issue of azure authentication library, could you please try disable the authentication cache (IntelliJ IDEA Settings -> Tools -> Azure -> Uncheck `Enable Authentication Cache`) and try again? Thanks again for your support.
