### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Catch java.lang.UnsupportedOperationException: Unsupported node type

### ISSUE THREAD

**Issue by david-zellmer** [microsoft/azure-tools-for-java#7652]
IntelliJ build version: 2022.2.3 IC-222.4345.14
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.4.1
Plugin version: 3.74.1-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1920x1055,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarUtil$3@308898ef,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Catch, throwable=java.lang.UnsupportedOperationException: Unsupported node type! DeferredIconRequest (id = 65baseIcon = RowIconModel (subNodes = [CompositionIconModel (subNodes = [RowIconModel (subNodes = [ImageIcon

**Comment by Flanker32** [comment]
[IntelliJ][ReportedByUser] Uncaught Exception Catch java.lang.UnsupportedOperationException: Unsupported node type! DeferredIconRequest (id = 65baseIcon = RowIconModel (subNodes = [CompositionIconModel (subNodes = [RowIconModel (subNodes = [ImageIconModel (wrapper = ImageIconInternWrapper (identity = 142path = "fileTypes/javaClass.svg"sources = [IconSource (path = "fileTypes/javaClass.svg"body = [B@36547)IconSource (path = "fileTypes/javaClass@2x.svg"body = <null>)IconSource (path = "fileTypes/javaClass_dark.svg"body = <null>)... and 1 more]))])])]))

**Comment by Flanker32** [comment]
@david-zellmer Thanks for your report and sorry for the trouble. Could this issue be stable reproduced? If so, could you please provide the steps to repro this issue?
