### ISSUE TITLE
[IntelliJ] After updating to 2017.2 - IntelliJ wants to to install very old plugin. 

### ISSUE THREAD

**Issue by vladimir-shcherbakov** [Microsoft/azure-tools-for-java#768]
![image](https://user-images.githubusercontent.com/6579928/28430492-936bfdcc-6d35-11e7-97ed-ec1c52700aeb.png)

![image](https://user-images.githubusercontent.com/6579928/28430337-01e6b612-6d35-11e7-8fcd-0e89b8e32888.png)

**Comment by adashen** [comment]
Noticed, we will release a new version next week to support 2017.2 and the problem should be solved

**Comment by adashen** [comment]
new version released for 2017.2, the issue should already be fixed
