### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.AssertionError: 3 : child= 'FilePartNode

### ISSUE THREAD

**Issue by atufashabnam** [microsoft/azure-tools-for-java#7705]
IntelliJ build version: 2023.1.1 IU-231.8770.65
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.78.1-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1440x900,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.AssertionError: 3 : child=

**Comment by Flanker32** [comment]
@atufashabnam Thanks a lot for your report and sorry for the late response. Could you please help share a bit more info for this issue? Could this issue be stable reproduced? If so, could you please help share us the repo steps for this issue?
