### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.AssertionError: 3

### ISSUE THREAD

**Issue by Sugilal** [microsoft/azure-tools-for-java#7709]
IntelliJ build version: 2022.3.1 IC-223.8214.52
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.5
Plugin version: 3.77.0-2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.AssertionErr

**Comment by Flanker32** [comment]
@Sugilal Thanks for your report and sorry for the late response. Could you please help share a bit more info for this issue? Could this issue be stable reproduced? If so, could you please help share the repro steps?
