### ISSUE TITLE
[Eclipse]Redis cache: UI issue[Linux]

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#772]
Build: daily76
OS: Linux
![image](https://user-images.githubusercontent.com/22470312/28510480-3cb20b18-707b-11e7-8b47-9553fd41479a.png)
@jdneo

**Comment by jdneo** [comment]
Hi @bsaby , could you please provide the Linux version and Eclipse version?

**Comment by bsaby** [comment]
Can not repro in dev435, so close this issue.
