### ISSUE TITLE
[Eclipse]Docker Container: The Finish button should not be available without WebApp selection

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#773]
![image](https://user-images.githubusercontent.com/22470312/28512948-a2bc3522-7086-11e7-9d78-09c8f6b80934.png)

![image](https://user-images.githubusercontent.com/22470312/28512967-b320074a-7086-11e7-817d-57e33e8e9899.png)
![image](https://user-images.githubusercontent.com/22470312/28513006-debba292-7086-11e7-9593-e588af9c529d.png)
![image](https://user-images.githubusercontent.com/22470312/28513008-e0a5e81a-7086-11e7-9e72-264d20538143.png)
![image](https://user-images.githubusercontent.com/22470312/28513515-06b57e74-7089-11e7-8d47-65548c4d85c7.png)
![image](https://user-images.githubusercontent.com/22470312/28513520-0935d6f8-7089-11e7-917d-e8bd147af2cf.png)

@Eskibear

**Comment by Eskibear** [comment]
please verify @bsaby

**Comment by bsaby** [comment]
Test passed.
Build used: dev223
