### ISSUE TITLE
[IntelliJ][ReportedByUser][feature-request] Feature Request

### ISSUE THREAD

**Issue by pieterdb** [microsoft/azure-tools-for-java#7797]
####  Is your feature request related to a problem? Please describe
yes, when I write pojo mapper/converter classes, i have to write out all the property setters with getters
It is unfortunately company policy to declare these mapping statements explicitly rather than use a Mapper framerwork like Orika, Dozer, Struct etc. 
This is a fairly boilerplate and repetitive dev process. 
I am frequently frustrated that I have to use the autocomplete to verify what properties i have yet to map and if I have missed one or not

####  Describe the solution you'd like
1. the autocomplete should indicate if in my chained statement, certain methods/properties have already been mapped. The autocomplete should intelligently lower the order of properties that have clearly already been used within the statement OR visually represent (perhaps grey out?) the setters that have already been used. 

2. provide a "best effort" mapper autowriter for beans who's properties are identically or similarly named. 

both options together would be ideal. 

#### Additional context
For example:

new Foo()
  .setX(bar.getX())
  .setY(bar.getY())
  .set ... autocomplete here should not suggest X, Y etc properties that have already been mapped because if you have more than 10 it becomes difficult to see if you've missed one.

**Comment by wangmingliang-ms** [comment]
the issue has nothing to do with Azure toolkit for IntelliJ, you should report it to IntelliJ IDEA.
