### ISSUE TITLE
Spark Assembly and document update

### ISSUE THREAD

**Issue by donamk** [Microsoft/azure-tools-for-java#780]
When I create an application with the tempalte, HDInsight > Spark on HDInsight (Scala) or Spark on HDInsight Cluster Run Sample (Scala) and No Spark SDK, show me error with link https://github.com/MSBigDataTeam/AzureHDInsightIntelliJTools/releases/v1.0.0.

It looks fine and quite convenient however, the link did not reflect actual HDI Spark version.
![bc1067b0-1bb2-11e7-9670-f82fe42fbdcc](https://user-images.githubusercontent.com/816815/28560229-274c6d9e-715d-11e7-9a39-da27890715cf.png)
As you can see, spark-assembly-2.0.0-hadoop2.7.0-SNAPSHOT.jar should update to 2.0.2 and Spark 2.1.0 is totally missing.

Could you explain where can I find the assembly file in HDI? 
How can I get it? (Please tell me the location... :broken_heart::cry:)

I create same issuse on AzureHDInsightIntelliJTools but no one reply.
If the AzureHDInsightIntelliJTools  repo is abandoned, the assembly link should be change to azure-tools-for-java repo.

Also related document doesn't reflect current Azure Toolkit for IntelliJ IDEA. 
For example, in the https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-apache-spark-intellij-tool-plugin document, Run a local Spark Scala application section, the screenshot have Spark version selection box, however current version shows Scala SDK and Spark SDK.

It would be great the above things to update.

**Comment by donamk** [comment]
This issue was happen because of IntelliJ IDEA 2017.2 didn't allow you to install latest version. This issue can merge with #768

**Comment by jdneo** [comment]
Duplicated with #768
