### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalArgumentException: Invalid offsets: start=1224; end=1240; document length=740

### ISSUE THREAD

**Issue by rranjangupta** [microsoft/azure-tools-for-java#7824]
IntelliJ build version: 2023.2.1 IC-232.9559.62
OS: Linux
JDK: JetBrains s.r.o. 17.0.8
Plugin version: 3.79.1-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,37,1920x1001,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalArgumentException: Invalid offsets: start=1224; end=1240; document length=740
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:53)
```

**Comment by Flanker32** [comment]
@rranjangupta Thank you for reporting this issue and we are sorry for the inconvenience. To help us troubleshoot this issue, could you please provide some more details, such as the steps that you followed to encounter this issue?
