### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.AssertionError

### ISSUE THREAD

**Issue by nabinwbut1** [microsoft/azure-tools-for-java#7872]
IntelliJ build version: 2023.2.1 IU-232.9559.62
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.8
Plugin version: 3.80.1-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1512x945,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.As

**Comment by Flanker32** [comment]
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.AssertionError: 2 : child= 'FilePartNode: 'RrgPo'; children: 4; fs=LocalFileSystem; myFileOrUrl=file:///Users/nabinmondal/Documents/Tekion/gitLab/part_ro_sale/pricing-fulfilment-availabilty/src/main/java/com/tekion/part/service/purchase/service/RrgPo; class java.lang.String'; child.nameEqualTo(nameId)=false; child.getClass()=class com.intellij.openapi.vfs.impl.FilePartNode; child.nameId=11325418; child.getName()='RrgPo'; nameId=9916; name='rrgPo'; compare(child) = 0; UrlPart.nameEquals: true; name.equals(child.getName())=false; file=file:///Users/nabinmondal/Documents/Tekion/gitLab/part_ro_sale/pricing-fulfilment-availabilty/src/main/java/com/tekion/part/service/purchase/service/rrgPo; this.isCaseSensitive()=false

**Comment by Flanker32** [comment]
@nabinwbut1 Thank you for reporting this issue and we are sorry for the inconvenience. To help us troubleshoot this issue, could you please provide some more details, such as the steps that you followed to encounter this issue?
