### ISSUE TITLE
Create VM Flow -> When existing Availability set is selected it show a GUID rather than name.

### ISSUE THREAD

**Issue by anudeepsharma** [Microsoft/azure-tools-for-java#79]
1. Click Create VM.
2. Fill information on 1st, 2nd and 3rd page, to reach associated resources page.
3. When you select an existing availability set it shows GUID rather than name.

Expected  - When an availability set is selected then it's name should be shown.

**Comment by lenala** [comment]
Fixed, please verify.

**Comment by bsaby** [comment]
Test passed in artifacts/azure-toolkit-for-intellij.234.zip 
When an availability set is selected then it's name should be shown.
But I can't create vm successfully
![image](https://cloud.githubusercontent.com/assets/22470312/23538399/d72e546e-000d-11e7-97e7-7406a309c5c7.png)

**Comment by lenala** [comment]
This should be fixed by recent dependencies cleanup, please verify.

**Comment by songkaiape** [comment]
Not repro. Verified this issue  in azure-toolkit-for-intellij.14.zip
