### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed CompositeException (13 nested):

### ISSUE THREAD

**Issue by afrotransact** [microsoft/azure-tools-for-java#7985]
IntelliJ build version: 2023.2.4 IU-232.10203.10
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.8.1
Plugin version: 3.81.1-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1920x1032,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=CompositeException (13 nested):
------------------------------
```

**Comment by Flanker32** [comment]
@afrotransact Thank you for reporting this issue and we are sorry for the inconvenience and late response. To help us troubleshoot this issue, could you please provide some more details, such as the steps that you followed to encounter this issue?
