### ISSUE TITLE
Unable to authenticate to Team Services. Verify your network connection, credentials for you microsoft account and try "sign in" again

### ISSUE THREAD

**Issue by SiNewman07** [microsoft/azure-tools-for-java#7988]
When trying to clone a repo in intellij and the repo exists in an Azure Dev Ops environment I am now getting an error stating Unable to authenticate to Team Services. Verify your network connection, credentials for you microsoft account and try "sign in" again

I am unable to correctly log into to my company work account using micorsoft authentication.

This previously worked in older versions of intellij but since upgrading to the below or above it no longer allows a clone to a repo to happen correctly. Is there an outstanding issue with the plugins provided for azure within intellij??

IntelliJ IDEA 2023.1.2 (Community Edition)
Build #IC-231.9011.34, built on May 16, 2023
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.github.copilot (1.3.3.3572)
    Docker (231.9011.41)
    com.microsoft.tooling.msservices.intellij.azure (3.81.1-2023.1)
    com.microsoft.vso.idea (1.162.2)

Kotlin: 231-1.8.21-IJ9011.34

**Comment by wangmingliang-ms** [comment]
`Azure toolkit for IntelliJ` (for Azure cloud, https://azure.microsoft.com) and `Azure DevOps` are two different plugins. 
as your issue happens at cloning repos hosted in Azure DevOps, I believe it's related to plugin `Azure DevOps`.

**Comment by SiNewman07** [comment]
I have both of the above mentioned plugins installed and enabled. No matter what repo I try and clone it fails to acknowledge my account. 

On initial clone im prompted with a follow instructions to complete sing in box, this gives me a device login web address as well as a code, I put this in but the next step fails to recognise my account and sign in fails. This happens for multiple engineers as well. 

To get around the issue I have found that if I use Microsoft VS Code and sign in here it works correctly, with all the same or similar extensions enabled. I can clone correctly and pick and assign to my account correctly. I can clone the repo to the same project folder as my others previously done through intellij.

I can then open the repo and use it within intellij. 

The issue with intellij seems fairly new and is it possibly related to its build. I'm unable to go back older intellijs to test this due to other company policies. The workaround is okay, but the issue with sign in and cloning in one place in intellij is an annoying problem.

**Comment by wangmingliang-ms** [comment]
@SiNewman07  thanks for your detailed explanation. and sorry for the unpleasant experience. 

let's figure out which plugin caused the problem first, is it possible for you to share the screenshot of the sign-in box (please mask any secrets)?
the sign-in dialog of `Azure Toolkit for IntelliJ` plugin is
![image](https://github.com/microsoft/azure-tools-for-java/assets/69189193/9abf088d-a4d6-408c-ac8a-d875ae043cae)
is it what you saw? otherwise, I believe you should report the issue in `Azure DevOps` repo: https://github.com/microsoft/azure-devops-intellij

**Comment by SiNewman07** [comment]
When I try to clone a repo inside intellij I don't get the above. I am unable to upload an image due to my companys security policy so it is being blocked.

But the sign in I get is not the one above, its from Azure Devops Services, its a tab next to Team Foundation Server. This pops up when trying to clone an ADO repo.

I then have a URL and a passcode that I need to go to, this then before would allow me to select my microsoft company account email and login, however it now stops that and gives a different pop up, I can put in my email address but it then states  sign in failed as my company needs to allow access. From what they have looked at in all the config it is okay, and I can performe the task okay and sign in in Ms VS Code.

**Comment by wangmingliang-ms** [comment]
@SiNewman07 then I believe this issue is caused by plugin `Azure DevOps`, it's not maintained by us. Can you report the issue here: https://github.com/microsoft/azure-devops-intellij ?

**Comment by wangmingliang-ms** [comment]
not related.

**Comment by SiNewman07** [comment]
OK thanks, will report the same at the above.
