### ISSUE TITLE
if you delete the auth file and you have set azure sign in as automated it won't let you continue till it gets back the auth file

### ISSUE THREAD

**Issue by arroyc** [Microsoft/azure-tools-for-java#80]
![image](https://cloud.githubusercontent.com/assets/16231002/23078850/37ea6672-f4ff-11e6-9755-9cbbf24c83c8.png)

**Comment by vladimir-shcherbakov** [comment]
Fixed.

**Comment by bsaby** [comment]
Test passed in artifacts/azure-toolkit-for-intellij.197.zip and closed.
