### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.AssertionError

### ISSUE THREAD

**Issue by marcus-hei** [microsoft/azure-tools-for-java#8016]
IntelliJ build version: 2023.2.3 IU-232.10072.27
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.8.1
Plugin version: 3.82.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2560x1415,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```

**Comment by Flanker32** [comment]
@marcus-hei Thanks for your feedback and we apologize for the trouble and late response. To help us troubleshoot this issue, could you please provide some more details, such as the steps that you followed to encounter this issue?
