### ISSUE TITLE
when running an azure functions - import app settings does not list local.settings.json in the dropdown menu

### ISSUE THREAD

**Issue by gsfrrrr** [microsoft/azure-tools-for-java#8061]
when running an azure functions - import app settings does not list local.settings.json in the dropdown menu, so settings cannot be imported at all.. manual setting change does work properly.
![settings_bug](https://github.com/microsoft/azure-tools-for-java/assets/62307661/754a016f-b886-451f-b912-7d500cd9c932)

**Comment by Flanker32** [comment]
@gsfrrrr Thanks for your report. Could you please help share the toolkit version and the runtime (intellij version/os) info for your machine? It could be better if you could share us a demo project for investigation.

**Comment by gsfrrrr** [comment]
@Flanker32  I upgraded to latest versions, to make sure I am not chasing an old issue -

Intellij:
IntelliJ IDEA 2023.3.1 (Ultimate Edition)
Build #IU-233.11799.300, built on December 12, 2023
Runtime version: 17.0.9+7-b1087.7 amd64

Azure Toolkit for IntelliJ:
3.83.0-2023.3

This is happening to a few other developers as well, it starts out ok, and we seem to lose the import functionality at some point.
Any help/workaround will be appreciated.

**Comment by Flanker32** [comment]
> @Flanker32 I upgraded to latest versions, to make sure I am not chasing an old issue -
> 
> Intellij: IntelliJ IDEA 2023.3.1 (Ultimate Edition) Build #IU-233.11799.300, built on December 12, 2023 Runtime version: 17.0.9+7-b1087.7 amd64
> 
> Azure Toolkit for IntelliJ: 3.83.0-2023.3
> 
> This is happening to a few other developers as well, it starts out ok, and we seem to lose the import functionality at some point. Any help/workaround will be appreciated.

@gsfrrrr Thanks a lot for your report, could you please help check whether there are any exceptions logged in idea.log? You may find them in `Help` -> `Open Log in Editor`. 

Meanwhile, could you please try sign-out and see whether this helps? As we will also load app settings from your remote function app which may breaks for service side issue and block the loading function.

**Comment by gsfrrrr** [comment]
Hi @Flanker32,

There are no relevant exceptions in the log.
I have signed in and out of azure many times - this has been going on for over a month..

**Comment by Flanker32** [comment]
@gsfrrrr Thanks for your report and sorry for the trouble. We will support select `local.settings.json` file in our next release, will update here once the feature is done.
