### ISSUE TITLE
[HDInsight] Test fail because of java.net.BindException: Address already in use

### ISSUE THREAD

**Issue by jdneo** [Microsoft/azure-tools-for-java#819]
Log: http://vscjavaci.cloudapp.net/job/AzureToolsManager_PR/524/consoleFull

**Comment by wezhang** [comment]
We can keep an eyes on this to see if it hits very frequently or not.

**Comment by wezhang** [comment]
Close it because it does not always hit.

**Comment by jdneo** [comment]
@wezhang Maybe #911 can also be closed?
