### ISSUE TITLE
Create a Docker Host - Should disable "Finish" button after it is clicked

### ISSUE THREAD

**Issue by anuchandy** [Microsoft/azure-tools-for-java#82]
After providing necessary inputs to "Create Docker Host" and clicking "Finish" button, it takes few seconds to close this dialog and return to "New Deployment of a Docker Container on Azure", we might want to disable the "Finish" button after clicking it.

**Comment by milismsft** [comment]
"Finish" is disabled if an input error is detected at this time... Can you add the repro steps for the issue you saw?

**Comment by bsaby** [comment]
Not repro in artifacts/azure-toolkit-for-intellij.225.zip
