### ISSUE TITLE
Error text for IDE failures it badly formatted 

### ISSUE THREAD

**Issue by hovsepm** [Microsoft/azure-tools-for-java#83]
![image](https://cloud.githubusercontent.com/assets/7052173/23079054/0b9268b2-f500-11e6-943b-0ddb19bad0c4.png)

Following part of the message is broken:

```
<br>(Message from Azure: "null")
```

**Comment by lenala** [comment]
Error reporting fixed, please verify. Looks like the way to repro exception would be to try use new resource group with the name of existing resource group

**Comment by bsaby** [comment]
Test passed, using azure-toolkit-for-intellij.2017.208.04-04-2017.zip.
![image](https://cloud.githubusercontent.com/assets/22470312/24686902/3dd1e0f6-19e9-11e7-9538-81bfbbc2547b.png)
