### ISSUE TITLE
[IntelliJ] Deploy to Azure -> The URL is not displayed

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#830]
IU + IC
No URL displays for the first deploy
![image](https://user-images.githubusercontent.com/22470312/29013202-0e20be94-7b74-11e7-8778-18e8ba670055.png)

**Comment by jdneo** [comment]
@bsaby Fixed, please help verify it in the new build, thanks.

**Comment by bsaby** [comment]
Test passed;
Build: dev272
