### ISSUE TITLE
[IntelliJ] Deploy to Azure -> No auto-refresh after deploying

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#832]
No auto-refresh after deploying new Web App for App service list
No auto-refresh after deploying new Web App for Web App list in Azure explorer
![image](https://user-images.githubusercontent.com/22470312/29013298-ae50c6c0-7b74-11e7-9c19-03f958beb9e2.png)
![image](https://user-images.githubusercontent.com/22470312/29013305-b74ef972-7b74-11e7-8c5f-7d5c04798c77.png)

**Comment by jdneo** [comment]
@bsaby Fixed, please help verify this in the new build, thanks.

**Comment by bsaby** [comment]
Test passed.
Build: Dev282
