### ISSUE TITLE
[IntelliJ] Deploy to Azure -> After choosing the Web App, the warning message is still shown

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#833]
After choosing the Web App, the warning message is still shown.
Unless you click the Maven window at the bottom of the dialog box

![image](https://user-images.githubusercontent.com/22470312/29013645-efe291c0-7b76-11e7-8620-818f56e169fb.png)

**Comment by jdneo** [comment]
@bsaby Fixed, please help verify in the new build, thanks.

**Comment by bsaby** [comment]
Test passed.
Build: dev268
