### ISSUE TITLE
Azure Explorer still shows missing WebApps in IntelliJ

### ISSUE THREAD

**Issue by clguimanMSFT** [Microsoft/azure-tools-for-java#84]
I deployed a WebApp, then removed it from the portal. The Azure Explorer still shows it even if I refresh
![image](https://cloud.githubusercontent.com/assets/22645093/23079277/18e216ec-f501-11e6-8215-4845e3ea287f.png)

![image](https://cloud.githubusercontent.com/assets/22645093/23079291/278b7468-f501-11e6-9f59-fbea67ef2f30.png)

**Comment by martinsawicki** [comment]
make sure Refresh forces a true refresh from Azure and cache gets refreshed

**Comment by lenala** [comment]
This was fixed, please verify.

**Comment by bsaby** [comment]
Test passed in artifacts/azure-toolkit-for-intellij.103.zip.
