### ISSUE TITLE
Thank you for your help!

### ISSUE THREAD

**Issue by rafaelldi** [microsoft/azure-tools-for-java#8420]
Hello! We published a [blog post](https://blog.jetbrains.com/dotnet/2024/05/14/azure-toolkit-for-rider-v4-0-preview-request-for-feedback/) about the new preview version of the plugin for Rider and mentioned the help of your team.

> We’d like to thank the Azure Toolkit for IntelliJ team at Microsoft for their help and collaboration!

Thank you very much! Without your help this would not be possible.

**Comment by wangmingliang-ms** [comment]
thanks @rafaelldi , very happy to hear that.
