### ISSUE TITLE
Should allow plan and webapp in different groups

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#846]
Both publish as web app on Linux and Run on Web App
The existing plan list should show all available plans under the current subscription, not under the current resource group
![image](https://user-images.githubusercontent.com/22470312/29107266-e7ac7d2c-7d0b-11e7-9966-a016d6e4c439.png)

**Comment by adashen** [comment]
The recommend practice is to  have webap appserviceplan in the same resource group. So we can leave it as it is now. And track whether there is complain about it.

**Comment by adashen** [comment]
fixed on webapp

**Comment by adashen** [comment]
There is a bug in sdk [https://github.com/Azure/azure-sdk-for-java/issues/1861 ](url) . The issue has dependency on the sdk bug

**Comment by Eskibear** [comment]
external dependency resolved in https://github.com/Azure/azure-sdk-for-java/issues/1861

**Comment by Eskibear** [comment]
close, won't fix.
