### ISSUE TITLE
[Eclipse]publish as Web App on Linux->A Sign-in error message appears during deployment

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#847]
1. Interactive sign-in
2. publish with existing Web App on Linux
3. A Sign-in error message appears during deployment

The error window can not be closed because the deploy process is in progress.
![image](https://user-images.githubusercontent.com/22470312/29107552-4c7fe0a8-7d0d-11e7-82cd-c5af0abb6d1b.png)

**Comment by Eskibear** [comment]
@bsaby , fixed in #892 , please verify, including following scenario:
step 1: interactive login 
step 2: uncheck some of the subscription (make sure not to select all of them).
step 3: publish to existing web app on linux

**Comment by bsaby** [comment]
Test passed.
BUild: dev291
