### ISSUE TITLE
Azure Web App Container SpringBoot with Java 17 crashing due SIGSEGV (0xb) at pc=0x0000747cfcf91ef4 net.bytebuddy

### ISSUE THREAD

**Issue by pedrolozano** [microsoft/azure-tools-for-java#8472]
Hello i am using this parent pom : 

<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.3.0-SNAPSHOT</version>
		<relativePath /> 
</parent>

And is crashing while startup , can you please guide me on which is the supported parent pom from Azure running on Java 17 ?
please . Thanks in advance !

**Comment by pedrolozano** [comment]
[azureLog05072024.log](https://github.com/user-attachments/files/16112275/azureLog05072024.log)

**Comment by wangmingliang-ms** [comment]
@pedrolozano do you use Azure AppService? Can you please report this issue to Azure App Service team? It seems this issue has nothing to do with "azure toolkit".

**Comment by pedrolozano** [comment]
yes @wangmingliang-ms  i couldn´t find any other place to report it, so i gave a try here but thanks for respond i will try to find the right place , thanks !
