### ISSUE TITLE
Azure Cloud Shell support

### ISSUE THREAD

**Issue by rafaelldi** [microsoft/azure-tools-for-java#8477]
Hello! We've implemented an Azure Cloud Shell basic support [in our plugin](https://github.com/JetBrains/azure-tools-for-intellij/tree/develop/PluginsAndFeatures/azure-toolkit-for-rider/azure-intellij-plugin-cloud-shell). If you want, I can send a PR to your plugin with this module. But one possible downside for you might be that it is written in kotlin

**Comment by wangmingliang-ms** [comment]
@rafaelldi  That's super great! We want it. Kotlin is not a problem. thanks!
