### ISSUE TITLE
[IntelliJ]Azure Web App(Container)-> Null issue for publishing with new App service plan

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#849]
Build: develop260
1.  Create new Web App with new service plan
2. Then publish

![image](https://user-images.githubusercontent.com/22470312/29110625-d1ca9940-7d19-11e7-9595-d277e621ec7a.png)
![image](https://user-images.githubusercontent.com/22470312/29110629-d4121354-7d19-11e7-940a-4e5d2de4e710.png)

**Comment by Eskibear** [comment]
cannot fix now due to SDK issue, SDK throw exceptions with emtpy message. Wait for SDK update.

**Comment by Eskibear** [comment]
Will fix by upgrading SDK in next sprint.
ref:
https://github.com/Azure/azure-sdk-for-java/issues/1858

**Comment by Eskibear** [comment]
might be fixed in #944 , please help to verify. @bsaby

**Comment by Eskibear** [comment]
Try providing some illegal values, e.g. to create web app using an existing name.

**Comment by bsaby** [comment]
Null issue is not repro.
