### ISSUE TITLE
No way to delete entire resource group from the Azure explorer 

### ISSUE THREAD

**Issue by hovsepm** [microsoft/azure-tools-for-java#85]
Very inconvenient. While specifying VM I declared a lot of resources like Network, Storage account etc. Now if I want to clean all that I've created in that resource group I have to go to portal.

**Comment by martinsawicki** [comment]
future feature maybe

**Comment by andxu** [comment]
This is already supported
![image](https://user-images.githubusercontent.com/17075863/84867248-6b0bfd00-b0ad-11ea-8811-be9c4536523c.png)
