### ISSUE TITLE
Add 'Open in Browser' context menu option in the Azure Explorer for Docker Hosts

### ISSUE THREAD

**Issue by clguimanMSFT** [Microsoft/azure-tools-for-java#86]
![image](https://cloud.githubusercontent.com/assets/22645093/23079442/c9c604dc-f501-11e6-8504-1b552dbe8a58.png)
This type of context menu option exists for the WebApp

**Comment by milismsft** [comment]
Fixed in the latest version. The "Open in Browser" option is added to the Docker container item.
