### ISSUE TITLE
vm credentials and ssh should be mutually exclusive

### ISSUE THREAD

**Issue by arroyc** [Microsoft/azure-tools-for-java#87]
both are enabled, default ssh should be none, or if ssh is auto-generate enabled then vm credentials should be disabled at the same time

![image](https://cloud.githubusercontent.com/assets/16231002/23079673/bbb88eb8-f502-11e6-962b-ce2d5c4e8356.png)

**Comment by milismsft** [comment]
Both are actually supported at the same time; you can specify a password and SSH keys when creating the Azure virtual machine (Azure Portal only allows one and that is wrong).
