### ISSUE TITLE
Run Web App(Linux) -> Can't select the first Web App in the  list to publish

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#879]
Choose the first Web App of existing list, the error message is still shown, unless select another one.
![image](https://user-images.githubusercontent.com/22470312/29205011-dc1d0d3a-7eac-11e7-9cc3-83340414d184.png)

**Comment by bsaby** [comment]
Repro.
Build: dev291
![image](https://user-images.githubusercontent.com/22470312/29260282-74fb6e84-80fb-11e7-851e-b801cdf343e6.png)

**Comment by Eskibear** [comment]
updated, please verify @bsaby

**Comment by bsaby** [comment]
Test passed.
Build: dev294
