### ISSUE TITLE
Deploy to docker host fails with not very helpful message

### ISSUE THREAD

**Issue by jianghaolu** [Microsoft/azure-tools-for-java#88]
I think I probably filled in some wrong params for docker host, and then I get an error message as this:
<img width="1280" alt="screen shot 2017-02-17 at 11 16 38 am" src="https://cloud.githubusercontent.com/assets/2320445/23079678/be634342-f502-11e6-9ff8-5edc85629853.png">

**Comment by milismsft** [comment]
The error is triggered when we try to load the Docker host details but for some reason (missing keyvault, wrong credentials) we don't have the VM login credentials. I temporarily fixed this in the Docker Host refresh routine so the error is not triggered but there's still a pending work item to add proper support for the user to specify the login credentials in case he selects that particular Docker host for deployment.
