### ISSUE TITLE
Run on Web App(Linux) -> An error occurs when deploying a  Web project

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#880]
Repro steps:
1. New a Web project
2. Configure a Artifact
3. Right click project and select Add Docker Support
4. Then select Run on Web App(Linux)
5. New a App Service or Choose an existing one
6. Run it

![image](https://user-images.githubusercontent.com/22470312/29205126-7e5c77d4-7ead-11e7-8979-401044e43897.png)

**Comment by Eskibear** [comment]
please verify it.

**Comment by bsaby** [comment]
Test passed.
BUild: dev291
