### ISSUE TITLE
Run on Web App(Linux) -> The deployed page does not display properly

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#883]
OS:
Mac/Linux
All deployment pages are not displaying properly。
![image](https://user-images.githubusercontent.com/22470312/29207641-8f65ffa8-7eb9-11e7-8b65-5bebc428796a.png)
![image](https://user-images.githubusercontent.com/22470312/29207643-910cb6bc-7eb9-11e7-8d9e-941836edb52b.png)
![image](https://user-images.githubusercontent.com/22470312/29207646-941e7b9c-7eb9-11e7-95e7-eff64862d7fb.png)

**Comment by Eskibear** [comment]
fixed in #890
