### ISSUE TITLE
[Eclipse]Install Missing plugin

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#886]
Repro steps:

1. Install Azure Toolkit for Eclipse
2. Restart Eclipse

![image](https://user-images.githubusercontent.com/22470312/29255691-4142d430-80d6-11e7-9d43-95ae8a14a01c.png)

**Comment by adashen** [comment]
@wezhang, Can you have a look at this bug. It block the installation if eclipse plugin.

**Comment by wezhang** [comment]
add @djlan , he is investigating Eclipse scala-ide now.

**Comment by djlan** [comment]
This is by design. Our plugin reference scala. By clicking ok, it will start to install scala automatically and avoid the complex configuration process.

**Comment by adashen** [comment]
@djlan The error box seems like an error or exception. User may feel uncomfortable of it. Can we have a more better design of it?

**Comment by djlan** [comment]
1. Updated it to informational dialog
2. Made the description more clear
Please do let me know if there is any other suggestion.

**Comment by bsaby** [comment]
**RESULT:**
Both default installation with all components and custom installation without installing hdinsight will prompt to install the missing plugin
**EXPEXT:**
Don't prompt to install missing plugin when custom installation without installing hdinsight 

![image](https://user-images.githubusercontent.com/22470312/29300997-bd0af176-81ab-11e7-8c13-ee0dcb8b9ce9.png)

**Comment by djlan** [comment]
Just realized that this is a bug but not a regression. This issue has been there. When users do not install HDInsight, the window will still pop up before.

**Comment by djlan** [comment]
Fixing it.

**Comment by djlan** [comment]
Fixed

**Comment by bsaby** [comment]
Test passed.
The message dialog box will pop up only if the user installs hdinsight.
Build :dev309
