### ISSUE TITLE
[IntelliJ] Feature reqeust: concatenate ACR server URL and image&tag

### ISSUE THREAD

**Issue by zhzy0077** [Microsoft/azure-tools-for-java#889]
Now, we need to specify image and tag box like: `zhiyuan.azurecr.io/image:1.0.0`.
Obviously, it is the concatenation of Server URL, image name, tag.
I wonder if it is better to just specify `<image name>:<tag>` in this box and concatenation can be performed before push to ACR.

**Comment by adashen** [comment]
Add validation now to give hint about the image name format. #896
