### ISSUE TITLE
[IntelliJ] stdout cannot show normally after submission

### ISSUE THREAD

**Issue by ruoxinCheng** [microsoft/azure-tools-for-java#894]
I can see stdout from this, https://spark2withblob.azurehdinsight.net/yarnui/jobhistory/logs/10.0.0.4/port/30050/container_e10_1500294782280_0258_01_000001/container_e10_1500294782280_0258_01_000001/livy 

But was empty in job view of Intellij
![image](https://user-images.githubusercontent.com/20041888/29259721-3ffd0020-80f7-11e7-8a7b-7250336295a0.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748189
