### ISSUE TITLE
[Suggestion] Create Docker Host - Make use of virtual machine CreateAsync resource streaming

### ISSUE THREAD

**Issue by anuchandy** [microsoft/azure-tools-for-java#90]
We call VirtualMachine.Create which internally creates related resources. If we use VirtualMachine.CreateAsync then we get notification as each resource gets created, if this info can be
propagated to below UI then it would be cool.

![deployingtoazure](https://cloud.githubusercontent.com/assets/1471612/23079817/59b44c74-f503-11e6-9bf4-4ffb5384c046.png)

**Comment by milismsft** [comment]
The resource group and virtual network are created before we call VirtualMachine.create() so only the storage account (if new), the public ip and the network interface are actually created as part of it. 

I agree it will be a nice thing to have. This functionality is currently implemented outside of the UI so it is common to all the plugins and extensions so it;s a little more difficult to implement the status reporting as resources get created.

**Comment by martinsawicki** [comment]
future maybe

**Comment by Flanker32** [comment]
We have deprecated the support for docker host, close this issue.
