### ISSUE TITLE
Prerequesites needs an update for subscription requirements

### ISSUE THREAD

**Issue by shaunm-msft** [microsoft/azure-tools-for-java#93]
https://docs.microsoft.com/en-us/azure/azure-toolkit-for-eclipse-creating-a-hello-world-application

This topic requires ASM enabled on the subscription. If it is not enabled, then the instructions don't work. The prerequisites should mention this requirement. 

The newer mechanism is through ARM. For ARM-only subscriptions, we should refer people to this topic instead: https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-eclipse-create-hello-world-web-app

**Comment by martinsawicki** [comment]
We're removing ASM support anyway, so those docs will be removed --- AFTER v3.0 ships

**Comment by selvasingh** [comment]
We need to document the removal of ASM support services in dev experiences. @rmcmurray

**Comment by Flanker32** [comment]
@selvasingh The outdated document has been removed now, shall we close this issue?
