### ISSUE TITLE
[IntelliJ] Run on Web App(Linux)->Issue for creating a Web App using existing name

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#947]
Repro Steps:
1. first, deploy a new Web App(Linux) using below configuration:

![image](https://user-images.githubusercontent.com/22470312/29696820-da581f18-897d-11e7-896e-9d6e6d34e9d8.png)

2. deploy a new Web App(Linux) using above existing configuration again -> **no error pops up**
![image](https://user-images.githubusercontent.com/22470312/29696828-de8316ce-897d-11e7-804a-5e6172299fea.png)
![image](https://user-images.githubusercontent.com/22470312/29663080-187496d2-88fc-11e7-82d9-a557969df359.png)

3. deploy a new Web App(Linux) using below configuration -> **no error pops up**
![image](https://user-images.githubusercontent.com/22470312/29663112-42b2a056-88fc-11e7-969d-02f38e28b3e3.png)
![image](https://user-images.githubusercontent.com/22470312/29663080-187496d2-88fc-11e7-82d9-a557969df359.png)

In addition to 2,3, any other case for creating new Web App(Linux) using the existing name will be given a error.
![image](https://user-images.githubusercontent.com/22470312/29663310-faac5b16-88fc-11e7-9cbd-18cb84c3a210.png)

**Comment by andxu** [comment]
![image](https://user-images.githubusercontent.com/17075863/84394430-8307fa80-ac2f-11ea-9518-445484fe8c54.png)

**Comment by andxu** [comment]
There seems a bug in the app name validation, any name will report "already exists", @Flanker32 please take a look.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738793

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
