### ISSUE TITLE
Change the order of web containers from lastest to previous due to customer feedback. 

### ISSUE THREAD

**Issue by Matthew-Dong** [Microsoft/azure-tools-for-java#958]
![image](https://user-images.githubusercontent.com/7653539/29802512-2ac1429a-8ca8-11e7-86de-3a12f80ce465.png)

**Comment by jdneo** [comment]
Hi @Matthew-Dong, We have already changed the web container order, and will release in this sprint.
![image](https://user-images.githubusercontent.com/6193897/29807590-357fde70-8cc7-11e7-9650-e450f74c4643.png)

**Comment by Matthew-Dong** [comment]
Great! Thanks.
