### ISSUE TITLE
[IntelliJ]Run on Web App(Linux)-> The URL provided is not consistent with the actual published URL

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#959]
1. Deploy a project to Web App on Linux
![image](https://user-images.githubusercontent.com/22470312/29806922-4180e4c4-8cc4-11e7-83b0-81f6d8564734.png)

2. Click the provided url, and the web site is wrong
![image](https://user-images.githubusercontent.com/22470312/29807032-a57a8dd6-8cc4-11e7-8a6a-9647ef8eac14.png)

3. Right click web app in Azure explorer, and find that the content is actually deployed to the root directory
![image](https://user-images.githubusercontent.com/22470312/29807035-a778b068-8cc4-11e7-9e98-44b7f0da75a9.png)

**Comment by Eskibear** [comment]
confirmed.

**Comment by bsaby** [comment]
Test passed.
BUild: daily131
