### ISSUE TITLE
Shutting down VM shows message saying VIP will be lost

### ISSUE THREAD

**Issue by anudeepsharma** [Microsoft/azure-tools-for-java#96]
We should expand VIP to at least Virtual IP, VIP is not understandable at first look.

**Comment by martinsawicki** [comment]
This shows up when you do "Shutdown" on a VM or DockerHost oin Explorer. So instead of "VIP", it should say "virtual IP address"

**Comment by lenala** [comment]
This is fixed, please verify.

**Comment by bsaby** [comment]
Test passed in artifacts/azure-toolkit-for-intellij.225.zip
