### ISSUE TITLE
[Eclispe] Publish as Azure Web App -> No entry for Spring boot project(.jar) deployment

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#963]
![image](https://user-images.githubusercontent.com/22470312/29853323-dd9f310a-8d71-11e7-9c65-0dc2cd4da749.png)
Need to check **Dynamic Web Module** manually
![image](https://user-images.githubusercontent.com/22470312/29853344-01eca4ca-8d72-11e7-9355-2a6c66b0c022.png)

**Comment by adashen** [comment]
Fixed please verify on the latest build

**Comment by bsaby** [comment]
Test passed.
BUild used: develop350
