### ISSUE TITLE
[Eclispe] [Windows]Publish as Azure Web App -> Can't deploy spring boot project

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#967]
Even if change the build path to specify the use of jdk , the spring boot [roject can not be deployed.
![image](https://user-images.githubusercontent.com/22470312/29860761-aa814362-8d99-11e7-96e8-5918bdff027f.png)
![image](https://user-images.githubusercontent.com/22470312/29860780-bca0257c-8d99-11e7-9d3d-977f374317a2.png)

**Comment by jdneo** [comment]
@bsaby Fixed, please help verify in the new build, thanks.

**Comment by bsaby** [comment]
Test passed.
Build: Dev354
