### ISSUE TITLE
[Win][IntelliJ1.7.2] Help link inside deploy web app windows returns error

### ISSUE THREAD

**Issue by JialinXin** [microsoft/azure-tools-for-java#978]
![image](https://user-images.githubusercontent.com/15338714/30012422-40c9ab58-9172-11e7-979a-c6e2afebc9f5.png)

**Comment by andxu** [comment]
The link is available: https://www.jetbrains.com/help/idea/2019.2/run-debug-configurations-dialog.html?utm_campaign=IC&utm_content=2019.2&utm_medium=link&utm_source=product

**Comment by JialinXin** [comment]
Looks good. Good to close.
