### ISSUE TITLE
[Create VM] Create storage account dialog should allow the user to select the same new RG as the VM

### ISSUE THREAD

**Issue by clguimanMSFT** [Microsoft/azure-tools-for-java#98]
When creating a VM in a new resource group the storage account creation dialog should allow you to select the same RG as the one defined for the VM. 
Currently you can just select from a list of existing RGs or create a new one. The user is already crating a new one for the VM, the same RG name should be an option

**Comment by milismsft** [comment]
The same resource group is assumed if the "New storage account" option is selected.
