### ISSUE TITLE
[Eclipse Mars] [Linux]Can't open login window

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#985]
Build: develop354
Right click Azure in Azure explorer and choose Sign In
Choose Interactive and click Sign In
Result:
No login window pops up
Expect:
![image](https://user-images.githubusercontent.com/22470312/30018218-9dfec0bc-918e-11e7-9268-5b590f149dc2.png)

Try this feature on plugin v2.9.5 and v3.0.3
After plugin installation , select Sign in, an error dialog pops up
![image](https://user-images.githubusercontent.com/22470312/30018181-7a08584e-918e-11e7-8128-2c63b1b58518.png)

**Comment by Eskibear** [comment]
should not exist in new sign-in workflow, please help to verify it.

**Comment by bsaby** [comment]
Still repro in Eclispe Mars

**Comment by Eskibear** [comment]
It seems your desktop system is GTK3 by default, and XULRunner now only supports GTK2. 
So you can add parameter in `eclipse.ini` to use GTK2 to launch eclipse.

Possible solution: add such lines before `--launcher.appendVmargs`

```
--launcher.GTK_version
2
```

![image](https://user-images.githubusercontent.com/2351748/34478071-c2772b74-efd9-11e7-91bb-6ed69986f994.png)
