### ISSUE TITLE
Once you get a docker deployment error, it stays with you forever

### ISSUE THREAD

**Issue by arroyc** [Microsoft/azure-tools-for-java#99]
this pop window doesn't go ... it stays forever
![image](https://cloud.githubusercontent.com/assets/16231002/23080622/55f905c2-f506-11e6-82bc-bd1e39258a37.png)

**Comment by milismsft** [comment]
A number of people reported the same issue/bug :-) 

the error is triggered when a potential Docker host is detected but the log in credentials are missing/invalid. Temporarily work around this issue in the latest version while there's a bigger work item to prompt the user to specify the credentials manually.
