### ISSUE TITLE
[IntelliJ]Run on Web App(Linux)-> select wrong app service plan

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#993]
1. To repro this issue we need to create at least 2 group for example agroup,bgroup All of them has a Web app (Linux) plan e.g. aaplan,bplan
2. If I save a run configuration used existed group B with bplan and  reopen it. The selected plan will change to a different one e.g. aplan. Usually it will select the plan of the first group by alphabet order.

Saved configuration
![image](https://user-images.githubusercontent.com/22470312/30055740-f13cbade-9262-11e7-8500-eee373ed3868.png)

reopened configuration
![image](https://user-images.githubusercontent.com/22470312/30055668-c410e5d0-9262-11e7-8d59-5fe4b54730c1.png)

**Comment by Eskibear** [comment]
root cause confirmed. it's due to out-of-order async callbacks.

**Comment by Flanker32** [comment]
Close as we have retired this UI and change to the slim one
