### ISSUE TITLE
[Eclispe+IntelliJ] Virtual Machines -> Finish button shouldn't be enabled when some variable is still blank

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#999]
BUild Daily137
Also repro in v3.0.7 marketplace build

![image](https://user-images.githubusercontent.com/22470312/30096627-1982ffa4-930c-11e7-890d-cac800b1cb7b.png)
Result: Click Finish button, will pops up a error dialog
![image](https://user-images.githubusercontent.com/22470312/30096777-eba44f92-930c-11e7-833f-69d8b37796c0.png)
Expect:
 Finish button shouldn't be enabled when some variable is still blank

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738796

**Comment by vscjavaci** [comment]
Close this issue since it is tracked in Azure Boards.
